# Customer Support AI Agent — TWCS

## Hiver SDE Intern Take-Home Assignment

This notebook contains the complete research, experimentation, evaluation,
and analysis pipeline for building a historically grounded AI customer-support
agent using the Customer Support on Twitter (TWCS) dataset.

### Objective

Build an AI support agent for one selected customer-support brand that can:

1. Identify the customer's intent.
2. Retrieve relevant historical support resolutions.
3. Generate a response grounded in historical evidence.
4. Decide whether the request should be automatically handled or escalated.

### Methodology

The project follows this progression:

Dataset
→ Data Quality
→ Conversation Reconstruction
→ Brand Selection
→ Intent Discovery
→ Baselines
→ Intent Classification
→ Historical Resolution Retrieval
→ Response Generation
→ Escalation Decision
→ End-to-End Agent
→ Evaluation
→ Failure Analysis

### Important Data Principle

The dataset is conversational rather than a collection of independent
classification examples. Conversation relationships will therefore be
reconstructed using the tweet relationship fields, and evaluation splits
will be performed at the conversation level to reduce leakage.

### Important Historical-Data Limitation

TWCS contains historical customer-support interactions. Historical responses
are treated as evidence of how similar issues were handled in the dataset,
not as proof of the brand's current policies or procedures.

> The goal is to build a trustworthy support-agent prototype grounded in
> historical evidence, not to claim that it represents an official brand
> support system.

In [1]:
from pathlib import Path
import sys
import platform

print("Python version :", sys.version.split()[0])
print("Platform       :", platform.platform())

Python version : 3.11.9
Platform       : Windows-10-10.0.26200-SP0

In [2]:
# Project paths
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
GOLDEN_DATA_DIR = DATA_DIR / "golden"

print("\nProject root   :", PROJECT_ROOT)
print("Raw data       :", RAW_DATA_DIR)
print("Processed data :", PROCESSED_DATA_DIR)
print("Golden data    :", GOLDEN_DATA_DIR)

Project root   : d:\BECAME_DEVELOPER\hiver-sde-ai-agent
Raw data       : d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\raw
Processed data : d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed
Golden data    : d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\golden

In [3]:
# Create directories if they do not already exist
for directory in [
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    GOLDEN_DATA_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

print("\nDirectory setup complete.")

Directory setup complete.

In [4]:
import pandas as pd
import numpy as np

from collections import Counter
from pathlib import Path

pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", 120)

print("pandas :", pd.__version__)
print("numpy  :", np.__version__)

pandas : 2.2.3
numpy  : 2.1.3

In [5]:
# Discover files available in the raw dataset directory

raw_files = sorted(
    path for path in RAW_DATA_DIR.iterdir()
    if path.is_file()
)

print(f"Files found: {len(raw_files)}\n")

for path in raw_files:
    size_mb = path.stat().st_size / (1024 ** 2)
    print(f"{path.name:<30} {size_mb:>10.2f} MB")

Files found: 1

twcs.csv                           492.58 MB

In [6]:
# Inspect a small sample of the TWCS dataset

TWCS_PATH = RAW_DATA_DIR / "twcs.csv"

sample_df = pd.read_csv(
    TWCS_PATH,
    nrows=10
)

print("Dataset file:", TWCS_PATH)
print("\nShape of sample:", sample_df.shape)
print("\nColumns:")
print(sample_df.columns.tolist())

print("\nFirst 10 rows:")
display(sample_df)

Dataset file: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\raw\twcs.csv

Shape of sample: (10, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

First 10 rows:

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further as...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your ...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,"@115712 Can you please send us a private message, so that I can gain further details about your account?","5,7",8.0
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
7,11,sprintcare,False,Tue Oct 31 22:10:35 +0000 2017,"@115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC",NaN,12.0
8,12,115713,True,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯,"11,13,14",15.0
9,15,sprintcare,False,Tue Oct 31 20:03:31 +0000 2017,"@115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further...",12,16.0

In [7]:
# Inspect data types and missing values in the sample

print("DATA TYPES")
print("=" * 50)
display(sample_df.dtypes.to_frame("dtype"))

print("\nMISSING VALUES")
print("=" * 50)

missing_summary = pd.DataFrame({
    "missing_count": sample_df.isna().sum(),
    "missing_percent": sample_df.isna().mean().mul(100).round(2)
})

display(missing_summary)

DATA TYPES
==================================================

                           dtype
tweet_id                   int64
author_id                 object
inbound                     bool
created_at                object
text                      object
response_tweet_id         object
in_response_to_tweet_id  float64

MISSING VALUES
==================================================

                         missing_count  missing_percent
tweet_id                             0              0.0
author_id                            0              0.0
inbound                              0              0.0
created_at                           0              0.0
text                                 0              0.0
response_tweet_id                    2             20.0
in_response_to_tweet_id              1             10.0

In [8]:
# Load the complete TWCS dataset with memory-conscious dtypes
TWCS_DTYPES = {
    "tweet_id": "int64",
    "author_id": "string",
    "inbound": "bool",
    "created_at": "string",
    "text": "string",
    "response_tweet_id": "string",
    "in_response_to_tweet_id": "Int64",
}

twcs = pd.read_csv(
    TWCS_PATH,
    dtype=TWCS_DTYPES,
    low_memory=False
)

print("Dataset loaded successfully!")
print(f"Rows    : {len(twcs):,}")
print(f"Columns : {len(twcs.columns)}")
print(f"Memory  : {twcs.memory_usage(deep=True).sum() / (1024**3):.2f} GB")

Dataset loaded successfully!
Rows    : 2,811,774
Columns : 7
Memory  : 1.17 GB

In [9]:
# Dataset shape
print("DATASET SHAPE")
print("=" * 60)
print(f"Rows    : {len(twcs):,}")
print(f"Columns : {len(twcs.columns)}")

DATASET SHAPE
============================================================
Rows    : 2,811,774
Columns : 7

In [10]:
# duplicate tweet_ids
duplicate_tweet_ids = twcs["tweet_id"].duplicated().sum()

print("\nDUPLICATE TWEET IDs")
print("=" * 60)
print(f"Duplicate tweet_id rows : {duplicate_tweet_ids:,}")

DUPLICATE TWEET IDs
============================================================
Duplicate tweet_id rows : 0

In [11]:
# duplicate complete rows
duplicate_rows = twcs.duplicated().sum()

print("\nDUPLICATE COMPLETE ROWS")
print("=" * 60)
print(f"Duplicate rows : {duplicate_rows:,}")

DUPLICATE COMPLETE ROWS
============================================================
Duplicate rows : 0

In [12]:
# missing values
missing_summary = pd.DataFrame({
    "missing_count": twcs.isna().sum(),
    "missing_percent": (
        twcs.isna().mean() * 100
    ).round(2)
})

print("\nMISSING VALUES")
print("=" * 60)
display(missing_summary)

MISSING VALUES
============================================================

                         missing_count  missing_percent
tweet_id                             0             0.00
author_id                            0             0.00
inbound                              0             0.00
created_at                           0             0.00
text                                 0             0.00
response_tweet_id              1040629            37.01
in_response_to_tweet_id         794335            28.25

In [13]:
# empty/whitespace-only text
empty_text = (
    twcs["text"]
    .str.strip()
    .eq("")
    .sum()
)

print("\nEMPTY TEXT")
print("=" * 60)
print(f"Empty/whitespace-only text : {empty_text:,}")

EMPTY TEXT
============================================================
Empty/whitespace-only text : 0

In [14]:
# inbound/outbound distribution
direction_summary = pd.DataFrame({
    "count": twcs["inbound"].value_counts(),
    "percentage": (
        twcs["inbound"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )
})

direction_summary.index = [
    "Customer → Company" if value else "Company → Customer"
    for value in direction_summary.index
]

print("\nMESSAGE DIRECTION")
print("=" * 60)
display(direction_summary)

MESSAGE DIRECTION
============================================================

                      count  percentage
Customer → Company  1537843       54.69
Company → Customer  1273931       45.31

In [15]:
# timestamp validation
twcs["created_at_parsed"] = pd.to_datetime(
    twcs["created_at"],
    errors="coerce",
    utc=True
)

invalid_timestamps = twcs["created_at_parsed"].isna().sum()

print("TIMESTAMP VALIDATION")
print("=" * 60)

print(f"Invalid timestamps : {invalid_timestamps:,}")

print("\nTIMESTAMP RANGE")
print("=" * 60)

print("Earliest:", twcs["created_at_parsed"].min())
print("Latest  :", twcs["created_at_parsed"].max())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\987411096.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  twcs["created_at_parsed"] = pd.to_datetime(

TIMESTAMP VALIDATION
============================================================
Invalid timestamps : 0

TIMESTAMP RANGE
============================================================
Earliest: 2008-05-08 20:13:59+00:00
Latest  : 2017-12-03 23:14:01+00:00

In [16]:
print("YEAR DISTRIBUTION")
print("=" * 60)

year_distribution = (
    twcs["created_at_parsed"]
    .dt.year
    .value_counts()
    .sort_index()
    .rename_axis("year")
    .reset_index(name="tweet_count")
)

year_distribution["percentage"] = (
    year_distribution["tweet_count"] / len(twcs) * 100
).round(2)

display(year_distribution)

YEAR DISTRIBUTION
============================================================

   year  tweet_count  percentage
0  2008            2        0.00
1  2010            7        0.00
2  2011           11        0.00
3  2012           56        0.00
4  2013           86        0.00
5  2014          199        0.01
6  2015          427        0.02
7  2016         1512        0.05
8  2017      2809474       99.92

The 2008–2016 records are unusual but legitimate timestamp values in the file; won't delete them simply because they're old. Will preserve the dataset and investigate only if they become relevant to our analysis.

Agent is grounded in historical support interactions, overwhelmingly from 2017. It should not claim to represent current brand policies.

Discover candidate support brands

In [17]:
# Company/support messages only
support_messages = twcs.loc[
    ~twcs["inbound"],
    ["author_id", "tweet_id", "text"]
].copy()

brand_volume = (
    support_messages
    .groupby("author_id")
    .agg(
        support_tweets=("tweet_id", "count"),
        unique_responses=("text", "nunique")
    )
    .sort_values("support_tweets", ascending=False)
)

brand_volume["response_uniqueness_pct"] = (
    brand_volume["unique_responses"]
    / brand_volume["support_tweets"]
    * 100
).round(2)

print(f"Unique support accounts: {len(brand_volume):,}")
print("\nTOP 30 SUPPORT ACCOUNTS")
print("=" * 80)

display(brand_volume.head(30))

Unique support accounts: 108

TOP 30 SUPPORT ACCOUNTS
================================================================================

                 support_tweets  unique_responses  response_uniqueness_pct
author_id
AmazonHelp               169840            169805                    99.98
AppleSupport             106860            106770                    99.92
Uber_Support              56270             56198                    99.87
SpotifyCares              43265             43261                    99.99
Delta                     42253             42243                    99.98
Tesco                     38573             38562                    99.97
AmericanAir               36764             36763                   100.00
TMobileHelp               34317             34303                    99.96
comcastcares              33031             33018                    99.96
British_Airways           29361             29360                   100.00
SouthwestAir              28977             28974                    99.99
VirginTrains              27817             27770                    99.83
Ask_Spectrum              25860             25816                    99.83
XboxSupport               24557             24546                    99.96
sprintcare                22381             22351                    99.87
hulu_support              21872             21871                   100.00
sainsburys                19466             19456                    99.95
GWRHelp                   19364             19358                    99.97
AskPlayStation            19098             19073                    99.87
ChipotleTweets            18749             18748                    99.99
VerizonSupport            17966             17958                    99.96
UPSHelp                   17817             17809                    99.96
ATVIAssist                17650             17640                    99.94
O2                        16212             16206                    99.96
Safaricom_Care            16077             16053                    99.85
idea_cares                15724             15656                    99.57
AskTarget                 13218             13210                    99.94
AirAsiaSupport            12829             12794                    99.73
BofA_Help                 12683             12666                    99.87
SW_Help                   12231             12162                    99.44

The response_uniqueness_pct is ~99.7–100% for essentially every major brand.

That tells almost every support tweet is textually unique.

In [18]:
brand_customer = (
    twcs.loc[
        twcs["inbound"],
        ["author_id", "tweet_id"]
    ]
    .groupby("author_id")
    .agg(
        customer_tweets=("tweet_id", "count")
    )
)

print(f"Unique customer accounts: {len(brand_customer):,}")
print("\nTOP 30 CUSTOMER ACCOUNTS")
print("=" * 80)

display(brand_customer.head(30).sort_values("customer_tweets", ascending=False))

Unique customer accounts: 702,669

TOP 30 CUSTOMER ACCOUNTS
================================================================================

           customer_tweets
author_id
10304                   10
10766                    5
11242                    5
10026                    3
10297                    2
10221                    2
10424                    2
10637                    2
10423                    2
11113                    2
10821                    2
1084                     2
10103                    2
10286                    1
10701                    1
10545                    1
10449                    1
10298                    1
100363                   1
10985                    1
10980                    1
1083                     1
11044                    1
11037                    1
11162                    1
11111                    1
111743                   1
11210                    1
11227                    1
11298                    1

In [19]:
# INVALID (not using this brand_summary)

brand_summary = brand_volume.join( 
    brand_customer,
    how="left"
)

brand_summary["customer_tweets"] = (
    brand_summary["customer_tweets"]
    .fillna(0)
    .astype("int64")
)

brand_summary["total_tweets"] = (
    brand_summary["support_tweets"] + brand_summary["customer_tweets"]
)

brand_summary["support_share_pct"] = (
    brand_summary["support_tweets"] / brand_summary["total_tweets"] * 100
).round(2)

In [20]:
print("TOP 30 SUPPORT BRANDS — CUSTOMER + SUPPORT VOLUME")
print("=" * 100)

display(
    brand_summary[
        [
            "support_tweets",
            "customer_tweets",
            "total_tweets",
            "support_share_pct"
        ]
    ].head(30)
)

TOP 30 SUPPORT BRANDS — CUSTOMER + SUPPORT VOLUME
====================================================================================================

,support_tweets,customer_tweets,total_tweets,support_share_pct
author_id,,,,
AmazonHelp,169840,0,169840,100.0
AppleSupport,106860,0,106860,100.0
Uber_Support,56270,0,56270,100.0
SpotifyCares,43265,0,43265,100.0
Delta,42253,0,42253,100.0
Tesco,38573,0,38573,100.0
AmericanAir,36764,0,36764,100.0
TMobileHelp,34317,0,34317,100.0
comcastcares,33031,0,33031,100.0
British_Airways,29361,0,29361,100.0
SouthwestAir,28977,0,28977,100.0
VirginTrains,27817,0,27817,100.0
Ask_Spectrum,25860,0,25860,100.0
XboxSupport,24557,0,24557,100.0
sprintcare,22381,0,22381,100.0
hulu_support,21872,0,21872,100.0
sainsburys,19466,0,19466,100.0
GWRHelp,19364,0,19364,100.0
AskPlayStation,19098,0,19098,100.0
ChipotleTweets,18749,0,18749,100.0
VerizonSupport,17966,0,17966,100.0
UPSHelp,17817,0,17817,100.0
ATVIAssist,17650,0,17650,100.0
O2,16212,0,16212,100.0
Safaricom_Care,16077,0,16077,100.0
idea_cares,15724,0,15724,100.0
AskTarget,13218,0,13218,100.0
AirAsiaSupport,12829,0,12829,100.0
BofA_Help,12683,0,12683,100.0
SW_Help,12231,0,12231,100.0

customer_tweets are 0 -> cannot connect customers to brands through author_id directly

should not use this brand_summary result in analysis

In [21]:
# conversation linking
support_tweet_lookup = (
    twcs.loc[
        ~twcs["inbound"],
        ["tweet_id", "author_id"]
    ]
    .rename(columns={"author_id": "support_account"})
    .set_index("tweet_id")
)

print("Support tweets indexed :", f"{len(support_tweet_lookup):,}")
print("Unique support accounts:", f"{support_tweet_lookup['support_account'].nunique():,}")

print("\nSample lookup:")
display(support_tweet_lookup.head(10))

Support tweets indexed : 1,273,931
Unique support accounts: 108

Sample lookup:

         support_account
tweet_id
1             sprintcare
4             sprintcare
6             sprintcare
11            sprintcare
15            sprintcare
17            sprintcare
19            sprintcare
21          Ask_Spectrum
25          Ask_Spectrum
27          Ask_Spectrum

In [22]:
# Customer → Support References
customer_tweets = twcs.loc[
    twcs["inbound"],
    ["tweet_id", "author_id", "response_tweet_id", "in_response_to_tweet_id"]
].copy()

# Customer tweets that contain at least one response_tweet_id
customer_with_responses = customer_tweets[
    customer_tweets["response_tweet_id"].notna()
].copy()

print("CUSTOMER → SUPPORT LINKAGE")
print("=" * 70)

print(
    f"Customer tweets                         : {len(customer_tweets):,}"
)

print(
    f"Customer tweets with response_tweet_id  : "
    f"{len(customer_with_responses):,}"
)

print(
    f"Percentage with response_tweet_id       : "
    f"{len(customer_with_responses) / len(customer_tweets) * 100:.2f}%"
)

CUSTOMER → SUPPORT LINKAGE
======================================================================
Customer tweets                         : 1,537,843
Customer tweets with response_tweet_id  : 1,303,829
Percentage with response_tweet_id       : 84.78%

In [23]:
# check whether response_tweet_id points to support tweets
def contains_support_reference(value):
    if pd.isna(value):
        return False

    tweet_ids = str(value).split(",")

    return any(
        int(tweet_id.strip()) in support_tweet_lookup.index
        for tweet_id in tweet_ids
        if tweet_id.strip().isdigit()
    )


customer_with_responses["references_support_tweet"] = (
    customer_with_responses["response_tweet_id"]
    .apply(contains_support_reference)
)

support_reference_count = (
    customer_with_responses["references_support_tweet"].sum()
)

print(
    f"\nCustomer tweets referencing a support tweet : "
    f"{support_reference_count:,}"
)

print(
    f"Percentage of linked customer tweets          : "
    f"{support_reference_count / len(customer_with_responses) * 100:.2f}%"
)

Customer tweets referencing a support tweet : 1,164,365
Percentage of linked customer tweets          : 89.30%

In [24]:
# Support → Customer References
support_tweets = twcs.loc[
    ~twcs["inbound"],
    ["tweet_id", "author_id", "response_tweet_id", "in_response_to_tweet_id"]
].copy()

support_with_parent = support_tweets[
    support_tweets["in_response_to_tweet_id"].notna()
].copy()

print("SUPPORT → CUSTOMER LINKAGE")
print("=" * 70)

print(
    f"Support tweets                         : "
    f"{len(support_tweets):,}"
)

print(
    f"Support tweets with in_response_to_tweet_id : "
    f"{len(support_with_parent):,}"
)

print(
    f"Percentage with parent tweet           : "
    f"{len(support_with_parent) / len(support_tweets) * 100:.2f}%"
)

SUPPORT → CUSTOMER LINKAGE
======================================================================
Support tweets                         : 1,273,931
Support tweets with in_response_to_tweet_id : 1,266,942
Percentage with parent tweet           : 99.45%

In [25]:
customer_tweet_ids = set(
    customer_tweets["tweet_id"]
)

support_with_parent["parent_is_customer"] = (
    support_with_parent["in_response_to_tweet_id"]
    .isin(customer_tweet_ids)
)

customer_parent_count = (
    support_with_parent["parent_is_customer"].sum()
)

print(
    f"\nSupport tweets replying to customer tweets : "
    f"{customer_parent_count:,}"
)

print(
    f"Percentage of support tweets with customer parent : "
    f"{customer_parent_count / len(support_tweets) * 100:.2f}%"
)

Support tweets replying to customer tweets : 1,261,888
Percentage of support tweets with customer parent : 99.05%

99.05% number is especially valuable: almost every support tweet has a customer tweet as its immediate parent.

Correctly calculate customer volume by brand

In [26]:
# customer volume linked to support brands

def get_support_accounts(response_ids):
    """Return support accounts referenced by a customer's response_tweet_id."""
    
    if pd.isna(response_ids):
        return []
    
    accounts = []
    
    for tweet_id in str(response_ids).split(","):
        tweet_id = tweet_id.strip()
        
        if not tweet_id.isdigit():
            continue
        
        tweet_id = int(tweet_id)
        
        if tweet_id in support_tweet_lookup.index:
            accounts.append(
                support_tweet_lookup.loc[tweet_id, "support_account"]
            )
    
    return list(set(accounts))

In [27]:
customer_brand_links = customer_tweets[
    ["tweet_id", "response_tweet_id"]
].copy()

customer_brand_links["support_accounts"] = (
    customer_brand_links["response_tweet_id"]
    .apply(get_support_accounts)
)

# Keep only customer tweets that can be linked to at least one support account
customer_brand_links = customer_brand_links[
    customer_brand_links["support_accounts"].str.len() > 0
].copy()

# One row per customer tweet ↔ support brand relationship
customer_brand_links = customer_brand_links.explode(
    "support_accounts"
)

customer_brand_links = customer_brand_links.rename(
    columns={"support_accounts": "support_account"}
)

print("CUSTOMER → BRAND LINKAGE")
print("=" * 70)

print(
    f"Customer tweets linked to support brand : "
    f"{customer_brand_links['tweet_id'].nunique():,}"
)

print(
    f"Customer-brand relationships            : "
    f"{len(customer_brand_links):,}"
)

print(
    f"Unique support brands represented       : "
    f"{customer_brand_links['support_account'].nunique():,}"
)

CUSTOMER → BRAND LINKAGE
======================================================================
Customer tweets linked to support brand : 1,164,365
Customer-brand relationships            : 1,166,579
Unique support brands represented       : 108

1,166,579 > 1,164,365

That's because some customer tweets reference more than one support tweet, so a single customer tweet can legitimately create multiple customer→brand relationships.

That's exactly why we said earlier that tweet-level linkage ≠ conversation-level analysis.

In [28]:
# customer value per brand
brand_customer_volume = (
    customer_brand_links
    .groupby("support_account")
    .agg(
        customer_tweets=("tweet_id", "nunique")
    )
    .sort_values("customer_tweets", ascending=False)
)

print("\nTOP 30 BRANDS BY LINKED CUSTOMER VOLUME")
print("=" * 80)

display(brand_customer_volume.head(30))

TOP 30 BRANDS BY LINKED CUSTOMER VOLUME
================================================================================

                 customer_tweets
support_account
AmazonHelp                154976
AppleSupport              106623
Uber_Support               55182
SpotifyCares               41585
AmericanAir                36457
Delta                      36134
TMobileHelp                33837
comcastcares               30369
SouthwestAir               28285
VirginTrains               26272
Tesco                      25282
Ask_Spectrum               24976
British_Airways            24084
hulu_support               21468
XboxSupport                20213
sprintcare                 20026
AskPlayStation             18650
ChipotleTweets             18565
GWRHelp                    18506
sainsburys                 17717
UPSHelp                    17601
VerizonSupport             17534
ATVIAssist                 16879
O2                         15952
Safaricom_Care             13881
AskTarget                  13135
idea_cares                 12887
ArgosHelpers               11444
AskLyft                    11437
AskPayPal                  11181

each tweet can point to its immediate parent using: in_response_to_tweet_id

A tweet can also have multiple responses through: response_tweet_id

Therefore, the dataset can be represented as a forest of conversation trees.

Conversation Quality

In [29]:
tweet_ids = twcs["tweet_id"]

parent_ids = twcs["in_response_to_tweet_id"]

has_parent = parent_ids.notna()

existing_parent = parent_ids.isin(
    tweet_ids
)

missing_parent_reference = (
    has_parent & ~existing_parent
)

print("CONVERSATION GRAPH VALIDATION")
print("=" * 75)

print(f"Total tweets                         : {len(twcs):,}")
print(f"Tweets with a parent                 : {has_parent.sum():,}")
print(
    f"Tweets without a parent              : "
    f"{(~has_parent).sum():,}"
)

print(
    f"\nValid parent references              : "
    f"{(has_parent & existing_parent).sum():,}"
)

print(
    f"Missing parent references             : "
    f"{missing_parent_reference.sum():,}"
)

print(
    f"Parent-reference validity             : "
    f"{(has_parent & existing_parent).sum() / has_parent.sum() * 100:.2f}%"
)

CONVERSATION GRAPH VALIDATION
===========================================================================
Total tweets                         : 2,811,774
Tweets with a parent                 : 2,017,439
Tweets without a parent              : 794,335

Valid parent references              : 2,013,577
Missing parent references             : 3,862
Parent-reference validity             : 99.81%

In [30]:
# ceck any tweet points to itself
self_references = (
    has_parent &
    (parent_ids == tweet_ids)
).sum()

print(
    f"\nSelf-referencing tweets              : "
    f"{self_references:,}"
)

Self-referencing tweets              : 0

A non-null in_response_to_tweet_id should point to another tweet in TWCS.

Tweet ID Ordering

In [31]:
valid_parent_mask = (
    twcs["in_response_to_tweet_id"].notna()
    & twcs["in_response_to_tweet_id"].isin(twcs["tweet_id"])
)

parent_order_check = twcs.loc[
    valid_parent_mask,
    ["tweet_id", "in_response_to_tweet_id"]
].copy()

parent_order_check["parent_id"] = (
    parent_order_check["in_response_to_tweet_id"]
    .astype("int64")
)

parent_order_check["parent_before_child"] = (
    parent_order_check["parent_id"]
    < parent_order_check["tweet_id"]
)

parent_before_count = (
    parent_order_check["parent_before_child"].sum()
)

total_valid_parents = len(parent_order_check)

print("PARENT / CHILD ID ORDERING")
print("=" * 75)

print(f"Valid parent-child relationships : {total_valid_parents:,}")
print(
    f"Parent ID < child ID             : "
    f"{parent_before_count:,}"
)

print(
    f"Parent-before-child percentage   : "
    f"{parent_before_count / total_valid_parents * 100:.4f}%"
)

print(
    f"Parent ID >= child ID            : "
    f"{total_valid_parents - parent_before_count:,}"
)

PARENT / CHILD ID ORDERING
===========================================================================
Valid parent-child relationships : 2,013,577
Parent ID < child ID             : 895,760
Parent-before-child percentage   : 44.4860%
Parent ID >= child ID            : 1,117,817

In [32]:
# Show any exceptions, if they exist
exceptions = parent_order_check[
    ~parent_order_check["parent_before_child"]
]

print("\nEXAMPLES OF EXCEPTIONS")
print("=" * 75)

display(exceptions.head(10))

EXAMPLES OF EXCEPTIONS
===========================================================================

    tweet_id  in_response_to_tweet_id  parent_id  parent_before_child
0          1                        3          3                False
2          3                        4          4                False
3          4                        5          5                False
4          5                        6          6                False
5          6                        8          8                False
7         11                       12         12                False
8         12                       15         15                False
9         15                       16         16                False
10        16                       17         17                False
11        17                       18         18                False

tweet IDs are absolutely not a safe chronological ordering mechanism.
Therefore, will not use tweet IDs to infer conversation order.

Then can go through created_at
- Are parent tweets actually earlier than their child tweets according to created_at?

Use the actual timestamp for conversation ordering

In [33]:
# Build a minimal tweet_id -> timestamp lookup.
tweet_time_lookup = (
    twcs[
        ["tweet_id", "created_at_parsed"]
    ]
    .set_index("tweet_id")["created_at_parsed"]
)

temporal_check = twcs.loc[
    valid_parent_mask,
    ["tweet_id", "in_response_to_tweet_id", "created_at_parsed"]
].copy()

temporal_check["parent_id"] = (
    temporal_check["in_response_to_tweet_id"]
    .astype("int64")
)

temporal_check["parent_created_at"] = (
    temporal_check["parent_id"]
    .map(tweet_time_lookup)
)

temporal_check["parent_before_child"] = (
    temporal_check["parent_created_at"]
    < temporal_check["created_at_parsed"]
)

valid_temporal_rows = temporal_check[
    temporal_check["parent_created_at"].notna()
]

temporal_valid_count = (
    valid_temporal_rows["parent_before_child"].sum()
)

temporal_total = len(valid_temporal_rows)

print("TEMPORAL PARENT / CHILD ORDERING")
print("=" * 75)

print(
    f"Valid parent-child pairs with timestamps : "
    f"{temporal_total:,}"
)

print(
    f"Parent timestamp < child timestamp       : "
    f"{temporal_valid_count:,}"
)

print(
    f"Parent-before-child percentage            : "
    f"{temporal_valid_count / temporal_total * 100:.4f}%"
)

print(
    f"Non-chronological relationships            : "
    f"{temporal_total - temporal_valid_count:,}"
)

print("\nEXAMPLES OF NON-CHRONOLOGICAL RELATIONSHIPS")
print("=" * 75)

temporal_exceptions = valid_temporal_rows[
    ~valid_temporal_rows["parent_before_child"]
]

display(
    temporal_exceptions[
        [
            "tweet_id",
            "parent_id",
            "parent_created_at",
            "created_at_parsed"
        ]
    ].head(10)
)

TEMPORAL PARENT / CHILD ORDERING
===========================================================================
Valid parent-child pairs with timestamps : 2,013,577
Parent timestamp < child timestamp       : 2,013,521
Parent-before-child percentage            : 99.9972%
Non-chronological relationships            : 56

EXAMPLES OF NON-CHRONOLOGICAL RELATIONSHIPS
===========================================================================

,tweet_id,parent_id,parent_created_at,created_at_parsed
187812,221474,221473,2017-10-04 17:18:43+00:00,2017-10-04 17:18:43+00:00
331656,379549,379550,2017-10-09 06:34:14+00:00,2017-10-09 06:34:14+00:00
331657,379550,379551,2017-10-09 06:34:14+00:00,2017-10-09 06:34:14+00:00
331658,379551,379552,2017-10-09 06:34:14+00:00,2017-10-09 06:34:14+00:00
337322,385533,385529,2017-10-17 12:29:53+00:00,2017-10-17 12:29:53+00:00
337325,385535,385534,2017-10-24 07:33:56+00:00,2017-10-24 07:33:56+00:00
337329,385540,385538,2017-10-24 15:53:08+00:00,2017-10-24 15:53:08+00:00
337332,385543,385542,2017-10-25 09:30:36+00:00,2017-10-25 09:30:36+00:00
337334,385545,385544,2017-10-25 09:30:37+00:00,2017-10-25 09:30:37+00:00
337342,385550,385549,2017-10-17 13:59:44+00:00,2017-10-17 13:59:44+00:00

TWCS's explicit parent-child relationships are temporally consistent. We can use in_response_to_tweet_id to reconstruct conversation chains and created_at to order the turns.

binary < check classified equal timestamps as exceptions, should correct that interpretation rather than call them non-chronological.

In [34]:
valid_parent_mask.head(10)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8     True
9     True
Name: in_response_to_tweet_id, dtype: boolean

In [35]:
# Identify conversation roots
is_root = ~valid_parent_mask

root_tweets = twcs.loc[
    is_root,
    ["tweet_id", "inbound", "created_at_parsed", "text"]
].copy()

print("CONVERSATION ROOTS")
print("=" * 75)

print(f"Total tweets              : {len(twcs):,}")
print(f"Valid parent-linked tweets: {valid_parent_mask.sum():,}")
print(f"Root tweets               : {is_root.sum():,}")

print(
    f"Root percentage           : "
    f"{is_root.mean() * 100:.2f}%"
)

print("\nROOT MESSAGE DIRECTION")
print("=" * 75)

root_direction = (
    root_tweets["inbound"]
    .map({
        True: "Customer → Company",
        False: "Company → Customer"
    })
    .value_counts()
)

display(root_direction.to_frame("root_count"))

print("\nSAMPLE ROOT TWEETS")
print("=" * 75)

display(
    root_tweets.head(10)
)

CONVERSATION ROOTS
===========================================================================
Total tweets              : 2,811,774
Valid parent-linked tweets: 2,013,577
Root tweets               : 798,197
Root percentage           : 28.39%

ROOT MESSAGE DIRECTION
===========================================================================

                    root_count
inbound
Customer → Company      789547
Company → Customer        8650

SAMPLE ROOT TWEETS
===========================================================================

,tweet_id,inbound,created_at_parsed,text
6,8,True,2017-10-31 21:45:10+00:00,@sprintcare is the worst customer service
12,18,True,2017-10-31 19:56:01+00:00,"@115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh."
14,20,True,2017-10-31 22:03:34+00:00,"@115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never i..."
23,29,True,2017-10-31 22:01:35+00:00,actually that's a broken link you sent me and incorrect information https://t.co/V4yfrHR8VI
25,31,True,2017-10-31 22:06:54+00:00,"Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service go..."
27,33,True,2017-10-31 22:06:56+00:00,My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik
31,36,True,2017-10-31 22:10:46+00:00,somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service
33,39,True,2017-10-31 22:12:16+00:00,@VerizonSupport My friend is without internet we need to play videogames together please our skills diminish every m...
43,49,True,2017-10-31 21:42:09+00:00,"@115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give..."
53,59,True,2017-10-31 19:54:51+00:00,@115722 is the worst ISP I’ve ever had

In [36]:
# reconstruct conversation chains
# Number of tweets
n_rows = len(twcs)

tweet_id_array = twcs["tweet_id"].to_numpy(dtype=np.int64)

# Parent tweet ID.
# -1 means there is no parent.
parent_id_array = (
    twcs["in_response_to_tweet_id"]
    .fillna(-1)
    .to_numpy(dtype=np.int64)
)

# Map tweet_id -> row position
tweet_id_index = pd.Index(tweet_id_array)

parent_row = tweet_id_index.get_indexer(parent_id_array)

no_parent = parent_id_array == -1
valid_parent = parent_row >= 0
unresolved_parent = (~no_parent) & (~valid_parent)

print("PARENT RELATIONSHIP CATEGORIES")
print("=" * 75)

print(f"No parent          : {no_parent.sum():,}")
print(f"Valid parent       : {valid_parent.sum():,}")
print(f"Unresolved parent  : {unresolved_parent.sum():,}")

PARENT RELATIONSHIP CATEGORIES
===========================================================================
No parent          : 794,335
Valid parent       : 2,013,577
Unresolved parent  : 3,862

In [37]:
# Initialize every tweet as its own root.

root = np.arange(n_rows, dtype=np.int64)

# Tweets with a valid parent initially point to their parent.
root[valid_parent] = parent_row[valid_parent]

iterations = 0

while True:
    previous_root = root.copy()

    # For every tweet, jump to the root currently assigned
    # to its current ancestor.
    root = root[root]

    iterations += 1

    if np.array_equal(root, previous_root):
        break

# Convert root row positions → root tweet IDs
twcs["conversation_id"] = tweet_id_array[root]

In [38]:
# Conversation root type

twcs["conversation_root_type"] = np.where(
    no_parent,
    "no_parent",
    np.where(
        unresolved_parent,
        "unresolved_parent",
        "child"
    )
)

In [39]:
print("\nCONVERSATION ROOT RECONSTRUCTION")
print("=" * 75)

print(f"Pointer-jumping iterations : {iterations:,}")

print(
    f"Unique conversation IDs    : "
    f"{twcs['conversation_id'].nunique():,}"
)

print("\nROOT TYPES")
print("=" * 75)

display(
    twcs["conversation_root_type"]
    .value_counts()
    .to_frame("tweet_count")
)

CONVERSATION ROOT RECONSTRUCTION
===========================================================================
Pointer-jumping iterations : 11
Unique conversation IDs    : 798,197

ROOT TYPES
===========================================================================

                        tweet_count
conversation_root_type
child                       2013577
no_parent                    794335
unresolved_parent              3862

In [40]:
# Step 19 — Validate Reconstructed Conversation
TEST_TWEET_ID = 1

test_conversation_id = twcs.loc[
    twcs["tweet_id"] == TEST_TWEET_ID,
    "conversation_id"
].iloc[0]

test_conversation = (
    twcs.loc[
        twcs["conversation_id"] == test_conversation_id,
        [
            "tweet_id",
            "author_id",
            "inbound",
            "created_at_parsed",
            "in_response_to_tweet_id",
            "conversation_id",
            "text"
        ]
    ]
    .sort_values("created_at_parsed")
    .reset_index(drop=True)
)

print("CONVERSATION VALIDATION")
print("=" * 90)

print(f"Test tweet ID       : {TEST_TWEET_ID}")
print(f"Conversation ID     : {test_conversation_id}")
print(f"Number of turns     : {len(test_conversation)}")

display(test_conversation)

CONVERSATION VALIDATION
==========================================================================================
Test tweet ID       : 1
Conversation ID     : 8
Number of turns     : 10

,tweet_id,author_id,inbound,created_at_parsed,in_response_to_tweet_id,conversation_id,text
0,8,115712,True,2017-10-31 21:45:10+00:00,<NA>,8,@sprintcare is the worst customer service
1,10,sprintcare,False,2017-10-31 21:45:59+00:00,8,8,@115712 Hello! We never like our customers to feel like they are not valued.
2,9,sprintcare,False,2017-10-31 21:46:14+00:00,8,8,@115712 I would love the chance to review the account and provide assistance.
3,6,sprintcare,False,2017-10-31 21:46:24+00:00,8,8,"@115712 Can you please send us a private message, so that I can gain further details about your account?"
4,7,115712,True,2017-10-31 21:47:48+00:00,6,8,@sprintcare the only way I can get a response is to tweet apparently
5,5,115712,True,2017-10-31 21:49:35+00:00,6,8,@sprintcare I did.
6,4,sprintcare,False,2017-10-31 21:54:49+00:00,5,8,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your ...
7,3,115712,True,2017-10-31 22:08:27+00:00,4,8,@sprintcare I have sent several private messages and no one is responding as usual
8,1,sprintcare,False,2017-10-31 22:10:47+00:00,3,8,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further as...
9,2,115712,True,2017-10-31 22:11:45+00:00,1,8,@sprintcare and how do you propose we do that

- Tweets in the same parent chain received the same conversation_id.
- The resulting conversation is chronologically ordered.
- Customer/support roles make sense within the conversation.

Conversation Structure Validation

In [41]:
conversation_stats = (
    twcs
    .groupby("conversation_id")
    .agg(
        conversation_size=("tweet_id", "size"), # can also use .count()
        customer_tweets=("inbound", "sum"),
        support_tweets=("inbound", lambda x: (~x).sum()),
        unique_authors=("author_id", "nunique"),
        start_time=("created_at_parsed", "min"),
        end_time=("created_at_parsed", "max"),
    )
)

conversation_stats["duration_minutes"] = (
    (
        conversation_stats["end_time"]
        - conversation_stats["start_time"]
    )
    .dt.total_seconds()
    / 60
)

conversation_stats["is_multi_turn"] = (
    conversation_stats["conversation_size"] >= 2
)

conversation_stats["has_customer_and_support"] = (
    (conversation_stats["customer_tweets"] > 0)
    & (conversation_stats["support_tweets"] > 0)
)

print("CONVERSATION STRUCTURE")
print("=" * 80)

print(
    f"Unique conversations              : "
    f"{len(conversation_stats):,}"
)

print(
    f"Multi-tweet conversations         : "
    f"{conversation_stats['is_multi_turn'].sum():,}"
)

print(
    f"Multi-tweet percentage             : "
    f"{conversation_stats['is_multi_turn'].mean() * 100:.2f}%"
)

print(
    f"Customer + support conversations   : "
    f"{conversation_stats['has_customer_and_support'].sum():,}"
)

print(
    f"Customer + support percentage      : "
    f"{conversation_stats['has_customer_and_support'].mean() * 100:.2f}%"
)

print("\nCONVERSATION SIZE DISTRIBUTION")
print("=" * 80)

display(
    conversation_stats["conversation_size"]
    .describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
    .to_frame("conversation_size")
)

CONVERSATION STRUCTURE
================================================================================
Unique conversations              : 798,197
Multi-tweet conversations         : 798,197
Multi-tweet percentage             : 100.00%
Customer + support conversations   : 798,110
Customer + support percentage      : 99.99%

CONVERSATION SIZE DISTRIBUTION
================================================================================

       conversation_size
count      798197.000000
mean            3.522657
std             5.152779
min             2.000000
25%             2.000000
50%             2.000000
75%             4.000000
90%             6.000000
95%             8.000000
99%            15.000000
max          1390.000000

For each reconstructed conversation, which support brand does it belong to?

Map Conversations to Support Brands

In [42]:
# For each reconstructed conversation, collect the unique
# support accounts that participated in it.

conversation_brand_map = (
    twcs.loc[
        ~twcs["inbound"],
        ["conversation_id", "author_id"]
    ]
    .drop_duplicates()
    .groupby("conversation_id")
    .agg(
        support_brands=("author_id", list),
        support_brand_count=("author_id", "nunique")
    )
)

# Classify each conversation
conversation_brand_map["brand_mapping_type"] = np.select(
    [
        conversation_brand_map["support_brand_count"] == 1,
        conversation_brand_map["support_brand_count"] > 1
    ],
    [
        "single_brand",
        "multiple_brands"
    ],
    default="no_support_brand"
)

# Counts
support_conversation_count = len(conversation_brand_map)

single_brand_count = (
    conversation_brand_map["brand_mapping_type"]
    .eq("single_brand")
    .sum()
)

multi_brand_count = (
    conversation_brand_map["brand_mapping_type"]
    .eq("multiple_brands")
    .sum()
)

print("CONVERSATION → BRAND MAPPING")
print("=" * 80)

print(f"Total conversations          : {len(conversation_stats):,}")
print(f"Conversations with support   : {support_conversation_count:,}")
print(f"Single-brand conversations   : {single_brand_count:,}")
print(f"Multi-brand conversations    : {multi_brand_count:,}")

print("\nMAPPING DISTRIBUTION")
print("=" * 80)

mapping_distribution = (
    conversation_brand_map["brand_mapping_type"]
    .value_counts()
    .to_frame("conversation_count")
)

mapping_distribution["percentage"] = (
    mapping_distribution["conversation_count"]
    / len(conversation_stats)
    * 100
).round(2)

display(mapping_distribution)

print("\nEXAMPLES OF MULTI-BRAND CONVERSATIONS")
print("=" * 80)

multi_brand_examples = conversation_brand_map.loc[
    conversation_brand_map["brand_mapping_type"] == "multiple_brands"
].head(10)

display(multi_brand_examples)

CONVERSATION → BRAND MAPPING
================================================================================
Total conversations          : 798,197
Conversations with support   : 798,197
Single-brand conversations   : 795,131
Multi-brand conversations    : 3,066

MAPPING DISTRIBUTION
================================================================================

                    conversation_count  percentage
brand_mapping_type
single_brand                    795131       99.62
multiple_brands                   3066        0.38

EXAMPLES OF MULTI-BRAND CONVERSATIONS
================================================================================

,support_brands,support_brand_count,brand_mapping_type
conversation_id,,,
1299,"[sprintcare, TMobileHelp]",2,multiple_brands
1998,"[TMobileHelp, sprintcare]",2,multiple_brands
2659,"[AppleSupport, sprintcare]",2,multiple_brands
7442,"[marksandspencer, Tesco, sainsburys, AldiUK, Morrisons]",5,multiple_brands
7511,"[SouthwestAir, AmericanAir]",2,multiple_brands
8036,"[comcastcares, sprintcare]",2,multiple_brands
8063,"[comcastcares, VerizonSupport]",2,multiple_brands
8210,"[SouthwestAir, AmericanAir]",2,multiple_brands
8608,"[Uber_Support, AskLyft]",2,multiple_brands
8905,"[VerizonSupport, comcastcares]",2,multiple_brands

Conversation Quality by Brand

In [43]:
# keepin only single brand conversations
single_brand_conversations = conversation_brand_map.loc[
    conversation_brand_map["brand_mapping_type"] == "single_brand"
].copy()

# Extract the single support brand
single_brand_conversations["support_account"] = (
    single_brand_conversations["support_brands"]
    .str[0]
)

In [44]:
# add conv statistics
brand_conversation_data = (
    single_brand_conversations[
        ["support_account"]
    ]
    .join(
        conversation_stats[
            [
                "conversation_size",
                "customer_tweets",
                "support_tweets",
                "duration_minutes"
            ]
        ],
        how="inner"
    )
)

In [45]:
# define meaninggful multi-turn signals
brand_conversation_data["has_multiple_customer_turns"] = (
    brand_conversation_data["customer_tweets"] >= 2
)

brand_conversation_data["has_multiple_support_turns"] = (
    brand_conversation_data["support_tweets"] >= 2
)

brand_conversation_data["has_3_plus_tweets"] = (
    brand_conversation_data["conversation_size"] >= 3
)

brand_conversation_data["has_4_plus_tweets"] = (
    brand_conversation_data["conversation_size"] >= 4
)

In [46]:
# aggregate by brand
brand_conversation_quality = (
    brand_conversation_data
    .groupby("support_account")
    .agg(
        conversations=("conversation_size", "size"),

        mean_size=("conversation_size", "mean"),
        median_size=("conversation_size", "median"),

        pct_3_plus=("has_3_plus_tweets", "mean"),
        pct_4_plus=("has_4_plus_tweets", "mean"),

        pct_multiple_customer_turns=(
            "has_multiple_customer_turns",
            "mean"
        ),

        pct_multiple_support_turns=(
            "has_multiple_support_turns",
            "mean"
        ),

        median_duration_minutes=(
            "duration_minutes",
            "median"
        )
    )
)

In [47]:
# Convert proportions to percentages
percentage_columns = [
    "pct_3_plus",
    "pct_4_plus",
    "pct_multiple_customer_turns",
    "pct_multiple_support_turns"
]

brand_conversation_quality[percentage_columns] *= 100

brand_conversation_quality[percentage_columns] = (
    brand_conversation_quality[percentage_columns]
    .round(2)
)

brand_conversation_quality[
    ["mean_size", "median_size", "median_duration_minutes"]
] = (
    brand_conversation_quality[
        ["mean_size", "median_size", "median_duration_minutes"]
    ]
    .round(2)
)

In [48]:
# rank by conversation ability
brand_conversation_quality = (
    brand_conversation_quality
    .sort_values(
        "conversations",
        ascending=False
    )
)


print("BRAND-LEVEL CONVERSATION QUALITY")
print("=" * 110)

display(
    brand_conversation_quality.head(30)
)

BRAND-LEVEL CONVERSATION QUALITY
==============================================================================================================

,conversations,mean_size,median_size,pct_3_plus,pct_4_plus,pct_multiple_customer_turns,pct_multiple_support_turns,median_duration_minutes
support_account,,,,,,,,
AmazonHelp,82246,4.52,3.0,61.95,47.96,57.07,49.63,27.14
AppleSupport,80552,2.95,2.0,34.73,24.82,34.60,22.21,135.54
Uber_Support,41848,3.05,2.0,35.88,24.61,35.04,22.40,18.16
SpotifyCares,28224,3.23,2.0,37.00,28.63,35.08,29.17,89.28
AmericanAir,25941,3.27,2.0,42.91,30.38,42.37,27.13,21.73
Delta,25907,3.32,2.0,42.02,29.83,35.47,33.33,23.33
comcastcares,23802,2.94,2.0,35.85,21.05,29.22,24.01,65.03
TMobileHelp,22447,3.38,2.0,36.77,27.26,36.07,23.13,5.82
SouthwestAir,21389,2.96,2.0,32.65,20.59,31.78,19.56,12.12
Ask_Spectrum,18374,3.11,2.0,34.85,24.24,33.11,22.91,48.76
Tesco,16566,4.26,4.0,69.26,50.89,47.71,61.06,179.76
British_Airways,16342,3.67,3.0,53.36,35.75,42.35,44.28,301.53
UPSHelp,15155,2.73,2.0,32.87,15.51,32.27,10.83,19.17
hulu_support,14871,3.20,2.0,39.09,28.75,38.18,28.12,1094.80
VirginTrains,14766,4.39,3.0,61.62,45.00,59.72,42.23,10.57
ChipotleTweets,14385,2.91,2.0,33.81,20.20,33.39,18.16,19.22
XboxSupport,13354,4.08,3.0,62.12,39.19,51.71,42.47,166.64
sprintcare,13171,3.60,2.0,45.51,31.17,42.02,29.54,21.13
AskPlayStation,12519,3.42,2.0,45.63,33.64,44.09,32.46,298.95
AskTarget,11103,2.73,2.0,33.64,17.55,33.32,14.15,201.73
ATVIAssist,11062,4.18,2.0,48.94,31.46,47.20,23.61,2012.42
sainsburys,10748,3.84,3.0,56.24,45.12,52.69,45.78,501.76
GWRHelp,10636,4.32,3.0,64.45,47.35,63.28,43.55,24.73
AskLyft,10126,2.65,2.0,29.46,14.11,27.79,11.15,11.14
O2,9521,3.80,2.0,46.35,38.09,45.80,36.61,190.57
AskPayPal,9437,2.78,2.0,30.63,17.48,30.31,11.95,1391.02
Safaricom_Care,9337,3.61,3.0,53.12,33.55,43.13,40.59,37.67
McDonalds,8121,2.36,2.0,16.92,3.77,16.75,0.87,703.52
VerizonSupport,8073,5.14,4.0,64.93,52.56,63.83,48.09,11.95
marksandspencer,7927,3.16,2.0,43.52,27.59,39.14,27.80,345.10

customer problem - 
support investigation - 
customer clarification - 
support resolution

Inspect Real Support Responses

In [49]:
# inspect real multi-turn conversations
candidate_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Tesco",
    "XboxSupport"
]

# Candidate conversations:
# - single brand
# - at least 4 tweets
# - contains both customer and support messages

candidate_conversations = (
    brand_conversation_data.loc[
        brand_conversation_data["support_account"].isin(candidate_brands)
        & (brand_conversation_data["conversation_size"] >= 4)
        & (brand_conversation_data["customer_tweets"] >= 2)
        & (brand_conversation_data["support_tweets"] >= 2)
    ]
    .groupby("support_account", group_keys=False)
    .head(3)
    .index
)

In [50]:
inspection_df = twcs.loc[
    twcs["conversation_id"].isin(candidate_conversations),
    [
        "conversation_id",
        "tweet_id",
        "author_id",
        "inbound",
        "created_at_parsed",
        "text"
    ]
].copy()

inspection_df = inspection_df.sort_values(
    ["conversation_id", "created_at_parsed"]
)

In [51]:
for brand in candidate_brands:

    print("\n")
    print("=" * 100)
    print(f"{brand}")
    print("=" * 100)

    brand_conversation_ids = (
        brand_conversation_data.loc[
            brand_conversation_data["support_account"] == brand
        ]
        .loc[
            lambda x: x["conversation_size"] >= 4
        ]
        .loc[
            lambda x: x["customer_tweets"] >= 2
        ]
        .loc[
            lambda x: x["support_tweets"] >= 2
        ]
        .index
        .tolist()
    )

    # Inspect up to 3 conversations
    for conversation_id in brand_conversation_ids[:3]:

        conversation = inspection_df.loc[
            inspection_df["conversation_id"] == conversation_id
        ]

        print(f"\nConversation ID: {conversation_id}")
        print("-" * 100)

        for _, row in conversation.iterrows():

            speaker = (
                "CUSTOMER"
                if row["inbound"]
                else "SUPPORT"
            )

            print(
                f"[{speaker}] "
                f"{row['created_at_parsed']} | "
                f"{row['text']}"
            )

====================================================================================================
AmazonHelp
====================================================================================================

Conversation ID: 272
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-11-22 09:14:39+00:00 | amazonのfireTVstickが見れない😢
[SUPPORT] 2017-11-22 09:23:01+00:00 | @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
[CUSTOMER] 2017-11-22 09:24:30+00:00 | @AmazonHelp ありがとうございます。
今、電話で主人が対応していただいてます。
[CUSTOMER] 2017-11-22 09:30:36+00:00 | @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
[SUPPORT] 2017-11-22 09:40:27+00:00 | @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET
[CUSTOMER] 2017-11-22 09:44:04+00:00 | @AmazonHelp こちらこそありがとうございました。
[SUPPORT] 2017-11-22 10:06:26+00:00 | @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

Conversation ID: 617
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 22:16:32+00:00 | Way to drop the ball on customer service @115821 so pissed right now!
[SUPPORT] 2017-10-31 22:29:00+00:00 | @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN
[CUSTOMER] 2017-10-31 23:22:08+00:00 | @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
[SUPPORT] 2017-10-31 23:28:00+00:00 | @115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG
[CUSTOMER] 2017-10-31 23:32:26+00:00 | @AmazonHelp I frankly don't have the patience for another chat with your "customer service" people today.

Conversation ID: 624
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 22:12:37+00:00 | @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?
[SUPPORT] 2017-10-31 22:28:00+00:00 | @115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS
[CUSTOMER] 2017-10-31 22:32:07+00:00 | @AmazonHelp Okay, danke für die Info
[SUPPORT] 2017-10-31 22:34:32+00:00 | @115824 Wir haben zu danken. Schönen Abend noch. ^JS


====================================================================================================
AppleSupport
====================================================================================================

Conversation ID: 700
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 22:16:56+00:00 | @AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
[CUSTOMER] 2017-10-31 22:17:40+00:00 | @AppleSupport  https://t.co/NV0yucs0lB
[SUPPORT] 2017-10-31 22:27:49+00:00 | @115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.
[CUSTOMER] 2017-10-31 22:31:23+00:00 | @AppleSupport The newest update. I️ made sure to download it yesterday.
[SUPPORT] 2017-10-31 22:36:27+00:00 | @115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT

Conversation ID: 711
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 21:29:22+00:00 | What is up with this “ I️ “
[CUSTOMER] 2017-10-31 21:29:50+00:00 | Why are my I’s question marks ?
[CUSTOMER] 2017-10-31 21:34:45+00:00 | @AppleSupport I️ need answers because it’s annoying 🙃
[SUPPORT] 2017-10-31 21:43:15+00:00 | @115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?
[CUSTOMER] 2017-10-31 21:48:51+00:00 | @AppleSupport I️ have an iPhone 7 Plus and yes I️ do
[SUPPORT] 2017-10-31 21:57:00+00:00 | @115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?
[CUSTOMER] 2017-10-31 21:58:48+00:00 | @AppleSupport Last night
[CUSTOMER] 2017-10-31 21:59:17+00:00 | @AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
[SUPPORT] 2017-10-31 22:09:52+00:00 | @115855 Any steps tried since it started last night?
[CUSTOMER] 2017-10-31 22:11:31+00:00 | @AppleSupport Tried resetting my settings .. restarting my phone .. all that
[SUPPORT] 2017-10-31 22:26:49+00:00 | @115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT

Conversation ID: 719
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 22:01:50+00:00 | Tf is wrong with my keyboard @115858
[SUPPORT] 2017-10-31 22:05:00+00:00 | @115857 Fill us in on what is happening, then we can help out from there.
[CUSTOMER] 2017-10-31 22:13:08+00:00 | @AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
[SUPPORT] 2017-10-31 22:24:54+00:00 | @115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT


====================================================================================================
Tesco
====================================================================================================

Conversation ID: 789
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 18:02:11+00:00 | @Tesco 3/3 on the wrong which I really don’t appreciate. This needs to be investigate and I was simply queuing to pay and the guy pushed in😡
[SUPPORT] 2017-10-31 19:47:00+00:00 | @115881 Hi Cade, what was my colleagues name? Can you give a description? When were you in our store? - Nick
[CUSTOMER] 2017-10-31 20:29:25+00:00 | @Tesco Tall lady 6ft, slim, was on the till about 15:10, think she had blonde hair. She served the guy after knowing he didn’t queue up like others
[SUPPORT] 2017-10-31 22:18:58+00:00 | @115881 Hi Cade, thanks so much for sending that over. I have sent an email to the Store Manager to look into this for you. 1/2
[SUPPORT] 2017-10-31 22:18:59+00:00 | @115881 However, I'd still like to log this for you. Can you send us your full name, postcode &amp; address and email please? Thanks - Josh 2/2 https://t.co/py5Z991Bme

Conversation ID: 1819
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 21:14:03+00:00 | Ay @Tesco what’s your policy on bottles of lemonade? 6 bottle max is a bit of a joke am thirsty
[CUSTOMER] 2017-10-31 21:19:17+00:00 | @116115 @Tesco Think it’s that for anything now yeno, we can’t even get our limes from there now
[CUSTOMER] 2017-10-31 21:20:00+00:00 | @759373 @Tesco @sainsburys you gunna supply us?
[CUSTOMER] 2017-10-31 21:21:32+00:00 | @116115 @Tesco 😂😂🙄
[SUPPORT] 2017-10-31 21:24:38+00:00 | @116115 Hi James, not sure what you mean by this can you please elaborate on this for me so I can help? Thanks - Marian
[CUSTOMER] 2017-10-31 21:25:46+00:00 | @Tesco What’s the max amount of products you can buy at any one time? Just tried to buy 20 bottles of lemonade and got told 6 per person
[CUSTOMER] 2017-10-31 21:26:38+00:00 | @116116 @Tesco  https://t.co/OOFePDl9eC
[SUPPORT] 2017-10-31 22:40:23+00:00 | @116115 Hi James, would you be able to let me know how many bottles of lemonade were in stock at the time you were there? Thanks - Callum

Conversation ID: 1823
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 21:10:48+00:00 | @Tesco thought you’d like to know: these sausages I purchased from you taste awful. Ruined my sausage and mash dinner, I just had mash! https://t.co/xBRP0FxHks
[SUPPORT] 2017-10-31 22:37:50+00:00 | @116117 Hi Rhys, I'm really sorry you've not had a stellar time with our Mor range, I'd like to get an internal log of this 1/3
[SUPPORT] 2017-10-31 22:37:53+00:00 | @116117 To do so could you please send me your name, address and postcode? I'll also need the barcode and supplier code (SC1234) from the box 2/3
[SUPPORT] 2017-10-31 22:37:54+00:00 | @116117 Finally could you please send me the bottom most row of digits from your receipt. - Nick 3/3
[CUSTOMER] 2017-11-01 14:42:32+00:00 | @Tesco Honestly, I don’t care that much. You should just know that all 6 sausages ended up in the bin
[SUPPORT] 2017-11-01 17:03:50+00:00 | @116117 Hi Rhys, thanks for letting us know. I've log this feed back anonymously. Thanks, James.


====================================================================================================
XboxSupport
====================================================================================================

Conversation ID: 318
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 20:03:55+00:00 | @XboxSupport @115786 @115787 @15913 can anyone let me know when our pre orders are going to be shipped for xbox one x??
[CUSTOMER] 2017-10-31 20:04:15+00:00 | @XboxSupport @115786 @115787 @15913 Would like to know so I can make sure I have enough money for it...
[SUPPORT] 2017-10-31 22:13:28+00:00 | @115785 Hi there! We'd recommend reaching out to the chat team here: https://t.co/UrUi80i54l ^JA
[CUSTOMER] 2017-10-31 22:14:11+00:00 | @XboxSupport They have no info either..
[SUPPORT] 2017-10-31 22:52:52+00:00 | @115785 We'd recommend keeping an eye out on your email that is associated with your account for further info.  ^JA
[CUSTOMER] 2017-11-01 00:50:56+00:00 | @XboxSupport Lol so there's no one @115786 who can say when they're going to be shipped...? That's kinda weird
[CUSTOMER] 2017-11-01 00:59:24+00:00 | @XboxSupport @115786 When someone @115786 or @15913 @115787 @115788 knows when the xbox one x ships let us know.  Lol shouldn't b a mystery..
[SUPPORT] 2017-11-01 01:09:18+00:00 | @115785 @115786 Did you pre-order this console via the Microsoft store? If so, then let's have you reach out here: https://t.co/jY7fDjTzLd ^JA
[CUSTOMER] 2017-11-01 01:11:28+00:00 | @XboxSupport @115786 Already did they had me call and no one can answer the question.  I'm not trying to be a jerk but it's nuts no one has a answer..
[CUSTOMER] 2017-11-01 01:13:10+00:00 | @XboxSupport @115786 Kinda need to make sure I have 680$ cdn in my bank, so would be nice to know.. I dun just have cash laying around ya know #RealLifeStruggles

Conversation ID: 1598
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 21:41:12+00:00 | @XboxSupport my brother can't install Forza 7 on his Xbox one, he's already tried a power cycle, what can he do please?
[SUPPORT] 2017-10-31 22:24:29+00:00 | @116040 Hello! Most of the time connecting via ethernet can help, or restarting the console, router, and download. ^CO
[CUSTOMER] 2017-10-31 22:48:47+00:00 | @XboxSupport Connection via Ethernet not possible where he is, also there's no file to delete &amp; restart as said before he's done a power cycle?
[SUPPORT] 2017-10-31 23:14:06+00:00 | @116040 Canceling the download, powering down the console, unplugging for five full minutes (this clears the cache), and try again. ^CO

Conversation ID: 2341
----------------------------------------------------------------------------------------------------
[CUSTOMER] 2017-10-31 21:24:16+00:00 | A headset should be a simple plug in and go method right? @XboxSupport
[SUPPORT] 2017-10-31 22:35:10+00:00 | @116241 Hi there! Mind clarifying for us the make/model of the headset that you are using?  ^JA
[CUSTOMER] 2017-11-02 13:45:47+00:00 | @XboxSupport The one you guys give in box at purchase
[SUPPORT] 2017-11-02 16:20:31+00:00 | @116241 Gotcha, let's make sure that your controller is up to date https://t.co/AjbWyIX8UB and see if the headset works then. ^JS

A long conversation ≠ a resolved conversation.

Quantify Resolution Richness

In [52]:
# Candidate brands selected for deeper comparison
resolution_candidates = [
    "AmazonHelp",
    "AppleSupport",
    "Tesco",
    "XboxSupport"
]

resolution_support = twcs.loc[
    (~twcs["inbound"])
    & (twcs["author_id"].isin(resolution_candidates))
].copy()

resolution_support["text_lower"] = (
    resolution_support["text"]
    .str.lower()
    .fillna("")
)

In [53]:
# routin signals
routing_pattern = (
    r"\bdm\b"
    r"|direct message"
    r"|private message"
    r"|private messaging"
    r"|reach us"
    r"|contact us"
    r"|call us"
    r"|phone"
    r"|chat"
)

resolution_support["has_routing_signal"] = (
    resolution_support["text_lower"]
    .str.contains(routing_pattern, regex=True, na=False)
)

In [54]:
# info gathhering signals
question_signal = (
    resolution_support["text"]
    .str.contains(r"\?", regex=True, na=False)
)

diagnostic_patterns = (
    r"which "
    r"|what "
    r"|when "
    r"|where "
    r"|how "
    r"|have you "
    r"|did you "
    r"|can you "
    r"|could you "
    r"|please.*send"
)

resolution_support["has_diagnostic_signal"] = (
    question_signal
    | resolution_support["text_lower"]
        .str.contains(
            diagnostic_patterns,
            regex=True,
            na=False
        )
)

In [55]:
# action signals
action_patterns = (
    r"try "
    r"|restart"
    r"|reset"
    r"|check "
    r"|select "
    r"|click "
    r"|go to "
    r"|follow "
    r"|install "
    r"|update "
    r"|unplug"
    r"|power"
    r"|clear "
)

resolution_support["has_action_signal"] = (
    resolution_support["text_lower"]
    .str.contains(
        action_patterns,
        regex=True,
        na=False
    )
)

In [56]:
# investigation signals
investigation_patterns = (
    r"look into"
    r"|investigate"
    r"|review"
    r"|internal"
    r"|manager"
    r"|log"
    r"|account"
    r"|details"
    r"|information"
)

resolution_support["has_investigation_signal"] = (
    resolution_support["text_lower"]
    .str.contains(
        investigation_patterns,
        regex=True,
        na=False
    )
)

actionable > investigation > diagnostic > routing > closure

In [57]:
# assign response-level resolution category
resolution_support["resolution_category"] = np.select(
    [
        resolution_support["has_action_signal"],
        resolution_support["has_investigation_signal"],
        resolution_support["has_diagnostic_signal"],
        resolution_support["has_routing_signal"]
    ],
    [
        "ACTIONABLE",
        "CASE_INVESTIGATION",
        "DIAGNOSTIC",
        "ROUTING"
    ],
    default="OTHER"
)

In [58]:
resolution_summary = (
    resolution_support
    .groupby(["author_id", "resolution_category"])
    .size()
    .unstack(fill_value=0)
)

resolution_summary["total_support_responses"] = (
    resolution_summary.sum(axis=1)
)

resolution_categories = [
    "ACTIONABLE",
    "CASE_INVESTIGATION",
    "DIAGNOSTIC",
    "ROUTING",
    "OTHER"
]

for category in resolution_categories:
    if category not in resolution_summary.columns:
        resolution_summary[category] = 0

resolution_summary["substantive_rate_pct"] = (
    (
        resolution_summary["ACTIONABLE"]
        + resolution_summary["CASE_INVESTIGATION"]
        + resolution_summary["DIAGNOSTIC"]
    )
    / resolution_summary["total_support_responses"]
    * 100
).round(2)

resolution_summary = resolution_summary.sort_values(
    "substantive_rate_pct",
    ascending=False
)

print("RESPONSE-LEVEL RESOLUTION SIGNALS")
print("=" * 100)

display(
    resolution_summary[
        [
            "total_support_responses",
            "ACTIONABLE",
            "CASE_INVESTIGATION",
            "DIAGNOSTIC",
            "ROUTING",
            "OTHER",
            "substantive_rate_pct"
        ]
    ]
)

RESPONSE-LEVEL RESOLUTION SIGNALS
====================================================================================================

resolution_category,total_support_responses,ACTIONABLE,CASE_INVESTIGATION,DIAGNOSTIC,ROUTING,OTHER,substantive_rate_pct
author_id,,,,,,,
AppleSupport,106860,20870,20755,35487,19130,10618,72.16
XboxSupport,24557,6386,2911,7391,820,7049,67.96
Tesco,38573,2478,10890,11165,1477,12563,63.60
AmazonHelp,169840,14805,46804,38576,6090,63565,58.99

will explicitly call it something like:

“response-level substantive-resolution signal rate”

Validate Resolution Heuristic (REJECTED)

In [59]:
validation_categories = [
    "ACTIONABLE",
    "CASE_INVESTIGATION",
    "DIAGNOSTIC",
    "ROUTING",
    "OTHER"
]

validation_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Tesco",
    "XboxSupport"
]

for category in validation_categories:

    print("\n")
    print("=" * 110)
    print(f"CATEGORY: {category}")
    print("=" * 110)

    category_examples = (
        resolution_support.loc[
            (resolution_support["author_id"].isin(validation_brands))
            & (
                resolution_support["resolution_category"]
                == category
            ),
            [
                "author_id",
                "text",
                "has_action_signal",
                "has_investigation_signal",
                "has_diagnostic_signal",
                "has_routing_signal"
            ]
        ]
        .sample(
            n=min(
                5,
                (
                    resolution_support[
                        resolution_support["resolution_category"]
                        == category
                    ]
                    .shape[0]
                )
            ),
            random_state=42
        )
    )

    display(category_examples)

==============================================================================================================
CATEGORY: ACTIONABLE
==============================================================================================================

,author_id,text,has_action_signal,has_investigation_signal,has_diagnostic_signal,has_routing_signal
708220,AmazonHelp,@183225 You must have received a correspondence from our team. Kindly check the same here: https://t.co/ubzNHWZvL2 a...,True,False,False,False
281594,AmazonHelp,@192776 Have you had a chance to try uninstalling and reinstalling the skill for the Sonos speaker? ^GR,True,False,True,False
2129483,AmazonHelp,@665365 Thank you for taking time to register your email address. Kindly fill in the form through the link mentioned...,True,False,False,False
98422,AppleSupport,"@143867 We'll do all we can to help. Follow up with us in DM. Tell us how you restored the device, and the type of d...",True,False,True,True
435923,AmazonHelp,@233281 Try reaching us here: https://t.co/hApLpMlfHN ^AP,True,False,False,False

==============================================================================================================
CATEGORY: CASE_INVESTIGATION
==============================================================================================================

,author_id,text,has_action_signal,has_investigation_signal,has_diagnostic_signal,has_routing_signal
64192,AmazonHelp,@133917 Apologies for the inconvenience you've experienced regarding the issue. Could you kindly elaborate on it fur...,False,True,True,False
1826152,AppleSupport,@586666 We know how important having auto correct work properly is. Send us a DM and we'll look into this with you. ...,False,True,True,True
2344230,AmazonHelp,@715702 I’m sorry about the issue you’re facing. Let us look into it. Please share your details (1/2)^HR,False,True,False,False
409712,Tesco,"@226113 Hi there, thanks for getting back to me. I'll ask one of my colleagues to contact the store to investigate t...",False,True,True,False
852112,AppleSupport,@344943 We're happy to help you with this. DM us the details of what you are experiencing here: https://t.co/GDrqU22YpT,False,True,True,True

==============================================================================================================
CATEGORY: DIAGNOSTIC
==============================================================================================================

,author_id,text,has_action_signal,has_investigation_signal,has_diagnostic_signal,has_routing_signal
1767548,AppleSupport,@572114 We're happy to help. Have you checked your restriction settings? Are you sign in with the correct Apple ID? ...,False,False,True,True
1077707,AppleSupport,@400212 We'll be happy to see how we can help. Which iPhone and iOS version are you using?,False,False,True,True
970087,AmazonHelp,@373964 I'm so sorry for the frustration! Who is the carrier for the order? ^DD,False,False,True,False
1546620,AppleSupport,"@196053 Let us help. For a full breakdown of what to do with a possible phishing attempt, please visit: https://t.co...",False,False,True,False
774051,AppleSupport,@325213 We're here to help. DM us what iOS 11 version you're on. https://t.co/GDrqU22YpT,False,False,True,True

==============================================================================================================
CATEGORY: ROUTING
==============================================================================================================

,author_id,text,has_action_signal,has_investigation_signal,has_diagnostic_signal,has_routing_signal
851803,XboxSupport,"@141881 Hi there, if you'd like to request a refund, please contact our chat support team here: https://t.co/lUV7XYl...",False,False,False,True
629913,AppleSupport,@288835 Let's meet up in DM to discuss options related to isolation further at this time. https://t.co/GDrqU22YpT,False,False,False,True
1210040,AmazonHelp,@431402 I'm sorry for the inconvenience on the return of your order. Call us here: https://t.co/vlvfJr4nN9 &amp; we'...,False,False,False,True
1957249,AppleSupport,@623074 Thanks for reaching out. We have a workaround for this here: https://t.co/xXaXeeSRt9 DM us if you still need...,False,False,False,True
618168,AppleSupport,@250275 Updating is a great first step. Let's meet in DM for a closer look at the issue. https://t.co/GDrqU22YpT,False,False,False,True

==============================================================================================================
CATEGORY: OTHER
==============================================================================================================

,author_id,text,has_action_signal,has_investigation_signal,has_diagnostic_signal,has_routing_signal
322209,AmazonHelp,"@203474 I get your concern, please connect with our support team here: https://t.co/TdDksLo6Mf. We'll assist you on ...",False,False,False,False
515226,AmazonHelp,@256800 I understand you want to return your order. You can place a return request here: https://t.co/dgreAZQ5qf. Do...,False,False,False,False
1531427,Tesco,@361095 The correct charge will apply in around 3 days and the £1 will be refunded. This is used to validate your c...,False,False,False,False
2272441,AmazonHelp,"@699165 Late packages have 36 hours past the given delivery date to be delivered. If you don't have it by then, plea...",False,False,False,False
1742310,Tesco,"@388632 Hi Caroline, sorry to see your pumpkin was damaged and mouldy inside. I'd like to refund this for you and pa...",False,False,False,False

- ACTIONABLE is not reliably actionable
- DIAGNOSTIC and ROUTING overlap

current substantive_rate_pct is not trustworthy.

first resolution heuristic was misleading, validated it against real examples and rejected it instead of using a bad metric.

Create conversation-level resolution evidence

In [60]:
resolution_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Tesco",
    "XboxSupport"
]


# Select single-brand conversations
resolution_conversations = (
    brand_conversation_data.loc[
        brand_conversation_data["support_account"].isin(resolution_brands)
    ]
    .copy()
)

print("RESOLUTION EPISODE POOL")
print("=" * 80)

print(
    f"Total candidate conversations : "
    f"{len(resolution_conversations):,}"
)

display(
    resolution_conversations
    .groupby("support_account")
    .size()
    .sort_values(ascending=False)
    .to_frame("conversation_count")
)

RESOLUTION EPISODE POOL
================================================================================
Total candidate conversations : 192,718

                 conversation_count
support_account
AmazonHelp                    82246
AppleSupport                  80552
Tesco                         16566
XboxSupport                   13354

In [61]:
# Build chronological conversation records
resolution_tweets = twcs.loc[
    twcs["conversation_id"].isin(
        resolution_conversations.index
    ),
    [
        "conversation_id",
        "tweet_id",
        "author_id",
        "inbound",
        "created_at_parsed",
        "text"
    ]
].copy()

resolution_tweets = resolution_tweets.sort_values(
    [
        "conversation_id",
        "created_at_parsed",
        "tweet_id"
    ]
)

In [62]:
# helping functions
def first_customer_message(group):
    rows = group[group["inbound"]]

    if rows.empty:
        return None

    return rows.iloc[0]["text"]


def last_customer_message(group):
    rows = group[group["inbound"]]

    if rows.empty:
        return None

    return rows.iloc[-1]["text"]


def first_support_message(group):
    rows = group[~group["inbound"]]

    if rows.empty:
        return None

    return rows.iloc[0]["text"]


def last_support_message(group):
    rows = group[~group["inbound"]]

    if rows.empty:
        return None

    return rows.iloc[-1]["text"]

def conversation_text(group):
    messages = []

    for _, row in group.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "SUPPORT"
        )

        messages.append(
            f"[{speaker}] {row['text']}"
        )

    return "\n".join(messages)

In [63]:
resolution_episodes = (
    resolution_tweets
    .groupby("conversation_id")
    .apply(
        lambda group: pd.Series({
            "first_customer_message": first_customer_message(group),

            "last_customer_message": last_customer_message(group),

            "first_support_message": first_support_message(group),

            "last_support_message": last_support_message(group),

            "conversation_text": conversation_text(group),

            "customer_turns": int(group["inbound"].sum()),

            "support_turns": int((~group["inbound"]).sum()),

            "conversation_size": len(group),

            "start_time": group["created_at_parsed"].min(),

            "end_time": group["created_at_parsed"].max()
        }),
        include_groups=False
    )
)

resolution_episodes["duration_minutes"] = (
    (
        resolution_episodes["end_time"]
        - resolution_episodes["start_time"]
    )
    .dt.total_seconds()
    / 60
)

In [64]:
# Add brand
resolution_episodes = resolution_episodes.join(
    resolution_conversations[["support_account"]],
    how="left"
)

print("\nRESOLUTION EPISODES CREATED")
print("=" * 80)

print(
    f"Resolution episodes : "
    f"{len(resolution_episodes):,}"
)

print(
    f"Columns              : "
    f"{len(resolution_episodes.columns)}"
)

display(
    resolution_episodes.head(3)
)

RESOLUTION EPISODES CREATED
================================================================================
Resolution episodes : 192,718
Columns              : 12

,first_customer_message,last_customer_message,first_support_message,last_support_message,conversation_text,customer_turns,support_turns,conversation_size,start_time,end_time,duration_minutes,support_account
conversation_id,,,,,,,,,,,,
272,amazonのfireTVstickが見れない😢,@AmazonHelp こちらこそありがとうございました。,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pb...,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET,[CUSTOMER] amazonのfireTVstickが見れない😢\n[SUPPORT] @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシ...,4,3,7,2017-11-22 09:14:39+00:00,2017-11-22 10:06:26+00:00,51.783333,AmazonHelp
277,"@XboxSupport can I change me sons Xbox live account to his Hotmail account, currently linked to my Hotmail account","@XboxSupport can I change me sons Xbox live account to his Hotmail account, currently linked to my Hotmail account","@115771 Hi, you can change your Microsoft account email through the steps here: https://t.co/DkEhOHbOYy . If the ema...","@115771 Hi, you can change your Microsoft account email through the steps here: https://t.co/DkEhOHbOYy . If the ema...","[CUSTOMER] @XboxSupport can I change me sons Xbox live account to his Hotmail account, currently linked to my Hotmai...",1,1,2,2017-12-02 09:17:57+00:00,2017-12-02 18:06:03+00:00,528.100000,XboxSupport
318,@XboxSupport @115786 @115787 @15913 can anyone let me know when our pre orders are going to be shipped for xbox one x??,"@XboxSupport @115786 Kinda need to make sure I have 680$ cdn in my bank, so would be nice to know.. I dun just have ...",@115785 Hi there! We'd recommend reaching out to the chat team here: https://t.co/UrUi80i54l ^JA,"@115785 @115786 Did you pre-order this console via the Microsoft store? If so, then let's have you reach out here: h...",[CUSTOMER] @XboxSupport @115786 @115787 @15913 can anyone let me know when our pre orders are going to be shipped fo...,7,3,10,2017-10-31 20:03:55+00:00,2017-11-01 01:13:10+00:00,309.250000,XboxSupport

- Customer/support turns are separated.
- Conversations are chronologically ordered.
- The episodes retain the support brand.

Stratified Resolution Screening Sample

In [65]:
resolution_episodes["size_bucket"] = pd.cut(
    resolution_episodes["conversation_size"],
    bins=[0, 2, 4, 8, np.inf],
    labels=[
        "2_tweets",
        "3_to_4_tweets",
        "5_to_8_tweets",
        "9_plus_tweets"
    ],
    include_lowest=True
)

In [66]:
# Sample from each brand × conversation-size bucket
sample_per_bucket = 8

sampled_groups = []

for (brand, bucket), group in resolution_episodes.groupby(
    ["support_account", "size_bucket"],
    observed=True
):

    n_sample = min(sample_per_bucket, len(group))

    if n_sample == 0:
        continue

    sampled = group.sample(
        n=n_sample,
        random_state=42
    ).copy()

    # The conversation_id is the INDEX of resolution_episodes.
    # Explicitly convert that index into a column.
    sampled["conversation_id"] = sampled.index

    # Explicitly preserve grouping information.
    sampled["support_account"] = brand
    sampled["size_bucket"] = bucket

    sampled_groups.append(sampled)

In [67]:
# combine sampled conversations
resolution_screening_sample = pd.concat(
    sampled_groups,
    axis=0,
    ignore_index=True
)

In [68]:
# select inspection columns
screening_columns = [
    "conversation_id",
    "support_account",
    "size_bucket",
    "conversation_size",
    "customer_turns",
    "support_turns",
    "duration_minutes",
    "first_customer_message",
    "last_customer_message",
    "first_support_message",
    "last_support_message",
    "conversation_text"
]

resolution_screening_sample = (
    resolution_screening_sample[
        screening_columns
    ]
    .sort_values(
        [
            "support_account",
            "size_bucket",
            "conversation_id"
        ]
    )
    .reset_index(drop=True)
)

In [69]:
# report sample
print("RESOLUTION SCREENING SAMPLE")
print("=" * 90)

print(
    f"Sampled conversations : "
    f"{len(resolution_screening_sample):,}"
)

print(
    f"Brands                : "
    f"{resolution_screening_sample['support_account'].nunique()}"
)

print("\nSAMPLE SIZE BY BRAND")
print("=" * 90)

display(
    resolution_screening_sample
    .groupby("support_account")
    .size()
    .to_frame("sample_count")
)

print("\nSAMPLE SIZE BY BRAND × CONVERSATION SIZE")
print("=" * 90)

display(
    resolution_screening_sample
    .groupby(
        ["support_account", "size_bucket"],
        observed=True
    )
    .size()
    .to_frame("sample_count")
)

RESOLUTION SCREENING SAMPLE
==========================================================================================
Sampled conversations : 128
Brands                : 4

SAMPLE SIZE BY BRAND
==========================================================================================

                 sample_count
support_account
AmazonHelp                 32
AppleSupport               32
Tesco                      32
XboxSupport                32

SAMPLE SIZE BY BRAND × CONVERSATION SIZE
==========================================================================================

                               sample_count
support_account size_bucket
AmazonHelp      2_tweets                  8
                3_to_4_tweets             8
                5_to_8_tweets             8
                9_plus_tweets             8
AppleSupport    2_tweets                  8
                3_to_4_tweets             8
                5_to_8_tweets             8
                9_plus_tweets             8
Tesco           2_tweets                  8
                3_to_4_tweets             8
                5_to_8_tweets             8
                9_plus_tweets             8
XboxSupport     2_tweets                  8
                3_to_4_tweets             8
                5_to_8_tweets             8
                9_plus_tweets             8

Display Resolution Annotation Batch

In [70]:
# Take the first 20 conversations for manual screening.
annotation_batch = (
    resolution_screening_sample
    .head(20)
    .copy()
)

print("RESOLUTION ANNOTATION BATCH")
print("=" * 100)

for _, row in annotation_batch.iterrows():

    print("\n" + "=" * 100)

    print(
        f"Conversation ID : {row['conversation_id']}"
    )

    print(
        f"Brand           : {row['support_account']}"
    )

    print(
        f"Size            : {row['conversation_size']} tweets"
    )

    print(
        f"Customer turns  : {row['customer_turns']}"
    )

    print(
        f"Support turns   : {row['support_turns']}"
    )

    print(
        f"Duration        : {row['duration_minutes']:.1f} minutes"
    )

    print("-" * 100)

    print(row["conversation_text"])

RESOLUTION ANNOTATION BATCH
====================================================================================================

====================================================================================================
Conversation ID : 227908
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 29.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 My issue is contained in the below pic. Please look into it and reply. https://t.co/j9pvkXhaa5
[SUPPORT] @170338 Allow us to take a closer look. Please call us here: https://t.co/vlvfJr4nN9 for live assistance. ^HK

====================================================================================================
Conversation ID : 236650
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 9.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Le plus marrant c'est que j'ai vu le livreur avec le colis en bas et j'ai demandé, il m'a dit "Non le colis est pas pour vous".
@120533 https://t.co/F5H41AXRll
[SUPPORT] @172357 Bonjour Loïck, je suis désolée pour cela. L'avez-vous signalé à notre SAV? ^SM

====================================================================================================
Conversation ID : 377207
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 83.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 just gt a call frm delivery person regarding where my address is. Yes at 7:58 in the mrning. What a great way to wakeup! #scarcasm
[SUPPORT] @205509 Apologies for the inconvenience with the delivery. I'll forward this as a feedback internally to the concerned teams. ^ST

====================================================================================================
Conversation ID : 474254
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 13.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115830 Hi there, having a bit of problem. I received an email saying that my delivery has been delivered, but because it was sent to my work address and after office hours.. not too sure where the delivery man has left it? it's no where to be seen.
[SUPPORT] @227883 Sorry to hear that. We'll be happy to look into for you. Please reach out to us here: https://t.co/JzP7hlA23B ^RS

====================================================================================================
Conversation ID : 583523
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 7.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Dear @115821, time to up your shipping game.  I’m good paying for Prime, but paying for 2 day shipping, then getting something in 5 days (or more) is not cool.  Go back to using only @115817.
[SUPPORT] @257626 I'm sorry for the frustration, Lauren, but we're here to help! Our shipping speeds start when the item ships. We aim to meet the delivery date given in checkout/confirmation e-mail. Are we missing this date? You can find this info here: https://t.co/6gnop11w6Z ^KN

====================================================================================================
Conversation ID : 1678016
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 4.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Vous êtes sérieux @120533 de livrer ça dans cet état ?? https://t.co/4PLAp7wGD9
[SUPPORT] @510378 Bonjour,désolée pour cela😓
Je vous prie de le signaler à notre SAV: https://t.co/hgIrz98cdI afin qu'il fasse le nécessaire.^FT

====================================================================================================
Conversation ID : 2276470
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 17.6 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115830 hi, is it possible to redirect an order to an amazon locker after it's been despatched? Thanks!
[SUPPORT] @662093 We can see what options are available. Reach us by phone or chat to go over details: https://t.co/JzP7hlA23B ^MG

====================================================================================================
Conversation ID : 2598545
Brand           : AmazonHelp
Size            : 2 tweets
Customer turns  : 1
Support turns   : 1
Duration        : 14.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Amazon Prime Musicで音楽聴きながら作業して捗る
[SUPPORT] @735688 ご利用いただきありがとうございます😊✨SK

====================================================================================================
Conversation ID : 210399
Brand           : AmazonHelp
Size            : 4 tweets
Customer turns  : 2
Support turns   : 2
Duration        : 15.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp please help me make my dreams of being a pumpkin for Halloween come true https://t.co/VA2eaeKt8Y
[SUPPORT] @165799 I'm sorry for the trouble! Was your costume being shipped from us or a third-party seller: https://t.co/PCtircFm5C?  ^GL
[CUSTOMER] @AmazonHelp Description says it was supposed to be fulfilled by Amazon https://t.co/VQjiilTo1q
[SUPPORT] @165799 Please contact us directly via phone or chat here: https://t.co/hApLpMlfHN ^NC

====================================================================================================
Conversation ID : 268721
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 2
Support turns   : 1
Duration        : 76.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @119625 video quality is horrible for the game.
[SUPPORT] @180068 Apologies for the inconvenience. Could you please help us with the cast of the movie? We'll get this checked. ^HD
[CUSTOMER] @AmazonHelp NFL game it got better

====================================================================================================
Conversation ID : 366006
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 1
Support turns   : 2
Duration        : 147.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 1 hour to process amazon pay balance into the account !! Seriously?? Order no : 405-7666923-7204367 @AmazonHelp
[SUPPORT] @202714 Sorry about the delay. Connect with our support team here: https://t.co/vlvfJr4nN9, we'll assist you regarding this. ^NR 1/2
[SUPPORT] @202714 Please don't provide your order details, we consider it personal info. Our Twitter page is visible to public. ^NR 2/2

====================================================================================================
Conversation ID : 709030
Brand           : AmazonHelp
Size            : 4 tweets
Customer turns  : 2
Support turns   : 2
Duration        : 48.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp ordered a pop vinyl on @115821 and the body isn't attached properly and it doesn't stand up?!?! @289525
[SUPPORT] @289524 Oh no! We're here to help. Just to clarify, can you tell us where you ordered this from?(https://t.co/hSs9w9f1pF,.ca,.co.uk)^AL
[CUSTOMER] @AmazonHelp https://t.co/vtLvUjSjSb
[SUPPORT] @289524 You can check the available return/replacement options here: https://t.co/aaDyEz1VgE ^ME

====================================================================================================
Conversation ID : 842214
Brand           : AmazonHelp
Size            : 4 tweets
Customer turns  : 2
Support turns   : 2
Duration        : 32.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 take a bow sir. I ordrd product at Noida address and u dlvrd it to Maharashtra to some unknown person. Why unnecessarily troubling
[SUPPORT] @320325 Apologies for the ordeal. Did you happen to escalate this to our support team here: https://t.co/T6y6Xlutbs? ^VN
[CUSTOMER] @AmazonHelp From past 1 hr I am trying to connect but did not receive any call
[SUPPORT] @320325 Sorry for the hassle. You can also choose to call us or drop an email to us Himanshu. ^HN

====================================================================================================
Conversation ID : 2159283
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 1
Support turns   : 2
Duration        : 19.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp What kind of prime service u are giving to customers to 1 day delivery as promised order id 4__credit_card__
[SUPPORT] @634246 Could you confirm if we happened to miss the estimate as mentioned here: https://t.co/ykWpCt0ely ? ^KA
[SUPPORT] @634246 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. ^KA

====================================================================================================
Conversation ID : 2684289
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 2
Support turns   : 1
Duration        : 17.0 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Hey @AmazonHelp warum ist das Spiel Monopoly für die Switch plötzlich ca. 10 Euro teurer? #nerv
[SUPPORT] @754979 Hi, wir konnten den genannten Artikel kurze Zeit günstiger anbieten. Der Grund dafür ist mir aber nicht bekannt. Gruß ^JS
[CUSTOMER] @AmazonHelp Schade .... dann wird er woanders gekauft.

====================================================================================================
Conversation ID : 2802385
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 2
Support turns   : 1
Duration        : 9.4 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115821 my package was supposed to be delivered today and it wasn’t :-(
[SUPPORT] @781734 I'm so sorry your package hasn't arrived! Can you please let us know who the carrier is? You can check here: https://t.co/Y5jpI9gRhE ^EB
[CUSTOMER] @AmazonHelp UPS!

====================================================================================================
Conversation ID : 183065
Brand           : AmazonHelp
Size            : 5 tweets
Customer turns  : 3
Support turns   : 2
Duration        : 38.2 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp help please my order is out for delivery but it hasn’t arrived and it seems to have changed on the website ? Help thanks
[SUPPORT] @159053 Oh no! What does the tracking status say here? https://t.co/aaDyEz1VgE Were you given a new estimated delivery date? ^FD
[CUSTOMER] @AmazonHelp Can I dm you to show what it says thanks
[SUPPORT] @159053 Orders can be delivered until 21:00. Please keep us posted on your order. ^VS
[CUSTOMER] @AmazonHelp It’s arrived  thank you

====================================================================================================
Conversation ID : 285629
Brand           : AmazonHelp
Size            : 6 tweets
Customer turns  : 4
Support turns   : 2
Duration        : 29.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I love how I pay for Prime and my package that I really needed in 2 days is going to take over a week to get to me @AmazonHelp 👎🏼👎🏼👎🏼
[SUPPORT] @184039 We're here to help! Have we missed our expected delivery date we provided? Check here: https://t.co/Y5jpI9gRhE ^JE
[CUSTOMER] @AmazonHelp I ordered it Tuesday. Said it would be here today. Now it says next Wednesday.
[CUSTOMER] @184039 @AmazonHelp GET THEM STONE! Drag em
[CUSTOMER] @184040 @AmazonHelp Lmaoooo its so much easier to tweet at company’s help accounts than email them 😭😭😭
[SUPPORT] @184039 Let us know if it doesn't arrive by the new estimated delivery date! ^VB

====================================================================================================
Conversation ID : 386800
Brand           : AmazonHelp
Size            : 6 tweets
Customer turns  : 3
Support turns   : 3
Duration        : 35.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115821 I'm trying to figure out why do I PAY for amazon prime and 2 items I ordered a WEEK ago haven't arrived and I was supposed to receive in 2 days 😡😡
[SUPPORT] @207570 I'm sorry for the trouble, Jonique! Have we missed the estimated delivery date provided at checkout/in your e-mail? ^FD
[CUSTOMER] @AmazonHelp Yes, I was supposed to receive it on the 2nd...today is the 9th
[SUPPORT] @207570 Oh no! Can you verify if there's any tracking updates for this order? You can check that info here:https://t.co/Y5jpI9gRhE ^AL
[CUSTOMER] @AmazonHelp It now says from the 4 but again it's the 9th...no further updates and I need those items
[SUPPORT] @207570 Please reach us via phone/chat so we can look closer in to this together: https://t.co/hApLpMlfHN Keep us posted, Jonique! ^KN

====================================================================================================
Conversation ID : 685687
Brand           : AmazonHelp
Size            : 5 tweets
Customer turns  : 3
Support turns   : 2
Duration        : 45.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @119625  ray donovan season 5 not on amazon only up to 4 when you will add up
[SUPPORT] @207168 We will continue to add new content. Keeping checking https://t.co/FYM9PIZOR8 where we highlight the latest movies and TV shows we have available. ^HS
[CUSTOMER] @AmazonHelp If you're adding some content then give it with full  season
[CUSTOMER] @AmazonHelp Not half
[SUPPORT] @207168 Fair enough, Sushant. I'll be sure to share this feedback internally with the right team. ^JC

In [71]:
annotation_batch = (
    resolution_screening_sample
    .groupby("support_account", group_keys=False)
    .apply(
        lambda group: group.sample(
            n=5,
            random_state=42
        ),
        include_groups=True
    )
    .reset_index(drop=True)
)

print("BALANCED RESOLUTION ANNOTATION BATCH")
print("=" * 100)

print(
    f"Total conversations : {len(annotation_batch):,}"
)

print("\nCONVERSATIONS PER BRAND")
print("=" * 100)

display(
    annotation_batch
    .groupby("support_account")
    .size()
    .to_frame("count")
)

BALANCED RESOLUTION ANNOTATION BATCH
====================================================================================================
Total conversations : 20

CONVERSATIONS PER BRAND
====================================================================================================

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3238689582.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

                 count
support_account
AmazonHelp           5
AppleSupport         5
Tesco                5
XboxSupport          5

In [72]:
for _, row in annotation_batch.iterrows():

    print("\n" + "=" * 100)

    print(
        f"Conversation ID : {row['conversation_id']}"
    )

    print(
        f"Brand           : {row['support_account']}"
    )

    print(
        f"Size            : {row['conversation_size']} tweets"
    )

    print(
        f"Customer turns  : {row['customer_turns']}"
    )

    print(
        f"Support turns   : {row['support_turns']}"
    )

    print(
        f"Duration        : {row['duration_minutes']:.1f} minutes"
    )

    print("-" * 100)

    print(row["conversation_text"])

====================================================================================================
Conversation ID : 1666514
Brand           : AmazonHelp
Size            : 12 tweets
Customer turns  : 6
Support turns   : 6
Duration        : 3091.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115833 when can I set recurring reminders on Alexa?
[SUPPORT] @161011 Our support team would be happy to help you out with your query! Please contact us from here: https://t.co/vlvfJr4nN9. ^MP
[CUSTOMER] @AmazonHelp Getting the following error while trying to get to the URL. https://t.co/RGEjkbxQg8
[SUPPORT] @161011 I've checked and seen the link is working fine. Kindly try accessing it here:  https://t.co/2t6DQoUmNZ again. ^AP
[CUSTOMER] @AmazonHelp Done, thanks!
[SUPPORT] @161011 You're welcome. Please keep us posted for further concerns. ^BS
[CUSTOMER] @AmazonHelp Looks like recurring reminders are not possible for now :( That's quite disappointing. Google calendar integration?
[SUPPORT] @161011 I'm sorry I couldn't comprehend your concern. Kindly elaborate. ^HR
[CUSTOMER] @AmazonHelp Is there a way I can set up some recurring reminder on Google calendar and make Alexa pick it up?
[SUPPORT] @161011 I get your concern. However, we do not have any such feature as of now. Please stay tuned for new updates and features. ^KH
[CUSTOMER] @AmazonHelp Does that mean this will be a candidate for future release, or is it just generic reference to new features that I may not necessarily be interested in?
[SUPPORT] @161011 As informed earlier, we don't have that feature at this moment, stay tuned for updates. ^SU

====================================================================================================
Conversation ID : 2802385
Brand           : AmazonHelp
Size            : 3 tweets
Customer turns  : 2
Support turns   : 1
Duration        : 9.4 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115821 my package was supposed to be delivered today and it wasn’t :-(
[SUPPORT] @781734 I'm so sorry your package hasn't arrived! Can you please let us know who the carrier is? You can check here: https://t.co/Y5jpI9gRhE ^EB
[CUSTOMER] @AmazonHelp UPS!

====================================================================================================
Conversation ID : 34503
Brand           : AmazonHelp
Size            : 10 tweets
Customer turns  : 5
Support turns   : 5
Duration        : 90.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] fico impressionado com a rapidez da @117086 nos envios dos pedidos, comprei ontem e já tá em transporte 💙 amo demais
[SUPPORT] @123478 Eitaa quais livros comprou 😍? ^MB
[CUSTOMER] @AmazonHelp Comprei 9, trilogia Crônicas de Amor e Ódio, Fronteiras do Universos 1 e 3, Estamos Bem, Contos de Horror séc XIX, Carry On e A longa Viagem
[SUPPORT] @123478 O seu coração bate mais forte quando você passa na frente de uma livraria? 😊💞 ^VL
[CUSTOMER] @AmazonHelp Com certeza e é quase impossível eu não entrar hahah 💙
[SUPPORT] @123478 As pessoas costumam te perguntar quantos livros você já leu? 🙊 ^VL
[CUSTOMER] @AmazonHelp Sim! Principalmente quando olham minha estante dizem "nooossa você já leu quantos desses?"
[SUPPORT] @123478 Nossa! manda uma foto dessa estante maravilhosa para gente 🤗. ^AZ
[CUSTOMER] @AmazonHelp Olha ela aí 💙 https://t.co/9I5Av2Lv7i
[SUPPORT] @123478 Eita nossa, amei tanto que quero um igual! ❤ ^DA

====================================================================================================
Conversation ID : 285629
Brand           : AmazonHelp
Size            : 6 tweets
Customer turns  : 4
Support turns   : 2
Duration        : 29.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I love how I pay for Prime and my package that I really needed in 2 days is going to take over a week to get to me @AmazonHelp 👎🏼👎🏼👎🏼
[SUPPORT] @184039 We're here to help! Have we missed our expected delivery date we provided? Check here: https://t.co/Y5jpI9gRhE ^JE
[CUSTOMER] @AmazonHelp I ordered it Tuesday. Said it would be here today. Now it says next Wednesday.
[CUSTOMER] @184039 @AmazonHelp GET THEM STONE! Drag em
[CUSTOMER] @184040 @AmazonHelp Lmaoooo its so much easier to tweet at company’s help accounts than email them 😭😭😭
[SUPPORT] @184039 Let us know if it doesn't arrive by the new estimated delivery date! ^VB

====================================================================================================
Conversation ID : 210399
Brand           : AmazonHelp
Size            : 4 tweets
Customer turns  : 2
Support turns   : 2
Duration        : 15.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp please help me make my dreams of being a pumpkin for Halloween come true https://t.co/VA2eaeKt8Y
[SUPPORT] @165799 I'm sorry for the trouble! Was your costume being shipped from us or a third-party seller: https://t.co/PCtircFm5C?  ^GL
[CUSTOMER] @AmazonHelp Description says it was supposed to be fulfilled by Amazon https://t.co/VQjiilTo1q
[SUPPORT] @165799 Please contact us directly via phone or chat here: https://t.co/hApLpMlfHN ^NC

====================================================================================================
Conversation ID : 2037763
Brand           : AppleSupport
Size            : 10 tweets
Customer turns  : 9
Support turns   : 1
Duration        : 91.2 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I️ don’t know why I️ laughed as hard as I️ dis but here we are https://t.co/9fJas3g6Zv
[CUSTOMER] @602528 Are you running iOS 11.0 by any chance? https://t.co/UscNfmF4MS
[CUSTOMER] @602527 sadly i am..I’ve been looking for work arounds
[CUSTOMER] @602528 Update to 11.1?
[CUSTOMER] @602527 sorry just checked again I’m up to 11.1. Something else I’m missing out on?
[CUSTOMER] @602528 So weird, in your previous tweets the letter “I” appears as that weird question mark block on my screen. I updated to 11.1 and my twitter app just to make sure it wasn’t me 😒
[CUSTOMER] @602527 yeah I just looked at that. Very confusing...and I don’t like it one bit
[CUSTOMER] @602528 @AppleSupport fix this please. We are both running 11.1. I don’t understand why I’m seeing the question mark block in place of the letter “I”
[SUPPORT] @602527 Thanks for reaching out. We have a workaround for this here: https://t.co/xXaXeeSRt9 DM us if you still need help. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @602528 I guess the only solution for now is this workaround. Get it together, Apple!

====================================================================================================
Conversation ID : 2857301
Brand           : AppleSupport
Size            : 3 tweets
Customer turns  : 2
Support turns   : 1
Duration        : 63.4 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115858 @AppleSupport y'all are pretty sus eating up 7 GB of unmarked space on my phone
[SUPPORT] @794127 We'd be happy to look into this with you.  Please reach out to us via DM and we'll get started. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @794127 if you don't follow through with this you're a uniformed police officer

====================================================================================================
Conversation ID : 1037659
Brand           : AppleSupport
Size            : 9 tweets
Customer turns  : 6
Support turns   : 3
Duration        : 738.0 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport my camera roll folder shows zero pics all of a sudden, how do I retrieve them back ?? Kindly reply asap
[SUPPORT] @365471 We know how important your photos can be to you. We're here to help. Which iOS version is your device currently running?
[CUSTOMER] @AppleSupport 11.3
[CUSTOMER] @AppleSupport 11.3 ios
[CUSTOMER] @AppleSupport 11.0.3
[CUSTOMER] @AppleSupport Been facing wierd problems with camera roll, since ios 11.... deletion restoration, blurry screen shots n etc etc
[SUPPORT] @365471 How long ago did you update your device to iOS 11.0.3?
[CUSTOMER] @AppleSupport As soon as it was launched
[SUPPORT] @365471 Thanks for letting us know. Let's continue this conversation in a DM. https://t.co/GDrqU22YpT

====================================================================================================
Conversation ID : 1174774
Brand           : AppleSupport
Size            : 6 tweets
Customer turns  : 3
Support turns   : 3
Duration        : 1495.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Why would this be @AppleSupport ?? I’ve tried three times and says the same 😤 https://t.co/9XRmxCFuAR
[SUPPORT] @396316 We want to help. Have you tried updating via iTunes on a computer?  Have you tried restarting your device?
[CUSTOMER] @AppleSupport I’m unable to plug my phone into a computer currently however I have tried to restart and I’m still seeing the same error!
[SUPPORT] @396316 Have you tried updating via another Wi-Fi network?
[CUSTOMER] @AppleSupport This worked! Thank you 😊
[SUPPORT] @396316 Excellent!  We are glad that you are all set.  Contact us again if you need further assistance.  We are here for you.

====================================================================================================
Conversation ID : 1248350
Brand           : AppleSupport
Size            : 4 tweets
Customer turns  : 3
Support turns   : 1
Duration        : 320.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] you do it’s starts freezing and not working and closing apps while you’re in them and all kinds crazy stuff.. Why is that @115858 ? Smh 🤔🤔
[CUSTOMER] @412883 @115858 It won’t let me update it and I’m getting charged for 4G data use 😡
[SUPPORT] @412881 Thanks for reaching out. We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @412881 It’s happening to mine as well.

====================================================================================================
Conversation ID : 1842494
Brand           : Tesco
Size            : 14 tweets
Customer turns  : 8
Support turns   : 6
Duration        : 232.0 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Shocking 2 find you can't return a faulty item in a 24hr store after 10pm @Tesco. Shouldn't be 24hr if you can't offer every service.
[SUPPORT] @552135 Hi there, did you ask if a manager could do this for you? They may have been able to see if they could resolve this for you - Allyn
[CUSTOMER] @Tesco I spoke to the manager on the phone 940 she was finishing at 10. No staff trained in refunds after this. Most helpful was the security guard
[CUSTOMER] @Tesco It was a cracked TV screen. Had to then buy another one with the option of returning to store again today to refund the original
[CUSTOMER] @Tesco Shocking management if you're open 24 hours a day but only for basic things
[SUPPORT] @552135 I am very sorry about this, please could you advise what store you visited? - Allyn
[CUSTOMER] @Tesco Walsall Extra
[CUSTOMER] @Tesco Can you advise, is this Company policy or solely an inept MGMT team at the branch?
[SUPPORT] @552135 Hi there, I have checked on this for you. It is due to the type of product it is. 1/2
[SUPPORT] @552135 The process of returning a TV needs to go through the helpline and they can only do up until 10pm - Allyn 2/2
[CUSTOMER] @Tesco So why allow these to be sold after 10pm?
[SUPPORT] @552135 Hi, the reason why we can sell after 10pm is all electric items can be purchased 24 hours.
[SUPPORT] @552135 For returns and faults our customers must contact the electrical helpline so we can determine whether the items can be repaired - David
[CUSTOMER] @Tesco Ok but a bit of common sense  would suggest a cracked screen won't be repaired

====================================================================================================
Conversation ID : 2273718
Brand           : Tesco
Size            : 4 tweets
Customer turns  : 1
Support turns   : 3
Duration        : 88.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Bought Tadcaster Road, York. Entire loaf has a nice hole through the middle. Was supposed to be the perfect post @80601 brekky :( https://t.co/QzNbtzGKvk
[SUPPORT] @661359 Hi Phil, I'm sorry your loaf has a hole running through it, I appreciate how disappointing this must be for you. Please DM me your full name, address and email address so I can refund you via Tesco Moneycard and inform our supplier? 1/3
[SUPPORT] @661359 Would you mind your details being passed to our supplier in case they wish to contact you directly for feedback? Would you prefer your Moneycard to be sent by email (can be printed or scanned off a smart phone) or in the post? 2/3
[SUPPORT] @661359 Can you also message the barcode, use by date, SC code (eg.SC1234) and batch code from the packaging along with the price you paid? A full photo of the receipt would also be helpful if you still have it. Thanks - Clare 3/3

====================================================================================================
Conversation ID : 143038
Brand           : Tesco
Size            : 14 tweets
Customer turns  : 10
Support turns   : 4
Duration        : 6344.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Very useful charge at Tesco Extra, Crawley. Quickly to 80% from 20% on Leaf with ABB rapid charger at 24p per kWh. Great facility. Thanks @Tesco &amp; @122417 (just behind the click+collect by the petrol station, for anyone looking. ) https://t.co/00Yn4SgYZK
[SUPPORT] @148298 It's great that your finding the facilities so useful 🙌 Would there be anyway they could be improved or anything you'd like to see added?
[CUSTOMER] @Tesco It’s early days, yet, but probably plan for 3 or 4 rapid chargers near the petrol station &amp; 20+ 7 kW chargers in the main car park, over next couple of years. Many people will do what I did, rapid charge &amp; finish charging on the slow chargers while we shop. Great facility, thanks https://t.co/GywjB8Prum
[SUPPORT] @148298 It'll be the norm before long 😊 Thanks for your input though, it's much appreciated! Have a good one 👍
[CUSTOMER] @148298 @Tesco How much does it cost to ‘fill up’ your car and how far will it get you?
[CUSTOMER] @Tesco @148298 Can we have some 7kw chargers at the Winchester store please @Tesco? Was disappointed you didn't install with recent car park works and store refresh.
[SUPPORT] @148299 Hi Sean, please can you provide us with your name, address &amp; email via DM? We can then log your interest in seeing this. - Rocsi https://t.co/py5Z991Bme
[CUSTOMER] @Tesco @148298 Any chance of some rapid chargers at Northern Ireland stores?
[CUSTOMER] @148300 @Tesco @148298  https://t.co/Q2G99O91Vc
[CUSTOMER] @148301 @Tesco @148298 Is that Heather Locklear's hair on the right?
[CUSTOMER] @Tesco @148298 Any chance of branching out to Scottish stores? Would be well received North of the wall :-)
[CUSTOMER] @148303 @Tesco We havenae rebuilt the wall yet.
[SUPPORT] @148303 Hi there, we don't actually have an exact date to when they will make their way up to Scotland. But it is starting to branch out into more and more stores. So hopefully they will be available in the near future. Thanks, Calum
[CUSTOMER] @Tesco Ok, thanks. Sooner, the better! Ones in my town are closest to an Aldi and an Asda, so you'd be doing yourselves a favour :-)

====================================================================================================
Conversation ID : 852099
Brand           : Tesco
Size            : 7 tweets
Customer turns  : 3
Support turns   : 4
Duration        : 259.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco at Stroud is getting terrible last week yogurts 3days out of date this week mouldy peppers!!
[SUPPORT] @322410 Hi Georgia, I'm very sorry to hear this, that is very disappointing! 1/3
[SUPPORT] @322410 Also were the peppers loose or packed and did you purchase any of these items? Thanks Calum 3/3
[SUPPORT] @322410 Please could you tell exactly which store in Stroud this is and I can contact the store and get this sorted? 2/3
[CUSTOMER] @Tesco Stroud main store , I gave both items to customer services desk ,the peppers where packed
[SUPPORT] @322410 Hi Georgia, as you have returned this to the store they will feedback to our supplier for a quality inspection. Ty - Darren
[CUSTOMER] @Tesco Ok Thankyou

====================================================================================================
Conversation ID : 56046
Brand           : Tesco
Size            : 4 tweets
Customer turns  : 1
Support turns   : 3
Duration        : 61.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Wondering why no @2951 goats butter on shelves in @117250 or @Tesco in last weeks. When will it be back? Alternative suppliers?
[SUPPORT] @128719 Hi Nick, I am sorry to hear you can't find this product. 1/3
[SUPPORT] @128719 I have checked with my support team and they have informed me we a currently having supplier issues 2/3
[SUPPORT] @128719 There might still be product in other stores can you DM me your postcode and I can check, Ty, Andy 3/3

====================================================================================================
Conversation ID : 1613716
Brand           : XboxSupport
Size            : 9 tweets
Customer turns  : 5
Support turns   : 4
Duration        : 139.6 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I just sent u a dm with a message on it,it was too long for me to pop in a tweet so I dm it u,please could u check it out?
[SUPPORT] @495044 Hi there, you'll want to ensure you're following the steps here: https://t.co/s9FfQ6hpAz to change your  1 ^ZM
[SUPPORT] @495044 Microsoft account email address as they may help with what you're experiencing there. :)  2 ^ZM
[CUSTOMER] @XboxSupport if i was to remove the original email inked with the account tho would it affect my xbox live signing in or would it change the the new
[CUSTOMER] @XboxSupport email because at the minute my xbox account still has the old email come up when i sign in,not the new email that is now my primary alias?
[SUPPORT] @495044 It's stating that you wouldn't be able to use it to sign in. You would have to use the other Alias instead. ^CO
[CUSTOMER] @XboxSupport I’m confused,it doesn’t exactly make it that clear if I’m honest😂,what does this mean then? Does it mean that I would use the original email
[CUSTOMER] @XboxSupport To sign in on my Xbox or would it be the new email I’d just created and made my primary alias?
[SUPPORT] @495044 It's just reminding you to no longer use the original e-mail for login and you may need to log back into consoles. ^CO

====================================================================================================
Conversation ID : 2355974
Brand           : XboxSupport
Size            : 4 tweets
Customer turns  : 3
Support turns   : 1
Duration        : 1032.2 minutes

AmazonHelp has substantial operational support, but many public responses route customers elsewhere.

AppleSupport has strong diagnostic/troubleshooting behavior and some confirmed outcomes.

Tesco shows particularly strong case-action behavior.

XboxSupport has concrete technical troubleshooting and investigation.

NON_SUPPORT, ROUTING_ONLY, DIAGNOSTIC, ACTIONABLE_GUIDANCE, CASE_ACTION, CONFIRMED_OUTCOME, UNRESOLVED, AMBIGUOUS

Create human annotation sheet for resolution screening

In [73]:
from pathlib import Path

# Project root = parent of the notebooks directory
PROJECT_ROOT = Path.cwd().parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

annotation_cols = [
    "conversation_id",
    "support_account",
    "size_bucket",
    "conversation_size",
    "customer_turns",
    "support_turns",
    "duration_minutes",
    "conversation_text",
]

resolution_screening_annotations = (
    resolution_screening_sample[annotation_cols]
    .copy()
)

# Human annotation fields
resolution_screening_annotations["resolution_label"] = ""
resolution_screening_annotations["annotation_notes"] = ""
resolution_screening_annotations["annotator"] = "human"

# Save
annotation_path = (
    PROCESSED_DIR / "resolution_screening_annotations.csv"
)

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Project root:", PROJECT_ROOT)
print("Saved:", annotation_path)
print("Rows:", len(resolution_screening_annotations))
print("Columns:", resolution_screening_annotations.columns.tolist())

Project root: d:\BECAME_DEVELOPER\hiver-sde-ai-agent
Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\resolution_screening_annotations.csv
Rows: 128
Columns: ['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

In [74]:
from pathlib import Path
import pandas as pd

annotation_path = (
    Path.cwd().parent
    / "data"
    / "processed"
    / "resolution_screening_annotations.csv"
)

resolution_screening_annotations = pd.read_csv(annotation_path)

# Show the first 20 conversations for manual review
batch_1 = resolution_screening_annotations.iloc[:20].copy()

print("Batch size:", len(batch_1))
print("Total conversations:", len(resolution_screening_annotations))

for i, row in batch_1.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Total conversations: 128

====================================================================================================
ROW: 0
Conversation ID: 227908
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 29.883333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 My issue is contained in the below pic. Please look into it and reply. https://t.co/j9pvkXhaa5
[SUPPORT] @170338 Allow us to take a closer look. Please call us here: https://t.co/vlvfJr4nN9 for live assistance. ^HK

====================================================================================================
ROW: 1
Conversation ID: 236650
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 9.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Le plus marrant c'est que j'ai vu le livreur avec le colis en bas et j'ai demandé, il m'a dit "Non le colis est pas pour vous".
@120533 https://t.co/F5H41AXRll
[SUPPORT] @172357 Bonjour Loïck, je suis désolée pour cela. L'avez-vous signalé à notre SAV? ^SM

====================================================================================================
ROW: 2
Conversation ID: 377207
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 83.85 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 just gt a call frm delivery person regarding where my address is. Yes at 7:58 in the mrning. What a great way to wakeup! #scarcasm
[SUPPORT] @205509 Apologies for the inconvenience with the delivery. I'll forward this as a feedback internally to the concerned teams. ^ST

====================================================================================================
ROW: 3
Conversation ID: 474254
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 13.683333333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115830 Hi there, having a bit of problem. I received an email saying that my delivery has been delivered, but because it was sent to my work address and after office hours.. not too sure where the delivery man has left it? it's no where to be seen.
[SUPPORT] @227883 Sorry to hear that. We'll be happy to look into for you. Please reach out to us here: https://t.co/JzP7hlA23B ^RS

====================================================================================================
ROW: 4
Conversation ID: 583523
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 7.066666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Dear @115821, time to up your shipping game.  I’m good paying for Prime, but paying for 2 day shipping, then getting something in 5 days (or more) is not cool.  Go back to using only @115817.
[SUPPORT] @257626 I'm sorry for the frustration, Lauren, but we're here to help! Our shipping speeds start when the item ships. We aim to meet the delivery date given in checkout/confirmation e-mail. Are we missing this date? You can find this info here: https://t.co/6gnop11w6Z ^KN

====================================================================================================
ROW: 5
Conversation ID: 1678016
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 4.783333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Vous êtes sérieux @120533 de livrer ça dans cet état ?? https://t.co/4PLAp7wGD9
[SUPPORT] @510378 Bonjour,désolée pour cela😓
Je vous prie de le signaler à notre SAV: https://t.co/hgIrz98cdI afin qu'il fasse le nécessaire.^FT

====================================================================================================
ROW: 6
Conversation ID: 2276470
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 17.616666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115830 hi, is it possible to redirect an order to an amazon locker after it's been despatched? Thanks!
[SUPPORT] @662093 We can see what options are available. Reach us by phone or chat to go over details: https://t.co/JzP7hlA23B ^MG

====================================================================================================
ROW: 7
Conversation ID: 2598545
Brand: AmazonHelp
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 14.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Amazon Prime Musicで音楽聴きながら作業して捗る
[SUPPORT] @735688 ご利用いただきありがとうございます😊✨SK

====================================================================================================
ROW: 8
Conversation ID: 210399
Brand: AmazonHelp
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 15.3 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp please help me make my dreams of being a pumpkin for Halloween come true https://t.co/VA2eaeKt8Y
[SUPPORT] @165799 I'm sorry for the trouble! Was your costume being shipped from us or a third-party seller: https://t.co/PCtircFm5C?  ^GL
[CUSTOMER] @AmazonHelp Description says it was supposed to be fulfilled by Amazon https://t.co/VQjiilTo1q
[SUPPORT] @165799 Please contact us directly via phone or chat here: https://t.co/hApLpMlfHN ^NC

====================================================================================================
ROW: 9
Conversation ID: 268721
Brand: AmazonHelp
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 76.11666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @119625 video quality is horrible for the game.
[SUPPORT] @180068 Apologies for the inconvenience. Could you please help us with the cast of the movie? We'll get this checked. ^HD
[CUSTOMER] @AmazonHelp NFL game it got better

====================================================================================================
ROW: 10
Conversation ID: 366006
Brand: AmazonHelp
Size: 3 tweets
Customer turns: 1
Support turns: 2
Duration: 147.88333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 1 hour to process amazon pay balance into the account !! Seriously?? Order no : 405-7666923-7204367 @AmazonHelp
[SUPPORT] @202714 Sorry about the delay. Connect with our support team here: https://t.co/vlvfJr4nN9, we'll assist you regarding this. ^NR 1/2
[SUPPORT] @202714 Please don't provide your order details, we consider it personal info. Our Twitter page is visible to public. ^NR 2/2

====================================================================================================
ROW: 11
Conversation ID: 709030
Brand: AmazonHelp
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 48.266666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp ordered a pop vinyl on @115821 and the body isn't attached properly and it doesn't stand up?!?! @289525
[SUPPORT] @289524 Oh no! We're here to help. Just to clarify, can you tell us where you ordered this from?(https://t.co/hSs9w9f1pF,.ca,.co.uk)^AL
[CUSTOMER] @AmazonHelp https://t.co/vtLvUjSjSb
[SUPPORT] @289524 You can check the available return/replacement options here: https://t.co/aaDyEz1VgE ^ME

====================================================================================================
ROW: 12
Conversation ID: 842214
Brand: AmazonHelp
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 32.45 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 take a bow sir. I ordrd product at Noida address and u dlvrd it to Maharashtra to some unknown person. Why unnecessarily troubling
[SUPPORT] @320325 Apologies for the ordeal. Did you happen to escalate this to our support team here: https://t.co/T6y6Xlutbs? ^VN
[CUSTOMER] @AmazonHelp From past 1 hr I am trying to connect but did not receive any call
[SUPPORT] @320325 Sorry for the hassle. You can also choose to call us or drop an email to us Himanshu. ^HN

====================================================================================================
ROW: 13
Conversation ID: 2159283
Brand: AmazonHelp
Size: 3 tweets
Customer turns: 1
Support turns: 2
Duration: 19.78333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp What kind of prime service u are giving to customers to 1 day delivery as promised order id 4__credit_card__
[SUPPORT] @634246 Could you confirm if we happened to miss the estimate as mentioned here: https://t.co/ykWpCt0ely ? ^KA
[SUPPORT] @634246 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. ^KA

====================================================================================================
ROW: 14
Conversation ID: 2684289
Brand: AmazonHelp
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 16.966666666666665 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Hey @AmazonHelp warum ist das Spiel Monopoly für die Switch plötzlich ca. 10 Euro teurer? #nerv
[SUPPORT] @754979 Hi, wir konnten den genannten Artikel kurze Zeit günstiger anbieten. Der Grund dafür ist mir aber nicht bekannt. Gruß ^JS
[CUSTOMER] @AmazonHelp Schade .... dann wird er woanders gekauft.

====================================================================================================
ROW: 15
Conversation ID: 2802385
Brand: AmazonHelp
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 9.4 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115821 my package was supposed to be delivered today and it wasn’t :-(
[SUPPORT] @781734 I'm so sorry your package hasn't arrived! Can you please let us know who the carrier is? You can check here: https://t.co/Y5jpI9gRhE ^EB
[CUSTOMER] @AmazonHelp UPS!

====================================================================================================
ROW: 16
Conversation ID: 183065
Brand: AmazonHelp
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 38.25 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp help please my order is out for delivery but it hasn’t arrived and it seems to have changed on the website ? Help thanks
[SUPPORT] @159053 Oh no! What does the tracking status say here? https://t.co/aaDyEz1VgE Were you given a new estimated delivery date? ^FD
[CUSTOMER] @AmazonHelp Can I dm you to show what it says thanks
[SUPPORT] @159053 Orders can be delivered until 21:00. Please keep us posted on your order. ^VS
[CUSTOMER] @AmazonHelp It’s arrived  thank you

====================================================================================================
ROW: 17
Conversation ID: 285629
Brand: AmazonHelp
Size: 6 tweets
Customer turns: 4
Support turns: 2
Duration: 29.53333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I love how I pay for Prime and my package that I really needed in 2 days is going to take over a week to get to me @AmazonHelp 👎🏼👎🏼👎🏼
[SUPPORT] @184039 We're here to help! Have we missed our expected delivery date we provided? Check here: https://t.co/Y5jpI9gRhE ^JE
[CUSTOMER] @AmazonHelp I ordered it Tuesday. Said it would be here today. Now it says next Wednesday.
[CUSTOMER] @184039 @AmazonHelp GET THEM STONE! Drag em
[CUSTOMER] @184040 @AmazonHelp Lmaoooo its so much easier to tweet at company’s help accounts than email them 😭😭😭
[SUPPORT] @184039 Let us know if it doesn't arrive by the new estimated delivery date! ^VB

====================================================================================================
ROW: 18
Conversation ID: 386800
Brand: AmazonHelp
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 35.75 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115821 I'm trying to figure out why do I PAY for amazon prime and 2 items I ordered a WEEK ago haven't arrived and I was supposed to receive in 2 days 😡😡
[SUPPORT] @207570 I'm sorry for the trouble, Jonique! Have we missed the estimated delivery date provided at checkout/in your e-mail? ^FD
[CUSTOMER] @AmazonHelp Yes, I was supposed to receive it on the 2nd...today is the 9th
[SUPPORT] @207570 Oh no! Can you verify if there's any tracking updates for this order? You can check that info here:https://t.co/Y5jpI9gRhE ^AL
[CUSTOMER] @AmazonHelp It now says from the 4 but again it's the 9th...no further updates and I need those items
[SUPPORT] @207570 Please reach us via phone/chat so we can look closer in to this together: https://t.co/hApLpMlfHN Keep us posted, Jonique! ^KN

====================================================================================================
ROW: 19
Conversation ID: 685687
Brand: AmazonHelp
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 45.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @119625  ray donovan season 5 not on amazon only up to 4 when you will add up
[SUPPORT] @207168 We will continue to add new content. Keeping checking https://t.co/FYM9PIZOR8 where we highlight the latest movies and TV shows we have available. ^HS
[CUSTOMER] @AmazonHelp If you're adding some content then give it with full  season
[CUSTOMER] @AmazonHelp Not half
[SUPPORT] @207168 Fair enough, Sushant. I'll be sure to share this feedback internally with the right team. ^JC

In [75]:
# Save Batch 1 human annotations

batch_1_labels = {
    0: ("ROUTING_ONLY", "Support only redirects customer to phone assistance."),
    1: ("DIAGNOSTIC", "Support asks whether the issue was reported; no resolution."),
    2: ("CASE_ACTION", "Support says the delivery complaint will be forwarded as internal feedback."),
    3: ("ROUTING_ONLY", "Support redirects customer to another support channel."),
    4: ("ACTIONABLE_GUIDANCE", "Provides delivery-date policy and a way to check the promised date."),
    5: ("ROUTING_ONLY", "Customer is directed to customer service to handle the damaged delivery."),
    6: ("ROUTING_ONLY", "Support redirects customer to phone/chat without answering the question."),
    7: ("NON_SUPPORT", "Social/positive engagement rather than a support issue."),
    8: ("ROUTING_ONLY", "Support gathers one detail but ultimately routes customer to phone/chat."),
    9: ("CONFIRMED_OUTCOME", "Customer explicitly reports that the video quality improved."),
    10: ("ROUTING_ONLY", "Support directs customer to the support team; no resolution."),
    11: ("ACTIONABLE_GUIDANCE", "Provides concrete return/replacement options."),
    12: ("ROUTING_ONLY", "Customer cannot reach support and is redirected to phone/email."),
    13: ("DIAGNOSTIC", "Support checks whether the promised delivery estimate was missed."),
    14: ("AMBIGUOUS", "Support explains the price change but no clear support outcome/action occurs."),
    15: ("DIAGNOSTIC", "Support gathers the carrier information for the delivery investigation."),
    16: ("CONFIRMED_OUTCOME", "Customer explicitly confirms that the order arrived."),
    17: ("UNRESOLVED", "Delivery remains delayed; support only asks customer to wait."),
    18: ("DIAGNOSTIC", "Support gathers tracking information and routes to phone/chat; unresolved."),
    19: ("CASE_ACTION", "Support says the feedback will be shared internally."),
}

for row_idx, (label, note) in batch_1_labels.items():
    resolution_screening_annotations.loc[
        row_idx, "resolution_label"
    ] = label

    resolution_screening_annotations.loc[
        row_idx, "annotation_notes"
    ] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 1 annotations saved.")
print()
print(
    resolution_screening_annotations
    .iloc[:20]["resolution_label"]
    .value_counts()
)

Batch 1 annotations saved.

resolution_label
ROUTING_ONLY           7
DIAGNOSTIC             4
CASE_ACTION            2
ACTIONABLE_GUIDANCE    2
CONFIRMED_OUTCOME      2
NON_SUPPORT            1
AMBIGUOUS              1
UNRESOLVED             1
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3192402335.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'ROUTING_ONLY' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  resolution_screening_annotations.loc[
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3192402335.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Support only redirects customer to phone assistance.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  resolution_screening_annotations.loc[

In [76]:
#Display Batch 2 for manual annotation

batch_2 = resolution_screening_annotations.iloc[20:40].copy()

print("Batch size:", len(batch_2))
print("Rows:", batch_2.index.tolist())

for i, row in batch_2.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Rows: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

====================================================================================================
ROW: 20
Conversation ID: 930342
Brand: AmazonHelp
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 2039.6833333333332 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AmazonHelp Bonjour, a défaut de pouvoir annuler ma commande, puis je avoir des informations sur pourquoi celle-ci met autant de temps à être envoyée?? On m'annonce depuis vendredi un envoi immédiat. Ce qui n'est pas le cas. J'ai précommandé l'article depuis longtemps....
[SUPPORT] @340706 Bonjour, je suis désolée pour cela. Que dit le suivi SVP ? ^SM
[CUSTOMER] @AmazonHelp Simplement "envoi aujourd'hui", livraison prévue le 21/22 Novembre. Mais si le colis n'est pas envoyé les dates prévues ne peuvent pas être respecté. Aucun mail d'explications pour ce retard également.
[SUPPORT] @340706 Quelle était la date de livraison indiquée lors de la validation de la commande?
^MD
[CUSTOMER] @AmazonHelp Le colis a apparemment enfin été expédié. Ce serait peut être bien d'envoyer des mails d'avertissement quand vous avez des soucis pour l'expédition. :/
[SUPPORT] @340706 Je suis désolé pour cela , votre commentaire sera remonté au service concerné, afin d'améliorer notre service.
^YL

====================================================================================================
ROW: 21
Conversation ID: 1338751
Brand: AmazonHelp
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 29.05 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] so much for launch day mario

fuck me right?
[SUPPORT] @407865 Our couriers deliver all the way up to 9PM. ^EM
[CUSTOMER] @AmazonHelp your "couriers" are kids in hatchbacks and idiots who park halfway in the bushes. and apparently destroyed my package beyond deliverability
[SUPPORT] @407865 I'm sorry to hear this! Can you confirm who the carrier was for your order? You can check here: https://t.co/f79PjNlw2b ^KJ
[CUSTOMER] @AmazonHelp https://t.co/3YgF0VbZjt
[SUPPORT] @407865 I'd like a member of our Transportation team to take a look. Please provide your details here: https://t.co/7OrkQKsRWB ^AN

====================================================================================================
ROW: 22
Conversation ID: 2826557
Brand: AmazonHelp
Size: 5 tweets
Customer turns: 2
Support turns: 3
Duration: 60.81666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG
[SUPPORT] @787339 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. 2/2^KK
[SUPPORT] @787339 Sorry for the trouble. I would request you to wait until the end of the day.1/2 ^KK
[CUSTOMER] @AmazonHelp You have sent an email that product was Delivered and in Application you have updated status that, it was handed directly to me and the delivery receipt was signed by me, which is completely false. This seems to be the signature forgery and fraud. @120781 @115850 https://t.co/LVYjdo0ky4
[SUPPORT] @787339 I get your concern and I'd like help you with this. Please share your details here : https://t.co/GIJyeYqKE0 and we'll reach out to you soon. Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^AS

====================================================================================================
ROW: 23
Conversation ID: 2977345
Brand: AmazonHelp
Size: 7 tweets
Customer turns: 5
Support turns: 2
Duration: 29.216666666666665 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115833 I can’t get routines to work 😢 They run if I do that through the app but can’t get any phrases to work. Good morning etc. Help!!
[SUPPORT] @821121 I'm so sorry for the trouble your experiencing. Are you receiving an error message?  ^AG
[CUSTOMER] @AmazonHelp Depends on routine. If I say TV time she replies she doesn’t know that one if I say Good Night she says goodnight back 🙄😁 both have routines
[CUSTOMER] @AmazonHelp Here’s a screen shot of routine https://t.co/ikKPbWvl7H
[CUSTOMER] @AmazonHelp And I’ve tried CAPS, lower case, spaces...
[CUSTOMER] @AmazonHelp And here’s the card after I say it. Any help you can give would be great. https://t.co/fmhHU5oOU9
[SUPPORT] @821121 That's odd! Let's take a closer look into this with you here: https://t.co/JzP7hlA23B Thank you! ^ML

====================================================================================================
ROW: 24
Conversation ID: 34503
Brand: AmazonHelp
Size: 10 tweets
Customer turns: 5
Support turns: 5
Duration: 90.08333333333331 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] fico impressionado com a rapidez da @117086 nos envios dos pedidos, comprei ontem e já tá em transporte 💙 amo demais
[SUPPORT] @123478 Eitaa quais livros comprou 😍? ^MB
[CUSTOMER] @AmazonHelp Comprei 9, trilogia Crônicas de Amor e Ódio, Fronteiras do Universos 1 e 3, Estamos Bem, Contos de Horror séc XIX, Carry On e A longa Viagem
[SUPPORT] @123478 O seu coração bate mais forte quando você passa na frente de uma livraria? 😊💞 ^VL
[CUSTOMER] @AmazonHelp Com certeza e é quase impossível eu não entrar hahah 💙
[SUPPORT] @123478 As pessoas costumam te perguntar quantos livros você já leu? 🙊 ^VL
[CUSTOMER] @AmazonHelp Sim! Principalmente quando olham minha estante dizem "nooossa você já leu quantos desses?"
[SUPPORT] @123478 Nossa! manda uma foto dessa estante maravilhosa para gente 🤗. ^AZ
[CUSTOMER] @AmazonHelp Olha ela aí 💙 https://t.co/9I5Av2Lv7i
[SUPPORT] @123478 Eita nossa, amei tanto que quero um igual! ❤ ^DA

====================================================================================================
ROW: 25
Conversation ID: 423802
Brand: AmazonHelp
Size: 11 tweets
Customer turns: 6
Support turns: 5
Duration: 55.45 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] 野球と全く関係ないんですが質問したいことがあるのでさせていただきます
Amazonを利用したことがある人はわかると思いますが商品を注文して自宅に届くようにしたんですけど受け取るまでの過程とかよくわからないのでわかる人いたら教えて欲しいです
お願いします
[SUPPORT] @215890 Amazon公式アカウントです。注文の過程についてご不明との事ですが、お支払方法は何を選択されておりましたか？ EK
[CUSTOMER] @AmazonHelp 代金引換ってやつです
[SUPPORT] @215890 すでのご注文済みの場合、代金引換をご選択とのことでしたので、そのまま商品の発送をお待ちください。発送はＥメールにてお知らせいたします。　その後、お届け予定日に配送業者がお届けにあがりますので、配送業者に代金をお渡しいただき商品をお受け取りくださいませ。　SM
[CUSTOMER] @AmazonHelp Eメールが届いたら自分で配送業者に連絡とかしなくていいんですよね？
[SUPPORT] @215890 はい、お客様からのご連絡は不要でございます。　配送時に、お届け先住所にご登録いただいた電話番号に、配送業者より在宅確認のお電話を差し上げます。https://t.co/m233uVez0P　SM
[CUSTOMER] @AmazonHelp 家に商品が届いた時にやることや本人じゃなくても家族に代わりに受け取ってもらうことが可能なのかの２つだけ最後に教えてください
[CUSTOMER] @AmazonHelp 明日学校なので携帯に連絡いただいても出れない可能性があるんですが
[SUPPORT] @215890 商品はご家族の方でもお受け取りいただけます。受取の際にどのような手続きが必要であるかは、その時に伺った配達員にご確認ください。また、お電話に出られずご不在だった場合には、不在表を投函しますので、不在表に従って再配達依頼を行ってください。 EK
[CUSTOMER] @AmazonHelp わかりました
色々と教えていただきありがとうございました
[SUPPORT] @215890 恐れ入ります、どうぞよろしくお願いいたします。　Amazonをご利用いただきありがとうございます。商品のお届けまで、今しばらくお待ちくださいませ。　SM

====================================================================================================
ROW: 26
Conversation ID: 432288
Brand: AmazonHelp
Size: 10 tweets
Customer turns: 7
Support turns: 3
Duration: 24.416666666666668 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Good of @AmazonHelp to "try but fail to deliver" my order today. Not entirely sure how they can fail at half four when they had until nine.
[CUSTOMER] @AmazonHelp Especially as no reason was given for said failure. And even more especially given that this is the second time they've sent it out.
[CUSTOMER] @AmazonHelp The first time they delivered it, I wasn't in and came home to a card saying they'd left it on my doorstep. It wasn't there.
[SUPPORT] @217813 I'm sorry you haven't received your order! Have you contacted our Customer Support team: https://t.co/JzP7hlA23B? ^ME
[CUSTOMER] @AmazonHelp I have. Frequently, largely because Amazon Logistics is one of the least reliable companies I've ever dealt with.
[SUPPORT] @217813 What were the available options offered when you spoke with us? Could we provide more insight on the order's delivery? ^ME
[CUSTOMER] @AmazonHelp Well it was a choice between parcel going missing, parcel being delivered to the wrong and unspecified street, delivery drivers simply...
[CUSTOMER] @AmazonHelp ...opening the front door and throwing the parcel into my house without knocking, drivers claiming they'd attempted delivery...
[CUSTOMER] @AmazonHelp ...but never actually turning up at any point... Oh wait, you mean what help was offered rather than what your drivers have actually done.
[SUPPORT] @217813 We'd like to have a member of our team look in to this with you! Pls leave your details here: https://t.co/t8PaQbbQwz ^KN

====================================================================================================
ROW: 27
Conversation ID: 538510
Brand: AmazonHelp
Size: 10 tweets
Customer turns: 5
Support turns: 5
Duration: 43.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Everyone should cancel @115821 prime his time of year and just use their regular free shipping. You're not going to 2 days shipping this time of year anyway. #fail #canthandletheseason #amazonwasniceonce
[SUPPORT] @244847 Hey, Markus! Has there been a delay in delivery for your items? We'd love to help! ^GP
[CUSTOMER] @AmazonHelp 2 of 3 from this week.
[SUPPORT] @244847 I'm sorry to hear of this. Have you contacted us about this? If so what were you advised? ^KI
[CUSTOMER] @AmazonHelp I have not. I've come to expect and accept that type of delivery delay this time of year.
[SUPPORT] @244847 Has this been a trend with a specific carrier? We want to help! ^MT
[CUSTOMER] @AmazonHelp It's UPS. They do fine the other times of the year. Although I no longer get Saturday deliveries either. Prime used to be more fun...
[SUPPORT] @244847 Oh goodness! Have you been provided a reason for the delays or an updated delivery date? ^AB
[CUSTOMER] @AmazonHelp By Monday your app says
[SUPPORT] @244847 Thanks for the additional information! Please keep us posted on the delivery of your package. ^SW

====================================================================================================
ROW: 28
Conversation ID: 719893
Brand: AmazonHelp
Size: 10 tweets
Customer turns: 5
Support turns: 5
Duration: 120.68333333333334 minutes
----------------------------------------------------------------------------------------------------
[SUPPORT] @292289 I'm sorry! Have you been able to contact the USPS directly for more insight into this and to provide feedback? ^SB
[CUSTOMER] @AmazonHelp And wow, I wasn't expecting a response so soon and certainly not from someone who's fault it isn't. Thank you!
[SUPPORT] @292289 To clarify, did you receive your package after normal delivery hours? We just want to make sure you're taken care of! ^ST
[CUSTOMER] @AmazonHelp I haven't gotten any packages at all. Some were supposed to come Saturday and some today. Nothing yet. 😕
[SUPPORT] @292289 Late packages typically arrive 1-2 business days after the delivery date. Please let us know when your package arrives! ^GM
[CUSTOMER] @AmazonHelp Will do! We have just gotten this update from the packages that were supposed to come today. We were home, and there wasn't an attempt. 😕 https://t.co/uQT860GrpF
[CUSTOMER] @AmazonHelp Thanks for your help though! I'm sorry, I don't usually complain about things. 😌
[SUPPORT] @292289 Let us know if the order doesn't arrive by tomorrow and please shoot us an e-mail regarding the non-delivery attempt. ^ST
[CUSTOMER] @AmazonHelp Wouldn't that be a postal service issue and not an Amazon issue? I don't want to bother you with an issue that isn't yours.
[SUPPORT] @292289 We love to hear from customers, and we can ensure your feedback is reviewed by the correct team: https://t.co/hApLpMlfHN ^SB

====================================================================================================
ROW: 29
Conversation ID: 1666514
Brand: AmazonHelp
Size: 12 tweets
Customer turns: 6
Support turns: 6
Duration: 3091.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115833 when can I set recurring reminders on Alexa?
[SUPPORT] @161011 Our support team would be happy to help you out with your query! Please contact us from here: https://t.co/vlvfJr4nN9. ^MP
[CUSTOMER] @AmazonHelp Getting the following error while trying to get to the URL. https://t.co/RGEjkbxQg8
[SUPPORT] @161011 I've checked and seen the link is working fine. Kindly try accessing it here:  https://t.co/2t6DQoUmNZ again. ^AP
[CUSTOMER] @AmazonHelp Done, thanks!
[SUPPORT] @161011 You're welcome. Please keep us posted for further concerns. ^BS
[CUSTOMER] @AmazonHelp Looks like recurring reminders are not possible for now :( That's quite disappointing. Google calendar integration?
[SUPPORT] @161011 I'm sorry I couldn't comprehend your concern. Kindly elaborate. ^HR
[CUSTOMER] @AmazonHelp Is there a way I can set up some recurring reminder on Google calendar and make Alexa pick it up?
[SUPPORT] @161011 I get your concern. However, we do not have any such feature as of now. Please stay tuned for new updates and features. ^KH
[CUSTOMER] @AmazonHelp Does that mean this will be a candidate for future release, or is it just generic reference to new features that I may not necessarily be interested in?
[SUPPORT] @161011 As informed earlier, we don't have that feature at this moment, stay tuned for updates. ^SU

====================================================================================================
ROW: 30
Conversation ID: 1714337
Brand: AmazonHelp
Size: 18 tweets
Customer turns: 9
Support turns: 9
Duration: 1472.9666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115850  thing to understand is that Amazon does not want to offer full service to the customer Flipkart is the best service in India
[CUSTOMER] @115850 I request all the Indians not to trust Amazon as it broke my trust.Thank the store, the dish
[SUPPORT] @450218 I'm sorry you felt that way, could you please let us know what went wrong so that we can assist you accordingly. ^SU
[SUPPORT] @450218 I understand your concern, Nitin. If you've shared your details, our team will reach out to you shortly. ^HD
[CUSTOMER] @AmazonHelp I asked to send my rupee in the name of the bank, so the people sent me to the Amazon ... troubling me
[CUSTOMER] @AmazonHelp So people are asking what went wrong
[SUPPORT] @450218 I'm sorry for the trouble. We'll check and get back to you with an update shortly. ^MK
[CUSTOMER] @AmazonHelp You forgot, you said that you get back an update.
[CUSTOMER] @AmazonHelp I sent all the details to your link but your team says whatever email you have given,no account by that name,how it is muzzling,howdo Iorder
[SUPPORT] @450218 I’m sorry about the issue you’re facing with your order. Let us look into it. (1/2)^HR
[SUPPORT] @450218 Please share your details from the link here: https://t.co/beaaDm0muc to assist you accordingly. (2/2)^HR
[CUSTOMER] @AmazonHelp Man has given the details right now Do not speak on your link, Hindi is giving your description, if not, then accept your mistake directly.
[CUSTOMER] @AmazonHelp If you within the slightest shame rest then call me to my problem resolves to not so I समझूँगा your and Amazon FAQ and fake
[CUSTOMER] @AmazonHelp 9826745404 and 8718932967
[SUPPORT] @450218 Being a social media platform, we will not have access to you account. Please reply to the email sent for more info. ^KS 1/2
[SUPPORT] @450218 Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^KS 2/2
[SUPPORT] @450218 Being on Social media, we won't be able to call you. Request you to share your details in the link provided earlier 1/2 ^HS
[SUPPORT] @450218 and we'll help you with your concern. 2/2 ^HS

====================================================================================================
ROW: 31
Conversation ID: 1719165
Brand: AmazonHelp
Size: 12 tweets
Customer turns: 6
Support turns: 6
Duration: 935.8833333333332 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @116875 A que se debe esto? https://t.co/VIzXve1rta
[SUPPORT] @520452 Hola, lamento el inconveniente. ¿Has verificado si todo está correcto con tu método de pago? Recomiendo verificar la siguiente información: https://t.co/pBSNHyi8dA. ^AZ
[CUSTOMER] @AmazonHelp Si, todo está en orden ya me apareció como 3 veces eso
[SUPPORT] @520452 Y al verificar tu método de pago, ¿pudiste completar el pedido, o aún no? ^ES
[CUSTOMER] @AmazonHelp Ya, despues como a las horas me da el error https://t.co/KjCpwOsX4p
[SUPPORT] @520452 Entiendo, ¿ya intentaste cambiar la forma de pago? ^MB
[CUSTOMER] @AmazonHelp Sólo cuento con una tarjeta, ya la puse de nuevo y tampoco
[SUPPORT] @520452 En este caso, te recomendamos entrar en contacto con nuestro departamento de Servicio al cliente por medio del siguiente enlace para más ayuda: https://t.co/beR78zMMYB ^FZ
[CUSTOMER] @AmazonHelp Creo que ya vi el error, quise comprar los headset y se pago el amazon prime, el cual yo no lo queria, ni lo compre, como le hago para el rembolso? yo solo queria los headset no el prime https://t.co/HbNVdSo9Mk
[SUPPORT] @520452 ¡Hola lFlinko! En este caso para realizar la cancelación de tu suscripción puedes acceder al siguiente enlace: https://t.co/r4beqDfCMD.

Saludos
^JL
[CUSTOMER] @AmazonHelp Si, ya envie el gmail para la cancelación del prime, lo que me intriga ahora, es saber si cuando de devuelvan el dinero, podre comprar los headset con el precio que los intente comprar el dia 24 de nov
[SUPPORT] @520452 lFlinko, en el momento de realizar el nuevo pedido, antes de finalizarlo, en la página de resumen del pedido, podrás ver el valor total cobrado por el producto y envío. ^VM

====================================================================================================
ROW: 32
Conversation ID: 152977
Brand: AppleSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 42.95 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport please help my iPhone 7 is freezing constantly and keeps going to a black screen forcing a restart feels like every 10 min - what can I do?
[SUPPORT] @151000 Meet us in DM with your current iOS version, and we'll check into this together and find a solution. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 33
Conversation ID: 756526
Brand: AppleSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 18.166666666666668 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] That is not a "Pause Download" Button @115858, that is a "CANCEL DOWNLOAD" Button and we're in version 12. smh https://t.co/q4qET5czfO

In [77]:
# Save Batch 2 human annotations

batch_2_labels = {
    20: ("CASE_ACTION", "Support investigates delivery issue and records customer complaint as internal feedback."),
    21: ("CASE_ACTION", "Support collects carrier information and initiates Transportation-team review."),
    22: ("CASE_ACTION", "Support requests details so the delivery issue can be investigated."),
    23: ("DIAGNOSTIC", "Support gathers error/context information and routes for closer investigation."),
    24: ("NON_SUPPORT", "Social engagement about books; no support issue."),
    25: ("ACTIONABLE_GUIDANCE", "Detailed instructions explain delivery/payment/receiving process and what to do if absent."),
    26: ("CASE_ACTION", "Support gathers information and offers team investigation of repeated delivery failures."),
    27: ("DIAGNOSTIC", "Support gathers carrier and delivery information but does not resolve the issue."),
    28: ("UNRESOLVED", "Packages remain undelivered; no resolution is shown."),
    29: ("ACTIONABLE_GUIDANCE", "Provides a working link and explains that the requested recurring-reminder feature is unavailable."),
    30: ("CASE_ACTION", "Support attempts to obtain details and route the case for investigation; no outcome shown."),
    31: ("ACTIONABLE_GUIDANCE", "Provides concrete Prime-cancellation and reorder information."),
    32: ("ROUTING_ONLY", "Immediately directs customer to DM for investigation."),
    33: ("ROUTING_ONLY", "Only moves the issue to DM."),
    34: ("ACTIONABLE_GUIDANCE", "Provides a concrete workaround for the software issue."),
    35: ("ROUTING_ONLY", "Directs customer to DM without substantive troubleshooting."),
    36: ("ACTIONABLE_GUIDANCE", "Provides a specific address-editing path and fallback DM option."),
    37: ("ROUTING_ONLY", "Only requests device/iOS information through DM."),
    38: ("ACTIONABLE_GUIDANCE", "Directly answers that Apple IDs cannot be merged and provides more information."),
    39: ("ROUTING_ONLY", "Requests more details through DM without substantive help."),
}

for row_idx, (label, note) in batch_2_labels.items():
    resolution_screening_annotations.loc[
        row_idx, "resolution_label"
    ] = label

    resolution_screening_annotations.loc[
        row_idx, "annotation_notes"
    ] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 2 annotations saved.")
print()
print(
    resolution_screening_annotations
    .iloc[20:40]["resolution_label"]
    .value_counts()
)

Batch 2 annotations saved.

resolution_label
ACTIONABLE_GUIDANCE    6
CASE_ACTION            5
ROUTING_ONLY           5
DIAGNOSTIC             2
NON_SUPPORT            1
UNRESOLVED             1
Name: count, dtype: int64

In [78]:
# Display Batch 3 for manual annotation

batch_3 = resolution_screening_annotations.iloc[40:60].copy()

print("Batch size:", len(batch_3))
print("Rows:", batch_3.index.tolist())

for i, row in batch_3.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Rows: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]

====================================================================================================
ROW: 40
Conversation ID: 1248350
Brand: AppleSupport
Size: 4 tweets
Customer turns: 3
Support turns: 1
Duration: 320.76666666666665 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] you do it’s starts freezing and not working and closing apps while you’re in them and all kinds crazy stuff.. Why is that @115858 ? Smh 🤔🤔
[CUSTOMER] @412883 @115858 It won’t let me update it and I’m getting charged for 4G data use 😡
[SUPPORT] @412881 Thanks for reaching out. We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @412881 It’s happening to mine as well.

====================================================================================================
ROW: 41
Conversation ID: 1360112
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 134.83333333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport do I need to own the latest AirPods to use wireless charging?
[SUPPORT] @125141 Great question! The wireless charging case for your AirPods will be available in 2018. More here: https://t.co/nlkjBpUhh6
[CUSTOMER] @AppleSupport Thanks 🙏

====================================================================================================
ROW: 42
Conversation ID: 1742422
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 548.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport why tf do my “I️” come out like this &gt; I️
[CUSTOMER] @AppleSupport “I️”
[SUPPORT] @525597 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

====================================================================================================
ROW: 43
Conversation ID: 1766003
Brand: AppleSupport
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 109.71666666666668 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Y'all need to fix this shanigans. Got me playing Wheel of Fortune trying read simple shit. @AppleSupport
[SUPPORT] @531108 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9
[CUSTOMER] @AppleSupport Already did. And 🗣 IT DIDN'T WORK
[SUPPORT] @531108 Let's take a closer look. Can you DM us? https://t.co/GDrqU22YpT

====================================================================================================
ROW: 44
Conversation ID: 2046024
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 33.56666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport Snapchat notification icon on Apple Watch is blanked out. Even after updating to OS 4.0.1....
[SUPPORT] @605086 Hi there. Are you still getting the notification as normal and only the icon is affected? Let us know by DM. We'll help. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport I am still getting the notification as normal. But the icon is affected. The twitter notification is the same way.

====================================================================================================
ROW: 45
Conversation ID: 2065998
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 131.9 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Was excited about iOS 11. Now it’s just annoying. 😏screen is just frozen most of the time. Wanna do something about that @115858 ?
[CUSTOMER] @115858 Even at 11.0.2 is the same. 😏 it’s a miracle I was able to tweet this in one go.!
[SUPPORT] @610955 Let's take a look at the performance after your update. Which apps or features are you using when it does this? Tell us in DM. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 46
Conversation ID: 2371194
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 18.23333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport
Are apps allowed to demand 5* reviews in return for unlocking features?
[SUPPORT] @258735 We'd love to help. Each app is different and the developers of the apps can request that information once the app is downloaded, but it is left to the discretion of the developer.
[CUSTOMER] @AppleSupport Ok, so this is deemed acceptable? It feels like gaming the system to me... https://t.co/ceYBLrCDAY

====================================================================================================
ROW: 47
Conversation ID: 2857301
Brand: AppleSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 63.43333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115858 @AppleSupport y'all are pretty sus eating up 7 GB of unmarked space on my phone
[SUPPORT] @794127 We'd be happy to look into this with you.  Please reach out to us via DM and we'll get started. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @794127 if you don't follow through with this you're a uniformed police officer

====================================================================================================
ROW: 48
Conversation ID: 889085
Brand: AppleSupport
Size: 5 tweets
Customer turns: 4
Support turns: 1
Duration: 12.633333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] 1) hey @115858 @AppleSupport I bought a new phone from you on Wednesday! But you sent me some other person’s phone! Whoops....
[CUSTOMER] @115858 @AppleSupport 2) I called @AppleSupport and they said they’d send me a new phone expedited. That seems fair, I didn’t send myself the wrong phone....
[CUSTOMER] @115858 @AppleSupport 3) but then I get an @AppleSupport email. Y’all want me to send the wrong phone back before I get the new phone. That’ll take 4-5 addl days
[CUSTOMER] @115858 @AppleSupport 4) @AppleSupport so “expedited” means “twice as slow to fix the mistake @115858 made”....
[SUPPORT] @331079 We can assist you. Please DM us via the following link the case number from your interaction with our phone support advisor. We can help you further from there. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 49
Conversation ID: 1174774
Brand: AppleSupport
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 1495.65 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Why would this be @AppleSupport ?? I’ve tried three times and says the same 😤 https://t.co/9XRmxCFuAR
[SUPPORT] @396316 We want to help. Have you tried updating via iTunes on a computer?  Have you tried restarting your device?
[CUSTOMER] @AppleSupport I’m unable to plug my phone into a computer currently however I have tried to restart and I’m still seeing the same error!
[SUPPORT] @396316 Have you tried updating via another Wi-Fi network?
[CUSTOMER] @AppleSupport This worked! Thank you 😊
[SUPPORT] @396316 Excellent!  We are glad that you are all set.  Contact us again if you need further assistance.  We are here for you.

====================================================================================================
ROW: 50
Conversation ID: 1379598
Brand: AppleSupport
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 73.41666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Phone won't update or restore so left with this .. @AppleSupport 😡 https://t.co/vlLFuW5Mcw
[SUPPORT] @415605 We're happy to help. Can you tell us what happened when you received this message to connect to iTunes?
[CUSTOMER] @AppleSupport Was updated to latest iOS been at it since 10.30am it's now 5.28pm 🤦🏼‍♀️
[SUPPORT] @415605 What are you seeing in iTunes on your computer? Do you get a pop-up message when connected? https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport Couldn't be updated so needs to be restored but just as it's finished extracting software it says it can't be done
[SUPPORT] @415605 Got it. Let's try the steps in this article, and let us know the result: https://t.co/HLE0hfPneP

====================================================================================================
ROW: 51
Conversation ID: 1633487
Brand: AppleSupport
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 21050.416666666668 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Music app WatchOS 4 so annoying, keep crashing, take 3-5 secs to respond a click, reset itself to shuffle @115858 @AppleSupport #watchos4
[SUPPORT] @316424 Thanks for reaching out. When you have a free moment, can you please tell us how often does this issue occur in a typical day?
[CUSTOMER] @AppleSupport thanks 4 reply! so after WatchOS4, reset to shuffle every single time, crash every other day, take really long to respond to click everytime
[SUPPORT] @316424 We'd like to look into this further with you. Could you please send us a DM so we can gather some info? https://t.co/GDrqU22YpT
[CUSTOMER] @316424 @AppleSupport Did you find a fix for this? My watch shuffles every playlist as well.
[SUPPORT] @499771 We are here to help whenever possible. DM which Apple Watch and specific watchOS version you are using to get started. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 52
Conversation ID: 2132164
Brand: AppleSupport
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 106.2 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Music voice control has ruined my life
[CUSTOMER] @AppleSupport
[SUPPORT] @627457 We'll be glad to help. Can you tell us more about what you're experiencing?
[CUSTOMER] @AppleSupport Voice control is ruining my life
[SUPPORT] @627457 Thanks for the info. What happens when you try to use Voice Control? Send us a DM and we'll take a look together. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 53
Conversation ID: 2285829
Brand: AppleSupport
Size: 7 tweets
Customer turns: 4
Support turns: 3
Duration: 97.55 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Ever since I updated my phone to the new iOS , the shit turns off out of nowhere atleast 3 times a day SMH .. way to go @115858
[SUPPORT] @655298 We're here to help. Which iPhone model are you using and what version of iOS is installed? Check Settings &gt; General &gt; About.
[CUSTOMER] @AppleSupport check the dm
[CUSTOMER] @AppleSupport https://t.co/fucPBACKNi
[SUPPORT] @655298 Are you using a specific app when this happens?
[CUSTOMER] @AppleSupport nope just on my phone texting or listening to music
[SUPPORT] @655298 Let's continue in DM. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 54
Conversation ID: 2422466
Brand: AppleSupport
Size: 5 tweets
Customer turns: 4
Support turns: 1
Duration: 489.9166666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I always feel so emotionally abused leaving an @115858 store. You’d think after spending 100s - 1000s of dollars on a device, they’d take your problems seriously and not treat you like cattle. Guess not. I can’t even call to book an appointment? Your customer service needs work.
[SUPPORT] @695770 We'd like to discuss this further with you. Join us in a Direct Message to tell us about your visit. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @695770 Are you guys going to solve this problem with compensation OR fix all problems with a real solution?
[CUSTOMER] @AppleSupport @695770 @AppleSupport that's what they always do they always sugar coat it and don't fix the issue. That's why it's better to go to a third-party which they don't advise because they're losing money. What's the problem?
[CUSTOMER] @695771 @AppleSupport @695770 That’s right they don’t fix things, for me they never gave call back they promised. After weeks of chasing I gave up #evilapple

====================================================================================================
ROW: 55
Conversation ID: 2557403
Brand: AppleSupport
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 195.9333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115858 Why does my Bluetooth automatically turn on after I fully charge my phone? Didn’t do that before the iOS 11 update.
[SUPPORT] @726056 Let's take a look at this for you. When you turn off Bluetooth are you doing this using the Control Center or in Settings?
[CUSTOMER] @AppleSupport Control Center.
[SUPPORT] @726056 This is expected behavior with iOS 11. If you wish to turn it off and leave it off, you can do that via Settings. Find out more here: https://t.co/G7BHuQnDS6
[CUSTOMER] @AppleSupport Makes sense. Thanks!

====================================================================================================
ROW: 56
Conversation ID: 1037659
Brand: AppleSupport
Size: 9 tweets
Customer turns: 6
Support turns: 3
Duration: 738.0166666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport my camera roll folder shows zero pics all of a sudden, how do I retrieve them back ?? Kindly reply asap
[SUPPORT] @365471 We know how important your photos can be to you. We're here to help. Which iOS version is your device currently running?
[CUSTOMER] @AppleSupport 11.3
[CUSTOMER] @AppleSupport 11.3 ios
[CUSTOMER] @AppleSupport 11.0.3
[CUSTOMER] @AppleSupport Been facing wierd problems with camera roll, since ios 11.... deletion restoration, blurry screen shots n etc etc
[SUPPORT] @365471 How long ago did you update your device to iOS 11.0.3?
[CUSTOMER] @AppleSupport As soon as it was launched
[SUPPORT] @365471 Thanks for letting us know. Let's continue this conversation in a DM. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 57
Conversation ID: 1078275
Brand: AppleSupport
Size: 10 tweets
Customer turns: 5
Support turns: 5
Duration: 11042.033333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Hey @AppleSupport. Updated to the newest ios and now my phone doesn't display volume settings.
[SUPPORT] @327975 We'll be happy to help! Can you tell us where on the iPhone the volume settings are missing?
[CUSTOMER] @327975 @AppleSupport Same here. They used to pop up when you pushed the buttons. Now nothing. 6s.
[SUPPORT] @501166 Since noticing this, have you had a chance to restart your device? It may seem like a simple step, but can resolve many issues.
[CUSTOMER] @AppleSupport Every single screen. I press the volume change and it works but doesn't display the levels.
[SUPPORT] @327975 Let's begin by restarting the iPhone. Restart your iPhone: https://t.co/OWRDHWSt4h
[CUSTOMER] @AppleSupport Yeah. I've tried it
[SUPPORT] @327975 Is this happening with just one app? Does the volume change work and just not being displayed?
[CUSTOMER] @AppleSupport Volume works. Just not displayed. This isn't in any app. It's in the system. I can be on the home screen or lock screen or anything.
[SUPPORT] @327975 Got it. We'd like to gather more information from you. Please DM us to get started. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 58
Conversation ID: 1173988
Brand: AppleSupport
Size: 9 tweets
Customer turns: 5
Support turns: 4
Duration: 1053.1166666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Can @AppleSupport help me please as I have a black screen!!
[SUPPORT] @396127 We want to help you with this. Which device has a black screen?
[CUSTOMER] @AppleSupport MacBook pro
[SUPPORT] @396127 Thanks for that information. Are you able to hear any startup sounds?
[CUSTOMER] @AppleSupport yes....
[CUSTOMER] @AppleSupport and can’t type Apple ID or password
[SUPPORT] @396127 Try resetting the SMC, and let us know the results. Here's how: https://t.co/FYojVXHuwn
[CUSTOMER] @AppleSupport tried that before contacting you guys...
[SUPPORT] @396127 Send us a DM and let us know your country. We'll be glad to have closer look at this with you. https://t.co/GDrqU22YpT

====================================================================================================
ROW: 59
Conversation ID: 1387619
Brand: AppleSupport
Size: 9 tweets
Customer turns: 6
Support turns: 3
Duration: 89.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @15462 takes ages to boot after a restart on my @AppleSupport tab? Where are things wrong?
[SUPPORT] @442861 We'd like to help. Tell us more details about what you're experiencing. Also, which device you're using.
[CUSTOMER] @AppleSupport Hi... I use IPad... off late, logging into Netflix especially after a reboot takes a lot of time...
[CUSTOMER] @AppleSupport the last time around it didn't happen at all, so I deleted the app and reinstalled, but lost my downloads in the process.
[SUPPORT] @442861 If the issue is occurring after deleting and reinstalling the app, you'll want to reach out to the developer for support.
[CUSTOMER] @AppleSupport the frequency of occurrence increased over the last couple of weeks and I therefore deleted and reinstalled the app
[CUSTOMER] @AppleSupport @15462 ???
[SUPPORT] @442861 If the problem is still happening since reinstalling, the developer would be the best resource to help you out from here.
[CUSTOMER] @AppleSupport @15462 did you understand the problem?

In [79]:
# Save Batch 3 human annotations

batch_3_labels = {
    40: ("ROUTING_ONLY", "Support only asks customer to move the problem to DM."),
    41: ("ACTIONABLE_GUIDANCE", "Directly answers the wireless-charging question with relevant product information."),
    42: ("ACTIONABLE_GUIDANCE", "Provides a concrete workaround for the software issue."),
    43: ("UNRESOLVED", "Customer tried the workaround and says it did not work; support then routes to DM."),
    44: ("DIAGNOSTIC", "Support asks whether notifications work normally or only the icon is affected."),
    45: ("DIAGNOSTIC", "Support gathers information about which apps/features trigger the freezing."),
    46: ("ACTIONABLE_GUIDANCE", "Explains the app/developer responsibility and how the behavior works."),
    47: ("ROUTING_ONLY", "Support only offers to investigate through DM."),
    48: ("ROUTING_ONLY", "Support requests the existing case number and moves the issue to DM."),
    49: ("CONFIRMED_OUTCOME", "Customer says the suggested Wi-Fi change worked and support confirms resolution."),
    50: ("ACTIONABLE_GUIDANCE", "Provides a concrete troubleshooting article/next step; no successful outcome shown."),
    51: ("DIAGNOSTIC", "Support gathers frequency/details and requests device/version information."),
    52: ("DIAGNOSTIC", "Support gathers more information about the Voice Control problem."),
    53: ("DIAGNOSTIC", "Support gathers device/iOS/app context before continuing in DM."),
    54: ("ROUTING_ONLY", "Support only asks customer to continue the discussion in DM."),
    55: ("CONFIRMED_OUTCOME", "Support explains the behavior and customer confirms it makes sense."),
    56: ("DIAGNOSTIC", "Support gathers iOS/version/timing information; no resolution shown."),
    57: ("DIAGNOSTIC", "Support attempts troubleshooting, gathers additional information, then routes to DM."),
    58: ("UNRESOLVED", "Suggested troubleshooting had already been tried and no resolution follows."),
    59: ("ACTIONABLE_GUIDANCE", "Support identifies the app developer as the appropriate support path based on the issue."),
}

for row_idx, (label, note) in batch_3_labels.items():
    resolution_screening_annotations.loc[
        row_idx, "resolution_label"
    ] = label

    resolution_screening_annotations.loc[
        row_idx, "annotation_notes"
    ] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 3 annotations saved.")
print()
print(
    resolution_screening_annotations
    .iloc[40:60]["resolution_label"]
    .value_counts()
)

Batch 3 annotations saved.

resolution_label
DIAGNOSTIC             7
ACTIONABLE_GUIDANCE    5
ROUTING_ONLY           4
UNRESOLVED             2
CONFIRMED_OUTCOME      2
Name: count, dtype: int64

In [80]:
# Display Batch 4 for manual annotation

batch_4 = resolution_screening_annotations.iloc[60:80].copy()

print("Batch size:", len(batch_4))
print("Rows:", batch_4.index.tolist())

for i, row in batch_4.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Rows: [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]

====================================================================================================
ROW: 60
Conversation ID: 1752360
Brand: AppleSupport
Size: 10 tweets
Customer turns: 6
Support turns: 4
Duration: 6398.45 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @AppleSupport got this today and looks like a phishing attempt. Can you verify? https://t.co/A6Osq0jZCD
[SUPPORT] @116714 That is definitely not from us. This article shows how to report a phishing attempt: https://t.co/V2QRdtocGo
[CUSTOMER] @AppleSupport Ok. Thanks.
[SUPPORT] @116714 You're welcome. If you need help in the future, feel free to let us know. Have a wonderful day.
[CUSTOMER] @AppleSupport Any way to fix it so I can read story titles ? https://t.co/zdIlcA6byp
[CUSTOMER] @AppleSupport Here is the link:
https://t.co/ckmkD2rO3p
[SUPPORT] @116714 We're here to help. The link shared took us to an Apple News story without an issue. Do the headlines appear in portrait mode? Which iOS version is the iPad running? When selecting on the Saved or Spotlight tabs are you able to see the headlines?
[CUSTOMER] @AppleSupport Yes I can see them in Saved and Spotlight but that doesn’t help when I’m looking at the stories in For You.
[SUPPORT] @116714 Thanks for helping us isolate things down to the For You page. It appears the font on this page is larger than expected. Is the font size the same in other News app tabs? If so, test a smaller font by following these steps: https://t.co/hos2HtyyxL
[CUSTOMER] @AppleSupport Thanks that worked.
Can I move an audio book from my iMac to my iPhone!

====================================================================================================
ROW: 61
Conversation ID: 2037763
Brand: AppleSupport
Size: 10 tweets
Customer turns: 9
Support turns: 1
Duration: 91.16666666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I️ don’t know why I️ laughed as hard as I️ dis but here we are https://t.co/9fJas3g6Zv
[CUSTOMER] @602528 Are you running iOS 11.0 by any chance? https://t.co/UscNfmF4MS
[CUSTOMER] @602527 sadly i am..I’ve been looking for work arounds
[CUSTOMER] @602528 Update to 11.1?
[CUSTOMER] @602527 sorry just checked again I’m up to 11.1. Something else I’m missing out on?
[CUSTOMER] @602528 So weird, in your previous tweets the letter “I” appears as that weird question mark block on my screen. I updated to 11.1 and my twitter app just to make sure it wasn’t me 😒
[CUSTOMER] @602527 yeah I just looked at that. Very confusing...and I don’t like it one bit
[CUSTOMER] @602528 @AppleSupport fix this please. We are both running 11.1. I don’t understand why I’m seeing the question mark block in place of the letter “I”
[SUPPORT] @602527 Thanks for reaching out. We have a workaround for this here: https://t.co/xXaXeeSRt9 DM us if you still need help. https://t.co/GDrqU22YpT
[CUSTOMER] @AppleSupport @602528 I guess the only solution for now is this workaround. Get it together, Apple!

====================================================================================================
ROW: 62
Conversation ID: 2520745
Brand: AppleSupport
Size: 10 tweets
Customer turns: 8
Support turns: 2
Duration: 1209.9166666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] CARALHO DE ASA MINHA GALERIA ZEROU DO NADA, já reiniciei e tudo, APPLE FILHA DA PUTA @AppleSupport @115858 VAI TOMA NO CU DESGRACADOS
[SUPPORT] @717985 Since our Twitter support is available in English, get help at https://t.co/IBIY3vMgPj or join https://t.co/pvaOFfPbjt
[CUSTOMER] @AppleSupport Ah fuck u empresa de merda do caralho
[CUSTOMER] @AppleSupport i have one problem, i need assistence
[CUSTOMER] @717985 @AppleSupport AHAHAAHHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHAHHAHA
[CUSTOMER] @717985 @AppleSupport APPLE AJUDA ELE CARA
[CUSTOMER] @717986 @AppleSupport caralho meus prints foram tudo embora
[CUSTOMER] @717985 @AppleSupport KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK TADINHO
[SUPPORT] @717985 You're in the right place for help. Tell us in detail the issues you're having and we're going from there.
[CUSTOMER] @717985 @AppleSupport LKKKKKKKKKKKKKKKKKKKKJKKKKKKK

====================================================================================================
ROW: 63
Conversation ID: 2736455
Brand: AppleSupport
Size: 9 tweets
Customer turns: 8
Support turns: 1
Duration: 77.38333333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] از اشتباهاتم این بود که برای مامان آیفون خریدم، در حالی که هیچکس تو خونه مون آیفون نداره. هر روز یه مشکل داشته با این گوشی! آیفون تو ایران اشتباهه کلا. باید صایران میخریدم.
[CUSTOMER] @766831 چی شده؟
[CUSTOMER] @766830 رو آرم اپل گیر کرده، بوت نمیشه
[CUSTOMER] @766831 دکمه پاور هوم رو همزمان نگه داره ببینه بعد که صفحه خاموش شد ولشون کنه ببین درست میشه؟
[CUSTOMER] @766830 نشده. الان میگه باید به ایتونز وصل کنی. که خب نداره رو پی سی. یعنی فقط گرفتاری
[CUSTOMER] @766831 یه عکس  اون صفحه و خطایی که میده برام بفرست وقت کردی
[CUSTOMER] @766830 روی علامت سیب میمونه. با اون 10 ثانیه نگه داشتن هم میگه هیچی نشده. مسخره ست اصلا
[CUSTOMER] @766831 اسمان این اکانت اپل رو دست کم نگیر هر سوالی داری ازش بپرس جواب میده
@AppleSupport
[SUPPORT] @766830 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj

====================================================================================================
ROW: 64
Conversation ID: 83742
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 131.55 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco from 22:25 last night Tesco delivery van parked outside my house making loads of noise, again! 😭
Try parking outside your customers house?
[SUPPORT] @134397 Hi, I'm sorry the delivery driver was causing disruption and for the inconvenience. Please can you DM the full address of the delivery so I can feed this back to the store? Charlotte https://t.co/py5Z991Bme

====================================================================================================
ROW: 65
Conversation ID: 684979
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 9.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] okay what do me and ben have for tea tomorrow
[SUPPORT] @283486 We be happy to make a few suggestions, thinking along the lines of some healthy comfort food? 😋😋😋

====================================================================================================
ROW: 66
Conversation ID: 838753
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 64.51666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Hey @tesco. Just had a fridge delivered, paid £20 for connection. All I have to do is plug it in. What exactly did I pay for? Not impressed!
[SUPPORT] @257890 Hey, Victoria! Sorry to hear that!  Can you kindly DM me your order number, full name and address please? - Dawn

====================================================================================================
ROW: 67
Conversation ID: 1408508
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 2.066666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Just had your Gingerbread and Butterscotch Bombe, quite simply blown away! (pardon the pun) Favourite Christmas product so far
[SUPPORT] @447374 Hi India, we are really glad you are loving our Gingerbread and Butterscotch Bombe, I'll be sure to give this a try. Thanks - Mark

====================================================================================================
ROW: 68
Conversation ID: 1866552
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 158.16666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Hi, I haven't received any Tesco vouchers in a long time (around a year) despite constantly using my card in Tesco stores-please help
[SUPPORT] @557631 Hi Ollie, that's really strange! Can you DM us your full name, address and Clubcard number so we can look into this. Kind regards - Rhys

====================================================================================================
ROW: 69
Conversation ID: 2227321
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 85.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco hi ive dm’ed you a question with regards to my visit to your opticians.
[SUPPORT] @650145 Hello Ryan. I have replied to your DM. - Alisha :)

====================================================================================================
ROW: 70
Conversation ID: 2261210
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 254.6 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Well done @Tesco that is the most horrible rhubarb crumble I've ever had the disappointment of tasting. https://t.co/sxnFBAMszk
[SUPPORT] @658376 Hi Paul, I'm sorry that you were unhappy with our rhubarb crumble. Could you please DM me and elaborate on your comment? TY - Paul

====================================================================================================
ROW: 71
Conversation ID: 2269484
Brand: Tesco
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 29.83333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Hi ho, hi ho, so its off to Tesco I shall go! Well done @Tesco https://t.co/2KF3FAtoYX
[SUPPORT] @617733 Happy to have you shopping with us, Lou! Let us know if you need anything at all :) - Christie #EveryonesWelcome

====================================================================================================
ROW: 72
Conversation ID: 56046
Brand: Tesco
Size: 4 tweets
Customer turns: 1
Support turns: 3
Duration: 61.86666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Wondering why no @2951 goats butter on shelves in @117250 or @Tesco in last weeks. When will it be back? Alternative suppliers?
[SUPPORT] @128719 Hi Nick, I am sorry to hear you can't find this product. 1/3
[SUPPORT] @128719 I have checked with my support team and they have informed me we a currently having supplier issues 2/3
[SUPPORT] @128719 There might still be product in other stores can you DM me your postcode and I can check, Ty, Andy 3/3

====================================================================================================
ROW: 73
Conversation ID: 166579
Brand: Tesco
Size: 4 tweets
Customer turns: 1
Support turns: 3
Duration: 20.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco @131115  not my favourite way to try these new biscuits. #disappointed https://t.co/RDCYgFSivY
[SUPPORT] @154691 Hi Lucie, I am very sorry to see this! It is indeed a remarkably tragic image! If you are able to return them to store with the receipt we'd be more than happy to replace them for you! 1/3
[SUPPORT] @154691 Failing that if you could DM me your name, address, email, the barcode and the store you purchased them from and the price you paid I can get a refund sent out to you so you can get some that aren't obliterated! 2/3
[SUPPORT] @154691 Can I ask if you would prefer your refund sent via post or email? Kind regards - Martin 3/3

====================================================================================================
ROW: 74
Conversation ID: 1430012
Brand: Tesco
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 174.33333333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Requested 2 Subtotal lines on self-service receipt today, neither showing. Having to resort to a calculator... 🙈
[SUPPORT] @452112 Hi Nick, sorry to hear you are having difficulty with our receipt process, can you give me a summary of the issue please. 1/2
[SUPPORT] @452112 Can you also supply a clear picture of your receipt? Regards, Andy 2/2
[CUSTOMER] @Tesco I'll DM you 😊

====================================================================================================
ROW: 75
Conversation ID: 1618012
Brand: Tesco
Size: 4 tweets
Customer turns: 1
Support turns: 3
Duration: 83.13333333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Dear @Tesco, as someone who hates BBQ sauce I feel like you should put BBQ sauce on the front of this like you do with mayo. Not pleasant. https://t.co/RHUDDoaHMC
[SUPPORT] @496106 Hi Lawrie, thanks for getting in touch. I'm also #TeamNoBBQ and I'm more than happy to feed this back. 1/3
[SUPPORT] @496106 Could you please DM your name, address, email, how much you paid, which store you bought it in and the barcode? 2/3
[SUPPORT] @496106 I'll get your feedback logged for you and arrange a refund for your surprise BBQ sauce. TY - Robyn 3/3

====================================================================================================
ROW: 76
Conversation ID: 1770256
Brand: Tesco
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 64.15 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I'm less impressed with whoever picked my onions, they look like they've come out of a bin 😂 @Tesco https://t.co/akYSdrwWRI
[SUPPORT] @532187 Oh goodness. I'm really sorry you had these delivered to you. Can you please DM your full name, address &amp; email? Thanks - Emma
[CUSTOMER] @Tesco Done, thank you for responding:)

====================================================================================================
ROW: 77
Conversation ID: 1812767
Brand: Tesco
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 2673.516666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco your gluten free game is strong 💪🏼 shame about the damn price though
[SUPPORT] @544596 Thanks for the feedback, I'm glad you're a fan of our range :) We work hard to negotiate prices &amp; your feedback really is beneficial! - Mat
[CUSTOMER] @Tesco I only say this because every time I enter tescos I end up needing 3 days off work from open wallet surgery. #glutenfreeisfookingexpensive 🙈
[SUPPORT] @544596 I totally understand. Keep an eye out for offers we have. I love the Mrs Crimble's Choc Macaroons when they are on offer. :-) TY - Rhuari

====================================================================================================
ROW: 78
Conversation ID: 2002457
Brand: Tesco
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 141.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco please sort out the card readers at Hursts on A20 before Little Chart and Hothfield, I’m losing out on points big time! 😳
[SUPPORT] @592120 Hi Justine. Is it an issue with the self service checkouts? We're having issues with them reading the key fobs everywhere at the moment. 1/2
[SUPPORT] @592120 We're working on getting them fixed, but for the meantime you can still use the contactless on the big card. Hope this helps - Cameron 2/2
[CUSTOMER] @Tesco It’s in the partnered fuel stations. Been months now and I don’t always carry the large card.

====================================================================================================
ROW: 79
Conversation ID: 2273718
Brand: Tesco
Size: 4 tweets
Customer turns: 1
Support turns: 3
Duration: 88.11666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Bought Tadcaster Road, York. Entire loaf has a nice hole through the middle. Was supposed to be the perfect post @80601 brekky :( https://t.co/QzNbtzGKvk
[SUPPORT] @661359 Hi Phil, I'm sorry your loaf has a hole running through it, I appreciate how disappointing this must be for you. Please DM me your full name, address and email address so I can refund you via Tesco Moneycard and inform our supplier? 1/3
[SUPPORT] @661359 Would you mind your details being passed to our supplier in case they wish to contact you directly for feedback? Would you prefer your Moneycard to be sent by email (can be printed or scanned off a smart phone) or in the post? 2/3
[SUPPORT] @661359 Can you also message the barcode, use by date, SC code (eg.SC1234) and batch code from the packaging along with the price you paid? A full photo of the receipt would also be helpful if you still have it. Thanks - Clare 3/3

In [81]:
# Save Batch 4 human annotations

batch_4_labels = {
    60: ("CONFIRMED_OUTCOME", "Customer explicitly confirms the Apple News workaround worked."),
    61: ("ACTIONABLE_GUIDANCE", "Support provides a concrete workaround; customer accepts it as the current solution."),
    62: ("ROUTING_ONLY", "Support redirects to an English-language support resource and asks for more details."),
    63: ("ROUTING_ONLY", "Support only redirects the customer to an English-language support channel."),
    64: ("CASE_ACTION", "Support requests the address so the delivery complaint can be fed back to the store."),
    65: ("NON_SUPPORT", "Casual food/suggestion conversation rather than a support issue."),
    66: ("DIAGNOSTIC", "Support requests order/customer details to investigate the complaint."),
    67: ("NON_SUPPORT", "Positive product feedback/social engagement."),
    68: ("DIAGNOSTIC", "Support requests account details to investigate missing vouchers."),
    69: ("ROUTING_ONLY", "Support only confirms a DM response; no substantive assistance is visible."),
    70: ("DIAGNOSTIC", "Support asks the customer to elaborate so the complaint can be investigated."),
    71: ("NON_SUPPORT", "Positive/general shopping engagement."),
    72: ("CASE_ACTION", "Support checks internally, identifies a supplier issue, and offers to check other stores."),
    73: ("CASE_ACTION", "Support offers replacement/refund and collects information needed to execute it."),
    74: ("DIAGNOSTIC", "Support requests a summary and receipt image to investigate the receipt issue."),
    75: ("CASE_ACTION", "Support explicitly says it will log feedback and arrange a refund."),
    76: ("DIAGNOSTIC", "Support requests customer details for investigation; no outcome is shown."),
    77: ("ACTIONABLE_GUIDANCE", "Support gives concrete advice to watch for relevant offers."),
    78: ("UNRESOLVED", "The proposed workaround does not solve the customer's actual fuel-station problem."),
    79: ("CASE_ACTION", "Support initiates a refund/supplier process and requests required information."),
}

for row_idx, (label, note) in batch_4_labels.items():
    resolution_screening_annotations.loc[
        row_idx, "resolution_label"
    ] = label

    resolution_screening_annotations.loc[
        row_idx, "annotation_notes"
    ] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 4 annotations saved.")
print()
print(
    resolution_screening_annotations
    .iloc[60:80]["resolution_label"]
    .value_counts()
)

Batch 4 annotations saved.

resolution_label
CASE_ACTION            5
DIAGNOSTIC             5
ROUTING_ONLY           3
NON_SUPPORT            3
ACTIONABLE_GUIDANCE    2
CONFIRMED_OUTCOME      1
UNRESOLVED             1
Name: count, dtype: int64

In [82]:
# Display Batch 5 for manual annotation

batch_5 = resolution_screening_annotations.iloc[80:100].copy()

print("Batch size:", len(batch_5))
print("Rows:", batch_5.index.tolist())

for i, row in batch_5.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Rows: [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

====================================================================================================
ROW: 80
Conversation ID: 95884
Brand: Tesco
Size: 5 tweets
Customer turns: 2
Support turns: 3
Duration: 19.2 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] When you're on in massive line @Tesco  express with one person service and two stuff members standing on the shop floor laughing at the guy serving and one of them refuses to get on the till even when asked by another stuff member. Great customer service!
[SUPPORT] @136878 Hi Laila, Sorry to learn that this has happened and I can understand how you'd be unhappy to see this. If you could let me know which store this was at, what time this happened, the colleagues names or descriptions of the colleagues. 1/2
[SUPPORT] @136878 Once I have this information I will let the stores management aware of this and they will take the appropriate action. Thanks - Lee 2/2
[CUSTOMER] @Tesco Can I DM the info?
[SUPPORT] @136878 Hi Laila, yeah that would be perfect, please DM us at your earliest convenience:) Thanks - Mark https://t.co/py5Z991Bme

====================================================================================================
ROW: 81
Conversation ID: 852099
Brand: Tesco
Size: 7 tweets
Customer turns: 3
Support turns: 4
Duration: 259.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco at Stroud is getting terrible last week yogurts 3days out of date this week mouldy peppers!!
[SUPPORT] @322410 Hi Georgia, I'm very sorry to hear this, that is very disappointing! 1/3
[SUPPORT] @322410 Also were the peppers loose or packed and did you purchase any of these items? Thanks Calum 3/3
[SUPPORT] @322410 Please could you tell exactly which store in Stroud this is and I can contact the store and get this sorted? 2/3
[CUSTOMER] @Tesco Stroud main store , I gave both items to customer services desk ,the peppers where packed
[SUPPORT] @322410 Hi Georgia, as you have returned this to the store they will feedback to our supplier for a quality inspection. Ty - Darren
[CUSTOMER] @Tesco Ok Thankyou

====================================================================================================
ROW: 82
Conversation ID: 879556
Brand: Tesco
Size: 5 tweets
Customer turns: 2
Support turns: 3
Duration: 1272.7333333333331 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco this was the last leek at my Tesco express. What a joke! https://t.co/xC9RA9XF72
[SUPPORT] @328821 Hi Joe, what seems to be the problem? - Nick
[CUSTOMER] @Tesco 1 tinynleek in all that packaging!! So wasteful and pointless.
[SUPPORT] @328821 Hi Joe, Thanks for the feedback, can you DM your details and I'll pass your feedback to our head office 1/2
[SUPPORT] @328821 If you could send me details of the store, your full name and address. Thanks - Mark 2/2

====================================================================================================
ROW: 83
Conversation ID: 1737196
Brand: Tesco
Size: 5 tweets
Customer turns: 1
Support turns: 4
Duration: 419.25 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Only bought these a week ago... thanks @Tesco https://t.co/a5wLFgq7j0
[SUPPORT] @524419 Hi Ben, I am very sorry about this. I would like to feed this back to our supplier. 1/4
[SUPPORT] @524419 Please could we have a picture of the packaging, including the barcode, date code and SC code that is usually near the Tesco address? 2/4
[SUPPORT] @524419 Please could you DM us with your name, address, email address, the store you purchased them from and price paid? 3/4
[SUPPORT] @524419 Are you happy for us to attach your details to the report we send to our supplier? - Allyn 4/4

====================================================================================================
ROW: 84
Conversation ID: 1837286
Brand: Tesco
Size: 7 tweets
Customer turns: 2
Support turns: 5
Duration: 1426.7666666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] How does your Tesco Direct Partners work @tesco You sell their items with a mark-up and still add deliv charge to your 'valued' customers?
[SUPPORT] @494055 Hello Andrea, the price you'll find for delivery and items sold by Partners are set by the Partners themselves. I hope this helps. Ty - John
[CUSTOMER] @Tesco No, John. Perfume bought through @Tesco £39.71 - Direct from your Partner would have been £35.05 &amp; I got to pay deliv charge of £3.95.
[SUPPORT] @494055 Hi Andrea. Our Tesco Partners use our website as a platform to sell their own products, they are not purchased from Tesco. 1/4
[SUPPORT] @494055 This means Tesco promotions do not apply to these products as they are purchased from another company. 2/4
[SUPPORT] @494055 We added Tesco Partners some time ago to give our customers a wider variety of products to choose from on our website. 3/4
[SUPPORT] @494055 You can refine your search to Tesco products to ensure Tesco promotions like our delivery saver apply. I hope this helps. Cheers - Billy 3/4

====================================================================================================
ROW: 85
Conversation ID: 1950868
Brand: Tesco
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 3450.833333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Nothing like a @133684 in @Tesco but then you have to sit your little one in a high chair with straps that are dirty and stink 😡
[CUSTOMER] @133684 @Tesco And look like they have never been washed.  #Grim #Dirty #HowGermsSpread
[SUPPORT] @579406 Hi Kat, that is not good at all. Can you let me know what store this is and also if you spoke to anyone about this at the time? Ty - Darren
[CUSTOMER] @133684 @Tesco Grove Green, Maidstone. Yes I did but was told it’s the only high chair they have so pretty much tough 🙄
[SUPPORT] @579406 @133684 Hi Kat, thanks for replying, can you please DM a brief description of the colleague you spoke to and the time and date you visited? - Struan

====================================================================================================
ROW: 86
Conversation ID: 2036091
Brand: Tesco
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 11895.433333333332 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Why is there no Wonder Woman in the @Tesco Justice League? https://t.co/GpjJBGIPfs
[CUSTOMER] @601961 @Tesco Sold out due to popularity?
[CUSTOMER] @601962 @Tesco Well there certainly wasn’t any tags out suggesting that. There was price tags on for all the male team members. Just seems odd.
[SUPPORT] @601961 Hi John, thanks for taking the time to contact us. I'm really sorry there are no Wonder Woman toys. 1/2
[SUPPORT] @601961 I'll get this looked into with the store. Thanks for bringing this to our attention. TY - Robyn 2/2
[SUPPORT] @601961 Hi John, thanks for your patience. The supplier hasn't included the Wonder Woman character in the range due to low sales. Charlotte

====================================================================================================
ROW: 87
Conversation ID: 2880965
Brand: Tesco
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 2064.0 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] shoutout to the security guard at Tesco in Goodmayes who decided to stop me for no sane reason when the alarm by the doors went off. all i did was go in to buy blue top milk and you haven’t got any kmt. what the fuck am i gonna steal, a loaf of bread?
[CUSTOMER] LOLOLOLOLOLOL the security guard was like, “what have you got, open your bag”. i just gave it and told him to check himself. @Tesco your security need stuff to do, help them out
[SUPPORT] @799427 Hi There, I'm very sorry you feel this way. I'm sure you understand that our security guards have a job to do and if the alarm goes off they need to investigate this. However he could have handled this better than he did.1/2
[SUPPORT] @799427 Would you like me to get this logged and fed back to the stores management team? Can you please tell me the name of the security guard or a description. Also your full name, address and email. Kind regards - Stacey. 2/2
[CUSTOMER] @Tesco Hi Stacey, apologies for the late reply. it’s all good, i don’t wish to file a complaint, just letting you guys know that your security staff need things to do since they’re static, &amp; i prefer to DM you my details if that’s okay
[SUPPORT] @799427 Hi there, please reply via DM with the details my colleague requested? I will pass on your feedback to the Store Manager. TY - Joanne

====================================================================================================
ROW: 88
Conversation ID: 143038
Brand: Tesco
Size: 14 tweets
Customer turns: 10
Support turns: 4
Duration: 6344.133333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Very useful charge at Tesco Extra, Crawley. Quickly to 80% from 20% on Leaf with ABB rapid charger at 24p per kWh. Great facility. Thanks @Tesco &amp; @122417 (just behind the click+collect by the petrol station, for anyone looking. ) https://t.co/00Yn4SgYZK
[SUPPORT] @148298 It's great that your finding the facilities so useful 🙌 Would there be anyway they could be improved or anything you'd like to see added?
[CUSTOMER] @Tesco It’s early days, yet, but probably plan for 3 or 4 rapid chargers near the petrol station &amp; 20+ 7 kW chargers in the main car park, over next couple of years. Many people will do what I did, rapid charge &amp; finish charging on the slow chargers while we shop. Great facility, thanks https://t.co/GywjB8Prum
[SUPPORT] @148298 It'll be the norm before long 😊 Thanks for your input though, it's much appreciated! Have a good one 👍
[CUSTOMER] @148298 @Tesco How much does it cost to ‘fill up’ your car and how far will it get you?
[CUSTOMER] @Tesco @148298 Can we have some 7kw chargers at the Winchester store please @Tesco? Was disappointed you didn't install with recent car park works and store refresh.
[SUPPORT] @148299 Hi Sean, please can you provide us with your name, address &amp; email via DM? We can then log your interest in seeing this. - Rocsi https://t.co/py5Z991Bme
[CUSTOMER] @Tesco @148298 Any chance of some rapid chargers at Northern Ireland stores?
[CUSTOMER] @148300 @Tesco @148298  https://t.co/Q2G99O91Vc
[CUSTOMER] @148301 @Tesco @148298 Is that Heather Locklear's hair on the right?
[CUSTOMER] @Tesco @148298 Any chance of branching out to Scottish stores? Would be well received North of the wall :-)
[CUSTOMER] @148303 @Tesco We havenae rebuilt the wall yet.
[SUPPORT] @148303 Hi there, we don't actually have an exact date to when they will make their way up to Scotland. But it is starting to branch out into more and more stores. So hopefully they will be available in the near future. Thanks, Calum
[CUSTOMER] @Tesco Ok, thanks. Sooner, the better! Ones in my town are closest to an Aldi and an Asda, so you'd be doing yourselves a favour :-)

====================================================================================================
ROW: 89
Conversation ID: 885963
Brand: Tesco
Size: 10 tweets
Customer turns: 4
Support turns: 6
Duration: 1911.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco how come youve stopped selling gnocci??? #favourite
[SUPPORT] @330366 Hi Ruth, can you let me know what store you are struggling to find this in please? I'll look in to this for you :) Thanks - Josh
[CUSTOMER] @Tesco At Chichester Extras store :)
[SUPPORT] @330366 Hi Ruth, I've had a look and I can tell you that there is in fact 8 of this product in-store. 1/2
[SUPPORT] @330366 Keep in mind this does no include what may be in customers baskets right now. The store is expecting a delivery at 10PM tonight. TY Mike 2/2
[CUSTOMER] @Tesco We could only find gluten free.... there isnt even a hole on the shelf for them anymore....might have to go elsewhere 😕
[SUPPORT] @330366 Hi Ruth, I am very sorry you are having troubles in finding this in the store. 1/2
[SUPPORT] @330366 I can let you know at the moment there is 13 in stock and they are currently located in aisle 24 on the right hand side. Ty – Darren 2/2
[CUSTOMER] @Tesco You used to sell non fresh that was half this price :( https://t.co/F8D2MTZkNp
[SUPPORT] @330366 Hi Ruth, we still do sell the non fresh version in stores. :) Did you ask any of my colleagues if they had any? - Danny

====================================================================================================
ROW: 90
Conversation ID: 1443444
Brand: Tesco
Size: 9 tweets
Customer turns: 7
Support turns: 2
Duration: 110.16666666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] I thought it was so crap that all schools were shut, so many businesses sent their workers home but @Tesco made them stay #Ophelia #badShout
[CUSTOMER] @454917 @Tesco I thought I saw Tesco closed a lot of stores
[CUSTOMER] @139085 @Tesco The one near me was still open at 230 and the warning to not go outside was at 3 - the girl said there was no sign of them heading home
[CUSTOMER] @454917 @Tesco Where was that?
[CUSTOMER] @139085 @Tesco Lisburn Road
[SUPPORT] @454917 Hi Megan, all our stores closed at 5pm tonight in Northern Ireland and the Republic due to extreme weather conditions. TY - Callum
[CUSTOMER] @Tesco The warning said everybody should be home by 3pm lol
[CUSTOMER] @Tesco The warning said everybody should be home and not leave their homes after 3pm lol
[SUPPORT] @454917 Hi Megs, that was the time we were advised. However, the stores would be closed by now. Thanks - Luciano

====================================================================================================
ROW: 91
Conversation ID: 1500060
Brand: Tesco
Size: 11 tweets
Customer turns: 4
Support turns: 7
Duration: 2013.3166666666664 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco Can't believe the hours I have spent trying to complete a large online order with lots of issues and now unable to checkout. Crying!!
[SUPPORT] @468266 Oh no, Fiona! I'm so sorry :( Was this Tesco Direct or Groceries? I'll make sure that your comments are passed to the right team. 1/2
[CUSTOMER] @Tesco groceries I am so frustrated it's ridiculous. Completely put off ever using you again. Wasted morning, no food!!
[SUPPORT] @468266 Hi Fiona, I'm so sorry we are currently experiencing website issues and our online team are working to resolve them as soon as possible. 1/2
[SUPPORT] @468266 Do you see an error message or is the page unresponsive? Did you first see the problem when clicking the checkout button?TY Mike 2/2
[CUSTOMER] @Tesco lots problems whilst adding items - error messages, page unresponsive. Clicking checkout was ultimate frustaration just led to blank screen.
[SUPPORT] @468266 Hi Fiona, we have a few steps for you to follow to help get you up and running. 1/3
[SUPPORT] @468266 Can you please clear the cache/cookies on your browser, then check the date and time on device. 2/3
[SUPPORT] @468266 Please then close the browser and reopen, please then try once more. This should work, however if not please get back in touch. Ty Andy 3/3
[CUSTOMER] @Tesco I can assure you the problem is all with your 'new' website. Not going to 'fix' my pc, I'll go to Asda's website instead!!
[SUPPORT] @468266 I am sorry Fiona, can you please DM your full name, address and email? I can log your feedback. TY - Chris

====================================================================================================
ROW: 92
Conversation ID: 1631420
Brand: Tesco
Size: 12 tweets
Customer turns: 7
Support turns: 5
Duration: 12127.4 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @Tesco I have been trying to order my Online Shopping for 4 days and the payment page keeps saying ‘An Error’ - Can you help?
[SUPPORT] @499285 I'm sorry for the inconvenience. We're aware of some problems with the website and are investigating further. 1/2
[SUPPORT] @499285 At this time we have no timescale for this and are hoping to be back up and running soon. Charlotte 2/2
[CUSTOMER] @Tesco Ok - Thanks!
[CUSTOMER] @Tesco Hi, This issue is still going on. When will this be resolved? I pay a monthly delivery charge. What is the point?!
[SUPPORT] @499285 Hi Jessica, I'm really you're still having issues! What's the specific error message you see when trying to place an order? Can you DM us? (This will help us reply without the character limit!) - Emma
[CUSTOMER] @Tesco DM’d - Thanks!
[SUPPORT] @499285 Hi Jessica thanks for getting back to us, I am really sorry you are experiencing difficulties booking a delivery :( can you send us your name, address &amp; email by DM please so we can access your account please? - Mike
[CUSTOMER] @Tesco DM’d - Thanks!
[CUSTOMER] @Tesco Hi, Can someone get back to me ASAP. This is the error message
[CUSTOMER] @Tesco  https://t.co/4mh6Nhd2KV
[SUPPORT] @499285 I've replied to your DM :)

====================================================================================================
ROW: 93
Conversation ID: 1842494
Brand: Tesco
Size: 14 tweets
Customer turns: 8
Support turns: 6
Duration: 232.0 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Shocking 2 find you can't return a faulty item in a 24hr store after 10pm @Tesco. Shouldn't be 24hr if you can't offer every service.
[SUPPORT] @552135 Hi there, did you ask if a manager could do this for you? They may have been able to see if they could resolve this for you - Allyn
[CUSTOMER] @Tesco I spoke to the manager on the phone 940 she was finishing at 10. No staff trained in refunds after this. Most helpful was the security guard
[CUSTOMER] @Tesco It was a cracked TV screen. Had to then buy another one with the option of returning to store again today to refund the original
[CUSTOMER] @Tesco Shocking management if you're open 24 hours a day but only for basic things
[SUPPORT] @552135 I am very sorry about this, please could you advise what store you visited? - Allyn
[CUSTOMER] @Tesco Walsall Extra
[CUSTOMER] @Tesco Can you advise, is this Company policy or solely an inept MGMT team at the branch?
[SUPPORT] @552135 Hi there, I have checked on this for you. It is due to the type of product it is. 1/2
[SUPPORT] @552135 The process of returning a TV needs to go through the helpline and they can only do up until 10pm - Allyn 2/2
[CUSTOMER] @Tesco So why allow these to be sold after 10pm?
[SUPPORT] @552135 Hi, the reason why we can sell after 10pm is all electric items can be purchased 24 hours.
[SUPPORT] @552135 For returns and faults our customers must contact the electrical helpline so we can determine whether the items can be repaired - David
[CUSTOMER] @Tesco Ok but a bit of common sense  would suggest a cracked screen won't be repaired

====================================================================================================
ROW: 94
Conversation ID: 2612474
Brand: Tesco
Size: 10 tweets
Customer turns: 4
Support turns: 6
Duration: 184.7333333333333 minutes

In [83]:
# Save Batch 5 annotations

batch_5_labels = {
    80: ("CASE_ACTION", "Support will pass the complaint to store management after collecting details."),
    81: ("CONFIRMED_OUTCOME", "Customer returned the products and support confirms supplier quality feedback will occur; customer acknowledges completion."),
    82: ("CASE_ACTION", "Support collects store/customer details to pass packaging feedback to head office."),
    83: ("CASE_ACTION", "Support is collecting evidence/details to formally report the product issue to the supplier."),
    84: ("ACTIONABLE_GUIDANCE", "Support explains the Partner model and tells the customer how to filter for Tesco products/promotions."),
    85: ("CASE_ACTION", "Support collects details to escalate the hygiene complaint to store management."),
    86: ("CASE_ACTION", "Support investigates with the store/supplier and provides the reason for the product range decision."),
    87: ("CASE_ACTION", "Support agrees to log and pass the security complaint/feedback to store management."),
    88: ("CASE_ACTION", "Support collects details to log the customer's request for additional charging facilities and provides availability information."),
    89: ("ACTIONABLE_GUIDANCE", "Support checks inventory and gives the customer the aisle/location and stock information."),
    90: ("ACTIONABLE_GUIDANCE", "Support provides the store-closing information and explains the timing during extreme weather."),
    91: ("UNRESOLVED", "Troubleshooting is offered, but the customer rejects it and the actual website problem remains unresolved."),
    92: ("UNRESOLVED", "The customer explicitly reports the problem is still occurring; the visible conversation only moves into DM/support investigation."),
    93: ("ACTIONABLE_GUIDANCE", "Support explains the return policy/process and tells the customer how electrical returns are handled."),
    94: ("CASE_ACTION", "Support initiates complaint logging/supplier feedback and reimbursement handling, then continues collecting required details."),
    95: ("CASE_ACTION", "Support collects product/customer details for supplier investigation while also suggesting a possible size adjustment."),
    96: ("DIAGNOSTIC", "Support asks for more details before investigating the purchase/game entitlement issue."),
    97: ("ACTIONABLE_GUIDANCE", "Support provides a direct resource for managing/cancelling the subscription."),
    98: ("DIAGNOSTIC", "Support needs the Gamertag and additional details before investigating the missing update."),
    99: ("ACTIONABLE_GUIDANCE", "Support provides a concrete troubleshooting guide for the wireless-network problem."),
}

for row_idx, (label, note) in batch_5_labels.items():
    resolution_screening_annotations.loc[row_idx, "resolution_label"] = label
    resolution_screening_annotations.loc[row_idx, "annotation_notes"] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 5 annotations saved.")
print(resolution_screening_annotations.iloc[80:100]["resolution_label"].value_counts())

Batch 5 annotations saved.
resolution_label
CASE_ACTION            9
ACTIONABLE_GUIDANCE    6
UNRESOLVED             2
DIAGNOSTIC             2
CONFIRMED_OUTCOME      1
Name: count, dtype: int64

In [84]:
# Display Batch 6 for manual annotation

batch_6 = resolution_screening_annotations.iloc[100:120].copy()

print("Batch size:", len(batch_6))
print("Rows:", batch_6.index.tolist())

for i, row in batch_6.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 20
Rows: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]

====================================================================================================
ROW: 100
Conversation ID: 2285965
Brand: XboxSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 607.5333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport need to have your guys fix the messaging apps "talk to text" feature. It's not good. Thank you.
[SUPPORT] @664268 Hey, could you direct message us and explain in detail what issue you are experiencing?
 ^RM

====================================================================================================
ROW: 101
Conversation ID: 2328826
Brand: XboxSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 139.75 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I have the disc for Dishonored 2. It installed on 1 Xbox, but not on my other.  The disc had no damage.  What can I do?
[SUPPORT] @485337 Hello, thanks for reaching out to us. Are you seeing any errors when you try to install the game? ^CO

====================================================================================================
ROW: 102
Conversation ID: 2654484
Brand: XboxSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 63.28333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport why is my messaging blocked?  I didn’t break any code of conduct I don’t even use chat in game.
[SUPPORT] @748490 Hi there. If you sign in here https://t.co/AnmW7twuVZ do you see any issues with the account? ^JL

====================================================================================================
ROW: 103
Conversation ID: 2749934
Brand: XboxSupport
Size: 2 tweets
Customer turns: 1
Support turns: 1
Duration: 120.36666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport why ea access trials sw and nfs does not work?
[SUPPORT] @200318 Hi there, what happens when you try? Can you please DM: https://t.co/nPX1yNG0Tv your gamertag and a detailed issue summary? ^ZM

====================================================================================================
ROW: 104
Conversation ID: 99045
Brand: XboxSupport
Size: 3 tweets
Customer turns: 1
Support turns: 2
Duration: 588.1 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] How’s this invisible lag switcher tank.... cheating cum junkie. Happens all to often and no body cares..cause companies still getting paid.. @45971 @19645 @115446 @115786 @XboxSupport https://t.co/FiBPiIcsyO
[SUPPORT] @137691 If you believe that your suspension was incorrectly levied against you please head over here: https://t.co/DKYj5dv910  1 ^XS
[SUPPORT] @137691 if you are eligible for a case review you can do that there as well.  2 ^XS

====================================================================================================
ROW: 105
Conversation ID: 409027
Brand: XboxSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 60.86666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115766 @XboxSupport Is there something wrong with Modern Warfare Remastered? I can’t connect to the servers
[CUSTOMER] @115766 @XboxSupport Keep getting this message https://t.co/SFsHSaM0LP
[SUPPORT] @212529 Hi there, can you DM us your Gamertag and if this is happening with any other games? ^JS

====================================================================================================
ROW: 106
Conversation ID: 1410921
Brand: XboxSupport
Size: 3 tweets
Customer turns: 1
Support turns: 2
Duration: 312.7333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I have been treated disgustingly by your colleagues, you have banned me and I have not done anything wrong!! It’s disgusting
[SUPPORT] @447936 Hi there, sorry to hear about the frustrating experience. Can you please DM: https://t.co/nPX1yNXCi5 us your gamertag so  1 ^ZM
[SUPPORT] @447936 we can take a closer look into the issue? Were you provided with a service request number?  2 ^ZM

====================================================================================================
ROW: 107
Conversation ID: 1482800
Brand: XboxSupport
Size: 3 tweets
Customer turns: 1
Support turns: 2
Duration: 19.23333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport Can you please look into my recent stuff I bought on Xbox because I haven’t done anything  wrong. https://t.co/n69Z1g8nkW
[SUPPORT] @464316 Hi there. unfortunately, we are not part of Enforcement and would not be able to look into  1 ^JL
[SUPPORT] @464316 this with you. The best course of action, if you are eligible, would be the case review.  2 ^JL

====================================================================================================
ROW: 108
Conversation ID: 1520786
Brand: XboxSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 641.7 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport Hello every time I try to log in on the xbox app on ios this comes upp!? Thanks for help. https://t.co/Xc4sTrJTei
[SUPPORT] @472735 We'd be happy to help, but we could use more info. Could you follow &amp; DM @Xboxsupport with your Gamertag &amp; some details? ^EZ
[CUSTOMER] @XboxSupport Sure

====================================================================================================
ROW: 109
Conversation ID: 1585692
Brand: XboxSupport
Size: 3 tweets
Customer turns: 2
Support turns: 1
Duration: 1160.3833333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] HEY FIX YOUR SERVERS I JUST WANNA PLAY @ATVIAssist @115765 @XboxSupport
[SUPPORT] @487874 Hello! Xbox Live Services are currently experiencing issues. You can stay up to date here: https://t.co/NSXOiTMoQ9
 ^RR
[CUSTOMER] @XboxSupport i don’t want to stay up to date i want my $60 back. Who can i contact for a refund?

====================================================================================================
ROW: 110
Conversation ID: 1589638
Brand: XboxSupport
Size: 4 tweets
Customer turns: 2
Support turns: 2
Duration: 1111.2666666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport my son has an xbox one and he is getting a blue screen all the time...he has taken all cables out etc and cannot fix it.
[SUPPORT] @488784 Hi there, we'd like to help but could use more info. Can you please send us  1 ^ZM
[SUPPORT] @488784 a DM: https://t.co/nPX1yNXCi5 with your gamertag and a detailed summary of the issue you're experiencing?  2 ^ZM
[CUSTOMER] @XboxSupport send us what? 1^ZM mean?

====================================================================================================
ROW: 111
Conversation ID: 2355974
Brand: XboxSupport
Size: 4 tweets
Customer turns: 3
Support turns: 1
Duration: 1032.1833333333334 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport having a lot of poor picture when watching purchased content on Microsoft movies and tv regularly. Hard wired to console. Connection tests look good. Almost 80mgbs download speed. Other stream services are fine.
[CUSTOMER] @XboxSupport Nvrmnd resolves with online chat. Thank you.
[SUPPORT] @680624 Great to hear online chat was able to help you out! Feel free to reach out should you have future Xbox Support questions! Happy Gaming!
 ^JS
[CUSTOMER] @XboxSupport Unfortunately it’s happening again. Nat is open. Speed is good. Hard wired to modem. Other video services look fine. I’ve done two console resets.

====================================================================================================
ROW: 112
Conversation ID: 709764
Brand: XboxSupport
Size: 6 tweets
Customer turns: 4
Support turns: 2
Duration: 9.5 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @115786 @XboxSupport Yo, boys! Fix your reporting system FFS!! Been banned 3 times, one of which was 'cheating' courtesy of BO2 modded lobbies
[CUSTOMER] @115786 @XboxSupport The other two were 'Communication' WELL I'M SORRY IF A SALTY NEW BORN STARTS GIVING ME HATE AND I SAY SOMETHING BACK!
[CUSTOMER] @115786 @XboxSupport LIKE FOR GOODNESS SAKE I'M OLD ENOUGH TO SWEAR AND PLAY THIS GAME THAT IS @187040!! I just wanna play my game in peace w/ calm chats
[CUSTOMER] @115786 @XboxSupport @187040 If I eventually get perma/console banned I will have lost Xbox and you will have lost a VERY loyal fan/supporter. I've played for YEARS!
[SUPPORT] @289705 Hi there. We're actually separate from the enforcement team &amp; couldn't provide info on their actions. Recommend 1/2
 ^TJ
[SUPPORT] @289705 Submitting a Case Review for more info regarding this https://t.co/U1yn6tkAAG 2/2 ^TJ

====================================================================================================
ROW: 113
Conversation ID: 940998
Brand: XboxSupport
Size: 5 tweets
Customer turns: 3
Support turns: 2
Duration: 206.9333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Anyone else having issues with the new dash not loading games *yes I've done hard resets  @XboxSupport
[CUSTOMER] @343074 @XboxSupport I find that switching over to input 1 on my tv usually fixes it. Oh and turnin off the the Xbox and tuning the PS4 on helps. #jk
[CUSTOMER] @343075 @XboxSupport Love it
[SUPPORT] @343074 Heyo! We'd like to Direct Message so we can collect some more information. Can you follow and  1 ^BZ
[SUPPORT] @343074 DM us your Gamertag and clarify what the issue is that you're having so we can investigate?  2 ^BZ

====================================================================================================
ROW: 114
Conversation ID: 1171806
Brand: XboxSupport
Size: 5 tweets
Customer turns: 4
Support turns: 1
Duration: 84.66666666666667 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I suddenly got the teredo, tried powercycling, portenabling. Can't even log in anymore. What to do? Gt: MyNameBounce (germany)
[CUSTOMER] @395607 live is down in germany right now.  Italy as well #XboxHelp
[CUSTOMER] @391615 Does this teredo Thing come along with the Xbox Live issues? Never had this before
[SUPPORT] @395607 Hi, can you clarify what is "teredo" ? ^RM
[CUSTOMER] @XboxSupport @395607 Dumb service. Fix it idiots!!!

====================================================================================================
ROW: 115
Conversation ID: 1410288
Brand: XboxSupport
Size: 8 tweets
Customer turns: 4
Support turns: 4
Duration: 92.91666666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport My redeem a code doesn't work, it keeps telling me to wait a bit but I've waited all day and still says the same thing
[SUPPORT] @447810 Hi, what redeem code are you trying to use? ^RM
[CUSTOMER] @XboxSupport Its for Xbox gold but when I click the redeem a code on the Xbox store it tells me to try again later
[SUPPORT] @447810 Have you tried redeeming the code here https://t.co/rM6pkPWTdX ^RM
[CUSTOMER] @XboxSupport Yes I have tried the website but it gives me an error also
[SUPPORT] @447810 What error appears? ^RM
[CUSTOMER] @XboxSupport Ive getting this all day https://t.co/4uwliYDUcS
[SUPPORT] @447810 Can you DM us your Gamertag, your NAT type, and a photo of your Detailed Network Stats from your Network Settings? ^CO

====================================================================================================
ROW: 116
Conversation ID: 1689835
Brand: XboxSupport
Size: 6 tweets
Customer turns: 4
Support turns: 2
Duration: 1490.2333333333331 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Only 2 days left to help the #Xbox community earn $500,000 for @129905! Get the full details at https://t.co/QNRcle6H6w. [E-M] https://t.co/l8T9Ca9qfX
[CUSTOMER] @115786 @129905 @115786  can you explain how my online has expired? This happened 1st November...... https://t.co/ffjjp9KfuR
[CUSTOMER] @115786 @129905 @XboxSupport Can you take a look at this
[SUPPORT] @513032 Apologies for missing your previous message! Let's have you reach out to our  1 ^JS
[SUPPORT] @513032 chat team https://t.co/lUV7XYl61S as they are the best equipped to help with this!  2 ^JS
[CUSTOMER] @XboxSupport I have talked with the live chat team since november 1st but not solved.

====================================================================================================
ROW: 117
Conversation ID: 2307471
Brand: XboxSupport
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 427.8 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I'm having trouble muting game audio coming through my headset. I no longer have the option to turn it off.
[SUPPORT] @669369 Hey, how did you previously mute game audio? ^RM
[CUSTOMER] @XboxSupport I'm using an Afterglow LVL 1 headset with a 3.5 mm jack. And even in the Xbox Accessories it doesn't show me able to adjust volume.
[SUPPORT] @669369 Have you tried accessing the settings to your chat audio by going to the console settings then Kinect and Device settings? ^RM
[CUSTOMER] @XboxSupport This is what I get/have. Please keep in mind I have updated my dashboard because of the Xbox Insiders Program. https://t.co/SgfmWpCTqI
[SUPPORT] @669369 So with the new update, are you not seeing them when you press guide and over to settings at the top? ^CO

====================================================================================================
ROW: 118
Conversation ID: 2319195
Brand: XboxSupport
Size: 6 tweets
Customer turns: 3
Support turns: 3
Duration: 432.98333333333335 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport is there a way to use old dashboard appearance because I got the new update and it’s horrible.
[SUPPORT] @149594 Hello, thanks for reaching out to us. Once the update has been applied, it cannot be rolled back. ^CO
[CUSTOMER] @XboxSupport What about you guys reverting to the old. It’s a suggestion. Multiple people I’ve seen hate the new update.
[SUPPORT] @149594 We don't have the ability to influence update changes. We're here if you see any issues though. ^CO
[CUSTOMER] @XboxSupport There’s an issue where messages don’t show up unless I physically go check. They work fine on the 360 port though.
[SUPPORT] @149594 Thanks for that feedback! Can you DM us your gamertag, your NAT type, and your detailed network stats. ^CO

====================================================================================================
ROW: 119
Conversation ID: 2363783
Brand: XboxSupport
Size: 7 tweets
Customer turns: 3
Support turns: 4
Duration: 94.31666666666666 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] My @115786 randomly turns itself on for no reason. Why, @XboxSupport? Why?!
[SUPPORT] @682479 Hi there! Is the console plugged directly into a wall socket? Are there other users  1 ^BL
[SUPPORT] @682479 in the home with mobile devices connected to the console through the network by chance?  2 ^BL
[CUSTOMER] @XboxSupport My iPhone has the Xbox app but it hardly ever connects when I want it to connect. And I'm not using the phone or app when the Xbox randomly turns on. That's the only connected device.
[SUPPORT] @682479 Thank you for confirming that. Is the console plugged into a wall socket directly?  ^BL
[CUSTOMER] @XboxSupport Yes it is.
[SUPPORT] @682479 Can you let us know the power setting the console is on: https://t.co/JQ878rRNzU ^BL

In [85]:
# Save Batch 6 annotations

batch_6_labels = {
    100: ("DIAGNOSTIC", "Support asks for detailed information before investigating the messaging issue."),
    101: ("DIAGNOSTIC", "Support asks whether an installation error occurs before troubleshooting."),
    102: ("ACTIONABLE_GUIDANCE", "Support provides a concrete account-check step through the supplied link."),
    103: ("DIAGNOSTIC", "Support asks what happens and requests Gamertag/details for investigation."),
    104: ("ACTIONABLE_GUIDANCE", "Support directs the customer to the formal suspension/case-review process."),
    105: ("DIAGNOSTIC", "Support requests Gamertag and comparison with other games to diagnose the server issue."),
    106: ("DIAGNOSTIC", "Support requests Gamertag and service-request information to investigate the complaint."),
    107: ("ACTIONABLE_GUIDANCE", "Support explains that it cannot handle enforcement and directs the customer to case review."),
    108: ("DIAGNOSTIC", "Support requests Gamertag and additional details before investigating the login issue."),
    109: ("UNRESOLVED", "Xbox acknowledges an outage, but the customer's refund request remains unanswered in the visible conversation."),
    110: ("DIAGNOSTIC", "Support requests Gamertag and a detailed issue summary; no troubleshooting outcome is reached."),
    111: ("UNRESOLVED", "The issue was temporarily resolved through chat but explicitly recurs afterward."),
    112: ("ACTIONABLE_GUIDANCE", "Support directs the customer to submit a Case Review for enforcement information."),
    113: ("DIAGNOSTIC", "Support requests Gamertag and clarification so the issue can be investigated."),
    114: ("DIAGNOSTIC", "Support asks for clarification of the 'teredo' issue; no solution is provided."),
    115: ("DIAGNOSTIC", "Support progressively gathers error/network information and requests diagnostic details."),
    116: ("UNRESOLVED", "Customer explicitly says the live-chat team has not solved the issue."),
    117: ("DIAGNOSTIC", "Support is still gathering information and testing settings; no resolution is shown."),
    118: ("DIAGNOSTIC", "Customer introduces a technical issue and support requests network/account details for investigation."),
    119: ("DIAGNOSTIC", "Support is actively gathering information about the unexpected console behavior; no outcome yet."),
}

for row_idx, (label, note) in batch_6_labels.items():
    resolution_screening_annotations.loc[row_idx, "resolution_label"] = label
    resolution_screening_annotations.loc[row_idx, "annotation_notes"] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Batch 6 annotations saved.")
print(resolution_screening_annotations.iloc[100:120]["resolution_label"].value_counts())

Batch 6 annotations saved.
resolution_label
DIAGNOSTIC             13
ACTIONABLE_GUIDANCE     4
UNRESOLVED              3
Name: count, dtype: int64

In [86]:
# Display final annotation batch

batch_7 = resolution_screening_annotations.iloc[120:128].copy()

print("Batch size:", len(batch_7))
print("Rows:", batch_7.index.tolist())

for i, row in batch_7.iterrows():
    print("\n" + "=" * 100)
    print(f"ROW: {i}")
    print(f"Conversation ID: {row['conversation_id']}")
    print(f"Brand: {row['support_account']}")
    print(f"Size: {row['conversation_size']} tweets")
    print(f"Customer turns: {row['customer_turns']}")
    print(f"Support turns: {row['support_turns']}")
    print(f"Duration: {row['duration_minutes']} minutes")
    print("-" * 100)
    print(row["conversation_text"])

Batch size: 8
Rows: [120, 121, 122, 123, 124, 125, 126, 127]

====================================================================================================
ROW: 120
Conversation ID: 881763
Brand: XboxSupport
Size: 13 tweets
Customer turns: 8
Support turns: 5
Duration: 1324.65 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] Lost over 100,000 Gamerscore after the most recent @115786 update. @15913, @116543, @115787 is this a known issue?
[CUSTOMER] @115786 @15913 @116543 @115787 Someone on Reddit has the same issue I'm having. https://t.co/gKtOM60Ki8
[SUPPORT] @329367 @115786 @15913 @116543 @115787 Definitely odd. To be sure is this consistent on the Xbox App and the https://t.co/6DxzuMtRWi?? Can you also dm your GT and 1/2 ^IS
[SUPPORT] @329367 @115786 @15913 @116543 @115787 the specific achievements that you notice are missing? That would be very helpful. https://t.co/nPX1yNG0Tv 2/2 ^IS
[CUSTOMER] @XboxSupport Yup. The issue is on my Xbox, App, and website. Clicking on an individual game shows the achievements I unlocked, but the Gamerscore for
[CUSTOMER] @XboxSupport Many games appear as 0 when looking through the tab. To make matters worse, the games where Gamerscore has disappeared have taken away from
[CUSTOMER] @XboxSupport My overall Gamerscore. I lost over 100,000 GS. Anything I unlock now increases the number, but everything else seems lost.
[SUPPORT] @329367 Hi there! Could you DM https://t.co/nPX1yNXCi5 us your Gamertag and any steps you've tried to fix this already? ^JS
[CUSTOMER] @XboxSupport Sent!
[SUPPORT] @329367 Thank you for all of that information, that really helps, so you can see the score/achievement  1 ^RM
[SUPPORT] @329367 when you click on a game but it is not being added to your overall score?  2 ^RM
[CUSTOMER] @XboxSupport Anything I earn AFTER I lost my Gamerscore adds to my overall score. Those games that I lost my Gamerscore on only appear when clicking on
[CUSTOMER] @XboxSupport the specific game. I can see that I unlocked them and that I received the score, but so many of them just "vanished" from my overall score.

====================================================================================================
ROW: 121
Conversation ID: 883847
Brand: XboxSupport
Size: 12 tweets
Customer turns: 8
Support turns: 4
Duration: 14362.366666666669 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport why tf wont it let me AND my friend buy the friday the 13th collection?
[SUPPORT] @329888 Hey there, are you able to make the purchase on the https://t.co/6DxzuMLtkS website? ^XS
[CUSTOMER] @XboxSupport No go on the website. Why no purchase?
[SUPPORT] @329888 Can you please DM us your Gamertag so that we can collect some more information from you? ^XS
[CUSTOMER] @XboxSupport ringding 024
[SUPPORT] @329888 Thanks for that, we are currently investigating the issue, and as that you please bear with us while we get it corrected. ^XS
[CUSTOMER] @XboxSupport Still nothing
[CUSTOMER] @XboxSupport  https://t.co/1a4a7pGPfr
[CUSTOMER] @XboxSupport Why isnt it working?
[SUPPORT] @329888 Hi there! This issue is currently being looked into. We appreciate your patience &amp; understanding.  ^JA
[CUSTOMER] @XboxSupport Anything?!
[CUSTOMER] @XboxSupport Hello xbox support. It has been several days, weeks even, since this problem has arose. I have a video that i have posted oct 13. Pls do sum

====================================================================================================
ROW: 122
Conversation ID: 891167
Brand: XboxSupport
Size: 15 tweets
Customer turns: 7
Support turns: 8
Duration: 1830.9166666666667 minutes
----------------------------------------------------------------------------------------------------
[SUPPORT] Have Call of Duty: WWII pre-ordered? Make sure your payment info is accurate here: https://t.co/mSIj23eFFF
[CUSTOMER] @XboxSupport 😝👎 New Dashboard sucks! @115786  @XboxSupport
[SUPPORT] @331599 We'd be happy to help with any questions you have in regards to the latest update. Just let us know!  ^JA
[CUSTOMER] @XboxSupport How about taking it off from my console? 🤔😂😂 I like it better the way it was!! 😩🙄
[SUPPORT] @331599 We're sorry to hear about the frustration! We'd recommend leaving feedback here: https://t.co/Ub2WjDyEcS  ^JA
[CUSTOMER] @XboxSupport Leave a feedback? 🙄 Wooo that’s gonna make it so much better! 😲 Now pass me the Malibu and carry on people!! 🥃😂😂😂
[CUSTOMER] @XboxSupport Can you guys help me out I can’t get custom gamer pics but I have an adult account https://t.co/wyg9TBY4IS
[SUPPORT] @344600 Hi there, you'll see this message when trying to set a customer gamerpic if your account is  1 ^ZM
[SUPPORT] @344600 not an adult account and instead meets the definition of a child/teen account here: https://t.co/YhTUV9JZgK .  2 ^ZM
[CUSTOMER] @XboxSupport My accounts birthday is April 1st 1999 though shouldn’t it have switched by now? I live in the United States
[SUPPORT] @344600 Can you let us know your gamertag via direct message so we can look into this further?  ^BL
 https://t.co/3ZhVDWKaYU
[CUSTOMER] @XboxSupport Xbox my brother sent a message calling someone a tryhard and we got this message. Is this a warning or does it give us a punishment. https://t.co/HgzNrtIUMy
[SUPPORT] @348039 Heya! To view enforcement actions you can go here: https://t.co/JXq4oCmI9s and if eligible you can submit a case review.
 ^RR
[CUSTOMER] @XboxSupport Yo wtf why do my games crash all the fucking time fix this shit or om switching to ps4
[SUPPORT] @351950 Hi there! Let's check out the guide here: https://t.co/YX3UgNYfB6 to get this sorted out.  ^BL

====================================================================================================
ROW: 123
Conversation ID: 953618
Brand: XboxSupport
Size: 11 tweets
Customer turns: 8
Support turns: 3
Duration: 434.8833333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport why can't I use my ms points to by 360 games for my Xbox one
[CUSTOMER] @346267 What points are you referring to?  For 360 purchases, you need a valid payment method on your account, even if free. #XboxHelp
[CUSTOMER] @213651 Using prepaid cards aka Microsoft points. Do you not own a Xbox?
[CUSTOMER] @346267 Just want to make sure we're on the same page. Microsoft Points were retired in 2012. Pre-paid cards are what replaced them.
[CUSTOMER] @346267 You can always let them know you would prefer not to require a valid payment payment method for purchases. https://t.co/jxMz0ob8xe
[CUSTOMER] @213651 I guess they're not called that anymore but what trying to say is I have ten dollars on my account and I want to by 360 dlc on my Xbox 1.
[SUPPORT] @346267 Hi there, to purchase Xbox 360 content with account balance, you'll need to make the transaction on an Xbox 360 console. ^ZM
[CUSTOMER] @XboxSupport Why is that, that's incredibly inefficient.
[CUSTOMER] @XboxSupport Nor do I even have a Xbox 360 anymore because it is 20 17 going on 18 and why would I have a dead console.
[SUPPORT] @346267 You can see that info here: https://t.co/GyGkgoBKA5 under "I want to use my Microsoft account balance to pay for  1 ^ZM
[SUPPORT] @346267 something, but I don't see it listed as a payment option." Otherwise, you'll need to use a credit card.  2 ^ZM

====================================================================================================
ROW: 124
Conversation ID: 1240782
Brand: XboxSupport
Size: 9 tweets
Customer turns: 8
Support turns: 1
Duration: 127.35 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport https://t.co/SqKvxKCJ3E    broken again
[CUSTOMER] @XboxSupport 10/25/2017, 3:40:27 PM   tell them tea break is over
[SUPPORT] @411026 Hi there! Are you having issues connecting to Xbox Live? Can you DM us your Gamertag if so? ^JL
[CUSTOMER] @XboxSupport no
[CUSTOMER] @XboxSupport how would that help?
[CUSTOMER] @XboxSupport what would help is if they fixed what is broken since 4pm this afternoon as I said b4   their tea break is over tell em 2  get back to work
[CUSTOMER] @XboxSupport oh I see they've now fixed it so I can be safe in the knowledge that my 25 digit code won't vanish into the depths of m$ pockets
[CUSTOMER] @XboxSupport and will actually redeem and I'll be able to use my purchases. It's about time  downtime was added back to accounts
[CUSTOMER] @XboxSupport all is good I'll moan at you again when it's broken again

====================================================================================================
ROW: 125
Conversation ID: 1613716
Brand: XboxSupport
Size: 9 tweets
Customer turns: 5
Support turns: 4
Duration: 139.63333333333333 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport I just sent u a dm with a message on it,it was too long for me to pop in a tweet so I dm it u,please could u check it out?
[SUPPORT] @495044 Hi there, you'll want to ensure you're following the steps here: https://t.co/s9FfQ6hpAz to change your  1 ^ZM
[SUPPORT] @495044 Microsoft account email address as they may help with what you're experiencing there. :)  2 ^ZM
[CUSTOMER] @XboxSupport if i was to remove the original email inked with the account tho would it affect my xbox live signing in or would it change the the new
[CUSTOMER] @XboxSupport email because at the minute my xbox account still has the old email come up when i sign in,not the new email that is now my primary alias?
[SUPPORT] @495044 It's stating that you wouldn't be able to use it to sign in. You would have to use the other Alias instead. ^CO
[CUSTOMER] @XboxSupport I’m confused,it doesn’t exactly make it that clear if I’m honest😂,what does this mean then? Does it mean that I would use the original email
[CUSTOMER] @XboxSupport To sign in on my Xbox or would it be the new email I’d just created and made my primary alias?
[SUPPORT] @495044 It's just reminding you to no longer use the original e-mail for login and you may need to log back into consoles. ^CO

====================================================================================================
ROW: 126
Conversation ID: 2021820
Brand: XboxSupport
Size: 12 tweets
Customer turns: 7
Support turns: 5
Duration: 209.41666666666663 minutes
----------------------------------------------------------------------------------------------------
[CUSTOMER] @XboxSupport i can sign into my account can you please help
[SUPPORT] @597950 Hey, can you show us the message that you are seeing that is preventing you from signing in? ^RM
[CUSTOMER] @XboxSupport Sure
[CUSTOMER] @XboxSupport  https://t.co/CF1g3DaBXR
[SUPPORT] @597950 Okay, and what happens when you go to https://t.co/hLdh6O4RFD ? ^RM
[CUSTOMER] @XboxSupport Says sign in with my account but i have tried too many times but i have got the email about what they have said the first time i tried
[SUPPORT] @597950 with more assistance in accessing your account. You can reach them here https://t.co/sMM0hn9ycL.  2 ^RM
[SUPPORT] @597950 Okay, you can try reaching out to our chat support team to provide you  1 ^RM
[CUSTOMER] @XboxSupport I will try tomorrow but thank you for the advice do you want to see what the email says
[SUPPORT] @597950 yes, you are welcome to send us that. We recommend direct messaging the email. ^RM
[CUSTOMER] @XboxSupport Okay i will do that now
[CUSTOMER] @XboxSupport I have just sent it

====================================================================================================
ROW: 127
Conversation ID: 2868617
Brand: XboxSupport
Size: 16 tweets
Customer turns: 9
Support turns: 7
Duration: 991.9 minutes
----------------------------------------------------------------------------------------------------
[SUPPORT] Just picked up a new Xbox One or Xbox One S console? This community video will help you get it set up: https://t.co/3GfqeK5lTk
[CUSTOMER] @XboxSupport What would be dope is a rereleased xbox one 1tb console no power brick native 1080p visuals and hdr support. I kinda liked the original look despite its size
[SUPPORT] @308960 If you have any ideas or suggestions, we have a feedback page here: https://t.co/xzPtJXQjgy for just that.  ^BL
[CUSTOMER] @XboxSupport Could you answer my dm’s
[SUPPORT] @587753 Hi there! The game is not currently available for pre-order digitally. You can pre-order it here: https://t.co/89R0hpNYj0 through  1 ^BL
[SUPPORT] @587753 the Microsoft Store, but this would be a code to redeem upon the release of the game.  2 ^BL
[CUSTOMER] @XboxSupport Can I just buy it digitally when it comes out on my Xbox?
[CUSTOMER] @XboxSupport played on the scorpion 11 days after the started strongly noise, sent on repair, exchange, forward ... very it is not nice: per
[CUSTOMER] @XboxSupport I just became an ambassador... what do I do now? How do I link my twitter account?
[SUPPORT] @798362 Hi there! We're not quite sure we understand that. Would you mind clarifying?  ^JA
[SUPPORT] @798501 Hey there! Be sure to check out the Ambassador site here: https://t.co/j5gM4iKU39 Just sign in and get started. ^BL
[CUSTOMER] @XboxSupport acquired Xbox one x played on it 11 days, then started strongly noise, sent on repair, exchange,
[CUSTOMER] @XboxSupport very saddened this, forward already 8ой day, I hope soon they new my tag MaCTEP XyAHA from Russia 😢
[CUSTOMER] @XboxSupport I recently bought an xbox one s and I bought xbox live for $1 on the store for a month, but it doesn't let me play online and tells me to buy live even though i already have
[CUSTOMER] @XboxSupport Xbox live gold*
[SUPPORT] @803209 Hi there! We'd be happy to help with this. Could you follow us back &amp; DM your GamerTag when you get a chance?  ^TJ

In [87]:
# Save final batch annotations

batch_7_labels = {
    120: ("DIAGNOSTIC", "Support is collecting Gamertag, missing achievements, and troubleshooting history; no resolution yet."),
    121: ("UNRESOLVED", "Xbox says the issue is being investigated, but the customer continues reporting that it is not fixed."),
    122: ("ACTIONABLE_GUIDANCE", "Across the support interactions, concrete guidance is provided: feedback route, account explanation, enforcement review, and a troubleshooting guide."),
    123: ("ACTIONABLE_GUIDANCE", "Support directly explains the purchasing requirement and provides the relevant information/link."),
    124: ("CONFIRMED_OUTCOME", "The customer explicitly says the issue has been fixed and that everything is good."),
    125: ("ACTIONABLE_GUIDANCE", "Support gives concrete instructions for changing the Microsoft account email/alias and explains the login implication."),
    126: ("ACTIONABLE_GUIDANCE", "Support gives a concrete next step through chat support and direct messaging, including what information to provide."),
    127: ("DIAGNOSTIC", "Multiple unrelated issues appear; support requests clarification and account information, with no demonstrated resolution."),
}

for row_idx, (label, note) in batch_7_labels.items():
    resolution_screening_annotations.loc[row_idx, "resolution_label"] = label
    resolution_screening_annotations.loc[row_idx, "annotation_notes"] = note

resolution_screening_annotations.to_csv(
    annotation_path,
    index=False,
    encoding="utf-8"
)

print("Final batch annotations saved.")
print("\nFinal batch counts:")
print(resolution_screening_annotations.iloc[120:128]["resolution_label"].value_counts())

Final batch annotations saved.

Final batch counts:
resolution_label
ACTIONABLE_GUIDANCE    4
DIAGNOSTIC             2
UNRESOLVED             1
CONFIRMED_OUTCOME      1
Name: count, dtype: int64

In [88]:
print("\nTotal annotation counts:")
print(resolution_screening_annotations["resolution_label"].value_counts())

print("\nTotal rows:", len(resolution_screening_annotations))
print("Annotated rows:", resolution_screening_annotations["resolution_label"].notna().sum())
print("Remaining unannotated:", resolution_screening_annotations["resolution_label"].isna().sum())

Total annotation counts:
resolution_label
DIAGNOSTIC             35
ACTIONABLE_GUIDANCE    29
CASE_ACTION            21
ROUTING_ONLY           19
UNRESOLVED             11
CONFIRMED_OUTCOME       7
NON_SUPPORT             5
AMBIGUOUS               1
Name: count, dtype: int64

Total rows: 128
Annotated rows: 128
Remaining unannotated: 0

useful evidence that “support response exists” ≠ “issue was resolved.”

In [89]:
# Final verification of resolution screening annotations

import pandas as pd

# Reload from disk to verify that the saved artifact is correct
resolution_screening_annotations = pd.read_csv(
    annotation_path
)

print("File:", annotation_path)
print("Rows:", len(resolution_screening_annotations))
print("Columns:", resolution_screening_annotations.columns.tolist())

print("\nMissing resolution labels:")
print(
    resolution_screening_annotations["resolution_label"]
    .isna()
    .sum()
)

print("\nOverall resolution-label distribution:")
label_counts = (
    resolution_screening_annotations["resolution_label"]
    .value_counts()
)

label_summary = pd.DataFrame({
    "count": label_counts,
    "percentage": (label_counts / len(resolution_screening_annotations) * 100).round(2)
})

print(label_summary)

print("\nBrand × resolution label:")
brand_resolution = pd.crosstab(
    resolution_screening_annotations["support_account"],
    resolution_screening_annotations["resolution_label"]
)

print(brand_resolution)

print("\nBrand totals:")
print(
    resolution_screening_annotations["support_account"]
    .value_counts()
)

print("\nAnnotation verification complete.")

File: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\resolution_screening_annotations.csv
Rows: 128
Columns: ['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

Missing resolution labels:
0

Overall resolution-label distribution:
                     count  percentage
resolution_label
DIAGNOSTIC              35       27.34
ACTIONABLE_GUIDANCE     29       22.66
CASE_ACTION             21       16.41
ROUTING_ONLY            19       14.84
UNRESOLVED              11        8.59
CONFIRMED_OUTCOME        7        5.47
NON_SUPPORT              5        3.91
AMBIGUOUS                1        0.78

Brand × resolution label:
resolution_label  ACTIONABLE_GUIDANCE  AMBIGUOUS  CASE_ACTION  \
support_account
AmazonHelp                          5          1            7
AppleSupport                        9          0            0
Tesco                               5          0           14
XboxSupport                        10          0            0

resolution_label  CONFIRMED_OUTCOME  DIAGNOSTIC  NON_SUPPORT  ROUTING_ONLY  \
support_account
AmazonHelp                        2           6            2             7
AppleSupport                      3           7            0            11
Tesco                             1           5            3             1
XboxSupport                       1          17            0             0

resolution_label  UNRESOLVED
support_account
AmazonHelp                 2
AppleSupport               2
Tesco                      3
XboxSupport                4

Brand totals:
support_account
AmazonHelp      32
AppleSupport    32
Tesco           32
XboxSupport     32
Name: count, dtype: int64

Annotation verification complete.

AMAZONHELP is best overall fit for the assignment because it gives us the strongest combination of:

- Very high data volume — 82K conversations
- Deep conversations — highest mean conversation size among the four
- Strong customer back-and-forth
- Meaningful case-action examples
- Actionable guidance + confirmed outcomes
- Routing and unresolved cases, which are valuable for building and evaluating escalation
- Enough breadth for a useful intent taxonomy
- Enough data to support retrieval and train/test splits without running out of examples

Selected brand: AmazonHelp

AmazonHelp was selected using a data-driven comparison of conversation volume, conversation depth, multi-turn interaction, resolution evidence, and escalation opportunities. It had the largest candidate conversation pool (82,246), the highest mean conversation size (4.52 tweets), and strong evidence of both substantive support actions and unresolved/routing cases. Tesco showed stronger case-action density in the manual screening sample, but its substantially smaller conversation pool made AmazonHelp the better overall choice for building and evaluating the complete agent.

Build the AmazonHelp conversation dataset

In [90]:
amazon_conversations = resolution_episodes[
    resolution_episodes["support_account"] == "AmazonHelp"
].copy()

print("AmazonHelp conversations:", len(amazon_conversations))
print(
    "Columns:",
    amazon_conversations.columns.tolist()
)

print("\nConversation size:")
print(
    amazon_conversations["conversation_size"]
    .describe()
)

print("\nCustomer turns:")
print(
    amazon_conversations["customer_turns"]
    .describe()
)

print("\nSupport turns:")
print(
    amazon_conversations["support_turns"]
    .describe()
)

print("\nSize buckets:")
print(
    amazon_conversations["size_bucket"]
    .value_counts()
)

print("\nResolution screening examples for AmazonHelp:")
print(
    resolution_screening_annotations[
        resolution_screening_annotations["support_account"] == "AmazonHelp"
    ][
        ["conversation_id", "conversation_size",
         "customer_turns", "support_turns",
         "resolution_label"]
    ].to_string(index=False)
)

AmazonHelp conversations: 82246
Columns: ['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

Conversation size:
count    82246.000000
mean         4.515928
std          5.107119
min          2.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
Name: conversation_size, dtype: float64

Customer turns:
count    82246.000000
mean         2.458186
std          3.280729
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max        447.000000
Name: customer_turns, dtype: float64

Support turns:
count    82246.000000
mean         2.057741
std          2.139243
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max        162.000000
Name: support_turns, dtype: float64

Size buckets:
size_bucket
2_tweets         31296
3_to_4_tweets    25490
5_to_8_tweets    17850
9_plus_tweets     7610
Name: count, dtype: int64

Resolution screening examples for AmazonHelp:
 conversation_id  conversation_size  customer_turns  support_turns    resolution_label
          227908                  2               1              1        ROUTING_ONLY
          236650                  2               1              1          DIAGNOSTIC
          377207                  2               1              1         CASE_ACTION
          474254                  2               1              1        ROUTING_ONLY
          583523                  2               1              1 ACTIONABLE_GUIDANCE
         1678016                  2               1              1        ROUTING_ONLY
         2276470                  2               1              1        ROUTING_ONLY
         2598545                  2               1              1         NON_SUPPORT
          210399                  4               2              2        ROUTING_ONLY
          268721                  3               2              1   CONFIRMED_OUTCOME
          366006                  3               1              2        ROUTING_ONLY
          709030                  4               2              2 ACTIONABLE_GUIDANCE
          842214                  4               2              2        ROUTING_ONLY
         2159283                  3               1              2          DIAGNOSTIC
         2684289                  3               2              1           AMBIGUOUS
         2802385                  3               2              1          DIAGNOSTIC
          183065                  5               3              2   CONFIRMED_OUTCOME
          285629                  6               4              2          UNRESOLVED
          386800                  6               3              3          DIAGNOSTIC
          685687                  5               3              2         CASE_ACTION
          930342                  6               3              3         CASE_ACTION
         1338751                  6               3              3         CASE_ACTION
         2826557                  5               2              3         CASE_ACTION
         2977345                  7               5              2          DIAGNOSTIC
           34503                 10               5              5         NON_SUPPORT
          423802                 11               6              5 ACTIONABLE_GUIDANCE
          432288                 10               7              3         CASE_ACTION
          538510                 10               5              5          DIAGNOSTIC
          719893                 10               5              5          UNRESOLVED
         1666514                 12               6              6 ACTIONABLE_GUIDANCE
         1714337                 18               9              9         CASE_ACTION
         1719165                 12               6              6 ACTIONABLE_GUIDANCE

- 31,296 short 2-tweet conversations
- 25,490 with 3–4 tweets
- 17,850 with 5–8 tweets
- 7,610 with 9+ tweets
- Mean conversation size: 4.52 tweets
- Median: 3 tweets
- Mean customer turns: 2.46
- Mean support turns: 2.06

In [91]:
# Inspect AmazonHelp customer queries for intent discovery

import pandas as pd

# Balanced sample across conversation-size buckets
bucket_samples = []

for bucket in [
    "2_tweets",
    "3_to_4_tweets",
    "5_to_8_tweets",
    "9_plus_tweets"
]:
    subset = amazon_conversations[
        amazon_conversations["size_bucket"] == bucket
    ].copy()

    sample_n = min(250, len(subset))

    bucket_samples.append(
        subset.sample(
            n=sample_n,
            random_state=42
        )
    )

intent_discovery_sample = pd.concat(
    bucket_samples,
    ignore_index=True
)

print("Total sampled conversations:", len(intent_discovery_sample))
print(
    intent_discovery_sample["size_bucket"]
    .value_counts()
)

print("\n" + "=" * 100)
print("CUSTOMER OPENING MESSAGES")
print("=" * 100)

for i, (_, row) in enumerate(
    intent_discovery_sample.iterrows()
):
    print(
        f"\n[{i}] "
        f"bucket={row['size_bucket']} | "
        f"conversation_size={row['conversation_size']}"
    )
    print(row["first_customer_message"])

Total sampled conversations: 1000
size_bucket
2_tweets         250
3_to_4_tweets    250
5_to_8_tweets    250
9_plus_tweets    250
Name: count, dtype: int64

====================================================================================================
CUSTOMER OPENING MESSAGES
====================================================================================================

[0] bucket=2_tweets | conversation_size=2
Amazon Prime Musicで音楽聴きながら作業して捗る

[1] bucket=2_tweets | conversation_size=2
@115830 Hi there, having a bit of problem. I received an email saying that my delivery has been delivered, but because it was sent to my work address and after office hours.. not too sure where the delivery man has left it? it's no where to be seen.

[2] bucket=2_tweets | conversation_size=2
@115850 just gt a call frm delivery person regarding where my address is. Yes at 7:58 in the mrning. What a great way to wakeup! #scarcasm

[3] bucket=2_tweets | conversation_size=2
Vous êtes sérieux @120533 de livrer ça dans cet état ?? https://t.co/4PLAp7wGD9

[4] bucket=2_tweets | conversation_size=2
@115830 hi, is it possible to redirect an order to an amazon locker after it's been despatched? Thanks!

[5] bucket=2_tweets | conversation_size=2
Dear @115821, time to up your shipping game.  I’m good paying for Prime, but paying for 2 day shipping, then getting something in 5 days (or more) is not cool.  Go back to using only @115817.

[6] bucket=2_tweets | conversation_size=2
@115850 My issue is contained in the below pic. Please look into it and reply. https://t.co/j9pvkXhaa5

[7] bucket=2_tweets | conversation_size=2
Le plus marrant c'est que j'ai vu le livreur avec le colis en bas et j'ai demandé, il m'a dit "Non le colis est pas pour vous".
@120533 https://t.co/F5H41AXRll

[8] bucket=2_tweets | conversation_size=2
@AmazonHelp has superior customer service! I just had a fantastic customer experience with a rep! I will be a loyal customer for life!

[9] bucket=2_tweets | conversation_size=2
Amazon Music Unlimited に登録してみた。Amazon Echoで登録すると、月額380円と格安だったわ。

[10] bucket=2_tweets | conversation_size=2
@115821 @AmazonHelp pre-ordered this book and it finally came in today! but with damages :/ https://t.co/BdpvGIQYPj

[11] bucket=2_tweets | conversation_size=2
@115850 Most pathetic service,one plus 5t flash sale,prime customer,one day delivery,the product says dispatched from 2days. @132994  This is how you create demand by Monopoly which leads only to customer dissatisfaction??

[12] bucket=2_tweets | conversation_size=2
@116316 ich liebe Dich. https://t.co/hp5GRKGx9I

[13] bucket=2_tweets | conversation_size=2
Comprei uns livros quinta de noite e já chegou hoje, eu nasci pra te amar @117086

[14] bucket=2_tweets | conversation_size=2
@115850 discount coupon on Kindle received by email from amazon is showing as expired, though the coupon is valid till march 2018 plz help

[15] bucket=2_tweets | conversation_size=2
When your customer satisfaction goes from worse to hopeless avoiding customers is the only thing you can do @115850 @115821 https://t.co/s82Z34yAVd

[16] bucket=2_tweets | conversation_size=2
@115850  I booked 2 movie tickets from BookMyShow with the help of @115823. So it was mentioned over there I will get cashback of ₹100. Can you please tell me by what time I will get it back ?
Amazonrder ID: #P04-1700305-5777789.

[17] bucket=2_tweets | conversation_size=2
o site da @117086 não está abrindo para mim. para vocês está?

[18] bucket=2_tweets | conversation_size=2
@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK

[19] bucket=2_tweets | conversation_size=2
@115850 got a message that my order was shipped yesterday. This morning I get a refund of the purchase amount on my card. Confused!!

[20] bucket=2_tweets | conversation_size=2
Hey @120533 , c'est normal que mes commandes amazon prime expédiées via @77516, n'arrivent jamais ?

[21] bucket=2_tweets | conversation_size=2
Amazonプライムフォトってrawデータも無制限でいけるのね。

[22] bucket=2_tweets | conversation_size=2
BD持ってるけどアマゾンプライムでアンツィオ戦見てる

[23] bucket=2_tweets | conversation_size=2
Topgearのほとんどが見れるだけで、Amazonプライム会員になる価値はあるな。

[24] bucket=2_tweets | conversation_size=2
Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU

[25] bucket=2_tweets | conversation_size=2
Hey @117795 you've delayed a delivery once again. One more time and I'll be exploring options like @2300

[26] bucket=2_tweets | conversation_size=2
なんでいつも発売日に届かないの
Amazon無能すぎ

[27] bucket=2_tweets | conversation_size=2
@115821 .. doesn’t seem like the best packaging?  #decreasingQuality https://t.co/h8CDYrLmy6

[28] bucket=2_tweets | conversation_size=2
I think I fixed the Amazon assistant problem. Thanks to @442117 and @AmazonHelp

[29] bucket=2_tweets | conversation_size=2
Tried to post a review about the condition a package I received from @115821 and was rejected. While the shipping box was intact, the product had clearly been opened. Very disappointed as this was to be a gift. https://t.co/Ty1gXOpykA

[30] bucket=2_tweets | conversation_size=2
@115851 @115850 @115821 @AmazonHelp Do anybody in your team care for a 4 year old customer, who has paid for an undelivered product pending since last 1 month? https://t.co/vbHp7yRM9L

[31] bucket=2_tweets | conversation_size=2
@116329 @1110 is services available on @115850 ehco dot??

[32] bucket=2_tweets | conversation_size=2
@115850 @AmazonHelp If re order 4087261960-8669144,d bank debits accont, BT Amazon says "payment declined' shd Amzn pay Rs5000 as damages?

[33] bucket=2_tweets | conversation_size=2
Dear @115828 @115821  My "allegedly" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI

[34] bucket=2_tweets | conversation_size=2
@AmazonHelp No courier services to this place really? What's the problem? https://t.co/w0qZj2ooVY

[35] bucket=2_tweets | conversation_size=2
行方不明だった荷物今さら帰って来たらしい～～～～もうあまぞんが同じの送ってきてくれたっての(´-ι_-｀)ていうか何がちゃんとポストに投函したので後は知りません！！だよしてなかったじゃん！？

[36] bucket=2_tweets | conversation_size=2
@115821 do you guys have 10$ gift cards that are in stores? I keep seeing 20$-100$

[37] bucket=2_tweets | conversation_size=2
J'ai un colis amazon pour des voisins et ils ne viennent pas le chercher... le livreur a mis mon nom pour la réception du colis. Ils pensent peut-être que je vais venir leur apporter/livrer.

[38] bucket=2_tweets | conversation_size=2
@115821, enough with the recommendations. Just because I read one book on linguistics doesn't mean I want to read 12 books on linguistics.

[39] bucket=2_tweets | conversation_size=2
@AmazonHelp how can i cancel an order while my account is blocked?

[40] bucket=2_tweets | conversation_size=2
@119625 Please show Stranger Things as well

[41] bucket=2_tweets | conversation_size=2
Ordered the Drinko game from @115821 and was sent a Pokemon Monopoly game instead. I feel screwed today

[42] bucket=2_tweets | conversation_size=2
Don't know why I pay for @115830 prime waited all day yesterday for a parcel to now be told another 4 day same for the one I should be getting today 4 more days for that too. Not the first time it's happened shocking service. most people use next day for a reason.

[43] bucket=2_tweets | conversation_size=2
Well hidden @115830 I bet you were amazing at hide and seek! https://t.co/lIG8XORahi

[44] bucket=2_tweets | conversation_size=2
@AmazonHelp hey, what time do you release the outlander episodes(UK TIME)

[45] bucket=2_tweets | conversation_size=2
@116313 アマゾンのサイトのフォントサイズですが、大きくなりましたか？それとも、当PC（ちなみにChrome使用）だけでしょうか？

[46] bucket=2_tweets | conversation_size=2
Vou conferir as ofertas da @117086, alguém me segura

[47] bucket=2_tweets | conversation_size=2
@AmazonHelp my package delivery has been delayed TWICE &amp; I really need it delivered to the person ASAP. What is the problem?!?

[48] bucket=2_tweets | conversation_size=2
@115833 @5503 Can you do echo to echo calls internationally? In markets where echo calling is enabled, after all it's over the internet right, so it should work fine.

[49] bucket=2_tweets | conversation_size=2
@115851 I am having a major misdelivery problem. The last 4 deliveries have been misdelivered to a neighbor. Customer Service has not solved the problem after 3 calls. Drivers need to be instructed. I am getting tired of the misdeliveries!

[50] bucket=2_tweets | conversation_size=2
@117093  Hey, if your guys are running late for a scheduled 2 hr attended delivery window,  it'd be really nice to get a heads up phone call. Thx

[51] bucket=2_tweets | conversation_size=2
amazonの定期お得便楽だなぁ。おむつやミルクの在庫に焦らなくなったし、アカチャンホンポに定期的に買い出し行ってたけど、どうしても新しい便利グッズ見つけたりしちゃって毎度余計なもの買ってたから良かったwそもそも安いし。ちなみに我が家はミルク・おむつ・消毒液を買ってる https://t.co/CYk0cSdKGa

[52] bucket=2_tweets | conversation_size=2
@115850 customer service didn't receive my call, I tried more than 3 to 4 times.

[53] bucket=2_tweets | conversation_size=2
Hey @115821 why's my wife still getting someone else's emails from you?

[54] bucket=2_tweets | conversation_size=2
@AmazonHelp @124285  Bis wie lange ist heute denn noch Zustellung? 🤔 https://t.co/0UWqURCmsJ

[55] bucket=2_tweets | conversation_size=2
アマゾンプライムでアニメを見る日々が始まる……
ネットで探す必要がなくなった…
喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0

[56] bucket=2_tweets | conversation_size=2
Anyone having trouble w/ @116618 I have sound but no pics. All other streaming apps are fine on my fire stick

[57] bucket=2_tweets | conversation_size=2
@AmazonHelp i’ve done tht...bt nothing happens wht now??

[58] bucket=2_tweets | conversation_size=2
@115821 @AmazonHelp has always provided me great service even if they mess up ✊🏽

[59] bucket=2_tweets | conversation_size=2
My order no.407-3456571-8547565
 It’s been a month,din't receive my refund yet,truely great services by @115850

[60] bucket=2_tweets | conversation_size=2
昨日の夜Amazonでポチったらもう届いた😃 https://t.co/kfY4aEz1go

[61] bucket=2_tweets | conversation_size=2
@AmazonHelp Would like to make a complaint regarding a delivery due today that suddenly is showing as being delivered on Monday with no update or explanation... Now going to cost me customers because its not going to arrive in time.

[62] bucket=2_tweets | conversation_size=2
Was denn nun @116316 ? Wird heute versendet? Zustellung heute?
Lohnt sich #AmazonPrime noch, wenn man trotzdem warten muss? :( #Amazon https://t.co/bs3liYfX8D

[63] bucket=2_tweets | conversation_size=2
I need some help with internet marketing. I have a YouTube channel I can market prouducts for Amazon and other thi… https://t.co/wvXawSt9Od

[64] bucket=2_tweets | conversation_size=2
@115821 is the top email a scam attempt? It doesn’t say https://t.co/tby9TBRtP5 like all the other amazon emails I’ve gotten in the past. https://t.co/WBOxwz9vFv

[65] bucket=2_tweets | conversation_size=2
AMAZON WHY DO YOU LEAVE MY PACKAGES ON MY FRONT STEPS I LIVE IN THE HOOD PEOPLE WILL STEAL MY SHIT

[66] bucket=2_tweets | conversation_size=2
@AmazonHelp do you take Bitcoin?

[67] bucket=2_tweets | conversation_size=2
@115850 I have received package delivered notification but yet no package is received by me. Tracking # 216265638418

[68] bucket=2_tweets | conversation_size=2
@115850  Still didn't get my product😡😡😡 Too much disappointed https://t.co/jxFqdBYpne

[69] bucket=2_tweets | conversation_size=2
動きたく無さ過ぎてまたAmazonプライムナウ頼んでしまった....

本当Amazonさんに生活支えてもらってる😇😇 https://t.co/7iX3ScscBc

[70] bucket=2_tweets | conversation_size=2
I wish @115821 would stop sending out items that can be crushed in jiffy mailers. Saves money and space in trucks? that's tight but it also crushes things i bought. So if you could stop... https://t.co/PC5g01P0UJ

[71] bucket=2_tweets | conversation_size=2
@137341 Any idea how I can fix my Kindle Paperwhite, some parts of the screen has become unresponsive. I tried doing a factory reset.

[72] bucket=2_tweets | conversation_size=2
@AmazonHelp My Echo Dot believes it's still in USA. I can't add my Indian location! Any suggestions?

[73] bucket=2_tweets | conversation_size=2
@AmazonHelp Funny but I can order it now and it will arrive on Sunday yet mine which I bought on Tuesday gone won’t arrive till Monday https://t.co/LFwWXZ4j6v

[74] bucket=2_tweets | conversation_size=2
@120533 Bonjour , je suis un jeune  qui vient de perdre 3 doigts dont 1 irrécupérables. Pour me faire passer le temps auriez-vous la gentillesse de m’offrir un casque beats studio 3 wireless. Merci beaucoup

[75] bucket=2_tweets | conversation_size=2
@115850 Amazon India, can you kindly explain and justify your ridiculous and unsustainable packaging practices? That's all that came in the big carton. https://t.co/IjzDu30iFJ

[76] bucket=2_tweets | conversation_size=2
EVERY time @115830 uses @22805 to ship stuff this is how it arrives to me https://t.co/MY0agWkncK

[77] bucket=2_tweets | conversation_size=2
Neue Funktion? Amazon akzeptiert jetzt iDEAL!

@111541 @AmazonHelp @219464 @63924 @805122 https://t.co/fdYXpvHlz7

[78] bucket=2_tweets | conversation_size=2
@AmazonHelp how can I file a complaint?

[79] bucket=2_tweets | conversation_size=2
@117093 @115821 #FAIL Received wrong order, tried to do the right thing but your customer service team, Yash, specifically failed. https://t.co/oFhhy99Yob

[80] bucket=2_tweets | conversation_size=2
Mejor mande todo por DHL o Fedex, inutiles @115821

[81] bucket=2_tweets | conversation_size=2
@121284 Need more comprehensive commands and command chaining. eg: Switch off Hall Lights in 10 minutes.

[82] bucket=2_tweets | conversation_size=2
@116875  ayudenme en mi comprar porfaaaaa no me desepsiones amazon

[83] bucket=2_tweets | conversation_size=2
Um @115821 it’s the 25th two shipping means the 28th at the latest and it’s telling me Nov 1st hello that’s after I need the item

[84] bucket=2_tweets | conversation_size=2
@115850 You seem to make it a habit of not delivering on time, then messaging to say delivery attempted, then calling on voice mail because you know delivery wasn't attempted. Maybe easier to deliver on time rather than go round in circles and lies #justsaying @AmazonHelp

[85] bucket=2_tweets | conversation_size=2
@AmazonHelp I don't think this is an appropriate place to leave my package. I live in a block of flats and this could have been stolen. https://t.co/huOodXzcd1

[86] bucket=2_tweets | conversation_size=2
Amazon Musicのストリーミング再生ができぬ……

[87] bucket=2_tweets | conversation_size=2
@119625 when are you adding suits season 7? @116618

[88] bucket=2_tweets | conversation_size=2
Hey @119625 any idea when Laakhon Main Ek will be available on Amazon Prime Video in Europe?

[89] bucket=2_tweets | conversation_size=2
@115850 @1141 @AmazonHelp Ty for listenin to my complaint.I got my bk tday in a nyc cardbd bx wid a sweet coupon bkmrk.Very happy!

[90] bucket=2_tweets | conversation_size=2
アマゾンミュージックはペルソナのサントラだけじゃなくてモンハンもゆうなまのサントラもあるぞ！ https://t.co/We4OL2Eibf

[91] bucket=2_tweets | conversation_size=2
https://t.co/r9nPYG9JXG have taken unauthorised money out of my bank account! I am not happy so onto bank tomorrow!I am furious as I owe them nothing,I want my money back immediately. 😡

[92] bucket=2_tweets | conversation_size=2
@115821 when the delivery driver throws your package on your yard https://t.co/cm6sPQoryN

[93] bucket=2_tweets | conversation_size=2
@115830 right so best thing to come home to a really wet package after paying for delivery. I wouldn't think throwing a package over the wall when it's raining is a good thing. Fab https://t.co/ozM950MuNj

[94] bucket=2_tweets | conversation_size=2
Amazonで適当に注文確定しようと連打してたらなんかプライム会員に登録された 詐欺だ

[95] bucket=2_tweets | conversation_size=2
I told my delivery guy to leave my box in the office. And instead it took it back cause I wasn't home💀 @115821

[96] bucket=2_tweets | conversation_size=2
@115850  fake product was delivered to me.when i went to the service centre they told me the product was duplicate. and gave me https://t.co/hTNSE64Toa 7532051814 for further details https://t.co/6o0paNakc5

[97] bucket=2_tweets | conversation_size=2
@115821 has been seriously dropping the ball lately with their “2-day shipping”... #LameAF

[98] bucket=2_tweets | conversation_size=2
Major @115821 fail. How in the world can you mistake a 10 ft cable for 6 stainless steel grapefruit spoons! &amp;I can't return them?! #Amazon https://t.co/M1HlLOOElb

[99] bucket=2_tweets | conversation_size=2
@115821 why do i have to wait a month(s) for a screen protector for my kids new #firehd8?

[100] bucket=2_tweets | conversation_size=2
(E comunque, rassegnamoci, @120540 ha tutto. Io credo di amarlo )

[101] bucket=2_tweets | conversation_size=2
amazonプライム映画すごい見られるやんーー入ってるのに今まで使ってなかった！！

[102] bucket=2_tweets | conversation_size=2
@115821 your 25 dollar gift card I bought scratched the whole PIN number to add money off https://t.co/jEyEAdzdyW

[103] bucket=2_tweets | conversation_size=2
Hi, I need some help with my account on amazon

[104] bucket=2_tweets | conversation_size=2
Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄

[105] bucket=2_tweets | conversation_size=2
@115850 no link for email or phone to Amazon customer service. Pathetic service even after prime membership.

[106] bucket=2_tweets | conversation_size=2
@115850
Can I get an email address, to inform you of a fraud from Amazon  India,selling a Fake product, &amp; not responding for the last 5  months.I do no wish to highlight here.This is a Criminal &amp; Consumer  Forum Case. __email__

[107] bucket=2_tweets | conversation_size=2
La lista de novelas gráficas de mi wishlist de @116928 es más grande que mi lista de fracasos personales. Así que IMAGÍNATE.

[108] bucket=2_tweets | conversation_size=2
@115821 please stop using @3375 they are horrible and constantly fail to deliver packages on time!!

[109] bucket=2_tweets | conversation_size=2
@117086 Oi, boa noite. Ontem eu comprei um livro e sem querer comprei de novo, mas não foi contabilizado, hoje paguei mais caro.

[110] bucket=2_tweets | conversation_size=2
¿Tanto embalaje es necesario? @116928 https://t.co/wfHjywF81G

[111] bucket=2_tweets | conversation_size=2
@115821 it was showing that the product will be deliverd to me in 2 days guaranteed.
Orderd it on sunday still waiting to get it (2/2)

[112] bucket=2_tweets | conversation_size=2
せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T

[113] bucket=2_tweets | conversation_size=2
@AmazonHelp someone recently changed my main email but not the password on my amazon, is there anyway I could get any of my audiobooks back?

[114] bucket=2_tweets | conversation_size=2
@AmazonHelp . IRe: Your Amazon.in Order  # 402-4987357-3643550 dear Amazon stop making fools .

[115] bucket=2_tweets | conversation_size=2
@115821 i feel like my intelligence is being insulted by your seller customer support.

[116] bucket=2_tweets | conversation_size=2
@AmazonHelp I've had this book delivered today and it's turned up like this. How do I sort a refund? https://t.co/RhWKO5LYhl

[117] bucket=2_tweets | conversation_size=2
I feel like I got played @115821 at least have some bubble wrap in there 😭😂 https://t.co/ZWxsno4mJM

[118] bucket=2_tweets | conversation_size=2
No se si te amo o te odio @116875, cada día compro algo 🤔

[119] bucket=2_tweets | conversation_size=2
I’m glad that no one walking by my house wanted an antenna. Great boxing job @115821 https://t.co/a9tHdNBlkH

[120] bucket=2_tweets | conversation_size=2
Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B

[121] bucket=2_tweets | conversation_size=2
What is up @115821? Your box game is OUT OF CONTROL for several months. Size 11 shoe for reference. ELEVEN! https://t.co/sqAtzT0yhO

[122] bucket=2_tweets | conversation_size=2

The sample has many delivery variants:

- late delivery
- Prime one-day/two-day failure
- "out for delivery" but not delivered
- false attempted delivery
- wrong address
- neighbor delivery
- delivery instructions ignored
- carrier problems
- package missing

splitting all of these into separate classes would create artificially fine-grained intents and make the golden set harder to label consistently.

Create the 150-example taxonomy audit

In [92]:
import pandas as pd
from pathlib import Path

# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------
PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# use the existing 1000 example intent discovery sample
audit_source = intent_discovery_sample.copy()

print("Source rows:", len(audit_source))
print(audit_source["size_bucket"].value_counts().sort_index())

Source rows: 1000
size_bucket
2_tweets         250
3_to_4_tweets    250
5_to_8_tweets    250
9_plus_tweets    250
Name: count, dtype: int64

In [93]:
# Create the audit sample
audit_parts = []

bucket_counts = {
    "2_tweets": 38,
    "3_to_4_tweets": 37,
    "5_to_8_tweets": 37,
    "9_plus_tweets": 38,
}

for bucket, n in bucket_counts.items():
    part = (
        audit_source[audit_source["size_bucket"] == bucket]
        .sample(n=n, random_state=42)
        .copy()
    )
    audit_parts.append(part)

taxonomy_audit = (
    pd.concat(audit_parts, ignore_index=True)
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

# Add blank annotation columns
taxonomy_audit["intent_label"] = ""
taxonomy_audit["annotation_notes"] = ""
taxonomy_audit["annotator"] = ""

# Save
audit_path = PROCESSED_DIR / "taxonomy_audit_150.csv"
taxonomy_audit.to_csv(audit_path, index=False)

print("Taxonomy audit created.")
print("Rows:", len(taxonomy_audit))
print("Saved to:", audit_path)

print("\nSize-bucket distribution:")
print(taxonomy_audit["size_bucket"].value_counts().sort_index())

Taxonomy audit created.
Rows: 150
Saved to: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\taxonomy_audit_150.csv

Size-bucket distribution:
size_bucket
2_tweets         38
3_to_4_tweets    37
5_to_8_tweets    37
9_plus_tweets    38
Name: count, dtype: int64

In [94]:
print(taxonomy_audit.columns.tolist())

['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'intent_label', 'annotation_notes', 'annotator']

In [95]:
print(taxonomy_audit.head(2).to_string())

                                                                                                                     first_customer_message                                           last_customer_message                                                                                                            first_support_message                                                                                                             last_support_message                                                                                                                                                                                                                                                                                                               conversation_text  customer_turns  support_turns  conversation_size                start_time                  end_time  duration_minutes support_account    size_bucket intent_label annotation_notes annotator
0  @AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP                                           @AmazonHelp Thank you    @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF    @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF  [CUSTOMER] @AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP\n[SUPPORT] @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF\n[CUSTOMER] @AmazonHelp Thank you               2              1                  3 2017-10-21 19:03:22+00:00 2017-10-21 19:31:10+00:00         27.800000      AmazonHelp  3_to_4_tweets
1                                                                            @120533 Intéressants vos emballages... https://t.co/kMqmBDEt52  @120533 Intéressants vos emballages... https://t.co/kMqmBDEt52  @733790 Navrée pour cela, je vous prie de nous laisser un commentaire sur l'emballage via ce lien: https://t.co/6m981cpbIF. ^MA  @733790 Navrée pour cela, je vous prie de nous laisser un commentaire sur l'emballage via ce lien: https://t.co/6m981cpbIF. ^MA                                                                                                            [CUSTOMER] @120533 Intéressants vos emballages... https://t.co/kMqmBDEt52\n[SUPPORT] @733790 Navrée pour cela, je vous prie de nous laisser un commentaire sur l'emballage via ce lien: https://t.co/6m981cpbIF. ^MA               1              1                  2 2017-10-30 19:28:53+00:00 2017-10-30 19:49:57+00:00         21.066667      AmazonHelp       2_tweets

In [96]:
# Show first 30 taxonomy-audit examples for manual annotation
batch_1 = taxonomy_audit.iloc[:30][
    [
        "first_customer_message",
        "last_customer_message",
        "conversation_text",
        "customer_turns",
        "support_turns",
        "conversation_size",
        "size_bucket",
        "intent_label",
        "annotation_notes",
    ]
].copy()

pd.set_option("display.max_colwidth", 500)

display(batch_1)

,first_customer_message,last_customer_message,conversation_text,customer_turns,support_turns,conversation_size,size_bucket,intent_label,annotation_notes
0,@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP,@AmazonHelp Thank you,[CUSTOMER] @AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP\n[SUPPORT] @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF\n[CUSTOMER] @AmazonHelp Thank you,2,1,3,3_to_4_tweets,,
1,@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52,@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52,"[CUSTOMER] @120533 Intéressants vos emballages... https://t.co/kMqmBDEt52\n[SUPPORT] @733790 Navrée pour cela, je vous prie de nous laisser un commentaire sur l'emballage via ce lien: https://t.co/6m981cpbIF. ^MA",1,1,2,2_tweets,,
2,"You guys should really Google the word ""Guaranteed"" before giving me an arrival date. Just terrible this year. #Amazon @115821 #late #guess?",@AmazonHelp Per Amazon arriving today. Per UPS arriving tomorrow with 1 of 6 guaranteed delivered today.,"[CUSTOMER] You guys should really Google the word ""Guaranteed"" before giving me an arrival date. Just terrible this year. #Amazon @115821 #late #guess?\n[SUPPORT] @314885 Oh no, Jason! Have we missed a delivery date on a current order? Please let us know! ^MW\n[CUSTOMER] @AmazonHelp Consistently. I would really prefer actual dates to “guaranteed” ones. No matter the cost.\n[SUPPORT] @314885 I understand your frustration. Are you noticing this trend with a certain carrier: https://t.co/q4L...",5,5,10,9_plus_tweets,,
3,I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850,"@AmazonHelp Yes, I got many emails regarding this issue and finally they want me to wait till tomorrow. Hope this will be resolved tomorrow.","[CUSTOMER] I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850\n[SUPPORT] @183115 Could you please confirm if you have received a corresponding email from our team by checking your message centre. 1/2 ^AH\n[SUPPORT] @183115 Click the below link to visit your message centre. https://t.co/DTSNmGldJf. 2/2 ^AH\n[CUSTOMER] @AmazonHelp Yes, I got many emails regarding this issue and finally they want me to wait ti...",2,3,5,5_to_8_tweets,,
4,"@115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG","@AmazonHelp You have sent an email that product was Delivered and in Application you have updated status that, it was handed directly to me and the delivery receipt was signed by me, which is completely false. This seems to be the signature forgery and fraud. @120781 @115850 https://t.co/LVYjdo0ky4","[CUSTOMER] @115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG\n[SUPPORT] @787339 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. 2/2^KK\n[SUPPORT] @787339 Sorry for the trouble. I wo...",2,3,5,5_to_8_tweets,,
5,"Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI","Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI","[CUSTOMER] Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI\n[SUPPORT] @587985 Oh no! I'm sorry the item isn't as expected. Have you requested a refund or replacement here: https://t.co/wYgi4H7sKm ^QJ",1,1,2,2_tweets,,
6,"Can’t believe @115830’s response to me asking why my Xbox One X hasn’t been despatched yet. “If you’re not happy with it, cancel”","@AmazonHelp It's still saying shipping today, arriving today. This was a waste of a day off work. A friend who ordered five days later has had theirs.","[CUSTOMER] Can’t believe @115830’s response to me asking why my Xbox One X hasn’t been despatched yet. “If you’re not happy with it, cancel”\n[SUPPORT] @662806 Apologies for the poor experience. This is not the service we expect. What's the latest tracking - https://t.co/Jr1kcqQUJY ^TP\n[CUSTOMER] @AmazonHelp It's still saying shipping today, arriving today. This was a waste of a day off work. A friend who ordered five days later has had theirs.",2,1,3,3_to_4_tweets,,
7,@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice,@AmazonHelp https://t.co/VtapWl2C1l The fact that there are videos of terrible AMZL_US deliveries sure says a lot. Where do you find these people?,"[CUSTOMER] @115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice\n[SUPPORT] @527064 I'm sorry that your having a frustrating experience. Without provided account information, can you give us more details?^AJ\n[CUSTOMER] @AmazonHelp My release date delivery of south park is apparently lost. No tracking update. Should be here already.\n[CUSTOMER] @AmazonHelp Carrier: AMZL US, Tracking #: TBA492774361000\n[SUPPORT] @5...",11,5,16,9_plus_tweets,,
8,@AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u,@AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u,[SUPPORT] @801372 Looks like you're facing trouble with the Pay balance on your account. Could you please elaborate on your concern so that we can help you accordingly? ^VN\n[CUSTOMER] @AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u\n[SUPPORT] @801372 I get you being upset. Kindly fill in your details here: https://t.co/beaaDm0muc we'd like to take a closer look at the issue. ^MN,1,2,3,3_to_4_tweets,,
9,An update : It’s still Monday. \n\n#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9,@794324 @794325 Amazon have fucked up big time with me over my order. Wont be getting it til Wednesday so youll be a day ahead of me. Never mind I'll pick up a copy at Waterstones tomorrow night maybe!!,[CUSTOMER] An update : It’s still Monday. \n\n#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9\n[CUSTOMER] @794324 I’m up for work at 5am. 😫😂\n[CUSTOMER] @794325 Aw crap!!! That’s just unacceptable sweetie! 😩😂\n[CUSTOMER] @794324 @794325 You both moght have your copy before I do. #countyourselflucky\n[CUSTOMER] @788400 @794325 I can’t stay up either but I will be downloading ASAP in the morning. 😇 Then nobody is allowed to talk to me until I’m finish...,6,1,7,5_to_8_tweets,,
10,@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.,@AmazonHelp Finally could do it through SMS alert link. But it's actually quite cumbersome looking for it.,[CUSTOMER] @AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.\n[SUPPORT] @206099 Sorry for the hassle. Please report this to our support team here: https://t.co/vlvfJr4nN9 and we'll check this. ^HN\n[CUSTOMER] @AmazonHelp I've done it two days back..\n[SUPPORT] @206099 What is the error you're seeing when you try to change the number? ^HD\n[CUSTOMER] @AmazonHelp Finally could do it through SMS alert link. But it's ...,3,3,6,5_to_8_tweets,,
11,Prime now turkey tracker. https://t.co/90UMXDP11e,Prime now turkey tracker. https://t.co/90UMXDP11e,[CUSTOMER] Prime now turkey tracker. https://t.co/90UMXDP11e\n[SUPPORT] @282022 Why did the turkey cross the road? To prove he wasn’t chicken! Have a great day 🦃🦃 ^BZ,1,1,2,2_tweets,,
12,@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK,@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK,"[CUSTOMER] @AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK\n[SUPPORT] @662616 I'm sorry about this, Jarreth! Are you receiving these messages to your regular e-mail, or on a Kindle device? If they're coming to your regular e-mail, you can adjust your preferences here: https://t.co/AUE3D3JzRP and here: https://t.co/EnklDbaglR ^LB",1,1,2,2_tweets,,
13,Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄,Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄,"[CUSTOMER] Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄\n[SUPPORT] @694817 Terribly sorry for your previous experience with us, Skylar! Without sharing any personal information, what were you having problems with? ^JZ",1,1,2,2_tweets,,
14,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,"[CUSTOMER] Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU\n[SUPPORT] @702707 I'm sorry for the aggravation! When you spoke with Seller Support, were they able to provide any insight or options? ^DD",1,1,2,2_tweets,,
15,Bought stickers from @115821 and they came all bent 😩,@AmazonHelp Third party,"[CUSTOMER] Bought stickers from @115821 and they came all bent 😩\n[SUPPORT] @381149 Oh no! I'm sorry your stickers came bent! Were they fulfilled by Amazon or a Third-Party Seller? ^AR\n[CUSTOMER] @AmazonHelp Third party\n[SUPPORT] @381149 Have you contacted the seller to report the damage? If not, please e-mail them and keep us posted: https://t.co/2hC58w1Tee ^BH",2,2,4,3_to_4_tweets,,
16,@115850 Your sale advertisement today. Trivia: Find the mistake in the image. U need better testers to validate content. Can I Join you? https://t.co/xMojPqCjvL,"@AmazonHelp The santa can visit early, may be on the Diwali day. 😁","[CUSTOMER] @115850 Your sale advertisement today. Trivia: Find the mistake in the image. U need better testers to validate content. Can I Join you? https://t.co/xMojPqCjvL\n[SUPPORT] @349395 Thanks for flagging this. I've checked and this has been updated. ^KA\n[CUSTOMER] @AmazonHelp No rewards for me??? 😏\n[SUPPORT] @349395 Unfortunately, we do not offer a bounty program. ^SA\n[CUSTOMER] @AmazonHelp The santa can visit early, may be on the Diwali day. 😁",3,2,5,5_to_8_tweets,,
17,@115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!,@AmazonHelp I have but this is the 2nd time this has happened. I was told in April you would not give my packages to Lasership but you did! No bueno!,[CUSTOMER] @115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!\n[SUPPORT] @123475 Sorry for the poor experience! Have you spoken our customer service so we could escalate this feedback to the carrier? ^AD\n[CUSTOMER] @AmazonHelp I have but this is the 2nd time this has happened. I was told in April you would not give my packages to Lasership but you did! No bueno!,2,1,3,3_to_4_tweets,,
18,Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!\nAmazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA,@171133 @115850 I registered. But where is my registration id https://t.co/gJhRyHNess,"[CUSTOMER] Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!\nAmazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA\n[CUSTOMER] @171133 @115850 I registered. But where is my registration id https://t.co/gJhRyHNess\n[SUPPORT] @773255 If you have registered, you'd receive a confirmation mail for the subscription. Kindly check the mail. Also, Ple...",2,1,3,3_to_4_tweets,,
19,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...","@AmazonHelp So i will just accept the refund i did not ask for and buy the book in another place, thank you.","[CUSTOMER] @AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (nev...",8,4,12,9_plus_tweets,,
20,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,[CUSTOMER] Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B\n[SUPPORT] @509967 Apologies. Request you to please share the feedback here: https://t.co/lvha47jKgQ. ^SK,1,1,2,2_tweets,,
21,@115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162,@AmazonHelp Sent the reply to the same,"[CUSTOMER] @115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162\n[SUPPORT] @213144 Apologies for the experience, Ram. Please elaborate your concern for us to assist you better. (1/2) ^SV\n[SUPPORT] @213144 Please don't provide your order details, we consider it personal info. Our Twitter page is visible to public. (2/2) ^SV\n[CUSTOMER] @AmazonHelp You can check the case by order number the issue\n[SUPPORT] @21314...",7,9,16,9_plus_tweets,,
22,アマゾンプライムでアニメを見る日々が始まる……\nネットで探す必要がなくなった…\n喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0,アマゾンプライムでアニメを見る日々が始まる……\nネットで探す必要がなくなった…\n喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0,[CUSTOMER] アマゾンプライムでアニメを見る日々が始まる……\nネットで探す必要がなくなった…\n喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0\n[SUPPORT] @751955 チキン・・・だ！！((；ﾟДﾟ)) TN,1,1,2,2_tweets,,
23,No @118706 has informed @AmazonHelp that my packages have been damaged before they even made an attempt to ship them out,"@AmazonHelp By the way, I a still on hold, after one of your customer service people hung up on me","[CUSTOMER] No @118706 has informed @AmazonHelp that my packages have been damaged before they even made an attempt to ship them out\n[SUPPORT] @322579 I'm sorry this happened, please contact us directly here: https://t.co/hApLpMlfHN\nSo we can help get this issue resolved as soon as possible. ^BT\n[CUSTOMER] @AmazonHelp No I did that yesterday. I am not doing that anymore. I can't do this anymore. I am exhausted. I just came from work and class, Why did I want to waste my time with a custom...",9,2,11,9_plus_tweets,,
24,Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT,"@146910 @AmazonHelp @146905 @146906 Et pendant ce temps, @146911 se frotte les mains.","[CUSTOMER] Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT\n[CUSTOMER] @146907 @120533 @AmazonHelp Oui ça part en sucette. Avec le Prime sur des produits envoyés par Amazon je n'arrive plus à être livré le lendemain que de temps en temps..\n[SUPPORT] @146907 Bonjour Pierre-Alain, sachez que de nombreux facteurs indépendants de notre volonté influent sur la date de livraison d'une commande : la disponibilité de l'article, la destination du colis...\n^ARC\n[SUPPO...",23,12,35,9_plus_tweets,,
25,"@115821 @117795 I've been trying to purchase a portable air purifier for the past 30 minutes, I can't find one that'll ship to CA..",@AmazonHelp My original question has not been answered - how can I locate an air purifier product that will ship to my area on #Amazon ?,"[CUSTOMER] @115821 @117795 I've been trying to purchase a portable air purifier for the past 30 minutes, I can't find one that'll ship to CA..\n[SUPPORT] @405222 Hi Michelle. Some items that are considered to be hazmat or large may have shipping restrictions to specific areas. You can (1/2)\n[SUPPORT] @405222 view more information about those restrictions here: https://t.co/rFpIWQE3UP We hope this helps. ^HC (2/2)\n[CUSTOMER] @AmazonHelp Ty for your response but the link doesn't help. Can yo...",5,4,9,9_plus_tweets,,
26,@115821 2 day delivery will NEVER happen if Amazon continues to rely on the USPS. Prime is nothing without the delivery guarantee.,"@AmazonHelp yes we were told no other options. So sorry. We have had deliveries to the door by UPS for years, now no other options","[CUSTOMER] @115821 2 day delivery will NEVER happen if Amazon continues to rely on the USPS. Prime is nothing without the delivery guarantee.\n[SUPPORT] @723483 Hi Christy, have you had an issue with a recent order? Without revealing any personal information, could you explain the problem? ^PJ\n[CUSTOMER] @AmazonHelp My last few orders have been over the guaranteed 2 days and one included me going to PO to pick up, because they DO NOT DELIVER\n[SUPPORT] @723483 Hi Christy, sorry to hear abou...",4,2,6,5_to_8_tweets,,
27,@115851 ur staff is updatung that we are resolving &amp; rturning your money after 50 days saying product delivered that was an office adress https://t.co/Ec6xunk8wk,@AmazonHelp @115851 i think u r't undersatnding that was not delivered to me so u r retng money on last 8th shareng confrmtn not able to cntct on cal https://t.co/3LvuaKzJg4,[CUSTOMER] @115851 ur staff is updatung that we are resolving &amp; rturning your money after 50 days saying product delivered that was an office adress https://t.co/Ec6xunk8wk\n[CUSTOMER] @115851 @115850 @115821 @AmazonHelp To whom you deliver the product that was your mistake if you deliver any one else i have not get the product by today itself wnt my money bk https://t.co/Tb2f4A5y9I\n[SUPPORT] @158410 in the details here : https://t.co/beaaDm0muc (2/2) ^PR\n[SUPPORT] @158410 Sorry for th...,5,4,9,9_plus_tweets,,

In [97]:
for i, row in taxonomy_audit.iloc[:30].iterrows():
    print("=" * 100)
    print(f"ROW {i}")
    print(f"Size: {row['size_bucket']} | "
          f"Customer turns: {row['customer_turns']} | "
          f"Support turns: {row['support_turns']}")
    print("-" * 100)
    print("FIRST CUSTOMER:")
    print(row["first_customer_message"])
    print("\nLAST CUSTOMER:")
    print(row["last_customer_message"])
    print()

====================================================================================================
ROW 0
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP

LAST CUSTOMER:
@AmazonHelp Thank you

====================================================================================================
ROW 1
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52

LAST CUSTOMER:
@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52

====================================================================================================
ROW 2
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
You guys should really Google the word "Guaranteed" before giving me an arrival date. Just terrible this year. #Amazon @115821 #late #guess?

LAST CUSTOMER:
@AmazonHelp Per Amazon arriving today. Per UPS arriving tomorrow with 1 of 6 guaranteed delivered today.

====================================================================================================
ROW 3
Size: 5_to_8_tweets | Customer turns: 2 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850

LAST CUSTOMER:
@AmazonHelp Yes, I got many emails regarding this issue and finally they want me to wait till tomorrow. Hope this will be resolved tomorrow.

====================================================================================================
ROW 4
Size: 5_to_8_tweets | Customer turns: 2 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG

LAST CUSTOMER:
@AmazonHelp You have sent an email that product was Delivered and in Application you have updated status that, it was handed directly to me and the delivery receipt was signed by me, which is completely false. This seems to be the signature forgery and fraud. @120781 @115850 https://t.co/LVYjdo0ky4

====================================================================================================
ROW 5
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Dear @115828 @115821  My "allegedly" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI

LAST CUSTOMER:
Dear @115828 @115821  My "allegedly" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI

====================================================================================================
ROW 6
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Can’t believe @115830’s response to me asking why my Xbox One X hasn’t been despatched yet. “If you’re not happy with it, cancel”

LAST CUSTOMER:
@AmazonHelp It's still saying shipping today, arriving today.  This was a waste of a day off work.  A friend who ordered five days later has had theirs.

====================================================================================================
ROW 7
Size: 9_plus_tweets | Customer turns: 11 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice

LAST CUSTOMER:
@AmazonHelp https://t.co/VtapWl2C1l The fact that there are videos of terrible AMZL_US deliveries sure says a lot. Where do you find these people?

====================================================================================================
ROW 8
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp When I was adding mny there was  no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u

LAST CUSTOMER:
@AmazonHelp When I was adding mny there was  no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u

====================================================================================================
ROW 9
Size: 5_to_8_tweets | Customer turns: 6 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
An update : It’s still Monday.

#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9

LAST CUSTOMER:
@794324 @794325 Amazon have fucked up big time with me over my order. Wont be getting it til Wednesday so youll be a day ahead of me. Never mind I'll pick up a copy at Waterstones tomorrow night maybe!!

====================================================================================================
ROW 10
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.

LAST CUSTOMER:
@AmazonHelp Finally could do it through SMS alert link. But it's actually quite cumbersome looking for it.

====================================================================================================
ROW 11
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Prime now turkey tracker. https://t.co/90UMXDP11e

LAST CUSTOMER:
Prime now turkey tracker. https://t.co/90UMXDP11e

====================================================================================================
ROW 12
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK

LAST CUSTOMER:
@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK

====================================================================================================
ROW 13
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄

LAST CUSTOMER:
Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄

====================================================================================================
ROW 14
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU

LAST CUSTOMER:
Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU

====================================================================================================
ROW 15
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Bought stickers from @115821 and they came all bent 😩

LAST CUSTOMER:
@AmazonHelp Third party

====================================================================================================
ROW 16
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 Your sale advertisement today. Trivia: Find the mistake in the image. U need better testers to validate content. Can I Join you? https://t.co/xMojPqCjvL

LAST CUSTOMER:
@AmazonHelp The santa can visit early, may be on the Diwali day. 😁

====================================================================================================
ROW 17
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!

LAST CUSTOMER:
@AmazonHelp I have but this is the 2nd time this has happened. I was told in April you would not give my packages to Lasership but you did! No bueno!

====================================================================================================
ROW 18
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!
Amazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA

LAST CUSTOMER:
@171133 @115850 I registered. But where is my registration id https://t.co/gJhRyHNess

====================================================================================================
ROW 19
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...

LAST CUSTOMER:
@AmazonHelp So i will just accept the refund i did not ask for and buy the book in another place, thank you.

====================================================================================================
ROW 20
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B

LAST CUSTOMER:
Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B

====================================================================================================
ROW 21
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 9
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162

LAST CUSTOMER:
@AmazonHelp Sent the reply to the same

====================================================================================================
ROW 22
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
アマゾンプライムでアニメを見る日々が始まる……
ネットで探す必要がなくなった…
喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0

LAST CUSTOMER:
アマゾンプライムでアニメを見る日々が始まる……
ネットで探す必要がなくなった…
喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0

====================================================================================================
ROW 23
Size: 9_plus_tweets | Customer turns: 9 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
No @118706 has informed @AmazonHelp that my packages have been damaged before they even made an attempt to ship them out

LAST CUSTOMER:
@AmazonHelp By the way, I a still on hold, after one of your customer service people hung up on me

====================================================================================================
ROW 24
Size: 9_plus_tweets | Customer turns: 23 | Support turns: 12
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT

LAST CUSTOMER:
@146910 @AmazonHelp @146905 @146906 Et pendant ce temps, @146911 se frotte les mains.

====================================================================================================
ROW 25
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 @117795 I've been trying to purchase a portable air purifier for the past 30 minutes, I can't find one that'll ship to CA..

LAST CUSTOMER:
@AmazonHelp My original question has not been answered - how can I locate an air purifier product that will ship to my area on #Amazon ?

====================================================================================================
ROW 26
Size: 5_to_8_tweets | Customer turns: 4 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 2 day delivery will NEVER happen if Amazon continues to rely on the USPS. Prime is nothing without the delivery guarantee.

LAST CUSTOMER:
@AmazonHelp yes we were told no other options. So sorry. We have had deliveries to the door by UPS for years, now no other options

====================================================================================================
ROW 27
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115851 ur staff is updatung that we are resolving &amp; rturning your money after 50 days saying product delivered that was an office adress https://t.co/Ec6xunk8wk

LAST CUSTOMER:
@AmazonHelp @115851 i think u r't undersatnding that was not delivered to me so u r retng money on last 8th shareng confrmtn not able to cntct on cal https://t.co/3LvuaKzJg4

====================================================================================================
ROW 28
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@118919  Ordered an Honor 8 from Amazon Prime and received a burned damaged crappy 1200 Nokia phone, a Rin Soap and a Life Boy soap. This is an experience that we never expected from a renowned company.  #badservice #amazon  9/11/17 #iwantmymoneyback https://t.co/XFukkBFBFz

LAST CUSTOMER:
@AmazonHelp Done

====================================================================================================
ROW 29
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
I ducking paid $4 extra for 1 day shipping and my shit coming in 3 days.   @115821 y’all fucking up o want to be credited for this

LAST CUSTOMER:
I ducking paid $4 extra for 1 day shipping and my shit coming in 3 days.   @115821 y’all fucking up o want to be credited for this

Enter Batch 1 into the dataframe

In [98]:
batch_1_labels = {
    0: "PRODUCT_PROBLEM",
    1: "OTHER_NON_SUPPORT",
    2: "DELIVERY_DELAY",
    3: "DELIVERY_DELAY",
    4: "DELIVERY_MISSING_OR_MISDELIVERED",
    5: "PRODUCT_PROBLEM",
    6: "ORDER_STATUS_OR_CANCELLATION",
    7: "DELIVERY_DELAY",
    8: "PAYMENT_BILLING",
    9: "DELIVERY_DELAY",
    10: "ACCOUNT_ACCESS_SECURITY",
    11: "OTHER_NON_SUPPORT",
    12: "WEBSITE_APP_TECHNICAL",
    13: "PRIME_MEMBERSHIP",
    14: "OTHER_NON_SUPPORT",
    15: "PRODUCT_PROBLEM",
    16: "OTHER_NON_SUPPORT",
    17: "DELIVERY_MISSING_OR_MISDELIVERED",
    18: "GIFT_CARD_PROMOTION",
    19: "ORDER_STATUS_OR_CANCELLATION",
    20: "PRODUCT_PROBLEM",
    21: "OTHER_NON_SUPPORT",
    22: "OTHER_NON_SUPPORT",
    23: "PRODUCT_PROBLEM",
    24: "DELIVERY_DELAY",
    25: "PRODUCT_AVAILABILITY_INFORMATION",
    26: "DELIVERY_DELAY",
    27: "DELIVERY_MISSING_OR_MISDELIVERED",
    28: "PRODUCT_PROBLEM",
    29: "DELIVERY_DELAY",
}

for row_idx, label in batch_1_labels.items():
    taxonomy_audit.loc[row_idx, "intent_label"] = label

# Add notes for the taxonomy-gap example
taxonomy_audit.loc[14, "annotation_notes"] = (
    "Does not fit current taxonomy cleanly; possible seller-support intent."
)

taxonomy_audit.loc[21, "annotation_notes"] = (
    "General customer-service complaint without a specific underlying issue."
)

taxonomy_audit.loc[16, "annotation_notes"] = (
    "Advertisement/content feedback rather than a defined support issue."
)

# Save
taxonomy_audit.to_csv(audit_path, index=False)

print("Batch 1 saved.")
print("Annotated:", (taxonomy_audit["intent_label"].str.strip() != "").sum())
print("Remaining:", (taxonomy_audit["intent_label"].str.strip() == "").sum())

Batch 1 saved.
Annotated: 30
Remaining: 120

In [99]:
for i, row in taxonomy_audit.iloc[30:60].iterrows():
    print("=" * 100)
    print(f"ROW {i}")
    print(
        f"Size: {row['size_bucket']} | "
        f"Customer turns: {row['customer_turns']} | "
        f"Support turns: {row['support_turns']}"
    )
    print("-" * 100)
    print("FIRST CUSTOMER:")
    print(row["first_customer_message"])
    print("\nLAST CUSTOMER:")
    print(row["last_customer_message"])
    print()

====================================================================================================
ROW 30
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp . IRe: Your Amazon.in Order  # 402-4987357-3643550 dear Amazon stop making fools .

LAST CUSTOMER:
@AmazonHelp . IRe: Your Amazon.in Order  # 402-4987357-3643550 dear Amazon stop making fools .

====================================================================================================
ROW 31
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@40172 when is your next season coming up?

LAST CUSTOMER:
@40172 when is your next season coming up?

====================================================================================================
ROW 32
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850   Ok den tell me till when I have to wait..first tym I dint got any call or msg regarding the delivery person..day is about to end..I paid to get it delivered today what if it dint happened today?

LAST CUSTOMER:
@AmazonHelp U ppl must b knowing the delivery boy who has my product. Talk to him and u let me knw or provide me the details

====================================================================================================
ROW 33
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp keep rec’ng pkgs for an apt building two blocks from my house.  Emails to amazon support not solving problem. Do drivers read?

LAST CUSTOMER:
@AmazonHelp keep rec’ng pkgs for an apt building two blocks from my house.  Emails to amazon support not solving problem. Do drivers read?

====================================================================================================
ROW 34
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 cudn't deliver in 2.5 month. Amazon sellers r very bad. Amazon takes no responsibility. Cust care don't know what to do. Trapped.

LAST CUSTOMER:
@AmazonHelp Details provided.

====================================================================================================
ROW 35
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 7
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Hi, I just recevied an order but the box is damaged, anything you can do ? Thanks !

LAST CUSTOMER:
@AmazonHelp No I haven't

====================================================================================================
ROW 36
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp sir your customer care is extremly rude,and Doesn't care About the truth.i can not bear this fraud any way.i want replacement.

LAST CUSTOMER:
@AmazonHelp sir your customer care is extremly rude,and Doesn't care About the truth.i can not bear this fraud any way.i want replacement.

====================================================================================================
ROW 37
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 @AmazonHelp pre-ordered this book and it finally came in today! but with damages :/ https://t.co/BdpvGIQYPj

LAST CUSTOMER:
@115821 @AmazonHelp pre-ordered this book and it finally came in today! but with damages :/ https://t.co/BdpvGIQYPj

====================================================================================================
ROW 38
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T

LAST CUSTOMER:
せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T

====================================================================================================
ROW 39
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Always nice to see @115821 drivers dropping your electronics on delivery https://t.co/DQFMmAad5m

LAST CUSTOMER:
Always nice to see @115821 drivers dropping your electronics on delivery https://t.co/DQFMmAad5m

====================================================================================================
ROW 40
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp plse help .check DM and help quickly

LAST CUSTOMER:
@AmazonHelp I have given link and why u not able to reply it.
 Cc also not answering right ..

====================================================================================================
ROW 41
Size: 5_to_8_tweets | Customer turns: 4 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Man... my @115821 package has been "preparing" for almost two days straight now... getting really #worried it won't "arrive tomorrow"

LAST CUSTOMER:
@AmazonHelp My packages arrived safely, thank you for your time :)

====================================================================================================
ROW 42
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Hey @115850 is there some down time going on on the app? I've been trying to place an order for two days now! Please help.

LAST CUSTOMER:
@AmazonHelp Caked multiple times but I'm not able to connect to a cust. care exec. There's no section on your app to address such technical issues!

====================================================================================================
ROW 43
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
whoever stole my amazon package, i hope you enjoy those lactating pads, you sicko

LAST CUSTOMER:
whoever stole my amazon package, i hope you enjoy those lactating pads, you sicko

====================================================================================================
ROW 44
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115830 it's an absolute joke I pay for prime and now you are charging a delivery fee that was free with prime!!! Ragging 😡 #Amazon #AmazonPrime

LAST CUSTOMER:
@115830 it's an absolute joke I pay for prime and now you are charging a delivery fee that was free with prime!!! Ragging 😡 #Amazon #AmazonPrime

====================================================================================================
ROW 45
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: "preparando envío"

LAST CUSTOMER:
@AmazonHelp Ya me cambiaron la información del producto 😡 ahora dice que no lo pueden enviar a mi código postal pero cuando lo pedí no decía eso, tengo que comprarlo de nuevo???? 😡😡

====================================================================================================
ROW 46
Size: 9_plus_tweets | Customer turns: 2 | Support turns: 7
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Having a nightmare delivery experience with @115821 @115850 2nd week in a row
No card swipe machines, delivery guy doesn't have any change

LAST CUSTOMER:
@AmazonHelp Delivery guy said MPOS machines available but "NOT WORKING" the whole of last week.2day again no change/machine for a Rs.2700/- order 🤨🤔

====================================================================================================
ROW 47
Size: 9_plus_tweets | Customer turns: 9 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
.@AmazonHelp ¿Podríais decidme cuál es el motivo de este retraso? @137605 ha pasado por la puerta del lugar de entrega a toda prisa1/2 https://t.co/nARimuzGAB

LAST CUSTOMER:
@137605 @AmazonHelp Acaban de realizar la entrega. Gracias de todos modos.

====================================================================================================
ROW 48
Size: 5_to_8_tweets | Customer turns: 5 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp See the magic done by prime. So you guys think that prime members are richer? First photo is for non-prime members and the second one for prime members. It should be the reverse right? https://t.co/vMB5tY6YjG

LAST CUSTOMER:
@AmazonHelp If the sellers are offering their products only for non prime members fearing of losing their delivery costs, then why did you come with this prime membership and free delivery campaign .  Now you are talking as if you don't have any connection with the prices shown by the seller

====================================================================================================
ROW 49
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Ordered what was probably my last physical new game release of the year with Amazon Prime and it winds up transit delayed by UPS at 5am and no new updates since. Can’t win em all?

LAST CUSTOMER:
@AmazonHelp The game did not arrive. Amazon order page says Dec 2 - 5 as the new delivery estimate. UPS hasn’t updated its status yet.

====================================================================================================
ROW 50
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
I love my Echo Look &amp; don't care if Amazon wants to datamine my wardrobe, but can I get some Bluetooth connectivity here? @115833

LAST CUSTOMER:
@115833 "Tinny music is the price you must pay for your sloth" NO! I REFUSE TO ACCEPT THIS

====================================================================================================
ROW 51
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115830 pre-ordered call of duty in April, getting an email at 9:43 on release day sayings it’s not dispatched yet is ridiculous.

LAST CUSTOMER:
@AmazonHelp I’m a prime member and I ordered it over 6 months ago. Surely that should qualify it?

====================================================================================================
ROW 52
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
げ、いつの間にかAmazonプライム会員になっていた。いつだよ

LAST CUSTOMER:
げ、いつの間にかAmazonプライム会員になっていた。いつだよ

====================================================================================================
ROW 53
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp What has happened to Prime One Day Delivery?  Both parcels I ordered last week have taken 3-4 days and one of them still isn't here...

LAST CUSTOMER:
@AmazonHelp What has happened to Prime One Day Delivery?  Both parcels I ordered last week have taken 3-4 days and one of them still isn't here...

====================================================================================================
ROW 54
Size: 9_plus_tweets | Customer turns: 4 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Thanks! The product just got delivered but it's broken :(

LAST CUSTOMER:
@AmazonHelp Super! Thanks

====================================================================================================
ROW 55
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp had two packages scheduled to arrive by 8pm from ur driver. 8:47 pm and no packages. Should I assume they are not coming today?

LAST CUSTOMER:
@AmazonHelp It still says out for delivery but my husband checked outside and the packages were just delivered. Thank you.

====================================================================================================
ROW 56
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115851 @115850 @115821 @AmazonHelp Do anybody in your team care for a 4 year old customer, who has paid for an undelivered product pending since last 1 month? https://t.co/vbHp7yRM9L

LAST CUSTOMER:
@115851 @115850 @115821 @AmazonHelp Do anybody in your team care for a 4 year old customer, who has paid for an undelivered product pending since last 1 month? https://t.co/vbHp7yRM9L

====================================================================================================
ROW 57
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp @115850 @115821 Greatly disappointed and tremendously frustrating experience with my order. Customer care highly misleading https://t.co/VSlBsXEcNU

LAST CUSTOMER:
@AmazonHelp Already spoke and they are the ones who provided the misleading information. It's been a series of people who have been doing so

====================================================================================================
ROW 58
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
マジでアマゾンミュージック様天才すぎっからみんなプライムはいれ

LAST CUSTOMER:
@AmazonHelp ﾋｴｯこちらこそ素晴らしいサービスをありがとうございます！！(;;)ペルソナ関連楽曲の配信とてもとてもうれしいです！！これからも利用させていただきます｡ﾟ(ﾟ＾∀＾ﾟ)ﾟ｡

====================================================================================================
ROW 59
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp すみません 😥
大丈夫です
気長に待ってます 😉

LAST CUSTOMER:
@AmazonHelp すみません 😥
大丈夫です
気長に待ってます 😉

In [100]:
batch_2_labels = {
    30: "OTHER_NON_SUPPORT",
    31: "OTHER_NON_SUPPORT",
    32: "DELIVERY_DELAY",
    33: "DELIVERY_MISSING_OR_MISDELIVERED",
    34: "DELIVERY_DELAY",
    35: "PRODUCT_PROBLEM",
    36: "RETURN_REPLACEMENT_REFUND",
    37: "PRODUCT_PROBLEM",
    38: "DIGITAL_CONTENT",
    39: "PRODUCT_PROBLEM",
    40: "OTHER_NON_SUPPORT",
    41: "DELIVERY_DELAY",
    42: "WEBSITE_APP_TECHNICAL",
    43: "DELIVERY_MISSING_OR_MISDELIVERED",
    44: "PRIME_MEMBERSHIP",
    45: "ORDER_STATUS_OR_CANCELLATION",
    46: "PAYMENT_BILLING",
    47: "DELIVERY_DELAY",
    48: "PRIME_MEMBERSHIP",
    49: "DELIVERY_DELAY",
    50: "DEVICE_TECHNICAL_SUPPORT",
    51: "ORDER_STATUS_OR_CANCELLATION",
    52: "PRIME_MEMBERSHIP",
    53: "DELIVERY_DELAY",
    54: "PRODUCT_PROBLEM",
    55: "DELIVERY_DELAY",
    56: "DELIVERY_DELAY",
    57: "OTHER_NON_SUPPORT",
    58: "DIGITAL_CONTENT",
    59: "OTHER_NON_SUPPORT",
}

for row_idx, label in batch_2_labels.items():
    taxonomy_audit.loc[row_idx, "intent_label"] = label

# Add useful taxonomy notes
taxonomy_audit.loc[40, "annotation_notes"] = (
    "Support/contact follow-up but underlying issue is not identifiable."
)

taxonomy_audit.loc[45, "annotation_notes"] = (
    "Order lifecycle problem; later becomes shipping eligibility issue."
)

taxonomy_audit.loc[44, "annotation_notes"] = (
    "Prime benefit/fee issue, therefore Prime Membership rather than delivery delay."
)

taxonomy_audit.loc[55, "annotation_notes"] = (
    "Initial issue is delayed delivery; eventual successful delivery does not change primary intent."
)

taxonomy_audit.to_csv(audit_path, index=False)

print("Batch 2 saved.")
print("Annotated:", (taxonomy_audit["intent_label"].str.strip() != "").sum())
print("Remaining:", (taxonomy_audit["intent_label"].str.strip() == "").sum())

Batch 2 saved.
Annotated: 60
Remaining: 90

In [101]:
for i, row in taxonomy_audit.iloc[60:90].iterrows():
    print("=" * 100)
    print(f"ROW {i}")
    print(
        f"Size: {row['size_bucket']} | "
        f"Customer turns: {row['customer_turns']} | "
        f"Support turns: {row['support_turns']}"
    )
    print("-" * 100)
    print("FIRST CUSTOMER:")
    print(row["first_customer_message"])
    print("\nLAST CUSTOMER:")
    print(row["last_customer_message"])
    print()

====================================================================================================
ROW 60
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Dear @115830 - what's the point of sending me an app validation code with 10 mins life if it takes 5 hours to get to me?

LAST CUSTOMER:
@AmazonHelp I've initiated a chat session now - thanks

====================================================================================================
ROW 61
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
I have ordered so many books from @115850 . But everytime I get the same old boring bookmarks. Could you please send me some really cool exciting bookmarks for my next order of book?.

LAST CUSTOMER:
I have ordered so many books from @115850 . But everytime I get the same old boring bookmarks. Could you please send me some really cool exciting bookmarks for my next order of book?.

====================================================================================================
ROW 62
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116313 アマゾンのサイトのフォントサイズですが、大きくなりましたか？それとも、当PC（ちなみにChrome使用）だけでしょうか？

LAST CUSTOMER:
@116313 アマゾンのサイトのフォントサイズですが、大きくなりましたか？それとも、当PC（ちなみにChrome使用）だけでしょうか？

====================================================================================================
ROW 63
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850  Still didn't get my product😡😡😡 Too much disappointed https://t.co/jxFqdBYpne

LAST CUSTOMER:
@115850  Still didn't get my product😡😡😡 Too much disappointed https://t.co/jxFqdBYpne

====================================================================================================
ROW 64
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115830 #lookout #everyone #amazonprime #charges #noconfrimation 🛒🧐

LAST CUSTOMER:
@AmazonHelp Many thanks : my query has been resolved now by your attentive help line :-)

====================================================================================================
ROW 65
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Hey @AmazonHelp warum ist das Spiel Monopoly für die Switch plötzlich ca. 10 Euro teurer? #nerv

LAST CUSTOMER:
@AmazonHelp Schade .... dann wird er woanders gekauft.

====================================================================================================
ROW 66
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp vais a reponer el stock de Horizon: Zero Dawn? Al llegar a casa ya se habían agotado. 😢

LAST CUSTOMER:
@AmazonHelp Gracias.

====================================================================================================
ROW 67
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
I am watching Shin Chan Season 1. But currently it is not available to my location. Why are you people doing like this? @119625

LAST CUSTOMER:
@AmazonHelp Thank you.

====================================================================================================
ROW 68
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I received ANOTHER damaged #AmazonSubscribeAndSave  delivered by @118706 it was clearly marked as HEAVY &amp; delivered on its side.

LAST CUSTOMER:
@AmazonHelp Is there an option to specifically avoid @118706 as the shipper?

====================================================================================================
ROW 69
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I have a parcel which says delivered but was not delivered to me. Could you help me track down where this was delivered please? @115821  @115830

LAST CUSTOMER:
@AmazonHelp All done already...

====================================================================================================
ROW 70
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
野球と全く関係ないんですが質問したいことがあるのでさせていただきます
Amazonを利用したことがある人はわかると思いますが商品を注文して自宅に届くようにしたんですけど受け取るまでの過程とかよくわからないのでわかる人いたら教えて欲しいです
お願いします

LAST CUSTOMER:
@AmazonHelp わかりました
色々と教えていただきありがとうございました

====================================================================================================
ROW 71
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
amazonの箱、お気に入りニャ！ https://t.co/5tpV2WlpKw

LAST CUSTOMER:
amazonの箱、お気に入りニャ！ https://t.co/5tpV2WlpKw

====================================================================================================
ROW 72
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116439 how do I connect my @115833 to my fire tv stick in the uk? Tried to go through Alexa app but no option to connect. Help!

LAST CUSTOMER:
@AmazonHelp And are you going to answer my question?

====================================================================================================
ROW 73
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Dear @115830 this is not the wonder twins https://t.co/AvhzdenO2R

LAST CUSTOMER:
@AmazonHelp Spoke to ur abysmal customer service team. 6 working days for a refund. 3rd party supplier so you can't do a single thing to properly help.

====================================================================================================
ROW 74
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
知らん間にAmazonプライム会員にさせられてたので有効活用してやろうと思うんやけど送料無料以外に何が出来るんや

LAST CUSTOMER:
@AmazonHelp ご丁寧にありがとうございます。prime studentは安いし良さそうなので今後も引き続き使わせていただきますが、自動更新のオンオフは無料体験開始時に設定できるとありがたいです。

====================================================================================================
ROW 75
Size: 5_to_8_tweets | Customer turns: 2 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp thank you so much for non delivery of your product and declaring it as delivered. Nt the 1st time. Multiple complaints &amp; still no answers... Kudos. https://t.co/tL8Waru6uL

LAST CUSTOMER:
@AmazonHelp Still no contact.. Great job!

====================================================================================================
ROW 76
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp @116618 @115850 keep on getting this error while playing any vid in the prime app!! Can use some help https://t.co/2KsfYfbbBt

LAST CUSTOMER:
@AmazonHelp Escalated it to a supervisor and he managed to help fix the issue stating that Account had Australia Regional setting that was causing the issue, Video is working on laptop, iPad and Mobile now, @132976 still shows unavailable :(

====================================================================================================
ROW 77
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Puto Correos de mierda y puto amazon. Empieza a ser demasiado habitual que llas reservas lleguen tarde...entonces PARA QUE COÑO RESERVAMOS? @116928

LAST CUSTOMER:
@AmazonHelp @133260 Si, la que me tenía qie haber llegado hoy y que me han reenviado para recibir mañana...eso espero vamos

====================================================================================================
ROW 78
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Amazonダッシュボタンを押しても無反応。今までは大丈夫だったのに。どういうこと？

LAST CUSTOMER:
Amazonダッシュボタンを押しても無反応。今までは大丈夫だったのに。どういうこと？

====================================================================================================
ROW 79
Size: 5_to_8_tweets | Customer turns: 2 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Order no. 405-0437040-6374722 is not dispatched yet. Delivery date is 5th October. Please call at 9654126686

LAST CUSTOMER:
@AmazonHelp It has been 48 hours since i have filled this form. When will you guys take action. it has already been 1 month since i have placed order

====================================================================================================
ROW 80
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 Amazon prime is not prime anymore, even the prime products take 4-5 days to deliver. :(

LAST CUSTOMER:
@AmazonHelp while viewing it is saying to 2-4 business days, but just before the payment option in review it is been updated to 3-7(as it is 25-28, pincode is same). people miss the updation in last page mostly. https://t.co/LmkkmLChYB

====================================================================================================
ROW 81
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
.@115830 Have sent me 2 boxes of 6 bottles of shampoo instead of the 2 I ordered in mistake, as I meant to order the conditioner. 🙈

LAST CUSTOMER:
@AmazonHelp Already processed to return dropping it off stage sorting office Saturday morning

====================================================================================================
ROW 82
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 it was showing that the product will be deliverd to me in 2 days guaranteed.
Orderd it on sunday still waiting to get it (2/2)

LAST CUSTOMER:
@115821 it was showing that the product will be deliverd to me in 2 days guaranteed.
Orderd it on sunday still waiting to get it (2/2)

====================================================================================================
ROW 83
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 when will I get my refund or claim refund from seller ?  Faulty roduct have been couriered to them and was delivered 4 days back.

LAST CUSTOMER:
@AmazonHelp Thanks

====================================================================================================
ROW 84
Size: 5_to_8_tweets | Customer turns: 5 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Wenn die Outlook App dir die Emails von gestern erst jetzt anzeigt und du die kurze Verfügbarkeit der Monster Hunter Collectors Edition auf @116316  verpasst. Ich raste aus...

LAST CUSTOMER:
@AmazonHelp Bin da schon Wochen dran. Was sind da 6 Std? 😂

====================================================================================================
ROW 85
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Hey @117795 you've delayed a delivery once again. One more time and I'll be exploring options like @2300

LAST CUSTOMER:
Hey @117795 you've delayed a delivery once again. One more time and I'll be exploring options like @2300

====================================================================================================
ROW 86
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 7
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
.@115821 @137088 What a joke. After "Guaranteed Delivery" today, total fail. Now I have to wait up to 6 days for an item that was supposed to be delivered next day? And the package started the day in Northridge! I could have picked it up myself. https://t.co/X2HpfjnogW

LAST CUSTOMER:
@137089 @115821 We are so sorry to hear this! Can you please DM us your tracking info so we can assist you?  Thank you!

====================================================================================================
ROW 87
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp this massive box for two nail varnishes is a bit much surely? 😂 https://t.co/aJBQUzsd1N

LAST CUSTOMER:
@AmazonHelp this massive box for two nail varnishes is a bit much surely? 😂 https://t.co/aJBQUzsd1N

====================================================================================================
ROW 88
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Excited to get an early birthday present today but holy crap @115821, that's the least environmentally conscious package I've ever seen! https://t.co/wXaEbdbmun

LAST CUSTOMER:
@AmazonHelp I'll do that now. Thanks for the speedy reply!

====================================================================================================
ROW 89
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Ahh. Was talking about exchanging ONE PLUS 5 for ONE PLUS 5T. 💁‍♂️

LAST CUSTOMER:
@AmazonHelp Ahh. Was talking about exchanging ONE PLUS 5 for ONE PLUS 5T. 💁‍♂️

In [102]:
batch_3_labels = {
    60: "ACCOUNT_ACCESS_SECURITY",
    61: "OTHER_NON_SUPPORT",
    62: "WEBSITE_APP_TECHNICAL",
    63: "DELIVERY_DELAY",
    64: "PAYMENT_BILLING",
    65: "PRODUCT_AVAILABILITY_INFORMATION",
    66: "PRODUCT_AVAILABILITY_INFORMATION",
    67: "DIGITAL_CONTENT",
    68: "PRODUCT_PROBLEM",
    69: "DELIVERY_MISSING_OR_MISDELIVERED",
    70: "PRODUCT_AVAILABILITY_INFORMATION",
    71: "OTHER_NON_SUPPORT",
    72: "DEVICE_TECHNICAL_SUPPORT",
    73: "RETURN_REPLACEMENT_REFUND",
    74: "PRIME_MEMBERSHIP",
    75: "DELIVERY_MISSING_OR_MISDELIVERED",
    76: "DIGITAL_CONTENT",
    77: "DELIVERY_DELAY",
    78: "DEVICE_TECHNICAL_SUPPORT",
    79: "ORDER_STATUS_OR_CANCELLATION",
    80: "DELIVERY_DELAY",
    81: "PRODUCT_PROBLEM",
    82: "DELIVERY_DELAY",
    83: "RETURN_REPLACEMENT_REFUND",
    84: "PRODUCT_AVAILABILITY_INFORMATION",
    85: "DELIVERY_DELAY",
    86: "DELIVERY_DELAY",
    87: "OTHER_NON_SUPPORT",
    88: "OTHER_NON_SUPPORT",
    89: "RETURN_REPLACEMENT_REFUND",
}

for row_idx, label in batch_3_labels.items():
    taxonomy_audit.loc[row_idx, "intent_label"] = label

# Record useful boundary notes
taxonomy_audit.loc[64, "annotation_notes"] = (
    "Transaction/charge confirmation issue; resolved by help line."
)

taxonomy_audit.loc[68, "annotation_notes"] = (
    "Repeated damaged delivery; shipper avoidance is secondary."
)

taxonomy_audit.loc[80, "annotation_notes"] = (
    "Prime mentioned, but actual problem is delivery time/estimate."
)

taxonomy_audit.loc[87, "annotation_notes"] = (
    "Packaging criticism without damage or concrete support request."
)

taxonomy_audit.loc[88, "annotation_notes"] = (
    "Environmental packaging criticism; no product defect."
)

taxonomy_audit.to_csv(audit_path, index=False)

print("Batch 3 saved.")
print("Annotated:", (taxonomy_audit["intent_label"].str.strip() != "").sum())
print("Remaining:", (taxonomy_audit["intent_label"].str.strip() == "").sum())

Batch 3 saved.
Annotated: 90
Remaining: 60

In [103]:
for i, row in taxonomy_audit.iloc[90:120].iterrows():
    print("=" * 100)
    print(f"ROW {i}")
    print(
        f"Size: {row['size_bucket']} | "
        f"Customer turns: {row['customer_turns']} | "
        f"Support turns: {row['support_turns']}"
    )
    print("-" * 100)
    print("FIRST CUSTOMER:")
    print(row["first_customer_message"])
    print("\nLAST CUSTOMER:")
    print(row["last_customer_message"])
    print()

====================================================================================================
ROW 90
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp one of my orders say its due to be delivered 2nd November but still no sign of it? 🤔

LAST CUSTOMER:
@AmazonHelp It doesn’t say

====================================================================================================
ROW 91
Size: 9_plus_tweets | Customer turns: 4 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 why my order is cancelled...? Need help 9782077700 https://t.co/fryoj1BkZz

LAST CUSTOMER:
@AmazonHelp I have already done this.. plz call me directly.. My prepaid order has been cancelled

====================================================================================================
ROW 92
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp https://t.co/9eUtPo7MRN

LAST CUSTOMER:
@AmazonHelp Still waiting for your response

====================================================================================================
ROW 93
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Apple Inc device ,IMEI no:__credit_card__ is not working. Got it through Amazon on 2oth September. Damages? Apple or Amazon?

LAST CUSTOMER:
@AmazonHelp Took a vow to not buy a product from Apple. And the product iPhone se on 20th September given is going to be a public burial.

====================================================================================================
ROW 94
Size: 9_plus_tweets | Customer turns: 13 | Support turns: 9
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 what is the point of calling it guarentee 2 day delivered when it is not guarenteed. And charging a premium for the delivery.

LAST CUSTOMER:
@AmazonHelp I have filled that form twice already. All I get is an apology message. This is even more frustrating. @120319 @348

====================================================================================================
ROW 95
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Ich bin etwas verwirrt. Wann kommt das Paket denn? Gestern, heute, morgen, Montag? https://t.co/nYRbEmTteO

LAST CUSTOMER:
@AmazonHelp Danke, werde ich machen sobald ich etwas Luft habe!

====================================================================================================
ROW 96
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Amazon Music Unlimited に登録してみた。Amazon Echoで登録すると、月額380円と格安だったわ。

LAST CUSTOMER:
Amazon Music Unlimited に登録してみた。Amazon Echoで登録すると、月額380円と格安だったわ。

====================================================================================================
ROW 97
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 @118702 @4167
(3/3) attaching the pics here. I never experienced this with Flipkart or Myntra. So funny and so betraying exp https://t.co/Z2gBtQ0fh4

LAST CUSTOMER:
@115850 @118702 @4167
(3/3) attaching the pics here. I never experienced this with Flipkart or Myntra. So funny and so betraying exp https://t.co/Z2gBtQ0fh4

====================================================================================================
ROW 98
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Prolly shoulda used better judgement on a Sunday delivery from @115821 but I PAID THE SHIPPING COST. WHERE'S MY STUFF??

LAST CUSTOMER:
@AmazonHelp And I don't see anywhere to report this. https://t.co/YOGfYNcTWB

====================================================================================================
ROW 99
Size: 9_plus_tweets | Customer turns: 11 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 you need to work on delivery. 1 in 4 of my orders have problems. 3 in a row now, two orders somewhere. You need to update shipping

LAST CUSTOMER:
@AmazonHelp carrier amzl US original delivery today, estimate now the 18th. Wrong dist center again. sold by Laptop Home

====================================================================================================
ROW 100
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
昨日の夜Amazonでポチったらもう届いた😃 https://t.co/kfY4aEz1go

LAST CUSTOMER:
昨日の夜Amazonでポチったらもう届いた😃 https://t.co/kfY4aEz1go

====================================================================================================
ROW 101
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
When your customer satisfaction goes from worse to hopeless avoiding customers is the only thing you can do @115850 @115821 https://t.co/s82Z34yAVd

LAST CUSTOMER:
When your customer satisfaction goes from worse to hopeless avoiding customers is the only thing you can do @115850 @115821 https://t.co/s82Z34yAVd

====================================================================================================
ROW 102
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I have been double charged and left penniless. The person I spoke to was worse than useless how do I make a formal complaint

LAST CUSTOMER:
@AmazonHelp I've had to phone twice to get what I needed after been told from an outside source. I want to lodge a complaint. I've been left with no money because of a mistake Amazon have made

====================================================================================================
ROW 103
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
SOCORRO AMAZON!!!!! GENTE EU COMPREI OS LIVROS ONTEM A TARDE E JA CHEGARAM AGORA EU TÔ PASMA COM A AGILIDADE, VC QUER @ ????

LAST CUSTOMER:
isso pq tava previsto pra chegar terça amém @117086

====================================================================================================
ROW 104
Size: 9_plus_tweets | Customer turns: 14 | Support turns: 11
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Hw to irritate n frustrate sme1,learn frm  @AmazonHelp
Filed a case in court,hope thy respond to the court notice

LAST CUSTOMER:
@179073 @AmazonHelp @115850 @115821 @115851 @127187 Did you get your order ? Me too facing the same issue ...

====================================================================================================
ROW 105
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 is down for me!

LAST CUSTOMER:
@115850 is down for me!

====================================================================================================
ROW 106
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 @115821 why there is no option of refund on electronic product? I m not happy with service. Provide me refund so I can buy some other product. #NotHappyWithAmazon

LAST CUSTOMER:
@AmazonHelp Yes, I have question. Was that the resolution?
Leave it guys. I guess you won't help me with issue I am facing. Please remove refund word from your offering for all electronics product and mention ONLY REPLACEMENT in bold. I guess that at least you can do. #NotHappyWithAmazon

====================================================================================================
ROW 107
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp oui depuis hier

LAST CUSTOMER:
@AmazonHelp livraison vendredi 17 c une blague

====================================================================================================
ROW 108
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 has been seriously dropping the ball lately with their “2-day shipping”... #LameAF

LAST CUSTOMER:
@115821 has been seriously dropping the ball lately with their “2-day shipping”... #LameAF

====================================================================================================
ROW 109
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Screen shot says package received at 10:49am and still cannot be delivered by @115850 till 18:30hrs. How will u Rate this service? https://t.co/QcEutdNYx3

LAST CUSTOMER:
Screen shot says package received at 10:49am and still cannot be delivered by @115850 till 18:30hrs. How will u Rate this service? https://t.co/QcEutdNYx3

====================================================================================================
ROW 110
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@130626 Ordered delux edition on @115821 but it says I won’t receive my order until Tuesday, the 17? Anything to suggest so I can receive the game 4 days early as advertised?

LAST CUSTOMER:
@AmazonHelp It’s the video game #WWE2K18 delux digital edition for the PlayStation 4

====================================================================================================
ROW 111
Size: 9_plus_tweets | Customer turns: 4 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
2nd time failed frm pymnt gatway fr bokng iphone6 32Gb gray cost 20k thn imdate incrsd to 26450.Wht's offr running don't undrstnd @115850 https://t.co/7edeUhB53O

LAST CUSTOMER:
@AmazonHelp It's nt stock exchange same item keep fluctuations.Its crazy Customer leave amazon will go some other online services Bytway I've buy'ed. Ty

====================================================================================================
ROW 112
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
J'ai commandé y'a 10 jours, et la date de livraison ne fait qu'être repoussée...
@120533 https://t.co/guP5rJgapW

LAST CUSTOMER:
@AmazonHelp À priori maintenant que le colis est parti ça devrait être bon mais il a mis du temps a partir... https://t.co/p8ipJ4qX16

====================================================================================================
ROW 113
Size: 9_plus_tweets | Customer turns: 11 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
(1) Bought @1469 K8 from Amazon. Pathetic camera quality. Wanted to return it and buy another phone. @115850 replaced instead of

LAST CUSTOMER:
@AmazonHelp @115850 @115851 #8 my last order from @115850 @amazonhelp @115851 @115821

====================================================================================================
ROW 114
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 where is my package you knob!!

LAST CUSTOMER:
@AmazonHelp Your one day deliver  is a joke.

====================================================================================================
ROW 115
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
home alone in the shower and the amazon delivery guy spent 10 mins beating on the door, shouting "oi" and has broken the lock @amazonhelp

LAST CUSTOMER:
@AmazonHelp sorry i was outside! you can call again now and it should be fine

====================================================================================================
ROW 116
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Bonjour, on peut se DM ?

LAST CUSTOMER:
@AmazonHelp je vous ai envoyé les infos en dm

====================================================================================================
ROW 117
Size: 9_plus_tweets | Customer turns: 20 | Support turns: 18
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I’m trying to buy something but I can’t use my gift card it won’t let me

LAST CUSTOMER:
@AmazonHelp Amazon

====================================================================================================
ROW 118
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Per @120540 6+2 fa 10. Non c’è più la rapidità e precisione di una volta. Nonostante Amazon Prime #amazon #ritardi #amazonprime https://t.co/cTbctKQxdV

LAST CUSTOMER:
@AmazonHelp Grazie per il consiglio ma ci rinuncio. Mi spiace perché funzionava bene Amazon. Ora non più. Almeno dalle mie parti. Peccato

====================================================================================================
ROW 119
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Prime "FREE One-Day Delivery"... will arrive in three days. Several items in this order and none of them can promise to make the "one-day delivery" that I've selected. Think I've seen this a few times recently @115830, is something up? https://t.co/GMwSxB18mr

LAST CUSTOMER:
@AmazonHelp Thanks @AmazonHelp. Guessed it was probably for this reason. Could you get this message onto the order page I screenshotted above? "Unlimited one-day delivery" is the headline promise of Prime so it's not very good to find this promise can be quietly dropped when inconvenient.

In [104]:
batch_4_labels = {
    90: "DELIVERY_DELAY",
    91: "ORDER_STATUS_OR_CANCELLATION",
    92: "OTHER_NON_SUPPORT",
    93: "PRODUCT_PROBLEM",
    94: "DELIVERY_DELAY",
    95: "DELIVERY_DELAY",
    96: "DIGITAL_CONTENT",
    97: "OTHER_NON_SUPPORT",
    98: "DELIVERY_DELAY",
    99: "DELIVERY_DELAY",
    100: "OTHER_NON_SUPPORT",
    101: "OTHER_NON_SUPPORT",
    102: "PAYMENT_BILLING",
    103: "OTHER_NON_SUPPORT",
    104: "OTHER_NON_SUPPORT",
    105: "WEBSITE_APP_TECHNICAL",
    106: "RETURN_REPLACEMENT_REFUND",
    107: "DELIVERY_DELAY",
    108: "DELIVERY_DELAY",
    109: "DELIVERY_DELAY",
    110: "PRODUCT_AVAILABILITY_INFORMATION",
    111: "PAYMENT_BILLING",
    112: "DELIVERY_DELAY",
    113: "PRODUCT_PROBLEM",
    114: "DELIVERY_DELAY",
    115: "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    116: "OTHER_NON_SUPPORT",
    117: "GIFT_CARD_PROMOTION",
    118: "DELIVERY_DELAY",
    119: "DELIVERY_DELAY",
}

for row_idx, label in batch_4_labels.items():
    taxonomy_audit.loc[row_idx, "intent_label"] = label

# Useful annotation notes
taxonomy_audit.loc[104, "annotation_notes"] = (
    "Legal/escalation complaint, but underlying support issue is insufficiently identifiable."
)

taxonomy_audit.loc[110, "annotation_notes"] = (
    "Digital product mentioned, but issue concerns advertised availability/release timing."
)

taxonomy_audit.loc[113, "annotation_notes"] = (
    "Return request is caused by poor product quality; primary intent is product problem."
)

taxonomy_audit.loc[115, "annotation_notes"] = (
    "Delivery-person behavior/access problem rather than delivery lateness."
)

taxonomy_audit.loc[116, "annotation_notes"] = (
    "DM routing request with no underlying issue visible."
)

taxonomy_audit.to_csv(audit_path, index=False)

print("Batch 4 saved.")
print("Annotated:", (taxonomy_audit["intent_label"].str.strip() != "").sum())
print("Remaining:", (taxonomy_audit["intent_label"].str.strip() == "").sum())

Batch 4 saved.
Annotated: 120
Remaining: 30

In [105]:
for i, row in taxonomy_audit.iloc[120:150].iterrows():
    print("=" * 100)
    print(f"ROW {i}")
    print(
        f"Size: {row['size_bucket']} | "
        f"Customer turns: {row['customer_turns']} | "
        f"Support turns: {row['support_turns']}"
    )
    print("-" * 100)
    print("FIRST CUSTOMER:")
    print(row["first_customer_message"])
    print("\nLAST CUSTOMER:")
    print(row["last_customer_message"])
    print()

====================================================================================================
ROW 120
Size: 5_to_8_tweets | Customer turns: 4 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp NO WHERE on the product page did it say the glasses couldn’t be returned. Now I’m stuck with a pair I can’t even use! 😡😡

LAST CUSTOMER:
@AmazonHelp Yes and they referred me back to Amazon

====================================================================================================
ROW 121
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp llevo casi un mes para devolver un producto. Vinieron a buscarlo y aún no he tenido noticias. En la app no sale ni registrada la recogida del paquete, cuando sí lo está. Necesito una solución... porque esto no es normal 😤

LAST CUSTOMER:
@AmazonHelp Sí, está marcado sólo el primer paso de recogida de la devolución programada con fecha del 8 de noviembre. Y desde entonces no se ha actualizado, pero el paquete vinieron a buscarlo hace mucho también.

====================================================================================================
ROW 122
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Amazon delivered used monitor scratches/broken seals!407-4263609-8713959. Amazing prime exp! #AmazonGreatIndianFestival #AmazonIndia #Amazon

LAST CUSTOMER:
Amazon delivered used monitor scratches/broken seals!407-4263609-8713959. Amazing prime exp! #AmazonGreatIndianFestival #AmazonIndia #Amazon

====================================================================================================
ROW 123
Size: 5_to_8_tweets | Customer turns: 4 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp another day and another misdelivered package by amazon logistics. This is the reason I’m canceling prime.

LAST CUSTOMER:
@AmazonHelp Form has been filled out. Another day and another messed up delivery.

====================================================================================================
ROW 124
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp @116090 Recieved Medium DuraSkin gloves &amp; they have yellow substance spilled on them. Ew. Might want to recall &amp; (1/2)

LAST CUSTOMER:
@AmazonHelp Will do.

====================================================================================================
ROW 125
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116928  segun esto me desbloquearon mi cuenta pero al hacer mi pedido no me deja!!! No entiendo entonces 😡😡

LAST CUSTOMER:
@AmazonHelp Si llame como 3 veces al centro de atencion de USA porque en el de españa no consigo el numero

====================================================================================================
ROW 126
Size: 5_to_8_tweets | Customer turns: 5 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@9583 @116090

If I have to go to the Lakeshore post office one more time to pick up parcels, I’m cancelling my Amazon Prime subscription.

LAST CUSTOMER:
@AmazonHelp I asked nice people at the post office if they could FedEx my parcels to me.

====================================================================================================
ROW 127
Size: 9_plus_tweets | Customer turns: 7 | Support turns: 6
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp with reference to my earlier tweet I haven't received any conversation from ur side @115821
I have already drop my details

LAST CUSTOMER:
@AmazonHelp  yes

====================================================================================================
ROW 128
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 got a message that my order was shipped yesterday. This morning I get a refund of the purchase amount on my card. Confused!!

LAST CUSTOMER:
@115850 got a message that my order was shipped yesterday. This morning I get a refund of the purchase amount on my card. Confused!!

====================================================================================================
ROW 129
Size: 3_to_4_tweets | Customer turns: 1 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp I have already filled up 3 forms for you on your site, so dont reply back asking me to fill one more form, you really don't care https://t.co/C7FL0rlywL

LAST CUSTOMER:
@AmazonHelp I have already filled up 3 forms for you on your site, so dont reply back asking me to fill one more form, you really don't care https://t.co/C7FL0rlywL

====================================================================================================
ROW 130
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
having an absolute nightmare with @115821

LAST CUSTOMER:
@AmazonHelp hope its good news 🤔

====================================================================================================
ROW 131
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
1/3: Serious racket of looting customers, @115850 - if u place bulk orders, shows order delivered for few when it isn't @120319

LAST CUSTOMER:
@AmazonHelp Already provided

====================================================================================================
ROW 132
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 I would like to complain against the delivery agent. He called me and I told him I’m home and 2 mins later it says delivered but no one came to my house https://t.co/hrpe3cs754

LAST CUSTOMER:
@115850 I would like to complain against the delivery agent. He called me and I told him I’m home and 2 mins later it says delivered but no one came to my house https://t.co/hrpe3cs754

====================================================================================================
ROW 133
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 7
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 Why are the orders not getting delivered after being OFD and are tagged as the said reasons? @AmazonHelp

3 orders stuck w/ this https://t.co/CjEUtlqh9e

LAST CUSTOMER:
@AmazonHelp I've had a couple of times! How many details you need for one resolution ?? I am amazed to see on the post-sale services! Need to buck-up!

====================================================================================================
ROW 134
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 My issue is contained in the below pic. Please look into it and reply. https://t.co/j9pvkXhaa5

LAST CUSTOMER:
@115850 My issue is contained in the below pic. Please look into it and reply. https://t.co/j9pvkXhaa5

====================================================================================================
ROW 135
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp can you help me fix my two factor authentication issue? Got a new phone but the website has been less than helpful in setting up 2FA on the new device.

LAST CUSTOMER:
@AmazonHelp I was able to disable it through the link you provided. Thanks for the help!

====================================================================================================
ROW 136
Size: 9_plus_tweets | Customer turns: 6 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116618 @amazonhelp Was looking forward to watch #beautyandthebaker #LehiyotIta ,but not there.   Supposed to be avail Oct 2.  #why

LAST CUSTOMER:
@AmazonHelp Did that last week, they have NO clue.  @116618 why don't you respond? #easyquestion #amazonfan

====================================================================================================
ROW 137
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently.

LAST CUSTOMER:
@AmazonHelp Have already share the order ID. U can check

====================================================================================================
ROW 138
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821  why do you offer prime shipping for a fee per month and items don't deliver on time

LAST CUSTOMER:
@AmazonHelp My package was schedule to deliver today by 8, after 8 I received notification that it could be within the next 3 days

====================================================================================================
ROW 139
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 4
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp  I need help I made an order on 12 November and until the 20 of November has not yet sent it, they were quick with the pay, but on slow shipping, I subscribed to amazon prime to see how it works, but I see that it was a loss of money It's not worth it.

LAST CUSTOMER:
@AmazonHelp I've been waiting for more than 2 weeks for the damn amazon package to come out

====================================================================================================
ROW 140
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116316 was nutzt einem AmazonPrime wenn man die Pakete nie pünktlich bekommt?! Erst 3-5 Tage später?! Danke an #Hermes!

LAST CUSTOMER:
@AmazonHelp Ja habe ich.

====================================================================================================
ROW 141
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
EU TÔ TREMENDO. @117086 EU TE AMO MUITO. https://t.co/Br5xFHHmTz

LAST CUSTOMER:
@AmazonHelp Tô só esperando aparecer mais alguma promoção do 9,90. Hahahahaha Mas continue, tá maravilhoso.

====================================================================================================
ROW 142
Size: 9_plus_tweets | Customer turns: 5 | Support turns: 5
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Um Amazon...if you are going to deliver...you need to have your customers be able to contact the delivery person directly! I want my stuff tonight!!! I should be able to contact them back directly! @115821

LAST CUSTOMER:
@AmazonHelp It has been resolved. Thank you

====================================================================================================
ROW 143
Size: 9_plus_tweets | Customer turns: 8 | Support turns: 8
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115821 Get your customer service under control. Cancelled my prime after having for years. Will never order with amazon again.

LAST CUSTOMER:
@AmazonHelp Okay, the reason I am complaining on Twitter, is because your customer service is not helping, is there some sort of management I can contact? Maybe they would actually care.

====================================================================================================
ROW 144
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp Any answer in this? https://t.co/gn18tV9b6e

LAST CUSTOMER:
@AmazonHelp Any answer in this? https://t.co/gn18tV9b6e

====================================================================================================
ROW 145
Size: 3_to_4_tweets | Customer turns: 2 | Support turns: 2
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
Don’t know why I bother ordering anything with @115821 anymore, they can never deliver on time 🙄

LAST CUSTOMER:
@AmazonHelp 28th November on the phone to customer services at the moment 🙄

====================================================================================================
ROW 146
Size: 5_to_8_tweets | Customer turns: 3 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@116875 ¿Qué hago, Amazon? Hice una devolución y @178440 no tiene idea de mi paquete. Selló la guía (aún la tengo) y dice que no lo he enviado.

LAST CUSTOMER:
@AmazonHelp  https://t.co/dImDiRcQeA

====================================================================================================
ROW 147
Size: 2_tweets | Customer turns: 1 | Support turns: 1
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 I have received package delivered notification but yet no package is received by me. Tracking # 216265638418

LAST CUSTOMER:
@115850 I have received package delivered notification but yet no package is received by me. Tracking # 216265638418

====================================================================================================
ROW 148
Size: 5_to_8_tweets | Customer turns: 4 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@AmazonHelp sumthing wrong in my account, lost prime membership, no order history, cust service not taking my calls. Manisha Chandnani

LAST CUSTOMER:
@AmazonHelp This is resolved. Thanks so much.

====================================================================================================
ROW 149
Size: 5_to_8_tweets | Customer turns: 5 | Support turns: 3
----------------------------------------------------------------------------------------------------
FIRST CUSTOMER:
@115850 very very bad product delivrd by amazon.my brother ordrd the lg phone Prodct output is not atleast 20 % wt dey gives in discrption

LAST CUSTOMER:
@AmazonHelp Your call executive  not respond well

Kindly arrange call back on 8826909077

In [106]:
batch_5_labels = {
    120: "RETURN_REPLACEMENT_REFUND",
    121: "RETURN_REPLACEMENT_REFUND",
    122: "PRODUCT_PROBLEM",
    123: "DELIVERY_MISSING_OR_MISDELIVERED",
    124: "PRODUCT_PROBLEM",
    125: "ACCOUNT_ACCESS_SECURITY",
    126: "DELIVERY_MISSING_OR_MISDELIVERED",
    127: "OTHER_NON_SUPPORT",
    128: "ORDER_STATUS_OR_CANCELLATION",
    129: "OTHER_NON_SUPPORT",
    130: "OTHER_NON_SUPPORT",
    131: "DELIVERY_MISSING_OR_MISDELIVERED",
    132: "DELIVERY_MISSING_OR_MISDELIVERED",
    133: "DELIVERY_DELAY",
    134: "OTHER_NON_SUPPORT",
    135: "ACCOUNT_ACCESS_SECURITY",
    136: "DIGITAL_CONTENT",
    137: "DELIVERY_MISSING_OR_MISDELIVERED",
    138: "DELIVERY_DELAY",
    139: "DELIVERY_DELAY",
    140: "DELIVERY_DELAY",
    141: "OTHER_NON_SUPPORT",
    142: "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    143: "OTHER_NON_SUPPORT",
    144: "OTHER_NON_SUPPORT",
    145: "DELIVERY_DELAY",
    146: "RETURN_REPLACEMENT_REFUND",
    147: "DELIVERY_MISSING_OR_MISDELIVERED",
    148: "ACCOUNT_ACCESS_SECURITY",
    149: "PRODUCT_PROBLEM",
}

for row_idx, label in batch_5_labels.items():
    taxonomy_audit.loc[row_idx, "intent_label"] = label

# Add useful notes
taxonomy_audit.loc[128, "annotation_notes"] = (
    "Shipment notification followed by refund; interpreted as order-state/cancellation issue."
)

taxonomy_audit.loc[125, "annotation_notes"] = (
    "Account reportedly unlocked but ordering remains blocked."
)

taxonomy_audit.loc[148, "annotation_notes"] = (
    "Prime/order-history disappearance is treated as account-state problem."
)

taxonomy_audit.loc[149, "annotation_notes"] = (
    "Poor product performance/quality is the underlying issue."
)

taxonomy_audit.to_csv(audit_path, index=False)

print("Batch 5 saved.")
print("Annotated:", (taxonomy_audit["intent_label"].str.strip() != "").sum())
print("Remaining:", (taxonomy_audit["intent_label"].str.strip() == "").sum())

Batch 5 saved.
Annotated: 150
Remaining: 0

Taxonomy audit analysis

In [107]:
import pandas as pd

# 1. Basic validation
print("=" * 80)
print("TAXONOMY AUDIT VALIDATION")
print("=" * 80)

print("Total examples:", len(taxonomy_audit))
print(
    "Annotated:",
    (taxonomy_audit["intent_label"].str.strip() != "").sum()
)
print(
    "Missing:",
    (taxonomy_audit["intent_label"].str.strip() == "").sum()
)

# 2. Intent distribution
intent_counts = (
    taxonomy_audit["intent_label"]
    .value_counts()
    .rename_axis("intent")
    .reset_index(name="count")
)

intent_counts["percentage"] = (
    intent_counts["count"] / len(taxonomy_audit) * 100
).round(2)

print("\n" + "=" * 80)
print("INTENT DISTRIBUTION")
print("=" * 80)

display(intent_counts)

# 3. Distribution sorted alphabetically
print("\n" + "=" * 80)
print("INTENT DISTRIBUTION — ALPHABETICAL")
print("=" * 80)

display(
    intent_counts.sort_values("intent").reset_index(drop=True)
)

# 4. Rare intents
print("\n" + "=" * 80)
print("RARE INTENTS (< 5 examples)")
print("=" * 80)

rare_intents = intent_counts[intent_counts["count"] < 5]

if len(rare_intents) == 0:
    print("No intent has fewer than 5 examples.")
else:
    display(rare_intents)


# 5. OTHER_NON_SUPPORT rate
other_count = (
    taxonomy_audit["intent_label"]
    .eq("OTHER_NON_SUPPORT")
    .sum()
)

other_rate = other_count / len(taxonomy_audit) * 100

print("\n" + "=" * 80)
print("OTHER_NON_SUPPORT")
print("=" * 80)
print(f"Count: {other_count}")
print(f"Rate: {other_rate:.2f}%")

# 6. Intent distribution by conversation size
print("\n" + "=" * 80)
print("INTENT × CONVERSATION SIZE")
print("=" * 80)

intent_by_bucket = pd.crosstab(
    taxonomy_audit["intent_label"],
    taxonomy_audit["size_bucket"]
)

display(intent_by_bucket)

# 7. Potential taxonomy-gap examples
print("\n" + "=" * 80)
print("EXAMPLES WITH TAXONOMY NOTES")
print("=" * 80)

noted = taxonomy_audit[
    taxonomy_audit["annotation_notes"].fillna("").str.strip() != ""
][
    [
        "first_customer_message",
        "intent_label",
        "annotation_notes"
    ]
]

display(noted)

# 8. Coverage
print("\n" + "=" * 80)
print("TAXONOMY COVERAGE")
print("=" * 80)

print(
    f"Every example received exactly one operational label: "
    f"{len(taxonomy_audit) == taxonomy_audit['intent_label'].notna().sum()}"
)

print(
    f"Examples classified as OTHER_NON_SUPPORT: "
    f"{other_count}/{len(taxonomy_audit)} ({other_rate:.2f}%)"
)

================================================================================
TAXONOMY AUDIT VALIDATION
================================================================================
Total examples: 150
Annotated: 150
Missing: 0

================================================================================
INTENT DISTRIBUTION
================================================================================

                              intent  count  percentage
0                     DELIVERY_DELAY     38       25.33
1                  OTHER_NON_SUPPORT     29       19.33
2                    PRODUCT_PROBLEM     17       11.33
3   DELIVERY_MISSING_OR_MISDELIVERED     13        8.67
4          RETURN_REPLACEMENT_REFUND      8        5.33
5       ORDER_STATUS_OR_CANCELLATION      7        4.67
6   PRODUCT_AVAILABILITY_INFORMATION      6        4.00
7                    DIGITAL_CONTENT      6        4.00
8                    PAYMENT_BILLING      5        3.33
9            ACCOUNT_ACCESS_SECURITY      5        3.33
10                  PRIME_MEMBERSHIP      5        3.33
11             WEBSITE_APP_TECHNICAL      4        2.67
12          DEVICE_TECHNICAL_SUPPORT      3        2.00
13               GIFT_CARD_PROMOTION      2        1.33
14  DELIVERY_ATTEMPT_OR_INSTRUCTIONS      2        1.33

================================================================================
INTENT DISTRIBUTION — ALPHABETICAL
================================================================================

                              intent  count  percentage
0            ACCOUNT_ACCESS_SECURITY      5        3.33
1   DELIVERY_ATTEMPT_OR_INSTRUCTIONS      2        1.33
2                     DELIVERY_DELAY     38       25.33
3   DELIVERY_MISSING_OR_MISDELIVERED     13        8.67
4           DEVICE_TECHNICAL_SUPPORT      3        2.00
5                    DIGITAL_CONTENT      6        4.00
6                GIFT_CARD_PROMOTION      2        1.33
7       ORDER_STATUS_OR_CANCELLATION      7        4.67
8                  OTHER_NON_SUPPORT     29       19.33
9                    PAYMENT_BILLING      5        3.33
10                  PRIME_MEMBERSHIP      5        3.33
11  PRODUCT_AVAILABILITY_INFORMATION      6        4.00
12                   PRODUCT_PROBLEM     17       11.33
13         RETURN_REPLACEMENT_REFUND      8        5.33
14             WEBSITE_APP_TECHNICAL      4        2.67

================================================================================
RARE INTENTS (< 5 examples)
================================================================================

                              intent  count  percentage
11             WEBSITE_APP_TECHNICAL      4        2.67
12          DEVICE_TECHNICAL_SUPPORT      3        2.00
13               GIFT_CARD_PROMOTION      2        1.33
14  DELIVERY_ATTEMPT_OR_INSTRUCTIONS      2        1.33

================================================================================
OTHER_NON_SUPPORT
================================================================================
Count: 29
Rate: 19.33%

================================================================================
INTENT × CONVERSATION SIZE
================================================================================

size_bucket,2_tweets,3_to_4_tweets,5_to_8_tweets,9_plus_tweets
intent_label,,,,
ACCOUNT_ACCESS_SECURITY,0,1,3,1
DELIVERY_ATTEMPT_OR_INSTRUCTIONS,0,0,0,2
DELIVERY_DELAY,7,9,12,10
DELIVERY_MISSING_OR_MISDELIVERED,4,1,6,2
DEVICE_TECHNICAL_SUPPORT,1,0,1,1
DIGITAL_CONTENT,2,1,0,3
GIFT_CARD_PROMOTION,0,1,0,1
ORDER_STATUS_OR_CANCELLATION,1,1,3,2
OTHER_NON_SUPPORT,14,7,2,6
PAYMENT_BILLING,0,2,1,2
PRIME_MEMBERSHIP,2,2,1,0
PRODUCT_AVAILABILITY_INFORMATION,0,2,2,2
PRODUCT_PROBLEM,4,7,1,5
RETURN_REPLACEMENT_REFUND,0,3,4,1
WEBSITE_APP_TECHNICAL,3,0,1,0

================================================================================
EXAMPLES WITH TAXONOMY NOTES
================================================================================

,first_customer_message,intent_label,annotation_notes
14,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,OTHER_NON_SUPPORT,Does not fit current taxonomy cleanly; possible seller-support intent.
16,@115850 Your sale advertisement today. Trivia: Find the mistake in the image. U need better testers to validate content. Can I Join you? https://t.co/xMojPqCjvL,OTHER_NON_SUPPORT,Advertisement/content feedback rather than a defined support issue.
21,@115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162,OTHER_NON_SUPPORT,General customer-service complaint without a specific underlying issue.
40,@AmazonHelp plse help .check DM and help quickly,OTHER_NON_SUPPORT,Support/contact follow-up but underlying issue is not identifiable.
44,@115830 it's an absolute joke I pay for prime and now you are charging a delivery fee that was free with prime!!! Ragging 😡 #Amazon #AmazonPrime,PRIME_MEMBERSHIP,"Prime benefit/fee issue, therefore Prime Membership rather than delivery delay."
45,"@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: ""preparando envío""",ORDER_STATUS_OR_CANCELLATION,Order lifecycle problem; later becomes shipping eligibility issue.
55,@AmazonHelp had two packages scheduled to arrive by 8pm from ur driver. 8:47 pm and no packages. Should I assume they are not coming today?,DELIVERY_DELAY,Initial issue is delayed delivery; eventual successful delivery does not change primary intent.
64,@115830 #lookout #everyone #amazonprime #charges #noconfrimation 🛒🧐,PAYMENT_BILLING,Transaction/charge confirmation issue; resolved by help line.
68,@AmazonHelp I received ANOTHER damaged #AmazonSubscribeAndSave delivered by @118706 it was clearly marked as HEAVY &amp; delivered on its side.,PRODUCT_PROBLEM,Repeated damaged delivery; shipper avoidance is secondary.
80,"@115850 Amazon prime is not prime anymore, even the prime products take 4-5 days to deliver. :(",DELIVERY_DELAY,"Prime mentioned, but actual problem is delivery time/estimate."
87,@AmazonHelp this massive box for two nail varnishes is a bit much surely? 😂 https://t.co/aJBQUzsd1N,OTHER_NON_SUPPORT,Packaging criticism without damage or concrete support request.
88,"Excited to get an early birthday present today but holy crap @115821, that's the least environmentally conscious package I've ever seen! https://t.co/wXaEbdbmun",OTHER_NON_SUPPORT,Environmental packaging criticism; no product defect.
104,"Hw to irritate n frustrate sme1,learn frm @AmazonHelp \nFiled a case in court,hope thy respond to the court notice",OTHER_NON_SUPPORT,"Legal/escalation complaint, but underlying support issue is insufficiently identifiable."
110,"@130626 Ordered delux edition on @115821 but it says I won’t receive my order until Tuesday, the 17? Anything to suggest so I can receive the game 4 days early as advertised?",PRODUCT_AVAILABILITY_INFORMATION,"Digital product mentioned, but issue concerns advertised availability/release timing."
113,(1) Bought @1469 K8 from Amazon. Pathetic camera quality. Wanted to return it and buy another phone. @115850 replaced instead of,PRODUCT_PROBLEM,Return request is caused by poor product quality; primary intent is product problem.
115,"home alone in the shower and the amazon delivery guy spent 10 mins beating on the door, shouting ""oi"" and has broken the lock @amazonhelp",DELIVERY_ATTEMPT_OR_INSTRUCTIONS,Delivery-person behavior/access problem rather than delivery lateness.
116,"@AmazonHelp Bonjour, on peut se DM ?",OTHER_NON_SUPPORT,DM routing request with no underlying issue visible.
125,@116928 segun esto me desbloquearon mi cuenta pero al hacer mi pedido no me deja!!! No entiendo entonces 😡😡,ACCOUNT_ACCESS_SECURITY,Account reportedly unlocked but ordering remains blocked.
128,@115850 got a message that my order was shipped yesterday. This morning I get a refund of the purchase amount on my card. Confused!!,ORDER_STATUS_OR_CANCELLATION,Shipment notification followed by refund; interpreted as order-state/cancellation issue.
148,"@AmazonHelp sumthing wrong in my account, lost prime membership, no order history, cust service not taking my calls. Manisha Chandnani",ACCOUNT_ACCESS_SECURITY,Prime/order-history disappearance is treated as account-state problem.
149,@115850 very very bad product delivrd by amazon.my brother ordrd the lg phone Prodct output is not atleast 20 % wt dey gives in discrption,PRODUCT_PROBLEM,Poor product performance/quality is the underlying issue.

================================================================================
TAXONOMY COVERAGE
================================================================================
Every example received exactly one operational label: True
Examples classified as OTHER_NON_SUPPORT: 29/150 (19.33%)

LOCK the AmazonHelp intent taxonomy

In [108]:
# Add the locked taxonomy to the project
from pathlib import Path
import json

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

FINAL_INTENTS = [
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "ORDER_STATUS_OR_CANCELLATION",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_PROBLEM",
    "PAYMENT_BILLING",
    "PRIME_MEMBERSHIP",
    "ACCOUNT_ACCESS_SECURITY",
    "GIFT_CARD_PROMOTION",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DIGITAL_CONTENT",
    "DEVICE_TECHNICAL_SUPPORT",
    "WEBSITE_APP_TECHNICAL",
    "OTHER_NON_SUPPORT",
]

INTENT_DEFINITIONS = {
    "DELIVERY_DELAY":
        "Shipment is late, delayed, or misses the expected delivery window.",

    "DELIVERY_MISSING_OR_MISDELIVERED":
        "Package is marked delivered but not received, or delivered to the wrong location.",

    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS":
        "Delivery attempt behavior, driver behavior, delivery instructions, or delivery location/slot issues.",

    "ORDER_STATUS_OR_CANCELLATION":
        "Order lifecycle status, cancellation, dispatch, or preorder issues.",

    "RETURN_REPLACEMENT_REFUND":
        "Return, replacement, or refund process/status.",

    "PRODUCT_PROBLEM":
        "Product is damaged, defective, wrong, incomplete, used, counterfeit, or otherwise has a product-quality problem.",

    "PAYMENT_BILLING":
        "Payment method, card, unexpected charge, billing, or Amazon Pay issue.",

    "PRIME_MEMBERSHIP":
        "Prime signup, renewal, cancellation, membership status, or Prime benefits.",

    "ACCOUNT_ACCESS_SECURITY":
        "Login, password, locked account, hacked account, authentication, or security issue.",

    "GIFT_CARD_PROMOTION":
        "Gift card, coupon, promotion, cashback, or promotional-credit issue.",

    "PRODUCT_AVAILABILITY_INFORMATION":
        "Product stock, availability, pricing, shipping eligibility, or general product information.",

    "DIGITAL_CONTENT":
        "Prime Video, Amazon Music, Kindle content, or other digital-content access/availability.",

    "DEVICE_TECHNICAL_SUPPORT":
        "Kindle, Fire TV, Fire Stick, Echo, Alexa, or other Amazon-device technical issue.",

    "WEBSITE_APP_TECHNICAL":
        "Amazon website, mobile app, checkout, UI, form, or technical site/app error.",

    "OTHER_NON_SUPPORT":
        "Non-support/social content, insufficient information, generic complaints, marketing, or cases that do not fit another operational intent.",
}

taxonomy_config = {
    "brand": "AmazonHelp",
    "taxonomy_version": "v1",
    "status": "locked",
    "audit_size": 150,
    "intents": FINAL_INTENTS,
    "definitions": INTENT_DEFINITIONS,
}

taxonomy_path = PROCESSED_DIR / "amazonhelp_intent_taxonomy_v1.json"

with open(taxonomy_path, "w", encoding="utf-8") as f:
    json.dump(taxonomy_config, f, indent=2, ensure_ascii=False)

print("=" * 80)
print("FINAL TAXONOMY LOCKED")
print("=" * 80)
print("Brand:", taxonomy_config["brand"])
print("Version:", taxonomy_config["taxonomy_version"])
print("Status:", taxonomy_config["status"])
print("Number of intents:", len(FINAL_INTENTS))
print("Audit examples:", taxonomy_config["audit_size"])
print("Saved to:", taxonomy_path)

================================================================================
FINAL TAXONOMY LOCKED
================================================================================
Brand: AmazonHelp
Version: v1
Status: locked
Number of intents: 15
Audit examples: 150
Saved to: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_taxonomy_v1.json

need to create train / validation / test splits at the conversation level, not tweet level.

one tweet from that conversation goes into training and another goes into test, the classifier can effectively see the same issue during training and testing. 
That would make test score misleadingly high.

One conversation = one split.

In [109]:
# INSPECT EXISTING CONVERSATION DATA

print("=" * 80)
print("TWCS")
print("=" * 80)

print("Rows:", len(twcs))
print("Has conversation_id:", "conversation_id" in twcs.columns)
print("Has support_account:", "support_account" in twcs.columns)

print("\nTWCS columns:")
print(list(twcs.columns))


print("\n" + "=" * 80)
print("RESOLUTION EPISODES")
print("=" * 80)

print("Rows:", len(resolution_episodes))
print("Columns:")
print(list(resolution_episodes.columns))

print("\nSupport accounts:")
if "support_account" in resolution_episodes.columns:
    print(
        resolution_episodes["support_account"]
        .value_counts()
        .head(15)
    )

print("\nAmazonHelp rows:")
if "support_account" in resolution_episodes.columns:
    print(
        "AmazonHelp:",
        (
            resolution_episodes["support_account"]
            .eq("AmazonHelp")
            .sum()
        )
    )

print("\n" + "=" * 80)
print("AMAZON CONVERSATIONS")
print("=" * 80)

print("Exists:", "amazon_conversations" in globals())

if "amazon_conversations" in globals():
    print("Rows:", len(amazon_conversations))
    print("Columns:")
    print(list(amazon_conversations.columns))

================================================================================
TWCS
================================================================================
Rows: 2811774
Has conversation_id: True
Has support_account: False

TWCS columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'created_at_parsed', 'conversation_id', 'conversation_root_type']

================================================================================
RESOLUTION EPISODES
================================================================================
Rows: 192718
Columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

Support accounts:
support_account
AmazonHelp      82246
AppleSupport    80552
Tesco           16566
XboxSupport     13354
Name: count, dtype: int64

AmazonHelp rows:
AmazonHelp: 82246

================================================================================
AMAZON CONVERSATIONS
================================================================================
Exists: True
Rows: 82246
Columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

In [110]:
# INSPECT RESOLUTION EPISODE IDENTITY

print("=" * 80)
print("RESOLUTION EPISODE IDENTITY CHECK")
print("=" * 80)

print("resolution_episodes columns:")
print(list(resolution_episodes.columns))

print("\nAmazonHelp columns:")
print(list(amazon_conversations.columns))

# Check whether any hidden/index-like information survived
print("\nIndex information:")
print("resolution_episodes index:", resolution_episodes.index)
print("amazon_conversations index:", amazon_conversations.index)

# Check whether conversation_text is duplicated within AmazonHelp
amazon_text_counts = (
    amazon_conversations["conversation_text"]
    .value_counts()
)

duplicate_texts = amazon_text_counts[
    amazon_text_counts > 1
]

print("\n" + "=" * 80)
print("DUPLICATE CONVERSATION TEXT")
print("=" * 80)

print(
    "Unique conversation texts:",
    amazon_conversations["conversation_text"].nunique()
)

print(
    "Duplicated conversation texts:",
    len(duplicate_texts)
)

print(
    "AmazonHelp rows participating in duplicate texts:",
    int(duplicate_texts.sum())
)

if len(duplicate_texts) > 0:
    print("\nExample duplicated conversation text:")
    example_text = duplicate_texts.index[0]

    display(
        amazon_conversations[
            amazon_conversations["conversation_text"]
            == example_text
        ][
            [
                "conversation_text",
                "conversation_size",
                "customer_turns",
                "support_turns",
                "start_time",
                "end_time",
                "support_account"
            ]
        ]
    )

# Check whether start/end timestamps + size are unique enough
identity_cols = [
    "conversation_text",
    "conversation_size",
    "customer_turns",
    "support_turns",
    "start_time",
    "end_time"
]

print("\n" + "=" * 80)
print("COMPOSITE IDENTITY CHECK")
print("=" * 80)

print(
    "Unique composite records:",
    amazon_conversations[identity_cols].drop_duplicates().shape[0]
)

print(
    "Total AmazonHelp records:",
    len(amazon_conversations)
)

================================================================================
RESOLUTION EPISODE IDENTITY CHECK
================================================================================
resolution_episodes columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

AmazonHelp columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

Index information:
resolution_episodes index: Index([    272,     277,     318,     320,     323,     325,     617,     621,
           624,     630,
       ...
       2987738, 2987740, 2987742, 2987815, 2987818, 2987820, 2987822, 2987901,
       2987903, 2987939],
      dtype='int64', name='conversation_id', length=192718)
amazon_conversations index: Index([    272,     325,     617,     621,     624,     630,     632,     634,
           636,     643,
       ...
       2987738, 2987740, 2987742, 2987815, 2987818, 2987820, 2987822, 2987901,
       2987903, 2987939],
      dtype='int64', name='conversation_id', length=82246)

================================================================================
DUPLICATE CONVERSATION TEXT
================================================================================
Unique conversation texts: 82246
Duplicated conversation texts: 0
AmazonHelp rows participating in duplicate texts: 0

================================================================================
COMPOSITE IDENTITY CHECK
================================================================================
Unique composite records: 82246
Total AmazonHelp records: 82246

In [111]:
# RESTORE conversation_id FROM INDEX

import pandas as pd
from pathlib import Path

print("=" * 80)
print("RESTORING conversation_id")
print("=" * 80)

# ------------------------------------------------------------
# 1. Copy the existing AmazonHelp dataset
# ------------------------------------------------------------

amazon_conversations = amazon_conversations.copy()

# ------------------------------------------------------------
# 2. The index is already conversation_id
# ------------------------------------------------------------

print("Index name:", amazon_conversations.index.name)

if amazon_conversations.index.name != "conversation_id":
    raise ValueError(
        "Expected the AmazonHelp dataframe index to be "
        "conversation_id."
    )

# Convert the index into an explicit column
amazon_conversations = amazon_conversations.reset_index()

# ------------------------------------------------------------
# 3. Validate
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("VALIDATION")
print("=" * 80)

print("Rows:", f"{len(amazon_conversations):,}")
print(
    "Unique conversation IDs:",
    f"{amazon_conversations['conversation_id'].nunique():,}"
)

print(
    "Missing conversation IDs:",
    amazon_conversations["conversation_id"].isna().sum()
)

print(
    "Duplicate conversation IDs:",
    amazon_conversations["conversation_id"].duplicated().sum()
)

print(
    "Support accounts:",
    amazon_conversations["support_account"].unique()
)

# ------------------------------------------------------------
# 4. Assertions
# ------------------------------------------------------------

assert len(amazon_conversations) == 82_246
assert amazon_conversations["conversation_id"].notna().all()
assert amazon_conversations["conversation_id"].is_unique
assert amazon_conversations["support_account"].eq("AmazonHelp").all()

print("\n✓ 82,246 unique AmazonHelp conversations recovered.")
print("✓ Every conversation has a valid conversation_id.")
print("✓ No duplicate conversation IDs.")
print("✓ Every record belongs to AmazonHelp.")

# ------------------------------------------------------------
# 5. Save corrected dataset
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

amazon_path = (
    PROCESSED_DIR /
    "amazonhelp_conversations_with_ids.csv"
)

amazon_conversations.to_csv(
    amazon_path,
    index=False,
    encoding="utf-8"
)

print("\nSaved:")
print(amazon_path)

print("\nColumns:")
print(list(amazon_conversations.columns))

================================================================================
RESTORING conversation_id
================================================================================
Index name: conversation_id

================================================================================
VALIDATION
================================================================================
Rows: 82,246
Unique conversation IDs: 82,246
Missing conversation IDs: 0
Duplicate conversation IDs: 0
Support accounts: ['AmazonHelp']

✓ 82,246 unique AmazonHelp conversations recovered.
✓ Every conversation has a valid conversation_id.
✓ No duplicate conversation IDs.
✓ Every record belongs to AmazonHelp.

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversations_with_ids.csv

Columns:
['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

Conversation-level Train / Validation / Test split

In [112]:
# LEAKAGE-SAFE CONVERSATION-LEVEL SPLIT

import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

print("=" * 80)
print("CONVERSATION-LEVEL DATASET SPLIT")
print("=" * 80)

# ------------------------------------------------------------
# 1. Work from the corrected AmazonHelp dataset
# ------------------------------------------------------------

amazon = amazon_conversations.copy()

required_columns = [
    "conversation_id",
    "conversation_text",
    "support_account"
]

missing_columns = [
    col for col in required_columns
    if col not in amazon.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# ------------------------------------------------------------
# 2. Basic identity checks
# ------------------------------------------------------------

assert amazon["conversation_id"].notna().all()
assert amazon["conversation_id"].is_unique
assert amazon["support_account"].eq("AmazonHelp").all()

print("Total conversations:", f"{len(amazon):,}")
print(
    "Unique conversation IDs:",
    f"{amazon['conversation_id'].nunique():,}"
)

# ------------------------------------------------------------
# 3. Split conversation IDs
# ------------------------------------------------------------

all_ids = amazon["conversation_id"].to_numpy()

train_ids, temp_ids = train_test_split(
    all_ids,
    test_size=0.20,
    random_state=RANDOM_STATE
)

validation_ids, test_ids = train_test_split(
    temp_ids,
    test_size=0.50,
    random_state=RANDOM_STATE
)

# ------------------------------------------------------------
# 4. Assign split
# ------------------------------------------------------------

split_map = {}

for cid in train_ids:
    split_map[cid] = "train"

for cid in validation_ids:
    split_map[cid] = "validation"

for cid in test_ids:
    split_map[cid] = "test"

amazon["split"] = amazon["conversation_id"].map(split_map)

# ------------------------------------------------------------
# 5. Validate split assignment
# ------------------------------------------------------------

assert amazon["split"].notna().all()

train = amazon[amazon["split"] == "train"].copy()
validation = amazon[amazon["split"] == "validation"].copy()
test = amazon[amazon["split"] == "test"].copy()

print("\n" + "=" * 80)
print("SPLIT SIZES")
print("=" * 80)

print(
    f"Train:      {len(train):,} "
    f"({len(train) / len(amazon) * 100:.2f}%)"
)

print(
    f"Validation: {len(validation):,} "
    f"({len(validation) / len(amazon) * 100:.2f}%)"
)

print(
    f"Test:       {len(test):,} "
    f"({len(test) / len(amazon) * 100:.2f}%)"
)

# ------------------------------------------------------------
# 6. CRITICAL LEAKAGE CHECK
# ------------------------------------------------------------

train_ids_set = set(train["conversation_id"])
validation_ids_set = set(validation["conversation_id"])
test_ids_set = set(test["conversation_id"])

train_validation_overlap = (
    train_ids_set & validation_ids_set
)

train_test_overlap = (
    train_ids_set & test_ids_set
)

validation_test_overlap = (
    validation_ids_set & test_ids_set
)

print("\n" + "=" * 80)
print("CONVERSATION LEAKAGE CHECK")
print("=" * 80)

print(
    "Train ∩ Validation:",
    len(train_validation_overlap)
)

print(
    "Train ∩ Test:",
    len(train_test_overlap)
)

print(
    "Validation ∩ Test:",
    len(validation_test_overlap)
)

assert len(train_validation_overlap) == 0
assert len(train_test_overlap) == 0
assert len(validation_test_overlap) == 0

print("\n✓ ZERO conversation overlap across splits.")

# ------------------------------------------------------------
# 7. Check that all conversations are assigned exactly once
# ------------------------------------------------------------

split_counts = amazon["split"].value_counts()

assert split_counts.sum() == len(amazon)

print("\nAll conversations assigned exactly once: ✓")

# ------------------------------------------------------------
# 8. Save
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

split_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits.csv"
)

amazon.to_csv(
    split_path,
    index=False,
    encoding="utf-8"
)

print("\nSaved:")
print(split_path)

# ------------------------------------------------------------
# 9. Final summary
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP COMPLETE")
print("=" * 80)

print("Train conversations:     ", f"{len(train):,}")
print("Validation conversations:", f"{len(validation):,}")
print("Test conversations:      ", f"{len(test):,}")
print("Total:                   ", f"{len(amazon):,}")

================================================================================
CONVERSATION-LEVEL DATASET SPLIT
================================================================================
Total conversations: 82,246
Unique conversation IDs: 82,246

================================================================================
SPLIT SIZES
================================================================================
Train:      65,796 (80.00%)
Validation: 8,225 (10.00%)
Test:       8,225 (10.00%)

================================================================================
CONVERSATION LEAKAGE CHECK
================================================================================
Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

✓ ZERO conversation overlap across splits.

All conversations assigned exactly once: ✓

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits.csv

================================================================================
STEP COMPLETE
================================================================================
Train conversations:      65,796
Validation conversations: 8,225
Test conversations:       8,225
Total:                    82,246

In [113]:
# CHECK GOLDEN AUDIT vs DATA SPLITS

import pandas as pd

print("=" * 80)
print("GOLDEN AUDIT / SPLIT CHECK")
print("=" * 80)

# ------------------------------------------------------------
# Load the saved split
# ------------------------------------------------------------

split_df = pd.read_csv(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits.csv"
)

print("Split rows:", f"{len(split_df):,}")

# ------------------------------------------------------------
# Inspect audit columns
# ------------------------------------------------------------

print("\nAudit rows:", len(taxonomy_audit))
print("Audit columns:")
print(list(taxonomy_audit.columns))

# ------------------------------------------------------------
# We intentionally do NOT assume the audit has conversation_id.
# Check whether it does.
# ------------------------------------------------------------

print("\nAudit has conversation_id:",
      "conversation_id" in taxonomy_audit.columns)

# ------------------------------------------------------------
# Compare using conversation text ONLY as a diagnostic.
# We will NOT use it to assign IDs.
# ------------------------------------------------------------

audit_texts = set(
    taxonomy_audit["conversation_text"]
    .astype(str)
)

split_df["is_taxonomy_audit"] = (
    split_df["conversation_text"]
    .astype(str)
    .isin(audit_texts)
)

audit_matches = split_df[
    split_df["is_taxonomy_audit"]
].copy()

print("\n" + "=" * 80)
print("AUDIT MATCH CHECK")
print("=" * 80)

print(
    "Audit examples found in split:",
    len(audit_matches)
)

print(
    "Expected audit examples:",
    len(taxonomy_audit)
)

if len(audit_matches) == len(taxonomy_audit):
    print("✓ All audit examples are present in the split.")
else:
    print(
        "⚠ Match count differs. Do not proceed to labeling yet."
    )

# ------------------------------------------------------------
# Show split distribution of matched audit examples
# ------------------------------------------------------------

if len(audit_matches) > 0:
    print("\nAudit examples by split:")
    print(
        audit_matches["split"]
        .value_counts()
    )

# ------------------------------------------------------------
# Show whether any audit example is in TEST
# ------------------------------------------------------------

test_audit = audit_matches[
    audit_matches["split"] == "test"
]

print(
    "\nAudit examples currently in TEST:",
    len(test_audit)
)

print(
    "Audit examples currently outside TEST:",
    len(audit_matches) - len(test_audit)
)

================================================================================
GOLDEN AUDIT / SPLIT CHECK
================================================================================
Split rows: 82,246

Audit rows: 150
Audit columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'intent_label', 'annotation_notes', 'annotator']

Audit has conversation_id: False

================================================================================
AUDIT MATCH CHECK
================================================================================
Audit examples found in split: 150
Expected audit examples: 150
✓ All audit examples are present in the split.

Audit examples by split:
split
train         118
test           20
validation     12
Name: count, dtype: int64

Audit examples currently in TEST: 20
Audit examples currently outside TEST: 130

FREEZE TAXONOMY AUDIT OUT OF MODEL DEVELOPMENT

In [114]:
import pandas as pd
from pathlib import Path

print("=" * 80)
print("FREEZING TAXONOMY AUDIT EXAMPLES")
print("=" * 80)

# ------------------------------------------------------------
# 1. Load the conversation-level split
# ------------------------------------------------------------

split_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed"
    r"\amazonhelp_conversation_splits.csv"
)

split_df = pd.read_csv(split_path)

# ------------------------------------------------------------
# 2. Identify taxonomy-audit conversations
# ------------------------------------------------------------

audit_texts = set(
    taxonomy_audit["conversation_text"]
    .astype(str)
)

split_df["is_taxonomy_audit"] = (
    split_df["conversation_text"]
    .astype(str)
    .isin(audit_texts)
)

# ------------------------------------------------------------
# 3. Validate exactly 150
# ------------------------------------------------------------

audit_count = split_df["is_taxonomy_audit"].sum()

print("Taxonomy audit examples found:", audit_count)

assert audit_count == 150

print("✓ Exactly 150 audit examples identified.")

# ------------------------------------------------------------
# 4. Examine their current split locations
# ------------------------------------------------------------

print("\nAudit examples by split:")

display(
    pd.crosstab(
        split_df["split"],
        split_df["is_taxonomy_audit"]
    )
)

# ------------------------------------------------------------
# 5. Create development-safe pools
# ------------------------------------------------------------

development_train = split_df[
    (split_df["split"] == "train") &
    (~split_df["is_taxonomy_audit"])
].copy()

development_validation = split_df[
    (split_df["split"] == "validation") &
    (~split_df["is_taxonomy_audit"])
].copy()

# Test remains completely untouched.
final_test = split_df[
    split_df["split"] == "test"
].copy()

print("\n" + "=" * 80)
print("DEVELOPMENT POOLS")
print("=" * 80)

print(
    "Training conversations available:",
    f"{len(development_train):,}"
)

print(
    "Validation conversations available:",
    f"{len(development_validation):,}"
)

print(
    "Test conversations:",
    f"{len(final_test):,}"
)

# ------------------------------------------------------------
# 6. Make sure no audit examples remain in development
# ------------------------------------------------------------

assert development_train["is_taxonomy_audit"].sum() == 0
assert development_validation["is_taxonomy_audit"].sum() == 0

print("\n✓ No taxonomy-audit examples in training.")
print("✓ No taxonomy-audit examples in validation.")

# ------------------------------------------------------------
# 7. Save frozen split metadata
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

frozen_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v2.csv"
)

split_df.to_csv(
    frozen_path,
    index=False,
    encoding="utf-8"
)

print("\nSaved:")
print(frozen_path)

================================================================================
FREEZING TAXONOMY AUDIT EXAMPLES
================================================================================
Taxonomy audit examples found: 150
✓ Exactly 150 audit examples identified.

Audit examples by split:

is_taxonomy_audit  False  True
split
test                8205     20
train              65678    118
validation          8213     12

================================================================================
DEVELOPMENT POOLS
================================================================================
Training conversations available: 65,678
Validation conversations available: 8,213
Test conversations: 8,225

✓ No taxonomy-audit examples in training.
✓ No taxonomy-audit examples in validation.

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits_v2.csv

SILVER-LABELING HEURISTIC

In [115]:
import re
import pandas as pd

FINAL_INTENTS = [
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "ORDER_STATUS_OR_CANCELLATION",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_PROBLEM",
    "PAYMENT_BILLING",
    "PRIME_MEMBERSHIP",
    "ACCOUNT_ACCESS_SECURITY",
    "GIFT_CARD_PROMOTION",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DIGITAL_CONTENT",
    "DEVICE_TECHNICAL_SUPPORT",
    "WEBSITE_APP_TECHNICAL",
    "OTHER_NON_SUPPORT",
]

PATTERNS = {
    "DELIVERY_MISSING_OR_MISDELIVERED": [
        r"\bdelivered\b",
        r"\bpackage\b.*\bmissing\b",
        r"\bparcel\b.*\bmissing\b",
        r"\bnot received\b",
        r"\bnever received\b",
        r"\bwrong address\b",
        r"\bwrong house\b",
        r"\bneighbor\b",
        r"\bneighbour\b",
        r"\bmisdelivered\b",
    ],

    "DELIVERY_DELAY": [
        r"\blate\b",
        r"\bdelayed\b",
        r"\bdelay\b",
        r"\boverdue\b",
        r"\bnot arrived\b",
        r"\bhasn't arrived\b",
        r"\bhasnt arrived\b",
        r"\bstill waiting\b",
        r"\bdelivery date\b",
        r"\bdelivery time\b",
    ],

    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS": [
        r"\bdelivery attempt\b",
        r"\bfailed attempt\b",
        r"\bdriver\b",
        r"\bcourier\b",
        r"\bdelivery instructions\b",
        r"\bleave .* door\b",
        r"\bleave .* porch\b",
        r"\bdelivery slot\b",
        r"\bdelivery person\b",
    ],

    "RETURN_REPLACEMENT_REFUND": [
        r"\breturn\b",
        r"\brefund\b",
        r"\breplacement\b",
        r"\breplace\b",
        r"\bexchange\b",
        r"\breturn label\b",
        r"\breturning\b",
    ],

    "PRODUCT_PROBLEM": [
        r"\bdamaged\b",
        r"\bbroken\b",
        r"\bdefective\b",
        r"\bfaulty\b",
        r"\bwrong item\b",
        r"\bwrong product\b",
        r"\bmissing parts\b",
        r"\bdoesn't work\b",
        r"\bdoesnt work\b",
        r"\bnot working\b",
        r"\bpoor quality\b",
        r"\bquality\b",
        r"\bscratched\b",
    ],

    "PAYMENT_BILLING": [
        r"\bcharged\b",
        r"\bcharge\b",
        r"\bbilling\b",
        r"\bpayment\b",
        r"\bcredit card\b",
        r"\bdebit card\b",
        r"\bpaypal\b",
        r"\bamazon pay\b",
    ],

    "PRIME_MEMBERSHIP": [
        r"\bprime\b",
        r"\bmembership\b",
        r"\bprime member\b",
        r"\bprime membership\b",
        r"\bprime trial\b",
        r"\bprime renewal\b",
    ],

    "ACCOUNT_ACCESS_SECURITY": [
        r"\blogin\b",
        r"\blog in\b",
        r"\bsign in\b",
        r"\bsign-in\b",
        r"\bpassword\b",
        r"\baccount locked\b",
        r"\blocked out\b",
        r"\bhacked\b",
        r"\bsecurity\b",
        r"\b2fa\b",
        r"\btwo factor\b",
        r"\bverification code\b",
    ],

    "GIFT_CARD_PROMOTION": [
        r"\bgift card\b",
        r"\bgiftcard\b",
        r"\bcoupon\b",
        r"\bpromo\b",
        r"\bpromotion\b",
        r"\bdiscount\b",
        r"\bcashback\b",
        r"\bvoucher\b",
    ],

    "PRODUCT_AVAILABILITY_INFORMATION": [
        r"\bin stock\b",
        r"\bout of stock\b",
        r"\bavailable\b",
        r"\bavailability\b",
        r"\bprice\b",
        r"\bcost\b",
        r"\bhow much\b",
    ],

    "DIGITAL_CONTENT": [
        r"\bprime video\b",
        r"\bamazon video\b",
        r"\bamazon music\b",
        r"\bkindle book\b",
        r"\be[- ]?book\b",
        r"\bstreaming\b",
    ],

    "DEVICE_TECHNICAL_SUPPORT": [
        r"\bkindle\b",
        r"\becho\b",
        r"\balexa\b",
        r"\bfire tv\b",
        r"\bfire stick\b",
        r"\bfirestick\b",
        r"\btablet\b",
        r"\bdevice\b",
    ],

    "WEBSITE_APP_TECHNICAL": [
        r"\bapp\b",
        r"\bwebsite\b",
        r"\bsite\b",
        r"\bcheckout\b",
        r"\berror\b",
        r"\berror message\b",
        r"\bbutton\b",
        r"\bloading\b",
    ],

    "ORDER_STATUS_OR_CANCELLATION": [
        r"\border status\b",
        r"\bcancel\b",
        r"\bcancelled\b",
        r"\bcanceled\b",
        r"\bdispatch\b",
        r"\bshipped\b",
        r"\bshipment\b",
        r"\border\b.*\bstatus\b",
    ],
}


def predict_intent(text):

    text = str(text).lower()

    scores = {}

    for intent, patterns in PATTERNS.items():

        score = sum(
            bool(re.search(pattern, text))
            for pattern in patterns
        )

        scores[intent] = score

    best_intent = max(scores, key=scores.get)
    best_score = scores[best_intent]

    if best_score == 0:
        return "OTHER_NON_SUPPORT"

    tied = [
        intent
        for intent, score in scores.items()
        if score == best_score
    ]

    if len(tied) > 1:
        return "OTHER_NON_SUPPORT"

    return best_intent


# ------------------------------------------------------------
# Generate predictions
# ------------------------------------------------------------

audit_eval = taxonomy_audit.copy()

audit_eval["heuristic_prediction"] = (
    audit_eval["first_customer_message"]
    .fillna("")
    .map(predict_intent)
)

print("=" * 80)
print("HEURISTIC PREDICTIONS CREATED")
print("=" * 80)

print("Examples:", len(audit_eval))
print(
    "Predicted labels:",
    audit_eval["heuristic_prediction"].nunique()
)

display(
    audit_eval[
        [
            "first_customer_message",
            "intent_label",
            "heuristic_prediction"
        ]
    ].head(20)
)

================================================================================
HEURISTIC PREDICTIONS CREATED
================================================================================
Examples: 150
Predicted labels: 15

,first_customer_message,intent_label,heuristic_prediction
0,@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
1,@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52,OTHER_NON_SUPPORT,OTHER_NON_SUPPORT
2,"You guys should really Google the word ""Guaranteed"" before giving me an arrival date. Just terrible this year. #Amazon @115821 #late #guess?",DELIVERY_DELAY,DELIVERY_DELAY
3,I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED
4,"@115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG",DELIVERY_MISSING_OR_MISDELIVERED,OTHER_NON_SUPPORT
5,"Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI",PRODUCT_PROBLEM,OTHER_NON_SUPPORT
6,"Can’t believe @115830’s response to me asking why my Xbox One X hasn’t been despatched yet. “If you’re not happy with it, cancel”",ORDER_STATUS_OR_CANCELLATION,ORDER_STATUS_OR_CANCELLATION
7,@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice,DELIVERY_DELAY,PRIME_MEMBERSHIP
8,@AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u,PAYMENT_BILLING,OTHER_NON_SUPPORT
9,An update : It’s still Monday. \n\n#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9,DELIVERY_DELAY,OTHER_NON_SUPPORT
10,@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.,ACCOUNT_ACCESS_SECURITY,WEBSITE_APP_TECHNICAL
11,Prime now turkey tracker. https://t.co/90UMXDP11e,OTHER_NON_SUPPORT,PRIME_MEMBERSHIP
12,@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK,WEBSITE_APP_TECHNICAL,OTHER_NON_SUPPORT
13,Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄,PRIME_MEMBERSHIP,PRIME_MEMBERSHIP
14,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,OTHER_NON_SUPPORT,OTHER_NON_SUPPORT
15,Bought stickers from @115821 and they came all bent 😩,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
16,@115850 Your sale advertisement today. Trivia: Find the mistake in the image. U need better testers to validate content. Can I Join you? https://t.co/xMojPqCjvL,OTHER_NON_SUPPORT,OTHER_NON_SUPPORT
17,@115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!,DELIVERY_MISSING_OR_MISDELIVERED,OTHER_NON_SUPPORT
18,Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!\nAmazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA,GIFT_CARD_PROMOTION,OTHER_NON_SUPPORT
19,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...",ORDER_STATUS_OR_CANCELLATION,ORDER_STATUS_OR_CANCELLATION

EVALUATE SILVER-LABELING HEURISTIC

In [116]:
print("=" * 80)
print("SILVER-LABELING HEURISTIC EVALUATION")
print("=" * 80)

# ------------------------------------------------------------
# 1. Overall accuracy
# ------------------------------------------------------------

accuracy = (
    audit_eval["heuristic_prediction"]
    == audit_eval["intent_label"]
).mean()

print(
    f"\nAccuracy on 150 human-labelled examples: "
    f"{accuracy * 100:.2f}%"
)

# ------------------------------------------------------------
# 2. Confusion table
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CONFUSION TABLE")
print("=" * 80)

confusion = pd.crosstab(
    audit_eval["intent_label"],
    audit_eval["heuristic_prediction"],
    rownames=["Human label"],
    colnames=["Heuristic prediction"]
)

display(confusion)

# ------------------------------------------------------------
# 3. Per-intent performance
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PER-INTENT ACCURACY")
print("=" * 80)

per_intent = (
    audit_eval
    .assign(
        correct=lambda x:
        x["intent_label"]
        == x["heuristic_prediction"]
    )
    .groupby("intent_label")["correct"]
    .agg(["count", "mean"])
    .reset_index()
)

per_intent["accuracy_percentage"] = (
    per_intent["mean"] * 100
).round(2)

per_intent = per_intent.drop(columns=["mean"])

display(
    per_intent.sort_values(
        "accuracy_percentage"
    )
)

# ------------------------------------------------------------
# 4. Inspect mistakes
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("HEURISTIC ERRORS")
print("=" * 80)

errors = audit_eval[
    audit_eval["intent_label"]
    != audit_eval["heuristic_prediction"]
][
    [
        "first_customer_message",
        "intent_label",
        "heuristic_prediction",
        "annotation_notes"
    ]
].copy()

print("Number of errors:", len(errors))

display(errors)

================================================================================
SILVER-LABELING HEURISTIC EVALUATION
================================================================================

Accuracy on 150 human-labelled examples: 36.67%

================================================================================
CONFUSION TABLE
================================================================================

Heuristic prediction,ACCOUNT_ACCESS_SECURITY,DELIVERY_ATTEMPT_OR_INSTRUCTIONS,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,DEVICE_TECHNICAL_SUPPORT,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,ORDER_STATUS_OR_CANCELLATION,OTHER_NON_SUPPORT,PAYMENT_BILLING,PRIME_MEMBERSHIP,PRODUCT_AVAILABILITY_INFORMATION,PRODUCT_PROBLEM,RETURN_REPLACEMENT_REFUND,WEBSITE_APP_TECHNICAL
Human label,,,,,,,,,,,,,,,
ACCOUNT_ACCESS_SECURITY,1,0,0,0,0,0,0,0,1,0,1,0,0,0,2
DELIVERY_ATTEMPT_OR_INSTRUCTIONS,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
DELIVERY_DELAY,0,1,3,6,0,0,0,0,19,0,8,1,0,0,0
DELIVERY_MISSING_OR_MISDELIVERED,0,0,0,7,0,0,0,0,5,0,1,0,0,0,0
DEVICE_TECHNICAL_SUPPORT,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0
DIGITAL_CONTENT,0,0,0,0,0,1,0,0,3,0,0,1,0,0,1
GIFT_CARD_PROMOTION,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
ORDER_STATUS_OR_CANCELLATION,0,0,1,0,0,0,0,3,3,0,0,0,0,0,0
OTHER_NON_SUPPORT,0,0,0,0,0,0,0,0,27,0,1,0,0,0,1
PAYMENT_BILLING,0,0,0,0,0,0,0,0,3,1,0,1,0,0,0
PRIME_MEMBERSHIP,0,0,0,0,0,0,0,0,2,0,3,0,0,0,0
PRODUCT_AVAILABILITY_INFORMATION,0,0,0,0,0,0,0,0,5,0,0,0,0,0,1
PRODUCT_PROBLEM,0,0,0,0,0,0,0,0,15,0,0,0,2,0,0
RETURN_REPLACEMENT_REFUND,0,0,0,0,0,0,0,0,5,0,0,0,0,2,1
WEBSITE_APP_TECHNICAL,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1

================================================================================
PER-INTENT ACCURACY
================================================================================

                        intent_label  count  accuracy_percentage
11  PRODUCT_AVAILABILITY_INFORMATION      6                 0.00
2                     DELIVERY_DELAY     38                 7.89
12                   PRODUCT_PROBLEM     17                11.76
5                    DIGITAL_CONTENT      6                16.67
0            ACCOUNT_ACCESS_SECURITY      5                20.00
9                    PAYMENT_BILLING      5                20.00
13         RETURN_REPLACEMENT_REFUND      8                25.00
14             WEBSITE_APP_TECHNICAL      4                25.00
7       ORDER_STATUS_OR_CANCELLATION      7                42.86
6                GIFT_CARD_PROMOTION      2                50.00
1   DELIVERY_ATTEMPT_OR_INSTRUCTIONS      2                50.00
3   DELIVERY_MISSING_OR_MISDELIVERED     13                53.85
10                  PRIME_MEMBERSHIP      5                60.00
4           DEVICE_TECHNICAL_SUPPORT      3                66.67
8                  OTHER_NON_SUPPORT     29                93.10

================================================================================
HEURISTIC ERRORS
================================================================================
Number of errors: 95

,first_customer_message,intent_label,heuristic_prediction,annotation_notes
0,@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP,PRODUCT_PROBLEM,OTHER_NON_SUPPORT,
3,I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,
4,"@115850 Hello Amazon team, I have ordered an item and got an email that it was delivered to me today. I am at home and didn't receive any product. When I try to call the agent number (8179260086) it is switched off. I am a Prime customer and your service is ridiculous. https://t.co/cibAXpH6jG",DELIVERY_MISSING_OR_MISDELIVERED,OTHER_NON_SUPPORT,
5,"Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI",PRODUCT_PROBLEM,OTHER_NON_SUPPORT,
7,@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice,DELIVERY_DELAY,PRIME_MEMBERSHIP,
...,...,...,...,...
140,@116316 was nutzt einem AmazonPrime wenn man die Pakete nie pünktlich bekommt?! Erst 3-5 Tage später?! Danke an #Hermes!,DELIVERY_DELAY,OTHER_NON_SUPPORT,
145,"Don’t know why I bother ordering anything with @115821 anymore, they can never deliver on time 🙄",DELIVERY_DELAY,OTHER_NON_SUPPORT,
146,"@116875 ¿Qué hago, Amazon? Hice una devolución y @178440 no tiene idea de mi paquete. Selló la guía (aún la tengo) y dice que no lo he enviado.",RETURN_REPLACEMENT_REFUND,OTHER_NON_SUPPORT,
148,"@AmazonHelp sumthing wrong in my account, lost prime membership, no order history, cust service not taking my calls. Manisha Chandnani",ACCOUNT_ACCESS_SECURITY,PRIME_MEMBERSHIP,Prime/order-history disappearance is treated as account-state problem.
149,@115850 very very bad product delivrd by amazon.my brother ordrd the lg phone Prodct output is not atleast 20 % wt dey gives in discrption,PRODUCT_PROBLEM,OTHER_NON_SUPPORT,Poor product performance/quality is the underlying issue.

Weak-labeling baseline: A transparent keyword heuristic achieved only 36.67% accuracy on 150 manually reviewed examples, demonstrating that lexical rules were insufficient for reliable intent labeling.

LLM Environment Check

In [117]:
import os
import importlib.util
import sys

print("=" * 80)
print("LLM ENVIRONMENT CHECK")
print("=" * 80)

print("Python:", sys.version)

================================================================================
LLM ENVIRONMENT CHECK
================================================================================
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [118]:
packages = [
    "groq",
    "anthropic",
    "mistralai",
    "openai",
    "langchain",
    "langgraph",
    "sentence_transformers",
    "faiss",
]

print("\nInstalled packages:")
for package in packages:
    installed = importlib.util.find_spec(package) is not None
    print(f"{package:25s} : {'YES' if installed else 'NO'}")

Installed packages:
groq                      : NO
anthropic                 : NO
mistralai                 : NO
openai                    : YES
langchain                 : YES
langgraph                 : NO
sentence_transformers     : YES
faiss                     : YES

In [119]:
env_keys = [
    "GROQ_API_KEY",
    "ANTHROPIC_API_KEY",
    "MISTRAL_API_KEY",
    "OPENAI_API_KEY",
]

print("\nAPI key availability:")
for key in env_keys:
    exists = bool(os.getenv(key))
    print(f"{key:25s} : {'SET' if exists else 'NOT SET'}")

API key availability:
GROQ_API_KEY              : NOT SET
ANTHROPIC_API_KEY         : NOT SET
MISTRAL_API_KEY           : NOT SET
OPENAI_API_KEY            : NOT SET

In [120]:
from pathlib import Path

project_root = Path.cwd().parent

env_path = project_root / ".env"

print("\nProject root:")
print(project_root)

print("\n.env file exists:", env_path.exists())

if env_path.exists():
    print(".env location:", env_path)

Project root:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent

.env file exists: False

Development Data Check

In [121]:
import pandas as pd
from pathlib import Path

print("=" * 80)
print("DEVELOPMENT DATA CHECK")
print("=" * 80)

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

split_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v2.csv"
)

if not split_path.exists():
    raise FileNotFoundError(
        f"Expected split file not found:\n{split_path}"
    )

split_df = pd.read_csv(split_path)

print("Loaded:", split_path)
print("Rows:", f"{len(split_df):,}")

================================================================================
DEVELOPMENT DATA CHECK
================================================================================
Loaded: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits_v2.csv
Rows: 82,246

In [122]:
train_pool = split_df[
    (split_df["split"] == "train") &
    (~split_df["is_taxonomy_audit"])
].copy()

validation_pool = split_df[
    (split_df["split"] == "validation") &
    (~split_df["is_taxonomy_audit"])
].copy()

test_pool = split_df[
    split_df["split"] == "test"
].copy()

print("\nDevelopment pools:")
print(
    "Train:",
    f"{len(train_pool):,}"
)

print(
    "Validation:",
    f"{len(validation_pool):,}"
)

print(
    "Test:",
    f"{len(test_pool):,}"
)

Development pools:
Train: 65,678
Validation: 8,213
Test: 8,225

In [123]:
required = [
    "conversation_id",
    "first_customer_message",
    "conversation_text",
    "support_account",
    "split",
    "is_taxonomy_audit",
]

missing = [
    c for c in required
    if c not in split_df.columns
]

if missing:
    raise ValueError(
        f"Missing required columns: {missing}"
    )

In [124]:
assert train_pool["is_taxonomy_audit"].sum() == 0
assert validation_pool["is_taxonomy_audit"].sum() == 0

print("\n✓ Training pool excludes taxonomy audit.")
print("✓ Validation pool excludes taxonomy audit.")
print("✓ Test pool remains untouched.")

✓ Training pool excludes taxonomy audit.
✓ Validation pool excludes taxonomy audit.
✓ Test pool remains untouched.

In [125]:
PILOT_SIZE = 100

pilot = train_pool.sample(
    n=PILOT_SIZE,
    random_state=42
)

print(
    f"\nPilot sample prepared: {len(pilot)} conversations"
)

print("\nPilot intent-label input examples:")

display(
    pilot[
        [
            "conversation_id",
            "first_customer_message",
            "conversation_size"
        ]
    ].head(10)
)

Pilot sample prepared: 100 conversations

Pilot intent-label input examples:

,conversation_id,first_customer_message,conversation_size
65169,2448288,@115821 tracking says my shipment was delivered but it hasn’t arrived. What do I️ do?,5
66550,2493763,mandy finally made an amazon account 😳 sorry bank account,2
40625,1339616,ordered phone on @115850 twice money got deducted from acc &amp; twice amazon says payment failed. on retrying they charging more. Disgusting.,9
58868,2254646,"My @32611 pre-order of the 3CD/Blu-Ray Deluxe ""Automatic…"" re-issue was not delivered by @115821 and they aren't sure when it will arrive. :(",3
6418,231318,@AmazonHelp why u increase price on big sale day nd after giving discount make it older rate making fool of people,3
31281,1001077,@115821 this guy is tossing packages on 51st street btwn 1st/2nd ave https://t.co/HXAvTTJB0Z,2
56781,2144476,そういえばAmazon prime会員なので、今更ながら始めてprimeビデオ？を観てみた。いぬやしきの第一話,2
58413,2226591,@AmazonHelp Lots of confusion whether i m the winner on not. Still not confirmed. No upadate yet.,3
61801,2319945,"per la seconda volta mi arriva un articolo diverso da quello ordinato: mai più @120540, sapevatelo.....",4
79211,2907786,"I don't live close enough for 2 hour Amazon delivery but I get same day, aka the coffee I ordered this morning will be here in a few hours. HURRYYYY!",12

In [126]:
import sys
import importlib.metadata as md

print("=" * 80)
print("DEPENDENCY VERSION CHECK")
print("=" * 80)

packages = [
    "sentence-transformers",
    "transformers",
    "torch",
    "huggingface-hub",
    "tokenizers",
]

for package in packages:
    try:
        print(f"{package:25s}: {md.version(package)}")
    except md.PackageNotFoundError:
        print(f"{package:25s}: NOT INSTALLED")

print("\nPython:", sys.version)

================================================================================
DEPENDENCY VERSION CHECK
================================================================================
sentence-transformers    : 5.1.0
transformers             : 4.55.0
torch                    : 2.4.1
huggingface-hub          : 0.34.4
tokenizers               : 0.21.4

Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [127]:
import os
os.environ["USE_TF"] = "0"
os.environ["USE_FLAX"] = "0"

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("=" * 80)
print("ZERO-SHOT SEMANTIC INTENT BASELINE")
print("=" * 80)

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

================================================================================
ZERO-SHOT SEMANTIC INTENT BASELINE
================================================================================

In [128]:
INTENT_DEFINITIONS = {
    "DELIVERY_DELAY":
        "Shipment is late, delayed, or misses the expected delivery window.",

    "DELIVERY_MISSING_OR_MISDELIVERED":
        "Package is marked delivered but not received, or delivered to the wrong location.",

    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS":
        "Delivery attempt behavior, driver behavior, delivery instructions, or delivery location or slot issues.",

    "ORDER_STATUS_OR_CANCELLATION":
        "Order lifecycle status, cancellation, dispatch, or preorder issues.",

    "RETURN_REPLACEMENT_REFUND":
        "Return, replacement, or refund process or status.",

    "PRODUCT_PROBLEM":
        "Product is damaged, defective, wrong, incomplete, used, counterfeit, or has a product-quality problem.",

    "PAYMENT_BILLING":
        "Payment method, card, unexpected charge, billing, or Amazon Pay issue.",

    "PRIME_MEMBERSHIP":
        "Prime signup, renewal, cancellation, membership status, or Prime benefits.",

    "ACCOUNT_ACCESS_SECURITY":
        "Login, password, locked account, hacked account, authentication, or security issue.",

    "GIFT_CARD_PROMOTION":
        "Gift card, coupon, promotion, cashback, or promotional-credit issue.",

    "PRODUCT_AVAILABILITY_INFORMATION":
        "Product stock, availability, pricing, shipping eligibility, or general product information.",

    "DIGITAL_CONTENT":
        "Prime Video, Amazon Music, Kindle content, or other digital-content access or availability.",

    "DEVICE_TECHNICAL_SUPPORT":
        "Kindle, Fire TV, Fire Stick, Echo, Alexa, or other Amazon-device technical issue.",

    "WEBSITE_APP_TECHNICAL":
        "Amazon website, mobile app, checkout, UI, form, or technical site or app error.",

    "OTHER_NON_SUPPORT":
        "Non-support or social content, insufficient information, generic complaints, marketing, or cases that do not fit another operational intent.",
}

FINAL_INTENTS = list(INTENT_DEFINITIONS.keys())

In [129]:
import os

# Remove invalid SSL certificate overrides
os.environ.pop("SSL_CERT_FILE", None)
os.environ.pop("REQUESTS_CA_BUNDLE", None)
os.environ.pop("CURL_CA_BUNDLE", None)

print("SSL_CERT_FILE:", os.environ.get("SSL_CERT_FILE"))
print("REQUESTS_CA_BUNDLE:", os.environ.get("REQUESTS_CA_BUNDLE"))
print("CURL_CA_BUNDLE:", os.environ.get("CURL_CA_BUNDLE"))

print("\n✓ Invalid certificate overrides removed.")

SSL_CERT_FILE: None
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None

✓ Invalid certificate overrides removed.

In [130]:
MODEL_NAME = "all-MiniLM-L6-v2"

print("\nLoading embedding model:")
print(MODEL_NAME)

model = SentenceTransformer(MODEL_NAME)

print("✓ Model loaded.")

Loading embedding model:
all-MiniLM-L6-v2
✓ Model loaded.

In [131]:
intent_names = list(INTENT_DEFINITIONS.keys())
intent_texts = list(INTENT_DEFINITIONS.values())

intent_embeddings = model.encode(
    intent_texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

print(
    "\nIntent embeddings:",
    intent_embeddings.shape
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Intent embeddings: (15, 384)

In [132]:
#  Embed 150 HUMAN-LABELLED audit examples
audit_texts = (
    taxonomy_audit["first_customer_message"]
    .fillna("")
    .astype(str)
    .tolist()
)

audit_embeddings = model.encode(
    audit_texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("✓ 150 audit examples embedded.")

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

✓ 150 audit examples embedded.

In [133]:
#Predict using cosine similarity
similarities = audit_embeddings @ intent_embeddings.T

prediction_indices = similarities.argmax(axis=1)

predictions = [
    intent_names[i]
    for i in prediction_indices
]

confidence = similarities[
    np.arange(len(similarities)),
    prediction_indices
]

In [134]:
# Evaluation dataframe
semantic_eval = taxonomy_audit.copy()

semantic_eval["semantic_prediction"] = predictions
semantic_eval["semantic_similarity"] = confidence

In [135]:
# Overall accuracy
accuracy = accuracy_score(
    semantic_eval["intent_label"],
    semantic_eval["semantic_prediction"]
)

print("\n" + "=" * 80)
print("ZERO-SHOT SEMANTIC BASELINE")
print("=" * 80)

print(f"Accuracy: {accuracy:.4f}")
print(f"Accuracy: {accuracy * 100:.2f}%")

================================================================================
ZERO-SHOT SEMANTIC BASELINE
================================================================================
Accuracy: 0.3067
Accuracy: 30.67%

In [136]:
print("\n" + "=" * 80)
print("PER-INTENT PERFORMANCE")
print("=" * 80)

report = classification_report(
    semantic_eval["intent_label"],
    semantic_eval["semantic_prediction"],
    labels=intent_names,
    output_dict=True,
    zero_division=0
)

per_intent = pd.DataFrame(report).T

display(
    per_intent[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

================================================================================
PER-INTENT PERFORMANCE
================================================================================

                                  precision  recall  f1-score  support
DELIVERY_DELAY                        0.857   0.474     0.610   38.000
DELIVERY_MISSING_OR_MISDELIVERED      0.333   0.615     0.432   13.000
DELIVERY_ATTEMPT_OR_INSTRUCTIONS      0.000   0.000     0.000    2.000
ORDER_STATUS_OR_CANCELLATION          0.250   0.286     0.267    7.000
RETURN_REPLACEMENT_REFUND             0.750   0.375     0.500    8.000
PRODUCT_PROBLEM                       0.333   0.235     0.276   17.000
PAYMENT_BILLING                       0.079   0.600     0.140    5.000
PRIME_MEMBERSHIP                      0.667   0.400     0.500    5.000
ACCOUNT_ACCESS_SECURITY               0.000   0.000     0.000    5.000
GIFT_CARD_PROMOTION                   0.000   0.000     0.000    2.000
PRODUCT_AVAILABILITY_INFORMATION      0.000   0.000     0.000    6.000
DIGITAL_CONTENT                       0.600   0.500     0.545    6.000
DEVICE_TECHNICAL_SUPPORT              1.000   0.667     0.800    3.000
WEBSITE_APP_TECHNICAL                 0.000   0.000     0.000    4.000
OTHER_NON_SUPPORT                     1.000   0.034     0.067   29.000
accuracy                              0.307   0.307     0.307    0.307
macro avg                             0.391   0.279     0.276  150.000
weighted avg                          0.598   0.307     0.334  150.000

In [137]:
# Lowest-confidence examples
print("\n" + "=" * 80)
print("LOWEST-CONFIDENCE EXAMPLES")
print("=" * 80)

low_confidence = (
    semantic_eval
    .sort_values("semantic_similarity")
    [
        [
            "first_customer_message",
            "intent_label",
            "semantic_prediction",
            "semantic_similarity"
        ]
    ]
    .head(20)
)

display(low_confidence)

================================================================================
LOWEST-CONFIDENCE EXAMPLES
================================================================================

,first_customer_message,intent_label,semantic_prediction,semantic_similarity
62,@116313 アマゾンのサイトのフォントサイズですが、大きくなりましたか？それとも、当PC（ちなみにChrome使用）だけでしょうか？,WEBSITE_APP_TECHNICAL,ACCOUNT_ACCESS_SECURITY,0.055659
22,アマゾンプライムでアニメを見る日々が始まる……\nネットで探す必要がなくなった…\n喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0,OTHER_NON_SUPPORT,WEBSITE_APP_TECHNICAL,0.058308
24,Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT,DELIVERY_DELAY,PRODUCT_PROBLEM,0.060634
125,@116928 segun esto me desbloquearon mi cuenta pero al hacer mi pedido no me deja!!! No entiendo entonces 😡😡,ACCOUNT_ACCESS_SECURITY,WEBSITE_APP_TECHNICAL,0.071616
74,知らん間にAmazonプライム会員にさせられてたので有効活用してやろうと思うんやけど送料無料以外に何が出来るんや,PRIME_MEMBERSHIP,PRODUCT_PROBLEM,0.075309
95,"@AmazonHelp Ich bin etwas verwirrt. Wann kommt das Paket denn? Gestern, heute, morgen, Montag? https://t.co/nYRbEmTteO",DELIVERY_DELAY,DELIVERY_DELAY,0.082451
141,EU TÔ TREMENDO. @117086 EU TE AMO MUITO. https://t.co/Br5xFHHmTz,OTHER_NON_SUPPORT,PRODUCT_PROBLEM,0.090902
58,マジでアマゾンミュージック様天才すぎっからみんなプライムはいれ,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,0.092713
52,げ、いつの間にかAmazonプライム会員になっていた。いつだよ,PRIME_MEMBERSHIP,PRODUCT_PROBLEM,0.101404
38,せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,0.102542
112,"J'ai commandé y'a 10 jours, et la date de livraison ne fait qu'être repoussée...\n@120533 https://t.co/guP5rJgapW",DELIVERY_DELAY,ORDER_STATUS_OR_CANCELLATION,0.106663
1,@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52,OTHER_NON_SUPPORT,PRODUCT_PROBLEM,0.110385
45,"@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: ""preparando envío""",ORDER_STATUS_OR_CANCELLATION,ACCOUNT_ACCESS_SECURITY,0.114038
20,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,PRODUCT_PROBLEM,PRODUCT_AVAILABILITY_INFORMATION,0.115098
63,@115850 Still didn't get my product😡😡😡 Too much disappointed https://t.co/jxFqdBYpne,DELIVERY_DELAY,PAYMENT_BILLING,0.124018
65,Hey @AmazonHelp warum ist das Spiel Monopoly für die Switch plötzlich ca. 10 Euro teurer? #nerv,PRODUCT_AVAILABILITY_INFORMATION,ORDER_STATUS_OR_CANCELLATION,0.129223
73,Dear @115830 this is not the wonder twins https://t.co/AvhzdenO2R,RETURN_REPLACEMENT_REFUND,DELIVERY_MISSING_OR_MISDELIVERED,0.153878
140,@116316 was nutzt einem AmazonPrime wenn man die Pakete nie pünktlich bekommt?! Erst 3-5 Tage später?! Danke an #Hermes!,DELIVERY_DELAY,PAYMENT_BILLING,0.163835
84,Wenn die Outlook App dir die Emails von gestern erst jetzt anzeigt und du die kurze Verfügbarkeit der Monster Hunter Collectors Edition auf @116316 verpasst. Ich raste aus...,PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL,0.169000
70,野球と全く関係ないんですが質問したいことがあるのでさせていただきます\nAmazonを利用したことがある人はわかると思いますが商品を注文して自宅に届くようにしたんですけど受け取るまでの過程とかよくわからないのでわかる人いたら教えて欲しいです\nお願いします,PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL,0.173902

In [138]:
# Save results
semantic_path = (
    PROCESSED_DIR /
    "semantic_intent_baseline_150.csv"
)

semantic_eval.to_csv(
    semantic_path,
    index=False
)

print("\n✓ Saved:")
print(semantic_path)

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\semantic_intent_baseline_150.csv

In [139]:
# ============================================================
# STEP 60D — SEMANTIC INTENT EVALUATION
# ============================================================

import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score, classification_report

# ------------------------------------------------------------
# 1. Locked taxonomy
# ------------------------------------------------------------

INTENT_DEFINITIONS = {
    "DELIVERY_DELAY":
        "Shipment is late, delayed, or misses the expected delivery window.",

    "DELIVERY_MISSING_OR_MISDELIVERED":
        "Package is marked delivered but not received, or delivered to the wrong location.",

    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS":
        "Delivery attempt behavior, driver behavior, delivery instructions, or delivery location or slot issues.",

    "ORDER_STATUS_OR_CANCELLATION":
        "Order lifecycle status, cancellation, dispatch, or preorder issues.",

    "RETURN_REPLACEMENT_REFUND":
        "Return, replacement, or refund process or status.",

    "PRODUCT_PROBLEM":
        "Product is damaged, defective, wrong, incomplete, used, counterfeit, or has a product-quality problem.",

    "PAYMENT_BILLING":
        "Payment method, card, unexpected charge, billing, or Amazon Pay issue.",

    "PRIME_MEMBERSHIP":
        "Prime signup, renewal, cancellation, membership status, or Prime benefits.",

    "ACCOUNT_ACCESS_SECURITY":
        "Login, password, locked account, hacked account, authentication, or security issue.",

    "GIFT_CARD_PROMOTION":
        "Gift card, coupon, promotion, cashback, or promotional-credit issue.",

    "PRODUCT_AVAILABILITY_INFORMATION":
        "Product stock, availability, pricing, shipping eligibility, or general product information.",

    "DIGITAL_CONTENT":
        "Prime Video, Amazon Music, Kindle content, or other digital-content access or availability.",

    "DEVICE_TECHNICAL_SUPPORT":
        "Kindle, Fire TV, Fire Stick, Echo, Alexa, or other Amazon-device technical issue.",

    "WEBSITE_APP_TECHNICAL":
        "Amazon website, mobile app, checkout, UI, form, or technical site or app error.",

    "OTHER_NON_SUPPORT":
        "Non-support or social content, insufficient information, generic complaints, marketing, or cases that do not fit another operational intent.",
}

intent_names = list(INTENT_DEFINITIONS.keys())
intent_texts = list(INTENT_DEFINITIONS.values())

# ------------------------------------------------------------
# 2. Embed intent descriptions
# ------------------------------------------------------------

intent_embeddings = model.encode(
    intent_texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("✓ Intent descriptions embedded.")

# ------------------------------------------------------------
# 3. Embed 150 HUMAN-LABELLED audit examples
# ------------------------------------------------------------

audit_texts = (
    taxonomy_audit["first_customer_message"]
    .fillna("")
    .astype(str)
    .tolist()
)

audit_embeddings = model.encode(
    audit_texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("✓ 150 audit examples embedded.")

# ------------------------------------------------------------
# 4. Predict using cosine similarity
# ------------------------------------------------------------

similarities = audit_embeddings @ intent_embeddings.T

prediction_indices = similarities.argmax(axis=1)

predictions = [
    intent_names[i]
    for i in prediction_indices
]

confidence = similarities[
    np.arange(len(similarities)),
    prediction_indices
]

# ------------------------------------------------------------
# 5. Evaluation dataframe
# ------------------------------------------------------------

semantic_eval = taxonomy_audit.copy()

semantic_eval["semantic_prediction"] = predictions
semantic_eval["semantic_similarity"] = confidence

# ------------------------------------------------------------
# 6. Overall accuracy
# ------------------------------------------------------------

accuracy = accuracy_score(
    semantic_eval["intent_label"],
    semantic_eval["semantic_prediction"]
)

print("\n" + "=" * 80)
print("ZERO-SHOT SEMANTIC BASELINE")
print("=" * 80)

print(f"Accuracy: {accuracy:.4f}")
print(f"Accuracy: {accuracy * 100:.2f}%")

# ------------------------------------------------------------
# 7. Classification report
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PER-INTENT PERFORMANCE")
print("=" * 80)

report = classification_report(
    semantic_eval["intent_label"],
    semantic_eval["semantic_prediction"],
    labels=intent_names,
    output_dict=True,
    zero_division=0
)

per_intent = pd.DataFrame(report).T

display(
    per_intent[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

# ------------------------------------------------------------
# 8. Lowest-confidence examples
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("LOWEST-CONFIDENCE EXAMPLES")
print("=" * 80)

low_confidence = (
    semantic_eval
    .sort_values("semantic_similarity")
    [
        [
            "first_customer_message",
            "intent_label",
            "semantic_prediction",
            "semantic_similarity"
        ]
    ]
    .head(20)
)

display(low_confidence)

# ------------------------------------------------------------
# 9. Save result
# ------------------------------------------------------------

semantic_path = (
    PROCESSED_DIR /
    "semantic_intent_baseline_150.csv"
)

semantic_eval.to_csv(
    semantic_path,
    index=False
)

print("\n✓ Saved:")
print(semantic_path)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

✓ Intent descriptions embedded.

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

✓ 150 audit examples embedded.

================================================================================
ZERO-SHOT SEMANTIC BASELINE
================================================================================
Accuracy: 0.3067
Accuracy: 30.67%

================================================================================
PER-INTENT PERFORMANCE
================================================================================

                                  precision  recall  f1-score  support
DELIVERY_DELAY                        0.857   0.474     0.610   38.000
DELIVERY_MISSING_OR_MISDELIVERED      0.333   0.615     0.432   13.000
DELIVERY_ATTEMPT_OR_INSTRUCTIONS      0.000   0.000     0.000    2.000
ORDER_STATUS_OR_CANCELLATION          0.250   0.286     0.267    7.000
RETURN_REPLACEMENT_REFUND             0.750   0.375     0.500    8.000
PRODUCT_PROBLEM                       0.333   0.235     0.276   17.000
PAYMENT_BILLING                       0.079   0.600     0.140    5.000
PRIME_MEMBERSHIP                      0.667   0.400     0.500    5.000
ACCOUNT_ACCESS_SECURITY               0.000   0.000     0.000    5.000
GIFT_CARD_PROMOTION                   0.000   0.000     0.000    2.000
PRODUCT_AVAILABILITY_INFORMATION      0.000   0.000     0.000    6.000
DIGITAL_CONTENT                       0.600   0.500     0.545    6.000
DEVICE_TECHNICAL_SUPPORT              1.000   0.667     0.800    3.000
WEBSITE_APP_TECHNICAL                 0.000   0.000     0.000    4.000
OTHER_NON_SUPPORT                     1.000   0.034     0.067   29.000
accuracy                              0.307   0.307     0.307    0.307
macro avg                             0.391   0.279     0.276  150.000
weighted avg                          0.598   0.307     0.334  150.000

================================================================================
LOWEST-CONFIDENCE EXAMPLES
================================================================================

,first_customer_message,intent_label,semantic_prediction,semantic_similarity
62,@116313 アマゾンのサイトのフォントサイズですが、大きくなりましたか？それとも、当PC（ちなみにChrome使用）だけでしょうか？,WEBSITE_APP_TECHNICAL,ACCOUNT_ACCESS_SECURITY,0.055659
22,アマゾンプライムでアニメを見る日々が始まる……\nネットで探す必要がなくなった…\n喜びすぎてチキンになるわ… https://t.co/ow0gXbNsQ0,OTHER_NON_SUPPORT,WEBSITE_APP_TECHNICAL,0.058308
24,Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT,DELIVERY_DELAY,PRODUCT_PROBLEM,0.060634
125,@116928 segun esto me desbloquearon mi cuenta pero al hacer mi pedido no me deja!!! No entiendo entonces 😡😡,ACCOUNT_ACCESS_SECURITY,WEBSITE_APP_TECHNICAL,0.071616
74,知らん間にAmazonプライム会員にさせられてたので有効活用してやろうと思うんやけど送料無料以外に何が出来るんや,PRIME_MEMBERSHIP,PRODUCT_PROBLEM,0.075309
95,"@AmazonHelp Ich bin etwas verwirrt. Wann kommt das Paket denn? Gestern, heute, morgen, Montag? https://t.co/nYRbEmTteO",DELIVERY_DELAY,DELIVERY_DELAY,0.082451
141,EU TÔ TREMENDO. @117086 EU TE AMO MUITO. https://t.co/Br5xFHHmTz,OTHER_NON_SUPPORT,PRODUCT_PROBLEM,0.090902
58,マジでアマゾンミュージック様天才すぎっからみんなプライムはいれ,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,0.092713
52,げ、いつの間にかAmazonプライム会員になっていた。いつだよ,PRIME_MEMBERSHIP,PRODUCT_PROBLEM,0.101404
38,せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,0.102542
112,"J'ai commandé y'a 10 jours, et la date de livraison ne fait qu'être repoussée...\n@120533 https://t.co/guP5rJgapW",DELIVERY_DELAY,ORDER_STATUS_OR_CANCELLATION,0.106663
1,@120533 Intéressants vos emballages... https://t.co/kMqmBDEt52,OTHER_NON_SUPPORT,PRODUCT_PROBLEM,0.110385
45,"@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: ""preparando envío""",ORDER_STATUS_OR_CANCELLATION,ACCOUNT_ACCESS_SECURITY,0.114038
20,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,PRODUCT_PROBLEM,PRODUCT_AVAILABILITY_INFORMATION,0.115098
63,@115850 Still didn't get my product😡😡😡 Too much disappointed https://t.co/jxFqdBYpne,DELIVERY_DELAY,PAYMENT_BILLING,0.124018
65,Hey @AmazonHelp warum ist das Spiel Monopoly für die Switch plötzlich ca. 10 Euro teurer? #nerv,PRODUCT_AVAILABILITY_INFORMATION,ORDER_STATUS_OR_CANCELLATION,0.129223
73,Dear @115830 this is not the wonder twins https://t.co/AvhzdenO2R,RETURN_REPLACEMENT_REFUND,DELIVERY_MISSING_OR_MISDELIVERED,0.153878
140,@116316 was nutzt einem AmazonPrime wenn man die Pakete nie pünktlich bekommt?! Erst 3-5 Tage später?! Danke an #Hermes!,DELIVERY_DELAY,PAYMENT_BILLING,0.163835
84,Wenn die Outlook App dir die Emails von gestern erst jetzt anzeigt und du die kurze Verfügbarkeit der Monster Hunter Collectors Edition auf @116316 verpasst. Ich raste aus...,PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL,0.169000
70,野球と全く関係ないんですが質問したいことがあるのでさせていただきます\nAmazonを利用したことがある人はわかると思いますが商品を注文して自宅に届くようにしたんですけど受け取るまでの過程とかよくわからないのでわかる人いたら教えて欲しいです\nお願いします,PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL,0.173902

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\semantic_intent_baseline_150.csv

Zero-shot semantic matching is insufficient for operational intent classification, achieving 30.7% accuracy and 27.6% macro-F1 on the 150-example human-labelled audit. This motivated a supervised classifier rather than relying on intent-description similarity alone.

TF-IDF + LOGISTIC REGRESSION BASELINE

In [140]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [141]:
print("=" * 80)
print("TF-IDF + LOGISTIC REGRESSION BASELINE")
print("=" * 80)

# Prepare data
X = (
    taxonomy_audit["first_customer_message"]
    .fillna("")
    .astype(str)
)

y = taxonomy_audit["intent_label"].astype(str)

print("\nExamples:", len(X))
print("Intents:", y.nunique())

print("\nClass distribution:")
print(y.value_counts())

================================================================================
TF-IDF + LOGISTIC REGRESSION BASELINE
================================================================================

Examples: 150
Intents: 15

Class distribution:
intent_label
DELIVERY_DELAY                      38
OTHER_NON_SUPPORT                   29
PRODUCT_PROBLEM                     17
DELIVERY_MISSING_OR_MISDELIVERED    13
RETURN_REPLACEMENT_REFUND            8
ORDER_STATUS_OR_CANCELLATION         7
PRODUCT_AVAILABILITY_INFORMATION     6
DIGITAL_CONTENT                      6
PAYMENT_BILLING                      5
ACCOUNT_ACCESS_SECURITY              5
PRIME_MEMBERSHIP                     5
WEBSITE_APP_TECHNICAL                4
DEVICE_TECHNICAL_SUPPORT             3
GIFT_CARD_PROMOTION                  2
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     2
Name: count, dtype: int64

In [142]:
# Pipeline
tfidf_lr = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            strip_accents="unicode",
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )
    ),
    (
        "classifier",
        LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        )
    )
])

In [143]:
# stratified cross-validation
min_class_count = y.value_counts().min()

n_splits = min(5, min_class_count)

print(f"\nUsing {n_splits}-fold stratified cross-validation.")

cv = StratifiedKFold(
    n_splits=n_splits,
    shuffle=True,
    random_state=42
)

predictions = cross_val_predict(
    tfidf_lr,
    X,
    y,
    cv=cv
)

Using 2-fold stratified cross-validation.

In [144]:
accuracy = accuracy_score(y, predictions)

print("\n" + "=" * 80)
print("RESULT")
print("=" * 80)

print(f"Cross-validation accuracy   : {accuracy:.4f}")
print(f"Cross-validation accuracy(%): {accuracy * 100:.2f}%")

================================================================================
RESULT
================================================================================
Cross-validation accuracy   : 0.3133
Cross-validation accuracy(%): 31.33%

In [145]:
print("\n" + "=" * 80)
print("PER-INTENT PERFORMANCE")
print("=" * 80)

report = classification_report(
    y,
    predictions,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report).T

display(
    report_df[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

================================================================================
PER-INTENT PERFORMANCE
================================================================================

                                  precision  recall  f1-score  support
ACCOUNT_ACCESS_SECURITY               0.000   0.000     0.000    5.000
DELIVERY_ATTEMPT_OR_INSTRUCTIONS      0.000   0.000     0.000    2.000
DELIVERY_DELAY                        0.306   0.395     0.345   38.000
DELIVERY_MISSING_OR_MISDELIVERED      0.148   0.308     0.200   13.000
DEVICE_TECHNICAL_SUPPORT              0.000   0.000     0.000    3.000
DIGITAL_CONTENT                       0.000   0.000     0.000    6.000
GIFT_CARD_PROMOTION                   0.000   0.000     0.000    2.000
ORDER_STATUS_OR_CANCELLATION          1.000   0.714     0.833    7.000
OTHER_NON_SUPPORT                     0.348   0.552     0.427   29.000
PAYMENT_BILLING                       0.000   0.000     0.000    5.000
PRIME_MEMBERSHIP                      0.000   0.000     0.000    5.000
PRODUCT_AVAILABILITY_INFORMATION      0.000   0.000     0.000    6.000
PRODUCT_PROBLEM                       0.455   0.294     0.357   17.000
RETURN_REPLACEMENT_REFUND             0.000   0.000     0.000    8.000
WEBSITE_APP_TECHNICAL                 0.667   0.500     0.571    4.000
accuracy                              0.313   0.313     0.313    0.313
macro avg                             0.195   0.184     0.182  150.000
weighted avg                          0.274   0.313     0.282  150.000

In [146]:

print("\n" + "=" * 80)
print("CONFUSION MATRIX")
print("=" * 80)

labels = sorted(y.unique())

cm = confusion_matrix(
    y,
    predictions,
    labels=labels
)

cm_df = pd.DataFrame(
    cm,
    index=labels,
    columns=labels
)

display(cm_df)

================================================================================
CONFUSION MATRIX
================================================================================

,ACCOUNT_ACCESS_SECURITY,DELIVERY_ATTEMPT_OR_INSTRUCTIONS,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,DEVICE_TECHNICAL_SUPPORT,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,ORDER_STATUS_OR_CANCELLATION,OTHER_NON_SUPPORT,PAYMENT_BILLING,PRIME_MEMBERSHIP,PRODUCT_AVAILABILITY_INFORMATION,PRODUCT_PROBLEM,RETURN_REPLACEMENT_REFUND,WEBSITE_APP_TECHNICAL
ACCOUNT_ACCESS_SECURITY,0,0,3,1,0,0,0,0,0,0,0,0,0,1,0
DELIVERY_ATTEMPT_OR_INSTRUCTIONS,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
DELIVERY_DELAY,1,0,15,9,0,0,0,0,9,1,0,0,2,1,0
DELIVERY_MISSING_OR_MISDELIVERED,0,0,8,4,0,0,0,0,0,0,0,0,1,0,0
DEVICE_TECHNICAL_SUPPORT,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0
DIGITAL_CONTENT,0,0,1,1,0,0,0,0,3,0,0,0,1,0,0
GIFT_CARD_PROMOTION,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
ORDER_STATUS_OR_CANCELLATION,0,0,1,0,0,0,0,5,1,0,0,0,0,0,0
OTHER_NON_SUPPORT,0,0,5,3,0,1,0,0,16,2,0,1,1,0,0
PAYMENT_BILLING,0,0,2,1,0,0,0,0,2,0,0,0,0,0,0
PRIME_MEMBERSHIP,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0
PRODUCT_AVAILABILITY_INFORMATION,0,0,3,0,0,0,0,0,2,0,0,0,0,0,1
PRODUCT_PROBLEM,0,0,2,5,0,0,0,0,5,0,0,0,5,0,0
RETURN_REPLACEMENT_REFUND,0,0,4,2,0,0,0,0,2,0,0,0,0,0,0
WEBSITE_APP_TECHNICAL,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2

In [147]:
errors = taxonomy_audit.copy()

errors["tfidf_prediction"] = predictions

errors = errors[
    errors["intent_label"] != errors["tfidf_prediction"]
][
    [
        "first_customer_message",
        "intent_label",
        "tfidf_prediction"
    ]
]

print("\n" + "=" * 80)
print("MISCLASSIFIED EXAMPLES")
print("=" * 80)

display(errors.head(30))

================================================================================
MISCLASSIFIED EXAMPLES
================================================================================

,first_customer_message,intent_label,tfidf_prediction
0,@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
3,I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED
5,"Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI",PRODUCT_PROBLEM,OTHER_NON_SUPPORT
7,@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice,DELIVERY_DELAY,OTHER_NON_SUPPORT
8,@AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u,PAYMENT_BILLING,DELIVERY_DELAY
9,An update : It’s still Monday. \n\n#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9,DELIVERY_DELAY,OTHER_NON_SUPPORT
10,@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.,ACCOUNT_ACCESS_SECURITY,RETURN_REPLACEMENT_REFUND
12,@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK,WEBSITE_APP_TECHNICAL,OTHER_NON_SUPPORT
13,Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄,PRIME_MEMBERSHIP,DELIVERY_DELAY
14,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,OTHER_NON_SUPPORT,DELIVERY_DELAY
17,@115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
18,Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!\nAmazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA,GIFT_CARD_PROMOTION,OTHER_NON_SUPPORT
20,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
21,@115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162,OTHER_NON_SUPPORT,DELIVERY_MISSING_OR_MISDELIVERED
23,No @118706 has informed @AmazonHelp that my packages have been damaged before they even made an attempt to ship them out,PRODUCT_PROBLEM,DELIVERY_DELAY
24,Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT,DELIVERY_DELAY,OTHER_NON_SUPPORT
25,"@115821 @117795 I've been trying to purchase a portable air purifier for the past 30 minutes, I can't find one that'll ship to CA..",PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL
27,@115851 ur staff is updatung that we are resolving &amp; rturning your money after 50 days saying product delivered that was an office adress https://t.co/Ec6xunk8wk,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
28,"@118919 Ordered an Honor 8 from Amazon Prime and received a burned damaged crappy 1200 Nokia phone, a Rin Soap and a Life Boy soap. This is an experience that we never expected from a renowned company. #badservice #amazon 9/11/17 #iwantmymoneyback https://t.co/XFukkBFBFz",PRODUCT_PROBLEM,DELIVERY_MISSING_OR_MISDELIVERED
31,@40172 when is your next season coming up?,OTHER_NON_SUPPORT,DELIVERY_DELAY
32,@115850 Ok den tell me till when I have to wait..first tym I dint got any call or msg regarding the delivery person..day is about to end..I paid to get it delivered today what if it dint happened today?,DELIVERY_DELAY,RETURN_REPLACEMENT_REFUND
33,@AmazonHelp keep rec’ng pkgs for an apt building two blocks from my house. Emails to amazon support not solving problem. Do drivers read?,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
34,@115850 cudn't deliver in 2.5 month. Amazon sellers r very bad. Amazon takes no responsibility. Cust care don't know what to do. Trapped.,DELIVERY_DELAY,ACCOUNT_ACCESS_SECURITY
36,"@AmazonHelp sir your customer care is extremly rude,and Doesn't care About the truth.i can not bear this fraud any way.i want replacement.",RETURN_REPLACEMENT_REFUND,OTHER_NON_SUPPORT
37,@115821 @AmazonHelp pre-ordered this book and it finally came in today! but with damages :/ https://t.co/BdpvGIQYPj,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
38,せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T,DIGITAL_CONTENT,OTHER_NON_SUPPORT
39,Always nice to see @115821 drivers dropping your electronics on delivery https://t.co/DQFMmAad5m,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
40,@AmazonHelp plse help .check DM and help quickly,OTHER_NON_SUPPORT,PRODUCT_PROBLEM
44,@115830 it's an absolute joke I pay for prime and now you are charging a delivery fee that was free with prime!!! Ragging 😡 #Amazon #AmazonPrime,PRIME_MEMBERSHIP,DELIVERY_DELAY
45,"@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: ""preparando envío""",ORDER_STATUS_OR_CANCELLATION,DELIVERY_DELAY

In [148]:
# train baseline model on 1150 examples
tfidf_lr.fit(X, y)

print("\n✓ TF-IDF + Logistic Regression baseline trained.")

✓ TF-IDF + Logistic Regression baseline trained.

In [149]:
# ============================================================
# STEP 61 — TF-IDF + LOGISTIC REGRESSION BASELINE
# ============================================================

import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("=" * 80)
print("TF-IDF + LOGISTIC REGRESSION BASELINE")
print("=" * 80)

# ------------------------------------------------------------
# 1. Prepare data
# ------------------------------------------------------------

X = (
    taxonomy_audit["first_customer_message"]
    .fillna("")
    .astype(str)
)

y = taxonomy_audit["intent_label"].astype(str)

print("\nExamples:", len(X))
print("Intents:", y.nunique())

print("\nClass distribution:")
print(y.value_counts())

# ------------------------------------------------------------
# 2. Pipeline
# ------------------------------------------------------------

tfidf_lr = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            strip_accents="unicode",
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )
    ),
    (
        "classifier",
        LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        )
    )
])

# ------------------------------------------------------------
# 3. Stratified cross-validation
# ------------------------------------------------------------

min_class_count = y.value_counts().min()

n_splits = min(5, min_class_count)

print(f"\nUsing {n_splits}-fold stratified cross-validation.")

cv = StratifiedKFold(
    n_splits=n_splits,
    shuffle=True,
    random_state=42
)

predictions = cross_val_predict(
    tfidf_lr,
    X,
    y,
    cv=cv
)

# ------------------------------------------------------------
# 4. Metrics
# ------------------------------------------------------------

accuracy = accuracy_score(y, predictions)

print("\n" + "=" * 80)
print("RESULT")
print("=" * 80)

print(f"Cross-validation accuracy: {accuracy:.4f}")
print(f"Cross-validation accuracy: {accuracy * 100:.2f}%")

# ------------------------------------------------------------
# 5. Classification report
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PER-INTENT PERFORMANCE")
print("=" * 80)

report = classification_report(
    y,
    predictions,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report).T

display(
    report_df[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

# ------------------------------------------------------------
# 6. Confusion matrix
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CONFUSION MATRIX")
print("=" * 80)

labels = sorted(y.unique())

cm = confusion_matrix(
    y,
    predictions,
    labels=labels
)

cm_df = pd.DataFrame(
    cm,
    index=labels,
    columns=labels
)

display(cm_df)

# ------------------------------------------------------------
# 7. Misclassified examples
# ------------------------------------------------------------

errors = taxonomy_audit.copy()

errors["tfidf_prediction"] = predictions

errors = errors[
    errors["intent_label"] != errors["tfidf_prediction"]
][
    [
        "first_customer_message",
        "intent_label",
        "tfidf_prediction"
    ]
]

print("\n" + "=" * 80)
print("MISCLASSIFIED EXAMPLES")
print("=" * 80)

display(errors.head(30))

# ------------------------------------------------------------
# 8. Train final baseline model on the 150 examples
# ------------------------------------------------------------

tfidf_lr.fit(X, y)

print("\n✓ TF-IDF + Logistic Regression baseline trained.")

================================================================================
TF-IDF + LOGISTIC REGRESSION BASELINE
================================================================================

Examples: 150
Intents: 15

Class distribution:
intent_label
DELIVERY_DELAY                      38
OTHER_NON_SUPPORT                   29
PRODUCT_PROBLEM                     17
DELIVERY_MISSING_OR_MISDELIVERED    13
RETURN_REPLACEMENT_REFUND            8
ORDER_STATUS_OR_CANCELLATION         7
PRODUCT_AVAILABILITY_INFORMATION     6
DIGITAL_CONTENT                      6
PAYMENT_BILLING                      5
ACCOUNT_ACCESS_SECURITY              5
PRIME_MEMBERSHIP                     5
WEBSITE_APP_TECHNICAL                4
DEVICE_TECHNICAL_SUPPORT             3
GIFT_CARD_PROMOTION                  2
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     2
Name: count, dtype: int64

Using 2-fold stratified cross-validation.

================================================================================
RESULT
================================================================================
Cross-validation accuracy: 0.3133
Cross-validation accuracy: 31.33%

================================================================================
PER-INTENT PERFORMANCE
================================================================================

                                  precision  recall  f1-score  support
ACCOUNT_ACCESS_SECURITY               0.000   0.000     0.000    5.000
DELIVERY_ATTEMPT_OR_INSTRUCTIONS      0.000   0.000     0.000    2.000
DELIVERY_DELAY                        0.306   0.395     0.345   38.000
DELIVERY_MISSING_OR_MISDELIVERED      0.148   0.308     0.200   13.000
DEVICE_TECHNICAL_SUPPORT              0.000   0.000     0.000    3.000
DIGITAL_CONTENT                       0.000   0.000     0.000    6.000
GIFT_CARD_PROMOTION                   0.000   0.000     0.000    2.000
ORDER_STATUS_OR_CANCELLATION          1.000   0.714     0.833    7.000
OTHER_NON_SUPPORT                     0.348   0.552     0.427   29.000
PAYMENT_BILLING                       0.000   0.000     0.000    5.000
PRIME_MEMBERSHIP                      0.000   0.000     0.000    5.000
PRODUCT_AVAILABILITY_INFORMATION      0.000   0.000     0.000    6.000
PRODUCT_PROBLEM                       0.455   0.294     0.357   17.000
RETURN_REPLACEMENT_REFUND             0.000   0.000     0.000    8.000
WEBSITE_APP_TECHNICAL                 0.667   0.500     0.571    4.000
accuracy                              0.313   0.313     0.313    0.313
macro avg                             0.195   0.184     0.182  150.000
weighted avg                          0.274   0.313     0.282  150.000

================================================================================
CONFUSION MATRIX
================================================================================

,ACCOUNT_ACCESS_SECURITY,DELIVERY_ATTEMPT_OR_INSTRUCTIONS,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,DEVICE_TECHNICAL_SUPPORT,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,ORDER_STATUS_OR_CANCELLATION,OTHER_NON_SUPPORT,PAYMENT_BILLING,PRIME_MEMBERSHIP,PRODUCT_AVAILABILITY_INFORMATION,PRODUCT_PROBLEM,RETURN_REPLACEMENT_REFUND,WEBSITE_APP_TECHNICAL
ACCOUNT_ACCESS_SECURITY,0,0,3,1,0,0,0,0,0,0,0,0,0,1,0
DELIVERY_ATTEMPT_OR_INSTRUCTIONS,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
DELIVERY_DELAY,1,0,15,9,0,0,0,0,9,1,0,0,2,1,0
DELIVERY_MISSING_OR_MISDELIVERED,0,0,8,4,0,0,0,0,0,0,0,0,1,0,0
DEVICE_TECHNICAL_SUPPORT,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0
DIGITAL_CONTENT,0,0,1,1,0,0,0,0,3,0,0,0,1,0,0
GIFT_CARD_PROMOTION,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
ORDER_STATUS_OR_CANCELLATION,0,0,1,0,0,0,0,5,1,0,0,0,0,0,0
OTHER_NON_SUPPORT,0,0,5,3,0,1,0,0,16,2,0,1,1,0,0
PAYMENT_BILLING,0,0,2,1,0,0,0,0,2,0,0,0,0,0,0
PRIME_MEMBERSHIP,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0
PRODUCT_AVAILABILITY_INFORMATION,0,0,3,0,0,0,0,0,2,0,0,0,0,0,1
PRODUCT_PROBLEM,0,0,2,5,0,0,0,0,5,0,0,0,5,0,0
RETURN_REPLACEMENT_REFUND,0,0,4,2,0,0,0,0,2,0,0,0,0,0,0
WEBSITE_APP_TECHNICAL,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2

================================================================================
MISCLASSIFIED EXAMPLES
================================================================================

,first_customer_message,intent_label,tfidf_prediction
0,@AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
3,I had an issue with delivery. Ordered on 3rd. Product is still not delivered. No help from Amazon side. Just asking me to wait @115850,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED
5,"Dear @115828 @115821 My ""allegedly"" brand new copy of Tokyo Xanadu is missing something... https://t.co/APYKHYijZI",PRODUCT_PROBLEM,OTHER_NON_SUPPORT
7,@115828 @115821 You ruined my https://t.co/uBSwBeyAjG shipping is a joke. Thanks.For real.Thanks. Made cancelling prime easy choice,DELIVERY_DELAY,OTHER_NON_SUPPORT
8,@AmazonHelp When I was adding mny there was no clearification that money cant be credited back to bank a/c I hve lost my mney I don't buy anythng frm u,PAYMENT_BILLING,DELIVERY_DELAY
9,An update : It’s still Monday. \n\n#DarkerAsToldByChristian #Darker #ChristianGreysPov #ChristianGrey https://t.co/0EZOIk2Tq9,DELIVERY_DELAY,OTHER_NON_SUPPORT
10,@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.,ACCOUNT_ACCESS_SECURITY,RETURN_REPLACEMENT_REFUND
12,@AmazonHelp I can’t unsubscribe to this. It just says “coming soon” on the page that’s loaded. I really don’t want daily @144771 emails. 🤢 https://t.co/XW16sJlszK,WEBSITE_APP_TECHNICAL,OTHER_NON_SUPPORT
13,Canceling my prime membership because @115821 has finally wasted all of my patience. Corporate America 🙄🙄🙄,PRIME_MEMBERSHIP,DELIVERY_DELAY
14,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU,OTHER_NON_SUPPORT,DELIVERY_DELAY
17,@115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
18,Get a chance to win the upcoming #Honor7X &amp; #MaxYourView by registering to get notified on @115850! Share the screenshot of your registration confirmation in the comments. 10 #Honor7X to be won!\nAmazon- https://t.co/gT93gu9IXB https://t.co/TlBT5F2DKA,GIFT_CARD_PROMOTION,OTHER_NON_SUPPORT
20,Would like some cushioning or any cushioning at all. @115850 :/ https://t.co/VSENES2n8B,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
21,@115850 worst customer service executive left between the chat you ppl are moving from bad to worse order number 404-1341814-7017162,OTHER_NON_SUPPORT,DELIVERY_MISSING_OR_MISDELIVERED
23,No @118706 has informed @AmazonHelp that my packages have been damaged before they even made an attempt to ship them out,PRODUCT_PROBLEM,DELIVERY_DELAY
24,Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT,DELIVERY_DELAY,OTHER_NON_SUPPORT
25,"@115821 @117795 I've been trying to purchase a portable air purifier for the past 30 minutes, I can't find one that'll ship to CA..",PRODUCT_AVAILABILITY_INFORMATION,WEBSITE_APP_TECHNICAL
27,@115851 ur staff is updatung that we are resolving &amp; rturning your money after 50 days saying product delivered that was an office adress https://t.co/Ec6xunk8wk,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
28,"@118919 Ordered an Honor 8 from Amazon Prime and received a burned damaged crappy 1200 Nokia phone, a Rin Soap and a Life Boy soap. This is an experience that we never expected from a renowned company. #badservice #amazon 9/11/17 #iwantmymoneyback https://t.co/XFukkBFBFz",PRODUCT_PROBLEM,DELIVERY_MISSING_OR_MISDELIVERED
31,@40172 when is your next season coming up?,OTHER_NON_SUPPORT,DELIVERY_DELAY
32,@115850 Ok den tell me till when I have to wait..first tym I dint got any call or msg regarding the delivery person..day is about to end..I paid to get it delivered today what if it dint happened today?,DELIVERY_DELAY,RETURN_REPLACEMENT_REFUND
33,@AmazonHelp keep rec’ng pkgs for an apt building two blocks from my house. Emails to amazon support not solving problem. Do drivers read?,DELIVERY_MISSING_OR_MISDELIVERED,DELIVERY_DELAY
34,@115850 cudn't deliver in 2.5 month. Amazon sellers r very bad. Amazon takes no responsibility. Cust care don't know what to do. Trapped.,DELIVERY_DELAY,ACCOUNT_ACCESS_SECURITY
36,"@AmazonHelp sir your customer care is extremly rude,and Doesn't care About the truth.i can not bear this fraud any way.i want replacement.",RETURN_REPLACEMENT_REFUND,OTHER_NON_SUPPORT
37,@115821 @AmazonHelp pre-ordered this book and it finally came in today! but with damages :/ https://t.co/BdpvGIQYPj,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
38,せっかくプライム会員なので30日間だけアマゾンミュージコお試しで〜。 https://t.co/MVdp7mPd3T,DIGITAL_CONTENT,OTHER_NON_SUPPORT
39,Always nice to see @115821 drivers dropping your electronics on delivery https://t.co/DQFMmAad5m,PRODUCT_PROBLEM,OTHER_NON_SUPPORT
40,@AmazonHelp plse help .check DM and help quickly,OTHER_NON_SUPPORT,PRODUCT_PROBLEM
44,@115830 it's an absolute joke I pay for prime and now you are charging a delivery fee that was free with prime!!! Ragging 😡 #Amazon #AmazonPrime,PRIME_MEMBERSHIP,DELIVERY_DELAY
45,"@116875 hace 6 días compre un disco duro y es fecha que en el estatus de envío sigue diciendo: ""preparando envío""",ORDER_STATUS_OR_CANCELLATION,DELIVERY_DELAY

✓ TF-IDF + Logistic Regression baseline trained.

| Baseline | Accuracy | Macro F1 |
|---|---|---|
| Zero-shot semantic similarity | 30.7% | 27.6% |
| TF-IDF + Logistic Regression | 31.3% | 18.2% |

Majority Class Baseline

In [150]:
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

print("=" * 80)
print("MAJORITY-CLASS BASELINE")
print("=" * 80)

# Ground-truth labels from the 150 human-labelled audit
y_true = taxonomy_audit["intent_label"].astype(str)

# Most frequent class
majority_class = y_true.value_counts().idxmax()
majority_count = y_true.value_counts().max()

# Predict the same class for every example
majority_predictions = np.repeat(
    majority_class,
    len(y_true)
)

accuracy = accuracy_score(
    y_true,
    majority_predictions
)

print(f"\nMajority class: {majority_class}")
print(f"Majority examples: {majority_count}/{len(y_true)}")

print(f"\nAccuracy: {accuracy:.4f}")
print(f"Accuracy: {accuracy * 100:.2f}%")

print("\n" + "=" * 80)
print("CLASSIFICATION REPORT")
print("=" * 80)

report = classification_report(
    y_true,
    majority_predictions,
    output_dict=True,
    zero_division=0
)

majority_report = pd.DataFrame(report).T

display(
    majority_report[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

print("\n✓ Majority baseline complete.")

================================================================================
MAJORITY-CLASS BASELINE
================================================================================

Majority class: DELIVERY_DELAY
Majority examples: 38/150

Accuracy: 0.2533
Accuracy: 25.33%

================================================================================
CLASSIFICATION REPORT
================================================================================

                                  precision  recall  f1-score  support
ACCOUNT_ACCESS_SECURITY               0.000   0.000     0.000    5.000
DELIVERY_ATTEMPT_OR_INSTRUCTIONS      0.000   0.000     0.000    2.000
DELIVERY_DELAY                        0.253   1.000     0.404   38.000
DELIVERY_MISSING_OR_MISDELIVERED      0.000   0.000     0.000   13.000
DEVICE_TECHNICAL_SUPPORT              0.000   0.000     0.000    3.000
DIGITAL_CONTENT                       0.000   0.000     0.000    6.000
GIFT_CARD_PROMOTION                   0.000   0.000     0.000    2.000
ORDER_STATUS_OR_CANCELLATION          0.000   0.000     0.000    7.000
OTHER_NON_SUPPORT                     0.000   0.000     0.000   29.000
PAYMENT_BILLING                       0.000   0.000     0.000    5.000
PRIME_MEMBERSHIP                      0.000   0.000     0.000    5.000
PRODUCT_AVAILABILITY_INFORMATION      0.000   0.000     0.000    6.000
PRODUCT_PROBLEM                       0.000   0.000     0.000   17.000
RETURN_REPLACEMENT_REFUND             0.000   0.000     0.000    8.000
WEBSITE_APP_TECHNICAL                 0.000   0.000     0.000    4.000
accuracy                              0.253   0.253     0.253    0.253
macro avg                             0.017   0.067     0.027  150.000
weighted avg                          0.064   0.253     0.102  150.000

✓ Majority baseline complete.

| Baseline | Accuracy | Macro F1 |
|---|---|---|
| Majority class | 25.33% | 2.7% |
| Zero-shot semantic similarity | 30.7% | 27.6% |
| TF-IDF + Logistic Regression | 31.3% | 18.2% |

GOLDEN/AUDIT LABEL DISTRIBUTION BY CONVERSATION SIZE

In [151]:
print("=" * 80)
print("TAXONOMY AUDIT DISTRIBUTION BY CONVERSATION SIZE")
print("=" * 80)

distribution = pd.crosstab(
    taxonomy_audit["size_bucket"],
    taxonomy_audit["intent_label"]
)

display(distribution)

print("\n" + "=" * 80)
print("ROW-WISE PERCENTAGES")
print("=" * 80)

distribution_pct = pd.crosstab(
    taxonomy_audit["size_bucket"],
    taxonomy_audit["intent_label"],
    normalize="index"
) * 100

display(
    distribution_pct.round(1)
)

print("\n" + "=" * 80)
print("INTENT COUNTS")
print("=" * 80)

intent_counts = (
    taxonomy_audit["intent_label"]
    .value_counts()
    .rename_axis("intent")
    .reset_index(name="count")
)

intent_counts["percentage"] = (
    intent_counts["count"] / len(taxonomy_audit) * 100
)

display(intent_counts.round(2))

print("\n✓ Distribution audit complete.")

================================================================================
TAXONOMY AUDIT DISTRIBUTION BY CONVERSATION SIZE
================================================================================

intent_label,ACCOUNT_ACCESS_SECURITY,DELIVERY_ATTEMPT_OR_INSTRUCTIONS,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,DEVICE_TECHNICAL_SUPPORT,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,ORDER_STATUS_OR_CANCELLATION,OTHER_NON_SUPPORT,PAYMENT_BILLING,PRIME_MEMBERSHIP,PRODUCT_AVAILABILITY_INFORMATION,PRODUCT_PROBLEM,RETURN_REPLACEMENT_REFUND,WEBSITE_APP_TECHNICAL
size_bucket,,,,,,,,,,,,,,,
2_tweets,0,0,7,4,1,2,0,1,14,0,2,0,4,0,3
3_to_4_tweets,1,0,9,1,0,1,1,1,7,2,2,2,7,3,0
5_to_8_tweets,3,0,12,6,1,0,0,3,2,1,1,2,1,4,1
9_plus_tweets,1,2,10,2,1,3,1,2,6,2,0,2,5,1,0

================================================================================
ROW-WISE PERCENTAGES
================================================================================

intent_label,ACCOUNT_ACCESS_SECURITY,DELIVERY_ATTEMPT_OR_INSTRUCTIONS,DELIVERY_DELAY,DELIVERY_MISSING_OR_MISDELIVERED,DEVICE_TECHNICAL_SUPPORT,DIGITAL_CONTENT,GIFT_CARD_PROMOTION,ORDER_STATUS_OR_CANCELLATION,OTHER_NON_SUPPORT,PAYMENT_BILLING,PRIME_MEMBERSHIP,PRODUCT_AVAILABILITY_INFORMATION,PRODUCT_PROBLEM,RETURN_REPLACEMENT_REFUND,WEBSITE_APP_TECHNICAL
size_bucket,,,,,,,,,,,,,,,
2_tweets,0.0,0.0,18.4,10.5,2.6,5.3,0.0,2.6,36.8,0.0,5.3,0.0,10.5,0.0,7.9
3_to_4_tweets,2.7,0.0,24.3,2.7,0.0,2.7,2.7,2.7,18.9,5.4,5.4,5.4,18.9,8.1,0.0
5_to_8_tweets,8.1,0.0,32.4,16.2,2.7,0.0,0.0,8.1,5.4,2.7,2.7,5.4,2.7,10.8,2.7
9_plus_tweets,2.6,5.3,26.3,5.3,2.6,7.9,2.6,5.3,15.8,5.3,0.0,5.3,13.2,2.6,0.0

================================================================================
INTENT COUNTS
================================================================================

                              intent  count  percentage
0                     DELIVERY_DELAY     38       25.33
1                  OTHER_NON_SUPPORT     29       19.33
2                    PRODUCT_PROBLEM     17       11.33
3   DELIVERY_MISSING_OR_MISDELIVERED     13        8.67
4          RETURN_REPLACEMENT_REFUND      8        5.33
5       ORDER_STATUS_OR_CANCELLATION      7        4.67
6   PRODUCT_AVAILABILITY_INFORMATION      6        4.00
7                    DIGITAL_CONTENT      6        4.00
8                    PAYMENT_BILLING      5        3.33
9            ACCOUNT_ACCESS_SECURITY      5        3.33
10                  PRIME_MEMBERSHIP      5        3.33
11             WEBSITE_APP_TECHNICAL      4        2.67
12          DEVICE_TECHNICAL_SUPPORT      3        2.00
13               GIFT_CARD_PROMOTION      2        1.33
14  DELIVERY_ATTEMPT_OR_INSTRUCTIONS      2        1.33

✓ Distribution audit complete.

CREATE STRATIFIED TRAINING LABELING POOL

In [152]:
from pathlib import Path
import pandas as pd

print("=" * 80)
print("RELOADING AMAZONHELP CONVERSATION SPLITS")
print("=" * 80)

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

split_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v2.csv"
)

print("\nFile:")
print(split_path)

if not split_path.exists():
    raise FileNotFoundError(
        f"Split file not found:\n{split_path}"
    )

amazonhelp_conversation_splits_v2 = pd.read_csv(
    split_path
)

print("\n✓ File loaded.")
print("Rows:", len(amazonhelp_conversation_splits_v2))
print(
    "Columns:",
    list(amazonhelp_conversation_splits_v2.columns)
)

================================================================================
RELOADING AMAZONHELP CONVERSATION SPLITS
================================================================================

File:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits_v2.csv

✓ File loaded.
Rows: 82246
Columns: ['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'split', 'is_taxonomy_audit']

In [153]:
print("=" * 80)
print("EXISTING AMAZONHELP SPLIT — ACTUAL VALUES")
print("=" * 80)

print("\nSplit distribution:")
print(
    amazonhelp_conversation_splits_v2["split"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nExact split counts:")
for split_name, count in (
    amazonhelp_conversation_splits_v2["split"]
    .value_counts(dropna=False)
    .items()
):
    print(f"{repr(split_name):15s} : {count}")

print("\nTaxonomy audit distribution:")
print(
    amazonhelp_conversation_splits_v2["is_taxonomy_audit"]
    .value_counts(dropna=False)
)

print("\nFirst 5 rows:")
display(
    amazonhelp_conversation_splits_v2.head()
)

print("\n✓ Inspection complete.")

================================================================================
EXISTING AMAZONHELP SPLIT — ACTUAL VALUES
================================================================================

Split distribution:
split
test           8225
train         65796
validation     8225
Name: count, dtype: int64

Exact split counts:
'train'         : 65796
'test'          : 8225
'validation'    : 8225

Taxonomy audit distribution:
is_taxonomy_audit
False    82096
True       150
Name: count, dtype: int64

First 5 rows:

,conversation_id,first_customer_message,last_customer_message,first_support_message,last_support_message,conversation_text,customer_turns,support_turns,conversation_size,start_time,end_time,duration_minutes,support_account,size_bucket,split,is_taxonomy_audit
0,272,amazonのfireTVstickが見れない😢,@AmazonHelp こちらこそありがとうございました。,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET,[CUSTOMER] amazonのfireTVstickが見れない😢\n[SUPPORT] @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET\n[CUSTOMER] @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。\n[CUSTOMER] @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[SUPPORT] @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET\n[CUSTOMER] @AmazonHelp こちらこそありがとうございました。\n[SUPPORT] @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET,4,3,7,2017-11-22 09:14:39+00:00,2017-11-22 10:06:26+00:00,51.783333,AmazonHelp,5_to_8_tweets,train,False
1,325,amazonプライムビデオ、再生エラーが多いです,amazonプライムビデオ、再生エラーが多いです,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET,[CUSTOMER] amazonプライムビデオ、再生エラーが多いです\n[SUPPORT] @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET,1,1,2,2017-11-22 08:55:35+00:00,2017-11-22 09:06:00+00:00,10.416667,AmazonHelp,2_tweets,train,False
2,617,Way to drop the ball on customer service @115821 so pissed right now!,"@AmazonHelp I frankly don't have the patience for another chat with your ""customer service"" people today.","@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN",@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG,"[CUSTOMER] Way to drop the ball on customer service @115821 so pissed right now!\n[SUPPORT] @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN\n[CUSTOMER] @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day\n[SUPPORT] @115820 We'd like to take a further look into this with you! Please reach us by phone or chat here:...",3,2,5,2017-10-31 22:16:32+00:00,2017-10-31 23:32:26+00:00,75.900000,AmazonHelp,5_to_8_tweets,train,False
3,621,@115823 I want my amazon payments account CLOSED. dm me please.,@115823 I want my amazon payments account CLOSED. dm me please.,"@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH","@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH","[CUSTOMER] @115823 I want my amazon payments account CLOSED. dm me please.\n[SUPPORT] @115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH",1,1,2,2017-10-31 22:19:34+00:00,2017-10-31 22:28:34+00:00,9.000000,AmazonHelp,2_tweets,train,False
4,624,"@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?","@AmazonHelp Okay, danke für die Info","@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS",@115824 Wir haben zu danken. Schönen Abend noch. ^JS,"[CUSTOMER] @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?\n[SUPPORT] @115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS\n[CUSTOMER] @AmazonHelp Okay, danke für die Info\n[SUPPORT] @115824 Wir haben zu danken. Schönen Abend noch. ^JS",2,2,4,2017-10-31 22:12:37+00:00,2017-10-31 22:34:32+00:00,21.916667,AmazonHelp,3_to_4_tweets,train,False

✓ Inspection complete.

In [154]:
print("=" * 80)
print("CREATE CLEAN AMAZONHELP LABELING POOL")
print("=" * 80)

# train only
train_pool = amazonhelp_conversation_splits_v2[
    (amazonhelp_conversation_splits_v2["split"] == "train") &
    (amazonhelp_conversation_splits_v2["is_taxonomy_audit"] == False)
].copy()

print("\nClean training pool:", len(train_pool))

# verify taxonomy audit exclusions
assert train_pool["is_taxonomy_audit"].eq(False).all()

print("✓ 150 taxonomy-audit examples excluded.")

================================================================================
CREATE CLEAN AMAZONHELP LABELING POOL
================================================================================

Clean training pool: 65678
✓ 150 taxonomy-audit examples excluded.

In [155]:
BUCKETS = [
    "2_tweets",
    "3_to_4_tweets",
    "5_to_8_tweets",
    "9_plus_tweets"
]

SAMPLES_PER_BUCKET = 375

pool_parts = []

print("\nSampling:")

for bucket in BUCKETS:

    bucket_df = train_pool[
        train_pool["size_bucket"] == bucket
    ]

    sample = bucket_df.sample(
        n=SAMPLES_PER_BUCKET,
        random_state=42
    )

    pool_parts.append(sample)

    print(
        f"{bucket:20s} "
        f"available={len(bucket_df):6d} "
        f"sampled={len(sample):4d}"
    )

Sampling:
2_tweets             available= 25029 sampled= 375
3_to_4_tweets        available= 20388 sampled= 375
5_to_8_tweets        available= 14201 sampled= 375
9_plus_tweets        available=  6060 sampled= 375

In [156]:
labeling_pool = pd.concat(
    pool_parts,
    ignore_index=True
)

labeling_pool = labeling_pool.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [157]:

labeling_pool["intent_label"] = ""
labeling_pool["annotation_notes"] = ""
labeling_pool["annotator"] = ""

assert len(labeling_pool) == 1500

assert labeling_pool["split"].eq("train").all()

assert labeling_pool["is_taxonomy_audit"].eq(False).all()

assert labeling_pool["size_bucket"].value_counts().to_dict() == {
    "2_tweets": 375,
    "3_to_4_tweets": 375,
    "5_to_8_tweets": 375,
    "9_plus_tweets": 375
}

print("\n" + "=" * 80)
print("LABELING POOL")
print("=" * 80)

print("Total:", len(labeling_pool))

print("\nSize-bucket distribution:")
print(
    labeling_pool["size_bucket"]
    .value_counts()
    .sort_index()
)

labeling_pool_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_labeling_pool_1500.csv"
)

labeling_pool.to_csv(
    labeling_pool_path,
    index=False
)

print("\n✓ Saved:")
print(labeling_pool_path)

print("\n✓ CLEAN TRAINING LABELING POOL CREATED.")

================================================================================
LABELING POOL
================================================================================
Total: 1500

Size-bucket distribution:
size_bucket
2_tweets         375
3_to_4_tweets    375
5_to_8_tweets    375
9_plus_tweets    375
Name: count, dtype: int64

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_labeling_pool_1500.csv

✓ CLEAN TRAINING LABELING POOL CREATED.

In [158]:
# ============================================================
# STEP 64C — CREATE CLEAN TRAINING LABELING POOL
# ============================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("CREATE CLEAN AMAZONHELP LABELING POOL")
print("=" * 80)

# ------------------------------------------------------------
# 1. TRAIN ONLY
# ------------------------------------------------------------

train_pool = amazonhelp_conversation_splits_v2[
    (amazonhelp_conversation_splits_v2["split"] == "train") &
    (amazonhelp_conversation_splits_v2["is_taxonomy_audit"] == False)
].copy()

print("\nClean training pool:", len(train_pool))

# ------------------------------------------------------------
# 2. Verify taxonomy audit is excluded
# ------------------------------------------------------------

assert train_pool["is_taxonomy_audit"].eq(False).all()

print("✓ 150 taxonomy-audit examples excluded.")

# ------------------------------------------------------------
# 3. Sample equally across conversation-size buckets
# ------------------------------------------------------------

BUCKETS = [
    "2_tweets",
    "3_to_4_tweets",
    "5_to_8_tweets",
    "9_plus_tweets"
]

SAMPLES_PER_BUCKET = 375

pool_parts = []

print("\nSampling:")

for bucket in BUCKETS:

    bucket_df = train_pool[
        train_pool["size_bucket"] == bucket
    ]

    sample = bucket_df.sample(
        n=SAMPLES_PER_BUCKET,
        random_state=42
    )

    pool_parts.append(sample)

    print(
        f"{bucket:20s} "
        f"available={len(bucket_df):6d} "
        f"sampled={len(sample):4d}"
    )

# ------------------------------------------------------------
# 4. Combine and shuffle
# ------------------------------------------------------------

labeling_pool = pd.concat(
    pool_parts,
    ignore_index=True
)

labeling_pool = labeling_pool.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# ------------------------------------------------------------
# 5. Annotation columns
# ------------------------------------------------------------

labeling_pool["intent_label"] = ""
labeling_pool["annotation_notes"] = ""
labeling_pool["annotator"] = ""

# ------------------------------------------------------------
# 6. Safety checks
# ------------------------------------------------------------

assert len(labeling_pool) == 1500

assert labeling_pool["split"].eq("train").all()

assert labeling_pool["is_taxonomy_audit"].eq(False).all()

assert labeling_pool["size_bucket"].value_counts().to_dict() == {
    "2_tweets": 375,
    "3_to_4_tweets": 375,
    "5_to_8_tweets": 375,
    "9_plus_tweets": 375
}

# ------------------------------------------------------------
# 7. Show distribution
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("LABELING POOL")
print("=" * 80)

print("Total:", len(labeling_pool))

print("\nSize-bucket distribution:")
print(
    labeling_pool["size_bucket"]
    .value_counts()
    .sort_index()
)

# ------------------------------------------------------------
# 8. Save
# ------------------------------------------------------------

labeling_pool_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_labeling_pool_1500.csv"
)

labeling_pool.to_csv(
    labeling_pool_path,
    index=False
)

print("\n✓ Saved:")
print(labeling_pool_path)

print("\n✓ CLEAN TRAINING LABELING POOL CREATED.")

================================================================================
CREATE CLEAN AMAZONHELP LABELING POOL
================================================================================

Clean training pool: 65678
✓ 150 taxonomy-audit examples excluded.

Sampling:
2_tweets             available= 25029 sampled= 375
3_to_4_tweets        available= 20388 sampled= 375
5_to_8_tweets        available= 14201 sampled= 375
9_plus_tweets        available=  6060 sampled= 375

================================================================================
LABELING POOL
================================================================================
Total: 1500

Size-bucket distribution:
size_bucket
2_tweets         375
3_to_4_tweets    375
5_to_8_tweets    375
9_plus_tweets    375
Name: count, dtype: int64

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_labeling_pool_1500.csv

✓ CLEAN TRAINING LABELING POOL CREATED.

only 118 of the 150 audit examples are being excluded from train, implying some audit examples may be sitting in validation/test

In [159]:
print("=" * 80)
print("TAXONOMY AUDIT PLACEMENT CHECK")
print("=" * 80)

audit_rows = amazonhelp_conversation_splits_v2[
    amazonhelp_conversation_splits_v2["is_taxonomy_audit"] == True
].copy()

print("\nTotal taxonomy-audit examples:", len(audit_rows))

print("\nAudit examples by split:")
audit_split_counts = (
    audit_rows["split"]
    .value_counts(dropna=False)
    .sort_index()
)

print(audit_split_counts)

print("\nDetailed split × audit status:")
display(
    pd.crosstab(
        amazonhelp_conversation_splits_v2["split"],
        amazonhelp_conversation_splits_v2["is_taxonomy_audit"]
    )
)

print("\n" + "=" * 80)
print("AUDIT EXAMPLES OUTSIDE TRAIN")
print("=" * 80)

outside_train = audit_rows[
    audit_rows["split"] != "train"
]

print("Count:", len(outside_train))

if len(outside_train) > 0:
    display(
        outside_train[
            [
                "conversation_id",
                "split",
                "is_taxonomy_audit",
                "first_customer_message"
            ]
        ].head(50)
    )

print("\n✓ Audit placement check complete.")

================================================================================
TAXONOMY AUDIT PLACEMENT CHECK
================================================================================

Total taxonomy-audit examples: 150

Audit examples by split:
split
test           20
train         118
validation     12
Name: count, dtype: int64

Detailed split × audit status:

is_taxonomy_audit  False  True
split
test                8205     20
train              65678    118
validation          8213     12

================================================================================
AUDIT EXAMPLES OUTSIDE TRAIN
================================================================================
Count: 32

,conversation_id,split,is_taxonomy_audit,first_customer_message
1848,80798,test,True,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently.
4034,152192,test,True,I have ordered so many books from @115850 . But everytime I get the same old boring bookmarks. Could you please send me some really cool exciting bookmarks for my next order of book?.
5716,210526,test,True,2nd time failed frm pymnt gatway fr bokng iphone6 32Gb gray cost 20k thn imdate incrsd to 26450.Wht's offr running don't undrstnd @115850 https://t.co/7edeUhB53O
7820,271576,test,True,Hey @117795 you've delayed a delivery once again. One more time and I'll be exploring options like @2300
9932,318900,test,True,@115850 very very bad product delivrd by amazon.my brother ordrd the lg phone Prodct output is not atleast 20 % wt dey gives in discrption
10118,321644,test,True,@AmazonHelp plse help .check DM and help quickly
12042,375828,test,True,Prolly shoulda used better judgement on a Sunday delivery from @115821 but I PAID THE SHIPPING COST. WHERE'S MY STUFF??
12649,386412,test,True,"Man... my @115821 package has been ""preparing"" for almost two days straight now... getting really #worried it won't ""arrive tomorrow"""
16227,478452,test,True,I am watching Shin Chan Season 1. But currently it is not available to my location. Why are you people doing like this? @119625
20975,627702,validation,True,@AmazonHelp I have a parcel which says delivered but was not delivered to me. Could you help me track down where this was delivered please? @115821 @115830
22338,679032,validation,True,Prime now turkey tracker. https://t.co/90UMXDP11e
23072,707947,validation,True,@AmazonHelp There's no option of changing the Registered Mobile Number in your App. Need to change the number urgently. Pl help.
25529,792025,test,True,".@115830 Have sent me 2 boxes of 6 bottles of shampoo instead of the 2 I ordered in mistake, as I meant to order the conditioner. 🙈"
29245,930385,validation,True,"@AmazonHelp I need help I made an order on 12 November and until the 20 of November has not yet sent it, they were quick with the pay, but on slow shipping, I subscribed to amazon prime to see how it works, but I see that it was a loss of money It's not worth it."
33888,1106540,test,True,Bought stickers from @115821 and they came all bent 😩
34522,1125063,test,True,@AmazonHelp can you help me fix my two factor authentication issue? Got a new phone but the website has been less than helpful in setting up 2FA on the new device.
43323,1429422,validation,True,@115821 it was showing that the product will be deliverd to me in 2 days guaranteed.\nOrderd it on sunday still waiting to get it (2/2)
51642,1735260,test,True,Per @120540 6+2 fa 10. Non c’è più la rapidità e precisione di una volta. Nonostante Amazon Prime #amazon #ritardi #amazonprime https://t.co/cTbctKQxdV
53750,1875465,test,True,@115850 when will I get my refund or claim refund from seller ? Faulty roduct have been couriered to them and was delivered 4 days back.
55926,2107331,test,True,Amazon Music Unlimited に登録してみた。Amazon Echoで登録すると、月額380円と格安だったわ。
56149,2117819,validation,True,@AmazonHelp What has happened to Prime One Day Delivery? Both parcels I ordered last week have taken 3-4 days and one of them still isn't here...
59574,2279881,validation,True,"Can’t believe @115830’s response to me asking why my Xbox One X hasn’t been despatched yet. “If you’re not happy with it, cancel”"
60867,2301887,test,True,@AmazonHelp https://t.co/9eUtPo7MRN
62937,2371416,validation,True,Um Amazon...if you are going to deliver...you need to have your customers be able to contact the delivery person directly! I want my stuff tonight!!! I should be able to contact them back directly! @115821
64464,2419144,validation,True,@AmazonHelp oui depuis hier
65307,2452519,test,True,Hey @115830 please pay my seller funds which has been held for over 115 days! __email__ https://t.co/Iua8OUsUfU
65653,2462189,test,True,@AmazonHelp with reference to my earlier tweet I haven't received any conversation from ur side @115821\nI have already drop my details
68687,2569451,validation,True,@AmazonHelp keep rec’ng pkgs for an apt building two blocks from my house. Emails to amazon support not solving problem. Do drivers read?
71429,2671989,validation,True,"@AmazonHelp Bonjour, on peut se DM ?"
74384,2774111,test,True,"@116875 ¿Qué hago, Amazon? Hice una devolución y @178440 no tiene idea de mi paquete. Selló la guía (aún la tengo) y dice que no lo he enviado."
74440,2776337,test,True,@AmazonHelp I have been double charged and left penniless. The person I spoke to was worse than useless how do I make a formal complaint
78017,2878652,validation,True,@AmazonHelp I’m trying to buy something but I can’t use my gift card it won’t let me

✓ Audit placement check complete.

- TRAIN      - 65,678 clean + 118 audit
- VALIDATION -  8,213 clean + 12 audit
- TEST       -  8,205 clean + 20 audit
- AUDIT      -     150 total

32 of 150 manually labelled taxonomy-audit examples leaked into validation/test.

create clean split v3

In [160]:
print("=" * 80)
print("CREATE CLEAN AMAZONHELP SPLIT V3")
print("=" * 80)

df = amazonhelp_conversation_splits_v2.copy()

df["original_split"] = df["split"]

audit_mask = df["is_taxonomy_audit"] == True
df.loc[audit_mask, "split"] = "audit"

print("\nClean split distribution:")

split_counts = (
    df["split"]
    .value_counts()
    .sort_index()
)

print(split_counts)

================================================================================
CREATE CLEAN AMAZONHELP SPLIT V3
================================================================================

Clean split distribution:
split
audit           150
test           8205
train         65678
validation     8213
Name: count, dtype: int64

In [161]:
audit_rows = df[df["split"] == "audit"]

assert len(audit_rows) == 150

assert audit_rows["is_taxonomy_audit"].eq(True).all()

assert (
    df.loc[df["split"] != "audit", "is_taxonomy_audit"]
    .eq(False)
    .all()
)

assert len(df) == 82246
assert df["conversation_id"].is_unique

In [162]:
clean_split_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v3.csv"
)

df.to_csv(
    clean_split_path,
    index=False
)

print("\n" + "=" * 80)
print("FINAL VERIFICATION")
print("=" * 80)

print("Total rows:", len(df))
print("Unique conversations:", df["conversation_id"].nunique())

print("\nSplit counts:")
print(df["split"].value_counts().sort_index())

print("\nAudit counts:")
print(
    pd.crosstab(
        df["split"],
        df["is_taxonomy_audit"]
    )
)

print("\n✓ Clean split v3 saved:")
print(clean_split_path)

================================================================================
FINAL VERIFICATION
================================================================================
Total rows: 82246
Unique conversations: 82246

Split counts:
split
audit           150
test           8205
train         65678
validation     8213
Name: count, dtype: int64

Audit counts:
is_taxonomy_audit  False  True
split
audit                  0    150
test                8205      0
train              65678      0
validation          8213      0

✓ Clean split v3 saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits_v3.csv

In [163]:
# ============================================================
# STEP 64E — CREATE CLEAN SPLIT V3
# ============================================================

import pandas as pd
from pathlib import Path

print("=" * 80)
print("CREATE CLEAN AMAZONHELP SPLIT V3")
print("=" * 80)

df = amazonhelp_conversation_splits_v2.copy()

# ------------------------------------------------------------
# 1. Preserve original split
# ------------------------------------------------------------

df["original_split"] = df["split"]

# ------------------------------------------------------------
# 2. Move ALL taxonomy-audit examples to dedicated audit split
# ------------------------------------------------------------

audit_mask = df["is_taxonomy_audit"] == True

df.loc[audit_mask, "split"] = "audit"

# ------------------------------------------------------------
# 3. Verify clean split counts
# ------------------------------------------------------------

print("\nClean split distribution:")

split_counts = (
    df["split"]
    .value_counts()
    .sort_index()
)

print(split_counts)

# Expected:
# audit         150
# test         8205
# train       65678
# validation   8213

# ------------------------------------------------------------
# 4. Verify audit isolation
# ------------------------------------------------------------

audit_rows = df[df["split"] == "audit"]

assert len(audit_rows) == 150

assert audit_rows["is_taxonomy_audit"].eq(True).all()

assert (
    df.loc[df["split"] != "audit", "is_taxonomy_audit"]
    .eq(False)
    .all()
)

# ------------------------------------------------------------
# 5. Verify no rows were lost
# ------------------------------------------------------------

assert len(df) == 82246

# ------------------------------------------------------------
# 6. Verify conversation IDs remain unique
# ------------------------------------------------------------

assert df["conversation_id"].is_unique

# ------------------------------------------------------------
# 7. Save clean split
# ------------------------------------------------------------

clean_split_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v3.csv"
)

df.to_csv(
    clean_split_path,
    index=False
)

print("\n" + "=" * 80)
print("FINAL VERIFICATION")
print("=" * 80)

print("Total rows:", len(df))
print("Unique conversations:", df["conversation_id"].nunique())

print("\nSplit counts:")
print(df["split"].value_counts().sort_index())

print("\nAudit counts:")
print(
    pd.crosstab(
        df["split"],
        df["is_taxonomy_audit"]
    )
)

print("\n✓ Clean split v3 saved:")
print(clean_split_path)

================================================================================
CREATE CLEAN AMAZONHELP SPLIT V3
================================================================================

Clean split distribution:
split
audit           150
test           8205
train         65678
validation     8213
Name: count, dtype: int64

================================================================================
FINAL VERIFICATION
================================================================================
Total rows: 82246
Unique conversations: 82246

Split counts:
split
audit           150
test           8205
train         65678
validation     8213
Name: count, dtype: int64

Audit counts:
is_taxonomy_audit  False  True
split
audit                  0    150
test                8205      0
train              65678      0
validation          8213      0

✓ Clean split v3 saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_conversation_splits_v3.csv

now have a clean, defensible split

In [164]:
from pathlib import Path
import pandas as pd

print("=" * 80)
print("LOAD CLEAN AMAZONHELP SPLIT V3")
print("=" * 80)

split_v3_path = (
    PROCESSED_DIR /
    "amazonhelp_conversation_splits_v3.csv"
)

amazonhelp_splits = pd.read_csv(
    split_v3_path
)

print("\nRows:", len(amazonhelp_splits))

print("\nSplit distribution:")
print(
    amazonhelp_splits["split"]
    .value_counts()
    .sort_index()
)

================================================================================
LOAD CLEAN AMAZONHELP SPLIT V3
================================================================================

Rows: 82246

Split distribution:
split
audit           150
test           8205
train         65678
validation     8213
Name: count, dtype: int64

In [165]:
assert len(amazonhelp_splits) == 82246
assert amazonhelp_splits["conversation_id"].is_unique

assert (
    amazonhelp_splits.loc[
        amazonhelp_splits["split"] != "audit",
        "is_taxonomy_audit"
    ].eq(False).all()
)

assert (
    amazonhelp_splits.loc[
        amazonhelp_splits["split"] == "audit",
        "is_taxonomy_audit"
    ].eq(True).all()
)

print("\n✓ v3 is now the official working split.")

print("\nOfficial datasets:")
print("Train:", len(amazonhelp_splits[amazonhelp_splits["split"] == "train"]))
print("Validation:", len(amazonhelp_splits[amazonhelp_splits["split"] == "validation"]))
print("Test:", len(amazonhelp_splits[amazonhelp_splits["split"] == "test"]))
print("Audit:", len(amazonhelp_splits[amazonhelp_splits["split"] == "audit"]))

✓ v3 is now the official working split.

Official datasets:
Train: 65678
Validation: 8213
Test: 8205
Audit: 150

In [166]:
print("=" * 80)
print("CREATE HUMAN-LABELLED TRAINING BATCH 1")
print("=" * 80)

labeling_pool_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_labeling_pool_1500.csv"
)

labeling_pool = pd.read_csv(
    labeling_pool_path
)

print("\nLabeling pool:", len(labeling_pool))

assert len(labeling_pool) == 1500

assert labeling_pool["split"].eq("train").all()

assert labeling_pool["is_taxonomy_audit"].eq(False).all()

================================================================================
CREATE HUMAN-LABELLED TRAINING BATCH 1
================================================================================

Labeling pool: 1500

In [167]:
BUCKETS = [
    "2_tweets",
    "3_to_4_tweets",
    "5_to_8_tweets",
    "9_plus_tweets"
]

BATCH_SIZE_PER_BUCKET = 75

batch_parts = []

for bucket in BUCKETS:

    bucket_df = labeling_pool[
        labeling_pool["size_bucket"] == bucket
    ].copy()

    # Deterministic sampling
    batch = bucket_df.sample(
        n=BATCH_SIZE_PER_BUCKET,
        random_state=42
    )

    batch_parts.append(batch)

    print(
        f"{bucket:20s}: "
        f"{len(batch)} selected"
    )

2_tweets            : 75 selected
3_to_4_tweets       : 75 selected
5_to_8_tweets       : 75 selected
9_plus_tweets       : 75 selected

In [168]:
training_batch_1 = pd.concat(
    batch_parts,
    ignore_index=True
)

training_batch_1 = training_batch_1.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [169]:
training_batch_1["intent_label"] = ""

training_batch_1["annotation_notes"] = ""

training_batch_1["annotator"] = ""

training_batch_1["annotation_status"] = "UNLABELED"

In [170]:
assert len(training_batch_1) == 300

assert (
    training_batch_1["size_bucket"]
    .value_counts()
    .to_dict()
    == {
        "2_tweets": 75,
        "3_to_4_tweets": 75,
        "5_to_8_tweets": 75,
        "9_plus_tweets": 75
    }
)

assert training_batch_1["split"].eq("train").all()

assert training_batch_1["is_taxonomy_audit"].eq(False).all()

assert training_batch_1["conversation_id"].is_unique

In [171]:
training_batch_1_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_training_batch_01.csv"
)

training_batch_1.to_csv(
    training_batch_1_path,
    index=False
)

print("\n" + "=" * 80)
print("BATCH CREATED")
print("=" * 80)

print("Total examples:", len(training_batch_1))

print("\nSize distribution:")
print(
    training_batch_1["size_bucket"]
    .value_counts()
    .sort_index()
)

print("\nSplit distribution:")
print(
    training_batch_1["split"]
    .value_counts()
)

print("\nAudit distribution:")
print(
    training_batch_1["is_taxonomy_audit"]
    .value_counts()
)

print("\n✓ Saved:")
print(training_batch_1_path)

print("\n✓ Training batch 01 is ready for human annotation.")

================================================================================
BATCH CREATED
================================================================================
Total examples: 300

Size distribution:
size_bucket
2_tweets         75
3_to_4_tweets    75
5_to_8_tweets    75
9_plus_tweets    75
Name: count, dtype: int64

Split distribution:
split
train    300
Name: count, dtype: int64

Audit distribution:
is_taxonomy_audit
False    300
Name: count, dtype: int64

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv

✓ Training batch 01 is ready for human annotation.

In [172]:
# ============================================================
# STEP 66 — CREATE HUMAN-LABELLED TRAINING BATCH 1
# ============================================================

import pandas as pd
from pathlib import Path

print("=" * 80)
print("CREATE HUMAN-LABELLED TRAINING BATCH 1")
print("=" * 80)

# ------------------------------------------------------------
# 1. Load the existing 1,500 pool
# ------------------------------------------------------------

labeling_pool_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_labeling_pool_1500.csv"
)

labeling_pool = pd.read_csv(
    labeling_pool_path
)

print("\nLabeling pool:", len(labeling_pool))

# ------------------------------------------------------------
# 2. Safety checks
# ------------------------------------------------------------

assert len(labeling_pool) == 1500

assert labeling_pool["split"].eq("train").all()

assert labeling_pool["is_taxonomy_audit"].eq(False).all()

# ------------------------------------------------------------
# 3. Sample 75 per size bucket
# ------------------------------------------------------------

BUCKETS = [
    "2_tweets",
    "3_to_4_tweets",
    "5_to_8_tweets",
    "9_plus_tweets"
]

BATCH_SIZE_PER_BUCKET = 75

batch_parts = []

for bucket in BUCKETS:

    bucket_df = labeling_pool[
        labeling_pool["size_bucket"] == bucket
    ].copy()

    # Deterministic sampling
    batch = bucket_df.sample(
        n=BATCH_SIZE_PER_BUCKET,
        random_state=42
    )

    batch_parts.append(batch)

    print(
        f"{bucket:20s}: "
        f"{len(batch)} selected"
    )

# ------------------------------------------------------------
# 4. Combine and shuffle
# ------------------------------------------------------------

training_batch_1 = pd.concat(
    batch_parts,
    ignore_index=True
)

training_batch_1 = training_batch_1.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# ------------------------------------------------------------
# 5. Add clean annotation fields
# ------------------------------------------------------------

training_batch_1["intent_label"] = ""

training_batch_1["annotation_notes"] = ""

training_batch_1["annotator"] = ""

# ------------------------------------------------------------
# 6. Add explicit annotation status
# ------------------------------------------------------------

training_batch_1["annotation_status"] = "UNLABELED"

# ------------------------------------------------------------
# 7. Safety checks
# ------------------------------------------------------------

assert len(training_batch_1) == 300

assert (
    training_batch_1["size_bucket"]
    .value_counts()
    .to_dict()
    == {
        "2_tweets": 75,
        "3_to_4_tweets": 75,
        "5_to_8_tweets": 75,
        "9_plus_tweets": 75
    }
)

assert training_batch_1["split"].eq("train").all()

assert training_batch_1["is_taxonomy_audit"].eq(False).all()

# ------------------------------------------------------------
# 8. Check conversation uniqueness
# ------------------------------------------------------------

assert training_batch_1["conversation_id"].is_unique

# ------------------------------------------------------------
# 9. Save
# ------------------------------------------------------------

training_batch_1_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_training_batch_01.csv"
)

training_batch_1.to_csv(
    training_batch_1_path,
    index=False
)

print("\n" + "=" * 80)
print("BATCH CREATED")
print("=" * 80)

print("Total examples:", len(training_batch_1))

print("\nSize distribution:")
print(
    training_batch_1["size_bucket"]
    .value_counts()
    .sort_index()
)

print("\nSplit distribution:")
print(
    training_batch_1["split"]
    .value_counts()
)

print("\nAudit distribution:")
print(
    training_batch_1["is_taxonomy_audit"]
    .value_counts()
)

print("\n✓ Saved:")
print(training_batch_1_path)

print("\n✓ Training batch 01 is ready for human annotation.")

================================================================================
CREATE HUMAN-LABELLED TRAINING BATCH 1
================================================================================

Labeling pool: 1500
2_tweets            : 75 selected
3_to_4_tweets       : 75 selected
5_to_8_tweets       : 75 selected
9_plus_tweets       : 75 selected

================================================================================
BATCH CREATED
================================================================================
Total examples: 300

Size distribution:
size_bucket
2_tweets         75
3_to_4_tweets    75
5_to_8_tweets    75
9_plus_tweets    75
Name: count, dtype: int64

Split distribution:
split
train    300
Name: count, dtype: int64

Audit distribution:
is_taxonomy_audit
False    300
Name: count, dtype: int64

✓ Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv

✓ Training batch 01 is ready for human annotation.

prepare Batch 01 for manual annotation

In [173]:
import pandas as pd

batch_path = (
    PROCESSED_DIR /
    "amazonhelp_intent_training_batch_01.csv"
)

training_batch_1 = pd.read_csv(batch_path)

print("=" * 80)
print("TRAINING BATCH 01 — MANUAL ANNOTATION SET 1")
print("=" * 80)

print("\nTotal batch:", len(training_batch_1))
print("Showing examples 0–29\n")

for i in range(30):

    row = training_batch_1.iloc[i]

    print("=" * 80)
    print(f"EXAMPLE {i}")
    print("=" * 80)

    print("Conversation size :", row["conversation_size"])
    print("Customer turns   :", row["customer_turns"])
    print("Support turns    :", row["support_turns"])
    print("Size bucket      :", row["size_bucket"])

    print("\nCUSTOMER:")
    print(row["first_customer_message"])

    print("\nFULL CONVERSATION:")
    print(row["conversation_text"])

    print("\nCURRENT LABEL:")
    print("[ UNLABELED ]")

print("\n" + "=" * 80)
print("END OF SET 1")
print("=" * 80)

================================================================================
TRAINING BATCH 01 — MANUAL ANNOTATION SET 1
================================================================================

Total batch: 300
Showing examples 0–29

================================================================================
EXAMPLE 0
================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.

FULL CONVERSATION:
[CUSTOMER] I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.
[SUPPORT] @204457 We never want to let our customers down! Is there an issue with one of your current orders: https://t.co/3kQwjObgTc? ^GM
[CUSTOMER] @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +
[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.
[SUPPORT] @204457 Oh no, Bree! I'm sorry for the poor experience. When you spoke with us previously, what insights or alternatives did we provide?^TG

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 1
================================================================================
Conversation size : 100
Customer turns   : 59
Support turns    : 41
Size bucket      : 9_plus_tweets

CUSTOMER:
@115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]

FULL CONVERSATION:
[CUSTOMER] @115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]
[SUPPORT] @183363 it to be personal information. Our Twitter page is public.​ 3/3^EM
[SUPPORT] @183363 and we'll see what best can be done to help you. Also, please don't provide your order details, as we consider 2/3^EM
[SUPPORT] @183363 I understand your concern regarding the return. Kindly reach out to our support team here: https://t.co/beaaDm0muc 1/3^EM
[CUSTOMER] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer.
[SUPPORT] @183363 I get your concern but post the expiration of return window we'll not be able to accept the return. It's the 1/3 ^SH
[SUPPORT] @183363 manufacturer who will help with the warranty. If the manufacturer is unable to help you with the warranty, kindly 2/3 ^SH
[SUPPORT] @183363 get a service denial letter from them so that we can assist you accordingly. 3/3 ^SH
[CUSTOMER] @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered glass is available for merely Rs 100 per piece. Yet I bought Netboon at Rs 1800. I did not buy from Netboon. Who  is Netbeen ? Nobody know. I bought from Amazon. @115937 @118702
[SUPPORT] @183363 Sorry to know about the trouble. As Amazon.in being a market place post the return window, as mentioned earlier (1/3) ^KA
[CUSTOMER] @AmazonHelp Amazon- Have the Netboon order &amp; Refusal to help. If tempered glass falls off on its own, is a quality issue. I did not buy from Netboon. I bought Netboon product from Amazon. Please resolve my concern. @115937 @118702 https://t.co/G6PkbmqPTF
[SUPPORT] @183363 kindly contact the manufacturer to avail the warranty(if applicable). In case any service center refuses to honor (2/3) ^KA
[SUPPORT] @183363 the warranty, please get back to us with a service denial letter and we'll look into this for you. (3/3) ^KA
[CUSTOMER] @AmazonHelp where is the service center of Netboon???????
[CUSTOMER] @AmazonHelp Service denial letter attached once again. How many times you want me attach this letter @115937 @20502 https://t.co/GAa6Id6ahi
[CUSTOMER] @AmazonHelp @115937 @20502 Service denial letter's copy attached once again. At lease open your eyes and read the same. What is wrong with you Amazon???? https://t.co/QtAm5wXACR
[CUSTOMER] @AmazonHelp @115937 @20502 Now, do not tell me to go and get it signed by Netboon. Give me Netboon's address, I will deal directly with them.
[CUSTOMER] @AmazonHelp @115937 @20502 Please do not buy any Netboon Product from Amazon. Netboon Cheat, Amazone support them. @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319
[SUPPORT] @183363 Mahesh, since you've emailed us the service denial letter, our team will look into it and get back to you. ^MS
[CUSTOMER] @AmazonHelp Thanks Amazon. Netboon has charged an exorbitant price from me. He is responsible to provide me due service from the product.
[SUPPORT] @183363 I'm sorry for the issues with your order, the resolution provided to you is the best. 1/2 ^MJ
[SUPPORT] @183363 Further, we'll not be able to assist you with returns until we have a service denial letter from the manufacturer. 2/2 ^MJ
[SUPPORT] @183363 Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^MJ
[CUSTOMER] @AmazonHelp ORDER # 408-7866006-8411522 was cancelled by Amazon immediately after registering it. It was informed to me repeatedly by SMS. I was assured that my money will be refunded. Today, I received this SMS that it is under despatch. I do not need it. Please refund my money. https://t.co/JhES7zBUlA
[SUPPORT] @183363 I'm sorry about the trouble with your order. We'd like to help, kindly connect with us here: https://t.co/vlvfJr4nN9 1/2
[SUPPORT] @183363 Please don’t provide the order details, we consider it to be personal info. Our Twitter page is visible to public. 2/2 ^MA
[CUSTOMER] @AmazonHelp i agree but I fail to understand how to contact you and share my concern.
[SUPPORT] @183363 You can use the following link to share your details and concern with us: https://t.co/cQVomR1pWz and we'll get back soon.^SK
[CUSTOMER] @AmazonHelp I am getting this kind of SMS daily, today also. Please refund my money you have already cancelled this order, which you can verify from your own server.
[SUPPORT] @183363 We'd like to help, please share your details in the link provided earlier. ^AG
[CUSTOMER] @AmazonHelp I have already provided the details. Since you are not taking any action, I am getting such SMSs.
[SUPPORT] @183363 We've sent you a correspondence. Kindly check the same here: https://t.co/ubzNHWZvL2 ^SG
[CUSTOMER] @AmazonHelp What I shuld do. You are not refunding my money and I am getting SMS every day. Please tell me what I should do.
[SUPPORT] @183363 Just to confirm, have you dropped in your details using the link provided by ^SK ? We'd like to have a look into it. ^AB
[CUSTOMER] @AmazonHelp Kindly stop ridiculing your genuine customer. Immediately after I booked this order and paid the relevant amount. Amazon Cancelled this order and assured me to return the amount. Now. I am getting the SMS that shipment is on the way. Pl help me.
[CUSTOMER] @AmazonHelp I have dropped all the details on that linl. Kindly read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read and help
[SUPPORT] @183363 Thanks for sharing your details with us. We're working on your issue and will be contacting you with an update. ^ZH
[CUSTOMER] @AmazonHelp I have already had enough harassment from you. Please confirm, did you cancel this order immediately or not. That will answer my query.
[CUSTOMER] @AmazonHelp  https://t.co/byD9feifRX
[CUSTOMER] @AmazonHelp One more SMS https://t.co/irk5Hx7xS3
[CUSTOMER] @AmazonHelp Amazon, you surprise me. How you can dispatch an item when you yourself canceled this item and promised to refund my money. Do you have any system or running a shop.
[SUPPORT] @183363 I apologize for the trouble with your order, Mahesh. Please share your insight by writing back to the e-mail ^MP (1/2)
[SUPPORT] @183363 sent by our team. We'll revert to the same with an update. ^MP (2/2)
[CUSTOMER] @AmazonHelp I booked and order on Amazon. Immediately after booking, Amazon cancelled the order [a fact can be verified from my account] and committed to refund my amount. I purchased the item from elsewhere. Now Amazon say, item being dispatched, which I do not need. Pl refund my money https://t.co/7fhquvB6qP
[CUSTOMER] @AmazonHelp On 26.09.2017, booked order for an item on Amazon. Amazon cancelled it immediately &amp; committed to refund money, facts can be seen from my account. I purchased that item from somewhere else. Now. Amazon do not refund and say item is under dispatch. @120033 @120319
[CUSTOMER] @AmazonHelp @120033 @120319 Can you @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 help me to get my money from @115850 who themselves cancelled my order, but refuse to refund money.
[CUSTOMER] @AmazonHelp @118342 @15352 @137848 @55412 @5832 @1145 I booked an item on Amazon. But, Amazon cancelled the order [as seen in my a/c] &amp; committed to refund. Now Amazon say, it being dispatched, which I do not need. Pl help refund of my money https://t.co/37ugFU3SuC
[SUPPORT] @183363 I get your concern, Mahesh. Our team is working on it, kindly reply to the email sent by our team for an update. ^MP (1/2)
[SUPPORT] @183363 Don't provide your order details, we consider it to be personal info. Our Twitter page is visible to the public. ^MP (2/2)
[CUSTOMER] @AmazonHelp You are harassing me. See my account that you yourself cancelled this order. You sent me many SMS in this regard. I have replied your email many times. Do your job &amp; refund my money. Pl stop this nuisance of asking details again and again. @1145 Kindly intervene.
[CUSTOMER] @AmazonHelp If I do not provide details than what I do. Where the hell I should go. You are simply harassing me. Can't you see my account that you cancelled this order immediately after I booked it. What else you require. Is this your style of operation. Pl refund my money.
[CUSTOMER] @AmazonHelp When you yourself cancelled the order, I am under no obligation to prove it or supply you any detail in this regard. Check at your end and refund my money, Please instruct your inexperienced boys to avoid writing me those unwanted messages. Check your own record and do your job
[CUSTOMER] @AmazonHelp @115850 @123644  @115821- Does Amazon have one person who can appreciate that when Amazon themselves cancelled an order, which is on record, than how the can force a customer to accept it. Amazon boys do not read the account, they do not read the email. SAD SAD  SAD
[CUSTOMER] @AmazonHelp @115850 @123644 @115821 I am sick of you Amazon. Give me your final decision. Are you going to refund my money or not. I will escalate the matter to regulating authorities. @4030  @118702  @4167 @4110 @144775 @11779 @120320 @137849  @144775 @11779  @33808 https://t.co/GYuPYQ5FEv
[CUSTOMER] @AmazonHelp Every email duly answered Sir. Please show some amount of sincerity towards your organisation and discharge your responsibility. Do you think you will get away and keep my money for long. Kindly do not continue to harass me. It would not help you.
[CUSTOMER] @AmazonHelp Kindly do not pretend to apologize. Please do your work. I trust you are capable of reading client's account, or Amazon pay you only to harass the clients. Kindly act like a gentleman and refund my money. This email was replied long time ago.
[CUSTOMER] @AmazonHelp Kindly show some kind of sensibility and note my insight from the attached piece. Trust Amazon would have trained you to at least that level, or that is also too much asking from you. https://t.co/C3c2LgEC61
[SUPPORT] @183363 I'm sorry about the trouble you've had regrading this order lately. We'd like to set things right. Kindly respond 1/2 ^KH
[SUPPORT] @183363 To the latest correspondence you've received for further assistance. 2/2 ^KH
[CUSTOMER] @AmazonHelp My dearest Sir, I am listening this since last twenty days. What makes you people to work, or Amazon keep you only to make fool of customers. @115850               @115821  @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Respond to what my dear Sir. You are not torturing me. I have given you all the details. What more you want. Do you want to kill your client. @115850 @115821  @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp No Sir, you are not sorry. Amazon has employed to harass the client, which you are doing so well. I know you are not going to refund my money, so I am also enjoying. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Amazon must send you to English Learning Academy, so that you are clear in your expression. @115821  @115850 @AmazonHelp @123644. Do you @4030  @118702  @4167 @4110 @4168 also have such kind of executives.
[SUPPORT] @183363 Apologize for the hassle. Please fill in the details of your concern here: https://t.co/GIJyeYqKE0 &amp; we'll help you. ^BS
[CUSTOMER] @AmazonHelp Hi Sir, do you know the meaning of Insight. Where did you (not) learn English. I feel so sorry for Amazon. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Whether you refund or not, I will not do anymore filling. My case is clear in the attached image. If you can not appreciate your own order Nos, you will never help me @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168 https://t.co/LbhLhxlZPj
[CUSTOMER] @AmazonHelp Will you @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 not help me for refund of my money from Amazon. Details clear in the image. https://t.co/IzJXvQ0kv8
[CUSTOMER] @AmazonHelp Hi Your Excellency BS Sir. In order to make you also feel satisfied from my harassment, I fill in details fifth time also. I await eagerly to receive further torture from you. Your @115821 @115850 @4030  @118702  @4167 @4110 @4168  Exec should learn. https://t.co/FMxKiPsFsy
[CUSTOMER] @AmazonHelp Why all Amazon Sirs/Madams are silent, or are you innovating further tactics to torture and harass the client. Do Amazon run an academy where Client Harassment is taught. Do you @115821  @115850 @4030  @118702  @4167 @4110 @4168 also have similar academy.
[CUSTOMER] @AmazonHelp The word Apology does not match Amazon Executive's profile. It is counter productive for you organisation. Or is this the way you prepare your client to have further series of torture. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Co Chweet of KH when he/she says "Lately". It is ongoing since last 20 days. I know you will never refund my money. I am simply enjoying the whole process. Do you @4030  @118702  @4167 @4110 @4168 refund in such cases or fight out and kill the client. https://t.co/0WSCqXsOWr
[CUSTOMER] @AmazonHelp Amazon Team working on "what". It is obvious. They are working on how to torture the client. Do you @4030  @118702  @4167 @4110 @4168 also have similar teams.
[CUSTOMER] @AmazonHelp M/s @115821 @115850 @123644 @4030  @118702  @4167 @4110 @4168, pl note, Amazon admit that I already shared the requisite details. Still forced me to share again today on 18.10.17. How Amazon take away intelligence from their executives. It is amazing.
[SUPPORT] @183363 social media team, we'll get back to you soon. 2/2^AP
[SUPPORT] @183363 I understand you're upset due to the issues with the order. Kindly reply to the email you've received from 1/2^AP
[SUPPORT] @183363 I understand you're upset and I'm sorry about this as you've mentioned that you've 1/2 ^KH
[SUPPORT] @183363 Sharedd the details, We'll check and get back to you at the earliest. 2/2 ^KH
[CUSTOMER] @AmazonHelp Another admission, yet forced the client to share details again today on 18.09.17. Amazon run special session to make executive so less intelligent, sharp, responsible, anti-customer etc @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Now it is his/her turn to take revenge. Just an hour ago, I replied the queries, attached. Now his/her Holiness asks for details, without telling me what he/she demands. Amazing Amazon @4030  @118702  @4167 @4110 @4168 https://t.co/vjQlH8uQUz
[CUSTOMER] @AmazonHelp Your Excellency, 1 hour ago I obeyed your instructions to submit attached details. Your Lordship, if you are not satisfied with my humble details, kindly pardon me and show your mercy by telling what I shuld do. @4030  @118702  @4167 @4110 @4168 https://t.co/xQQz3WuutM
[CUSTOMER] @AmazonHelp No Your Honor, how a mortal can dare to be upset with a Mighty Kingdom Amazon. I am your poor people, seeking your kindness for refund of my money, if it pleases the Kingdom. Trust your Holiness will not punish me further. @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Your Majesty, I am sorry I never learnt a word "Sharedd". Will you be kind enough to make me understand the meaning of your novel invention " Sharedd". I will be hugely obliged. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168
[SUPPORT] @183363 I get your concern. If the details were shared, our team shall reach out to you soon. Appreciate your understanding. ^MP
[CUSTOMER] @AmazonHelp @115821 @115850 @123644 @4030 @118702 @4167 @4110 @4168 I do not agree with Confucius when he says "When ---- is inevitable. Lay back and enjoy". I am participating. I will never accept the delivery. Amazon will never refund. Some new result will flow out. Bye until when I resume after end of Festival season.  Happy Diwali to all. https://t.co/lgwolHYDxg
[CUSTOMER] @AmazonHelp I know Your Majesty, you are angry with me. I have not realized your might &amp; dared challenge. As a punishment, you will never refund my money. I am a humble commercial legal person. I am learning a commercial dispute readdress. Whether you pay or not, I will be remain winner.
[SUPPORT] @183363 Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^HA
[SUPPORT] @183363 If you've shared the details, we'll get back to you at the earliest. Appreciate your understanding. ^HA
[SUPPORT] @183363 I see we've emailed you regarding this. Kindly reply to our email and we'll look into it. ^NR
[CUSTOMER] @AmazonHelp My dear Sir, you are torturing me. I sent these details so many times in past 20 days. Your intelligence and service level are much lower than a road side shop. @135980 @61230 @120697 @120033 @144769 @29568 @136912 @61231 @120319
[CUSTOMER] @AmazonHelp @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 Amazon an ethic less organisation. Amazon executives shameless group of personnel. No customer support in Amazon
[CUSTOMER] @AmazonHelp You lack even commonsense. It is pain to interact with you. A class fifth standard student will be more intelligent and responsive than you. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168 @115937
[CUSTOMER] @AmazonHelp Amazon has employed a bunch of brainless personnel in customer care. They neither read, nor listen nor understand customers' pain. Amazon cheat the client. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168 @115937

In [174]:
print("=" * 80)
print("TRAINING BATCH 01 — MANUAL ANNOTATION SET 2")
print("=" * 80)

print("\nTotal batch:", len(training_batch_1))
print("Showing examples 30–59\n")

for i in range(30, 60):

    row = training_batch_1.iloc[i]

    print("=" * 80)
    print(f"EXAMPLE {i}")
    print("=" * 80)

    print("Conversation size :", row["conversation_size"])
    print("Customer turns   :", row["customer_turns"])
    print("Support turns    :", row["support_turns"])
    print("Size bucket      :", row["size_bucket"])

    print("\nCUSTOMER:")
    print(row["first_customer_message"])

    print("\nFULL CONVERSATION:")
    print(row["conversation_text"])

    print("\nCURRENT LABEL:")
    print("[ UNLABELED ]")

print("\n" + "=" * 80)
print("END OF SET 2")
print("=" * 80)

================================================================================
TRAINING BATCH 01 — MANUAL ANNOTATION SET 2
================================================================================

Total batch: 300
Showing examples 30–59

================================================================================
EXAMPLE 30
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Everyone is getting their Amazon Echo while Amazon has delayed the delivery of mine to Monday 😢😢😢😭

FULL CONVERSATION:
[CUSTOMER] Everyone is getting their Amazon Echo while Amazon has delayed the delivery of mine to Monday 😢😢😢😭
[SUPPORT] @463847 We understand your excitement. Sorry for the delay. Kindly wait until the revised estimated delivery date. ^NS

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 31
================================================================================
Conversation size : 6
Customer turns   : 4
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
Is @115830 tracking a joke? Got similar screen Mon Tues and Wed and different info on DHL page. @AmazonHelp CS only giving useless standard replies. Definitely avoiding in the future. https://t.co/lgFvSKn7Im

FULL CONVERSATION:
[CUSTOMER] Is @115830 tracking a joke? Got similar screen Mon Tues and Wed and different info on DHL page. @AmazonHelp CS only giving useless standard replies. Definitely avoiding in the future. https://t.co/lgFvSKn7Im
[SUPPORT] @628834 I'm sorry for this delay! Has a new delivery date been posted in the order details here: https://t.co/aaDyEz1VgE? ^HS
[CUSTOMER] @AmazonHelp Thanks but Tracking, DHL and Customer Service giving 3 different dates. Lost confidence in @115830 Too much time wasted to bother following up further. If not delivered by next week will request refund
[CUSTOMER] @AmazonHelp Another day, another @115830 delivery day. If you keep updating it every day you should get it right eventually...... https://t.co/1RVwYeu0LO
[SUPPORT] @628834 Sorry for all the delays. Hope your order reaches you soon. ^MA
[CUSTOMER] @AmazonHelp Thanks - will keep this thread updated

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 32
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Ummmmmm @AmazonHelp THIS ISNT MY HOUSE HELPPP https://t.co/zwZ2nD5unj

FULL CONVERSATION:
[CUSTOMER] Ummmmmm @AmazonHelp THIS ISNT MY HOUSE HELPPP https://t.co/zwZ2nD5unj
[SUPPORT] @490321 Oh no! A member from our team will look into this for you. Please provide more info here: https://t.co/Jpqug6wIH2 ^BA

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 33
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp My order shouldve arrived yesterday, now am told if it  doesn't arrive next Wednesday, contact them. This is UNACCEPTABLE &amp; makes it not worth the wait. I'd like to cancel my order. 114-1833079-0185059

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp My order shouldve arrived yesterday, now am told if it  doesn't arrive next Wednesday, contact them. This is UNACCEPTABLE &amp; makes it not worth the wait. I'd like to cancel my order. 114-1833079-0185059
[SUPPORT] @227697 We would like to help you. Please share your details with us here: https://t.co/GIJyeYqKE0. We'll get in touch shortly.
Please don't provide your order details as we consider it personal information. Our twitter page is visible to public.^CB

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 34
================================================================================
Conversation size : 8
Customer turns   : 7
Support turns    : 1
Size bucket      : 5_to_8_tweets

CUSTOMER:
FUN FACT. @2150'S WEBSITE SAYS "CUSTOMER REQUESTED REATTEMPT AT A LATER POINT" BUT I NEVER EVEN SPOKE TO THEM ??? LIES.

FULL CONVERSATION:
[CUSTOMER] FUN FACT. @2150'S WEBSITE SAYS "CUSTOMER REQUESTED REATTEMPT AT A LATER POINT" BUT I NEVER EVEN SPOKE TO THEM ??? LIES.
[CUSTOMER] @192781 @2150 Yikes, seems like this is business as usual for them... Did you pay for the shipping? Should be refunded... https://t.co/5Zjak0nxZL
[CUSTOMER] @192782 @2150 I didn't thankfully, because it comes with my amazon prime but I'm still effing annoyed.
[CUSTOMER] @192781 @2150 That’s almost more annoying... you’re paying for @115821 Prime but you “technically” didn’t pay for the shipping so there’s no refund owed 🙄
[CUSTOMER] @192782 @2150 @115821 Yep. Super shitty. Also laser ship hasn't emailed me back yet. Shocker!
[CUSTOMER] @192781 @192782 @2150 @115821 Did you address your email to __email__?  This differs from the form found on https://t.co/8EeDIhlpM3
[CUSTOMER] @174208 @192782 @2150 @115821 Update: still no response 🙃
[SUPPORT] @192781 We'd like to help! Please reach us via phone/chat here: https://t.co/hApLpMlfHN so we can look at this closer with you. ^KP

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 35
================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
@AmazonHelp me habéis facturado mal la compra de contenidos Kindle. Como realizo la reclamación? Gracias

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp me habéis facturado mal la compra de contenidos Kindle. Como realizo la reclamación? Gracias
[SUPPORT] @403798 Susana, nos disculpamos por lo sucedido. Contacta a nuestro SAC para brindarte más soporte: https://t.co/OjvUxwnzPe ^AV
[CUSTOMER] @AmazonHelp Perdona, pero las opciones están todas tabuladas y en ninguna hay posibilidad de explicar el problema que yo tengo. Dirigeme a la opción.
[SUPPORT] @403798 Si ninguna opción se ajusta a tu situación, puedes seleccionar la que más se acerque. ^JD

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 36
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115821 must have just been slapped from Black-Friday / Cyber Monday. Ordered on the 23rd - arrived 29th. That’s with prime as well!

FULL CONVERSATION:
[CUSTOMER] @115821 must have just been slapped from Black-Friday / Cyber Monday. Ordered on the 23rd - arrived 29th. That’s with prime as well!
[SUPPORT] @814235 I'm sorry for the wait on your order. Not all items are able to ship immediately. What was the delivery date listed on your order confirmation e-mail? ^AN

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 37
================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115821 if you are going to deliver a package after 830 pm at least ring the door bell.  Thankfully i looked out seen delivery guy in the truck.

FULL CONVERSATION:
[CUSTOMER] @115821 if you are going to deliver a package after 830 pm at least ring the door bell.  Thankfully i looked out seen delivery guy in the truck.
[SUPPORT] @225827 I'm sorry you weren't notified when your order was delivered. You can reach out to us here so we can leave carrier feedback on your behalf: https://t.co/rkA1v9pDLd ^CL
[CUSTOMER] @AmazonHelp Not saying yall are bad or want to get driver in trouble.  Just was curious why no ring to let us know its delivered.   So we can make sure its off the porch and inside.   Will assume it was not not interrupt @205580 game lol happy i saw his lights outside.

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 38
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@120533 vos livreurs qui remettent mes colis à n’importe qui on en parle ou pas ? 🤔

FULL CONVERSATION:
[CUSTOMER] @120533 vos livreurs qui remettent mes colis à n’importe qui on en parle ou pas ? 🤔
[SUPPORT] @680447 Bonsoir,
Je suis désolée d'apprendre cela. Quel est le transporteur en charge de la livraison?
^MD

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 39
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115850 got it!!! Thanks a lot, It is Amazing!!! https://t.co/1s8tR1pxhd

FULL CONVERSATION:
[CUSTOMER] @115850 got it!!! Thanks a lot, It is Amazing!!! https://t.co/1s8tR1pxhd
[SUPPORT] @548167 Awww.. that is so cute!😍 Welcome. 🙂 ^HR

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 40
================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
@AmazonHelp hi, i've been charged with a purchase that I didn't make. What's up with that?!

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp hi, i've been charged with a purchase that I didn't make. What's up with that?!
[SUPPORT] @450846 Hi, what is the amount of the charge &amp; what's written next to it on your statement? ^TS
[CUSTOMER] @AmazonHelp It says that I was charged $65.28 USD by https://t.co/etr0USS6O4 https://t.co/dFulhkZf3o
[SUPPORT] @450846 I'm sorry to hear that. If you get in touch: https://t.co/hApLpMlfHN, we'll be happy to look into this with you. ^DC

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 41
================================================================================
Conversation size : 4
Customer turns   : 1
Support turns    : 3
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115850 bad service by amazon, no order cancellation, no customer care response

FULL CONVERSATION:
[CUSTOMER] @115850 bad service by amazon, no order cancellation, no customer care response
[SUPPORT] @504631 Order can be canceled only after few minutes of placing the order. Once the time line is missed, (1/3)^HR
[SUPPORT] @504631 and it will be sent back to us. Appreciate your understanding. (3/3)^HR
[SUPPORT] @504631 we can't cancel the order. But, you can reject the order at the time of delivery (2/3)^HR

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 42
================================================================================
Conversation size : 13
Customer turns   : 6
Support turns    : 7
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850 @2036 @120033 Beware of Amazon, de sell old stocks 2015 &amp; b4 on lightining sales 2 liquidate their inventory which r unreturnable https://t.co/u1318Bv12T

FULL CONVERSATION:
[CUSTOMER] @115850 @2036 @120033 Beware of Amazon, de sell old stocks 2015 &amp; b4 on lightining sales 2 liquidate their inventory which r unreturnable https://t.co/u1318Bv12T
[SUPPORT] @120032 We've responded to your query here: https://t.co/dqlxgCvPWP ^AK
[CUSTOMER] @AmazonHelp What is the response. I am yet to get a call from customer care
[SUPPORT] @120032 Please respond to our email or request a call back through the same mail so we could reach out to you. ^JC
[CUSTOMER] @AmazonHelp Have already shared my registered mobile no. 9673101122, but I m currently contactable on 9818601122
[CUSTOMER] @AmazonHelp My email address is __email__
[SUPPORT] @120032 Please don't provide your order details, we consider it to be personal info. Our page is visible to the public.  2/2^VH
[SUPPORT] @120032 Please respond to our email or request a call back through the same mail so we could reach out to you. 1/2 ^VH
[CUSTOMER] @AmazonHelp If nothing happens then I will put on FB also
[SUPPORT] @120032 I just checked and we haven't received your details yet. Kindly share your details (1/2) ^GK
[SUPPORT] @120032 here: https://t.co/beaaDm0muc and we'll reach out to you. (2/2) ^GK
[CUSTOMER] @AmazonHelp Have shared the details in the above linked which was shared by u. Need early resolution from u.
[SUPPORT] @120032 Thanks for sharing, Kamlesh. We'll check and get back to you at the earliest.^AR

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 43
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
amazonのサポートが24時間チャット対応でよかった

FULL CONVERSATION:
[CUSTOMER] amazonのサポートが24時間チャット対応でよかった
[SUPPORT] @707791 カスタマーサービスへお問い合わせくだいただきありがとうございます。　365日24時間営業しておりますので、当サイトのご利用に際しお困りな事やご不明な点がございましたら、お気軽にお問い合わせくださいませ。　SM

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 44
================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
Sat In today waiting for @115830 delivery, and guess what! Delivery unsuccessful! I live on the busiest road in bedford too. Not happy

FULL CONVERSATION:
[CUSTOMER] Sat In today waiting for @115830 delivery, and guess what! Delivery unsuccessful! I live on the busiest road in bedford too. Not happy
[SUPPORT] @696242 I'm so sorry to hear your parcel was not delivered! Couriers will typically deliver until 21:00. ^RO
[CUSTOMER] @AmazonHelp Thank you for your reply, I have received an email, saying it was unsuccessful.

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 45
================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115821 your customer service is god awful! An undelivered packed twice in a row, nobody seems to know where it is! Top notch!

FULL CONVERSATION:
[CUSTOMER] @115821 your customer service is god awful! An undelivered packed twice in a row, nobody seems to know where it is! Top notch!
[SUPPORT] @413211 I'm so sorry! What's the current tracking and carrier shown here: https://t.co/Y5jpI9gRhE?  ^AG

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 46
================================================================================
Conversation size : 30
Customer turns   : 16
Support turns    : 14
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850, How can you sell a product for 1399 which has MRP of 1199? https://t.co/VlHoStH9ho

FULL CONVERSATION:
[CUSTOMER] @115850, How can you sell a product for 1399 which has MRP of 1199? https://t.co/VlHoStH9ho
[CUSTOMER] @115850 @58114, How can Amazon sell a product for 1399 which has MRP of 1199.
[SUPPORT] @444537 The MRP difference could come up owing to multiple factors. Kindly refer: https://t.co/JYMValPU6J for more information. ^MO
[SUPPORT] @444537 We attempt to ensure MRP information is accurate. Rarely, there may be cases where MRP of the product delivered 1/2 ^NK
[SUPPORT] @444537 is different from the MRP given on the website due to various reasons. For more info, refer https://t.co/aY3K54y2k4. 2/2 ^NK
[CUSTOMER] @AmazonHelp My simple querry is MRP printed on pruduct is 1199. Then how come? You are selling it for 1399. Your conditions given on the link
[CUSTOMER] @AmazonHelp  https://t.co/zYAG8zd6EF
[CUSTOMER] @AmazonHelp On product MRP written 1199.. Do you think customer is fool. I am going to sue in consumer portal with these details. Don’t give me nonsense https://t.co/zsMYrgYTzE
[CUSTOMER] @AmazonHelp Quoted MRP on website is 2799, Sold    to me for 1499 and MRP printed on Product received 1199 https://t.co/V55Tz0Xe6N
[CUSTOMER] @AmazonHelp Not satisfied with this!! Such response is not expected from brand like Amazon.it means you guys are cheating customers. It will spoil Name
[CUSTOMER] @AmazonHelp Why are you selling me at more than printed MRP
[SUPPORT] @444537 I understand the confusion you have with the MRP, Om. You can get a clarity on it here https://t.co/KEvww0DWc8 ^MA
[CUSTOMER] @AmazonHelp These terms &amp;conditions &amp; the incident happened with me is very funny. under this there is variation of more than 100%. Why r u making fool https://t.co/BQDVSyvmbZ
[CUSTOMER] @AmazonHelp Don’t try to reach me theory.I am going to highlight it everywhere very badly. That is why I am creating these conversations with you guys
[SUPPORT] @444537 Pricing and offers are decision of the sellers. The constantly changing marketplace and (1/2)^SQ
[SUPPORT] @444537 our efforts to offer you the lowest price, may result in fluctuations in our prices over time. (2/2)^SQ
[CUSTOMER] @AmazonHelp You guys are not selling vegetables that your seller can quote any price. How can your seller sell at More than printed MRP. Against Law!!!
[SUPPORT] @444537 I get your concern. However, I'm sorry the prices currently available on the website are the best we can offer. 1/2 ^EM
[SUPPORT] @444537 Appreciate your understanding in this matter. 2/2 ^EM
[CUSTOMER] @AmazonHelp Are you legally allowed sell products at more than printed MRP
[CUSTOMER] @AmazonHelp I have not received any response on this. Are you legally allowed to sell at more than printed MRP. Check with your concerned team and reply
[SUPPORT] @444537 Pricing and offers are a decision of the seller and hence are dynamic. There may be cases where M.R.P. of the product 1/3^NK
[SUPPORT] @444537 delivered is different from the M.R.P. given on the website due to various reasons including time lag in updating 2/3 ^NK
[SUPPORT] @444537 prices post changes in M.R.P etc.. You may refer the same here: https://t.co/z35wAl83F5. Request you to check. 3/3 ^NK
[CUSTOMER] @AmazonHelp Are you guys fool. Can’t understand simple question?Are you legally allowed to at more than printed MRP.Yor reply should be YES/NO that’s it
[SUPPORT] @444537 For sure, we cannot sell above or below designated pricing. Hence, it depends on location and 1/2 ^RW
[SUPPORT] @444537 you can follow the link given earlier for further insight. ^RW 2/2
[CUSTOMER] @AmazonHelp Then.arrange me replacement with other packaging if same product with your updated MRP or refund me money which you have taken more from MRP https://t.co/taUftniDBd
[CUSTOMER] @AmazonHelp Or I will escalate it further or different platforms
[SUPPORT] @444537 Kindly visit the link given earlier and learn more about our pricing policies. I've shared your feedback with our team. ^ZH

CURRENT LABEL:
[ UNLABELED ]
================================================================================
EXAMPLE 47
================================================================================
Conversation size : 10
Customer turns   : 4
Support turns    : 6
Size bucket      : 9_plus_tweets

CUSTOMER:
@145910 @60553 @164163 @137848 @115850 Service tax charged on 30th September 2017 invoice.... What is this??? https://t.co/QMZ2PL7Cof

FULL CONVERSATION:

In [175]:
training_batch_path = PROCESSED_DIR / "amazonhelp_intent_training_batch_01.csv"

training_batch = pd.read_csv(training_batch_path)

In [176]:
# Display Set 3: examples 60–89

start, end = 60, 89

for i in range(start, end + 1):
    row = training_batch.iloc[i]

    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print()
    print("CUSTOMER:")
    print(row["first_customer_message"])
    print()
    print("FULL CONVERSATION:")
    print(row["conversation_text"])
    print()
    print("CURRENT LABEL:")
    print("[ UNLABELED ]")
    print()

==========================================================================================
EXAMPLE 60
==========================================================================================
Conversation size : 10
Customer turns   : 5
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850 @AmazonHelp Facing fake price on Amazon App. Deal price Rs649 of SanDisk when proceeded to checkout its its Rs743. Kindly check https://t.co/xYjf51qFSQ

FULL CONVERSATION:
[CUSTOMER] @115850 @AmazonHelp Facing fake price on Amazon App. Deal price Rs649 of SanDisk when proceeded to checkout its its Rs743. Kindly check https://t.co/xYjf51qFSQ
[CUSTOMER] @115850 @AmazonHelp Rs 100 delivery charges on Prime product. Can you tell me why facing all these issue. Whenever I am proceeding to checkout price increased
[SUPPORT] @207103 them here: https://t.co/vlvfJr4nN9 and it'll be sorted. 2/2 ^SK
[SUPPORT] @207103 I'm sorry about this. Have you reported this to our support team? If not, please connect with 1/2 ^SK
[CUSTOMER] @AmazonHelp Issues never get sorted there. They have excuse for everything
[SUPPORT] @207103 We would like to help you. Please share your details with us here: https://t.co/GIJyeYqKE0. We'll get in touch shortly. ^CB
[CUSTOMER] @AmazonHelp I have told you the issue I am facing, not only I many are facing the same issue.
[CUSTOMER] @AmazonHelp Shared details on both the links provided. Kindly resolve this fake price issues facing since 3 months back. https://t.co/Y8JsltDdAg
[SUPPORT] @207103 I get your disappointment, Anita. As you've shared your details, our team will check and get back to you with an 1/2 ^NK
[SUPPORT] @207103 update soon. Request you to wait. 2/2 ^NK

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 61
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Dear @115821 if I pay or get one day shipping because of prime and you come after 6 to see my apt gate closed...get your lazy butt out that truck, walk through the gate and deliver my package. One day means one day.

FULL CONVERSATION:
[CUSTOMER] Dear @115821 if I pay or get one day shipping because of prime and you come after 6 to see my apt gate closed...get your lazy butt out that truck, walk through the gate and deliver my package. One day means one day.
[SUPPORT] @679489 We're sorry that you didn't receive your order on time. Who was the carrier of your order? Order status and carrier information can be found here: https://t.co/yaEaPhYfUg ^TE

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 62
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Amazonプライム会員なったった✋

FULL CONVERSATION:
[CUSTOMER] Amazonプライム会員なったった✋
[SUPPORT] @822644 リプライ失礼いたします、Amazonです。プライムのご登録、誠にありがとうございます！プライムビデオやプライムミュージックなど、さまざまな特典をご用意しておりますので、ぜひご活用くださいませ🙇  https://t.co/AbfeovjCgG HM

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 63
==========================================================================================
Conversation size : 8
Customer turns   : 4
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
Oulala plus que 23 minute :/ vite @115821

FULL CONVERSATION:
[CUSTOMER] Oulala plus que 23 minute :/ vite @115821
[SUPPORT] @139832 Bonsoir, avez-vous besoin d'assistance ? ^KD
[CUSTOMER] @AmazonHelp Bonsoir j'aimerais juste que mon colis soit envoyé à la date indiqué
[SUPPORT] @139832 Que dit le suivi de votre colis s'il vous plaît ? ^SB
[CUSTOMER] @AmazonHelp Date de livraison prévue aujourd'hui avant 20h
[SUPPORT] @139832 Je suis sincèrement désolée pour le désagrément causé par cela. Avez-vous signalé cet incident à notre service client s'il vous plait ? ^SB
[CUSTOMER] @AmazonHelp Non et je n'ai pas à le faire logiquement c'est a Amazon a honorer ses engagements
[SUPPORT] @139832 Notre service client est en mesure de vérifier l'état de cette livraison et prendre les mesures nécessaires si applicable. ^KD

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 64
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115850 can you help me find a 240-260lte double door frost free refrigerator deliverable at 388130

FULL CONVERSATION:
[CUSTOMER] @115850 can you help me find a 240-260lte double door frost free refrigerator deliverable at 388130
[SUPPORT] @207563 Please check this link: https://t.co/d8GAR0yp2j. ^HN
[CUSTOMER] @AmazonHelp :( no delivery or seller to pincode 388130
[SUPPORT] @207563 Please let us know the link of the product you would like to buy. We'll check and get back to you. ^JS
[CUSTOMER] @AmazonHelp LG 260 L 4 Star Frost-Free Double Door Refrigerator (GL-I292RPZL, Shinny Steel) https://t.co/vSS1rnythe

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 65
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp I have got my phone delivered before time and getting message that could not deliver. Are you okay #Amazon ?? https://t.co/I7o0IsKzNC

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp I have got my phone delivered before time and getting message that could not deliver. Are you okay #Amazon ?? https://t.co/I7o0IsKzNC
[SUPPORT] @293724 Apologies for the wrong update. Please contact us here: https://t.co/rS49hgaADF so that we can assist you accordingly. ^SF

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 66
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
What happens when you order a Christian book off @115821 and they send you the Autobiography of Gucci Mane instead ?? Help ??

FULL CONVERSATION:
[CUSTOMER] What happens when you order a Christian book off @115821 and they send you the Autobiography of Gucci Mane instead ?? Help ??
[SUPPORT] @216164 Oh no! I'm so sorry you received the wrong item! You can start the return process here: https://t.co/SfsrQic7cv ^JY

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 67
==========================================================================================
Conversation size : 14
Customer turns   : 10
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
Ok if my new Echo is going to need a factory reset every damn day, you and I will need to have word, Alexa.

I care less about mine than the one I plan to give to my dad. I don't really want to gift a customer service nightmare brick.
@115821 , make your signature product work.

FULL CONVERSATION:
[CUSTOMER] Ok if my new Echo is going to need a factory reset every damn day, you and I will need to have word, Alexa.

I care less about mine than the one I plan to give to my dad. I don't really want to gift a customer service nightmare brick.
@115821 , make your signature product work.
[SUPPORT] @491681 I'm so sorry for the frustration! Without revealing account specific details, could you tell us more about the issue? Also, what troubleshooting steps have you tried? ^JP
[CUSTOMER] @AmazonHelp It just stopped responding, within a day of setting it up. A hard reset fixed it. I just don't want to redo the setup process every day. Not do I want to give my dad a device that requires daily setup.
[CUSTOMER] @AmazonHelp Idk what you can do now aside from alerting the update team that they need to get on a real fix.
[CUSTOMER] @AmazonHelp Hopefully soon, so I don't have to spend the entire week of Christmas on the phone with @AmazonHelp
[SUPPORT] @491681 Has it been working since the hard reset or is it continuing to give you trouble? ^LA
[CUSTOMER] @AmazonHelp Yes, it has worked after a third hard reset.
[SUPPORT] @491681 Thanks for the update! Please let us know if there is anything further needed. ^MO
[CUSTOMER] @AmazonHelp Well, yeah. I'd like some assurance that the other devices I purchased from you will actually work.
Your responses have notably not addressed the future at all
@AmazonHelp
[CUSTOMER] @AmazonHelp Should I bother giving your device as an Xmas present, given that that entais months of phone support to fix what Amazon won't even own up to?
[SUPPORT] @491681 Our Echo devices all come with warranties. You can find more information about them here: https://t.co/vNgGwnnNSt ^LA
[CUSTOMER] @AmazonHelp Cool, so when my gift inevitably breaks, I know where to complain.
Maybe be a bit more proactive and make my gift *not* be a brick? Crazy idea, I know.
[CUSTOMER] @AmazonHelp Contacting the company about the warranty should not be a necessary part of purchasing your products.
Please tell me why you demand that extra from your customers.
[CUSTOMER] @AmazonHelp Yeah I did that. I got no help there.
Hence resorting to social media to hopefully shame @115821  into standing by their devices and maybe making them work

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 68
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp Just wanted to thank you for exceptional delivery service today. Lady delivering in HD4, Huddersfield, went above and beyond to deliver parcels when the road was shut. It’s a long walk!

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp Just wanted to thank you for exceptional delivery service today. Lady delivering in HD4, Huddersfield, went above and beyond to deliver parcels when the road was shut. It’s a long walk!
[SUPPORT] @722537 Delighted to hear you received your parcels!! Enjoy😁. - Conor

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 69
==========================================================================================
Conversation size : 6
Customer turns   : 3
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
Amazonから倉木麻衣のCDがこないよーーーー
代金支払って25日発送されてお届け予定日28日なんだけど追跡番号見る限りは集荷した郵便局から１ミリも動いてない

FULL CONVERSATION:
[CUSTOMER] Amazonから倉木麻衣のCDがこないよーーーー
代金支払って25日発送されてお届け予定日28日なんだけど追跡番号見る限りは集荷した郵便局から１ミリも動いてない
[SUPPORT] @715936 Amazonです。商品のお届けについてご心配をおかけしております。大変お手数ではございますが、配送業者へご確認いただきますようお願いいたします。SK
[CUSTOMER] @AmazonHelp 昨日はリプありがとうございました。郵便局で聞いたところ出荷漏れでは？と言われたのでカスタマーセンターに商品が届かないと連絡をして交換というかたちで発送していただくことになりました。ガラケーなので聞き取りにくかったかと思いますが対応ありがとうございました
[SUPPORT] @715936 わざわざご連絡いただき、ありがとうございます。このたびはお手数ならびにご不便をおかけいたしました。代替商品のお届けまで、今しばらくお待ちください。
今後ともご利用の際に何かお困りのことやご不明点があれば、いつでもご遠慮なくお問い合わせください。RI
[CUSTOMER] @AmazonHelp 今まで届かないということがなかったのでどうしたら…と思っていたのですが、昨日リプいただけたおかげで連絡してみようと思いました。迅速に対応していただきありがとうございました。今度こそ届くのを祈ります(笑)
[SUPPORT] @715936 少しでもお客様のお役に立てて幸いでございました。　恐れ入りますが、商品の到着を今しばらくお待ちくださいますようお願いいたします。リプライありがとうございました。　SM

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 70
==========================================================================================
Conversation size : 4
Customer turns   : 1
Support turns    : 3
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115850 I purchased Nokia 6 from amazon order #408-4016399-0973128. Now when I wanted to return it the CC not giving me proper response.

FULL CONVERSATION:
[CUSTOMER] @115850 I purchased Nokia 6 from amazon order #408-4016399-0973128. Now when I wanted to return it the CC not giving me proper response.
[SUPPORT] @174681 we consider them to be personal info. Our Twitter page is visible to public. ^MP (3/3)
[SUPPORT] @174681 Amazon.in Returns Policies here: https://t.co/S3T8hQ7Z3J. Please don’t provide your order details, ^MP (2/3)
[SUPPORT] @174681 All smartphones on Amazon.in are covered by 10 days - replacement only policy. Know more about ^MP (1/3)

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 71
==========================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
@AmazonHelp i keep getting this error every time i want to check my order, place an order, check my account etc https://t.co/N5lVxaXp2b

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp i keep getting this error every time i want to check my order, place an order, check my account etc https://t.co/N5lVxaXp2b
[SUPPORT] @724984 Uh oh! Have you tried signing out and signing back in? If so, please also try force closing the app and restarting it. Let us know how it goes! ^DY
[CUSTOMER] @AmazonHelp Signing out and signing in worked!! Thanks :)

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 72
==========================================================================================
Conversation size : 17
Customer turns   : 10
Support turns    : 7
Size bucket      : 9_plus_tweets

CUSTOMER:
Rapidly coming to the conclusion that @115830’s service has gone massively downhill since Amazon Logistics took over deliveries. Should have got better, is now awful. Won’t pick up faulty goods, expect customer to pay for returns (which will be refunded allegedly). Poor show.

FULL CONVERSATION:
[CUSTOMER] Rapidly coming to the conclusion that @115830’s service has gone massively downhill since Amazon Logistics took over deliveries. Should have got better, is now awful. Won’t pick up faulty goods, expect customer to pay for returns (which will be refunded allegedly). Poor show.
[SUPPORT] @55043 I'm sorry to hear about this poor experience, Sarah. Without sharing personal account information, could you let us know a little more about the issue you're facing? ^TH
[CUSTOMER] @AmazonHelp My other half ordered a coffee machine on PrimeNow. It arrived in just the product box, no packaging. It leaked hot water everywhere when setting it up. He tried to arrange a return - no option to have it picked up. Called, but told he would have to find a box and pay for return.
[SUPPORT] @55043 When was the item received, did you order this within the last 30 days? ^GR
[CUSTOMER] @AmazonHelp Ordered and delivered today on PrimeNow
[SUPPORT] @55043 I understand your frustration. When creating the return label, does the reason for return show "damaged/defective" or something else? More information about organizing a collection for your return can be found here: https://t.co/PfAeslqz49 ^SK
[CUSTOMER] @AmazonHelp Not sure what the form says, but both customer service reps insist that it is not possible for it to be picked up - “the system won’t allow it”
[CUSTOMER] @AmazonHelp Can you give me a UK complaints telephone number where we can talk to someone with some authority to fix the problem instead of someone stuck in a call centre who doesn’t care at all?
[SUPPORT] @55043 When you last spoke with us, were we able to help set up the return? If not, we're available whenever you have time here: https://t.co/653wjokbGF ^EP
[CUSTOMER] @AmazonHelp No, they are just saying the system won’t allow them to arrange a pickup. Quite honestly we’ve spoken to call centre staff for long enough today - at least an hour - I want a complaints number in the UK.
[SUPPORT] @55043 I'd like to have a specialist from our team take a look into this for you. Please leave us some detailed information here: https://t.co/13jd9gbOVQ ^TH
[CUSTOMER] @AmazonHelp Full details left on the form. I sincerely hope you can help resolve this. Talk to you tomorrow.
[CUSTOMER] @AmazonHelp Well, that was utterly pointless. 40 hours after filling in that form explaining the issue in detail, I finally had an email saying that they won’t do anything at all because I didn’t write from the email associated with the order. No-one is looking into this.
[SUPPORT] @55043 I'm sorry about that Sarah, can you fill out the form provided again, ensuring you sign into the account the order was placed on. Due to account security we are only able to take action if the request comes from the account associated with the order. ^MI
[CUSTOMER] @AmazonHelp I made it exceptionally clear that I was talking about an order placed by my partner and I was still told to fill in that form. Seriously unhappy right now.
[SUPPORT] @55043 Apologies - we do have procedures to follow for Account security. Can your partner fill in their details so we can assist ? ^TD
[CUSTOMER] @AmazonHelp Then why was I told to fill in the form? If no-one was going to take any notice of it, why was I asked to give details on that form? Oh maybe it was just to distract from my request for a UK-based complaints number, which I want now.

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 73
==========================================================================================
Conversation size : 7
Customer turns   : 4
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp @116928  Asi entrega los paquetes vuestra compañia @137605 https://t.co/ydRfKTzaWe

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp @116928  Asi entrega los paquetes vuestra compañia @137605 https://t.co/ydRfKTzaWe
[CUSTOMER] @AmazonHelp @116928 @137605 adjunto las opiniones  que son 200 negativas y ni una positiva #correoexpress https://t.co/bfeOB6npjW
[SUPPORT] @787946 Hola, Jos. Sentimos mucho la experiencia que has tenido. ¿Podrías indicarnos si el paquete presenta algún daño? ^DB
[CUSTOMER] @AmazonHelp La verdad esque no me he atrevido a mirar el segundo paquete asi que lo he comentado y me van a hacer un reemplazo esperemos que no sea correos quien lo gestione
[SUPPORT] @787946 Recuerda que puedes reportar cualquier incidente con nuestros compañeros de servicio al cliente o al siguiente enlace: https://t.co/qjpXgZ6jUh. ^NP
[CUSTOMER] @AmazonHelp alguna manera de que correos no gestione mis envios despues de 3 incidencias con ellos y esta siendo la cuarta?
[SUPPORT] @787946 Puedes reportarlo a través del enlace indicado anteriormente o por medio de Soporte al Cliente en este enlace: https://t.co/OjvUxwnzPe
Un saludo,
^DB

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 74
==========================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
@AmazonHelp Hello, I have recently bought the echo and the fire tv stick. Both of them are not working. The Echo keeps saying not registered, and the Fire tv stick does not get set up after looking for updates.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp Hello, I have recently bought the echo and the fire tv stick. Both of them are not working. The Echo keeps saying not registered, and the Fire tv stick does not get set up after looking for updates.

In [177]:
# Display Set 6: examples 150–179

start, end = 150, 179

for i in range(start, end + 1):
    row = training_batch.iloc[i]

    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print()
    print("CUSTOMER:")
    print(row["first_customer_message"])
    print()
    print("FULL CONVERSATION:")
    print(row["conversation_text"])
    print()
    print("CURRENT LABEL:")
    print("[ UNLABELED ]")
    print()

==========================================================================================
EXAMPLE 150
==========================================================================================
Conversation size : 12
Customer turns   : 8
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
Government’s reforms to push economic growth are working can be seen from that manufacturing has shown robust growth of 7% in Q2 and services at 7.1%. Gross fixed capital formation has increased from 1.6% in Q1 to 4.7% in Q2.

FULL CONVERSATION:
[CUSTOMER] Government’s reforms to push economic growth are working can be seen from that manufacturing has shown robust growth of 7% in Q2 and services at 7.1%. Gross fixed capital formation has increased from 1.6% in Q1 to 4.7% in Q2.
[CUSTOMER] @137848 @115850 @5834  this site continues doing a farud with seller almost 50 sellers I received complain they suspend account then they never contact all payment get zero
[SUPPORT] @137847 I'm sorry to learn this, has this been reported to our seller support team here: https://t.co/hITbmQzz2y? ^VN
[CUSTOMER] @AmazonHelp @AmazonHelp your team doing totally farud with us we are seller if our account was suspend then why your team not giving any support or guide us. You charging a big amount commission and also doing farud
[CUSTOMER] @AmazonHelp @137848 @115821 arun Sir this amazon company making own policy please support us ecommerce companies making everyday own policy against us. So now where we go
[SUPPORT] @137847 I understand that you're concerned regarding your seller account on Amazon. Could you please confirm if you've contacted our seller support team using the link provided earlier. ^MP
[CUSTOMER] @AmazonHelp No now i dont want to contact now i want file a case against in indian court
[CUSTOMER] @AmazonHelp Personally i lost more then 2 lakhs rupees and i have also recieved many complaint so we all togather file case in a court and then we talk in media
[SUPPORT] @137847 Our apologies for any inconvenience you had to go through, Ashoni. Please reach out to our support team here: https://t.co/hITbmQzz2y and we'll look into this. ^MK
[CUSTOMER] @AmazonHelp I already reach there which you link send me i mention there every thing but i know your team is very busy they very well know how to farud with seller its sound very good . Amazon have own policy sellers are nothing right @115851
[CUSTOMER] @AmazonHelp @115851 @118702 @122599 @122951 @14281 @2517 @137849 @12180 @20871
[SUPPORT] @137847 Sorry for the hassle, Ashoni. We'd like to help you, please share your details here: https://t.co/beaaDm0muc and we’ll contact you soon. ^SM

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 151
==========================================================================================
Conversation size : 3
Customer turns   : 1
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115850 Worst order thru Prime.. Order# 171-2807126-5805153
No updates on order n finally get a damaged piece without gift wrap n msg https://t.co/ivgGkNUiQp

FULL CONVERSATION:
[CUSTOMER] @115850 Worst order thru Prime.. Order# 171-2807126-5805153
No updates on order n finally get a damaged piece without gift wrap n msg https://t.co/ivgGkNUiQp
[SUPPORT] @510547 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. 2/2 ^RI
[SUPPORT] @510547 Sorry for the hassle. Please contact us here: https://t.co/rS49hgaADF so that we can assist you accordingly. 1/2 ^RI

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 152
==========================================================================================
Conversation size : 7
Customer turns   : 4
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
amazonのサイバーマンデーすごく広告が出るけどどうやったらたどり着けるんだろうか？普通のタイムセールにしか行くことができない。

FULL CONVERSATION:
[CUSTOMER] amazonのサイバーマンデーすごく広告が出るけどどうやったらたどり着けるんだろうか？普通のタイムセールにしか行くことができない。
[SUPPORT] @243946 リプライ失礼いたします、Amazon公式アカウントです。2017年のサイバーマンデーは12/8からの開催となっております。開催まで今しばらくお待ちくださいませ。セール情報は以下リンクにて随時更新をいたしております。https://t.co/TkzSh4s4A3 HM
[CUSTOMER] @AmazonHelp 人工知能と疑ってすみませんでした。丁寧なリプライ心に響きました。遅い時間までお疲れ様です。頑張ってください。
[SUPPORT] @243946 とんでもないことです！いつもAmazonをご覧いただきありがとうございます🙇　サイバーマンデーをお楽しみにしていただき、うれしく思っております。ぜひご期待くださいませ😊
夜分にリプライを失礼いたしました。HM
[CUSTOMER] @AmazonHelp HMってURLの一部なのかと思ってたら名前なんですか？ちゃんと人がいることが感じられました。こんな無駄な会話なのにリプライありがたいです。頑張ってください。
[SUPPORT] @243946 こちらこそ、ツイートにお付き合いいただき、ありがとうございました。あたたかいお言葉、中の人一同喜んでおります。最後はわたくしめより… RI
[CUSTOMER] @AmazonHelp こんなに！リプライが続くとは思ってもいませんで、嬉しいですね。ありがとうございます。大量投入される動画広告の16倍くらい印象に残るものとなりました。広告と比較するものでもありませんけど..

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 153
==========================================================================================
Conversation size : 6
Customer turns   : 4
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp Warum kommt meine Bestellung mit Standardversand früher als mit Premiumversand? Oder stimmt die Angabe nicht? https://t.co/UTl0xHFc5S

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp Warum kommt meine Bestellung mit Standardversand früher als mit Premiumversand? Oder stimmt die Angabe nicht? https://t.co/UTl0xHFc5S
[SUPPORT] @434823 Hi, zugegeben, das sieht ungewöhlich aus. Dies ist aber der Fall, wenn der Artikel nicht in einem "primefähigen" Logistikzentrum vorliegt. Das Langstrecke bedeutet, dass der andere Artikel aus dem Ausland an dich versendet würde. Daher die längere Lieferzeit. Gruß ^JS
[CUSTOMER] @AmazonHelp Wenn ich das Paket aber so schnell wie möglich haben möchte, soll ich dann besser Premium oder Standard wählen?
[CUSTOMER] @AmazonHelp Prinzipiell sollte ja ein Paket mit Premiumversand schneller hier sein als mit Standardversand, oder?
[SUPPORT] @434823 In diesem - eher ungewöhlichen - Fall empfehle ich dir tatsächlich den Standardversand. Da die Langstrecke durchaus etwas länger sein kann, was ja bei der Lieferzeit bereits berücksichtigt wurde. Gruß ^JS
[CUSTOMER] @AmazonHelp Okay, alles klar. Dann bestelle ich das so. Vielen Dank!

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 154
==========================================================================================
Conversation size : 15
Customer turns   : 7
Support turns    : 8
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850 sends fake electronic products and leaves you stuck with the e-waste disposal process #EpicFail

FULL CONVERSATION:
[CUSTOMER] @115850 sends fake electronic products and leaves you stuck with the e-waste disposal process #EpicFail
[SUPPORT] @695257 The sellers are committed to sell genuine products on the website. Could you tell us more (1/2)
[SUPPORT] @695257 about your concern for better assistance? (2/2)^YP
[CUSTOMER] @AmazonHelp 171-0453613-0568340
[CUSTOMER] @AmazonHelp These days @115850 is an aggressive advertiser for brick n mortar stores. This is my 2nd bad UPS experience.
[SUPPORT] @695257 Please don’t provide your order details as we consider them to be personal info. Our page is visible to public. ^PB (2/2)
[SUPPORT] @695257 Apologies for the trouble. Kindly connect with us here:https://t.co/vlvfJr4nN9
and we'll get this sorted for you. ^PB (1/2)
[CUSTOMER] @AmazonHelp have received the wrong product.have been sent ups 621i, which is different from iBall Nirantar UPS-621V.The one i received doesn't work
[CUSTOMER] @AmazonHelp Deleted the order number. Given you the review that you have refused to print.
[SUPPORT] @695257 As requested earlier, have you been in touch with our support team? ^RB
[CUSTOMER] @AmazonHelp Yes I have. That's why I'm stuck with e-waste disposal for the fake product I received.
[SUPPORT] @695257 details here:https://t.co/cQVomR1pWz and we'll sort this for you at the earliest. 2/2 ^KH
[SUPPORT] @695257 I'm sorry to hear about the trouble you've had with your order. Kindly share your 1/2 ^KH
[CUSTOMER] @AmazonHelp Done.
[SUPPORT] @695257 Thank you for confirming. We'll check and get in touch with you at the earliest. ^RI

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 155
==========================================================================================
Conversation size : 13
Customer turns   : 6
Support turns    : 7
Size bucket      : 9_plus_tweets

CUSTOMER:
made 2 times call to the customer support,every once I call they just update the status. How come one courier left from a place twice aday. https://t.co/NPoeT45Hoq

FULL CONVERSATION:
[CUSTOMER] made 2 times call to the customer support,every once I call they just update the status. How come one courier left from a place twice aday. https://t.co/NPoeT45Hoq
[SUPPORT] @448413 Sorry for the trouble with your order. Kindly fill in your details here: https://t.co/GIJyeYqKE0 &amp; I'll look into this. ^SQ
[SUPPORT] @448413 Please don't provide your order details as we consider it personal information. Our twitter page is visible to public. ^SQ
[CUSTOMER] @AmazonHelp Then please rectify it, don't request the customers to remove the complaints.
[SUPPORT] @448413 Apologies. Request you to please fill in the details in the link mentioned earlier and we'll look into this. ^MK
[CUSTOMER] @AmazonHelp Already done, how many times do I have to fill a form for a product ?
[SUPPORT] @448413 Sorry for the miss. I've just checked and we've received your details. Please allow us some time and we'll reach out. ^KA
[CUSTOMER] @AmazonHelp What's the status of my order. I haven't recieved any updates on this.
[SUPPORT] @448413 We are working on it, we'll get back to you at the earliest. ^SC
[CUSTOMER] @AmazonHelp Superb response ,then why is it advertised if you order in next 2 hour you will get delivered in a day.Fake promotions regarding delivery. https://t.co/BfWJPz5Fw5
[CUSTOMER] @AmazonHelp Worst response, asking customers to wait.
[SUPPORT] @448413 I get your concern, please reply to the email you received and we'll get back to you soon. 1/2 ^PS
[SUPPORT] @448413 Please don't provide your order details, as we consider it to be personal info. Our page is visible to the public. 2/2 ^PS

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 156
==========================================================================================
Conversation size : 8
Customer turns   : 3
Support turns    : 5
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115850 paid extra 4delivery before 11am.The delivery hs not yet reached,the boy told me he wl cm by 1145 bt I hv got this message! Fraud! https://t.co/n6HdCBsaHn

FULL CONVERSATION:
[CUSTOMER] @115850 paid extra 4delivery before 11am.The delivery hs not yet reached,the boy told me he wl cm by 1145 bt I hv got this message! Fraud! https://t.co/n6HdCBsaHn
[CUSTOMER] @115850 I cannot imagine how many consumers are getting cheated this way ! Awaiting your response @115850 @115821 ! #fraud
[SUPPORT] @294043 I'm sorry the tracking for the order has been updated as delivered even though you haven't received the package. 1/3 ^SH
[SUPPORT] @294043 This could be due to incorrect tracking scan update. Please report this to our 2/3 ^SH
[SUPPORT] @294043 support team here: https://t.co/Ldhd8cuJB1 and we'll be happy to help. 3/3 ^SH
[CUSTOMER] @AmazonHelp This is not incorrect scan.I spoke to the delivery guy.He is still 40 mts https://t.co/yOyGTewOu3 cud the update be sent w/o the delivery?
[SUPPORT] @294043 I'm sorry for the conflicting tracking update. Kindly reach out to our team using the link shared 1/2 ^GK
[SUPPORT] @294043 earlier and we'll have this checked. (2/2) ^GK

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 157
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
I get a text alert from @115821 saying my item has been delivered. Check to see if it's there and...wait for it....IT'S NOT!! WTF!!! 😡😡😡

FULL CONVERSATION:
[CUSTOMER] I get a text alert from @115821 saying my item has been delivered. Check to see if it's there and...wait for it....IT'S NOT!! WTF!!! 😡😡😡
[SUPPORT] @289624 I'm sorry for the trouble! Does the following provide any help in locating your package: https://t.co/p5YQ9CCNo1 ^ST

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 158
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115850
Both SS have same MRP but weight is 100g and 200g respectively.
This time don't say MRP keep on changing https://t.co/JT0LRHJ1pw

FULL CONVERSATION:
[CUSTOMER] @115850
Both SS have same MRP but weight is 100g and 200g respectively.
This time don't say MRP keep on changing https://t.co/JT0LRHJ1pw
[CUSTOMER] @115850 This is what ur seller did by showing wronh MRP and then huge discount on 100g
[SUPPORT] @201405 Pricing and offers are decision of the sellers. The constantly changing marketplace and our efforts to offer [1/2]^SK
[SUPPORT] @201405 you the lowest price, may result in fluctuations in our prices over time. [2/2] ^SK
[CUSTOMER] @AmazonHelp You mean to say that seller can write any higher MRP and offer discount to allure people

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 159
==========================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
@AmazonHelp No, that is precisely why I am so confused/frustrated.

FULL CONVERSATION:
[SUPPORT] @211137 Have you disputed any charge with your bank, or had any previous issues with your account? ^TR
[CUSTOMER] @AmazonHelp No, that is precisely why I am so confused/frustrated.
[SUPPORT] @211137 I'd like to have a colleague to look into what you've mentioned. Please leave your info here: https://t.co/E86xBwSBKZ ^PF
[CUSTOMER] @AmazonHelp I left my info, thanks.

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 160
==========================================================================================
Conversation size : 8
Customer turns   : 4
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115821 its very unfortunate, such i highly estimed brnd is fooling their custmrs. Amazon has 4-5 times escaleted my issue bt no result yet😑

FULL CONVERSATION:
[CUSTOMER] @115821 its very unfortunate, such i highly estimed brnd is fooling their custmrs. Amazon has 4-5 times escaleted my issue bt no result yet😑
[SUPPORT] @446017 Certainly not what we want you to experience. Kindly elaborate your concern. We would like to help. ^CB
[CUSTOMER] @AmazonHelp I have contacted customer support and they have escalated my issue 3-4 times but no result   yet
[CUSTOMER] @AmazonHelp And since i have returned the product and have the proof of same then why I'm being delayed for the refund
[CUSTOMER] @AmazonHelp I have returned a product but i havnt got my refund yet. Piuck up date 6/10 registered email - __email__
[SUPPORT] @446017 Sorry about the delay with your refund. I'd like to take a closer look into this. (1/2)^SQ
[SUPPORT] @446017 Kindly drop in your details here: https://t.co/GIJyeYqKE0 and I'll reach out to you. (2/2)^SQ
[SUPPORT] @446017 Please don't provide your email address as we consider it personal information. Our twitter page is visible to public. ^SQ

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 161
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115850 Tracking #: 216273107531.
Being prime member, product is not getting delivered even after 2, 4 business days. #AmazonPrime there is of no use.

FULL CONVERSATION:
[CUSTOMER] @115850 Tracking #: 216273107531.
Being prime member, product is not getting delivered even after 2, 4 business days. #AmazonPrime there is of no use.
[SUPPORT] @209581 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^RW 2/2
[SUPPORT] @209581 I'm sorry for the delay in delivery. If we have missed the estimate delivery date on the order, please get in touch with our support team here: https://t.co/2t6DQoUmNZ ^RW 1/2
[CUSTOMER] @AmazonHelp it says product delivered to customer with signature... and product yet not delivered....? m still waiting.
[CUSTOMER] @AmazonHelp do proceed with refund... useless #Prime....!

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 162
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115825 @AmazonHelp Gibt es bei Euch #Probleme beim #Streaming-&gt;die #Ladezeiten sind sehr lang über die #App in #IOS11

FULL CONVERSATION:
[CUSTOMER] @115825 @AmazonHelp Gibt es bei Euch #Probleme beim #Streaming-&gt;die #Ladezeiten sind sehr lang über die #App in #IOS11
[SUPPORT] @193267 Du kannst das versuchen: https://t.co/My5rk17xQ2 Falls es weiterhin nicht klappt, zur Prüfugn per: https://t.co/MBAcWSvzBH ^MH

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 163
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
This is so frustrating @115821. I need the supervisors supervisor to help me and finally get this done.

FULL CONVERSATION:
[CUSTOMER] This is so frustrating @115821. I need the supervisors supervisor to help me and finally get this done.
[SUPPORT] @288407 Sorry to hear that the issue hasn't been resolved yet. Please get in touch https://t.co/R55eEQwSEs and we'll investigate. ^BM

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 164
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115850
Very very poor service.

Damaged product.
Terrible Attitude by your customer care executives.

You'll need to rethink your  training of customer care.

FULL CONVERSATION:
[CUSTOMER] @115850
Very very poor service.

Damaged product.
Terrible Attitude by your customer care executives.

You'll need to rethink your  training of customer care.
[SUPPORT] @385272 Apologies for the experience you had with this order. Please share your details here: https://t.co/beaaDm0muc and we'll contact you soon.​ ^JS

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 165
==========================================================================================
Conversation size : 4
Customer turns   : 3
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:

In [178]:
# Display Set 7: examples 180–209

start, end = 180, 209

for i in range(start, end + 1):
    row = training_batch.iloc[i]

    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print()
    print("CUSTOMER:")
    print(row["first_customer_message"])
    print()
    print("FULL CONVERSATION:")
    print(row["conversation_text"])
    print()
    print("CURRENT LABEL:")
    print("[ UNLABELED ]")
    print()

==========================================================================================
EXAMPLE 180
==========================================================================================
Conversation size : 7
Customer turns   : 3
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
No matter how loud you cry @115850 is not gonna hear sellers. A blind eye approach. Stopping all Ads @128876 @115851 #HearUsAmazon https://t.co/jeCP6SD7C6

FULL CONVERSATION:
[CUSTOMER] No matter how loud you cry @115850 is not gonna hear sellers. A blind eye approach. Stopping all Ads @128876 @115851 #HearUsAmazon https://t.co/jeCP6SD7C6
[SUPPORT] @129201 Sorry for the unpleasant experience with us. We'd like to know what went wrong, (1/2)^SQ
[SUPPORT] @129201 please contact our seller support team here: https://t.co/hITbmQzz2y. We'll look into it. (2/2)^SQ
[CUSTOMER] @AmazonHelp Everything went wrong in last 1 year.  Every genuine concern is ignored with a Blind Eye.  Seller Support, Escalation Support all failed.
[SUPPORT] @129201 We'd like to take a closer look into this. Please fill in this form: https://t.co/GIJyeYqKE0 and we'll look into it. ^SQ
[CUSTOMER] @AmazonHelp Seller Support is helpless &amp; we can only get template copy+paste replies from them. Genuine concerned are being ignored like Garbages
[SUPPORT] @129201 I understand your concern. Request you to share your details in the link provided earlier and we'll help you with this. ^SQ

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 181
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@115821 has done fraud to me by not refunding money of cancelled order worth 13999/- rupees. Now I can't trust this company. I have complained everywhere, let's see what will happen.

FULL CONVERSATION:
[CUSTOMER] @115821 has done fraud to me by not refunding money of cancelled order worth 13999/- rupees. Now I can't trust this company. I have complained everywhere, let's see what will happen.
[SUPPORT] @256571 I'm sorry about the delay with the refund; we'd like to help. Please drop your details here: https://t.co/GIJyeYqKE0. We'll check and reach out to you with an update. ^VN

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 182
==========================================================================================
Conversation size : 12
Customer turns   : 7
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
@115823 Our account was suspended for no logical reason. No response from you in days despite repeated requests for help.

FULL CONVERSATION:
[CUSTOMER] @115823 Our account was suspended for no logical reason. No response from you in days despite repeated requests for help.
[SUPPORT] @300938 Hey, sorry to hear about the trouble! W/o providing personal or acct specific info, can you tell us more? ^LB
[CUSTOMER] @AmazonHelp Thanks. Can you give me a human being to call to discuss? We are a merchant. Unbelievable that no number for merchants to call for help.
[SUPPORT] @300938 You can reach out to our Seller Support team here: https://t.co/Djfb8eCbZS They'd be happy to help! ^ZW
[CUSTOMER] @AmazonHelp I've contacted them many times via our AmazonPay Account. Just get forwarded to another dept. No # for merchants in good standing to call?
[CUSTOMER] @AmazonHelp @115823 How can merchants trust you to process payments if you arbitrarily suspend long-term accounts in good standing &amp; then disappear?
[SUPPORT] @300938 What department are we stating we've forwarded your concern to? Have we provided a time frame for follow up? ^RA
[CUSTOMER] @AmazonHelp It's the @115823 team. Yes, they were supposed to respond by yesterday.
[CUSTOMER] @AmazonHelp What happens is that every support department refers us to someone else. Round and round it goes. @115823 do you care about merchants?
[SUPPORT] @300938 Please provide as much info as possible here: https://t.co/n10hjYK0A1 so a member of our Social Media team can look into this.^ZW
[CUSTOMER] @AmazonHelp OK. Filled it out. Hopefully, a real human can now contact me to discuss. Hard to believe @115823 can't provide support for merchants.
[SUPPORT] @300938 Thank you for the update! I have confirmed that we have received the information you sent. Someone will be in touch soon! ^AL

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 183
==========================================================================================
Conversation size : 9
Customer turns   : 5
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
@AmazonHelp This is my worst experience with you.I had to face huge troubles from Amazon. I've talked to your customer service a lot.
You have returned my package back. At least you should have informed me.I wouldn't have expected more Completely disappointing trade this time.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp This is my worst experience with you.I had to face huge troubles from Amazon. I've talked to your customer service a lot.
You have returned my package back. At least you should have informed me.I wouldn't have expected more Completely disappointing trade this time.
[SUPPORT] @263831 We apologize for the issue regarding your latest order, Anupam. Kindly fill in your details here: https://t.co/beaaDm0muc so that we can look into the issue and resolve it as soon as possible. ^MN
[CUSTOMER] @AmazonHelp I got a message now. It says I have rejected the package so it is being returned. I never guessed that Amazon is liar. You are accusing me that I have refused to take. Sir, my complain number is 4366. Mark my word if I don't get my package by tomorrow. I won't continue with you
[SUPPORT] @263831 I understand your concern regarding the delivery of your order, Anupam. We'll certainly help you with this. Could you please confirm if you have shared your details on the link provided earlier? ^SY
[CUSTOMER] @AmazonHelp I am having problem. What is "URL to Twitter message" section. I am operating it from phone. How can click right button??
[CUSTOMER] @AmazonHelp I have been waiting for my package for yesterday. Your executive says order another one. Forget it. You are not able to provide me this package. How do you expect me to do it again.
[SUPPORT] @263831 In that case you can ignore the URL section and fill the rest of the fields and submit. As soon as we receive your details we would assist you accordingly. ^MD
[CUSTOMER] @AmazonHelp I was going ahead without URL field. But it seems it is mandatory to fill. Do I give my order id through messaging you..??
[SUPPORT] @263831 You may just copy this link here: https://t.co/KAbFVRdL6o and paste it on the requested field. Do let us know for any further concern. ^AM

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 184
==========================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
What a amazing delivery by @115850
Order :406-1812084-5433962
Officially product delivered twice but actually not delivered yet.

FULL CONVERSATION:
[CUSTOMER] What a amazing delivery by @115850
Order :406-1812084-5433962
Officially product delivered twice but actually not delivered yet.
[SUPPORT] @320332 That's strange. I’d like to assist you. Please fill this form: https://t.co/beaaDm0muc and I’ll contact you soon. 1/2 ^NK
[SUPPORT] @320332 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ 2/2 ^NK
[CUSTOMER] @AmazonHelp Done.

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 185
==========================================================================================
Conversation size : 12
Customer turns   : 7
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
.@AmazonHelp @115821 Mr. BOt. use some logic n guess what its been a month since the order.U had speculated it be delivered by Nov 10 n now it nov 21.Is it coming towards me or going away @384052 @118702 or is it walking to be delivered @100545 wud have delivered earlier https://t.co/4TBCYFBwI2

FULL CONVERSATION:
[CUSTOMER] .@AmazonHelp @115821 Mr. BOt. use some logic n guess what its been a month since the order.U had speculated it be delivered by Nov 10 n now it nov 21.Is it coming towards me or going away @384052 @118702 or is it walking to be delivered @100545 wud have delivered earlier https://t.co/4TBCYFBwI2
[SUPPORT] @119350 I'm sorry for the stretch with the estimates, this usually happens when there is a lag in procuring stock. Call us here: https://t.co/vlvfJr4nN9 &amp; we'll voice out the updates with your order. ^MJ
[CUSTOMER] @AmazonHelp .@115850 A MONTH LAG IS UNHEARD OF!!!U should have bloody told me at the time of the order.SO much technology we have. Stop cheating people. and why will i call u.. ITs ur courtesy to call me...After asking my contact details for the nth time. How dare u call me to call u
[CUSTOMER] @AmazonHelp .@AmazonHelp Dude i even called but they also failed to find my order.. If you are not a robot , please give me ur name... Or arrange for a call back to me.. twice i called without any answer. FYI this is ur job and u get paid for it. I HAVE A LIFE AND GIVE ME WHAT I ORDERED
[SUPPORT] @119350 I can understand how frustrating this is for you and I would like to help right away. Kindly fill in your details here https://t.co/3qGoblkcPm and we'll reach out to you for assistance. ^VM
[CUSTOMER] @AmazonHelp how many times do I fill it .. I just filled it an hour back.. mr VM.. @115821 stop this shit ..tell ur robots to atleast cross check
[SUPPORT] @119350 Thank you for confirming, we are working on it and will get back to you soon with an update. ^SI
[CUSTOMER] @AmazonHelp And where will you update me ??? @AmazonHelp @115850
[SUPPORT] @119350 We will send all the updates to your registered email ID associated with Amazon account. ^SC
[CUSTOMER] @AmazonHelp I want the book asap.. and the reason as to why it took so long to deliver .. a month to deliver book. Good logic .. and the time wasted by me .. atleast apologise u bot
[SUPPORT] @119350 We value your time, we shall get this order home at the earliest. ^CB
[CUSTOMER] @AmazonHelp But it is still not dispatched .. I feel for the poor people who wait and never get the thing they order but u fool people by saying it's on the way

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 186
==========================================================================================
Conversation size : 11
Customer turns   : 7
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
I'm not too sure but I don't think that my bottom/basement of the case sides are supposed to be bent like this.

@240 @AmazonHelp https://t.co/YXSsk8ag9t

FULL CONVERSATION:
[CUSTOMER] I'm not too sure but I don't think that my bottom/basement of the case sides are supposed to be bent like this.

@240 @AmazonHelp https://t.co/YXSsk8ag9t
[CUSTOMER] @240 @AmazonHelp Here's the right hand side. https://t.co/U3449olsP9
[CUSTOMER] @240 @AmazonHelp Now here's the left. https://t.co/41Lc1MjxCv
[SUPPORT] @199270 Hi, sorry to see that. Was the order sold and fulfilled by Amazon or a 3rd Party Seller? ^JJ
[SUPPORT] @199270 Apologies - When did you purchase the monitor? Reach out - https://t.co/JzP7hlA23B we'll be happy to look into this ^TP
[CUSTOMER] @AmazonHelp Sold and Fulfilled by Amazon. Literally just arrived and unboxed.
[CUSTOMER] @AmazonHelp It's not a monitor, it's the Corsair 900D. Sorry for not mentioning.
[SUPPORT] @199270 Thanks, you can contact us via the link ^TP sent or look into the options available here: http:https://t.co/5RcjVPJgUP. ^JJ
[CUSTOMER] @AmazonHelp Yeah I already followed the link that TP provided, resolved my issue and the return has been processed.
[SUPPORT] @199270 Glad to hear. Thanks for the update :-) ^TP
[CUSTOMER] @AmazonHelp Thank you and no problem.

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 187
==========================================================================================
Conversation size : 5
Customer turns   : 2
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp C10036625743   &amp;   CT0001587143
Les deux colis ont le meme statut "livré a un resident"

FULL CONVERSATION:
[SUPPORT] @174211 Bonjour, je suis désolée pour cela. Pourriez-vous me communiquer le numéro de suivi SVP? ^SM
[CUSTOMER] @AmazonHelp C10036625743   &amp;   CT0001587143
Les deux colis ont le meme statut "livré a un resident"
[SUPPORT] @174211 Nous allons remonter cela, avez-vous également signalé cet incident à notre Service client afin d'y remédier ? ^KE
[CUSTOMER] @AmazonHelp Un lien vers le service client pour remonter ces incidents recurrents ?
[SUPPORT] @174211 Voici le lien pour joindre notre SAV: https://t.co/hgIrz98cdI ^FT

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 188
==========================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
アマゾンからCDが届いたんだけど、またしてもケースの細い部分が折れちゃってフタが外れていた。これで何回目だよ。マジで改善求む！

FULL CONVERSATION:
[CUSTOMER] アマゾンからCDが届いたんだけど、またしてもケースの細い部分が折れちゃってフタが外れていた。これで何回目だよ。マジで改善求む！
[SUPPORT] @197179 Amazon公式アカウントです。大変ご迷惑をおかけし申し訳ございません。お手数をおかけしますが注文履歴から返品（交換可能であれば交換）のお手続きをお願いいたします。なお、改善のため梱包に関するご意見も注文履歴よりお送りいただければと存じます。SK
[CUSTOMER] @AmazonHelp ご丁寧なお返事ありがとうございます。返品はしていただかなくてもけっこうです。梱包に関する意見も述べさせていただきました。
[SUPPORT] @197179 ご返信いただきありがとうございます。また、梱包についてのご意見をいただきありがとうございます。Twitterでもサポートさせていただいておりますので、また何かご利用に際しご不明な点やお困りのことなどございましたら、お知らせください。ET

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 189
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
danke @116316 für das letzt iOS Update. Wann kommt das Nächste, in dem der Landscape Modus wieder funktioniert?

FULL CONVERSATION:
[CUSTOMER] danke @116316 für das letzt iOS Update. Wann kommt das Nächste, in dem der Landscape Modus wieder funktioniert?
[SUPPORT] @337464 Ist derzeit leider nicht bekannt. Dein Feedback gebe ich natürlich gern weiter. Liebe Grüße ^MF

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 190
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Despite paying for @115830 Prime they still sometimes struggle to deliver within a week!

FULL CONVERSATION:
[CUSTOMER] Despite paying for @115830 Prime they still sometimes struggle to deliver within a week!
[SUPPORT] @132438 Hi Dominic, are you waiting for orders to be delivered? ^JC.

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 191
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115850 they are lier https://t.co/9gjGE79vfI

FULL CONVERSATION:
[CUSTOMER] @115850 they are lier https://t.co/9gjGE79vfI
[CUSTOMER] @115850  https://t.co/FpesjoNaqd
[SUPPORT] @231112 Also, please don't provide your details, we consider it to be personal information. Our Twitter page is visible to public. (2/2) ^SD
[SUPPORT] @231112 I understand this has been an unpleasant experience due to the delay in delivery of your order. We'd like to make things right for you. Please reach out to our support team using the link provided earlier and we'll help you. (1/2) ^SD
[CUSTOMER] @AmazonHelp when will you make right it was already wrong thing going on @115821

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 192
==========================================================================================
Conversation size : 10
Customer turns   : 5
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850 terrible delivery service @118919 amazon not fulfill ur promise see i haven't get my phone yet. #BakwasAmazon https://t.co/QKem1KY8P9

FULL CONVERSATION:
[CUSTOMER] @115850 terrible delivery service @118919 amazon not fulfill ur promise see i haven't get my phone yet. #BakwasAmazon https://t.co/QKem1KY8P9
[SUPPORT] @191826 Sorry to know about the delay with the order. Please share your details here: https://t.co/GIJyeYqKE0 and we'll reach out. ^KA
[SUPPORT] @191826 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. ^KA
[CUSTOMER] @AmazonHelp Oh. And what about you, you tell a lie your customers. I don't get any single call your delivery agent. If you speak truth show me proof.
[CUSTOMER] @AmazonHelp Your promise date end. I haven't received my order yet. I call to you many times. And ur customer representative unabe to help me @115850
[CUSTOMER] @AmazonHelp @119356 @118919 #BakwasAmazon
@120320 @2517 i am prime customer. You treat like that. What about ur next day delivery promise
[SUPPORT] @191826 I get your disappointment and I'm sorry about this ill experience. Please share your details and we'll help. ^HA
[CUSTOMER] @AmazonHelp @115850 @118919 @120320 @2517 I have already shared my all details. #BakwasAmazon
[SUPPORT] @191826 Your order/account details on Twitter will not help us gain access to your account. 1/2 ^MJ
[SUPPORT] @191826 We have received your details, appreciate your patience while we get back to you. 2/2 ^MJ

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 193
==========================================================================================
Conversation size : 8
Customer turns   : 5
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
Once again, @115830 promises Prime next day delivery, then fails. I have had it with this service.

FULL CONVERSATION:
[CUSTOMER] Once again, @115830 promises Prime next day delivery, then fails. I have had it with this service.
[SUPPORT] @271091 Hello! I'm really sorry for the frustration! We'd like to help! Please reach out to us via phone or chat here: https://t.co/JzP7hlA23B ^AJ
[CUSTOMER] @AmazonHelp I tried to reply to this via your orders dialogue, but it would not let me do it. Bottom line: you promised these items yesterday, and they aren't even here today, and I am sick and tired of your fibs. I was here all day and my CCTV proves this.
[SUPPORT] @271091 We strive to meet our delivery dates, however, unforeseen circumstances may cause a late delivery. We're available to address this concern via the link AJ provided. ^SJ
[CUSTOMER] @AmazonHelp 'Unforeseen circumstances'? Another Amazon delivery, scheduled for later, arrived here today, due to an excellent driver. This is the fifth time your 'next day' delivery has been a lie. Face it, your logistics aren't working any more. I am giving up now.

In [179]:
start, end = 210, 239

for i in range(start, end + 1):
    row = training_batch.iloc[i]

    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print()
    print("CUSTOMER:")
    print(row["first_customer_message"])
    print()
    print("FULL CONVERSATION:")
    print(row["conversation_text"])
    print()
    print("CURRENT LABEL:")
    print("[ UNLABELED ]")
    print()

==========================================================================================
EXAMPLE 210
==========================================================================================
Conversation size : 4
Customer turns   : 2
Support turns    : 2
Size bucket      : 3_to_4_tweets

CUSTOMER:
Also dad können mir @116316 und @124285 bestimmt erklären.
Ich sitze auf Arbeit. Ca. 60 Minuten von meiner Wohnung entfernt.
Wir konnte mir das Paket persönlich übergeben werden? 🤔 https://t.co/92kiqtCv4v

FULL CONVERSATION:
[CUSTOMER] Also dad können mir @116316 und @124285 bestimmt erklären.
Ich sitze auf Arbeit. Ca. 60 Minuten von meiner Wohnung entfernt.
Wir konnte mir das Paket persönlich übergeben werden? 🤔 https://t.co/92kiqtCv4v
[SUPPORT] @268677 Hast du bereits in der Sendungsverfolgung auf der DHL Webseite nachgeschaut, ob es mehr Infos dazu gibt? Nachdem du die Sendungsnummer eingetippt hast, gibt es die Option "Detaillierte Empfänger-Informationen anzeigen". ^LN
[CUSTOMER] @AmazonHelp Moin, da steht dann Nachbar und auch der Name.
Vielleicht sowas auch bei euch eintragen. Dann kommt nicht so eine Verwirrung zu stande. Das is ziemlich Unglücklich gelöst so 😅
[SUPPORT] @268677 Danke fürs Feedback, ich habe es weitergegeben. Zum Glück wissen wir ja jetzt, wo es tatsächlich abgeblieben ist :) ^AW

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 211
==========================================================================================
Conversation size : 9
Customer turns   : 5
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
.@115821 I saw a tip added into my Amazon Fresh order today without asking me ... is this new? $AMZN

FULL CONVERSATION:
[CUSTOMER] .@115821 I saw a tip added into my Amazon Fresh order today without asking me ... is this new? $AMZN
[SUPPORT] @737750 At checkout you will see a default $5.00 tip. You're welcome to change the amount without it being visible to the driver. ^JF
[CUSTOMER] @AmazonHelp Hi. Ordered something via amazon prime. It says my prime is suspended because I haven't updated my amazon prime billing info. That won't effect my 2 day shipment of my order will it?
[SUPPORT] @462773 It might. Have you checked your order to see if the delivery speed has changed, if not, click here: https://t.co/Y5jpI9gRhE ^SY
[CUSTOMER] @AmazonHelp I checked and it says it's processing so I hope so. Are you able to check if it has been gone through if I give you the order #?
[SUPPORT] @462773 I'm sorry we can't access your account via Twitter! If you'd like to be sure you can reach us here: https://t.co/hApLpM3Ejd ^AR
[CUSTOMER] @AmazonHelp @462773 I have been trying to tweet to you guys, and sent dms.. please help.
[CUSTOMER] @AmazonHelp I sent you a dm of the order #. Thats your purpose to help via twitter, yeah?
[SUPPORT] @462773 Please don´t share any account information via twitter. Instead reached out to us directly using the link provided earlier. ^LH

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 212
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@117634 The new interface on the Android app is great. Any plans to upgrade the interface in the Manage My Content zone of the Amazon website? Tagging, mark as read, easier organization, more graphical interface, drag and drop would be wonderful.

FULL CONVERSATION:
[CUSTOMER] @117634 The new interface on the Android app is great. Any plans to upgrade the interface in the Manage My Content zone of the Amazon website? Tagging, mark as read, easier organization, more graphical interface, drag and drop would be wonderful.
[SUPPORT] @643198 We're happy to hear you like it! Please don't hesitate to relay feedback through the app's menu, as it goes directly to the team that oversees improvements. ^MV

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 213
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp been told to contact your customer services department via live chat but there’s no option for that. I purchased a tablet today and it’s faulty already.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp been told to contact your customer services department via live chat but there’s no option for that. I purchased a tablet today and it’s faulty already.
[SUPPORT] @750676 Our chat services are only available on a desktop computer due to opening an additional window. Are you reaching out to us via desktop? ^BE

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 214
==========================================================================================
Conversation size : 9
Customer turns   : 5
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
@115821 have really let me down today. Ordered on PRIME yesterday morning so I'd get an item for a birthday today and it's not arriving. What do I pay that money for exactly?!

FULL CONVERSATION:
[CUSTOMER] @115821 have really let me down today. Ordered on PRIME yesterday morning so I'd get an item for a birthday today and it's not arriving. What do I pay that money for exactly?!
[SUPPORT] @800362 I'm so sorry to hear this! When you check the order, what is the latest status showing as? You can check here: https://t.co/aaDyEz1VgE ^JY
[CUSTOMER] @AmazonHelp Dispathed Today- arriving Thursday
[SUPPORT] @800362 I am sorry for the inconvience caused, Tom. We have slightly extended the delivery window for some orders. You can find more information here: https://t.co/IHwnfzgEC9. ^SM
[CUSTOMER] @AmazonHelp It should have been specified on the order! I ordered through prime as its suppose to be GUARANTEED next day delivery. Funnily enough i needed it today
[SUPPORT] @800362 Sorry to hear that. Can I ask what the delivery date provided at checkout and on your confirmation email was?^TI
[CUSTOMER] @AmazonHelp Jist said dispatched. Again, it was Prime ticked so it should be delivered today but it apparently wont be
[SUPPORT] @800362 I'm sorry for the delay in your order. If you do not have your order by 21:00 on Thursday, please let us know!

-RD
[CUSTOMER] @AmazonHelp Its useless if it doesn't get here today. Its for a birthday present for someone who leaves today. I'll just be sending it back. Im really disappointed bt the service

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 215
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
So, @115821, what’s up?  Your shipping used to be reliable, now 2 of my last 3 orders have been late.

FULL CONVERSATION:
[CUSTOMER] So, @115821, what’s up?  Your shipping used to be reliable, now 2 of my last 3 orders have been late.
[SUPPORT] @738799 Please get in touch with our customer support via https://t.co/ohyvGrpvrY Our colleagues will have a look into this. ^SK

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 216
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp My package hasn't shipped and it's scheduled to arrive tomorrow, is there any way to check if it'll still be delivered on time?

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp My package hasn't shipped and it's scheduled to arrive tomorrow, is there any way to check if it'll still be delivered on time?
[SUPPORT] @518123 We strive to meet the date shown on your confirmation e-mail. We'll send an e-mail as soon as it ships! Keep us posted! ^BN

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 217
==========================================================================================
Conversation size : 11
Customer turns   : 6
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
@AmazonHelp why can I not apply this balance to my outstanding amount due all of the sudden? https://t.co/RqDdn4mTAs

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp why can I not apply this balance to my outstanding amount due all of the sudden? https://t.co/RqDdn4mTAs
[SUPPORT] @162563 Oh no! We'd like to help! Have you been able to clear your cache and cookies? Please keep us posted! ^NM
[CUSTOMER] @AmazonHelp That did nothing...chat support is trying to cancel my pre-order to apply $40 to the remaining balance..
[SUPPORT] @162563 Please keep us posted on the outcome of the chat support! We're always here to help. ^ML
[CUSTOMER] @AmazonHelp I brought it to a close as we were not getting my issue resolved
[CUSTOMER] @AmazonHelp I ended the chat for my sanity....any help would be appreciated
[SUPPORT] @162563 I'm sorry the chat wasn't helpful! Usually after the chat, there's an option to leave feedback. When these are completed (1/2)
[SUPPORT] @162563 they're sent to management to be reviewed. Have you tried using another browser? (2/2) ^EP
[CUSTOMER] @AmazonHelp I have tried Firefox/Chrome/Edge and mobile...all say error redeeming gift card....which I already did...just want to APPLY it!
[CUSTOMER] @AmazonHelp also yes...I left feedback and got a transcript of the chat
[SUPPORT] @162563 Oh no! Have you tried signing out of the account and then signing back in? Please be sure to let us know! We're here to help. ^TG

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 218
==========================================================================================
Conversation size : 6
Customer turns   : 3
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
Por favor @AmazonHelp contratad a una empresa normal no a incompetentes para los envíos 😑 llevo toda la mañana en casa por culpa de @137605 para nada. https://t.co/0rBWMVkB9y

FULL CONVERSATION:
[CUSTOMER] Por favor @AmazonHelp contratad a una empresa normal no a incompetentes para los envíos 😑 llevo toda la mañana en casa por culpa de @137605 para nada. https://t.co/0rBWMVkB9y
[SUPPORT] @137604 Hola, Gonzalo. Lamentamos mucho este inconveniente.¿Podrías indicarnos si este pedido que estás esperando es vendido y distribuido por Amazon o por un vendedor externo? ^ES
[CUSTOMER] @AmazonHelp Si, es de Amazon. Y con Amazon no tengo inconveniente pero @137605 no me lo entrego ni el día que tenía que hacerlo ni el siguiente en el horario que me indicaron por mensaje.
[SUPPORT] @137604 Gonzalo, por favor contacta con nuestros colegas de Servicio al Cliente para una atención personalizada y te puedan ayudar con la gestión.
Lo puedes hacer a través del siguiente enlace: https://t.co/OjvUxwnzPe ^LC
[CUSTOMER] @AmazonHelp Muchas gracias!
[SUPPORT] @137604 Fue un gusto, Gonzalo. Recuerda que estamos para ayudarte con cualquier consulta. ^AA

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 219
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp I am a prime member and I got echo delivered. Do I need extra subscription for amazon music? Pls guide.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp I am a prime member and I got echo delivered. Do I need extra subscription for amazon music? Pls guide.
[SUPPORT] @161904 Please contact us our support team here: https://t.co/vlvfJr4nN9 for information about this. ^KC

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 220
==========================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115830 what is the point in me paying for Prime when the item I’ve ordered isn’t going to be delivered when promised.

FULL CONVERSATION:
[CUSTOMER] @115830 what is the point in me paying for Prime when the item I’ve ordered isn’t going to be delivered when promised.
[SUPPORT] @435340 If your order missed the delivery date, we'd like to review your options &amp; document feedback: https://t.co/qy3J24VGxb ^AF
[CUSTOMER] @AmazonHelp Review my options? Like make sure it’s delivered tomorrow morning? Not ‘in a day or two ‘ https://t.co/vnkRYZvlus

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 221
==========================================================================================
Conversation size : 12
Customer turns   : 5
Support turns    : 7
Size bucket      : 9_plus_tweets

CUSTOMER:
Pathetic service-wrong product delivrd(Order-404-7604078-2941905).Return pickup pendng-5days, replacmnt order cancld automaticlly @115850

FULL CONVERSATION:
[CUSTOMER] Pathetic service-wrong product delivrd(Order-404-7604078-2941905).Return pickup pendng-5days, replacmnt order cancld automaticlly @115850
[SUPPORT] @214414 Sorry to know your item hasn't been picked up yet. We certainly did not expect this to happen. 1/3 ^PS
[SUPPORT] @214414 I'd like to assist you on this, please share your details on the link here: https://t.co/GIJyeYqKE0. I'll contact you soon. 2/3 ^PS
[SUPPORT] @214414 Please don't provide your order details, as we consider it to be personal information. Our page is visible to the public. 3/3 ^PS
[CUSTOMER] @AmazonHelp Please resolve my query fast
[SUPPORT] @214414 We've received your details and we'll get back to you soon. ^PS
[CUSTOMER] @115850 @115850 - My replacement product has not been delivered yet
[SUPPORT] @214414 I’d like to understand this better. Please fill this form: https://t.co/beaaDlIL5C and I’ll contact you at the earliest. ^RD
[CUSTOMER] @115850 Got to know that product is lying at Amazon Jhandewalan office and yet it has not been delivered yet..
[SUPPORT] @214414 We've received your details and shall reach out to you with an update soon. ^GS
[CUSTOMER] @115850 Finally received the product yesterday...thank you so much for your cooperation
[SUPPORT] @214414 We're glad to hear that. Thanks a bunch for keeping us posted. ^CB

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 222
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
✈Spigen's GLAS.tR Slim for iPhone X
😉Spigen India - https://t.co/QVRMa1KoFs
 @115850 - https://t.co/2AIDKIrBzd
#Spigen #iPhoneX #apple https://t.co/NRljQhQk3Y

FULL CONVERSATION:
[CUSTOMER] ✈Spigen's GLAS.tR Slim for iPhone X
😉Spigen India - https://t.co/QVRMa1KoFs
 @115850 - https://t.co/2AIDKIrBzd
#Spigen #iPhoneX #apple https://t.co/NRljQhQk3Y
[CUSTOMER] @279923 @115850 Nokia 8 ka launch karo boss.
[SUPPORT] @128484 You can find the buying options of Nokia 8 here: https://t.co/kdk9UYeTAy. ^SI
[CUSTOMER] @AmazonHelp Have the phone. Looking for spigen case 😸
[SUPPORT] @128484 Currently, the item isn't available. Kindly keep a check on our website. ^PS

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 223
==========================================================================================
Conversation size : 6
Customer turns   : 4
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp why you collaborate with @120543 they have pathetic service,  they didn't delivery my order
402-5325761-8409150.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp why you collaborate with @120543 they have pathetic service,  they didn't delivery my order
402-5325761-8409150.
[SUPPORT] @182223 Please don't provide your details, we consider it personal information. Our Twitter page is visible to public. 2/2 ^HD
[SUPPORT] @182223 I understand your concern, Anand. Please confirm if we've missed the estimated delivery date of your order? 1/2 ^HD
[CUSTOMER] @AmazonHelp you never understand my concern kutte mother fucker Asshole,  if you had i should have get my product delivered
[CUSTOMER] @AmazonHelp FUCK
[CUSTOMER] @AmazonHelp i will FUCK your whole Family.. Asshole

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 224
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
non aspetto il sonno tanto presto e quindi leggo 📕 #kindle #buonanotte

FULL CONVERSATION:
[CUSTOMER] non aspetto il sonno tanto presto e quindi leggo 📕 #kindle #buonanotte
[SUPPORT] @313797 Buona lettura! 🌜^MZ

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 225
==========================================================================================
Conversation size : 9
Customer turns   : 5
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
Yet again @115830 @AmazonHelp I'm skeptical my delivery will arrive today when it's not left Preston yet... https://t.co/AvAXsAs6iW

FULL CONVERSATION:
[CUSTOMER] Yet again @115830 @AmazonHelp I'm skeptical my delivery will arrive today when it's not left Preston yet... https://t.co/AvAXsAs6iW
[SUPPORT] @134539 Has any notification of a delay been advised? Keep us posted. We hope you get it today. ^PK
[CUSTOMER] @AmazonHelp Not yet, keeps happening recently
 Raised it with CS but only ever seen to get apologies, never any answers.
[SUPPORT] @134539 What was the original estimated delivery date provided in your order confirmation email?^PJ
[CUSTOMER] @AmazonHelp Today.
[SUPPORT] @134539 Sorry to hear that you've had issues recently. Keep an eye on your tracking: https://t.co/aaDyEz1VgE for updates and keep us posted.^TI
[CUSTOMER] @AmazonHelp Thanks that's so helpful telling me how to track my orders. Nothing moved since this morning. No way they're even attempting delivery today
[CUSTOMER] @115830 @AmazonHelp Hopefully I'll be proven wrong!
[SUPPORT] @134539 Couriers can deliver until 21:00 pm. Keep us posted about your delivery! We're here to help! ^KN

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 226
==========================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
@115821 please make my art tablet come faster thank u

FULL CONVERSATION:
[CUSTOMER] @115821 please make my art tablet come faster thank u
[SUPPORT] @213261 I'm sorry for this wait. What was the original delivery estimate given to you at Checkout? ^DO
[CUSTOMER] @AmazonHelp its supposed to come tomorrow. I just tweeted at you for the meme. love u babe 😩💦

CURRENT LABEL:
[ UNLABELED ]

==========================================================================================
EXAMPLE 227
==========================================================================================

In [180]:
start = 240
end = 269

batch = training_batch.iloc[start:end+1]

for i, row in batch.iterrows():
    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print("\nCUSTOMER:")
    print(row["first_customer_message"])
    print("\nFULL CONVERSATION:")
    print(row["conversation_text"])
    print("\nCURRENT LABEL:")
    print(f"[ {row['intent_label']} ]")
    print()

==========================================================================================
EXAMPLE 240
==========================================================================================
Conversation size : 97
Customer turns   : 55
Support turns    : 42
Size bucket      : 9_plus_tweets

CUSTOMER:
Series, películas, deportes en vivo y mucho más. ¡Entra y prueba GRATIS Amazon Prime Video!  https://t.co/XLc8UIQnmu

FULL CONVERSATION:
[CUSTOMER] Series, películas, deportes en vivo y mucho más. ¡Entra y prueba GRATIS Amazon Prime Video!  https://t.co/XLc8UIQnmu
[CUSTOMER] @123813 ¿Para cuándo en el Apple TV? 😫
[CUSTOMER] @123813 Pero seran para formato 4k?
[SUPPORT] @525278 Hola Edgar. Actualmente no contamos con esas informaciones. Te sugerimos estar al pendiente de nuestro sitio para novedades. ^HC
[SUPPORT] @527535 Hola Elizzandra, espero que estés bien. Para conocer los formatos de Prime Video, accede aquí: https://t.co/Z9TlpyAsBb. ^DA
[CUSTOMER] @AmazonHelp Oki oki gracias ☺👍
[SUPPORT] @527535 De nada, cualquier duda adicional, estamos aquí para ayudarte.😍 ^DA
[CUSTOMER] @123813 Además de la NFL, que otros "deportes en vivo" transmiten??
[CUSTOMER] @123813 Q precio tiene la renta mensual
[SUPPORT] @528153 Hola Juan, actualmente solo tenemos transmisión de Fútbol Americano en nuestro catálogo. ^MB
[SUPPORT] @528379 Hola Gustavo, por favor verifica las siguientes informaciones: https://t.co/vj27T3rn4i. ^MB
[CUSTOMER] @123813 Ya se encuentra la aplicación en smartv ?
[CUSTOMER] @123813 Si tengo mi cuenta amazon prime de USA. Tengo que volver a pagar una cuenta de AMAZON PRIME mx ?
[SUPPORT] @529267 Hola EDGAR, si está disponible, por favor checa las siguientes informaciones:https://t.co/m82qtRgWzm . ^MB
[SUPPORT] @530050 Hola, los servicios de Amazon Prime son independientes de cada sitio web, por lo que si deseas contar con Prime en Amazon (1/2)
[SUPPORT] @530050 (2/2) México es necesario adquirirlo en dicho sitio web directamente. ^KS
[CUSTOMER] @123813 Hola la tienen disponible en roku?
[SUPPORT] @563038 Hola, accede al siguiente enlace para ver los dispositivos disponibles para el servicio: https://t.co/hf6gUznDbj ^AV
[CUSTOMER] @123813 Cuáles son los deportes en vivo?
[SUPPORT] @571011 Hola, Rodkiedis, aquí: https://t.co/beDXGv6aPJ, podrás encontrar más información al respecto.  ^VM
[CUSTOMER] @123813 ¿Algún día tendrá compatibilidad con Chromecast?
[SUPPORT] @629285 Hola Abraham. En estos momentos no tenemos informaciones pero al haber novedades lo vamos a anunciar en nuestra página. ^JJ
[CUSTOMER] @AmazonHelp Gracias. Igual probaré el primer mes.
[SUPPORT] @629285 Que lo disfrutes mucho, seguro que te va a encantar. 😃🤝 ^JJ
[CUSTOMER] @123813 Tiene opción pra descargar contenido?
[SUPPORT] @638375 Hola R, actualmente el contenido disponible no se puede descargar, unicamente puedes visualizarlo al suscribirte . ^MB
[CUSTOMER] @AmazonHelp Pff bueno :/
[CUSTOMER] @123813 Bueno, con eso me conformo, pero ojalá ampliarán ese catálogo, gracias.
[SUPPORT] @528153 Hola Manuel. Muchas gracias por tu sugerencia, será tomada en cuenta. Cualquier novedad será notificada a través de nuestra página web.

Saludos,
^DB
[CUSTOMER] @123813 Cuando van a poner subtitulos en español para el anime?
[SUPPORT] @664779 Hola Jeff. E este enlace podrás ver instrucciones para modificar tus preferencias de idioma para audio y subtítulos: https://t.co/mJYMvHzbyN  ^JJ
[CUSTOMER] @123813 Hola, leí que la serie The Americans estaba en su plataforma y ya soy subscriptor pero no está la serie. Tienen información de si la tendrán o no? Por favor. Gracias!
[SUPPORT] @667051 Hola, de momento no contamos con el dato. Cualquier información o novedad al respecto se podrá ver directamente en el sitio web. ^KS
[CUSTOMER] @123813 Hola comparé vs el catálogo de prime en USA y nada que ver? Las películas están ya algo pasaditas de tiempo, para eso las veo en cualquier otra plataforma!
[SUPPORT] @693580 hola, te agradecemos por brindarnos esta sugerencia, te aseguramos que la compartiremos con el equipo encargado. Te recomiendo estar atento a nuestro catalogo en el sitio web, allí estaremos anunciando cualquier novedad. ^KA
[CUSTOMER] @123813 Cuanto cuesta? Yo soy cliente prime, Que tengo q hacer?
[SUPPORT] @697475 ¡Hola Eagon! Te cuento que al ser cliente prime ya cuentas con acceso a Prime Video. Te recomiendo ingresar a este enlace para más información 😃 https://t.co/TmMkr2Exbg ¡Saludos! ^LC
[CUSTOMER] @AmazonHelp Y ya incluye contenido? Todo se paga por separado? O como funciona?
[SUPPORT] @697475 Claro. Tendrás acceso a muchas películas y series de televisión además del futbol americano de la NFL los jueves en la noche. ^JJ
[CUSTOMER] @AmazonHelp @638375 Oye @116875 mejor yo les manejo la cuenta... Estas personas nomas no saben nada... Si se puede bajar contenido. Adjunto evidencia https://t.co/lBB0ywnetV
[CUSTOMER] @638376 @AmazonHelp @116875 Plop! Jajajaja wtf. Neta dejen de contratar a sus sobrinos como CM. Y contraten a @638376 jeje
[CUSTOMER] @123813 Para cuándo en Roku México?
[SUPPORT] @704098 Hola Hecktor, te recomendamos estar al tanto de nuestro sitio web y redes sociales ya que cualquier novedad sería anunciada en esos medios ^AV
[CUSTOMER] @638376 @AmazonHelp @638375 @116875 Jajajaja

Bien ahí Peter. Esa maldita mala maña de tener sobrinity manager.
[CUSTOMER] @123813 Hay temporadas de series que no están disponibles para mi localización o para Prime. Entonces, ¿cómo le hago para verlas?
[SUPPORT] @731030 Hola, Señor L. El contenido disponible en Prime Video varía según la región. Por favor, verifica esta información: https://t.co/PNCrAvHzr0 ^CR
[CUSTOMER] @AmazonHelp Si, me queda claro. Quiero saber en realidad, ¿como accedo al contenido que no está disponible en mi ubicación?
[CUSTOMER] @123813 Para que tanta publicidad, sino se puede usar? Se quedan con los datos de tu TC y despues inventan infinidad de pretextos para no dar el servicio.
[SUPPORT] @735322 ¡Hola Tony! Lamento mucho el inconveniente. ¿Podrías por favor explicarnos un poco más sobre el problema que estás teniendo con el servicio de PrimeVideo? Quedamos a la espera de tu respuesta para poderte ayudar un poco más.
^FQ
[CUSTOMER] @AmazonHelp Para ayudar? Me gan estado mandando correos hasta en chino! Pero no resuelven nada...
[SUPPORT] @735322 Entiendo Tony, en este caso te recomendamos ponerte en contacto con nuestro departamento de Servicio al Cliente, ingresando en el siguiente enlace: https://t.co/beR78zMMYB ^KA
[CUSTOMER] @123813 creo que es la mejor opcion hasta ahora en precio habra que checar el contenido voy a probarlo
[SUPPORT] @742449 ¡Hola! Cuando pruebes el servicio y veas el contenido, nos cuentas que te pareció.📺🍿^AA
[CUSTOMER] @731030 @AmazonHelp No puedes. A menos que metas algunos trucos informáticos....
[CUSTOMER] @123813 Cuanto cuesta
[SUPPORT] @754797 Hola, puedes encontrar toda la información sobre Amazon Prime en el siguiente enlace: https://t.co/WrRoIvCyCR. ^KS
[CUSTOMER] @123813 ¿Para cuándo habilitan Mr. Robot temporada 3?
[SUPPORT] @768315 Hola Leandro, en el momento no contamos con esta información, puedes estar pendiente de nuestra página web en ella estaremos publicando más novedades. ^DA
[CUSTOMER] @AmazonHelp @742449 Cómo lo instaló en la play station
[CUSTOMER] @123813 Para cuándo la app para Roku TV en México? No puedo ver su contenido a causa de eso 😢
[SUPPORT] @772031 Hola. Cualquier novedad sobre el servicio sería anunciada en el sitio web directamente, por lo que te sugiero estar al tanto. ^JQ
[CUSTOMER] @123813 ¿Cuando sale la App para AppleTV?, la anunciaron hace meses y nada, esta muy chafa ver las peliculas en el teléfono o la tableta y el AirPlay no jala bien
[SUPPORT] @781026 Hola Romeo. No tenemos informaciones al respecto pero al haberlas las vamos a anunciar en nuestra página y en nuestras redes sociales. ^JJ
[CUSTOMER] @123813 Cuando do estará lista la tercera temporada de MR ROBOT en México?
[SUPPORT] @782396 ¡Hola, Gustavo! De momento no contamos con información al respecto, te recomendamos estar al tanto de nuestro sitio web y redes sociales oficiales.🙂🙂 ^DS
[CUSTOMER] @123813 Se encuentra disponible con Android TV?
[SUPPORT] @270745 Hola, Hugo. Puedes verificar los dispositivos compatibles en este enlace: https://t.co/4hKt0TIHcq ^VL
[CUSTOMER] @AmazonHelp @781026 Menor vayan a dormirse, no tienen información de nada.
[CUSTOMER] @123813 tienen the IT crowd?
[SUPPORT] @144781 Jelipe, en el siguiente enlace: https://t.co/Op1MdPexzE, podrás verificar la programación y disponibilidad del contenido disponible actualmente en Prime Video. ^VM
[CUSTOMER] @123813 The big sick estará disponible en México?
[SUPPORT] @152941 Hola, Jonathan.

Todos los detalles de nuevas series y películas se anuncian en nuestra página oficial y en nuestras redes sociales. ¡Mantente atento!

Saludos,
- Emelina S.
[CUSTOMER] @123813 Hola ¿Sirve en Roku?
[SUPPORT] @156609 Hola, te agradecemos el interés en nuestros servicios. En el siguiente enlace podrás encontrar toda la información de los dispositivos compatibles:  https://t.co/Tsp6iWxLTD.  ^AA
[CUSTOMER] @123813 Sirve si tengo una cuenta de EEUU?
[SUPPORT] @172887 ¡Hola! Para utilizar el servicio de Prime Video en https://t.co/nUUp5MLhYl es necesario tener una cuenta en esa plataforma de Amazon así como la suscripción de Amazon Prime. Te adjunto los detalles para que puedas revisarlos: https://t.co/9WQIA0dw4F ^PC
[CUSTOMER] @123813 No está disponible en App Store, no la veo
[SUPPORT] @654433 Hola, te recomiendo que puedas ver la información del siguiente enlace: https://t.co/i3T84aXi8v ^KA
[CUSTOMER] @123813 Cuando estará disponible, en México, la 3a temporada de Mozart in the Jungle? Gracias
[SUPPORT] @750642 ¡Hola Gabriel! Cualquier novedad al respecto la estaremos anunciando a través de nuestro sitio web y redes sociales oficiales. Te invitamos a mantenerte al tanto y seguir disfrutando del contenido de Prime Video. ^MZ
[CUSTOMER] @123813 Pero vale 450 al mes!!!
[SUPPORT] @755150 Hola, te comentamos que Prime Video es uno de los beneficios de la suscripción Prime, si tienes tu suscripción activa no tendrás ningún costo adicional por el servicio de Prime Video. Puedes ver más información aquí: https://t.co/zn2u5dWwfA. ^MZ
[CUSTOMER] @AmazonHelp Por eso, Prime cuesta 450 mensuales
[CUSTOMER] @755150 @AmazonHelp Son 450 anuales, yo lo tengo
[CUSTOMER] @755151 @AmazonHelp de verdad? yo creí que mensuales, gracias
[CUSTOMER] @123813 Ya contrate el año. Pero su aplicacion para smarTV Samsung se atora a cada rato y tengo que reiniciarla al terminar los capitulos de mi serie. Y aun no tienen cannal en Rocku Mexico. Ojalá mejoren esos aspectos
[SUPPORT] @401902 Hola Aldo. Esperamos que te encuentres muy bien. Gracias informarnos lo sucedido. ¿Ya lo has reportado con Soporte al Cliente?  En caso de que no sea así, puedes hacerlo acá: https://t.co/XrMDSgEmbN

^DB
[CUSTOMER] @755150 @AmazonHelp Son 450 el primer año, el segundo sube a 800 al año. Ademas te pasan los jueves los juegos de la NFL en vivo.
[CUSTOMER] @123813 Para cuando la tercera temporada de Mozart in the jungle?
[SUPPORT] @809675 Hola, Gabriel. Por el momento, no tenemos esa información. Sin embargo, cualquier novedad será anunciada directamente en nuestro sitio y redes sociales. ¡Sigue pendiente! ^CR
[CUSTOMER] @AmazonHelp Si es serie original, debería ser lanzamiento mundial
[CUSTOMER] @123813 Por que no está disponible la nueva temporada de Mr. Robot?? https://t.co/Rg6BfYwc8Z
[SUPPORT] @816937 ¡Hola Anibal! Gracias por tu interés en Prime Video. Actualmente no contamos con esta información, tan pronto se tengan novedades se estaría actualizando el sitio web, por favor mantente al tanto. ¡Saludos! ^ PC
[CUSTOMER] @123813 Sera verdad ?
[SUPPORT] @817328 ¡Hola! ¿En qué podemos ayudarte?😃 ^ES
[CUSTOMER] @123813 La temporada 3 de Mr Robot no está disponible en México, la van a liberar en algún momento.
[SUPPORT] @222530 ¡Hola Luis Alejandro! Actualmente no contamos con esa información, una vez que tengamos las novedades se estaría actualizando el sitio web para informar a todos los clientes, te recomendamos estar atentos. ¡Saludos! ^PC

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 241
==========================================================================================
Conversation size : 8
Customer turns   : 4
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp Hi! I returned 3 items (in the same package, all still new with tags) &amp; I only got refunded for 2. Please help? Thanks.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp Hi! I returned 3 items (in the same package, all still new with tags) &amp; I only got refunded for 2. Please help? Thanks.
[SUPPORT] @475465 I'm sorry for any trouble, Mindy! Did the third item have its own return label? You can check here: https://t.co/Y5jpI9gRhE ^BL
[CUSTOMER] @AmazonHelp It did, but I only had 1 bag to return things in. I put both of the bar code pages in the envelope. The link says it’s awaiting return.
[SUPPORT] @475465 It may be because that label wasn't sent. We'd love to help! Please contact us via phone/chat here: https://t.co/hApLpMlfHN ^AJ
[CUSTOMER] @AmazonHelp That link doesn’t seem to be working on my iPad? It just takes me to the return center. Thanks.
[SUPPORT] @475465 Hm... That's odd! You can reach out to us by phone here: https://t.co/RsDl7aOroi Let us know if this helps! ^ZW
[CUSTOMER] @AmazonHelp That worked! Thanks so much.
[SUPPORT] @475465 You're very welcome! 😊 ^LB

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 242
==========================================================================================
Conversation size : 6
Customer turns   : 3
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
.@115821 il va vraiment falloir que tu mettes la pression à @132988. Je suis CHEZ MOI ... mon colislivré en POINT RELAIS #WTF 🤔

FULL CONVERSATION:
[CUSTOMER] .@115821 il va vraiment falloir que tu mettes la pression à @132988. Je suis CHEZ MOI ... mon colislivré en POINT RELAIS #WTF 🤔
[SUPPORT] @385938 Bonjour, je suis désolée pour cela😓
L'avez-vous signalé à notre SAV afin qu'il prenne les mesures nécessaires?^FT
[CUSTOMER] @AmazonHelp Non pas encore, j'ai commencé par vérifié que je n'avais pas fait d'erreur dans la commande #tempsperdu. La marche à suivre svp = ?
[SUPPORT] @385938 Afin que notre service client puisse vous apporter de l'aide, je vous propose de les contacter via: https://t.co/qzuu0dgDXz. ^ASZ
[CUSTOMER] @AmazonHelp Merci à vous et à @115821 ... bonne journée ;-)
[SUPPORT] @385938 Bonne journée :)

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 243
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp @115851  Broken product delivered. https://t.co/a5Bnt3B2v7

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp @115851  Broken product delivered. https://t.co/a5Bnt3B2v7
[SUPPORT] @318693 I'm sorry that you've received the product in broken condition. We'd like to look into this. Kindly reach out to our support team here: https://t.co/vlvfJr4nN9 and we'll fix it for you.^HS

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 244
==========================================================================================
Conversation size : 8
Customer turns   : 4
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp Hello. I'm trying to log on to Amazon in my library but can't. "The owner of https://t.co/vWVKORx4Y8 has configured their website improperly..." I wanted to cancel Prime + Kindle subscriptions. Can you help?

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp Hello. I'm trying to log on to Amazon in my library but can't. "The owner of https://t.co/vWVKORx4Y8 has configured their website improperly..." I wanted to cancel Prime + Kindle subscriptions. Can you help?
[SUPPORT] @811832 Sorry to hear about the issue with the Libraries computer. We're unable to access your account via twitter. Are you able to access the cancel subscription link here: http:https://t.co/a4Yc9lKczA? Can you check another browser perhaps? ^MI
[CUSTOMER] @AmazonHelp I can't. Have tried in Chrome as well. I was hoping to get the cancellations in before next payments went out. I like the services. I just have a few minor debts mounting up that need clearing. Will have to find a friend to help me then.
[SUPPORT] @811832 Have you tried contacting us over the telephone? One of our agents can cancel your Prime + Kindle subscriptions if you would like. Feel free to contact us here: https://t.co/JzP7hlA23B Thanks for reaching out! ^VR
[CUSTOMER] @AmazonHelp No Amazon links work at all. Can't access any of it. I will have to ask a friend to use their phone or internet. Thanks for your help.
[SUPPORT] @811832 No worries at all. You should be able to log in from a different device and than you can either cancel it from your own account or get in touch with us.^MA
[CUSTOMER] @AmazonHelp Also going to try an internet cafe on the way home. It's something to do with this library I'm sure because I can't even use Google! Thanks again.
[SUPPORT] @811832 No worries at all Russell!^MA

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 245
==========================================================================================
Conversation size : 3
Customer turns   : 2
Support turns    : 1
Size bucket      : 3_to_4_tweets

CUSTOMER:
One more reason to cancel my @115821  prime account, I got yelled at by the rep when I called to cancel my 7th late package, which is lost

FULL CONVERSATION:
[CUSTOMER] One more reason to cancel my @115821  prime account, I got yelled at by the rep when I called to cancel my 7th late package, which is lost
[SUPPORT] @167110 I'm so sorry! Please submit feedback on this using the survey link at the bottom of the e-mail you should receive. ^DO
[CUSTOMER] @AmazonHelp Why? No one really cares. Otherwise things would get better instead of worse

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 246
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
Service u receive as an @115821 Prime customer is awful. Bloke chucked my new fire alarm over the fence. Didn’t knock, saw me &amp; drove off! https://t.co/ISJBHUhx7R

FULL CONVERSATION:
[CUSTOMER] Service u receive as an @115821 Prime customer is awful. Bloke chucked my new fire alarm over the fence. Didn’t knock, saw me &amp; drove off! https://t.co/ISJBHUhx7R
[CUSTOMER] @314212 @115821 @AmazonHelp @115830 I got a Hermes parcel in the same manner a week or so back. Luckily a soft item but still; if it was into a puddle I wouldn't have been so happy
[SUPPORT] @314212 Sorry to hear about this. Is the item damaged? ^MI
[SUPPORT] @618726 Hi, I'm sorry about the delivery issue. Have you had a chance to contact us: https://t.co/JzP7hlA23B about this?^PJ
[CUSTOMER] @AmazonHelp @314212 I think this is for you 😊

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 247
==========================================================================================
Conversation size : 8
Customer turns   : 4
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:

In [181]:
start = 270
end = 299

batch = training_batch.iloc[start:end+1]

for i, row in batch.iterrows():
    print("=" * 90)
    print(f"EXAMPLE {i}")
    print("=" * 90)
    print(f"Conversation size : {row['conversation_size']}")
    print(f"Customer turns   : {row['customer_turns']}")
    print(f"Support turns    : {row['support_turns']}")
    print(f"Size bucket      : {row['size_bucket']}")
    print("\nCUSTOMER:")
    print(row["first_customer_message"])
    print("\nFULL CONVERSATION:")
    print(row["conversation_text"])
    print("\nCURRENT LABEL:")
    print(f"[ {row['intent_label']} ]")
    print()

==========================================================================================
EXAMPLE 270
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
①Amazonで商品を注文する

②コンビニ払いで支払う

③支払い完了のメールが来る

④同じ注文番号で別の支払い番号が来る

⑤③に対しての商品遅延のメールが来る

⑥④の期限が過ぎたからと注文自体が無かったことになったとメールが来た

って状況なんだがなんだこれ

FULL CONVERSATION:
[CUSTOMER] ①Amazonで商品を注文する

②コンビニ払いで支払う

③支払い完了のメールが来る

④同じ注文番号で別の支払い番号が来る

⑤③に対しての商品遅延のメールが来る

⑥④の期限が過ぎたからと注文自体が無かったことになったとメールが来た

って状況なんだがなんだこれ
[SUPPORT] @688280 ご不便をお掛けしております。該当の注文など詳細を確認した上でご案内させていただきますので、恐れ入りますが、リンクよりカスタマーサービスにお問い合わせください。https://t.co/J6YEizo6qC TN

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 271
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Fake product received from Amazon #bose speaker#@115851 #@115850 #@AmazonHelp # #@118342#help#Worst customer Experience #@115850 supporting fake sellers #@119341#404-2877796-4009925 OD I'd #Cheating Poor Customer #Stop buying from Amazon # https://t.co/yhubx3DpVj

FULL CONVERSATION:
[CUSTOMER] Fake product received from Amazon #bose speaker#@115851 #@115850 #@AmazonHelp # #@118342#help#Worst customer Experience #@115850 supporting fake sellers #@119341#404-2877796-4009925 OD I'd #Cheating Poor Customer #Stop buying from Amazon # https://t.co/yhubx3DpVj
[SUPPORT] @131812 We would like to help you. Please share your details with us here: https://t.co/GIJyeYqKE0. We'll get in touch shortly.
Please don't provide your order details as we consider it personal information. Our twitter page is visible to public.^CB

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 272
==========================================================================================
Conversation size : 6
Customer turns   : 4
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
What would we do without @115821 and @127161? Get stuff delivered when they said I expect

FULL CONVERSATION:
[CUSTOMER] What would we do without @115821 and @127161? Get stuff delivered when they said I expect
[SUPPORT] @313184 I'm sorry for the delay! Have we sent an e-mail with an explanation? ^TR
[CUSTOMER] @AmazonHelp I didn't buy the thing - was to be delivered to me. You said 13 Oct - Yodel have tried 3 times already, so now won't deliver again (cont...)
[CUSTOMER] @AmazonHelp (cont...) was a present and now everyone's upset cos you and @127161 didn't do what you said you would.
[SUPPORT] @313184 I'm sorry you haven't received it. If this was a gift, please ask the purchaser to contact us so we can see look into options. ^MB
[CUSTOMER] @AmazonHelp I think the buyer has cancelled the order now due to all the upset. Feel badly let down by you and @127161

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 273
==========================================================================================
Conversation size : 5
Customer turns   : 3
Support turns    : 2
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115821 Just wanted to say thanks for the packaging that blew up in my wife's face....

FULL CONVERSATION:
[CUSTOMER] @115821 Just wanted to say thanks for the packaging that blew up in my wife's face....
[SUPPORT] @759507 Without giving account specific details, please provide more information on what happened? ^JF
[CUSTOMER] @AmazonHelp My wife opened a toy wrapped in a pillow-like air bag. It blew open and the toy hit my wife in the face. She's bleeding from the lip. It could have knocked her teeth out. You need to print clear warnings on those packages. If there is   air pressure, someone could (did) get hurt.
[SUPPORT] @759507 Oh no! We'd like to make sure your experience is escalated. When you have the time, please send us the order details here: https://t.co/8zEMG9heDt ^NN
[CUSTOMER] @AmazonHelp My wife is still waiting on that phone call..

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 274
==========================================================================================
Conversation size : 11
Customer turns   : 6
Support turns    : 5
Size bucket      : 9_plus_tweets

CUSTOMER:
I don't understand why I have to pay for return international postage because @115821 sent me a broken DVD? (@AmazonHelp)

FULL CONVERSATION:
[CUSTOMER] I don't understand why I have to pay for return international postage because @115821 sent me a broken DVD? (@AmazonHelp)
[SUPPORT] @143375 I'm sorry the DVD arrived broken! Did you set up the return online? If so, what was the selected reason for return? ^EP
[CUSTOMER] @AmazonHelp It's still in its plastic, but the disc is loose and there is rattling parts, it has been squashed or broken during transit or packing. I didn't click return on the website because it will cost me more than the original item and postage combined to return the broken DVD.
[CUSTOMER] @AmazonHelp the only other option I have is a chargeback or dispute with my bank. I didn't realise Amazon makes the customer pay twice when it's not the customer's fault. As it is, the dvd was sent in an envelope with minimal padding :/
[SUPPORT] @143375 Was this item shipped and sold by Amazon or a Marketplace seller? ^DO
[CUSTOMER] @AmazonHelp Amazon (#113-6452827-7987464)
[SUPPORT] @143375 I'm sorry, we are unable to view account or order information via Twitter. Can you tell us who it was shipped and sold by finding that info in the Your Orders page: https://t.co/Y5jpI9gRhE ^DO
[CUSTOMER] @AmazonHelp "Sold by: Amazon Export Sales LLC. Delivered today. Your package was delivered. It was handed directly to a resident. Condition: New."
[SUPPORT] @143375 Was the order shipped directly by the seller, 'Amazon Export Sales LLC' or was it shipped by https://t.co/nUUp5MLhYl? ^LR
[CUSTOMER] @AmazonHelp I don't know where to find this information on the Orders page. https://t.co/vWVXfilM5a
[SUPPORT] @143375 We'd like to look into this with you to see what options are available. Please reach out to us by chat here: https://t.co/EKXRLsnxJu ^JN

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 275
==========================================================================================
Conversation size : 8
Customer turns   : 5
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
@AmazonHelp 5th order in a row for the delivery to be delayed.  Needless to say I am getting VERY frustrated, especially considering I live less than 10 miles from the distribution center that they are being shipped from.  And it is not an inventory problem, order ships and then.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp 5th order in a row for the delivery to be delayed.  Needless to say I am getting VERY frustrated, especially considering I live less than 10 miles from the distribution center that they are being shipped from.  And it is not an inventory problem, order ships and then.
[CUSTOMER] @AmazonHelp sits at the distribution center for over 24 hours.  What is going on?!?
[SUPPORT] @709078 Have you raised this with us directly before, Matt? What were you advised by the associate you spoke with?^SM
[SUPPORT] @709078 Hi Matt, were you emailed to advise why there was a delay? ^HS
[CUSTOMER] @AmazonHelp I was not, only found out by looking at the order information through the app.  When I brought it up with another agent after the 3rd order delay, they didn't have any idea for the delays.
[CUSTOMER] @AmazonHelp In fact, the app makes it seem like you guys aren't even sure where my packages are.  I am greeted with the following "We're sorry your package is late             We're working to get your package back on track."
[SUPPORT] @709078 I'm sorry we were limited to details when you had contacted us. Did we ask you to wait longer for its arrival? That sounds like a transportation delay but we still have the package and it's still on the way. ^MG
[CUSTOMER] @AmazonHelp For 5 orders in a row?  And I shouldn't have to wait longer for my order, I was guaranteed a delivery date when I placed the order.  I certainly understand things happen but when it happens 5 times in a row, then there is something wrong with your process.

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 276
==========================================================================================
Conversation size : 6
Customer turns   : 3
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115821 My envelop with my order from Mvek Group came empty. Who should I contact?

FULL CONVERSATION:
[CUSTOMER] @115821 My envelop with my order from Mvek Group came empty. Who should I contact?
[SUPPORT] @300927 I'm sorry your order was empty. Was the item sold by Amazon or a third-party seller? ^VS
[CUSTOMER] @AmazonHelp Sight reads sold by Mvek Group and Fulfilled by Amazon.
[SUPPORT] @300927 Thanks for confirming! You can see available refund/replacement options here: https://t.co/Objdqrl5tq. Please keep us posted! ^SD
[CUSTOMER] @AmazonHelp Thank you.
[SUPPORT] @300927 Our pleasure! We're here for you, so please let us know if you still need us for anything at all! ^KN

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 277
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@AmazonHelp amigos les acabo de enviar un mensaje 😏

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp amigos les acabo de enviar un mensaje 😏
[SUPPORT] @576406 Hemos respondido tu DM. ^VM

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 278
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
Me pregunto si el Black Friday también estará en @116875

FULL CONVERSATION:
[CUSTOMER] Me pregunto si el Black Friday también estará en @116875
[SUPPORT] @197683 Hola Eduardo. Por el momento no tenemos información al respecto. Cualquier novedad será anunciada en nuestra página web. ¡Mantente atento! 👀😀
Saludos,
^DB

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 279
==========================================================================================
Conversation size : 11
Customer turns   : 4
Support turns    : 7
Size bucket      : 9_plus_tweets

CUSTOMER:
@AmazonHelp I am shocked and annoyed with the worst shopping experience. Order ID-402-5532671-1263504 nt delivered till now.

FULL CONVERSATION:
[CUSTOMER] @AmazonHelp I am shocked and annoyed with the worst shopping experience. Order ID-402-5532671-1263504 nt delivered till now.
[SUPPORT] @506435 Also, don’t provide your order details as its personal information. Our Twitter page is visible to public. 2/2^RS
[SUPPORT] @506435 Apologies for the delay with your order. Kindly fill this form: https://t.co/beaaDm0muc &amp; we'll check on it for you. 1/2^RS
[CUSTOMER] @AmazonHelp Honestly U R least bothered about getting the shipment delivered. Everytime I call custcare, no updates. #poorservice @AmazonHelp @115850
[SUPPORT] @506435 I understand how tiring it is to wait for a package. Request you to fill the details 1/2 ^SK
[SUPPORT] @506435 using the link provided in the previous post and we'll get this sorted for you. 2/2 ^SK
[CUSTOMER] @AmazonHelp Already done. And fyi, the packet is delayed for over 5 days of the promised time. What is the advantage of taking prime membership
[SUPPORT] @506435 here: https://t.co/hcuYSAImjs so that we can look into it. (2/2) ^MO
[SUPPORT] @506435 We haven't received your details yet. Request you to fill the form using the link provided earlier (1/2) ^MO
[CUSTOMER] @AmazonHelp Pls can you check now?
[SUPPORT] @506435 If you have filled the form, please be assured our team will get back to you at the earliest. ^PB

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 280
==========================================================================================
Conversation size : 9
Customer turns   : 6
Support turns    : 3
Size bucket      : 9_plus_tweets

CUSTOMER:
📺 Get $15 off Fire TV Stick with Alexa Voice Remote for a limited time. https://t.co/tIeSOkkqmq 📺 https://t.co/XeEilCvns9

FULL CONVERSATION:
[CUSTOMER] 📺 Get $15 off Fire TV Stick with Alexa Voice Remote for a limited time. https://t.co/tIeSOkkqmq 📺 https://t.co/XeEilCvns9
[CUSTOMER] @116439 What about France 😕
[SUPPORT] @766662 I'm sorry we don't have any insight. Keep an eye on the website and the item for any updates. ^EP
[CUSTOMER] @AmazonHelp Thanx still at 39.90€ on fr webside 😌
[CUSTOMER] @116439 bought one but why sling tv unavailable at appstore?
[SUPPORT] @808787 Hey, Nirupam please check here for Sling TV information: https://t.co/syesQV6eMQ
^MO
[CUSTOMER] @AmazonHelp Got it but when I checked with them they said Amazon fire stick dept should clarify this. why this passing the buck? have Sling stopped making app for A Fire os? please confirm.
[SUPPORT] @808787 We want to make sure your question is answered. Please reach out to us for live support by phone or chat from here:  https://t.co/hApLpMlfHN ^CH
[CUSTOMER] @AmazonHelp just contacted amazon support and they confirmed that sling has been deregistered from app store. a simple acceptance would have sufficed from either side.

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 281
==========================================================================================
Conversation size : 2
Customer turns   : 1
Support turns    : 1
Size bucket      : 2_tweets

CUSTOMER:
@116928 os pedí el jueves una funda para móvil y hoy me ha llegado pero el contenido del paquete no es correcto

FULL CONVERSATION:
[CUSTOMER] @116928 os pedí el jueves una funda para móvil y hoy me ha llegado pero el contenido del paquete no es correcto
[SUPPORT] @290365 Hola, lamentamos el inconveniente. Puedes seguir estas instrucciones para devolver el producto: https://t.co/MNBNv13sTa ^AV

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 282
==========================================================================================
Conversation size : 7
Customer turns   : 3
Support turns    : 4
Size bucket      : 5_to_8_tweets

CUSTOMER:
@115825 wann wird die Serie Empire wieder für Prime verfügbar sein? Ich war genau mittendrin.

FULL CONVERSATION:
[CUSTOMER] @115825 wann wird die Serie Empire wieder für Prime verfügbar sein? Ich war genau mittendrin.
[SUPPORT] @720723 2/2 "Serien nur noch begrenzte Zeit bei Prime": https://t.co/NmpgdVGto4 ^AS
[SUPPORT] @720723 1/2 Dazu haben wir leider keine Infos 😐 Damit dir das nicht nochmal passiert, wirf ab und an einen Blick in unsere Kategorie
[CUSTOMER] @AmazonHelp Ja das mache ich nur schaffe ich nicht 10 folgen in 2 Tagen
[CUSTOMER] @AmazonHelp Und wissen wie ob die Sendung True Detective irgend wann bei Prime rauskommt.
[SUPPORT] @720723 Wer braucht schon schlaf ;) ^AN
[SUPPORT] @720723 Leider haben wir auch da keine Infos. Ich setzte aber beides gerne auf unsere Wunschliste. ^AN

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 283
==========================================================================================
Conversation size : 10
Customer turns   : 6
Support turns    : 4
Size bucket      : 9_plus_tweets

CUSTOMER:
@116928 Por 2a vez me cerraron la cuenta. Tras cambiar la contraseña no me deja entrar. La verdad que me tienen un poco desesperado.

FULL CONVERSATION:
[CUSTOMER] @116928 Por 2a vez me cerraron la cuenta. Tras cambiar la contraseña no me deja entrar. La verdad que me tienen un poco desesperado.
[SUPPORT] @172750 Hola Michael, sentimos lo ocurrido. ¿Has recibido un correo indicándote los pasos para recuperar tu cuenta? ^DA
[CUSTOMER] @AmazonHelp Si. Los recibi. Segui los pasos, reestablece mi contraseña y no me deja entrar. Me parece fatal que pase esto 2 veces.
[SUPPORT] @172750 ¿Qué error te presenta al intentar accesar tu cuenta con la nueva contraseña? ^DA
[CUSTOMER] @AmazonHelp Me dice que la contraseña es incorrecta. Estoy 100% seguro que estoy pongo la contraseña correcta. Ya lo cambié 3x. Mismo error cada vez.
[SUPPORT] @172750 Michael, entra en contacto con Soporte al Cliente para que puedan verificar tu cuenta. por aquí: https://t.co/ppG57pGsMq. ^DA
[CUSTOMER] @AmazonHelp No puedo contactar con el chat ahi, solo email. Cuanto van a tardar en contestar? Es urgente ya que hice 2 pedidos que se cancelaron.
[SUPPORT] @172750 Michael, la respuesta puede demorar hasta 12 horas. En el enlace también verás el # de teléfono al que puedes llamar. ^LG
[CUSTOMER] @AmazonHelp Por favor, me pueden contestar lo antes posible. Es muy urgente. No puedo estar esperando 12 horas por culpa de Amazon.
[CUSTOMER] @AmazonHelp Hola?

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 284
==========================================================================================
Conversation size : 6
Customer turns   : 3
Support turns    : 3
Size bucket      : 5_to_8_tweets

CUSTOMER:
#AmazonIndia @115821 @115850 @AmazonHelp pathetic reply to the issue of Non delivery. Kindly provide me details of person who delivered https://t.co/EKsLKWab7M

FULL CONVERSATION:
[CUSTOMER] #AmazonIndia @115821 @115850 @AmazonHelp pathetic reply to the issue of Non delivery. Kindly provide me details of person who delivered https://t.co/EKsLKWab7M
[SUPPORT] @186222 I'd like to help you in getting this issue resolved. Please share your details here: https://t.co/GIJyeYqKE0 and we'll help. ^ZH
[SUPPORT] @186222 Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^ZH
[CUSTOMER] @AmazonHelp Are you going to help???
[CUSTOMER] @AmazonHelp Kindly give me details of delivery person
[SUPPORT] @186222 Please share your details in the link given earlier by me and we'll help you in resolving your issue. ^ZH

CURRENT LABEL:
[ nan ]

==========================================================================================
EXAMPLE 285
==========================================================================================
Conversation size : 55
Customer turns   : 27
Support turns    : 28
Size bucket      : 9_plus_tweets

CUSTOMER:
@115850 The delivery boy took 7parcels and said he delivered to my brother, and none in my family have taken those parcel.The guy is lying

FULL CONVERSATION:
[CUSTOMER] @115850 The delivery boy took 7parcels and said he delivered to my brother, and none in my family have taken those parcel.The guy is lying
[SUPPORT] @338251 Sorry for the trouble with the delivery of your order, Rohit. We'd like to look into this.  (1/2) ^HD
[SUPPORT] @338251 Please report this to our support team here: https://t.co/TdDksLo6Mf and we'll look into this. (2/2) ^HD
[CUSTOMER] @AmazonHelp I have already reported and been discussing with your customer care.. Its really frustrating do all UNNECESSARY this follow up

In [182]:
import pandas as pd

path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv"

df = pd.read_csv(path)

print(df.columns.tolist())
print(df.shape)
print(df[["conversation_id", "intent_label"]].head(10))

['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'split', 'is_taxonomy_audit', 'intent_label', 'annotation_notes', 'annotator', 'annotation_status']
(300, 20)
   conversation_id  intent_label
0           373303           NaN
1           282739           NaN
2          2292312           NaN
3           570075           NaN
4          1427974           NaN
5          1717565           NaN
6          2132842           NaN
7          2289374           NaN
8          1514342           NaN
9            42989           NaN

In [183]:
df.loc[0, "intent_label"] = "DELIVERY_DELAY"
df.loc[1, "intent_label"] = "PRODUCT_PROBLEM"
df.loc[2, "intent_label"] = "DELIVERY_DELAY"

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3755786279.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'DELIVERY_DELAY' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "intent_label"] = "DELIVERY_DELAY"

In [184]:
df.to_csv(path, index=False)

In [185]:
path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv"

df = pd.read_csv(path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nExisting intent labels:")
print(df["intent_label"].value_counts(dropna=False))

print("\nUnlabeled row indexes:")
print(df.index[df["intent_label"].isna()].tolist())

Shape: (300, 20)

Columns:
['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'split', 'is_taxonomy_audit', 'intent_label', 'annotation_notes', 'annotator', 'annotation_status']

Existing intent labels:
intent_label
NaN                297
DELIVERY_DELAY       2
PRODUCT_PROBLEM      1
Name: count, dtype: int64

Unlabeled row indexes:
[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299]

In [186]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)

In [187]:
training_df = pd.read_csv(
    PROJECT_ROOT / "data" / "processed" / "amazonhelp_intent_training_batch_01.csv"
)

print("Shape:", training_df.shape)
print("Missing labels:", training_df["intent_label"].isna().sum())
print("Unique conversations:", training_df["conversation_id"].nunique())

training_df.head()

Shape: (300, 20)
Missing labels: 297
Unique conversations: 300

,conversation_id,first_customer_message,last_customer_message,first_support_message,last_support_message,conversation_text,customer_turns,support_turns,conversation_size,start_time,end_time,duration_minutes,support_account,size_bucket,split,is_taxonomy_audit,intent_label,annotation_notes,annotator,annotation_status
0,373303,"I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.",@AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.,@204457 We never want to let our customers down! Is there an issue with one of your current orders: https://t.co/3kQwjObgTc? ^GM,"@204457 Oh no, Bree! I'm sorry for the poor experience. When you spoke with us previously, what insights or alternatives did we provide?^TG","[CUSTOMER] I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.\n[SUPPORT] @204457 We never want to let our customers down! Is there an issue with one of your current orders: https://t.co/3kQwjObgTc? ^GM\n[CUSTOMER] @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +\n[CUSTOMER] @AmazonHelp + when I ordered on...",3,2,5,2017-10-08 23:52:49+00:00,2017-10-09 00:28:31+00:00,35.700000,AmazonHelp,5_to_8_tweets,train,False,DELIVERY_DELAY,NaN,NaN,UNLABELED
1,282739,"@115821 Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]","@AmazonHelp Thanks Amazon for helping me, providing me my preferred resolution. @115821 @115850 @123644 @4030 @118702 @4167 @4110 @4168 @115937 @135980 @61230 @120697 @120033 @144769 @29568 @136912 @61231 @120319",@183363 it to be personal information. Our Twitter page is public.​ 3/3^EM,@183363 We're glad you like our services. Happy shopping :) ^OS,"[CUSTOMER] @115821 Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]\n[SUPPORT] @183363 it to be personal information. Our Twitter page is public.​ 3/3^EM\n[SUPPORT] @183363 and we'll see what best can be done to help you. Also, please don't provide your order details, as we consider 2/3^EM\n[SUPPORT] @183363 I understand y...",59,41,100,2017-10-06 12:11:43+00:00,2017-10-21 11:46:00+00:00,21574.283333,AmazonHelp,9_plus_tweets,train,False,PRODUCT_PROBLEM,NaN,NaN,UNLABELED
2,2292312,@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy,@AmazonHelp No it's the stupid post office that always messes up my deliveries,@569445 Two-Day shipping refers to the transit time in business days once an item has shipped. Some items may take additional time to prepare. Any prep time is included in the delivery estimate. More info: https://t.co/AbVhK00M4e ^EP,@569445 We can make sure this is reported to our Transportation team. When you have time send us the details here: https://t.co/hApLpMlfHN ^EP,[CUSTOMER] @AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy\n[SUPPORT] @569445 Two-Day shipping refers to the transit time in business days once an item has shipped. Some items may take additional time to prepare. Any prep time is included in the delivery estimate. More info: https://t.co/AbVhK00M4e ^EP\n[CUSTOMER] @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELI...,3,3,6,2017-11-11 22:00:01+00:00,2017-11-11 22:46:30+00:00,46.483333,AmazonHelp,5_to_8_tweets,train,False,DELIVERY_DELAY,NaN,NaN,UNLABELED
3,570075,Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^),Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^),@253812 こちらですね・・・？( *• ̀ω•́ )b \nhttps://t.co/Zj70OB4ODe SK,@253812 こちらですね・・・？( *• ̀ω•́ )b \nhttps://t.co/Zj70OB4ODe SK,[CUSTOMER] Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)\n[SUPPORT] @253812 こちらですね・・・？( *• ̀ω•́ )b \nhttps://t.co/Zj70OB4ODe SK,1,1,2,2017-12-03 03:24:29+00:00,2017-12-03 03:32:28+00:00,7.983333,AmazonHelp,2_tweets,train,False,NaN,NaN,NaN,UNLABELED
4,1427974,@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt,@AmazonHelp Done pls check,"@451696 I'm sorry about the issue you have with the refunds, fill this form: https://t.co/beaaDm0muc &amp; I’ll get it checked for you. ^SY",@451696 We'd like look into this for you. Please share your details here : https://t.co/GIJyeYqKE0 and we'll connect with you soon. ^AS,"[CUSTOMER] @115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt\n[SUPPORT] @451696 I'm sorry about the issue you have with the refunds, fill this form: https://t.co/beaaDm0muc &amp; I’ll get it checked for you. ^SY\n[CUSTOMER] @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check\n[SUPPORT] @451696 Thank you for sharing your details. We'll work on it and reach out to you soon. ^AP\n[CU...",8,5,13,2017-11-06 07:09:16+00:00,2017-11-06 16:39:46+00:00,570.500000,AmazonHelp,9_plus_tweets,train,False,NaN,NaN,NaN,UNLABELED

In [188]:
labeled_mask = (
    training_df["intent_label"].notna() &
    training_df["intent_label"].astype(str).str.strip().ne("") &
    training_df["intent_label"].astype(str).str.upper().ne("UNLABELED")
)

labeled_df = training_df.loc[labeled_mask].copy()

X = labeled_df["conversation_text"].fillna("").astype(str)
y = labeled_df["intent_label"].astype(str).str.strip()

min_class_count = y.value_counts().min()

stratify_labels = y if min_class_count >= 2 else None

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=stratify_labels,
)

print("Labeled examples:", len(labeled_df))
print("Training:", len(X_train))
print("Validation:", len(X_val))
print("Stratified split:", stratify_labels is not None)

Labeled examples: 3
Training: 2
Validation: 1
Stratified split: False

In [189]:
majority_class = y_train.value_counts().idxmax()

majority_pred = [majority_class] * len(y_val)

majority_accuracy = accuracy_score(y_val, majority_pred)
majority_macro_f1 = f1_score(
    y_val,
    majority_pred,
    average="macro",
    zero_division=0,
)

print("Majority class:", majority_class)
print("Accuracy:", round(majority_accuracy, 4))
print("Macro F1:", round(majority_macro_f1, 4))

Majority class: PRODUCT_PROBLEM
Accuracy: 0.0
Macro F1: 0.0

In [190]:
tfidf = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.95,
    sublinear_tf=True,
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf = tfidf.transform(X_val)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)
X_val_tfidf = tfidf.transform(X_val)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)

Train TF-IDF shape: (2, 2708)
Validation TF-IDF shape: (1, 2708)
Train TF-IDF shape: (2, 2708)
Validation TF-IDF shape: (1, 2708)

In [191]:
baseline_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42,
)

baseline_model.fit(X_train_tfidf, y_train)

tfidf_pred = baseline_model.predict(X_val_tfidf)

tfidf_accuracy = accuracy_score(y_val, tfidf_pred)
tfidf_macro_f1 = f1_score(
    y_val,
    tfidf_pred,
    average="macro",
    zero_division=0,
)

print("TF-IDF + Logistic Regression")
print("Accuracy:", round(tfidf_accuracy, 4))
print("Macro F1:", round(tfidf_macro_f1, 4))

TF-IDF + Logistic Regression
Accuracy: 0.0
Macro F1: 0.0

In [192]:
print(
    classification_report(
        y_val,
        tfidf_pred,
        zero_division=0,
    )
)

                 precision    recall  f1-score   support

 DELIVERY_DELAY       0.00      0.00      0.00       1.0
PRODUCT_PROBLEM       0.00      0.00      0.00       0.0

       accuracy                           0.00       1.0
      macro avg       0.00      0.00      0.00       1.0
   weighted avg       0.00      0.00      0.00       1.0

In [193]:
# Compare available text representations

input_views = {
    "first_customer_message": training_df["first_customer_message"],
    "last_customer_message": training_df["last_customer_message"],
    "conversation_text": training_df["conversation_text"],
}

for name, series in input_views.items():
    series = series.fillna("").astype(str)

    print(f"\n{name}")
    print("-" * 50)
    print("Empty:", series.str.strip().eq("").sum())
    print("Average characters:", round(series.str.len().mean(), 1))
    print("Median characters:", round(series.str.len().median(), 1))

first_customer_message
--------------------------------------------------
Empty: 0
Average characters: 131.9
Median characters: 131.5

last_customer_message
--------------------------------------------------
Empty: 0
Average characters: 107.8
Median characters: 103.0

conversation_text
--------------------------------------------------
Empty: 0
Average characters: 926.1
Median characters: 592.0

In [194]:
# Show a few examples so we can verify exactly what the classifier sees

for i in range(5):
    print("=" * 80)
    print(f"EXAMPLE {i}")
    
    print("\nFIRST CUSTOMER MESSAGE:")
    print(training_df.loc[i, "first_customer_message"])
    
    print("\nLAST CUSTOMER MESSAGE:")
    print(training_df.loc[i, "last_customer_message"])
    
    print("\nCOMPLETE CONVERSATION:")
    print(training_df.loc[i, "conversation_text"][:1000])

================================================================================
EXAMPLE 0

FIRST CUSTOMER MESSAGE:
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.

LAST CUSTOMER MESSAGE:
@AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.

COMPLETE CONVERSATION:
[CUSTOMER] I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.
[SUPPORT] @204457 We never want to let our customers down! Is there an issue with one of your current orders: https://t.co/3kQwjObgTc? ^GM
[CUSTOMER] @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +
[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.
[SUPPORT] @204457 Oh no, Bree! I'm sorry for the poor experience. When you spoke with us previously, what insights or alternatives did we provide?^TG
================================================================================
EXAMPLE 1

FIRST CUSTOMER MESSAGE:
@115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]

LAST CUSTOMER MESSAGE:
@AmazonHelp Thanks Amazon for helping me, providing me my preferred resolution. @115821  @115850 @123644 @4030 @118702  @4167 @4110 @4168 @115937 @135980 @61230 @120697 @120033 @144769 @29568 @136912 @61231  @120319

COMPLETE CONVERSATION:
[CUSTOMER] @115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)]
[SUPPORT] @183363 it to be personal information. Our Twitter page is public.​ 3/3^EM
[SUPPORT] @183363 and we'll see what best can be done to help you. Also, please don't provide your order details, as we consider 2/3^EM
[SUPPORT] @183363 I understand your concern regarding the return. Kindly reach out to our support team here: https://t.co/beaaDm0muc 1/3^EM
[CUSTOMER] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer.
[SUPPORT] @183363 I get your concern but post the expiration of return window we'll not be able to accept the return. It's the 1/3 ^SH
[SUPPORT] @183363 manufacturer who will help with the warranty. If the manufacturer is unable to h
================================================================================
EXAMPLE 2

FIRST CUSTOMER MESSAGE:
@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy

LAST CUSTOMER MESSAGE:
@AmazonHelp No  it's the stupid post office that always messes up my deliveries

COMPLETE CONVERSATION:
[CUSTOMER] @AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy
[SUPPORT] @569445 Two-Day shipping refers to the transit time in business days once an item has shipped. Some items may take additional time to prepare. Any prep time is included in the delivery estimate. More info: https://t.co/AbVhK00M4e ^EP
[CUSTOMER] @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY.
[SUPPORT] @569445 I'm sorry for the trouble! Has the delivery date changed since you placed the order? Were you sent an e-mail notifying you of the change? ^LJ
[CUSTOMER] @AmazonHelp No  it's the stupid post office that always messes up my deliveries
[SUPPORT] @569445 We can make sure this is reported to our Transportation team. When you have time send us the details here: https://t.co/hApLpMlfHN ^EP
================================================================================
EXAMPLE 3

FIRST CUSTOMER MESSAGE:
Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)

LAST CUSTOMER MESSAGE:
Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)

COMPLETE CONVERSATION:
[CUSTOMER] Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)
[SUPPORT] @253812 こちらですね・・・？( *• ̀ω•́ )b
https://t.co/Zj70OB4ODe SK
================================================================================
EXAMPLE 4

FIRST CUSTOMER MESSAGE:
@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt

LAST CUSTOMER MESSAGE:
@AmazonHelp Done pls check

COMPLETE CONVERSATION:
[CUSTOMER] @115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt
[SUPPORT] @451696 I'm sorry about the issue you have with the refunds, fill this form: https://t.co/beaaDm0muc &amp; I’ll get it checked for you. ^SY
[CUSTOMER] @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check
[SUPPORT] @451696 Thank you for sharing your details. We'll work on it and reach out to you soon. ^AP
[CUSTOMER] @AmazonHelp Thank you for quick response
[SUPPORT] @451696 You're welcome. ^AP
[CUSTOMER] @AmazonHelp One more product defaulted..Today I received a msg as delivered bt it was nt delivered to me.Pls check
[CUSTOMER] @AmazonHelp This is a serious fraud issue.Can u share the details of customer wh is taking my order n signing on my behalf
[SUPPORT] @451696 I'm sorry to hear about the tracking error. Please contact us via https://t.co/TxK11znixD and we'll do the needful. ^AM
[CUSTOMER] @AmazonHelp

In [195]:
labeled_mask = (
    training_df["intent_label"].notna()
    & training_df["intent_label"].astype(str).str.strip().ne("")
    & training_df["intent_label"].astype(str).str.upper().ne("UNLABELED")
)

labeled_df = training_df.loc[labeled_mask].copy()

X_customer = (
    labeled_df["first_customer_message"]
    .fillna("")
    .astype(str)
)

y = labeled_df["intent_label"].astype(str).str.strip()

stratify_labels = y if y.value_counts().min() >= 2 else None

X_train_customer, X_val_customer, y_train_customer, y_val_customer = (
    train_test_split(
        X_customer,
        y,
        test_size=0.25,
        random_state=42,
        stratify=stratify_labels,
    )
)

print("Training:", len(X_train_customer))
print("Validation:", len(X_val_customer))

Training: 2
Validation: 1

In [196]:
customer_tfidf = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.95,
    sublinear_tf=True,
)

X_train_customer_tfidf = customer_tfidf.fit_transform(
    X_train_customer
)

X_val_customer_tfidf = customer_tfidf.transform(
    X_val_customer
)

print(
    "Training TF-IDF shape:",
    X_train_customer_tfidf.shape
)

print(
    "Validation TF-IDF shape:",
    X_val_customer_tfidf.shape
)

Training TF-IDF shape: (2, 95)
Validation TF-IDF shape: (1, 95)

In [197]:
customer_tfidf = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2),
    min_df=1,       # allow vocab to be learned even with very small labeled sets
    max_df=1.0,     # avoid invalid max_df/min_df conflict on tiny splits
    sublinear_tf=True,
)

X_train_customer_tfidf = customer_tfidf.fit_transform(
    X_train_customer
)

X_val_customer_tfidf = customer_tfidf.transform(
    X_val_customer
)

customer_baseline_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42,
)

customer_baseline_model.fit(
    X_train_customer_tfidf,
    y_train_customer,
)

customer_pred = customer_baseline_model.predict(
    X_val_customer_tfidf
)

customer_accuracy = accuracy_score(
    y_val_customer,
    customer_pred,
)

customer_macro_f1 = f1_score(
    y_val_customer,
    customer_pred,
    average="macro",
    zero_division=0,
)

print("TF-IDF + Logistic Regression")
print("Accuracy:", round(customer_accuracy, 4))
print("Macro F1:", round(customer_macro_f1, 4))

TF-IDF + Logistic Regression
Accuracy: 1.0
Macro F1: 1.0

In [198]:
print(
    classification_report(
        y_val_customer,
        customer_pred,
        zero_division=0,
    )
)

                precision    recall  f1-score   support

DELIVERY_DELAY       1.00      1.00      1.00         1

      accuracy                           1.00         1
     macro avg       1.00      1.00      1.00         1
  weighted avg       1.00      1.00      1.00         1

In [199]:
baseline_comparison = pd.DataFrame({
    "Model": [
        "Majority Class",
        "TF-IDF + Logistic Regression (Full Conversation)",
        "TF-IDF + Logistic Regression (Customer Only)",
    ],
    "Accuracy": [
        majority_accuracy,
        tfidf_accuracy,
        customer_accuracy,
    ],
    "Macro F1": [
        majority_macro_f1,
        tfidf_macro_f1,
        customer_macro_f1,
    ],
})

baseline_comparison

                                              Model  Accuracy  Macro F1
0                                    Majority Class       0.0       0.0
1  TF-IDF + Logistic Regression (Full Conversation)       0.0       0.0
2      TF-IDF + Logistic Regression (Customer Only)       1.0       1.0

In [200]:
prediction_analysis = pd.DataFrame({
    "text": X_val_customer.values,
    "actual": y_val_customer.values,
    "predicted": customer_pred,
})

prediction_analysis["correct"] = (
    prediction_analysis["actual"]
    == prediction_analysis["predicted"]
)

prediction_analysis.head(10)

,text,actual,predicted,correct
0,"I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop.",DELIVERY_DELAY,DELIVERY_DELAY,True

In [201]:
labels_order = sorted(y.unique())

cm = confusion_matrix(
    y_val_customer,
    customer_pred,
    labels=labels_order,
)

cm_df = pd.DataFrame(
    
    cm,
    index=labels_order,
    columns=labels_order,
)

cm_df

                 DELIVERY_DELAY  PRODUCT_PROBLEM
DELIVERY_DELAY                1                0
PRODUCT_PROBLEM               0                0

In [202]:
errors = prediction_analysis[
    ~prediction_analysis["correct"]
].copy()

print("Total validation examples:", len(prediction_analysis))
print("Incorrect predictions:", len(errors))
print(
    "Error rate:",
    round(len(errors) / len(prediction_analysis), 4)
)

errors[
    ["actual", "predicted", "text"]
].head(30).to_string(index=False)

Total validation examples: 1
Incorrect predictions: 0
Error rate: 0.0

'Empty DataFrame\nColumns: [actual, predicted, text]\nIndex: []'

In [203]:
customer_probabilities = customer_baseline_model.predict_proba(
    X_val_customer_tfidf
)

confidence = customer_probabilities.max(axis=1)

prediction_analysis["confidence"] = confidence

prediction_analysis.sort_values(
    "confidence",
    ascending=False
).head(20)[
    ["actual", "predicted", "confidence", "text"]
]

,actual,predicted,confidence,text
0,DELIVERY_DELAY,DELIVERY_DELAY,0.535609,"I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop."

In [204]:
prediction_analysis[
    ~prediction_analysis["correct"]
].sort_values(
    "confidence",
    ascending=False
).head(20)[
    ["actual", "predicted", "confidence", "text"]
].to_string(index=False)

'Empty DataFrame\nColumns: [actual, predicted, confidence, text]\nIndex: []'

In [205]:
import re

def extract_customer_messages(conversation_text):
    """
    Extract only customer-authored messages from the reconstructed
    conversation while excluding all historical support responses.
    """
    if pd.isna(conversation_text):
        return ""

    text = str(conversation_text)

    messages = re.findall(
        r"\[CUSTOMER\]\s*(.*?)(?=\s*\[SUPPORT\]|\Z)",
        text,
        flags=re.DOTALL,
    )

    return " ".join(
        message.strip()
        for message in messages
        if message.strip()
    )


training_df["customer_only_text"] = (
    training_df["conversation_text"]
    .apply(extract_customer_messages)
)

print(
    "Empty customer-only conversations:",
    
    training_df["customer_only_text"].str.strip().eq("").sum()
)

print(
    "Average characters:",
    round(training_df["customer_only_text"].str.len().mean(), 1)
)

print(
    "Median characters:",
    round(training_df["customer_only_text"].str.len().median(), 1)
)

Empty customer-only conversations: 0
Average characters: 486.8
Median characters: 289.5

In [206]:
for i in range(5):
    print("=" * 80)
    print(f"EXAMPLE {i}")
    print(training_df.loc[i, "customer_only_text"])

================================================================================
EXAMPLE 0
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +
[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.
================================================================================
EXAMPLE 1
@115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer. @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered glass is available for merely Rs 100 per piece. Yet I bought Netboon at Rs 1800. I did not buy from Netboon. Who  is Netbeen ? Nobody know. I bought from Amazon. @115937 @118702 @AmazonHelp Amazon- Have the Netboon order &amp; Refusal to help. If tempered glass falls off on its own, is a quality issue. I did not buy from Netboon. I bought Netboon product from Amazon. Please resolve my concern. @115937 @118702 https://t.co/G6PkbmqPTF @AmazonHelp where is the service center of Netboon???????
[CUSTOMER] @AmazonHelp Service denial letter attached once again. How many times you want me attach this letter @115937 @20502 https://t.co/GAa6Id6ahi
[CUSTOMER] @AmazonHelp @115937 @20502 Service denial letter's copy attached once again. At lease open your eyes and read the same. What is wrong with you Amazon???? https://t.co/QtAm5wXACR
[CUSTOMER] @AmazonHelp @115937 @20502 Now, do not tell me to go and get it signed by Netboon. Give me Netboon's address, I will deal directly with them.
[CUSTOMER] @AmazonHelp @115937 @20502 Please do not buy any Netboon Product from Amazon. Netboon Cheat, Amazone support them. @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 @AmazonHelp Thanks Amazon. Netboon has charged an exorbitant price from me. He is responsible to provide me due service from the product. @AmazonHelp ORDER # 408-7866006-8411522 was cancelled by Amazon immediately after registering it. It was informed to me repeatedly by SMS. I was assured that my money will be refunded. Today, I received this SMS that it is under despatch. I do not need it. Please refund my money. https://t.co/JhES7zBUlA @AmazonHelp i agree but I fail to understand how to contact you and share my concern. @AmazonHelp I am getting this kind of SMS daily, today also. Please refund my money you have already cancelled this order, which you can verify from your own server. @AmazonHelp I have already provided the details. Since you are not taking any action, I am getting such SMSs. @AmazonHelp What I shuld do. You are not refunding my money and I am getting SMS every day. Please tell me what I should do. @AmazonHelp Kindly stop ridiculing your genuine customer. Immediately after I booked this order and paid the relevant amount. Amazon Cancelled this order and assured me to return the amount. Now. I am getting the SMS that shipment is on the way. Pl help me.
[CUSTOMER] @AmazonHelp I have dropped all the details on that linl. Kindly read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read,read and help @AmazonHelp I have already had enough harassment from you. Please confirm, did you cancel this order immediately or not. That will answer my query.
[CUSTOMER] @AmazonHelp  https://t.co/byD9feifRX
[CUSTOMER] @AmazonHelp One more SMS https://t.co/irk5Hx7xS3
[CUSTOMER] @AmazonHelp Amazon, you surprise me. How you can dispatch an item when you yourself canceled this item and promised to refund my money. Do you have any system or running a shop. @AmazonHelp I booked and order on Amazon. Immediately after booking, Amazon cancelled the order [a fact can be verified from my account] and committed to refund my amount. I purchased the item from elsewhere. Now Amazon say, item being dispatched, which I do not need. Pl refund my money https://t.co/7fhquvB6qP
[CUSTOMER] @AmazonHelp On 26.09.2017, booked order for an item on Amazon. Amazon cancelled it immediately &amp; committed to refund money, facts can be seen from my account. I purchased that item from somewhere else. Now. Amazon do not refund and say item is under dispatch. @120033 @120319
[CUSTOMER] @AmazonHelp @120033 @120319 Can you @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 help me to get my money from @115850 who themselves cancelled my order, but refuse to refund money.
[CUSTOMER] @AmazonHelp @118342 @15352 @137848 @55412 @5832 @1145 I booked an item on Amazon. But, Amazon cancelled the order [as seen in my a/c] &amp; committed to refund. Now Amazon say, it being dispatched, which I do not need. Pl help refund of my money https://t.co/37ugFU3SuC @AmazonHelp You are harassing me. See my account that you yourself cancelled this order. You sent me many SMS in this regard. I have replied your email many times. Do your job &amp; refund my money. Pl stop this nuisance of asking details again and again. @1145 Kindly intervene.
[CUSTOMER] @AmazonHelp If I do not provide details than what I do. Where the hell I should go. You are simply harassing me. Can't you see my account that you cancelled this order immediately after I booked it. What else you require. Is this your style of operation. Pl refund my money.
[CUSTOMER] @AmazonHelp When you yourself cancelled the order, I am under no obligation to prove it or supply you any detail in this regard. Check at your end and refund my money, Please instruct your inexperienced boys to avoid writing me those unwanted messages. Check your own record and do your job
[CUSTOMER] @AmazonHelp @115850 @123644  @115821- Does Amazon have one person who can appreciate that when Amazon themselves cancelled an order, which is on record, than how the can force a customer to accept it. Amazon boys do not read the account, they do not read the email. SAD SAD  SAD
[CUSTOMER] @AmazonHelp @115850 @123644 @115821 I am sick of you Amazon. Give me your final decision. Are you going to refund my money or not. I will escalate the matter to regulating authorities. @4030  @118702  @4167 @4110 @144775 @11779 @120320 @137849  @144775 @11779  @33808 https://t.co/GYuPYQ5FEv
[CUSTOMER] @AmazonHelp Every email duly answered Sir. Please show some amount of sincerity towards your organisation and discharge your responsibility. Do you think you will get away and keep my money for long. Kindly do not continue to harass me. It would not help you.
[CUSTOMER] @AmazonHelp Kindly do not pretend to apologize. Please do your work. I trust you are capable of reading client's account, or Amazon pay you only to harass the clients. Kindly act like a gentleman and refund my money. This email was replied long time ago.
[CUSTOMER] @AmazonHelp Kindly show some kind of sensibility and note my insight from the attached piece. Trust Amazon would have trained you to at least that level, or that is also too much asking from you. https://t.co/C3c2LgEC61 @AmazonHelp My dearest Sir, I am listening this since last twenty days. What makes you people to work, or Amazon keep you only to make fool of customers. @115850               @115821  @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Respond to what my dear Sir. You are not torturing me. I have given you all the details. What more you want. Do you want to kill your client. @115850 @115821  @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp No Sir, you are not sorry. Amazon has employed to harass the client, which you are doing so well. I know you are not going to refund my money, so I am also enjoying. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Amazon must send you to English Learning Academy, so that you are clear in your expression. @115821  @115850 @AmazonHelp @123644. Do you @4030  @118702  @4167 @4110 @4168 also have such kind of executives. @AmazonHelp Hi Sir, do you know the meaning of Insight. Where did you (not) learn English. I feel so sorry for Amazon. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Whether you refund or not, I will not do anymore filling. My case is clear in the attached image. If you can not appreciate your own order Nos, you will never help me @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168 https://t.co/LbhLhxlZPj
[CUSTOMER] @AmazonHelp Will you @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 not help me for refund of my money from Amazon. Details clear in the image. https://t.co/IzJXvQ0kv8
[CUSTOMER] @AmazonHelp Hi Your Excellency BS Sir. In order to make you also feel satisfied from my harassment, I fill in details fifth time also. I await eagerly to receive further torture from you. Your @115821 @115850 @4030  @118702  @4167 @4110 @4168  Exec should learn. https://t.co/FMxKiPsFsy
[CUSTOMER] @AmazonHelp Why all Amazon Sirs/Madams are silent, or are you innovating further tactics to torture and harass the client. Do Amazon run an academy where Client Harassment is taught. Do you @115821  @115850 @4030  @118702  @4167 @4110 @4168 also have similar academy.
[CUSTOMER] @AmazonHelp The word Apology does not match Amazon Executive's profile. It is counter productive for you organisation. Or is this the way you prepare your client to have further series of torture. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Co Chweet of KH when he/she says "Lately". It is ongoing since last 20 days. I know you will never refund my money. I am simply enjoying the whole process. Do you @4030  @118702  @4167 @4110 @4168 refund in such cases or fight out and kill the client. https://t.co/0WSCqXsOWr
[CUSTOMER] @AmazonHelp Amazon Team working on "what". It is obvious. They are working on how to torture the client. Do you @4030  @118702  @4167 @4110 @4168 also have similar teams.
[CUSTOMER] @AmazonHelp M/s @115821 @115850 @123644 @4030  @118702  @4167 @4110 @4168, pl note, Amazon admit that I already shared the requisite details. Still forced me to share again today on 18.10.17. How Amazon take away intelligence from their executives. It is amazing. @AmazonHelp Another admission, yet forced the client to share details again today on 18.09.17. Amazon run special session to make executive so less intelligent, sharp, responsible, anti-customer etc @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Now it is his/her turn to take revenge. Just an hour ago, I replied the queries, attached. Now his/her Holiness asks for details, without telling me what he/she demands. Amazing Amazon @4030  @118702  @4167 @4110 @4168 https://t.co/vjQlH8uQUz
[CUSTOMER] @AmazonHelp Your Excellency, 1 hour ago I obeyed your instructions to submit attached details. Your Lordship, if you are not satisfied with my humble details, kindly pardon me and show your mercy by telling what I shuld do. @4030  @118702  @4167 @4110 @4168 https://t.co/xQQz3WuutM
[CUSTOMER] @AmazonHelp No Your Honor, how a mortal can dare to be upset with a Mighty Kingdom Amazon. I am your poor people, seeking your kindness for refund of my money, if it pleases the Kingdom. Trust your Holiness will not punish me further. @4030  @118702  @4167 @4110 @4168
[CUSTOMER] @AmazonHelp Your Majesty, I am sorry I never learnt a word "Sharedd". Will you be kind enough to make me understand the meaning of your novel invention " Sharedd". I will be hugely obliged. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168 @AmazonHelp @115821 @115850 @123644 @4030 @118702 @4167 @4110 @4168 I do not agree with Confucius when he says "When ---- is inevitable. Lay back and enjoy". I am participating. I will never accept the delivery. Amazon will never refund. Some new result will flow out. Bye until when I resume after end of Festival season.  Happy Diwali to all. https://t.co/lgwolHYDxg
[CUSTOMER] @AmazonHelp I know Your Majesty, you are angry with me. I have not realized your might &amp; dared challenge. As a punishment, you will never refund my money. I am a humble commercial legal person. I am learning a commercial dispute readdress. Whether you pay or not, I will be remain winner. @AmazonHelp My dear Sir, you are torturing me. I sent these details so many times in past 20 days. Your intelligence and service level are much lower than a road side shop. @135980 @61230 @120697 @120033 @144769 @29568 @136912 @61231 @120319
[CUSTOMER] @AmazonHelp @135980 @61230 @120697 @120033 @135789 @144769 @71291 @29568 @136912 @61231 @219260 @120319 Amazon an ethic less organisation. Amazon executives shameless group of personnel. No customer support in Amazon
[CUSTOMER] @AmazonHelp You lack even commonsense. It is pain to interact with you. A class fifth standard student will be more intelligent and responsive than you. @115821  @115850 @123644 @4030  @118702  @4167 @4110 @4168 @115937
[CUSTOMER] @AmazonHelp Amazon has employed a bunch of brainless personnel in customer care. They neither read, nor listen nor understand customers' pain. Amazon cheat the client. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168 @115937
[CUSTOMER] @AmazonHelp Useless, Brainless, Emotionless person employed in Amazon. @115821  @115850 @AmazonHelp @123644 @4030  @118702  @4167 @4110 @4168 @115937 @AmazonHelp Thanks Amazon for helping me, providing me my preferred resolution. @115821  @115850 @123644 @4030 @118702  @4167 @4110 @4168 @115937 @135980 @61230 @120697 @120033 @144769 @29568 @136912 @61231  @120319
================================================================================
EXAMPLE 2
@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY. @AmazonHelp No  it's the stupid post office that always messes up my deliveries
================================================================================
EXAMPLE 3
Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)
================================================================================
EXAMPLE 4
@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check @AmazonHelp Thank you for quick response @AmazonHelp One more product defaulted..Today I received a msg as delivered bt it was nt delivered to me.Pls check
[CUSTOMER] @AmazonHelp This is a serious fraud issue.Can u share the details of customer wh is taking my order n signing on my behalf @AmazonHelp Already contacted.All they do is ask for 3 days..and after 3 days they refund the amt.bt thats nt thr issue ..
[CUSTOMER] @AmazonHelp Who’s receiving product on my behalf..pls share the details @AmazonHelp Done pls check

In [207]:
X_customer_context = (
    training_df["customer_only_text"]
    .fillna("")
    .astype(str)
)

y = training_df["intent_label"].astype(str)

# Keep only truly labeled rows; unlabeled / empty / "UNLABELED" entries
# will otherwise create NaN classes and fail StratifiedKFold/TrainTestSplit.
labeled_mask = (
    training_df["intent_label"].notna()
    & training_df["intent_label"].astype(str).str.strip().ne("")
    & training_df["intent_label"].astype(str).str.upper().ne("UNLABELED")
)

labeled_df = training_df.loc[labeled_mask].copy()

X_customer_context = (
    labeled_df["customer_only_text"]
    .fillna("")
    .astype(str)
)

y = labeled_df["intent_label"].astype(str).str.strip()

# Only stratify if every class has at least 2 examples
stratify_labels = y if y.value_counts().min() >= 2 else None

X_train_context, X_val_context, y_train_context, y_val_context = (
    train_test_split(
        X_customer_context,
        y,
        test_size=0.25,
        random_state=42,
        stratify=stratify_labels,
    )
)

In [208]:
context_tfidf = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2),
    min_df=2,
    max_df=1.0,
    sublinear_tf=True,
)

X_train_context_tfidf = context_tfidf.fit_transform(
    X_train_context
)

X_val_context_tfidf = context_tfidf.transform(
    X_val_context
)

print("Training shape:", X_train_context_tfidf.shape)
print("Validation shape:", X_val_context_tfidf.shape)

Training shape: (2, 34)
Validation shape: (1, 34)

In [209]:
context_tfidf = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    ngram_range=(1, 2),
    min_df=1,
    max_df=1.0,
    sublinear_tf=True,
)

X_train_context_tfidf = context_tfidf.fit_transform(
    X_train_context
)

X_val_context_tfidf = context_tfidf.transform(
    X_val_context
)

context_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42,
)

context_model.fit(
    X_train_context_tfidf,
    y_train_context,
)

context_pred = context_model.predict(
    X_val_context_tfidf
)

context_accuracy = accuracy_score(
    y_val_context,
    context_pred,
)

context_macro_f1 = f1_score(
    y_val_context,
    context_pred,
    average="macro",
    zero_division=0,
)

print("Customer-Only Context TF-IDF + Logistic Regression")
print("Accuracy:", round(context_accuracy, 4))
print("Macro F1:", round(context_macro_f1, 4))

Customer-Only Context TF-IDF + Logistic Regression
Accuracy: 0.0
Macro F1: 0.0

In [210]:
print(
    classification_report(
        y_val_context,
        context_pred,
        zero_division=0,
    )
)

                 precision    recall  f1-score   support

 DELIVERY_DELAY       0.00      0.00      0.00       1.0
PRODUCT_PROBLEM       0.00      0.00      0.00       0.0

       accuracy                           0.00       1.0
      macro avg       0.00      0.00      0.00       1.0
   weighted avg       0.00      0.00      0.00       1.0

In [211]:
baseline_comparison = pd.DataFrame({
    "Model": [
        "Majority Class",
        "TF-IDF + Logistic Regression (Full Conversation)",
        "TF-IDF + Logistic Regression (First Customer Message)",
        "TF-IDF + Logistic Regression (Customer-Only Context)",
    ],
    "Accuracy": [
        majority_accuracy,
        tfidf_accuracy,
        customer_accuracy,
        context_accuracy,
    ],
    "Macro F1": [
        majority_macro_f1,
        tfidf_macro_f1,
        customer_macro_f1,
        context_macro_f1,
    ],
})

baseline_comparison

                                                   Model  Accuracy  Macro F1
0                                         Majority Class       0.0       0.0
1       TF-IDF + Logistic Regression (Full Conversation)       0.0       0.0
2  TF-IDF + Logistic Regression (First Customer Message)       1.0       1.0
3   TF-IDF + Logistic Regression (Customer-Only Context)       0.0       0.0

Adding subsequent customer messages increased accuracy from 9.33% → 25.33%

#### Stronger Classical Intent Classifier

Twitter support conversations contain spelling variations, abbreviations,
usernames, URLs, and informal language.

We therefore evaluate a combined word-level and character-level TF-IDF
representation with a Linear SVM classifier.

This provides a stronger classical baseline before introducing
embedding-based models.

In [212]:
from sklearn.pipeline import FeatureUnion
from sklearn.svm import LinearSVC

In [213]:
word_vectorizer = TfidfVectorizer(
    lowercase=True,
    strip_accents="unicode",
    analyzer="word",
    ngram_range=(1, 2),
    min_df=1,
    sublinear_tf=True,
)

char_vectorizer = TfidfVectorizer(
    lowercase=True,
    analyzer="char",
    ngram_range=(3, 5),
    min_df=1,
    sublinear_tf=True,
)

combined_vectorizer = FeatureUnion([
    ("word", word_vectorizer),
    ("char", char_vectorizer),
])

In [214]:
X_train_combined = combined_vectorizer.fit_transform(
    X_train_context
)

X_val_combined = combined_vectorizer.transform(
    X_val_context
)

print("Training shape:", X_train_combined.shape)
print("Validation shape:", X_val_combined.shape)

Training shape: (2, 14896)
Validation shape: (1, 14896)

In [215]:
svm_model = LinearSVC(
    class_weight="balanced",
    C=1.0,
    random_state=42,
)

svm_model.fit(
    X_train_combined,
    y_train_context,
)

svm_pred = svm_model.predict(
    X_val_combined
)

In [216]:
svm_accuracy = accuracy_score(
    y_val_context,
    svm_pred,
)

svm_macro_f1 = f1_score(
    y_val_context,
    svm_pred,
    average="macro",
    zero_division=0,
)

print("Word + Character TF-IDF + Linear SVM")
print("Accuracy:", round(svm_accuracy, 4))
print("Macro F1:", round(svm_macro_f1, 4))

Word + Character TF-IDF + Linear SVM
Accuracy: 0.0
Macro F1: 0.0

In [217]:
print(
    classification_report(
        y_val_context,
        svm_pred,
        zero_division=0,
    )
)

                 precision    recall  f1-score   support

 DELIVERY_DELAY       0.00      0.00      0.00       1.0
PRODUCT_PROBLEM       0.00      0.00      0.00       0.0

       accuracy                           0.00       1.0
      macro avg       0.00      0.00      0.00       1.0
   weighted avg       0.00      0.00      0.00       1.0

In [218]:
baseline_comparison = pd.DataFrame({
    "Model": [
        "Majority Class",
        "TF-IDF + Logistic Regression (Full Conversation)",
        "TF-IDF + Logistic Regression (First Customer Message)",
        "TF-IDF + Logistic Regression (Customer-Only Context)",
        "Word + Character TF-IDF + Linear SVM (Customer-Only Context)",
    ],
    "Accuracy": [
        majority_accuracy,
        tfidf_accuracy,
        customer_accuracy,
        context_accuracy,
        svm_accuracy,
    ],
    "Macro F1": [
        majority_macro_f1,
        tfidf_macro_f1,
        customer_macro_f1,
        context_macro_f1,
        svm_macro_f1,
    ],
})

baseline_comparison

,Model,Accuracy,Macro F1
0,Majority Class,0.0,0.0
1,TF-IDF + Logistic Regression (Full Conversation),0.0,0.0
2,TF-IDF + Logistic Regression (First Customer Message),1.0,1.0
3,TF-IDF + Logistic Regression (Customer-Only Context),0.0,0.0
4,Word + Character TF-IDF + Linear SVM (Customer-Only Context),0.0,0.0

Classical lexical models are struggling with the semantic variation and noisy language in these Twitter conversations.

In [219]:
try:
    import sentence_transformers
    print("sentence-transformers:", sentence_transformers.__version__)
except ImportError:
    print("sentence-transformers is NOT installed")

sentence-transformers: 5.1.0

#### Semantic Intent Classifier — Sentence Embeddings

Lexical TF-IDF models struggle with the noisy and semantically varied
language in Twitter support conversations.

We therefore represent each customer-only conversation using a pretrained
Sentence Transformer embedding and train a lightweight Logistic Regression
classifier on top.

The pretrained encoder is not fine-tuned on the evaluation data.

In [220]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [221]:
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded.")

Embedding model loaded.

In [222]:
X_train_context
X_val_context
y_train_context
y_val_context

print("Training examples:", len(X_train_context))
print("Validation examples:", len(X_val_context))
print("Training labels:", len(y_train_context))
print("Validation labels:", len(y_val_context))

Training examples: 2
Validation examples: 1
Training labels: 2
Validation labels: 1

In [223]:
X_train_embeddings = embedding_model.encode(
    X_train_context.tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

X_val_embeddings = embedding_model.encode(
    X_val_context.tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print("Training embedding shape:", X_train_embeddings.shape)
print("Validation embedding shape:", X_val_embeddings.shape)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Training embedding shape: (2, 384)
Validation embedding shape: (1, 384)

In [224]:
embedding_model_classifier = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42,
)

embedding_model_classifier.fit(
    X_train_embeddings,
    y_train_context,
)

LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)

In [225]:
embedding_pred = embedding_model_classifier.predict(
    X_val_embeddings
)

In [226]:
embedding_accuracy = accuracy_score(
    y_val_context,
    embedding_pred,
)

embedding_macro_f1 = f1_score(
    y_val_context,
    embedding_pred,
    average="macro",
    zero_division=0,
)

print("Sentence Embeddings + Logistic Regression")
print("Accuracy:", round(embedding_accuracy, 4))
print("Macro F1:", round(embedding_macro_f1, 4))

Sentence Embeddings + Logistic Regression
Accuracy: 1.0
Macro F1: 1.0

In [227]:
print(
    classification_report(
        y_val_context,
        embedding_pred,
        zero_division=0,
    )
)

                precision    recall  f1-score   support

DELIVERY_DELAY       1.00      1.00      1.00         1

      accuracy                           1.00         1
     macro avg       1.00      1.00      1.00         1
  weighted avg       1.00      1.00      1.00         1

In [228]:
baseline_comparison = pd.DataFrame({
    "Model": [
        "Majority Class",
        "TF-IDF + Logistic Regression (Full Conversation)",
        "TF-IDF + Logistic Regression (First Customer Message)",
        "TF-IDF + Logistic Regression (Customer-Only Context)",
        "Word + Character TF-IDF + Linear SVM (Customer-Only Context)",
        "Sentence Embeddings + Logistic Regression",
    ],
    "Accuracy": [
        majority_accuracy,
        tfidf_accuracy,
        customer_accuracy,
        context_accuracy,
        svm_accuracy,
        embedding_accuracy,
    ],
    "Macro F1": [
        majority_macro_f1,
        tfidf_macro_f1,
        customer_macro_f1,
        context_macro_f1,
        svm_macro_f1,
        embedding_macro_f1,
    ],
})

baseline_comparison

,Model,Accuracy,Macro F1
0,Majority Class,0.0,0.0
1,TF-IDF + Logistic Regression (Full Conversation),0.0,0.0
2,TF-IDF + Logistic Regression (First Customer Message),1.0,1.0
3,TF-IDF + Logistic Regression (Customer-Only Context),0.0,0.0
4,Word + Character TF-IDF + Linear SVM (Customer-Only Context),0.0,0.0
5,Sentence Embeddings + Logistic Regression,1.0,1.0

In [229]:
print("resolution_episodes available:", "resolution_episodes" in globals())

if "resolution_episodes" in globals():
    print("Shape:", resolution_episodes.shape)
    print("Columns:")
    print(resolution_episodes.columns.tolist())

resolution_episodes available: True
Shape: (192718, 13)
Columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

In [230]:
amazon_resolution_corpus = resolution_episodes[
    resolution_episodes["support_account"] == "AmazonHelp"
].copy()

amazon_resolution_corpus = amazon_resolution_corpus.reset_index()

print("Shape:", amazon_resolution_corpus.shape)
print("Columns:")
print(amazon_resolution_corpus.columns.tolist())

print("\nAmazonHelp conversations:", len(amazon_resolution_corpus))
print(
    "Unique conversation IDs:",
    amazon_resolution_corpus["conversation_id"].nunique()
)

Shape: (82246, 14)
Columns:
['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket']

AmazonHelp conversations: 82246
Unique conversation IDs: 82246

In [231]:
display(
    amazon_resolution_corpus[
        [
            "conversation_id",
            "conversation_size",
            "customer_turns",
            "support_turns",
            "conversation_text",
        ]
    ].head(5)
)

,conversation_id,conversation_size,customer_turns,support_turns,conversation_text
0,272,7,4,3,[CUSTOMER] amazonのfireTVstickが見れない😢\n[SUPPORT] @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET\n[CUSTOMER] @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。\n[CUSTOMER] @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[SUPPORT] @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET\n[CUSTOMER] @AmazonHelp こちらこそありがとうございました。\n[SUPPORT] @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET
1,325,2,1,1,[CUSTOMER] amazonプライムビデオ、再生エラーが多いです\n[SUPPORT] @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET
2,617,5,3,2,"[CUSTOMER] Way to drop the ball on customer service @115821 so pissed right now!\n[SUPPORT] @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN\n[CUSTOMER] @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day\n[SUPPORT] @115820 We'd like to take a further look into this with you! Please reach us by phone or chat here:..."
3,621,2,1,1,"[CUSTOMER] @115823 I want my amazon payments account CLOSED. dm me please.\n[SUPPORT] @115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH"
4,624,4,2,2,"[CUSTOMER] @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?\n[SUPPORT] @115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS\n[CUSTOMER] @AmazonHelp Okay, danke für die Info\n[SUPPORT] @115824 Wir haben zu danken. Schönen Abend noch. ^JS"

In [232]:
# create a retrieval text
amazon_resolution_corpus["retrieval_text"] = (
    amazon_resolution_corpus["conversation_text"]
    .fillna("")
    .astype(str)
)

print(
    amazon_resolution_corpus["retrieval_text"]
    .str.len()
    .describe()
)

count    82246.000000
mean       588.593464
std        649.037089
min         46.000000
25%        277.000000
50%        423.000000
75%        698.000000
max      50654.000000
Name: retrieval_text, dtype: float64

In [233]:
resolution_embeddings = embedding_model.encode(
    amazon_resolution_corpus["retrieval_text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print("Resolution embedding shape:", resolution_embeddings.shape)

Batches:   0%|          | 0/1286 [00:00<?, ?it/s]

Resolution embedding shape: (82246, 384)

Build FAISS Index

In [234]:
import faiss
print("FAISS:", faiss.__version__)

FAISS: 1.11.0

In [235]:
embedding_dimension = resolution_embeddings.shape[1]

faiss_index = faiss.IndexFlatIP(
    embedding_dimension
)

faiss_index.add(
    resolution_embeddings.astype("float32")
)

print("FAISS index size:", faiss_index.ntotal)
print("Embedding dimension:", embedding_dimension)

FAISS index size: 82246
Embedding dimension: 384

In [236]:
# create a retrieval function
def retrieve_historical_resolutions(
    query,
    top_k=5,
):
    """
    Retrieve historically similar AmazonHelp conversations.
    """

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True,
    )

    scores, indices = faiss_index.search(
        query_embedding.astype("float32"),
        top_k,
    )

    results = amazon_resolution_corpus.iloc[
        indices[0]
    ].copy()

    results["similarity"] = scores[0]

    return results

In [237]:
query = (
    "My package was supposed to arrive yesterday "
    "but it still hasn't been delivered."
)

retrieved = retrieve_historical_resolutions(
    query,
    top_k=5,
)

retrieved[
    [
        "conversation_id",
        "similarity",
        "conversation_size",
        "customer_turns",
        "support_turns",
        "conversation_text",
    ]
]

,conversation_id,similarity,conversation_size,customer_turns,support_turns,conversation_text
26076,810790,0.822072,2,1,1,[CUSTOMER] S/o to @115821 for saying my package would be delivered yesterday.. and it still hasn’t came today lol\n[SUPPORT] @313190 I'm sorry it hasn't arrived yet! Reach out to us here: https://t.co/hApLpMlfHN so we can take a look into this delivery. ^AH
31787,1022541,0.769380,4,2,2,[CUSTOMER] @115821 whyyyyyyy did you say you delivered my package an hour ago and it still isn’t here????!???????????????????????\n[SUPPORT] @361962 I'm sorry you don't have your package! Here's a link to our Help page for situations like this: https://t.co/IZXXAsQ3jL ^BV\n[CUSTOMER] @AmazonHelp That link supplies Literally no help and still the package isn’t here. Thanks\n[SUPPORT] @361962 Orders like this typically arrive by the next business day. Please let us know if you don't have it by...
76127,2827311,0.767698,2,1,1,"[CUSTOMER] @115821 My package never arrived, says it was delivered 2 days ago and Im still waiting! There's no way of telling you this except TWITTER?!\n[SUPPORT] @787517 Hi Tony, sorry to hear that you haven't received your parcel yet. Have you tried these suggestions: https://t.co/gqSmOhsbTh? ^JJ"
56765,2142995,0.757764,2,1,1,[CUSTOMER] amazon says my package came 2 days ago but like i don’t have it this is a problem\n[SUPPORT] @630068 I'm sorry to hear it hasn't arrived. We'd like to look into the delivery and available options: https://t.co/hApLpMlfHN ^LI
59904,2285995,0.757157,2,1,1,"[CUSTOMER] I think @115821 and @118706 need to talk. I think @118706 lies to them constantly about when things are delivered. Sometimes it will even say delivered and come the next day. This one says today on Amazon, Monday according to USPS. https://t.co/Zr8Hv99bpd\n[SUPPORT] @664281 I'm sorry your package is running late, Stephen! If the item hasn't arrived by Monday, please phone us here: https://t.co/hApLpMlfHN to report this and discuss additional options. ^LB"

In [238]:
print("taxonomy_audit_df available:", "taxonomy_audit_df" in globals())

taxonomy_audit_df available: False

In [239]:
taxonomy_audit_df = pd.read_csv(
    PROJECT_ROOT / "data" / "processed" / "taxonomy_audit_150.csv"
)

print("Shape:", taxonomy_audit_df.shape)

print("\nColumns:")
print(taxonomy_audit_df.columns.tolist())

print("\nMissing intent labels:")
print(taxonomy_audit_df["intent_label"].isna().sum())

print("\nIntent distribution:")
print(taxonomy_audit_df["intent_label"].value_counts().sort_index())

Shape: (150, 16)

Columns:
['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'intent_label', 'annotation_notes', 'annotator']

Missing intent labels:
0

Intent distribution:
intent_label
ACCOUNT_ACCESS_SECURITY              5
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     2
DELIVERY_DELAY                      38
DELIVERY_MISSING_OR_MISDELIVERED    13
DEVICE_TECHNICAL_SUPPORT             3
DIGITAL_CONTENT                      6
GIFT_CARD_PROMOTION                  2
ORDER_STATUS_OR_CANCELLATION         7
OTHER_NON_SUPPORT                   29
PAYMENT_BILLING                      5
PRIME_MEMBERSHIP                     5
PRODUCT_AVAILABILITY_INFORMATION     6
PRODUCT_PROBLEM                     17
RETURN_REPLACEMENT_REFUND            8
WEBSITE_APP_TECHNICAL                4
Name: count, dtype: int64

In [240]:
# Match audit conversations against the AmazonHelp retrieval corpus
# using the complete reconstructed conversation text.

audit_texts = set(
    taxonomy_audit_df["conversation_text"]
    .fillna("")
    .astype(str)
)

amazon_resolution_corpus["is_audit_example"] = (
    amazon_resolution_corpus["conversation_text"]
    .fillna("")
    .astype(str)
    .isin(audit_texts)
)

print(
    "Audit conversations found in retrieval corpus:",
    amazon_resolution_corpus["is_audit_example"].sum()
)

print(
    "Retrieval corpus size:",
    len(amazon_resolution_corpus)
)

Audit conversations found in retrieval corpus: 150
Retrieval corpus size: 82246

In [241]:
audit_matches = amazon_resolution_corpus[
    amazon_resolution_corpus["is_audit_example"]
]

print(
    audit_matches[
        
        [
            "conversation_id",
            "intent_label" if "intent_label" in audit_matches.columns else "support_account",
            "conversation_text",
        ]
    ].head()
)

      conversation_id support_account  \
770             34483      AmazonHelp
1140            52943      AmazonHelp
1848            80798      AmazonHelp
2160            96641      AmazonHelp
3459           137048      AmazonHelp

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conversation_text
770                                                            [CUSTOMER] @115821 @115851 why do you continue to use @2150 I don’t get my items! How can “the door” sign for a package! Terrible service!\n[SUPPORT] @123475 Sorry for the poor experience! Have you spoken our customer service so we could escalate this feedback to the carrier? ^AD\n[CUSTOMER] @AmazonHelp I have but this is the 2nd time this has happened. I was told in April you would not give my packages to Lasership but you did! No bueno!
1140  [CUSTOMER] @AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (nev...
1848  [CUSTOMER] @115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently.\n[SUPPORT] @133926 That's strange! I'm sorry for about the incorrect update about the delivery of your order. May I know if you've reported this to our support team here:https://t.co/vlvfJr4nN9? 1/2 ^EM\n[SUPPORT] @133926 Also, please don't provide your order details, as we consider it to be personal information. Our Twitt...
2160  [CUSTOMER] .@115821 @137088 What a joke. After "Guaranteed Delivery" today, total fail. Now I have to wait up to 6 days for an item that was supposed to be delivered next day? And the package started the day in Northridge! I could have picked it up myself. https://t.co/X2HpfjnogW\n[CUSTOMER] @115821 @137088 Horrible delivery experience @115821 and @137088. I'm willing to bet money that you had this information earlier in the day. But I just don't understand how a package that ORIGINATED less...
3459  [CUSTOMER] Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT\n[CUSTOMER] @146907 @120533 @AmazonHelp Oui ça part en sucette. Avec le Prime sur des produits envoyés par Amazon je n'arrive plus à être livré le lendemain que de temps en temps..\n[SUPPORT] @146907 Bonjour Pierre-Alain, sachez que de nombreux facteurs indépendants de notre volonté influent sur la date de livraison d'une commande : la disponibilité de l'article, la destination du colis...\n^ARC\n[SUPPO...

Create a leakage-safe retrieval corpus

In [242]:
# Exclude the 150 taxonomy-audit conversations from the retrieval corpus.

audit_conversation_ids = set(
    audit_matches["conversation_id"].astype(int)
)

amazon_retrieval_eval_corpus = amazon_resolution_corpus[
    ~amazon_resolution_corpus["conversation_id"].isin(
        audit_conversation_ids
    )
].copy()

print("Original AmazonHelp corpus:", len(amazon_resolution_corpus))
print("Audit conversations excluded:", len(audit_conversation_ids))
print(
    "Leakage-safe retrieval corpus:",
    len(amazon_retrieval_eval_corpus)
)

print(
    "Remaining unique conversation IDs:",
    amazon_retrieval_eval_corpus["conversation_id"].nunique()
)

Original AmazonHelp corpus: 82246
Audit conversations excluded: 150
Leakage-safe retrieval corpus: 82096
Remaining unique conversation IDs: 82096

Rebuild FAISS using only the 82,096 conversations

In [243]:
# Build a leakage-safe FAISS retrieval index.
# The 150 taxonomy-audit conversations are excluded.

retrieval_texts = (
    amazon_retrieval_eval_corpus["retrieval_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

resolution_embeddings_safe = embedding_model.encode(
    retrieval_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(
    "Resolution embedding shape:",
    resolution_embeddings_safe.shape
)

Batches:   0%|          | 0/1283 [00:00<?, ?it/s]

Resolution embedding shape: (82096, 384)

In [244]:
import faiss

retrieval_dimension = resolution_embeddings_safe.shape[1]

faiss_index_safe = faiss.IndexFlatIP(
    retrieval_dimension
)

faiss_index_safe.add(
    resolution_embeddings_safe.astype("float32")
)

print("FAISS index size:", faiss_index_safe.ntotal)
print("Embedding dimension:", retrieval_dimension)

FAISS index size: 82096
Embedding dimension: 384

In [245]:
def retrieve_historical_resolutions_safe(
    query,
    top_k=5,
):
    """
    Retrieve historically similar AmazonHelp conversations
    from the leakage-safe retrieval corpus.
    """

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True,
    )

    scores, indices = faiss_index_safe.search(
        query_embedding.astype("float32"),
        top_k,
    )

    results = amazon_retrieval_eval_corpus.iloc[
        indices[0]
    ].copy()

    results["similarity"] = scores[0]

    return results

In [246]:
test_query = (
    "My package was supposed to arrive yesterday "
    "but it still hasn't been delivered."
)

retrieved_safe = retrieve_historical_resolutions_safe(
    test_query,
    top_k=5,
)

retrieved_safe[
    [
        "conversation_id",
        "similarity",
        "conversation_size",
        "customer_turns",
        "support_turns",
        "conversation_text",
    ]
]

,conversation_id,similarity,conversation_size,customer_turns,support_turns,conversation_text
26076,810790,0.822072,2,1,1,[CUSTOMER] S/o to @115821 for saying my package would be delivered yesterday.. and it still hasn’t came today lol\n[SUPPORT] @313190 I'm sorry it hasn't arrived yet! Reach out to us here: https://t.co/hApLpMlfHN so we can take a look into this delivery. ^AH
31787,1022541,0.769380,4,2,2,[CUSTOMER] @115821 whyyyyyyy did you say you delivered my package an hour ago and it still isn’t here????!???????????????????????\n[SUPPORT] @361962 I'm sorry you don't have your package! Here's a link to our Help page for situations like this: https://t.co/IZXXAsQ3jL ^BV\n[CUSTOMER] @AmazonHelp That link supplies Literally no help and still the package isn’t here. Thanks\n[SUPPORT] @361962 Orders like this typically arrive by the next business day. Please let us know if you don't have it by...
76127,2827311,0.767698,2,1,1,"[CUSTOMER] @115821 My package never arrived, says it was delivered 2 days ago and Im still waiting! There's no way of telling you this except TWITTER?!\n[SUPPORT] @787517 Hi Tony, sorry to hear that you haven't received your parcel yet. Have you tried these suggestions: https://t.co/gqSmOhsbTh? ^JJ"
56765,2142995,0.757764,2,1,1,[CUSTOMER] amazon says my package came 2 days ago but like i don’t have it this is a problem\n[SUPPORT] @630068 I'm sorry to hear it hasn't arrived. We'd like to look into the delivery and available options: https://t.co/hApLpMlfHN ^LI
59904,2285995,0.757157,2,1,1,"[CUSTOMER] I think @115821 and @118706 need to talk. I think @118706 lies to them constantly about when things are delivered. Sometimes it will even say delivered and come the next day. This one says today on Amazon, Monday according to USPS. https://t.co/Zr8Hv99bpd\n[SUPPORT] @664281 I'm sorry your package is running late, Stephen! If the item hasn't arrived by Monday, please phone us here: https://t.co/hApLpMlfHN to report this and discuss additional options. ^LB"

In [247]:
# Prepare leakage-safe retrieval evaluation queries.
# The audit conversations are used ONLY as queries.
# They are NOT present in the retrieval corpus.

audit_eval = taxonomy_audit_df.copy()

def extract_customer_only(text):
    text = str(text)
    
    customer_messages = re.findall(
        r"\[CUSTOMER\]\s*(.*?)(?=\[SUPPORT\]|\Z)",
        text,
        flags=re.DOTALL,
    )
    
    return " ".join(
        msg.strip() for msg in customer_messages
        if msg.strip()
    )

audit_eval["customer_only_text"] = (
    audit_eval["conversation_text"]
    .fillna("")
    .map(extract_customer_only)
)

print("Evaluation queries:", len(audit_eval))
print("Missing customer-only queries:",
      audit_eval["customer_only_text"].eq("").sum())
print("Intent classes:", audit_eval["intent_label"].nunique())

Evaluation queries: 150
Missing customer-only queries: 0
Intent classes: 15

In [248]:
# Encode all 150 evaluation queries

audit_query_embeddings = embedding_model.encode(
    audit_eval["customer_only_text"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print("Query embedding shape:", audit_query_embeddings.shape)

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

Query embedding shape: (150, 384)

In [249]:
# Retrieve top-10 historical conversations for every audit query

TOP_K = 10

retrieval_scores, retrieval_indices = faiss_index_safe.search(
    audit_query_embeddings.astype("float32"),
    TOP_K,
)

print("Scores shape:", retrieval_scores.shape)
print("Indices shape:", retrieval_indices.shape)

Scores shape: (150, 10)
Indices shape: (150, 10)

In [250]:
import numpy as np

retrieval_results = []

for query_idx in range(len(audit_eval)):
    
    true_intent = audit_eval.iloc[query_idx]["intent_label"]
    
    retrieved_rows = amazon_retrieval_eval_corpus.iloc[
        retrieval_indices[query_idx]
    ]
    
    retrieved_intents = []
    
    for _, row in retrieved_rows.iterrows():
        # We need an intent label for retrieved historical examples.
        # The 150 audit labels cannot be used because those conversations
        # were explicitly excluded from the retrieval corpus.
        retrieved_intents.append(None)
    
    retrieval_results.append({
        "query_idx": query_idx,
        "true_intent": true_intent,
        "retrieved_intents": retrieved_intents,
    })

In [251]:
# Load the 300 labelled AmazonHelp training examples

training_benchmark = pd.read_csv(
    PROJECT_ROOT
    / "data"
    / "processed"
    / "amazonhelp_intent_training_batch_01.csv"
)

training_benchmark = training_benchmark[
    [
        "conversation_id",
        "conversation_text",
        "intent_label",
    ]
].copy()

training_benchmark["benchmark_source"] = "training"

print("Training benchmark rows:", len(training_benchmark))
print(
    "Unique conversation IDs:",
    training_benchmark["conversation_id"].nunique()
)
print(
    "Missing intent labels:",
    training_benchmark["intent_label"].isna().sum()
)

Training benchmark rows: 300
Unique conversation IDs: 300
Missing intent labels: 297

In [252]:
audit_lookup = (
    amazon_resolution_corpus[
        ["conversation_id", "conversation_text"]
    ]
    .copy()
)

audit_benchmark = taxonomy_audit_df[
    [
        "conversation_text",
        "intent_label",
    ]
].copy()

audit_benchmark = audit_benchmark.merge(
    audit_lookup,
    on="conversation_text",
    how="left",
    validate="one_to_one",
)

audit_benchmark["benchmark_source"] = "taxonomy_audit"

print("Audit benchmark rows:", len(audit_benchmark))
print(
    "Missing audit conversation IDs:",
    audit_benchmark["conversation_id"].isna().sum()
)

Audit benchmark rows: 150
Missing audit conversation IDs: 0

In [253]:
retrieval_benchmark = pd.concat(
    [
        training_benchmark,
        audit_benchmark[
            [
                "conversation_id",
                "conversation_text",
                "intent_label",
                "benchmark_source",
            ]
        ],
    ],
    ignore_index=True,
)

retrieval_benchmark["conversation_id"] = (
    retrieval_benchmark["conversation_id"].astype(int)
)

print("Total retrieval queries:", len(retrieval_benchmark))
print(
    "Unique query conversations:",
    retrieval_benchmark["conversation_id"].nunique()
)

print("\nBenchmark source:")
print(retrieval_benchmark["benchmark_source"].value_counts())

Total retrieval queries: 450
Unique query conversations: 450

Benchmark source:
benchmark_source
training          300
taxonomy_audit    150
Name: count, dtype: int64

In [254]:
retrieval_benchmark["customer_only_text"] = (
    retrieval_benchmark["conversation_text"]
    .fillna("")
    .map(extract_customer_only)
)

print(
    "Empty customer queries:",
    retrieval_benchmark["customer_only_text"].eq("").sum()
)

print(
    "Average query length:",
    retrieval_benchmark["customer_only_text"].str.len().mean()
)

print(
    "Median query length:",
    retrieval_benchmark["customer_only_text"].str.len().median()
)

Empty customer queries: 0
Average query length: 461.38666666666666
Median query length: 275.5

In [255]:
retrieval_benchmark[
    [
        "conversation_id",
        "intent_label",
        "benchmark_source",
        "customer_only_text",
    ]
].head(5)

,conversation_id,intent_label,benchmark_source,customer_only_text
0,373303,DELIVERY_DELAY,training,"I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +\n[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then."
1,282739,PRODUCT_PROBLEM,training,"@115821 Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer. @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered gl..."
2,2292312,DELIVERY_DELAY,training,@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY. @AmazonHelp No it's the stupid post office that always messes up my deliveries
3,570075,NaN,training,Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)
4,1427974,NaN,training,@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check @AmazonHelp Thank you for quick response @AmazonHelp One more product defaulted..Today I received a msg as delivered bt it was nt delivered to me.Pls check\n[CUSTOMER] @AmazonHelp This is a serious fraud issue.Can u share the details of customer wh is taking my order n signing on ...

In [256]:
print("Total rows:", len(retrieval_benchmark))

print(
    "Missing intent labels:",
    retrieval_benchmark["intent_label"].isna().sum()
)

print(
    "Missing conversation IDs:",
    retrieval_benchmark["conversation_id"].isna().sum()
)

print(
    "\nRows with missing intent labels:"
)

display(
    retrieval_benchmark[
        retrieval_benchmark["intent_label"].isna()
    ][
        [
            "conversation_id",
            "conversation_text",
            "benchmark_source",
        ]
    ].head(20)
)

Total rows: 450
Missing intent labels: 297
Missing conversation IDs: 0

Rows with missing intent labels:

,conversation_id,conversation_text,benchmark_source
3,570075,[CUSTOMER] Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)\n[SUPPORT] @253812 こちらですね・・・？( *• ̀ω•́ )b \nhttps://t.co/Zj70OB4ODe SK,training
4,1427974,"[CUSTOMER] @115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt\n[SUPPORT] @451696 I'm sorry about the issue you have with the refunds, fill this form: https://t.co/beaaDm0muc &amp; I’ll get it checked for you. ^SY\n[CUSTOMER] @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check\n[SUPPORT] @451696 Thank you for sharing your details. We'll work on it and reach out to you soon. ^AP\n[CU...",training
5,1717565,"[CUSTOMER] Wait what?! In first group to preorder and I get it in Dec? @115788 @AmazonHelp @115787 Can someone assist?!! https://t.co/PRl65hAXj3\n[SUPPORT] @332329 We'd like to help. What does the current status of your order state here: https://t.co/q4LAMZ3tbE? ^GG\n[CUSTOMER] @AmazonHelp https://t.co/IcayOfZZ3L\n[CUSTOMER] @AmazonHelp Says date is pending, but when I used chat with customer care it says Dec 8th\n[SUPPORT] @332329 I'm sorry the delivery date is unavailable! Please keep an ...",training
6,2132842,"[CUSTOMER] @AmazonHelp Waited in all day for a guaranteed Prime Delivery that hasn't arrived, this is the 2nd time in a row this has happened, a courier problem maybe? Not good is it!\n[SUPPORT] @627584 So sorry for the delay! We do deliver until 21:00 so let us know if it doesn't arrive by then! ^AD\n[CUSTOMER] @AmazonHelp Don't think its coming, do you? https://t.co/88dDAhk5yb\n[CUSTOMER] @AmazonHelp @627584 My tracker has changed to that now, yet the order details page STILL states that i...",training
7,2289374,[CUSTOMER] アマゾンの会員登録しました！！！\n[SUPPORT] @665098 リプライ失礼いたします、Amazonです。プライムのご登録ありがとうございます！\nプライムビデオやプライムミュージックなど、さまざまな特典をご用意しておりますので、ぜひご活用くださいませ🙇 https://t.co/AbfeovjCgG HM\n[CUSTOMER] @AmazonHelp プライム登録はしてません…すいません…\n[SUPPORT] @665098 すみません、こちらこそ早とちりをしてしまい・・🙇🙏\n機会がございましたら、プライムもご検討くださいませ！HM,training
8,1514342,"[CUSTOMER] Effarant le nombre de loupés de distribution de @14967 ! Plus jamais ça lors de mes commandes @120533 ! Vivent les points relais !\n[SUPPORT] @471369 Bonjour, rencontrez-vous un problème avec une livraison en cours?^FT",training
9,42989,"[CUSTOMER] @117086 avisem pros entregadores de vocês que é feio jogar livro na garagem dos outros quando não tem ninguém em casa\n[SUPPORT] @125530 Olá Hellen! Sinto muito pelo acontecido. O seu pedido chegou danificado? ^JJ\n[CUSTOMER] @AmazonHelp Felizmente, não. Mas faz eu pensar duas vezes antes de comprar de novo algo\n[SUPPORT] @125530 Hellen, neste caso o pedido foi enviado pela Amazon ou por um vendedor?. ^NB\n[CUSTOMER] @AmazonHelp Pela Amazon\n[SUPPORT] @125530 Agradecemos o seu f...",training
10,1345839,"[CUSTOMER] Kann mir jemand einen Kuchen bringen, während ich auf den Kurier warte, der heute angeblich meine @116316-Rücksendung holt? #langwelig\n[SUPPORT] @433820 🍰\nHast du ein Zeitfenster zur Abholung bekommen? ^SM\n[CUSTOMER] @AmazonHelp Nein. Der Händler schreibt nur extrem unverständliches Deutsch oder Spanisch (was ich nicht kann), behauptet aber, da kommt heute jemand.\n[CUSTOMER] @AmazonHelp Er nannte weder Zeitfenster noch Dienstleister, leider hab ich auch von Amazon (also euch) ...",training
11,2311266,[CUSTOMER] I may be filing my first @115821 complaint ever. Seller has two days to get back to me . . .\n[SUPPORT] @670309 I'm sorry to hear there's been trouble with a recent order! Please keep us updated on the response from the seller. ^LR,training
12,944864,"[CUSTOMER] @AmazonHelp Bonjour j'ai commandé un colis le 15/10, selon le suivi de la commande, il est censé avoir été livré, mais je n'ai rien reçu..\n[SUPPORT] @344046 Bonjour, désolée pour cela. L'avez-vous signalé à notre SAV ? ^MA\n[CUSTOMER] @AmazonHelp Non, je ne l'ai pas signalé, pouvez-vous m'indiquer la démarche à suivre svp?\n[SUPPORT] @344046 Vous pouvez joindre le service client via ce lien : https://t.co/hgIrz98cdI ^MA\n[CUSTOMER] @AmazonHelp Je vais les contacter tout de suite,...",training
13,2970635,"[CUSTOMER] Delighted with our latest new arrival (from @115833) some teething problems at first, but everyone doing fine now. #alexa\n[SUPPORT] @819386 Great to hear! Enjoy! ^BL",training
14,244675,"[CUSTOMER] @115850 refund not initiated for 407-8896957-4238760. Got reply saying product is used.Please initiate refund,as product is not effective\n[SUPPORT] @174119 We regret for the inconvenience caused. Please reach out to our support team here: https://t.co/vlvfJr4nN9. 1/3^SB\n[CUSTOMER] @AmazonHelp rched out to support team.No response its been 2 weeks.return not initiated and now I am getting mails with sily excuses dat product is usd\n[SUPPORT] @174119 Please share your details from...",training
15,1165345,"[CUSTOMER] Bin krank und brauch Vorschläge, was man gucken kann. @22687 @115825\n[CUSTOMER] @394106 In welche Richtung soll es denn gehen?\n[CUSTOMER] @115825 mhhh.. nichts allzu hektisches :D\n[CUSTOMER] @394106 Wie ist dein Bayrisch so? ;-) Schau mal hier: https://t.co/DvlzykfC6Q. Garantiert nicht hektisch. Wünschen gute Besserung.\n[CUSTOMER] @115825 Musste letztens bei ner anderen bayrischen Serie deutsche Untertitel anschalten 😅Mal sehen.\n[SUPPORT] @394106 Jetzt hast du ja ein bißchen ...",training
16,2061685,"[CUSTOMER] Ordered a new phone from amazon got an one plus 5 instead of one plus 5 T due to some glitch ,the amazon guys are not willing to exchange what to do same product price @115821\n[SUPPORT] @609726 That was unexpected. We'd like to make this right for you. Kindly drop your details here: https://t.co/beaaDm0muc and we’ll get in touch with you soon. ^BV\n[CUSTOMER] @AmazonHelp Do I get my one plus 5T instead of the one plus 5 sent to me ? @AmazonHelp\n[SUPPORT] @609726 May I know if yo...",training
17,1171343,"[CUSTOMER] Nice to see that in order to make Prime look worthwhile @115821 now delays shipping your items for 2 days!!\n[SUPPORT] @395486 Sorry about the delay, Chris! You can check out how we calculate shipping times here: https://t.co/ggkD1YtmT8 ^LS\n[CUSTOMER] @AmazonHelp Nice try, @115821 you still use canada post but instead of the items shipped the next day you wait 3-4 days before sending!\n[CUSTOMER] @395486 @AmazonHelp @115821 Canada Post can get it there in 2 days if Amazon actuall...",training
18,1125079,"[CUSTOMER] @115850 If you cant honor orders, stop taking orders and then cancelling it once we lose opportunity to buy from your competitor!! Check OrderId 407-3570338-2876318 and 407-8674147-6797957. Get mature to do business !!\n[SUPPORT] @385288 Apologies for the experience you had with this order. Please report this to our support team here: https://t.co/vlvfJr4nN9 and we'll contact you soon. (1/2) ^JS\n[SUPPORT] @385288 Please don't provide your order details, we consider it to be perso...",training
19,2178028,[CUSTOMER] @86289 still waiting on my book ordered may 27th...amazon say it’s on the way...will be 110 by the time it gets here\n[SUPPORT] @638374 Sorry to hear of the delay with your order. Did you receive an email with info on the estimated delivery date?^ES\n[CUSTOMER] @AmazonHelp Yes October 4\n[CUSTOMER] @AmazonHelp Ordered 2 copies of Jim mellons book last May 27...awful\n[CUSTOMER] @AmazonHelp Just went back into my account and it says it will be with me on Saturday\n[CUSTOMER] @Amazo...,training
20,2883351,"[CUSTOMER] @AmazonHelp hola! Tengo dudas sobre la talla! Yo tengo el 6UK pero no me queda claro según la guía de tallas... Converse Chuck Taylor All Star Ox, Zapatillas de Lona, Unisex, Blanco (Optical White), 39 https://t.co/8e8iaKHVwb\n[SUPPORT] @699162 Hola Nuria, lamento el inconveniente. ¿Podrías informarme exactamente qué no te queda claro según nuestra tabla de tallas? ^AZ\n[CUSTOMER] @AmazonHelp Si miro la talla de mujer pone que 6UK es el 39,5 y si miro hombre, pone q el 6UK es el 3...",training
21,318073,"[CUSTOMER] @115850 How wonderful it feels to inform you that my package supposed to be deliverd by 8 pm yestrday has still to reach me at 14:40 today\n[SUPPORT] @184608 Kindly bear with us and you shall receive an update soon. ^HT\n[CUSTOMER] @AmazonHelp 4 chats, 3 emails and 8 tweets and thats all you can do ? #CourierCentric and not #customercentric",training
22,1533714,"[CUSTOMER] @115821 @115851 When did free 2 day Prime deliveries become 3 or more? This makes me 😠 that I’m paying for Prime and not getting 2 day 📦\n[SUPPORT] @475639 (1/2) Hello Kathy! Two-Day Shipping refers to transit time, in business days, once the order has been shipped.\n[SUPPORT] @475639 (2/2) You can locate more details regarding our shipping options here: https://t.co/pLtGoQ2gvG ^RM\n[CUSTOMER] @AmazonHelp Haven’t had problems with delivery until the last 6 months 🤔. Ordering said,...",training

In [257]:
print(
    "Training CSV rows:",
    len(training_benchmark)
)

print(
    "Training missing labels:",
    training_benchmark["intent_label"].isna().sum()
)

print(
    "Training label counts:"
)

display(
    training_benchmark["intent_label"].value_counts(
        dropna=False
    )
)

Training CSV rows: 300
Training missing labels: 297
Training label counts:

intent_label
NaN                297
DELIVERY_DELAY       2
PRODUCT_PROBLEM      1
Name: count, dtype: int64

In [258]:
# Show currently available notebook variables that may contain
# the labelled 300-example training set.

%whos DataFrame

Variable                            Type         Data/Info
----------------------------------------------------------
amazon                              DataFrame           conversation_id  \<...>[82246 rows x 15 columns]
amazon_conversations                DataFrame           conversation_id  \<...>[82246 rows x 14 columns]
amazon_resolution_corpus            DataFrame           conversation_id  \<...>[82246 rows x 16 columns]
amazon_retrieval_eval_corpus        DataFrame           conversation_id  \<...>[82096 rows x 16 columns]
amazonhelp_conversation_splits_v2   DataFrame           conversation_id  \<...>[82246 rows x 16 columns]
amazonhelp_splits                   DataFrame           conversation_id  \<...>[82246 rows x 17 columns]
annotation_batch                    DataFrame        conversation_id suppo<...>t there as well.  2 ^XS
audit_benchmark                     DataFrame                             <...>n\n[150 rows x 4 columns]
audit_eval                          DataFrame                             <...>\n[150 rows x 17 columns]
audit_lookup                        DataFrame           conversation_id  \<...>n[82246 rows x 2 columns]
audit_matches                       DataFrame           conversation_id  \<...>\n[150 rows x 16 columns]
audit_rows                          DataFrame           conversation_id  \<...>\n[150 rows x 17 columns]
audit_source                        DataFrame                             <...>n[1000 rows x 13 columns]
baseline_comparison                 DataFrame                             <...>     0.0  \n5       1.0
batch                               DataFrame         conversation_id  \\n<...>  NaN         UNLABELED
batch_1                             DataFrame                             <...>
batch_2                             DataFrame        conversation_id suppo<...>          NaN     human
batch_3                             DataFrame        conversation_id suppo<...>          NaN     human
batch_4                             DataFrame        conversation_id suppo<...>          NaN     human
batch_5                             DataFrame        conversation_id suppo<...>          NaN     human
batch_6                             DataFrame         conversation_id supp<...>          NaN     human
batch_7                             DataFrame         conversation_id supp<...>          NaN     human
brand_conversation_data             DataFrame                    support_a<...>[795131 rows x 9 columns]
brand_conversation_quality          DataFrame                     conversa<...>n\n[108 rows x 8 columns]
brand_customer                      DataFrame               customer_tweet<...>[702669 rows x 1 columns]
brand_customer_volume               DataFrame                     customer<...>n\n[108 rows x 1 columns]
brand_resolution                    DataFrame    resolution_label  ACTIONA<...>upport                4
brand_summary                       DataFrame                    support_t<...>n\n[108 rows x 6 columns]
brand_volume                        DataFrame                    support_t<...>n\n[108 rows x 3 columns]
bucket_df                           DataFrame          conversation_id  \\<...>\n[375 rows x 19 columns]
category_examples                   DataFrame              author_id  \\n3<...>310               False
cm_df                               DataFrame                     DELIVERY<...>       0                0
confusion                           DataFrame    Heuristic prediction     <...>                      1
conversation                        DataFrame          conversation_id  tw<...>headset works then. ^JS
conversation_brand_map              DataFrame                       suppor<...>[798197 rows x 3 columns]
conversation_stats                  DataFrame                     conversa<...>[798197 rows x 9 columns]
customer_brand_links                DataFrame             tweet_id respons<...>1166579 rows x 3 columns]
customer_tweets                     DataFrame             tweet_id author_<...>1537843 rows x 4 columns]
customer_with_responses             DataFrame             tweet_id author_<...>1303829 rows x 5 columns]
development_train                   DataFrame           conversation_id  \<...>[65678 rows x 16 columns]
development_validation              DataFrame           conversation_id  \<...>n[8213 rows x 16 columns]
df                                  DataFrame         conversation_id  \\n<...>\n[300 rows x 20 columns]
direction_summary                   DataFrame                          cou<...>omer  1273931       45.31
distribution                        DataFrame    intent_label   ACCOUNT_AC<...>                      0
distribution_pct                    DataFrame    intent_label   ACCOUNT_AC<...>               0.000000
errors                              DataFrame    Empty DataFrame\nColumns:<...>cted, correct]\nIndex: []
exceptions                          DataFrame             tweet_id  in_res<...>1117817 rows x 4 columns]
final_test                          DataFrame           conversation_id  \<...>n[8225 rows x 16 columns]
group                               DataFrame                             <...>\n[916 rows x 13 columns]
inspection_df                       DataFrame          conversation_id  tw<...>\n\n[73 rows x 6 columns]
intent_by_bucket                    DataFrame    size_bucket              <...>                      0
intent_counts                       DataFrame                             <...>CTIONS      2    1.333333
intent_discovery_sample             DataFrame                             <...>n[1000 rows x 13 columns]
label_summary                       DataFrame                         coun<...>            1        0.78
labeled_df                          DataFrame       conversation_id  \\n0 <...>messes up my deliveries
labeling_pool                       DataFrame          conversation_id  \\<...>n[1500 rows x 19 columns]
low_confidence                      DataFrame                             <...>0              0.173902
majority_report                     DataFrame                             <...>333  0.102411  150.000000
mapping_distribution                DataFrame                        conve<...>         3066        0.38
missing_summary                     DataFrame                             <...>  794335            28.25
multi_brand_examples                DataFrame                             <...>   2    multiple_brands
noted                               DataFrame                             <...>s the underlying issue.
outside_train                       DataFrame           conversation_id  \<...>tion               True
parent_order_check                  DataFrame             tweet_id  in_res<...>2013577 rows x 4 columns]
part                                DataFrame                             <...>azonHelp  9_plus_tweets
per_intent                          DataFrame                             <...>667  0.334454  150.000000
pilot                               DataFrame           conversation_id  \<...>\n[100 rows x 16 columns]
prediction_analysis                 DataFrame                             <...>AY     True    0.535609
rare_intents                        DataFrame                             <...>CTIONS      2        1.33
report_df                           DataFrame                             <...>333  0.281782  150.000000
resolution_conversations            DataFrame                    support_a<...>[192718 rows x 9 columns]
resolution_episodes                 DataFrame                             <...>192718 rows x 13 columns]
resolution_screening_annotations    DataFrame         conversation_id supp<...>\n[128 rows x 11 columns]
resolution_screening_sample         DataFrame         conversation_id supp<...>\n[128 rows x 12 columns]
resolution_summary                  DataFrame    resolution_category  ACTI<...>0                 58.99
resolution_support                  DataFrame             tweet_id    auth<...>339830 rows x 16 columns]
resolution_tweets                   DataFrame             conversation_id <...>[734046 rows x 6 columns]
retrieval_benchmark                 DataFrame         conversation_id  \\n<...>n\n[450 rows x 5 columns]
retrieved                           DataFrame           conversation_id  \<...>64  \n59904    0.757157
retrieved_rows                      DataFrame           conversation_id  \<...>8713              False
retrieved_safe                      DataFrame           conversation_id  \<...>      False    0.757157
root_tweets                         DataFrame             tweet_id  inboun<...>[798197 rows x 4 columns]
sample                              DataFrame           conversation_id  \<...>\n[375 rows x 16 columns]
sample_df                           DataFrame       tweet_id   author_id  <...>                   16.0
sampled                             DataFrame                             <...>                1613716
semantic_eval                       DataFrame                             <...>\n[150 rows x 18 columns]
single_brand_conversations          DataFrame                       suppor<...>[795131 rows x 4 columns]
split_df                            DataFrame           conversation_id  \<...>[82246 rows x 16 columns]
subset                              DataFrame                             <...>n[7610 rows x 13 columns]
support_messages                    DataFrame                  author_id  <...>1273931 rows x 3 columns]
support_tweet_lookup                DataFrame             support_account\<...>1273931 rows x 1 columns]
support_tweets                      DataFrame             tweet_id       a<...>1273931 rows x 4 columns]
support_with_parent                 DataFrame             tweet_id       a<...>1266942 rows x 5 columns]
taxonomy_audit                      DataFrame                             <...>\n[150 rows x 16 columns]
taxonomy_audit_df                   DataFrame                             <...>\n[150 rows x 16 columns]
temporal_check                      DataFrame             tweet_id  in_res<...>2013577 rows x 6 columns]
temporal_exceptions                 DataFrame             tweet_id  in_res<...>00                False
test                                DataFrame           conversation_id  \<...>n[8225 rows x 15 columns]
test_audit                          DataFrame           conversation_id  \<...>test               True
test_conversation                   DataFrame       tweet_id   author_id  <...> you propose we do that
test_pool                           DataFrame           conversation_id  \<...>n[8225 rows x 16 columns]
train                               DataFrame           conversation_id  \<...>[65796 rows x 15 columns]
train_pool                          DataFrame           conversation_id  \<...>[65678 rows x 16 columns]
training_batch                      DataFrame         conversation_id  \\n<...>\n[300 rows x 20 columns]
training_batch_1                    DataFrame         conversation_id  \\n<...>\n[300 rows x 20 columns]
training_benchmark                  DataFrame         conversation_id  \\n<...>n\n[300 rows x 4 columns]
training_df                         DataFrame         conversation_id  \\n<...>\n[300 rows x 21 columns]
twcs                                DataFrame             tweet_id   autho<...>811774 rows x 10 columns]
valid_temporal_rows                 DataFrame             tweet_id  in_res<...>2013577 rows x 6 columns]
validation                          DataFrame           conversation_id  \<...>n[8225 rows x 15 columns]
validation_pool                     DataFrame           conversation_id  \<...>n[8213 rows x 16 columns]
year_distribution                   DataFrame       year  tweet_count  per<...>      2809474       99.92

In [259]:
candidates = [
    "training_batch",
    "training_batch_1",
    "training_df",
    "labeled_df",
    "batch_1",
    "batch_2",
    "batch_3",
    "batch_4",
    "batch_5",
    "batch_6",
    "batch_7",
]

for name in candidates:
    if name in globals():
        obj = globals()[name]

        if isinstance(obj, pd.DataFrame):
            print(f"\n{name}")
            print("  Shape:", obj.shape)

            if "intent_label" in obj.columns:
                print(
                    "  Missing intent labels:",
                    obj["intent_label"].isna().sum()
                )
                print(
                    "  Unique labels:",
                    obj["intent_label"].nunique(dropna=True)
                )
                print(
                    "  Status:",
                    obj["annotation_status"].value_counts(dropna=False).to_dict()
                    if "annotation_status" in obj.columns
                    else "no annotation_status column"
                )
            else:
                print("  No intent_label column")

training_batch
  Shape: (300, 20)
  Missing intent labels: 300
  Unique labels: 0
  Status: {'UNLABELED': 300}

training_batch_1
  Shape: (300, 20)
  Missing intent labels: 300
  Unique labels: 0
  Status: {'UNLABELED': 300}

training_df
  Shape: (300, 21)
  Missing intent labels: 297
  Unique labels: 2
  Status: {'UNLABELED': 300}

labeled_df
  Shape: (3, 21)
  Missing intent labels: 0
  Unique labels: 2
  Status: {'UNLABELED': 3}

batch_1
  Shape: (30, 9)
  Missing intent labels: 0
  Unique labels: 1
  Status: no annotation_status column

batch_2
  Shape: (20, 11)
  No intent_label column

batch_3
  Shape: (20, 11)
  No intent_label column

batch_4
  Shape: (20, 11)
  No intent_label column

batch_5
  Shape: (20, 11)
  No intent_label column

batch_6
  Shape: (20, 11)
  No intent_label column

batch_7
  Shape: (8, 11)
  No intent_label column

In [260]:
for name in [
    "batch_1",
    "batch_2",
    "batch_3",
    "batch_4",
    "batch_5",
    "batch_6",
    "batch_7",
]:
    if name in globals():
        obj = globals()[name]

        print(f"\n{'=' * 60}")
        print(name)
        print("Shape:", obj.shape)
        print("Columns:")
        print(list(obj.columns))

============================================================
batch_1
Shape: (30, 9)
Columns:
['first_customer_message', 'last_customer_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'size_bucket', 'intent_label', 'annotation_notes']

============================================================
batch_2
Shape: (20, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

============================================================
batch_3
Shape: (20, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

============================================================
batch_4
Shape: (20, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

============================================================
batch_5
Shape: (20, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

============================================================
batch_6
Shape: (20, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

============================================================
batch_7
Shape: (8, 11)
Columns:
['conversation_id', 'support_account', 'size_bucket', 'conversation_size', 'customer_turns', 'support_turns', 'duration_minutes', 'conversation_text', 'resolution_label', 'annotation_notes', 'annotator']

In [261]:
# Restore the 300 previously completed human intent annotations.
# training_df is the original 300-row annotation batch in the same order
# used during our manual review.

intent_labels_300 = [
    # 0-29
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DIGITAL_CONTENT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "ORDER_STATUS_OR_CANCELLATION",
    "DELIVERY_DELAY",
    "PRIME_MEMBERSHIP",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "RETURN_REPLACEMENT_REFUND",
    "OTHER_NON_SUPPORT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DIGITAL_CONTENT",
    "RETURN_REPLACEMENT_REFUND",
    "DIGITAL_CONTENT",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "ORDER_STATUS_OR_CANCELLATION",
    "DELIVERY_DELAY",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "PAYMENT_BILLING",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",

    # 30-59
    "OTHER_NON_SUPPORT",
    "DIGITAL_CONTENT",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_PROBLEM",
    "OTHER_NON_SUPPORT",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "OTHER_NON_SUPPORT",
    "ORDER_STATUS_OR_CANCELLATION",
    "WEBSITE_APP_TECHNICAL",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRIME_MEMBERSHIP",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "PAYMENT_BILLING",
    "DELIVERY_DELAY",
    "PRIME_MEMBERSHIP",
    "DELIVERY_DELAY",
    "DEVICE_TECHNICAL_SUPPORT",
    "ORDER_STATUS_OR_CANCELLATION",
    "PRIME_MEMBERSHIP",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",

    # 60-89
    "PAYMENT_BILLING",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRIME_MEMBERSHIP",
    "DELIVERY_DELAY",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRODUCT_PROBLEM",
    "DEVICE_TECHNICAL_SUPPORT",
    "OTHER_NON_SUPPORT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "RETURN_REPLACEMENT_REFUND",
    "WEBSITE_APP_TECHNICAL",
    "PRODUCT_PROBLEM",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DEVICE_TECHNICAL_SUPPORT",
    "ORDER_STATUS_OR_CANCELLATION",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRIME_MEMBERSHIP",
    "DELIVERY_DELAY",
    "DEVICE_TECHNICAL_SUPPORT",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "ORDER_STATUS_OR_CANCELLATION",
    "OTHER_NON_SUPPORT",
    "PAYMENT_BILLING",
    "PRODUCT_PROBLEM",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",

    # 90-119
    "DELIVERY_DELAY",
    "ORDER_STATUS_OR_CANCELLATION",
    "OTHER_NON_SUPPORT",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DIGITAL_CONTENT",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "PAYMENT_BILLING",
    "OTHER_NON_SUPPORT",
    "ORDER_STATUS_OR_CANCELLATION",
    "WEBSITE_APP_TECHNICAL",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_DELAY",
    "PAYMENT_BILLING",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "OTHER_NON_SUPPORT",
    "GIFT_CARD_PROMOTION",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",

    # 120-149
    "RETURN_REPLACEMENT_REFUND",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_PROBLEM",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRODUCT_PROBLEM",
    "ACCOUNT_ACCESS_SECURITY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "OTHER_NON_SUPPORT",
    "ORDER_STATUS_OR_CANCELLATION",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_DELAY",
    "OTHER_NON_SUPPORT",
    "ACCOUNT_ACCESS_SECURITY",
    "DIGITAL_CONTENT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "OTHER_NON_SUPPORT",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRIME_MEMBERSHIP",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "ACCOUNT_ACCESS_SECURITY",
    "PRODUCT_PROBLEM",

    # 150-179
    "ACCOUNT_ACCESS_SECURITY",
    "PRODUCT_PROBLEM",
    "OTHER_NON_SUPPORT",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "PAYMENT_BILLING",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "WEBSITE_APP_TECHNICAL",
    "OTHER_NON_SUPPORT",
    "PRODUCT_PROBLEM",
    "DIGITAL_CONTENT",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_PROBLEM",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "OTHER_NON_SUPPORT",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "OTHER_NON_SUPPORT",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",

    # 180-209
    "OTHER_NON_SUPPORT",
    "RETURN_REPLACEMENT_REFUND",
    "ACCOUNT_ACCESS_SECURITY",
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRODUCT_PROBLEM",
    "WEBSITE_APP_TECHNICAL",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "ACCOUNT_ACCESS_SECURITY",
    "PRODUCT_PROBLEM",
    "WEBSITE_APP_TECHNICAL",
    "WEBSITE_APP_TECHNICAL",
    "PRODUCT_PROBLEM",
    "OTHER_NON_SUPPORT",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRODUCT_PROBLEM",
    "RETURN_REPLACEMENT_REFUND",
    "ORDER_STATUS_OR_CANCELLATION",
    "PAYMENT_BILLING",
    "PRODUCT_PROBLEM",
    "GIFT_CARD_PROMOTION",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "DELIVERY_MISSING_OR_MISDELIVERED",

    # 210-239
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PAYMENT_BILLING",
    "WEBSITE_APP_TECHNICAL",
    "PRODUCT_PROBLEM",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "GIFT_CARD_PROMOTION",
    "DELIVERY_DELAY",
    "DIGITAL_CONTENT",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRIME_MEMBERSHIP",
    "DELIVERY_DELAY",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRODUCT_PROBLEM",

    # 240-269
    "DIGITAL_CONTENT",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRODUCT_PROBLEM",
    "WEBSITE_APP_TECHNICAL",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "RETURN_REPLACEMENT_REFUND",
    "ACCOUNT_ACCESS_SECURITY",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DIGITAL_CONTENT",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "OTHER_NON_SUPPORT",
    "OTHER_NON_SUPPORT",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "ORDER_STATUS_OR_CANCELLATION",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "ORDER_STATUS_OR_CANCELLATION",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DIGITAL_CONTENT",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_DELAY",

    # 270-299
    "PAYMENT_BILLING",
    "PRODUCT_PROBLEM",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PRODUCT_PROBLEM",
    "RETURN_REPLACEMENT_REFUND",
    "DELIVERY_DELAY",
    "RETURN_REPLACEMENT_REFUND",
    "OTHER_NON_SUPPORT",
    "GIFT_CARD_PROMOTION",
    "DELIVERY_DELAY",
    "DIGITAL_CONTENT",
    "PRODUCT_PROBLEM",
    "DIGITAL_CONTENT",
    "ACCOUNT_ACCESS_SECURITY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "PAYMENT_BILLING",
    "PRODUCT_PROBLEM",
    "ACCOUNT_ACCESS_SECURITY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "OTHER_NON_SUPPORT",
    "DELIVERY_DELAY",
    "DELIVERY_DELAY",
    "PRODUCT_PROBLEM",
    "GIFT_CARD_PROMOTION",
    "ORDER_STATUS_OR_CANCELLATION",
]

# Safety checks before assigning anything
assert len(intent_labels_300) == 300
assert len(training_df) == 300

# Verify the first three IDs against the previously reviewed examples.
expected_first_ids = [373303, 282739, 2292312]

actual_first_ids = (
    training_df["conversation_id"]
    .astype(int)
    .head(3)
    .tolist()
)

assert actual_first_ids == expected_first_ids, (
    f"Unexpected training order: {actual_first_ids}"
)

# Restore labels
training_df = training_df.copy()
training_df["intent_label"] = intent_labels_300
training_df["annotation_status"] = "LABELED"

print("Rows:", len(training_df))
print(
    "Unique conversation IDs:",
    training_df["conversation_id"].nunique()
)
print(
    "Missing labels:",
    training_df["intent_label"].isna().sum()
)
print(
    "Unique intent labels:",
    training_df["intent_label"].nunique()
)
print(
    "Annotation status:",
    training_df["annotation_status"].value_counts().to_dict()
)

Rows: 300
Unique conversation IDs: 300
Missing labels: 0
Unique intent labels: 15
Annotation status: {'LABELED': 300}

In [262]:
# Replace the broken training_benchmark with the verified
# 300-example labelled dataframe.

training_benchmark = training_df[
    [
        "conversation_id",
        "conversation_text",
        "intent_label",
    ]
].copy()

training_benchmark["benchmark_source"] = "training"


# Rebuild the 150-example audit benchmark.
audit_lookup = amazon_resolution_corpus[
    [
        "conversation_id",
        "conversation_text",
    ]
].copy()

audit_benchmark = taxonomy_audit_df[
    [
        "conversation_text",
        "intent_label",
    ]
].copy()

audit_benchmark = audit_benchmark.merge(
    audit_lookup,
    on="conversation_text",
    how="left",
    validate="one_to_one",
)

audit_benchmark["benchmark_source"] = "taxonomy_audit"


# Combine the two labelled benchmark sets.
retrieval_benchmark = pd.concat(
    [
        training_benchmark,
        audit_benchmark[
            [
                "conversation_id",
                "conversation_text",
                "intent_label",
                "benchmark_source",
            ]
        ],
    ],
    ignore_index=True,
)

retrieval_benchmark["conversation_id"] = (
    retrieval_benchmark["conversation_id"].astype(int)
)


# Final validation.
print("Total retrieval queries:", len(retrieval_benchmark))
print(
    "Unique query conversations:",
    retrieval_benchmark["conversation_id"].nunique()
)
print(
    "Missing conversation IDs:",
    retrieval_benchmark["conversation_id"].isna().sum()
)
print(
    "Missing intent labels:",
    retrieval_benchmark["intent_label"].isna().sum()
)
print(
    "Unique intent labels:",
    retrieval_benchmark["intent_label"].nunique()
)

print("\nBenchmark source:")
print(
    retrieval_benchmark["benchmark_source"].value_counts()
)

print("\nIntent distribution:")
print(
    retrieval_benchmark["intent_label"].value_counts()
)

Total retrieval queries: 450
Unique query conversations: 450
Missing conversation IDs: 0
Missing intent labels: 0
Unique intent labels: 15

Benchmark source:
benchmark_source
training          300
taxonomy_audit    150
Name: count, dtype: int64

Intent distribution:
intent_label
DELIVERY_DELAY                      107
OTHER_NON_SUPPORT                    66
PRODUCT_PROBLEM                      49
DELIVERY_MISSING_OR_MISDELIVERED     45
RETURN_REPLACEMENT_REFUND            33
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     26
ORDER_STATUS_OR_CANCELLATION         20
DIGITAL_CONTENT                      19
PAYMENT_BILLING                      16
PRODUCT_AVAILABILITY_INFORMATION     15
ACCOUNT_ACCESS_SECURITY              14
PRIME_MEMBERSHIP                     13
WEBSITE_APP_TECHNICAL                13
DEVICE_TECHNICAL_SUPPORT              7
GIFT_CARD_PROMOTION                   7
Name: count, dtype: int64

In [263]:
retrieval_benchmark["customer_only_text"] = (
    retrieval_benchmark["conversation_text"]
    .fillna("")
    .map(extract_customer_only)
)

print("Empty customer queries:",
      retrieval_benchmark["customer_only_text"].eq("").sum())

print(
    "Average query length:",
    retrieval_benchmark["customer_only_text"].str.len().mean()
)

print(
    "Median query length:",
    retrieval_benchmark["customer_only_text"].str.len().median()
)

display(
    retrieval_benchmark[
        [
            "conversation_id",
            "intent_label",
            "benchmark_source",
            "customer_only_text",
        ]
    ].head(5)
)

Empty customer queries: 0
Average query length: 461.38666666666666
Median query length: 275.5

,conversation_id,intent_label,benchmark_source,customer_only_text
0,373303,DELIVERY_DELAY,training,"I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +\n[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then."
1,282739,PRODUCT_PROBLEM,training,"@115821 Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer. @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered gl..."
2,2292312,DELIVERY_DELAY,training,@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY. @AmazonHelp No it's the stupid post office that always messes up my deliveries
3,570075,DIGITAL_CONTENT,training,Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)
4,1427974,DELIVERY_MISSING_OR_MISDELIVERED,training,@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check @AmazonHelp Thank you for quick response @AmazonHelp One more product defaulted..Today I received a msg as delivered bt it was nt delivered to me.Pls check\n[CUSTOMER] @AmazonHelp This is a serious fraud issue.Can u share the details of customer wh is taking my order n signing on ...

In [264]:
benchmark_query_embeddings = embedding_model.encode(
    retrieval_benchmark["customer_only_text"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(
    "Query embedding shape:",
    benchmark_query_embeddings.shape
)

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

Query embedding shape: (450, 384)

In [265]:
# Final leakage-safe retrieval corpus.
# Exclude all 450 labelled benchmark conversations:
# 300 training + 150 taxonomy audit.

benchmark_conversation_ids = set(
    retrieval_benchmark["conversation_id"].astype(int)
)

amazon_retrieval_benchmark_corpus = (
    amazon_resolution_corpus[
        ~amazon_resolution_corpus["conversation_id"].isin(
            benchmark_conversation_ids
        )
    ]
    .copy()
    .reset_index(drop=True)
)

print("Original AmazonHelp corpus:",
      len(amazon_resolution_corpus))

print("Benchmark conversations excluded:",
      len(benchmark_conversation_ids))

print("Final retrieval corpus:",
      len(amazon_retrieval_benchmark_corpus))

print("Unique conversation IDs:",
      amazon_retrieval_benchmark_corpus["conversation_id"].nunique())

# Hard leakage check
remaining_ids = set(
    amazon_retrieval_benchmark_corpus["conversation_id"].astype(int)
)

leaked_ids = benchmark_conversation_ids & remaining_ids

print("Leaked benchmark conversations:",
      len(leaked_ids))

assert len(amazon_retrieval_benchmark_corpus) == 81796
assert amazon_retrieval_benchmark_corpus["conversation_id"].nunique() == 81796
assert len(leaked_ids) == 0

print("✓ Final leakage-safe retrieval corpus validated.")

Original AmazonHelp corpus: 82246
Benchmark conversations excluded: 450
Final retrieval corpus: 81796
Unique conversation IDs: 81796
Leaked benchmark conversations: 0
✓ Final leakage-safe retrieval corpus validated.

In [266]:
# Build the final leakage-safe FAISS index.

benchmark_retrieval_texts = (
    amazon_retrieval_benchmark_corpus["retrieval_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

print(
    "Retrieval documents:",
    len(benchmark_retrieval_texts)
)

benchmark_resolution_embeddings = embedding_model.encode(
    benchmark_retrieval_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(
    "Embedding shape:",
    benchmark_resolution_embeddings.shape
)

faiss_index_benchmark = faiss.IndexFlatIP(
    benchmark_resolution_embeddings.shape[1]
)

faiss_index_benchmark.add(
    benchmark_resolution_embeddings.astype("float32")
)

print(
    "FAISS index size:",
    faiss_index_benchmark.ntotal
)

print(
    "FAISS dimension:",
    faiss_index_benchmark.d
)

assert faiss_index_benchmark.ntotal == 81796

print("✓ Leakage-safe FAISS index ready.")

Retrieval documents: 81796

Batches:   0%|          | 0/1279 [00:00<?, ?it/s]

Embedding shape: (81796, 384)
FAISS index size: 81796
FAISS dimension: 384
✓ Leakage-safe FAISS index ready.

In [267]:
# Encode the 450 labelled benchmark queries.
# Queries contain customer messages only.

benchmark_query_embeddings = embedding_model.encode(
    retrieval_benchmark["customer_only_text"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(
    "Query embedding shape:",
    benchmark_query_embeddings.shape
)

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

Query embedding shape: (450, 384)

In [268]:
# Retrieve the top 10 unseen historical conversations
# for every benchmark query.

TOP_K = 10

benchmark_scores, benchmark_indices = (
    faiss_index_benchmark.search(
        benchmark_query_embeddings.astype("float32"),
        TOP_K,
    )
)

print("Scores shape:", benchmark_scores.shape)
print("Indices shape:", benchmark_indices.shape)

Scores shape: (450, 10)
Indices shape: (450, 10)

In [269]:
# Inspect retrieval results for 10 benchmark queries.

for query_idx in range(10):
    
    query_row = retrieval_benchmark.iloc[query_idx]
    
    print("\n" + "=" * 100)
    print(
        f"QUERY {query_idx + 1} | "
        f"ID={query_row['conversation_id']} | "
        f"INTENT={query_row['intent_label']} | "
        f"SOURCE={query_row['benchmark_source']}"
    )
    
    print("\nCUSTOMER QUERY:")
    print(query_row["customer_only_text"][:1000])
    
    print("\nTOP RETRIEVED:")
    
    retrieved_rows = amazon_retrieval_benchmark_corpus.iloc[
        benchmark_indices[query_idx]
    ]
    
    for rank, (_, row) in enumerate(
        retrieved_rows.iterrows(),
        start=1
    ):
        print(
            f"\n[{rank}] "
            f"similarity={benchmark_scores[query_idx][rank-1]:.4f} "
            f"conversation_id={row['conversation_id']} "
            f"size={row['conversation_size']}"
        )
        
        print(
            row["conversation_text"][:700]
            .replace("\n", " ")
        )

====================================================================================================
QUERY 1 | ID=373303 | INTENT=DELIVERY_DELAY | SOURCE=training

CUSTOMER QUERY:
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue +
[CUSTOMER] @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.

TOP RETRIEVED:

[1] similarity=0.7785 conversation_id=218089 size=2
[CUSTOMER] If you have problems with your @115821 same day delivery, @2150 might be involved. LMAO. https://t.co/Mq883LdLpi [SUPPORT] @167995 Hi! Are you currently experiencing an issue with an order? We'd like to help! ^WT

[2] similarity=0.7785 conversation_id=339472 size=2
[CUSTOMER] It's really frustrating trying to order things through @115821 lately. They seem to screw up shipment and delivery every time. [SUPPORT] @197062 This isn't what we like to hear! Are you currently having an issue? If so, can you give us more info? We're here for you! ^KJ

[3] similarity=0.7695 conversation_id=1779344 size=3
[CUSTOMER] Very disappointed with @115821 today. Marked item as failed to deliver but no delivery was even attempted. Now delayed even with @AmazonHelp [SUPPORT] @534614 I'm sorry to hear we've let you down, Micael! Have you been provided a new delivery date for the order? ^CS [CUSTOMER] @AmazonHelp Yap, tomorrow; but specifically wanted it today. Cancelled, bought and collected from @116245. Sorry @AmazonHelp, maybe next time.

[4] similarity=0.7616 conversation_id=1332627 size=3
[CUSTOMER] @115821 what's up with customer service!  Paid extra to get something here and was told it would be..2 days later than I needed it. [SUPPORT] @430880 I'm sorry for the poor experience! Were we able to offer any other information about this when you had reached out to us? ^KJ [CUSTOMER] @AmazonHelp After 3 calls, my order might be here today...not just 1 order I am have had issues with.  That's my problem.

[5] similarity=0.7581 conversation_id=2408738 size=2
[CUSTOMER] I just want to say that @115821 is amazing. I've had a few problems and their customer service is unrivaled. Shout out to @AmazonHelp and everyone on their team. My dollars support Amazon. [SUPPORT] @692621 Thank you, Amar! We're glad to help :) ^SM

[6] similarity=0.7545 conversation_id=260796 size=3
[CUSTOMER] I've always loved @115821 but come on! That's not what I ordered😒 @AmazonHelp @115830 https://t.co/fWFz2Aqati [SUPPORT] @178089 Zoinks! That wasn't supposed to happen! Was this dispatched from us or one of our sellers? Let us know, we'd love to help. ^SA [CUSTOMER] @AmazonHelp @178089 zoinks!

[7] similarity=0.7537 conversation_id=1301795 size=2
[CUSTOMER] Haven't been having the best luck with @115821 lately. Second delivery not being made within a week [SUPPORT] @424234 I'm sorry for the delivery issues, Jennifer! Who was the carrier of your orders? Pls check here: https://t.co/Y5jpI9ys9c ^FD

[8] similarity=0.7508 conversation_id=2646246 size=2
[CUSTOMER] I'm really getting tired of @115821 sending me used items when I pay for new. This has happened at least 4 times out of the last 6 orders. [SUPPORT] @169608 I'm sorry for this issue with your recent orders. Were they shipped and sold by Amazon or Third-Party sellers: https://t.co/Y5jpI9gRhE? ^DO

[9] similarity=0.7507 conversation_id=859626 size=2
[CUSTOMER] Don't waste your time with @115821. Go to a local business if you can. Amazon can't even deliver a package. Waste of money. [SUPPORT] @324103 I'm sorry to hear about the delivery issue. We'd like to help! W/out giving account info can you tell us what happened? ^JF

[10] similarity=0.7506 conversation_id=1149614 size=2
[CUSTOMER] The @115821 in house shipping service sucks more than usual today. [SUPPORT] @390532 Sorry for your delivery experience w/ us! A specialist will reach out to you personally: https://t.co/Feq2Z8zRUY ^JZ

====================================================================================================
QUERY 2 | ID=282739 | INTENT=PRODUCT_PROBLEM | SOURCE=training

CUSTOMER QUERY:
@115821  Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer. @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered glass is available for merely Rs 100 per piece. Yet I bought Netboon at Rs 1800. I did not buy from Netboon. Who  is Netbeen ? Nobody know. I bought from Amazon. @115937 @118702 @AmazonHelp Amazon- Have the Netboon order &amp; Refusal to help. If tempered glass falls off on its own, is a quality issue. I did not buy from Netboon. I bought Netboon product from Amazon. Please resolve my concern. @115937 @118702 https://t.co/G6PkbmqPTF @AmazonHelp where is the service center of Netboon???????
[CUSTOMER]

TOP RETRIEVED:

[1] similarity=0.6653 conversation_id=379293 size=5
[CUSTOMER] @115850 Ordrd phone during sale.temp glass on it, with scratches, looks like 2nd had product. Want a replacement.Cant contact seller [SUPPORT] @206004 Apologies for the trouble you've had with the order.1/2 ^MM [SUPPORT] @206004 Have you escalated this to our support team here: https://t.co/2t6DQoUmNZ for assistance? 2/2 ^MM [CUSTOMER] @AmazonHelp Yes I have, when can I expect a response on the same from your side [SUPPORT] @206004 Thank you. Our support team will work on the issue and get in touch with you at the earliest. ^NS

[2] similarity=0.6569 conversation_id=298481 size=8
[CUSTOMER] @115850 for my new 1+5 ordered temper glass on 4/8/17 vide order  405-6620277-8785136.Defective tempered glass sold placed d return 1/2 [CUSTOMER] @115850 Return not accepted,absolutely no adhesive was there in d tempered glass which makes d order meaningless.replace d defective product asap [SUPPORT] @187119 We apologize for the inconvenience. Could you confirm if you've contact our support team here: https://t.co/vlvfJr4nN9? ^ZH [CUSTOMER] @AmazonHelp Yes contacted but no reply was received, again used d link &amp; further highlightedabout d defective tempered glass.pls liveup to ur reputation [SUPPORT] @187119 Sorry to know about the issue with your order. Please contact us her

[3] similarity=0.6357 conversation_id=1438620 size=7
[CUSTOMER] Bought @80464  pro fit tempered glass for my  #OnePlus5 from @115850 and see what I received. https://t.co/jUC4KVuYPL [SUPPORT] @453867 I'm sorry you received a damaged product. Kindly report this to our support team here: https://t.co/rS49hgaADF 1/2^SC [SUPPORT] @453867 so that we can fix this for you. 2/2^SC [CUSTOMER] @AmazonHelp I've already reported the issue on your customer service. Let's see what will happen next. [CUSTOMER] @AmazonHelp Was Really excited about the Orzly tempered glass. Heard a lot about it 😞 [SUPPORT] @453867 Sorry about that. Please be assured our support team will sort this out for you. ^PB [SUPPORT] @453867 That's unexpected! As you've contacted our su

[4] similarity=0.6292 conversation_id=1341617 size=13
[CUSTOMER] @115850 really disappointed now. No refund for faulty part. 😞😞 https://t.co/BgH7Wgf9MF [SUPPORT] @432926 Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. (2/2) ^SV [SUPPORT] @432926 Sorry to know you're facing issues with your order. Please reach us from here: https://t.co/DasOQYSu9v we'll assist. (1/2) ^SV [CUSTOMER] @AmazonHelp I did not get support from your customer service team when called. They said window is closed but its still open as per me. [CUSTOMER] @AmazonHelp Need support from amazon for either replacement of order or refund. [SUPPORT] @432926 If an item is out of the return window, we would n't be

[5] similarity=0.5869 conversation_id=669214 size=6
[CUSTOMER] @115850 Just got the parcel delivered. I was surprised to got this. Shame on you. Ordered tempered glass and instead received broken and used products. Very disappointing and disgraceful https://t.co/OEiTSHRVE0 [SUPPORT] @182582 Sorry to know you received damaged item, we certainly didn't expect this to happen. Kindly report this to our support team here: https://t.co/TdDksLo6Mf. We'll definitely help you. ^PS [CUSTOMER] @AmazonHelp under your policy, it is showing this item is not eligible for a refund [SUPPORT] @182582 I understand it is a non-returnable item. Kindly connect with our support team here: https://t.co/FICxLgJUB5 and we'll help you with the issue. ^SH [CUSTOMER] @Am

[6] similarity=0.5853 conversation_id=2690697 size=7
[CUSTOMER] @115830 You sent me a cheaper alternative product not described as advertised. Now your telephone operative has had me on hold - total silence for 10 mins. Great customer service! [SUPPORT] @756425 Oh goodness! I'm sorry to hear that the product didn't arrive as expected. Keep us updated on how the phone call goes. ^AB [CUSTOMER] @115830 @115830 Ordered glass jar 'MeyKey'blender rrp £99 you sent me a plastic 'Homdox' rrp £55 Call abandoned by your customer service rep #TerribleCustomerService #Missadvertisement Can't wait to complain by email about this @115851 [CUSTOMER] 25mins on hold - total silence. Think it's time I hung up and called back now @115830 @115851 #TerribleCustome

[7] similarity=0.5833 conversation_id=2537453 size=2
[CUSTOMER] I ordered a high quality tempered glass to protect my screen from cracking from @115850. But what does one do if the glass itself is delivered cracked??? @159079 https://t.co/0CUPVeyMD9 [SUPPORT] @721754 Sorry to know about the delivery issue. This isn't the kind of service we would want our customers to experience. Kindly report the issue to our support team here: https://t.co/00q4Sqj9zL for assistance ^AR

[8] similarity=0.5793 conversation_id=390816 size=3
[CUSTOMER] @115850  __email__ You deliver wrong tempered glass it's not suit on my mobile screen. [SUPPORT] @208528 Sorry about that, please report that here: https://t.co/HQhpS2qeEd and our team will get this sorted. ^MS [SUPPORT] @208528 Please don’t provide your order details as it is personal information. Our Twitter page is visible to the public. ^MS

[9] similarity=0.5788 conversation_id=147339 size=3
[CUSTOMER] @115850 i got screen gaurd delivered today, it was sealed in good shipment however, to my amaze, inside it was broken glass. Is it failure of quality procedure or intended as customer won't have clue thereafter. Anyway I am returning it [SUPPORT] @149475 Sorry to know that you've received a defective product. Believe me, this isn't what we intended. Please provide your feedback via Packaging Feedback Program here: https://t.co/BOC2qI06T6. (1/2) ^KA [SUPPORT] @149475 Your input will help us improve product and Amazon packaging. We always appreciate customer input on how we can improve our services. (2/2) ^KA

[10] similarity=0.5726 conversation_id=2475997 size=10
[CUSTOMER] @115821   Experiencing the worst e-marketing with you people. As your logo explains.. A to Z ... Exactly same way the tempered glass i had ordered recently had a clear crack running from the Ath corner to Zth. And now the memory card repacked with tape putting lot of efforts. 🤣 [SUPPORT] @707783 Hi Samuel, I'm sorry to hear that your order arrived damaged. Did you reach out to us directly to see if we can arrange either a replacement or a refund? ^KI [CUSTOMER] @AmazonHelp That is the obvious thing i can do at the end to save my money sir. But whats the meaning of all this? This is not first time sir.. Do i need to do this everytime i transact with you people? [SUPPORT] @707783 Hi

====================================================================================================
QUERY 3 | ID=2292312 | INTENT=DELIVERY_DELAY | SOURCE=training

CUSTOMER QUERY:
@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY. @AmazonHelp No  it's the stupid post office that always messes up my deliveries

TOP RETRIEVED:

[1] similarity=0.8883 conversation_id=2480947 size=3
[CUSTOMER] @AmazonHelp why does prime 2 day shipping take 5 days to arrive? We pay for prime for fast delivery right? But we dont get it. [SUPPORT] @470885 I'm sorry for the trouble! Two-Day shipping refers to transit time, in business days, once shipped: https://t.co/x6DaIpAB5H ^EB [CUSTOMER] @AmazonHelp So your saying it could take MONTHS.. but as long as its 2 days in shipping counts as 2 day shipping... kida fucked up. I guess i wont renew

[2] similarity=0.8843 conversation_id=759758 size=3
[CUSTOMER] @115821 Why does my Prime shipping now seem to take 4 days to two weeks? If I can’t get it in 2 days don’t tell me it’s Prime eligible! 😡😡 [SUPPORT] @301536 Two-Day Shipping refers to the transit time in business days, once an item ships. More info here: https://t.co/bMtwK35Sm0 ^VS [CUSTOMER] @AmazonHelp Ordered on the 5th, shipped on the 8th, and ETA is anywhere from the 17th to the 24th. But thanks for the patronizing reply.

[3] similarity=0.8834 conversation_id=2969493 size=2
[CUSTOMER] @AmazonHelp Why do I pay for Prime with 2-day shipping, and then order something and it tells me it will be 6 days? [SUPPORT] @237243 I'm sorry for the trouble! Prime Two-Day shipping refers to the transit time, in business days, once the item has shipped: https://t.co/x6DaIpAB5H. Have we missed the delivery date provided at checkout on a recent order? ^VB

[4] similarity=0.8794 conversation_id=1335108 size=4
[CUSTOMER] @115821 Signed up for Prime for 2-day shipping. Had to cancel 2 items because they would NOT be shipped in two days! What a rip off! [SUPPORT] @431445 Two-Day Shipping refers to the transit time after the item ships. Did we miss the delivery date provided at checkout? ^GR [CUSTOMER] @AmazonHelp Yes, by several days. [CUSTOMER] @AmazonHelp One item is arriving today but without the other items, it's useless.

[5] similarity=0.8776 conversation_id=2905172 size=3
[CUSTOMER] @AmazonHelp Why is my 2 day prime shipping taking over a week. Order today with 2 day shipping says I'll get it Wed Dec 6th!? How is that right? [SUPPORT] @804516 Two-Day Shipping refers to transit time in business days after your order ships. Some orders need extra time to process &amp; handle before shipping. We aim to meet the date given to you in your confirmation e-mail. You can view more here: https://t.co/k0n2EI7aEw ^KP [CUSTOMER] @AmazonHelp I have just never seen it take this long. Usually it literally is in 2 days. I tried ordering yesterday and said it would take a week. Kinda disappointed in that. Not something I can wait that long for. Hence why I have prime membershi

[6] similarity=0.8753 conversation_id=712472 size=2
[CUSTOMER] @AmazonHelp why am I paying for prime 2 day shipping if it actually takes 4-5 days to come in? Whatever happened to getting it in 2 days?? [SUPPORT] @290386 I'm sorry to hear we've let you down, Dima! Have you noticed this happening more often with a specific carrier? ^ML

[7] similarity=0.8752 conversation_id=2752093 size=2
[CUSTOMER] @AmazonHelp why am I paying for Amazon prime next day delivery when it's taking 2, 3 sometimes 4 days to receive a delivery? All items are prime eligible and stated as one day delivery [SUPPORT] @740102 I'm sorry to hear you aren't receiving your orders by the date expected! Shipping speed refers to the time taken to arrive, in business days, once shipped. Details here: https://t.co/3EIy3fwMlH ^BV

[8] similarity=0.8722 conversation_id=391179 size=4
[CUSTOMER] @AmazonHelp if something is "free two day shipping" with prime, why is it taking four days? [SUPPORT] @208622 Sorry for the wait! What was the delivery date based on the order confirmation e-mail? Has it passed that day? ^DD [CUSTOMER] @AmazonHelp I ordered yesterday and was told delivery will be thursday and how that is considered "two day" with prime. [SUPPORT] @208622 Hi! Shipping speed applies once the order has shipped out. You can read more on Prime shipping here:https://t.co/tO81IDQfIu ^SA

[9] similarity=0.8664 conversation_id=2682213 size=3
[CUSTOMER] Why exactly am I paying for Amazon Prime if my packages are still coming 4+ days after I ordered ? @115821 [SUPPORT] @754528 1/2 I'm sorry your delivery isn't arriving as expected. Some items need extra time to process and aren't available to ship [SUPPORT] @754528 2/2 immediately. Two-Day Shipping refers to transit time in business days after your order ships. ^KP

[10] similarity=0.8652 conversation_id=2808954 size=4
[CUSTOMER] Why do I pay for amazon prime if my packages don’t actually arrive in 2 days?? 🙄😠 @115821 [SUPPORT] @140400 Two-Day Shipping refers to transit time, in business days, once shipped. Details can be found here: https://t.co/bBsSI4M8bu   Did we miss the delivery day in the confirmation e-mail? You can check here: https://t.co/z0lxodJgvN ^BH [CUSTOMER] @AmazonHelp Yeah... the confirmation was for today. 😞 [SUPPORT] @140400 We'd like to take a closer look at this and go over available options with you. Please reach out to us here: https://t.co/hApLpM3Ejd ^LJ

====================================================================================================
QUERY 4 | ID=570075 | INTENT=DIGITAL_CONTENT | SOURCE=training

CUSTOMER QUERY:
Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)

TOP RETRIEVED:

[1] similarity=0.8530 conversation_id=234239 size=2
[CUSTOMER] Amazonプライム入ってよかった…✨✨✨✨ [SUPPORT] @171766 |・∀・*)ﾉｼ　ご利用いただきありがとうございます～！ HM

[2] similarity=0.8456 conversation_id=536596 size=2
[CUSTOMER] Amazonプライム神だなぁ https://t.co/CP1r8bhf2B [SUPPORT] @244334 壁|▽//)ゝﾃﾚﾃﾚ  そのように言っていただけると… Amazonプライムをご利用いただき、ありがとうございます！どうぞ存分にお楽しみください♪ RI

[3] similarity=0.8343 conversation_id=1486242 size=2
[CUSTOMER] Amazonプライムの恩恵がすごい [SUPPORT] @465156 ぜひご活用くださいませ！ありがとうございます🙇✨ EK

[4] similarity=0.8307 conversation_id=531701 size=2
[CUSTOMER] Amazonプライム登録しました。 [SUPPORT] @243172 ご登録ありがとうございます！ヾ(=^▽^=)ノ　Amazonプライムの特典はプライム・ビデオ以外にも様々ございますので、ぜひご活用ください♪ https://t.co/qjaFIyuJfK  TN

[5] similarity=0.8285 conversation_id=608095 size=2
[CUSTOMER] アマゾンプライム登録したったー [SUPPORT] @264531 ご登録ありがとうございます！(*^^*) Amazonプライムの特典はプライム・ビデオなど様々ございますので、ぜひご活用くださいませ♪ https://t.co/qjaFIyMkEk  TN

[6] similarity=0.8283 conversation_id=570117 size=2
[CUSTOMER] Amazonプライムで映画SINGがもう無料で観れるとは！？ 今晩観よう。 [SUPPORT] @253820 ぜひ( *• ̀ω•́ )b SK

[7] similarity=0.8275 conversation_id=2390487 size=2
[CUSTOMER] Amazonプライム会員になったけど神 [SUPPORT] @688606 ご登録ありがとうございます！(*^^*) Amazonプライムの特典は様々ございますので、ぜひご活用ください♪ https://t.co/qjaFIyMkEk  TN

[8] similarity=0.8249 conversation_id=1575632 size=2
[CUSTOMER] Amazonプライム登録しちゃった！！！月400円は安いな(笑) [SUPPORT] @485517 ご登録いただきありがとうございました！様々な特典をご用意しておりますので、どうぞご活用くださいませ😉 https://t.co/VbtgF9ELUj EK

[9] similarity=0.8201 conversation_id=662701 size=2
[CUSTOMER] Amazonプライムで劇場版ガルパン見れる！！最高😁 [SUPPORT] @277888 喜んでいただけてよかったです😊 SK

[10] similarity=0.8190 conversation_id=2716924 size=2
[CUSTOMER] Amazonプライム会員になればいつでもタダでガルパン観れるのすごい！！！ [SUPPORT] @762609 どうぞお楽しみください( *´艸｀) EK

====================================================================================================
QUERY 5 | ID=1427974 | INTENT=DELIVERY_MISSING_OR_MISDELIVERED | SOURCE=training

CUSTOMER QUERY:

In [270]:
# Create a 150-query retrieval evaluation sample.
#
# We use the already-labelled benchmark queries, but the retrieved
# conversations come only from the unseen 81,796-document corpus.

from sklearn.model_selection import train_test_split

# Separate the two benchmark sources
training_queries = retrieval_benchmark[
    retrieval_benchmark["benchmark_source"] == "training"
].copy()

audit_queries = retrieval_benchmark[
    retrieval_benchmark["benchmark_source"] == "taxonomy_audit"
].copy()

# Stratified sample:
# 50 training queries
# 100 taxonomy-audit queries

training_review, _ = train_test_split(
    training_queries,
    test_size=len(training_queries) - 50,
    stratify=training_queries["intent_label"],
    random_state=42,
)

audit_review, _ = train_test_split(
    audit_queries,
    test_size=len(audit_queries) - 100,
    stratify=audit_queries["intent_label"],
    random_state=42,
)

retrieval_review_sample = pd.concat(
    [
        training_review,
        audit_review,
    ],
    ignore_index=True,
)

# Keep deterministic ordering
retrieval_review_sample = retrieval_review_sample.sort_values(
    ["benchmark_source", "conversation_id"]
).reset_index(drop=True)

print("Retrieval review queries:",
      len(retrieval_review_sample))

print("\nSource:")
print(
    retrieval_review_sample["benchmark_source"].value_counts()
)

print("\nIntent distribution:")
display(
    retrieval_review_sample["intent_label"].value_counts()
    .sort_index()
)

print(
    "\nMissing labels:",
    retrieval_review_sample["intent_label"].isna().sum()
)

Retrieval review queries: 150

Source:
benchmark_source
taxonomy_audit    100
training           50
Name: count, dtype: int64

Intent distribution:

intent_label
ACCOUNT_ACCESS_SECURITY              5
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     5
DELIVERY_DELAY                      38
DELIVERY_MISSING_OR_MISDELIVERED    14
DEVICE_TECHNICAL_SUPPORT             3
DIGITAL_CONTENT                      6
GIFT_CARD_PROMOTION                  2
ORDER_STATUS_OR_CANCELLATION         7
OTHER_NON_SUPPORT                   25
PAYMENT_BILLING                      5
PRIME_MEMBERSHIP                     4
PRODUCT_AVAILABILITY_INFORMATION     5
PRODUCT_PROBLEM                     16
RETURN_REPLACEMENT_REFUND           10
WEBSITE_APP_TECHNICAL                5
Name: count, dtype: int64

Missing labels: 0

Build the retrieval - review data

In [271]:
# Map the 150 review queries back to their retrieval results.

review_rows = []

# Create lookup from conversation ID -> row in the 450-query benchmark
benchmark_id_to_index = {
    int(row["conversation_id"]): idx
    for idx, row in retrieval_benchmark.iterrows()
}

for _, query_row in retrieval_review_sample.iterrows():

    query_id = int(query_row["conversation_id"])
    query_idx = benchmark_id_to_index[query_id]

    # Top 3 retrieved historical conversations
    retrieved_indices = benchmark_indices[query_idx][:3]
    retrieved_scores = benchmark_scores[query_idx][:3]

    for rank, (retrieved_idx, score) in enumerate(
        zip(retrieved_indices, retrieved_scores),
        start=1
    ):

        retrieved_row = amazon_retrieval_benchmark_corpus.iloc[
            retrieved_idx
        ]

        review_rows.append({
            "query_conversation_id": query_id,
            "query_intent": query_row["intent_label"],
            "benchmark_source": query_row["benchmark_source"],
            "query_text": query_row["customer_only_text"],

            "rank": rank,
            "similarity": float(score),

            "retrieved_conversation_id": int(
                retrieved_row["conversation_id"]
            ),

            "retrieved_conversation_size": int(
                retrieved_row["conversation_size"]
            ),

            "retrieved_customer_turns": int(
                retrieved_row["customer_turns"]
            ),

            "retrieved_support_turns": int(
                retrieved_row["support_turns"]
            ),

            "retrieved_conversation_text":
                retrieved_row["conversation_text"],
        })


retrieval_review = pd.DataFrame(review_rows)

print("Review rows:", len(retrieval_review))
print(
    "Unique queries:",
    retrieval_review["query_conversation_id"].nunique()
)
print(
    "Ranks:",
    sorted(retrieval_review["rank"].unique())
)
print(
    "Missing retrieved conversations:",
    retrieval_review["retrieved_conversation_id"].isna().sum()
)

Review rows: 450
Unique queries: 150
Ranks: [np.int64(1), np.int64(2), np.int64(3)]
Missing retrieved conversations: 0

In [272]:
display(
    retrieval_review[
        [
            "query_conversation_id",
            "query_intent",
            "rank",
            "similarity",
            "retrieved_conversation_id",
            "query_text",
            "retrieved_conversation_text",
        ]
    ].head(9)
)

,query_conversation_id,query_intent,rank,similarity,retrieved_conversation_id,query_text,retrieved_conversation_text
0,52943,ORDER_STATUS_OR_CANCELLATION,1,0.837597,1488825,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...","[CUSTOMER] @115821 \nI ordered book from few days , can I turn it back to exchange the edition ..?\n[SUPPORT] @465802 Hi, has the order been dispatched? Did you place the order on https://t.co/nUUp5MLhYl? ^JJ\n[CUSTOMER] @AmazonHelp \nYes , I received it from couple of days , but still new and wrapped too ✨\n[SUPPORT] @465802 Got it! You can start the return process by visiting us here: https://t.co/yIZoIuRY5p ^TK\n[CUSTOMER] @AmazonHelp \nThank you for helping 🌸✨\n[SUPPORT] @465802 No probl..."
1,52943,ORDER_STATUS_OR_CANCELLATION,2,0.824107,2338831,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...","[CUSTOMER] @115821 STILL NOT RECEIVED MY BOOK. I WOULD LIKE A REFUND PLEASE. ORDER PENDING SINCE JUNE 19th, 2017 https://t.co/pagtQwyUf8\n[SUPPORT] @676575 Hi sorry to hear this. What is the current tracking on your order. You can check here https://t.co/aaDyEz1VgE ^CR\n[CUSTOMER] @AmazonHelp I ordered via https://t.co/3mPq6UE7sm but it's not coming up on the link you've given here.\n[SUPPORT] @676575 So sorry! Try this link instead: https://t.co/JzP7hlA23B Please keep us posted! ^LB\n[CUSTO..."
2,52943,ORDER_STATUS_OR_CANCELLATION,3,0.819928,224575,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...","[CUSTOMER] @AmazonHelp are you kidding me? Twice now I've ordered a book and both times have had major issues with my order. Unreal. Give me a refund.\n[SUPPORT] @169654 Apologies. Can you tell us a bit more about the issues, were the books fulfilled by Amazon or a 3rd Party Seller? ^JJ\n[CUSTOMER] @AmazonHelp I just DM'd you guys about the issue."
3,80798,DELIVERY_MISSING_OR_MISDELIVERED,1,0.822829,676883,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,"[CUSTOMER] @115850 order no 407-2447542-9629927 not yet received by me, why is it showing delivered, Kindly check.\n[SUPPORT] @281471 I understand your concern. Please report this to our support team here: https://t.co/vlvfJr4nN9 and we'll get it checked. \nPlease don't provide your order details, we consider it to be personal information. Our page is visible to the public. ^SY\n[CUSTOMER] @AmazonHelp Again same problem, item not yet received by me but msg from Amazon says that it's delivere..."
4,80798,DELIVERY_MISSING_OR_MISDELIVERED,2,0.822015,2511798,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,"[CUSTOMER] @115850 my order#408-5604067-5477926 supposed to be delivered by tomorrow but I have noticed it is not yet dispatched. Status ASAP\n[SUPPORT] @715887 I’m sorry about the issue you’re facing with delivery. Let us look into it. (1/2)^HR\n[SUPPORT] @715887 Please share your details from the link here: https://t.co/beaaDm0muc to assist you accordingly. (2/2)^HR\n[SUPPORT] @715887 Also, as this a social medial platform, please don't provide order details. We consider it personal infor..."
5,80798,DELIVERY_MISSING_OR_MISDELIVERED,3,0.812312,230138,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,"[CUSTOMER] @115850 I have not received Order #402-5024592-7887529 put on September 18, 2017. In status, this shows delivered.\n[SUPPORT] @170834 That's unusual. Kindly report it here: https://t.co/vlvfJr4nN9 and we'll look into this right away. ^HK\n[CUSTOMER] @AmazonHelp I have already written item delivery feedback. But no response. u have waste rural service than others.\n[SUPPORT] @170834 Missing orders can be found by following the steps mentioned here: https://t.co/AfxKlWXhD7. (1/2)\n[..."
6,137048,DELIVERY_DELAY,1,0.778782,2111120,"Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT\n[CUSTOMER] @146907 @120533 @AmazonHelp Oui ça part en sucette. Avec le Prime sur des produits envoyés par Amazon je n'arrive plus à être livré le lendemain que de temps en temps.. @AmazonHelp Oui cela peut se comprendre... par contre annoncer ""livré en 1 jour ouvré"" reste mensonger et ne correspond pas aux services de mon abonnement Prime. cc @146905\n[CUSTOMER] @AmazonHelp Non.. Produit Prime commandé mardi et q...","[CUSTOMER] Mais le prime chez @120533 c'est la vie \o/ . Commandé hier, reçu ce matin. Bon ben cadeau de Noël ça c'est (déjà) fait :p\n[SUPPORT] @147566 Cool 😍 Merci d'avoir partagé vos impressions, c'est toujours un plaisir d'avoir un client satisfait. ^ASZ\n[CUSTOMER] @AmazonHelp là j'avoue c'est Top :D vous avez même réussi à me livrer un produit ""en rupture et réapro le 18"" le lendemain de ma commande, soit le 8. Chapeau bas 😎\n[SUPPORT] @147566 😍 Vous êtes cliente Amazon depuis quand ? ..."
7,137048,DELIVERY_DELAY,2,0.778368,1943813,"Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT\n[CUSTOMER] @146907 @120533 @AmazonHelp Oui ça part en sucette. Avec le Prime sur des produits envoyés par Amazon je n'arrive plus à être livré le lendemain que de temps en temps.. @AmazonHelp Oui cela peut se comprendre... par contre annoncer ""livré en 1 jour ouvré"" reste mensonger et ne correspond pas aux services de mon abonnement Prime. cc @146905\n[CUSTOMER] @AmazonHelp Non.. Produit Prime commandé mardi et q...","[CUSTOMER] franchement pour les client prime amazon devrait changer de transporteur parce que La Poste j'en peux juste plus\n[SUPPORT] @577901 Bonjour, rencontrez-vous un souci avec une commande en cours ? ^ME\n[CUSTOMER] @AmazonHelp le soucis c'est que LaPoste ne fait, encore une fois pas son taf\n[SUPPORT] @577901 Pouvez-vous nous expliquer davantage s'il vous plaît ? ^MA\n[CUSTOMER] @AmazonHelp commande prime qui aurait du être livré avant 20H mais qui selon LaPoste mon adresse était impo..."
8,137048,DELIVERY_DELAY,3,0.773506,2584206,"Désormais chez @120533 : 1 jour ouvré = 3 jours ouvrés https://t.co/IQwOxCXPWT\n[CUSTOMER] @146907 @120533 @AmazonHelp Oui ça part en sucette. Avec le Prime sur des produits envoyés par Amazon je n'arrive plus à être livré le lendemain que de temps en temps.. @AmazonHelp Oui cela peut se comprendre... par contre annoncer ""livré en 1 jour ouvré"" reste mensonger et ne correspond pas aux services de mon abonnement Prime. cc @146905\n[CUSTOMER] @AmazonHelp Non.. Produit Prime commandé mardi et q...","[CUSTOMER] @120533 Bonjour, J'ai amazon prime, ma commande lancé le 11 novembre est prévu pour le 25 novembre et je paye 2,5€ de frais de port ... Est-ce normal ??\n[SUPPORT] @732302 Bonsoir,\nL'article est-il expédié par Amazon ou par un vendeur tiers?\n^MD\n[CUSTOMER] @AmazonHelp Par un certain Nagiry ça doit être un tiers ... fait chier, je savais pas qu’on pouvait avoir contact directement avec un vendeur tiers\n[SUPPORT] @732302 Avez-vous eu à contacter le vendeur? Si oui, quelle est sa..."

In [273]:
import re

def extract_customer_only_clean(text):
    text = str(text)

    # Extract customer sections
    customer_messages = re.findall(
        r"\[CUSTOMER\]\s*(.*?)(?=\[SUPPORT\]|\Z)",
        text,
        flags=re.DOTALL
    )

    cleaned_messages = []

    for msg in customer_messages:
        # Remove accidental nested role markers
        msg = re.sub(r"\[CUSTOMER\]\s*", " ", msg)
        msg = re.sub(r"\[SUPPORT\]\s*", " ", msg)

        # Normalize whitespace
        msg = re.sub(r"\s+", " ", msg).strip()

        if msg:
            cleaned_messages.append(msg)

    return " ".join(cleaned_messages)


# Rebuild customer-only query text
retrieval_benchmark["customer_only_text"] = (
    retrieval_benchmark["conversation_text"]
    .apply(extract_customer_only_clean)
)

# Check for remaining role markers
remaining_customer_markers = (
    retrieval_benchmark["customer_only_text"]
    .str.contains(r"\[CUSTOMER\]", regex=True)
    .sum()
)

remaining_support_markers = (
    retrieval_benchmark["customer_only_text"]
    .str.contains(r"\[SUPPORT\]", regex=True)
    .sum()
)

print("Queries:", len(retrieval_benchmark))
print("Remaining [CUSTOMER] markers:", remaining_customer_markers)
print("Remaining [SUPPORT] markers:", remaining_support_markers)

print("\nExample cleaned query:")
print(retrieval_benchmark.iloc[0]["customer_only_text"][:1000])

Queries: 450
Remaining [CUSTOMER] markers: 0
Remaining [SUPPORT] markers: 0

Example cleaned query:
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue + @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.

In [274]:
# Re-encode the cleaned customer-only queries
clean_query_embeddings = embedding_model.encode(
    retrieval_benchmark["customer_only_text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

clean_query_embeddings = np.asarray(
    clean_query_embeddings,
    dtype="float32"
)

print("Query embedding shape:", clean_query_embeddings.shape)

# Retrieve top 10 from the leakage-safe benchmark corpus
clean_scores, clean_indices = faiss_index_benchmark.search(
    clean_query_embeddings,
    10
)

print("Scores shape:", clean_scores.shape)
print("Indices shape:", clean_indices.shape)

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Query embedding shape: (450, 384)
Scores shape: (450, 10)
Indices shape: (450, 10)

In [275]:
# Inspect the first 5 benchmark queries after cleaning.

for i in range(5):
    query_row = retrieval_benchmark.iloc[i]

    print("=" * 100)
    print(f"QUERY {i + 1}")
    print(f"Conversation ID : {query_row['conversation_id']}")
    print(f"Intent          : {query_row['intent_label']}")
    print(f"\nCustomer query:")
    print(query_row["customer_only_text"][:1200])

    print("\nTop 3 retrieved cases:")

    for rank in range(3):
        retrieved_idx = clean_indices[i][rank]
        score = clean_scores[i][rank]

        retrieved_row = amazon_retrieval_benchmark_corpus.iloc[
            retrieved_idx
        ]

        print(f"\n--- Rank {rank + 1} | Similarity: {score:.4f} ---")
        print(
            f"Retrieved conversation ID: "
            f"{retrieved_row['conversation_id']}"
        )
        print(
            retrieved_row["conversation_text"][:1000]
        )

    print()

====================================================================================================
QUERY 1
Conversation ID : 373303
Intent          : DELIVERY_DELAY

Customer query:
I looooove @115821, I use them all the time. My one qualm is when I actually pay for one day shipping, it never arrives. So - I will stop. @AmazonHelp I spoke with your customer service today. Although they did their best I’m frustrated I have to wait until tomorrow to resolve the issue + @AmazonHelp + when I ordered one day shipping because it was a gift. Now it’s late and I wouldn’t have ordered it if I couldn’t have gotten it then.

Top 3 retrieved cases:

--- Rank 1 | Similarity: 0.7752 ---
Retrieved conversation ID: 339472
[CUSTOMER] It's really frustrating trying to order things through @115821 lately. They seem to screw up shipment and delivery every time.
[SUPPORT] @197062 This isn't what we like to hear! Are you currently having an issue? If so, can you give us more info? We're here for you! ^KJ

--- Rank 2 | Similarity: 0.7714 ---
Retrieved conversation ID: 218089
[CUSTOMER] If you have problems with your @115821 same day delivery, @2150 might be involved. LMAO. https://t.co/Mq883LdLpi
[SUPPORT] @167995 Hi! Are you currently experiencing an issue with an order? We'd like to help! ^WT

--- Rank 3 | Similarity: 0.7582 ---
Retrieved conversation ID: 2408738
[CUSTOMER] I just want to say that @115821 is amazing. I've had a few problems and their customer service is unrivaled. Shout out to @AmazonHelp and everyone on their team. My dollars support Amazon.
[SUPPORT] @692621 Thank you, Amar! We're glad to help :) ^SM

====================================================================================================
QUERY 2
Conversation ID : 282739
Intent          : PRODUCT_PROBLEM

Customer query:
@115821 Netboon tempered glass purchased for BlackBerry Priv @ Rs 1180 in January 2017 lost adhesive, falls off on its own. Need replacement. Netboon not responding. Amazon to help [Ordered on Jan 4, 2017 (406-9818731-9588334)] @115821 Netboon refused to help. Temperd glass purchased for Rs 1180 does not stick to phone panel. Amazon enjoy being helpless to help the genuine buyer. @AmazonHelp Amazon- Do you sell product to survive only return expiration period. Go to CP in Delhi. Tempered glass is available for merely Rs 100 per piece. Yet I bought Netboon at Rs 1800. I did not buy from Netboon. Who is Netbeen ? Nobody know. I bought from Amazon. @115937 @118702 @AmazonHelp Amazon- Have the Netboon order &amp; Refusal to help. If tempered glass falls off on its own, is a quality issue. I did not buy from Netboon. I bought Netboon product from Amazon. Please resolve my concern. @115937 @118702 https://t.co/G6PkbmqPTF @AmazonHelp where is the service center of Netboon??????? @AmazonHelp Service denial letter attached once again. How many times you want me attach this letter @115937 @20502 https://t.co/GAa6Id6ahi @AmazonHelp @115937 @20502 Service denial letter's copy attached once aga

Top 3 retrieved cases:

--- Rank 1 | Similarity: 0.6653 ---
Retrieved conversation ID: 379293
[CUSTOMER] @115850 Ordrd phone during sale.temp glass on it, with scratches, looks like 2nd had product. Want a replacement.Cant contact seller
[SUPPORT] @206004 Apologies for the trouble you've had with the order.1/2 ^MM
[SUPPORT] @206004 Have you escalated this to our support team here: https://t.co/2t6DQoUmNZ for assistance? 2/2 ^MM
[CUSTOMER] @AmazonHelp Yes I have, when can I expect a response on the same from your side
[SUPPORT] @206004 Thank you. Our support team will work on the issue and get in touch with you at the earliest. ^NS

--- Rank 2 | Similarity: 0.6569 ---
Retrieved conversation ID: 298481
[CUSTOMER] @115850 for my new 1+5 ordered temper glass on 4/8/17 vide order  405-6620277-8785136.Defective tempered glass sold placed d return 1/2
[CUSTOMER] @115850 Return not accepted,absolutely no adhesive was there in d tempered glass which makes d order meaningless.replace d defective product asap
[SUPPORT] @187119 We apologize for the inconvenience. Could you confirm if you've contact our support team here: https://t.co/vlvfJr4nN9? ^ZH
[CUSTOMER] @AmazonHelp Yes contacted but no reply was received, again used d link &amp; further highlightedabout d defective tempered glass.pls liveup to ur reputation
[SUPPORT] @187119 Sorry to know about the issue with your order. Please contact us here:https://t.co/TK4yevTaND, we'll assist you. ^NR 1/2
[SUPPORT] @187119 Please don't provide your order details, we consider it personal info. Our Twitter page is visible to public. ^NR 2/2
[CUSTOMER] @AmazonHelp Noted,thanks,trust u resolve the issue to d satisfaction
[SUPPORT] @187119 We'll be sure

--- Rank 3 | Similarity: 0.6357 ---
Retrieved conversation ID: 1438620
[CUSTOMER] Bought @80464  pro fit tempered glass for my  #OnePlus5 from @115850 and see what I received. https://t.co/jUC4KVuYPL
[SUPPORT] @453867 I'm sorry you received a damaged product. Kindly report this to our support team here: https://t.co/rS49hgaADF 1/2^SC
[SUPPORT] @453867 so that we can fix this for you. 2/2^SC
[CUSTOMER] @AmazonHelp I've already reported the issue on your customer service. Let's see what will happen next.
[CUSTOMER] @AmazonHelp Was Really excited about the Orzly tempered glass. Heard a lot about it 😞
[SUPPORT] @453867 Sorry about that. Please be assured our support team will sort this out for you. ^PB
[SUPPORT] @453867 That's unexpected! As you've contacted our support team, please do keep us posted for further correspondence. ^BS

====================================================================================================
QUERY 3
Conversation ID : 2292312
Intent          : DELIVERY_DELAY

Customer query:
@AmazonHelp why offer 2 day shipping for prime when item will take 4 days to get it. #cancellingprime #nothappy @AmazonHelp I know that it's going to take 4 days transit time yet I pay monthly for 2 days. ITS SUPPOSED TO BE DELIVERED TODAY YET IT WILL BE DELIVERED MONDAY. @AmazonHelp No it's the stupid post office that always messes up my deliveries

Top 3 retrieved cases:

--- Rank 1 | Similarity: 0.8883 ---
Retrieved conversation ID: 2480947
[CUSTOMER] @AmazonHelp why does prime 2 day shipping take 5 days to arrive? We pay for prime for fast delivery right? But we dont get it.
[SUPPORT] @470885 I'm sorry for the trouble! Two-Day shipping refers to transit time, in business days, once shipped: https://t.co/x6DaIpAB5H ^EB
[CUSTOMER] @AmazonHelp So your saying it could take MONTHS.. but as long as its 2 days in shipping counts as 2 day shipping... kida fucked up. I guess i wont renew

--- Rank 2 | Similarity: 0.8843 ---
Retrieved conversation ID: 759758
[CUSTOMER] @115821 Why does my Prime shipping now seem to take 4 days to two weeks? If I can’t get it in 2 days don’t tell me it’s Prime eligible! 😡😡
[SUPPORT] @301536 Two-Day Shipping refers to the transit time in business days, once an item ships. More info here: https://t.co/bMtwK35Sm0 ^VS
[CUSTOMER] @AmazonHelp Ordered on the 5th, shipped on the 8th, and ETA is anywhere from the 17th to the 24th. But thanks for the patronizing reply.

--- Rank 3 | Similarity: 0.8834 ---
Retrieved conversation ID: 2969493
[CUSTOMER] @AmazonHelp Why do I pay for Prime with 2-day shipping, and then order something and it tells me it will be 6 days?
[SUPPORT] @237243 I'm sorry for the trouble! Prime Two-Day shipping refers to the transit time, in business days, once the item has shipped: https://t.co/x6DaIpAB5H. Have we missed the delivery date provided at checkout on a recent order? ^VB

====================================================================================================
QUERY 4
Conversation ID : 570075
Intent          : DIGITAL_CONTENT

Customer query:
Amazonプライム！私はこの時をずっと待っていたぞ！！パージ3めちゃくちゃ待ったわぁぁぁぁ(^q^)

Top 3 retrieved cases:

--- Rank 1 | Similarity: 0.8530 ---
Retrieved conversation ID: 234239
[CUSTOMER] Amazonプライム入ってよかった…✨✨✨✨
[SUPPORT] @171766 |・∀・*)ﾉｼ　ご利用いただきありがとうございます～！ HM

--- Rank 2 | Similarity: 0.8456 ---
Retrieved conversation ID: 536596
[CUSTOMER] Amazonプライム神だなぁ https://t.co/CP1r8bhf2B
[SUPPORT] @244334 壁|▽//)ゝﾃﾚﾃﾚ  そのように言っていただけると…
Amazonプライムをご利用いただき、ありがとうございます！どうぞ存分にお楽しみください♪ RI

--- Rank 3 | Similarity: 0.8343 ---
Retrieved conversation ID: 1486242
[CUSTOMER] Amazonプライムの恩恵がすごい
[SUPPORT] @465156 ぜひご活用くださいませ！ありがとうございます🙇✨ EK

====================================================================================================
QUERY 5
Conversation ID : 1427974
Intent          : DELIVERY_MISSING_OR_MISDELIVERED

Customer query:
@115850 Vry bad service in Patna region.ordered 3 products in last few weeks.It was showing delivered bt it was not nt @AmazonHelp Filled the form n mentioned the order id of other two products as well.Please check @AmazonHelp Thank you for quick response @AmazonHelp One more product defaulted..Today I received a msg as delivered bt it was nt delivered to me.Pls check @AmazonHelp This is a serious fraud issue.Can u share the details of customer wh is taking my order n signing on my behalf @AmazonHelp Already contacted.All they do is ask for 3 days..and after 3 days they refund the amt.bt thats nt thr issue .. @AmazonHelp Who’s receiving product on my behalf..pls share the details @AmazonHelp Done pls check

Top 3 retrieved cases:

--- Rank 1 | Similarity: 0.7687 ---
Retrieved conversation ID: 1124884
[CUSTOMER] @119356 @115850 @48686 @385241 @2517 @144775  fraud company sending wrong products everytime not letting customers check it they want is only money.. Request to every Indian bycot this fraud company they are just looting n befooling people
[CUSTOMER] @119356 @115850 @48686 @385241 @2517 @144775 Amazon a fraud company
[SUPPORT] @385240 Apologies for the trouble with the orders. I'd like to take a closer look at this and help. Please fill in your details using the link: https://t.co/JzRdscmdH9 and I'll get in touch with you soon. -AK

--- Rank 2 | Similarity: 0.7677 ---
Retrieved conversation ID: 1447136
[CUSTOMER] @115850 you'r a fraud company.nd your service is too bad. You didn't dispatched my product neither returned money of my product.Shame on u
[CUSTOMER] @115850 Your company is fraud nd you cannot solve my problem
[SUPPORT] @455800 Sorry for the trouble. Have you reported this to our support team as requested earlier? ^RB
[CUSTOMER] @AmazonHelp I booked a mobile cover by mode of online payment on 11 august nd expected delivery date 19 Aug bt can't nd my payment is also not refund wy
[SUPPORT] @455800 I do get you're upset. However, could you confirm if you've reached out to our support team? ^MS
[CUSTOMER] @115850 Amazon it's a fraud company.. Don't buy any things
[CUSTOMER] @AmazonHelp Plz slove my problem
[SUPPORT] @455800 That's quite a comment. Could you kindly elaborate on the issue for us to help you better? ^PB

--- Rank 3 | Similarity: 0.7625 ---
Retrieved conversation ID: 1718263
[CUSTOMER] @115850 Fraud by Amazon.Inflated mrp and sold to customers in name of sale and now refusing MRP.  Don't order from Amazon #AMAZONFRAUD https://t.co/LE6E0qE36l
[SUPPORT] @171474 you the lowest price, may result in fluctuations in our prices over time. [2/2] ^SK
[SUPPORT] @171474 Pricing and offers are decision of the sellers. The constantly changing marketplace and our efforts to offer [1/2] ^SK
[CUSTOMER] @115850 @115821 @115850 @AmazonHelp Still awaiting response. You don't have time to reply to customers?
[SUPPORT] @171474 Just to confirm, are you referring to a response from the support team or from us over social media? ^AB
[CUSTOMER] @AmazonHelp I want response from @115850 over this fraud
[SUPPORT] @171474 I'm unable to comprehend your concern. Kindly elaborate and we'll help you out. ^GK
[CUSTOMER] @AmazonHelp I ordered from Amazon India. Have attached 2 snapshot,  one of present nd other or when I ordered.see how u change mrp to fraud ppl
[SUPPORT] @171474 I understa

In [276]:
review_rows = []

# Map benchmark conversation ID -> benchmark row index
benchmark_id_to_index = {
    int(row["conversation_id"]): idx
    for idx, row in retrieval_benchmark.iterrows()
}

for _, query_row in retrieval_review_sample.iterrows():

    query_id = int(query_row["conversation_id"])
    query_idx = benchmark_id_to_index[query_id]

    # Use CLEAN retrieval results
    retrieved_indices = clean_indices[query_idx][:3]
    retrieved_scores = clean_scores[query_idx][:3]

    for rank, (retrieved_idx, score) in enumerate(
        zip(retrieved_indices, retrieved_scores),
        start=1
    ):

        retrieved_row = amazon_retrieval_benchmark_corpus.iloc[
            retrieved_idx
        ]

        review_rows.append({
            "query_conversation_id": query_id,
            "query_intent": query_row["intent_label"],
            "benchmark_source": query_row["benchmark_source"],
            "query_text": query_row["customer_only_text"],

            "rank": rank,
            "similarity": float(score),

            "retrieved_conversation_id": int(
                retrieved_row["conversation_id"]
            ),

            "retrieved_conversation_size": int(
                retrieved_row["conversation_size"]
            ),

            "retrieved_customer_turns": int(
                retrieved_row["customer_turns"]
            ),

            "retrieved_support_turns": int(
                retrieved_row["support_turns"]
            ),

            "retrieved_conversation_text":
                retrieved_row["conversation_text"],
        })


retrieval_review = pd.DataFrame(review_rows)

print("Retrieval review rows:", len(retrieval_review))
print(
    "Unique queries:",
    retrieval_review["query_conversation_id"].nunique()
)
print(
    "Rows per query:",
    retrieval_review.groupby(
        "query_conversation_id"
    ).size().value_counts().to_dict()
)

print(
    "Duplicate query/retrieved pairs:",
    retrieval_review.duplicated(
        ["query_conversation_id", "retrieved_conversation_id"]
    ).sum()
)

print(
    "Benchmark source:",
    retrieval_review["benchmark_source"].value_counts().to_dict()
)

Retrieval review rows: 450
Unique queries: 150
Rows per query: {3: 150}
Duplicate query/retrieved pairs: 0
Benchmark source: {'taxonomy_audit': 300, 'training': 150}

In [277]:
# Create the human retrieval annotation template

retrieval_annotations = retrieval_review.copy()

# Human annotation fields
retrieval_annotations["relevance_label"] = ""
retrieval_annotations["annotation_notes"] = ""
retrieval_annotations["annotator"] = ""

# Reorder columns for easier manual annotation
retrieval_annotations = retrieval_annotations[
    [
        "query_conversation_id",
        "query_intent",
        "benchmark_source",
        "query_text",

        "rank",
        "similarity",

        "retrieved_conversation_id",
        "retrieved_conversation_size",
        "retrieved_customer_turns",
        "retrieved_support_turns",
        "retrieved_conversation_text",

        "relevance_label",
        "annotation_notes",
        "annotator",
    ]
].copy()

# Save
retrieval_annotation_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_human_annotations.csv"
)

retrieval_annotations.to_csv(
    retrieval_annotation_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", retrieval_annotation_path)
print("Rows:", len(retrieval_annotations))
print("Columns:", len(retrieval_annotations.columns))
print(
    "Blank relevance labels:",
    (
        retrieval_annotations["relevance_label"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )
)

display(retrieval_annotations.head(6))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv
Rows: 450
Columns: 14
Blank relevance labels: 450

,query_conversation_id,query_intent,benchmark_source,query_text,rank,similarity,retrieved_conversation_id,retrieved_conversation_size,retrieved_customer_turns,retrieved_support_turns,retrieved_conversation_text,relevance_label,annotation_notes,annotator
0,52943,ORDER_STATUS_OR_CANCELLATION,taxonomy_audit,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...",1,0.833588,1488825,10,5,5,"[CUSTOMER] @115821 \nI ordered book from few days , can I turn it back to exchange the edition ..?\n[SUPPORT] @465802 Hi, has the order been dispatched? Did you place the order on https://t.co/nUUp5MLhYl? ^JJ\n[CUSTOMER] @AmazonHelp \nYes , I received it from couple of days , but still new and wrapped too ✨\n[SUPPORT] @465802 Got it! You can start the return process by visiting us here: https://t.co/yIZoIuRY5p ^TK\n[CUSTOMER] @AmazonHelp \nThank you for helping 🌸✨\n[SUPPORT] @465802 No probl...",,,
1,52943,ORDER_STATUS_OR_CANCELLATION,taxonomy_audit,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...",2,0.813460,2338831,16,10,6,"[CUSTOMER] @115821 STILL NOT RECEIVED MY BOOK. I WOULD LIKE A REFUND PLEASE. ORDER PENDING SINCE JUNE 19th, 2017 https://t.co/pagtQwyUf8\n[SUPPORT] @676575 Hi sorry to hear this. What is the current tracking on your order. You can check here https://t.co/aaDyEz1VgE ^CR\n[CUSTOMER] @AmazonHelp I ordered via https://t.co/3mPq6UE7sm but it's not coming up on the link you've given here.\n[SUPPORT] @676575 So sorry! Try this link instead: https://t.co/JzP7hlA23B Please keep us posted! ^LB\n[CUSTO...",,,
2,52943,ORDER_STATUS_OR_CANCELLATION,taxonomy_audit,"@AmazonHelp Hi! Order #204-2242560-7141155, 2 books that were preordered. I asked them to be shipped together...\n[CUSTOMER] @AmazonHelp ...but you sent the 1st one to me as soon as it was released, free of charge. Neat! But apparently it ended up in Austria (I am in Oslo)...\n[CUSTOMER] @AmazonHelp ...then i got a message saying its delivery time is now by the end of November. And now when I checked the order, you say I returned it!\n[CUSTOMER] @AmazonHelp I didn't return it (never received...",3,0.812170,224575,3,2,1,"[CUSTOMER] @AmazonHelp are you kidding me? Twice now I've ordered a book and both times have had major issues with my order. Unreal. Give me a refund.\n[SUPPORT] @169654 Apologies. Can you tell us a bit more about the issues, were the books fulfilled by Amazon or a 3rd Party Seller? ^JJ\n[CUSTOMER] @AmazonHelp I just DM'd you guys about the issue.",,,
3,80798,DELIVERY_MISSING_OR_MISDELIVERED,taxonomy_audit,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,1,0.822829,676883,4,2,2,"[CUSTOMER] @115850 order no 407-2447542-9629927 not yet received by me, why is it showing delivered, Kindly check.\n[SUPPORT] @281471 I understand your concern. Please report this to our support team here: https://t.co/vlvfJr4nN9 and we'll get it checked. \nPlease don't provide your order details, we consider it to be personal information. Our page is visible to the public. ^SY\n[CUSTOMER] @AmazonHelp Again same problem, item not yet received by me but msg from Amazon says that it's delivere...",,,
4,80798,DELIVERY_MISSING_OR_MISDELIVERED,taxonomy_audit,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,2,0.822015,2511798,7,3,4,"[CUSTOMER] @115850 my order#408-5604067-5477926 supposed to be delivered by tomorrow but I have noticed it is not yet dispatched. Status ASAP\n[SUPPORT] @715887 I’m sorry about the issue you’re facing with delivery. Let us look into it. (1/2)^HR\n[SUPPORT] @715887 Please share your details from the link here: https://t.co/beaaDm0muc to assist you accordingly. (2/2)^HR\n[SUPPORT] @715887 Also, as this a social medial platform, please don't provide order details. We consider it personal infor...",,,
5,80798,DELIVERY_MISSING_OR_MISDELIVERED,taxonomy_audit,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently. @115850 Reported to the team. Still no update. Kindly address @AmazonHelp Have already share the order ID. U can check,3,0.812312,230138,5,2,3,"[CUSTOMER] @115850 I have not received Order #402-5024592-7887529 put on September 18, 2017. In status, this shows delivered.\n[SUPPORT] @170834 That's unusual. Kindly report it here: https://t.co/vlvfJr4nN9 and we'll look into this right away. ^HK\n[CUSTOMER] @AmazonHelp I have already written item delivery feedback. But no response. u have waste rural service than others.\n[SUPPORT] @170834 Missing orders can be found by following the steps mentioned here: https://t.co/AfxKlWXhD7. (1/2)\n[...",,,

- 2	- Directly relevant and useful historical evidence for answering the query
- 1 - Related to the issue, but materially different / only partially useful
- 0	- Not relevant or not useful evidence

Interactive human retrieval annotation

In [278]:
import pandas as pd
import os

# Load the annotation file
retrieval_annotation_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_human_annotations.csv"
)

retrieval_annotations = pd.read_csv(
    retrieval_annotation_path,
    encoding="utf-8-sig"
)

# Make sure annotation columns exist
retrieval_annotations["relevance_label"] = (
    retrieval_annotations["relevance_label"]
    .fillna("")
    .astype(str)
)

retrieval_annotations["annotation_notes"] = (
    retrieval_annotations["annotation_notes"]
    .fillna("")
    .astype(str)
)

retrieval_annotations["annotator"] = (
    retrieval_annotations["annotator"]
    .fillna("")
    .astype(str)
)

print("Rows:", len(retrieval_annotations))
print(
    "Already annotated:",
    (
        retrieval_annotations["relevance_label"]
        .str.strip()
        .ne("")
    ).sum()
)
print(
    "Remaining:",
    (
        retrieval_annotations["relevance_label"]
        .str.strip()
        .eq("")
    ).sum()
)

Rows: 450
Already annotated: 0
Remaining: 450

In [279]:
# Export first 30 retrieval judgments for review

first_30 = retrieval_annotations.iloc[:30].copy()

first_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_first_30.csv"
)

first_30.to_csv(
    first_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", first_30_path)
print("Rows:", len(first_30))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_first_30.csv
Rows: 30

In [280]:
import pandas as pd
from pathlib import Path

# Input file
input_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"
)

# Load existing annotation file
df = pd.read_csv(input_path, encoding="utf-8-sig")

# Human-annotated labels for the first 30 rows
labels = [
    1, 1, 1,
    2, 1, 2,
    2, 1, 1,
    0, 0, 0,
    2, 2, 2,
    2, 1, 0,
    2, 2, 2,
    0, 2, 2,
    2, 1, 1,
    0, 1, 0
]

# Safety check
assert len(labels) == 30, "Exactly 30 labels are required."
assert len(df) >= 30, "The annotation CSV contains fewer than 30 rows."

# Update ONLY the first 30 rows
df.loc[df.index[:30], "relevance_label"] = labels

# Add annotation notes
notes = [
    "Related order/return issue, but materially different",
    "Missing book/order issue; useful but not the same requested outcome",
    "Generic order problem and refund request; partially useful",
    "Direct delivered-but-not-received case",
    "Delivery-status problem, but not delivered/misdelivered",
    "Direct delivered-but-not-received case",
    "Direct Prime/delivery-delay problem",
    "Prime shipping/delivery issue, but mainly seller/fee eligibility",
    "Prime one-day delivery availability; related but not an actual delay",
    "Delivery delay, unrelated to account-security problem",
    "Generic delivery complaint, not account access",
    "Order-return issue, not account security",
    "Direct electronic-device/product problem",
    "Direct faulty iPhone/product issue",
    "Direct device dead-on-arrival/product problem",
    "Strong delivery problem match despite noisy query label",
    "Repeated product-return issue; related but different",
    "Refund for damaged product; materially different",
    "Direct same-day delivery delay",
    "Direct repeated delivery delay",
    "Direct past-due delivery",
    "Positive on-time delivery; not useful for delay",
    "Direct late-delivery complaint",
    "Direct delivery-not-on-time complaint",
    "Direct damaged-product case",
    "Damaged packaging; partially relevant",
    "Packaging/delivery complaint, but product itself undamaged",
    "Payment/Prime issue, not account-access problem",
    "Prime-membership problem overlaps one part of query",
    "Delivery delay, unrelated to account issue",
]

# Update notes for first 30 rows
df.loc[df.index[:30], "annotation_notes"] = notes

# Mark these as your human-reviewed annotations
df.loc[df.index[:30], "annotator"] = "human_1"

# Save back to the same file
df.to_csv(input_path, index=False, encoding="utf-8-sig")

print("✅ First 30 retrieval rows annotated and saved successfully.")
print(f"File: {input_path}")

# Verification
check = pd.read_csv(input_path, encoding="utf-8-sig")

print("\nVerification:")
print("Total rows:", len(check))
print("First 30 labels:")
print(check.loc[:29, ["query_conversation_id", "rank",
                      "relevance_label", "annotation_notes"]].to_string(index=False))

✅ First 30 retrieval rows annotated and saved successfully.
File: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv

Verification:
Total rows: 450
First 30 labels:
 query_conversation_id  rank  relevance_label                                                     annotation_notes
                 52943     1              1.0                 Related order/return issue, but materially different
                 52943     2              1.0  Missing book/order issue; useful but not the same requested outcome
                 52943     3              1.0           Generic order problem and refund request; partially useful
                 80798     1              2.0                               Direct delivered-but-not-received case
                 80798     2              1.0              Delivery-status problem, but not delivered/misdelivered
                 80798     3              2.0                               Direct delivered-but-not-received case
                137048     1              2.0                                  Direct Prime/delivery-delay problem
                137048     2              1.0     Prime shipping/delivery issue, but mainly seller/fee eligibility
                137048     3              1.0 Prime one-day delivery availability; related but not an actual delay
                246997     1              0.0                Delivery delay, unrelated to account-security problem
                246997     2              0.0                       Generic delivery complaint, not account access
                246997     3              0.0                             Order-return issue, not account security
                259944     1              2.0                             Direct electronic-device/product problem
                259944     2              2.0                                   Direct faulty iPhone/product issue
                259944     3              2.0                        Direct device dead-on-arrival/product problem
                264786     1              2.0              Strong delivery problem match despite noisy query label
                264786     2              1.0                 Repeated product-return issue; related but different
                264786     3              0.0                     Refund for damaged product; materially different
                271576     1              2.0                                       Direct same-day delivery delay
                271576     2              2.0                                       Direct repeated delivery delay
                271576     3              2.0                                             Direct past-due delivery
                286794     1              0.0                      Positive on-time delivery; not useful for delay
                286794     2              2.0                                       Direct late-delivery complaint
                286794     3              2.0                                Direct delivery-not-on-time complaint
                300539     1              2.0                                          Direct damaged-product case
                300539     2              1.0                                Damaged packaging; partially relevant
                300539     3              1.0           Packaging/delivery complaint, but product itself undamaged
                316310     1              0.0                      Payment/Prime issue, not account-access problem
                316310     2              1.0                  Prime-membership problem overlaps one part of query
                316310     3              0.0                           Delivery delay, unrelated to account issue

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3947128289.py:68: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Related order/return issue, but materially different', 'Missing book/order issue; useful but not the same requested outcome', 'Generic order problem and refund request; partially useful', 'Direct delivered-but-not-received case', 'Delivery-status problem, but not delivered/misdelivered', 'Direct delivered-but-not-received case', 'Direct Prime/delivery-delay problem', 'Prime shipping/delivery issue, but mainly seller/fee eligibility', 'Prime one-day delivery availability; related but not an actual delay', 'Delivery delay, unrelated to account-security problem', 'Generic delivery complaint, not account access', 'Order-return issue, not account security', 'Direct electronic-device/product problem', 'Direct faulty iPhone/product issue', 'Direct device dead-on-arrival/product problem', 'Strong delivery problem match despite noisy query label', 'Repeated product-return issue; related but different', 'Refund for damaged product; materially different', 'Direct same-day delivery delay', 'Direct repeated delivery delay', 'Direct past-due delivery', 'Positive on-time delivery; not useful for delay', 'Direct late-delivery complaint', 'Direct delivery-not-on-time complaint', 'Direct damaged-product case', 'Damaged packaging; partially relevant', 'Packaging/delivery complaint, but product itself undamaged', 'Payment/Prime issue, not account-access problem', 'Prime-membership problem overlaps one part of query', 'Delivery delay, unrelated to account issue']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df.index[:30], "annotation_notes"] = notes
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8164\3947128289.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'human_1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df.index[:30], "annotator"] = "human_1"

In [281]:
# Fix column dtypes before writing text annotations
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# Now update the first 30 rows
df.loc[df.index[:30], "annotation_notes"] = notes
df.loc[df.index[:30], "annotator"] = "human_1"

# Save
df.to_csv(input_path, index=False, encoding="utf-8-sig")

print("✅ Saved without dtype warnings.")

✅ Saved without dtype warnings.

In [282]:
labels = [
    1, 2, 2, 2, 1, 0,
    2, 2, 2, 0, 1, 0,
    2, 2, 1, 2, 2, 2,
    0, 2, 1, 2, 1, 2,
    0, 0, 0, 0, 0, 0
]

notes = [
    "Related order issue, but not the same customer problem.",
    "Directly relevant delivery-delay evidence.",
    "Directly relevant late-delivery case.",
    "Directly relevant delivery-status issue.",
    "Related delivery issue but materially different.",
    "Not useful for the query.",
    "Direct product-problem evidence.",
    "Direct faulty-product evidence.",
    "Direct product-problem evidence.",
    "Not relevant to the query intent.",
    "Related account/order context but not the same issue.",
    "Not relevant to the query.",
    "Direct missing-delivery evidence.",
    "Direct delivery-status evidence.",
    "Related product/order issue but not identical.",
    "Direct payment/billing evidence.",
    "Direct payment/charge evidence.",
    "Related billing issue.",
    "Not useful for the query.",
    "Directly relevant delivery evidence.",
    "Related order-status issue.",
    "Direct order-status evidence.",
    "Related Prime/delivery context.",
    "Direct membership/support evidence.",
    "Not useful for the query.",
    "Related delivery issue.",
    "Direct delivery-delay evidence.",
    "Not relevant to the query.",
    "Not relevant to the query.",
    "Not relevant to the query."
]

In [289]:
START_ROW = 0
END_ROW = len(labels) - 1

expected_count = END_ROW - START_ROW + 1

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels)

In [290]:
print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

Labels: 30
Notes: 30
Expected: 30

In [293]:
# ============================================================
# WRITE ANNOTATIONS
# ============================================================

start_idx = START_ROW
end_idx = END_ROW + 1

# Select the intended rows using zero-based row numbers.
selected_index = df.index[start_idx:end_idx]

assert len(selected_index) == len(labels), (
    f"Selected {len(selected_index)} rows but received "
    f"{len(labels)} labels."
)

# Assign through an indexed Series to avoid iterable-length errors.
df.loc[selected_index, "relevance_label"] = pd.Series(
    labels,
    index=selected_index,
)
df.loc[df.index[start_idx:end_idx], "annotation_notes"] = notes
df.loc[df.index[start_idx:end_idx], "annotator"] = "human_1"

# ============================================================
# SAVE
# ============================================================

df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# VERIFY
# ============================================================

check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("✅ Batch 31–60 saved successfully!")
print(f"Rows annotated: {len(batch)}")
print(f"Row range: {START_ROW}–{END_ROW}")

print("\nLabel distribution:")
print(batch["relevance_label"].value_counts().sort_index())

print("\nRemaining unannotated rows:")
print(check["relevance_label"].isna().sum())

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label",
            "annotator"
        ]
    ].to_string(index=False)
)

✅ Batch 31–60 saved successfully!
Rows annotated: 30
Row range: 0–29

Label distribution:
relevance_label
0.0    10
1.0     6
2.0    14
Name: count, dtype: int64

Remaining unannotated rows:
420

Verification:
 query_conversation_id  rank  relevance_label annotator
                 52943     1              1.0   human_1
                 52943     2              2.0   human_1
                 52943     3              2.0   human_1
                 80798     1              2.0   human_1
                 80798     2              1.0   human_1
                 80798     3              0.0   human_1
                137048     1              2.0   human_1
                137048     2              2.0   human_1
                137048     3              2.0   human_1
                246997     1              0.0   human_1
                246997     2              1.0   human_1
                246997     3              0.0   human_1
                259944     1              2.0   human_1
                259944     2              2.0   human_1
                259944     3              1.0   human_1
                264786     1              2.0   human_1
                264786     2              2.0   human_1
                264786     3              2.0   human_1
                271576     1              0.0   human_1
                271576     2              2.0   human_1
                271576     3              1.0   human_1
                286794     1              2.0   human_1
                286794     2              1.0   human_1
                286794     3              2.0   human_1
                300539     1              0.0   human_1
                300539     2              0.0   human_1
                300539     3              0.0   human_1
                316310     1              0.0   human_1
                316310     2              0.0   human_1
                316310     3              0.0   human_1

In [294]:
next_60_90 = retrieval_annotations.iloc[61:91].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_60_90.csv"
)

next_60_90.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_60_90))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_60_90.csv
Rows: 30

In [295]:
import pandas as pd
from pathlib import Path

# ============================================================
# FILE
# ============================================================

input_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"
)

# ============================================================
# BATCH 61–90
# ============================================================

START_ROW = 61
END_ROW = 90

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

# Prevent dtype warnings
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ============================================================
# RELEVANCE LABELS
#
# 2 = Directly relevant and useful
# 1 = Related / partially useful
# 0 = Not relevant / not useful
# ============================================================

labels = [
    # 61–63 | Query 498437 | DELIVERY_DELAY
    1, 1, 1,

    # 64–66 | Query 514690 | DELIVERY_DELAY
    2, 1, 2,

    # 67–69 | Query 585801 | OTHER_NON_SUPPORT
    2, 2, 2,

    # 70–72 | Query 611123 | WEBSITE_APP_TECHNICAL
    0, 1, 2,

    # 73–75 | Query 617078 | PRODUCT_AVAILABILITY_INFORMATION
    2, 0, 1,

    # 76–78 | Query 627702 | DELIVERY_MISSING_OR_MISDELIVERED
    2, 2, 2,

    # 79–81 | Query 644769 | OTHER_NON_SUPPORT
    2, 0, 0,

    # 82–84 | Query 714744 | DELIVERY_MISSING_OR_MISDELIVERED
    2, 1, 1,

    # 85–87 | Query 792025 | PRODUCT_PROBLEM
    0, 1, 0,

    # 88–90 | Query 818203 | DELIVERY_DELAY
    2, 2, 2
]

# ============================================================
# ANNOTATION NOTES
# ============================================================

notes = [
    # 61–63
    "Delivered-but-not-received case; related to package location but materially different from a pure delay.",
    "Direct delivered-but-not-received evidence; useful for locating a package but different from the primary delay intent.",
    "Delivered-but-not-received case; related delivery evidence but not a direct delay resolution.",

    # 64–66
    "Direct delayed Prime/preorder delivery case.",
    "Related preorder problem involving stock/inventory, but not primarily a delivery-delay resolution.",
    "Direct delivery-delay case with carrier delay and updated delivery estimate.",

    # 67–69
    "Directly relevant packaging-feedback example.",
    "Directly relevant packaging-feedback example.",
    "Directly relevant packaging-feedback example.",

    # 70–72
    "Positive social engagement; not useful for an app-down technical issue.",
    "Technical support case, but it concerns an Echo device rather than the website/app.",
    "Direct app-down troubleshooting case.",

    # 73–75
    "Direct stock-availability question with Amazon support response.",
    "Packaging/damage issue; not useful for a stock-availability query.",
    "Price-information case; related to product information but not stock availability.",

    # 76–78
    "Direct parcel-marked-delivered-but-not-received case.",
    "Direct missing-delivery case with order-location assistance.",
    "Direct scanned-as-delivered-but-not-received case.",

    # 79–81
    "Direct promotion/discount-related conversation; useful for the promotional context.",
    "Delivered-but-not-received problem; unrelated to the query's social/promotion intent.",
    "Wrong-product complaint; unrelated to the query's social/promotion intent.",

    # 82–84
    "Directly relevant delivery failure involving delayed, lost, and wrong-house deliveries.",
    "Related Prime delivery failure, but the example is primarily a missed delivery window rather than confirmed misdelivery.",
    "Related repeated delivery failure, but primarily a next-day delivery delay rather than confirmed misdelivery.",

    # 85–87
    "Unrelated email/notification feedback; does not address the wrong-product problem.",
    "Related product-ordering issue involving minimum order quantity, but not the wrong-product problem.",
    "Positive packaging feedback; not useful for resolving the wrong-product problem.",

    # 88–90
    "Direct guaranteed-delivery-date failure.",
    "Direct repeated guaranteed-delivery failure.",
    "Direct late-delivery complaint with a missed promised date."
]

# ============================================================
# SAFETY CHECKS
# ============================================================

expected_count = END_ROW - START_ROW + 1

print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(
    label in [0, 1, 2]
    for label in labels
), "Labels must contain only 0, 1, or 2"

# ============================================================
# WRITE
# ============================================================

start_idx = START_ROW - 1
end_idx = END_ROW

df.loc[
    df.index[start_idx:end_idx],
    "relevance_label"
] = labels

df.loc[
    df.index[start_idx:end_idx],
    "annotation_notes"
] = notes

df.loc[
    df.index[start_idx:end_idx],
    "annotator"
] = "human_1"

# ============================================================
# SAVE
# ============================================================

df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# VERIFY
# ============================================================

check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("\n" + "=" * 60)
print("✅ BATCH 61–90 SAVED SUCCESSFULLY")
print("=" * 60)

print(f"Rows annotated: {len(batch)}")
print(f"Row range: {START_ROW}–{END_ROW}")

print("\nLabel distribution:")
print(
    batch["relevance_label"]
    .value_counts()
    .sort_index()
)

print("\nRemaining unannotated rows:")
print(
    check["relevance_label"].isna().sum()
)

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label",
            "annotator"
        ]
    ].to_string(index=False)
)

Labels: 30
Notes: 30
Expected: 30

============================================================
✅ BATCH 61–90 SAVED SUCCESSFULLY
============================================================
Rows annotated: 30
Row range: 61–90

Label distribution:
relevance_label
0.0     6
1.0     9
2.0    15
Name: count, dtype: int64

Remaining unannotated rows:
390

Verification:
 query_conversation_id  rank  relevance_label annotator
                498437     1              1.0   human_1
                498437     2              1.0   human_1
                498437     3              1.0   human_1
                514690     1              2.0   human_1
                514690     2              1.0   human_1
                514690     3              2.0   human_1
                585801     1              2.0   human_1
                585801     2              2.0   human_1
                585801     3              2.0   human_1
                611123     1              0.0   human_1
                611123     2              1.0   human_1
                611123     3              2.0   human_1
                617078     1              2.0   human_1
                617078     2              0.0   human_1
                617078     3              1.0   human_1
                627702     1              2.0   human_1
                627702     2              2.0   human_1
                627702     3              2.0   human_1
                644769     1              2.0   human_1
                644769     2              0.0   human_1
                644769     3              0.0   human_1
                714744     1              2.0   human_1
                714744     2              1.0   human_1
                714744     3              1.0   human_1
                792025     1              0.0   human_1
                792025     2              1.0   human_1
                792025     3              0.0   human_1
                818203     1              2.0   human_1
                818203     2              2.0   human_1
                818203     3              2.0   human_1

In [296]:
next_91_120 = retrieval_annotations.iloc[91:121].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_91_120.csv"
)

next_91_120.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_91_120))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_91_120.csv
Rows: 30

In [297]:
labels = [
    2, 2,
    2, 2, 2,
    2, 2, 2,
    0, 1, 2,
    2, 1, 0,
    2, 2, 2,
    1, 2, 1,
    2, 2, 1,
    2, 0, 1,
    2, 2, 1,
    2
]

In [298]:
print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", END_ROW - START_ROW + 1)

Labels: 30
Notes: 30
Expected: 30

In [299]:
labels = [
    2, 2,
    2, 2, 2,
    2, 2, 2,
    0, 1, 2,
    2, 1, 0,
    2, 2, 2,
    1, 2, 1,
    2, 2, 1,
    2, 0, 1,
    2, 2, 1,
    2
]

In [300]:
print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", END_ROW - START_ROW + 1)

Labels: 30
Notes: 30
Expected: 30

In [301]:
START_ROW = 91
END_ROW = 120

labels = [
    2, 2,
    2, 2, 2,
    2, 2, 2,
    0, 1, 2,
    2, 1, 0,
    2, 2, 2,
    1, 2, 1,
    2, 2, 1,
    2, 0, 1,
    2, 2, 1,
    2
]

print("Labels:", len(labels))
print("Expected:", END_ROW - START_ROW + 1)

Labels: 30
Expected: 30

In [302]:
notes = [
    "Directly relevant missing/non-received item case; useful historical evidence.",  # 1
    "Directly relevant prolonged non-delivery and refund problem.",  # 2
    "Direct delivery-delay case involving a very late order.",  # 3
    "Direct delivery-delay case involving a missed delivery window.",  # 4
    "Direct non-delivery complaint with Amazon support investigation.",  # 5
    "Direct shipping/tracking problem closely matching the delivery-delay query.",  # 6
    "Direct repeated delivery failures and late packages; highly useful.",  # 7
    "Direct repeated delivery delays and unresolved shipping problems.",  # 8
    "Not a product-defect resolution; retrieved conversation is unrelated to the specific product complaint.",  # 9
    "Packaging complaint is related to a product issue but materially different from the query's defect.",  # 10
    "Wrong-size product is a concrete product problem and useful historical evidence.",  # 11
    "Order not dispatched and delayed for weeks; directly relevant to delivery delay.",  # 12
    "Prime membership/order cancellation problem is related to fulfillment but materially different.",  # 13
    "Prime charge/refund issue is not useful for the delivery-delay problem.",  # 14
    "Direct wrong-item/return/refund case matching the return workflow.",  # 15
    "Direct refund-delay case.",  # 16
    "Undelivered order with missing refund; strongly relevant to the refund request.",  # 17
    "Generic poor customer-service complaint is related but lacks a specific issue.",  # 18
    "Direct generic customer-support dissatisfaction; useful for handling this type of complaint.",  # 19
    "Order-status request is a specific support issue but does not match the generic complaint closely.",  # 20
    "Direct refund request following an order problem.",  # 21
    "Damaged product with support discussing remedy/options; useful for return/refund handling.",  # 22
    "Delivery delay is related to an order problem but not specifically return/refund.",  # 23
    "Direct Echo/Alexa connectivity and Bluetooth-related device question.",  # 24
    "Positive Echo experience without a technical problem; not useful.",  # 25
    "Alexa/device-related question but different from the Bluetooth connectivity issue.",  # 26
    "Direct delivered-but-not-received and refund-related delivery problem.",  # 27
    "Direct missing-delivery/refund problem.",  # 28
    "Non-dispatched product with missing refund; related non-delivery/refund evidence but materially different from misdelivery.",  # 29
    "Direct accidental Prime membership/autorenewal problem; useful historical evidence.",  # 30
]

In [303]:
print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

Labels: 30
Notes: 30
Expected: 30

In [304]:
notes = [
    "Directly relevant missing/non-received item case; useful historical evidence.",
    "Directly relevant prolonged non-delivery and refund problem.",

    "Direct delivery-delay case involving a very late order.",
    "Direct delivery-delay case involving a missed delivery window.",
    "Direct non-delivery complaint with Amazon support investigation.",

    "Direct shipping/tracking problem closely matching the delivery-delay query.",
    "Direct repeated delivery failures and late packages; highly useful.",
    "Direct repeated delivery delays and unresolved shipping problems.",

    "Not a product-defect resolution; retrieved conversation is unrelated to the specific product complaint.",
    "Packaging complaint is related to a product issue but materially different from the query's defect.",
    "Wrong-size product is a concrete product problem and useful historical evidence.",

    "Order not dispatched and delayed for weeks; directly relevant to delivery delay.",
    "Prime/order cancellation problem is related to fulfillment but materially different.",
    "Prime charge/refund issue is not useful for the delivery-delay problem.",

    "Direct wrong-item/return/refund case matching the return workflow.",
    "Direct refund-delay case.",
    "Undelivered order with missing refund; strongly relevant to the refund request.",

    "Generic poor customer-service complaint is related but lacks a specific issue.",
    "Direct generic customer-support dissatisfaction; useful for handling this type of complaint.",
    "Order-status request is a specific support issue but does not match the generic complaint closely.",

    "Direct refund request following an order problem.",
    "Damaged product with support discussing remedy/options; useful for return/refund handling.",
    "Delivery delay is related to an order problem but not specifically return/refund.",

    "Direct Echo/Alexa connectivity and Bluetooth-related device question.",
    "Positive Echo experience without a technical problem; not useful.",
    "Alexa/device-related question but different from the Bluetooth connectivity issue.",

    "Direct delivered-but-not-received and refund-related delivery problem.",
    "Direct missing-delivery/refund problem.",
    "Non-dispatched product with missing refund; related non-delivery/refund evidence but materially different from misdelivery.",

    "Direct accidental Prime membership/autorenewal problem; useful historical evidence."
]

expected_count = END_ROW - START_ROW + 1

# ---------- Validate ----------
assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels), \
    "Invalid relevance label found."

# ---------- Load ----------
df = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

# Avoid dtype warnings
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ---------- Update 91–120 ----------
start_idx = START_ROW - 1
end_idx = END_ROW

df.loc[
    df.index[start_idx:end_idx],
    "relevance_label"
] = labels

df.loc[
    df.index[start_idx:end_idx],
    "annotation_notes"
] = notes

df.loc[
    df.index[start_idx:end_idx],
    "annotator"
] = "human_1"

# ---------- Save ----------
df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ---------- Verification ----------
check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("✅ Batch 91–120 saved successfully")
print(f"Rows updated: {len(batch)}")

print("\nLabel distribution:")
print(
    batch["relevance_label"]
    .value_counts()
    .sort_index()
)

print(
    f"\nRemaining unannotated rows: "
    f"{check['relevance_label'].isna().sum()}"
)

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label"
        ]
    ].to_string(index=False)
)

✅ Batch 91–120 saved successfully
Rows updated: 30

Label distribution:
relevance_label
0.0     3
1.0     7
2.0    20
Name: count, dtype: int64

Remaining unannotated rows: 360

Verification:
 query_conversation_id  rank  relevance_label
                846932     1              2.0
                846932     2              2.0
                846932     3              2.0
                857011     1              2.0
                857011     2              2.0
                857011     3              2.0
                865617     1              2.0
                865617     2              2.0
                865617     3              0.0
                873792     1              1.0
                873792     2              2.0
                873792     3              2.0
                930385     1              1.0
                930385     2              0.0
                930385     3              2.0
                937309     1              2.0
                937309     2              2.0
                937309     3              1.0
                940491     1              2.0
                940491     2              1.0
                940491     3              2.0
                942145     1              2.0
                942145     2              1.0
                942145     3              2.0
                958801     1              0.0
                958801     2              1.0
                958801     3              2.0
                993254     1              2.0
                993254     2              1.0
                993254     3              2.0

In [305]:
next_121_150 = retrieval_annotations.iloc[121:151].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_121_150.csv"
)

next_121_150.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_121_150))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_121_150.csv
Rows: 30

In [306]:
import pandas as pd
from pathlib import Path

input_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"
)

START_ROW = 121
END_ROW = 150

labels = [
    2, 0,
    2, 2, 1,
    2, 2, 2,
    1, 0, 1,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    1, 2, 2,
    2, 2, 2,
    2, 2, 2,
    1
]

notes = [
    "Direct accidental Prime-membership explanation and automatic renewal context.",
    "Positive Prime-membership experience; does not help resolve the accidental-membership complaint.",
    
    "Directly similar positive Amazon purchase and fast-delivery experience.",
    "Direct positive Amazon purchase/delivery experience; useful for a positive-support response.",
    "General Amazon positivity, but the specific topic differs from the query.",
    
    "Strongly related poor Amazon customer-service complaint with multiple support failures.",
    "Direct generic customer-service dissatisfaction and support follow-up.",
    "Direct generic poor-service complaint; useful for handling dissatisfaction.",
    
    "Customer-service complaint is related but does not identify the same underlying issue.",
    "Positive Amazon experience is unrelated to the negative/general complaint.",
    "Order-status problem is somewhat related to Amazon dissatisfaction but materially different.",
    
    "Directly related Prime Video/content-release announcement question.",
    "Directly related question about availability of a season on the platform.",
    "Directly related season-release question with support response.",
    
    "Direct one-day shipping delay and missed delivery expectation.",
    "Direct complaint about Prime/shipping taking longer than promised.",
    "Direct one-day shipping delay complaint.",
    
    "Direct two-factor authentication and verification-code problem.",
    "Direct account-access problem caused by delayed verification codes.",
    "Direct login/security-code timeout problem with troubleshooting guidance.",
    
    "Involves the app but concerns delivery status rather than the core app technical issue.",
    "Direct checkout/order technical failure with troubleshooting steps.",
    "Direct app/payment/order technical problem with troubleshooting guidance.",
    
    "Strongly related frustration about repeated forms and support handling.",
    "Direct form-submission/support follow-up issue.",
    "Direct form/support issue with an unresolved customer problem.",
    
    "Direct order-status problem involving an order not being dispatched.",
    "Direct order-status/non-delivery problem.",
    "Direct order-status problem involving an order marked out for delivery but not received.",
    
    "Related Amazon dissatisfaction, but the specific issue is different from the query."
]

# ---------- Validation ----------
expected_count = END_ROW - START_ROW + 1

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels), \
    "Invalid relevance label found."

# ---------- Load ----------
df = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

# Prevent dtype warnings
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ---------- Update rows 121–150 ----------
start_idx = START_ROW - 1
end_idx = END_ROW

df.loc[
    df.index[start_idx:end_idx],
    "relevance_label"
] = labels

df.loc[
    df.index[start_idx:end_idx],
    "annotation_notes"
] = notes

df.loc[
    df.index[start_idx:end_idx],
    "annotator"
] = "human_1"

# ---------- Save ----------
df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ---------- Verify ----------
check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("✅ Batch 121–150 saved successfully")
print(f"Rows updated: {len(batch)}")
print("\nLabel distribution:")
print(batch["relevance_label"].value_counts().sort_index())

print(f"\nRemaining unannotated rows: "
      f"{check['relevance_label'].isna().sum()}")

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label"
        ]
    ].to_string(index=False)
)

✅ Batch 121–150 saved successfully
Rows updated: 30

Label distribution:
relevance_label
0.0     2
1.0     5
2.0    23
Name: count, dtype: int64

Remaining unannotated rows: 330

Verification:
 query_conversation_id  rank  relevance_label
               1074622     1              2.0
               1074622     2              0.0
               1074622     3              2.0
               1100625     1              2.0
               1100625     2              1.0
               1100625     3              2.0
               1105827     1              2.0
               1105827     2              2.0
               1105827     3              1.0
               1110378     1              0.0
               1110378     2              1.0
               1110378     3              2.0
               1148768     1              2.0
               1148768     2              2.0
               1148768     3              2.0
               1219190     1              2.0
               1219190     2              2.0
               1219190     3              2.0
               1259305     1              2.0
               1259305     2              2.0
               1259305     3              1.0
               1266468     1              2.0
               1266468     2              2.0
               1266468     3              2.0
               1310651     1              2.0
               1310651     2              2.0
               1310651     3              2.0
               1385734     1              2.0
               1385734     2              2.0
               1385734     3              1.0

In [307]:
next_151_180 = retrieval_annotations.iloc[151:181].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_151_180.csv"
)

next_151_180.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_151_180))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_151_180.csv
Rows: 30

In [308]:
# ---------- RESET 151–180 LABELS ----------

START_ROW = 151
END_ROW = 180

labels = [
    1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 1, 1, 2, 1, 1, 2, 0,
    2, 2, 1, 2, 2, 1, 2, 1, 1, 1
]

notes = [
    "Generic customer-service complaint; related but not a specific support resolution.",
    "Defective-item complaint is related but materially different from the generic query.",
    "Return-policy/order-change issue is related but not a direct match.",
    "Direct return-policy issue involving an incorrectly ordered product.",
    "Direct returned-product and refund problem; highly relevant.",
    "Direct pre-order dispatch problem matching the order-status issue.",
    "Direct pre-order delivery-date problem; useful evidence.",
    "Direct pre-order non-delivery problem; highly relevant.",
    "Direct multi-day delivery delay; strong match.",
    "Direct delayed-package complaint; highly relevant.",
    "Direct repeated package non-arrival problem; useful evidence.",
    "Direct refund request and replacement/return workflow; highly relevant.",
    "Customer-care follow-up problem related to return/replacement but not a specific resolution.",
    "Generic customer-service dissatisfaction without a specific return/refund resolution.",
    "Direct undelivered-order and missing-refund complaint; useful evidence.",
    "Generic customer-service dissatisfaction related to an order problem but materially different.",
    "Unresolved order problem and poor support experience; partially useful.",
    "Direct card-payment/COD delivery problem matching the payment issue.",
    "Delivery failure is unrelated to the specific card-payment problem.",
    "Direct card-swipe/payment-on-delivery problem; highly relevant.",
    "Direct packaging/cushioning complaint matching the product concern.",
    "Cushioning recommendation concerns a different product and problem.",
    "Packaging feedback is related to cushioning but concerns a different packaging issue.",
    "Direct delivery-delay example with a missed promised delivery time.",
    "Direct late/out-for-delivery example; highly useful.",
    "Direct package-not-arrived example with late delivery; highly relevant.",
    "Delayed shipment is related to delivery timing but is somewhat less direct.",
    "Promotion/discount issue is related to an Amazon purchase but not delivery delay.",
    "Delivery-delay concern where the package had not yet shipped; useful evidence.",
    "Direct Prime membership/autorenewal problem; useful historical evidence."
]

expected_count = END_ROW - START_ROW + 1

print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

assert len(labels) == 30
assert len(notes) == 30
assert all(x in [0, 1, 2] for x in labels)

print("✅ EXACTLY 30 LABELS + 30 NOTES")

Labels: 30
Notes: 30
Expected: 30
✅ EXACTLY 30 LABELS + 30 NOTES

In [309]:
# ---------- Load ----------
df = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

# Avoid dtype warnings
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ---------- Update 151–180 ----------
start_idx = START_ROW - 1
end_idx = END_ROW

df.loc[
    df.index[start_idx:end_idx],
    "relevance_label"
] = labels

df.loc[
    df.index[start_idx:end_idx],
    "annotation_notes"
] = notes

df.loc[
    df.index[start_idx:end_idx],
    "annotator"
] = "human_1"

# ---------- Save ----------
df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ---------- Verification ----------
check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("✅ Batch 151–180 saved successfully")
print(f"Rows updated: {len(batch)}")

print("\nLabel distribution:")
print(
    batch["relevance_label"]
    .value_counts()
    .sort_index()
)

print(
    f"\nRemaining unannotated rows: "
    f"{check['relevance_label'].isna().sum()}"
)

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label"
        ]
    ].to_string(index=False)
)

✅ Batch 151–180 saved successfully
Rows updated: 30

Label distribution:
relevance_label
0.0     1
1.0    12
2.0    17
Name: count, dtype: int64

Remaining unannotated rows: 300

Verification:
 query_conversation_id  rank  relevance_label
               1405353     1              1.0
               1405353     2              1.0
               1405353     3              1.0
               1448054     1              2.0
               1448054     2              2.0
               1448054     3              2.0
               1491812     1              2.0
               1491812     2              2.0
               1491812     3              2.0
               1528649     1              2.0
               1528649     2              2.0
               1528649     3              2.0
               1568174     1              2.0
               1568174     2              1.0
               1568174     3              1.0
               1581994     1              2.0
               1581994     2              1.0
               1581994     3              1.0
               1652051     1              2.0
               1652051     2              0.0
               1652051     3              2.0
               1676412     1              2.0
               1676412     2              1.0
               1676412     3              2.0
               1711455     1              2.0
               1711455     2              1.0
               1711455     3              2.0
               1735260     1              1.0
               1735260     2              1.0
               1735260     3              1.0

In [310]:
next_181_240 = retrieval_annotations.iloc[181:241].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_181_240.csv"
)

next_181_240.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_181_240))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_181_240.csv
Rows: 60

In [311]:
START_ROW = 181
END_ROW = 240

labels = [
    2, 2,
    0, 0, 0,
    1, 1, 1,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    1, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    1, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 2,
    2, 2, 1,
    0, 2, 1,
    2
]

In [312]:
notes = [
    "Directly relevant late/non-received package case.",
    "Directly relevant pre-order with missing delivery date.",

    "Positive Amazon experience; not relevant to the support issue.",
    "Positive Amazon experience; not relevant.",
    "Positive Amazon pickup experience; not relevant to the query.",

    "Direct refund-status case; highly relevant.",
    "Direct refund-status request; useful historical evidence.",
    "Direct returned-order refund-status case; highly relevant.",

    "Related delivery/order problem, but not the specific missing product defect.",
    "Pre-order shipping problem is related but materially different from the product defect.",
    "Pre-order delivery failure is related to fulfillment but not the product defect itself.",

    "Direct prolonged non-delivery and delivery-delay case.",
    "Direct unpaid/undelivered order delay; highly relevant.",
    "Direct delivery-delay complaint involving a missed required date.",

    "Direct Amazon Music subscription/content example.",
    "Direct Amazon Music usage example; useful for digital-content context.",
    "Direct Amazon Music content/search question; highly relevant.",

    "Direct Prime one-day delivery failure; highly relevant.",
    "Direct Prime delivery-delay complaint; highly relevant.",
    "Direct Prime one-day delivery timing problem; highly relevant.",

    "Direct delivery-driver/address failure; highly relevant to the underlying delivery problem.",
    "Delivered-but-not-received gift is related but materially different from the driver's address issue.",
    "Ongoing delivery investigation and delayed birthday gift; highly relevant.",

    "Direct email-unsubscribe/website issue; highly relevant.",
    "Direct repeated unwanted-email/unsubscribe problem.",
    "Direct unsubscribe problem involving marketing emails.",

    "Shipping-status problem for a pre-order; directly relevant.",
    "Direct missing shipping confirmation/status problem.",
    "Direct delayed Xbox pre-order; highly relevant.",

    "Price/deal discussion is related to the pricing concern but not an exact MRP issue.",
    "Direct website price versus MRP discrepancy; highly relevant.",
    "Direct complaint about selling above MRP; highly relevant.",

    "Wrong/damaged product complaint is directly relevant to the product problem.",
    "Faulty mobile and return/refund problem; highly relevant.",
    "Wrong product delivered; directly relevant.",

    "Direct delivered-but-not-received package case.",
    "Direct delivered-but-not-received package case.",
    "Direct delivered-but-not-received package case with troubleshooting guidance.",

    "Prime registration is related to Amazon digital services but not the specific Amazon Music query.",
    "Prime Video availability is related to digital content but different from Amazon Music.",
    "Direct Amazon Music usage and benefits; highly relevant.",

    "Generic Amazon Prime contact route is only partially useful for the payment/charge issue.",
    "Generic dissatisfaction with Amazon; not useful for the specific payment issue.",
    "Direct unexpected Amazon Prime charge; highly relevant.",

    "Prime benefit/service feedback is related but not the delivery-fee complaint.",
    "Direct Prime dissatisfaction involving delivery delays; useful evidence.",
    "Direct Prime delivery-delay complaint; highly relevant.",

    "Direct damaged-product follow-up problem; highly relevant.",
    "Direct damaged-product complaint; highly relevant.",
    "Direct broken-product return/replacement/refund guidance; highly relevant.",

    "Direct Prime membership cancellation request.",
    "Direct Prime membership cancellation request.",
    "Direct Prime cancellation due to poor service; highly relevant.",

    "Direct delivery-delay issue involving compensation for late delivery.",
    "Direct missing-package/status problem; highly relevant.",
    "Delivered-to-neighbor problem is related to delivery but is materially different from the stated delay.",

    "Account-verification problem is unrelated to the delivery-delay query.",
    "Direct repeated delivery-delay complaint; highly relevant.",
    "Prime/package waiting complaint is related to delivery delay but is less specific.",

    "Direct seller-funds payment/holding problem matching the underlying query."
]

In [313]:
expected_count = END_ROW - START_ROW + 1

print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels), \
    "Invalid relevance label found."

print("✅ EXACTLY 60 LABELS + 60 NOTES")

Labels: 60
Notes: 60
Expected: 60
✅ EXACTLY 60 LABELS + 60 NOTES

In [314]:
# ---------- Load ----------
df = pd.read_csv(input_path, encoding="utf-8-sig")

df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ---------- Batch ----------
START_ROW = 181
END_ROW = 240

start_idx = START_ROW - 1
end_idx = END_ROW

# ---------- Update ----------
df.loc[df.index[start_idx:end_idx], "relevance_label"] = labels
df.loc[df.index[start_idx:end_idx], "annotation_notes"] = notes
df.loc[df.index[start_idx:end_idx], "annotator"] = "human_1"

# ---------- Save ----------
df.to_csv(input_path, index=False, encoding="utf-8-sig")

# ---------- Verification ----------
check = pd.read_csv(input_path, encoding="utf-8-sig")
batch = check.iloc[start_idx:end_idx]

print("✅ Batch 181–240 saved successfully")
print(f"Rows updated: {len(batch)}")

print("\nLabel distribution:")
print(batch["relevance_label"].value_counts().sort_index())

print(f"\nRemaining unannotated rows: {check['relevance_label'].isna().sum()}")

print("\nVerification:")
print(
    batch[
        ["query_conversation_id", "rank", "relevance_label"]
    ].to_string(index=False)
)

✅ Batch 181–240 saved successfully
Rows updated: 60

Label distribution:
relevance_label
0.0     4
1.0     7
2.0    49
Name: count, dtype: int64

Remaining unannotated rows: 240

Verification:
 query_conversation_id  rank  relevance_label
               1741904     1              2.0
               1741904     2              2.0
               1741904     3              0.0
               1844497     1              0.0
               1844497     2              0.0
               1844497     3              1.0
               1875465     1              1.0
               1875465     2              1.0
               1875465     3              2.0
               1986309     1              2.0
               1986309     2              2.0
               1986309     3              2.0
               2049109     1              2.0
               2049109     2              2.0
               2049109     3              2.0
               2107331     1              2.0
               2107331     2              2.0
               2107331     3              2.0
               2117819     1              2.0
               2117819     2              2.0
               2117819     3              2.0
               2192530     1              2.0
               2192530     2              2.0
               2192530     3              2.0
               2279034     1              2.0
               2279034     2              2.0
               2279034     3              2.0
               2279881     1              2.0
               2279881     2              2.0
               2279881     3              1.0
               2301887     1              2.0
               2301887     2              2.0
               2301887     3              2.0
               2310980     1              2.0
               2310980     2              2.0
               2310980     3              2.0
               2316614     1              2.0
               2316614     2              2.0
               2316614     3              2.0
               2318594     1              2.0
               2318594     2              2.0
               2318594     3              1.0
               2389659     1              2.0
               2389659     2              2.0
               2389659     3              2.0
               2390377     1              2.0
               2390377     2              2.0
               2390377     3              2.0
               2403961     1              2.0
               2403961     2              2.0
               2403961     3              2.0
               2417989     1              2.0
               2417989     2              2.0
               2417989     3              2.0
               2419144     1              2.0
               2419144     2              1.0
               2419144     3              0.0
               2432744     1              2.0
               2432744     2              1.0
               2432744     3              2.0

In [315]:
next_241_300 = retrieval_annotations.iloc[241:301].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_241_300.csv"
)

next_241_300.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_241_300))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_241_300.csv
Rows: 60

In [316]:
START_ROW = 241
END_ROW = 300

labels = [
    2, 2,
    2, 2, 1,
    2, 2, 2,
    2, 2, 2,
    0, 0, 0,
    2, 2, 2,
    1, 2, 1,
    1, 2, 2,
    0, 0, 0,
    2, 2, 2,
    2, 0, 0,
    2, 1, 2,
    2, 2, 2,
    2, 2, 2,
    1, 1, 1,
    0, 0, 0,
    2, 2, 2,
    2, 2, 2,
    1, 1, 1,
    2, 2, 2,
    2
]

notes = [
    "Direct seller-funds/payment-hold issue; strong historical evidence.",
    "Direct seller-support routing for held seller funds; useful evidence.",
    "Defective-product complaint is directly related, though the retrieved case focuses on wrong product descriptions.",
    "Escalation and investigation of a defective-product complaint; useful historical evidence.",
    "Undelivered order is related to the broader complaint but materially different from the defective-product issue.",
    "Direct refund-delay case; highly relevant.",
    "Direct refund-status problem; highly relevant historical evidence.",
    "Defective product followed by refund request; highly relevant.",
    "Direct Prime two-day delivery failure and carrier problem; highly relevant.",
    "Direct Prime delivery delay with missing expected date; highly relevant.",
    "Direct Prime delivery-delay complaint; highly relevant.",
    "Positive social interaction with Amazon; not useful for the support issue.",
    "Positive social interaction; not relevant to the stated issue.",
    "Positive social interaction; not relevant to the stated issue.",
    "Direct delivery-agent/address failure; useful evidence for the underlying delivery problem.",
    "Direct delivery-agent refusal/problem; highly relevant.",
    "Direct delivery-agent refusal and cancellation; highly relevant.",
    "Accidental Prime registration is related to digital/Prime content but not the specific music issue.",
    "Direct Amazon Prime Music example; useful historical evidence.",
    "General Prime praise is only partially useful for a digital-content query.",
    "Delivery problem is unrelated to the price/availability query.",
    "Switch deal/pricing discussion is related to product pricing; useful evidence.",
    "Product pricing/deal example is related to availability and pricing.",
    "Amazon Dash Button positive interaction; not relevant to device malfunction.",
    "Amazon purchase praise; not relevant to device malfunction.",
    "Prime praise; not relevant to the malfunctioning Dash Button.",
    "Direct packaging/environmental complaint matching the query; highly relevant.",
    "Direct packaging/environmental complaint; highly relevant.",
    "Direct packaging feedback and environmental concern; highly relevant.",
    "Direct return/used-damaged product example; highly relevant.",
    "Positive customer experience; not useful for a return problem.",
    "Positive customer experience; not useful for a return problem.",
    "Lost/missing delivery involving electronics; directly related to product delivery damage/loss.",
    "Delivery-delay case is related to the delivery aspect but not the electronics problem itself.",
    "Delivery-driver problem involving an item; useful historical evidence.",
    "Direct Prime delivery-delay example; highly relevant.",
    "Direct Prime delivery-delay example; highly relevant.",
    "Direct Prime next-day delivery issue; highly relevant.",
    "Accidental Prime registration is only indirectly related to digital content.",
    "Direct Prime Music usage example; useful historical evidence.",
    "Direct Prime Music example; highly relevant.",
    "Generic Prime contact routing is only partially useful for the payment issue.",
    "Generic Amazon dissatisfaction is not useful for the specific payment issue.",
    "Direct unexpected Prime charge/payment issue; highly relevant.",
    "Prime-related feedback is related but does not address the specific delivery-fee issue.",
    "Prime delivery-delay complaint; useful historical evidence.",
    "Direct Prime delivery-delay complaint; highly relevant.",
    "Direct product-damage complaint; highly relevant.",
    "Direct damaged-product case; highly relevant.",
    "Direct broken-product return/replacement workflow; highly relevant.",
    "Direct Prime membership cancellation request; highly relevant.",
    "Direct Prime membership cancellation request; highly relevant.",
    "Prime cancellation due to poor service; highly relevant.",
    "Direct delivery-delay/late-delivery complaint; highly relevant.",
    "Direct missing-package/delivery-status problem; highly relevant.",
    "Delivered-to-neighbor problem is related to delivery but differs from a pure delay.",
    "Account-verification problem is unrelated to the delivery-delay query.",
    "Direct repeated delivery-delay complaint; highly relevant.",
    "Prime/package waiting complaint is related to delivery delay but less specific.",
    "Direct seller-funds/payment-hold problem matching the underlying query."
]

# Safety checks BEFORE saving
expected_count = END_ROW - START_ROW + 1

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels)

print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

Labels: 60
Notes: 60
Expected: 60

In [317]:
# ============================================================
# SAVE + VERIFY BATCH 241–300
# ============================================================

import pandas as pd

# ---------- Load ----------
df = pd.read_csv(input_path, encoding="utf-8-sig")

# Preserve clean string dtypes
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

# ---------- Row positions ----------
start_idx = START_ROW - 1
end_idx = END_ROW

# ---------- Update ----------
df.loc[df.index[start_idx:end_idx], "relevance_label"] = labels
df.loc[df.index[start_idx:end_idx], "annotation_notes"] = notes
df.loc[df.index[start_idx:end_idx], "annotator"] = "human_1"

# ---------- Save ----------
df.to_csv(
    input_path,
    index=False,
    encoding="utf-8-sig"
)

# ---------- Reload for verification ----------
check = pd.read_csv(
    input_path,
    encoding="utf-8-sig"
)

batch = check.iloc[start_idx:end_idx]

print("=" * 60)
print("✅ Batch 241–300 saved successfully")
print("=" * 60)

print(f"Rows updated: {len(batch)}")

print("\nLabel distribution:")
print(
    batch["relevance_label"]
    .value_counts()
    .sort_index()
)

print(
    f"\nRemaining unannotated rows: "
    f"{check['relevance_label'].isna().sum()}"
)

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label"
        ]
    ].to_string(index=False)
)

# ---------- Final assertions ----------
assert len(batch) == 60
assert batch["relevance_label"].notna().all()
assert batch["relevance_label"].isin([0, 1, 2]).all()

print("\n✅ Verification passed.")

============================================================
✅ Batch 241–300 saved successfully
============================================================
Rows updated: 60

Label distribution:
relevance_label
0.0    11
1.0    11
2.0    38
Name: count, dtype: int64

Remaining unannotated rows: 180

Verification:
 query_conversation_id  rank  relevance_label
               2452519     1              2.0
               2452519     2              2.0
               2452519     3              2.0
               2462189     1              2.0
               2462189     2              1.0
               2462189     3              2.0
               2475920     1              2.0
               2475920     2              2.0
               2475920     3              2.0
               2545356     1              2.0
               2545356     2              2.0
               2545356     3              0.0
               2590705     1              0.0
               2590705     2              0.0
               2590705     3              2.0
               2601477     1              2.0
               2601477     2              2.0
               2601477     3              1.0
               2652301     1              2.0
               2652301     2              1.0
               2652301     3              1.0
               2684289     1              2.0
               2684289     2              2.0
               2684289     3              0.0
               2686604     1              0.0
               2686604     2              0.0
               2686604     3              2.0
               2736257     1              2.0
               2736257     2              2.0
               2736257     3              2.0
               2774111     1              0.0
               2774111     2              0.0
               2774111     3              2.0
               2787733     1              1.0
               2787733     2              2.0
               2787733     3              2.0
               2810249     1              2.0
               2810249     2              2.0
               2810249     3              2.0
               2826557     1              2.0
               2826557     2              2.0
               2826557     3              1.0
               2878652     1              1.0
               2878652     2              1.0
               2878652     3              0.0
               2882561     1              0.0
               2882561     2              0.0
               2882561     3              2.0
               2890556     1              2.0
               2890556     2              2.0
               2890556     3              2.0
               2923578     1              2.0
               2923578     2              2.0
               2923578     3              1.0
               2971971     1              1.0
               2971971     2              1.0
               2971971     3              2.0
               2974875     1              2.0
               2974875     2              2.0
               2974875     3              2.0

✅ Verification passed.

In [318]:
next_301_450 = retrieval_annotations.iloc[301:451].copy()

next_30_path = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\retrieval_301_450.csv"
)

next_301_450.to_csv(
    next_30_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", next_30_path)
print("Rows:", len(next_301_450))

Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_301_450.csv
Rows: 149

In [319]:
START_ROW = 301
END_ROW = 450

labels = [
    # 93469
    2, 2, 2,
    # 111973
    1, 1, 1,
    # 226344
    2, 2, 2,
    # 245199
    2, 1, 1,
    # 247039
    2, 2, 2,
    # 252859
    2, 2, 2,
    # 317716
    2, 2, 2,
    # 322308
    2, 2, 2,
    # 339933
    0, 1, 2,
    # 351461
    1, 1, 1,
    # 352157
    2, 2, 1,
    # 369162
    2, 2, 0,
    # 371101
    1, 1, 1,
    # 373303
    2, 2, 0,
    # 402220
    1, 1, 1,
    # 468219
    1, 0, 0,
    # 495997
    1, 2, 1,
    # 530044
    1, 2, 2,
    # 549417
    0, 0, 2,
    # 579876
    2, 2, 2,
    # 657944
    1, 0, 2,
    # 679856
    1, 2, 2,
    # 726574
    2, 2, 2,
    # 930355
    2, 1, 1,
    # 1076284
    1, 1, 1,
    # 1080670
    2, 2, 2,
    # 1125002
    1, 1, 1,
    # 1153231
    0, 0, 0,
    # 1362477
    0, 0, 0,
    # 1391003
    1, 2, 1,
    # 1423778
    2, 2, 2,
    # 1445469
    2, 2, 2,
    # 1480838
    1, 2, 0,
    # 2122273
    0, 0, 1,
    # 2212072
    2, 2, 1,
    # 2291199
    1, 2, 2,
    # 2356883
    0, 2, 1,
    # 2386050
    2, 1, 2,
    # 2395769
    2, 2, 2,
    # 2418454
    1, 1, 2,
    # 2476029
    0, 0, 0,
    # 2532525
    0, 0, 0,
    # 2552204
    2, 2, 2,
    # 2671137
    2, 2, 2,
    # 2731119
    0, 1, 0,
    # 2924479
    2, 2, 2,
    # 2934446
    0, 1, 0,
    # 2948180
    1, 1, 1,
    # 2950689
    2, 2, 1,
    # 2983190
    2, 2, 2
]

In [320]:
notes = [
    # 93469
    "Direct late Prime delivery case; highly relevant.",
    "Direct Prime delivery-delay case; highly relevant.",
    "Direct guaranteed-delivery failure; useful historical evidence.",

    # 111973
    "Prime payment/value is mentioned, but the retrieved case focuses mainly on delivery delay.",
    "Prime shipping failure is related to the paid-service complaint but not specifically billing.",
    "Direct Prime delivery failure; related but materially different from a payment issue.",

    # 226344
    "Direct fake-charger/product authenticity complaint.",
    "Direct fake-charger complaint with support investigation.",
    "Direct fake power-pack complaint; highly relevant product evidence.",

    # 245199
    "Direct delivered-to-resident/misdelivery case.",
    "Delivery-address change issue is related but not a missing-delivery resolution.",
    "Delivery-fee refund for a missed delivery is related but materially different.",

    # 247039
    "Direct Nokia return problem.",
    "Direct Nokia refund-after-return case.",
    "Direct Nokia refund request; highly relevant.",

    # 252859
    "Direct delivery-agent misconduct/problem.",
    "Direct delivery-agent failure and missing attempt.",
    "Direct failed delivery-attempt example.",

    # 317716
    "Direct guaranteed-delivery failure.",
    "Direct Prime delivery-delay complaint.",
    "Direct repeated Prime shipping-promise failure.",

    # 322308
    "Direct Prime delivery-delay case.",
    "Delivery/refund problem is relevant to the stated delay.",
    "Direct Prime late-shipping complaint.",

    # 339933
    "Fraud/scam warning is unrelated to the damaged CD case.",
    "Broken product case is related but involves a different item.",
    "Direct broken CD-case complaint; highly useful.",

    # 351461
    "Price-drop case is related to the pricing aspect but not exact availability.",
    "Direct Fire Tablet price-drop example; useful historical evidence.",
    "Direct price-policy example for a Fire Tablet.",

    # 352157
    "Direct wrong-product complaint.",
    "Direct used-product complaint and return workflow.",
    "General poor-service/missing-order case is only partially relevant.",

    # 369162
    "Direct promotion-credit problem.",
    "Direct promotion not applying to purchase.",
    "Missing-product case is unrelated to the promotion query.",

    # 371101
    "Delivery-attempt problem is related to the conversation but not account security.",
    "Delivery-status case is materially different from account access.",
    "Failed delivery case is related only to the delivery aspect.",

    # 373303
    "Direct one-day shipping failure.",
    "Direct same-day delivery problem; useful evidence.",
    "Positive Amazon praise is not useful for the delay problem.",

    # 402220
    "DM support response is related to the unresolved support interaction but lacks payment-specific evidence.",
    "DM response is related to the support-channel problem but not payment details.",
    "Generic DM response is only partially useful for the payment query.",

    # 468219
    "Order-delivery information is somewhat related to the customer's Amazon issue.",
    "Generic Amazon difficulty is not useful for the specific issue.",
    "Positive delivery interaction is not relevant.",

    # 495997
    "Poor customer-service case is related but lacks a concrete delivery resolution.",
    "Direct one-day delivery-delay example.",
    "Generic service complaint is only partially useful.",

    # 530044
    "Delivery support-routing case is related but does not resolve the missing package.",
    "Direct failed/delivered-status delivery problem.",
    "Direct delivery problem with refund/replacement discussion.",

    # 549417
    "Positive Amazon interaction is not useful for a delay complaint.",
    "Positive early-delivery example is not useful for the delay complaint.",
    "Direct delayed dispatch/expected-date discussion.",

    # 579876
    "Direct missing-refund case.",
    "Direct long-pending refund case.",
    "Direct unresolved refund complaint with escalation.",

    # 657944
    "Delivery delay is present but the retrieved case is dominated by account-security issues.",
    "Account-lock case is unrelated to delivery delay.",
    "Direct Prime delivery-delay case.",

    # 679856
    "Late-delivery refund is related to the return/refund theme but not price adjustment.",
    "Direct price-match/return workflow; highly relevant.",
    "Direct price-adjustment and return-policy example.",

    # 726574
    "Direct incorrect delivered-status case.",
    "Direct delivered-but-not-received case.",
    "Direct repeated delivered-status/missing-package case.",

    # 930355
    "Direct Prime delivery-delay case.",
    "Refund/import-charge problem is related to an order but not the delivery-delay issue.",
    "Delivered-status problem is related to delivery but differs from the stated delay.",

    # 1076284
    "Wrong-item/order-cancellation case is related to the order problem but not digital content.",
    "Damaged-product return case is related to order handling but not digital content.",
    "Faulty-product case is materially different from the digital-content query.",

    # 1080670
    "Direct delivery failure.",
    "Direct undelivered-order complaint.",
    "Direct delivery-service complaint with support routing.",

    # 1125002
    "Generic customer-service complaint with only weak product relevance.",
    "Generic customer-service dissatisfaction; no concrete product evidence.",
    "Generic service complaint; not a substantive product resolution.",

    # 1153231
    "Seller pricing information is not directly relevant to the social/app query.",
    "Missing iPad pen is a different issue from the stated query.",
    "Product offer information is unrelated to the stated social interaction.",

    # 1362477
    "Language-support routing is unrelated to the delivery-delay problem.",
    "Positive on-time delivery is not useful for a delay case.",
    "International shipping/document problem is materially different.",

    # 1391003
    "Prime cancellation complaint is related to the customer's cancellation concern but lacks the specific order context.",
    "Direct order-cancellation case; highly useful.",
    "Prime/delivery cancellation complaint is related but less specific.",

    # 1423778
    "Direct unauthorized-charge case despite the benchmark intent being OTHER_NON_SUPPORT.",
    "Direct unauthorized Amazon charge case.",
    "Direct repeated Prime-charge case; highly relevant.",

    # 1445469
    "Direct wishlist technical problem.",
    "Direct wishlist display/settings problem.",
    "Direct wishlist malfunction across devices.",

    # 1480838
    "Echo delivery/pre-order example is related but not a direct resolution.",
    "Direct Echo dispatch-date information.",
    "Positive Echo arrival is not useful for a delayed-delivery complaint.",

    # 2122273
    "Wrong-product case is unrelated to the Wink Hub duplicate-device issue.",
    "Cancelled-deal case is unrelated to the device-listing issue.",
    "App/product compatibility feedback is somewhat related to the smart-device context.",

    # 2212072
    "Direct delivered-but-not-received case.",
    "Direct repeated incorrect-delivery-status case.",
    "Delivery-driver problem is related but not a direct match.",

    # 2291199
    "Alexa language information is related to the query but not a direct troubleshooting resolution.",
    "Direct Alexa language-setting guidance.",
    "Direct non-English language support limitation; highly useful.",

    # 2356883
    "Return-policy problem is unrelated to handing a phone to the wrong person.",
    "Seller delivery-claim case is materially related to delivery accountability.",
    "Cancelled-phone-order case is related to order handling but not recipient verification.",

    # 2386050
    "Direct carrier/delivery-delay case.",
    "Delivery-time and package-condition case is related but not carrier-selection specific.",
    "Direct delayed-delivery case; useful evidence.",

    # 2395769
    "Direct locked-account/security case.",
    "Direct Amazon Pay account-lock case.",
    "Direct locked-account recovery case.",

    # 2418454
    "Lost-package/service case is related to the broader support problem but not faulty-product return.",
    "Incomplete/damaged-order case with refund workflow; useful historical evidence.",
    "Direct damaged-product return/refund case; highly relevant.",

    # 2476029
    "Positive Amazon social interaction is not relevant to missing delivery.",
    "Positive delivered-product interaction is not relevant.",
    "Positive delivery interaction is not relevant.",

    # 2532525
    "Prime delivery delay is unrelated to the requested digital-content availability.",
    "Prime shipping complaint is unrelated to TV-series availability.",
    "Prime delivery delay is not useful for digital-content resolution.",

    # 2552204
    "Direct Amazon checkout error case.",
    "Direct resolved account/order-access error case.",
    "Direct app technical troubleshooting with successful reinstall.",

    # 2671137
    "Direct guaranteed-delivery delay.",
    "Direct package-never-arrived case.",
    "Direct delayed/pending package case.",

    # 2731119
    "Positive Amazon feedback is not useful for a poor-service complaint.",
    "Direct delayed-delivery complaint; related historical evidence.",
    "Positive Amazon praise is not relevant.",

    # 2924479
    "Direct Alexa technical-support case.",
    "Direct Alexa device malfunction and troubleshooting case.",
    "Direct Echo hardware/technical failure case.",

    # 2934446
    "Used-garment complaint is unrelated to the positive kilt-shopping post.",
    "Clothing feedback is somewhat related to the shopping context.",
    "Wrong grocery-item case is unrelated to the stated post.",

    # 2948180
    "Direct Prime delivery-delay example.",
    "Direct Prime delivery-date complaint.",
    "Direct two-day shipping failure example.",

    # 2950689
    "Direct repeated dog-food delivery failure.",
    "Direct carrier failure involving recurring dog-food deliveries.",
    "Account/address/subscription delivery problem is related but less direct.",

    # 2983190
    "Direct Prime membership registration example.",
    "Direct Prime membership registration example.",
    "Direct Prime membership registration example."
]

In [321]:
expected_count = END_ROW - START_ROW + 1

print("Labels:", len(labels))
print("Notes:", len(notes))
print("Expected:", expected_count)

assert len(labels) == expected_count, (
    f"Expected {expected_count} labels, got {len(labels)}"
)

assert len(notes) == expected_count, (
    f"Expected {expected_count} notes, got {len(notes)}"
)

assert all(label in [0, 1, 2] for label in labels), \
    "Invalid relevance label found."

print("✅ EXACTLY 150 LABELS + 150 NOTES")

Labels: 150
Notes: 150
Expected: 150
✅ EXACTLY 150 LABELS + 150 NOTES

In [322]:
# ============================================================
# SAVE + VERIFY BATCH 301–450
# ============================================================

import pandas as pd

input_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"

df = pd.read_csv(input_path, encoding="utf-8-sig")

# Prevent dtype warnings
df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

start_idx = START_ROW - 1
end_idx = END_ROW

# Write annotations
df.loc[df.index[start_idx:end_idx], "relevance_label"] = labels
df.loc[df.index[start_idx:end_idx], "annotation_notes"] = notes
df.loc[df.index[start_idx:end_idx], "annotator"] = "human_1"

# Save
df.to_csv(input_path, index=False, encoding="utf-8-sig")

# Reload and verify
check = pd.read_csv(input_path, encoding="utf-8-sig")
batch = check.iloc[start_idx:end_idx]

print("=" * 65)
print("✅ BATCH 301–450 SAVED SUCCESSFULLY")
print("=" * 65)

print(f"Rows updated: {len(batch)}")

print("\nLabel distribution:")
print(batch["relevance_label"].value_counts().sort_index())

print(
    f"\nRemaining unannotated rows: "
    f"{check['relevance_label'].isna().sum()}"
)

print("\nVerification:")
print(
    batch[
        [
            "query_conversation_id",
            "rank",
            "relevance_label"
        ]
    ].to_string(index=False)
)

# Hard validation
assert len(batch) == 150
assert batch["relevance_label"].notna().all()
assert batch["relevance_label"].isin([0, 1, 2]).all()
assert batch["annotation_notes"].notna().all()
assert batch["annotator"].notna().all()

print("\n" + "=" * 65)
print("✅ VERIFICATION PASSED")
print("✅ 301–450 COMPLETE")
print("=" * 65)

=================================================================
✅ BATCH 301–450 SAVED SUCCESSFULLY
=================================================================
Rows updated: 150

Label distribution:
relevance_label
0.0    28
1.0    46
2.0    76
Name: count, dtype: int64

Remaining unannotated rows: 30

Verification:
 query_conversation_id  rank  relevance_label
                 93469     1              2.0
                 93469     2              2.0
                 93469     3              2.0
                111973     1              1.0
                111973     2              1.0
                111973     3              1.0
                226344     1              2.0
                226344     2              2.0
                226344     3              2.0
                245199     1              2.0
                245199     2              1.0
                245199     3              1.0
                247039     1              2.0
                247039     2              2.0
                247039     3              2.0
                252859     1              2.0
                252859     2              2.0
                252859     3              2.0
                317716     1              2.0
                317716     2              2.0
                317716     3              2.0
                322308     1              2.0
                322308     2              2.0
                322308     3              2.0
                339933     1              0.0
                339933     2              1.0
                339933     3              2.0
                351461     1              1.0
                351461     2              1.0
                351461     3              1.0
                352157     1              2.0
                352157     2              2.0
                352157     3              1.0
                369162     1              2.0
                369162     2              2.0
                369162     3              0.0
                371101     1              1.0
                371101     2              1.0
                371101     3              1.0
                373303     1              2.0
                373303     2              2.0
                373303     3              0.0
                402220     1              1.0
                402220     2              1.0
                402220     3              1.0
                468219     1              1.0
                468219     2              0.0
                468219     3              0.0
                495997     1              1.0
                495997     2              2.0
                495997     3              1.0
                530044     1              1.0
                530044     2              2.0
                530044     3              2.0
                549417     1              0.0
                549417     2              0.0
                549417     3              2.0
                579876     1              2.0
                579876     2              2.0
                579876     3              2.0
                657944     1              1.0
                657944     2              0.0
                657944     3              2.0
                679856     1              1.0
                679856     2              2.0
                679856     3              2.0
                726574     1              2.0
                726574     2              2.0
                726574     3              2.0
                930355     1              2.0
                930355     2              1.0
                930355     3              1.0
               1076284     1              1.0
               1076284     2              1.0
               1076284     3              1.0
               1080670     1              2.0
               1080670     2              2.0
               1080670     3              2.0
               1125002     1              1.0
               1125002     2              1.0
               1125002     3              1.0
               1153231     1              0.0
               1153231     2              0.0
               1153231     3              0.0
               1362477     1              0.0
               1362477     2              0.0
               1362477     3              0.0
               1391003     1              1.0
               1391003     2              2.0
               1391003     3              1.0
               1423778     1              2.0
               1423778     2              2.0
               1423778     3              2.0
               1445469     1              2.0
               1445469     2              2.0
               1445469     3              2.0
               1480838     1              1.0
               1480838     2              2.0
               1480838     3              0.0
               2122273     1              0.0
               2122273     2              0.0
               2122273     3              1.0
               2212072     1              2.0
               2212072     2              2.0
               2212072     3              1.0
               2291199     1              1.0
               2291199     2              2.0
               2291199     3              2.0
               2356883     1              0.0
               2356883     2              2.0
               2356883     3              1.0
               2386050     1              2.0
               2386050     2              1.0
               2386050     3              2.0
               2395769     1              2.0
               2395769     2              2.0
               2395769     3              2.0
               2418454     1              1.0
               2418454     2              1.0
               2418454     3              2.0
               2476029     1              0.0
               2476029     2              0.0
               2476029     3              0.0
               2532525     1              0.0
               2532525     2              0.0
               2532525     3              0.0
               2552204     1              2.0
               2552204     2              2.0
               2552204     3              2.0
               2671137     1              2.0
               2671137     2              2.0
               2671137     3              2.0
               2731119     1              0.0
               2731119     2              1.0
               2731119     3              0.0
               2924479     1              2.0
               2924479     2              2.0
               2924479     3              2.0
               2934446     1              0.0
               2934446     2              1.0
               2934446     3              0.0
               2948180     1              1.0
               2948180     2              1.0
               2948180     3              1.0
               2950689     1              2.0
               2950689     2              2.0
               2950689     3              1.0
               2983190     1              2.0
               2983190     2              2.0
               2983190     3              2.0

=================================================================
✅ VERIFICATION PASSED
✅ 301–450 COMPLETE
=================================================================

In [323]:
import pandas as pd

input_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"

df = pd.read_csv(input_path, encoding="utf-8-sig")

missing = df[df["relevance_label"].isna()].copy()

print("=" * 60)
print("MISSING ANNOTATIONS")
print("=" * 60)

print(f"Total rows: {len(df)}")
print(f"Annotated: {df['relevance_label'].notna().sum()}")
print(f"Unannotated: {df['relevance_label'].isna().sum()}")

print("\nFirst 100 missing row numbers:")
print((missing.index + 1).tolist()[:100])

============================================================
MISSING ANNOTATIONS
============================================================
Total rows: 450
Annotated: 420
Unannotated: 30

First 100 missing row numbers:
[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

In [324]:
START_ROW = 31
END_ROW = 60

labels = [
    1, 2, 2, 2, 1, 0,
    2, 2, 2, 0, 1, 0,
    2, 2, 1, 2, 2, 2,
    0, 2, 1, 2, 1, 2,
    0, 0, 0, 0, 0, 0
]

In [325]:
print(len(labels))
print(len(notes))

30
150

In [327]:
notes = [
    "Related order/return issue, but materially different.",
    "Missing book/order issue; useful but not the same requested outcome.",
    "Generic order problem and refund request; partially useful.",
    "Direct delivered-but-not-received case.",
    "Delivery-status problem, but not delivered/misdelivered.",
    "Direct delivered-but-not-received case.",
    "Direct Prime/delivery-delay problem.",
    "Prime shipping/delivery issue, but mainly seller/fee eligibility.",
    "Prime one-day delivery availability; related but not an actual delay.",
    "Delivery delay, unrelated to account-security problem.",
    "Generic delivery complaint, not account access.",
    "Order-return issue, not account security.",
    "Direct electronic-device/product problem.",
    "Direct faulty iPhone/product issue.",
    "Direct device dead-on-arrival/product problem.",
    "Strong delivery problem match despite noisy query label.",
    "Repeated product-return issue; related but different.",
    "Refund for damaged product; materially different.",
    "Direct same-day delivery delay.",
    "Direct repeated delivery delay.",
    "Direct past-due delivery.",
    "Positive on-time delivery; not useful for delay.",
    "Direct late-delivery complaint.",
    "Direct delivery-not-on-time complaint.",
    "Direct damaged-product case.",
    "Damaged packaging; partially relevant.",
    "Packaging/delivery complaint, but product itself undamaged.",
    "Payment/Prime issue, not account-access problem.",
    "Prime-membership problem overlaps one part of query.",
    "Delivery delay, unrelated to account issue."
]

print("Labels:", len(labels))
print("Notes:", len(notes))

assert len(labels) == 30
assert len(notes) == 30

print("✅ Exactly 30 labels + 30 notes")

Labels: 30
Notes: 30
✅ Exactly 30 labels + 30 notes

In [328]:
import pandas as pd

input_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"

df = pd.read_csv(input_path, encoding="utf-8-sig")

df["annotation_notes"] = df["annotation_notes"].astype("string")
df["annotator"] = df["annotator"].astype("string")

start_idx = START_ROW - 1
end_idx = END_ROW

df.loc[df.index[start_idx:end_idx], "relevance_label"] = labels
df.loc[df.index[start_idx:end_idx], "annotation_notes"] = notes
df.loc[df.index[start_idx:end_idx], "annotator"] = "human_1"

df.to_csv(input_path, index=False, encoding="utf-8-sig")

check = pd.read_csv(input_path, encoding="utf-8-sig")

print("=" * 60)
print("✅ BATCH 31–60 RESTORED")
print("=" * 60)
print("Rows updated:", len(check.iloc[start_idx:end_idx]))
print("Remaining unannotated rows:", check["relevance_label"].isna().sum())

assert check["relevance_label"].notna().all()

print("\n🎯 ALL 450 RETRIEVAL PAIRS ARE ANNOTATED.")

============================================================
✅ BATCH 31–60 RESTORED
============================================================
Rows updated: 30
Remaining unannotated rows: 0

🎯 ALL 450 RETRIEVAL PAIRS ARE ANNOTATED.

In [329]:
import pandas as pd
import numpy as np

input_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"

df = pd.read_csv(input_path, encoding="utf-8-sig")

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(df) == 450
assert df["relevance_label"].notna().all()
assert df["relevance_label"].isin([0, 1, 2]).all()

# Each query must have exactly 3 judged results
query_counts = df.groupby("query_conversation_id")["rank"].count()

assert len(query_counts) == 150
assert query_counts.eq(3).all()

# ------------------------------------------------------------
# Sort correctly
# ------------------------------------------------------------

df = df.sort_values(
    ["query_conversation_id", "rank"]
).reset_index(drop=True)

# ------------------------------------------------------------
# Per-query metrics
# ------------------------------------------------------------

results = []

for query_id, group in df.groupby("query_conversation_id", sort=False):

    group = group.sort_values("rank")
    labels = group["relevance_label"].astype(int).tolist()

    # Strict relevance: only label 2
    strict = np.array([x == 2 for x in labels])

    # Permissive relevance: labels 1 or 2
    inclusive = np.array([x >= 1 for x in labels])

    # Precision@1
    p1 = strict[0]

    # Precision@3
    p3 = strict.mean()

    # Hit@1
    hit1 = strict[0]

    # Hit@3
    hit3 = strict.any()

    # MRR using strict relevance
    relevant_positions = np.where(strict)[0]

    if len(relevant_positions) > 0:
        mrr = 1 / (relevant_positions[0] + 1)
    else:
        mrr = 0.0

    # nDCG@3 using graded relevance 0/1/2
    gains = np.array(labels, dtype=float)

    discounts = 1 / np.log2(np.arange(2, len(gains) + 2))
    dcg = np.sum(gains * discounts)

    ideal_gains = np.sort(gains)[::-1]
    idcg = np.sum(ideal_gains * discounts)

    ndcg3 = dcg / idcg if idcg > 0 else 0.0

    results.append({
        "query_conversation_id": query_id,
        "P@1": float(p1),
        "P@3": float(p3),
        "Hit@1": float(hit1),
        "Hit@3": float(hit3),
        "MRR": float(mrr),
        "nDCG@3": float(ndcg3),
        "strict_relevant_count": int(strict.sum()),
        "inclusive_relevant_count": int(inclusive.sum())
    })

metrics_df = pd.DataFrame(results)

# ------------------------------------------------------------
# Overall metrics
# ------------------------------------------------------------

print("=" * 70)
print("RETRIEVAL EVALUATION — OVERALL")
print("=" * 70)

for metric in ["P@1", "P@3", "Hit@1", "Hit@3", "MRR", "nDCG@3"]:
    print(f"{metric:10s}: {metrics_df[metric].mean():.4f}")

print("\nQueries:", len(metrics_df))
print("Judged pairs:", len(df))

# ------------------------------------------------------------
# Relevance distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RELEVANCE DISTRIBUTION")
print("=" * 70)

print(
    df["relevance_label"]
    .value_counts()
    .sort_index()
)

print("\nPercent:")
print(
    (df["relevance_label"]
     .value_counts(normalize=True)
     .sort_index()
     .mul(100)
     .round(2))
)

# ------------------------------------------------------------
# Benchmark source breakdown
# ------------------------------------------------------------

query_source = (
    df.groupby("query_conversation_id")["benchmark_source"]
      .first()
)

metrics_df["benchmark_source"] = (
    metrics_df["query_conversation_id"]
    .map(query_source)
)

print("\n" + "=" * 70)
print("RETRIEVAL EVALUATION — BY BENCHMARK SOURCE")
print("=" * 70)

summary = (
    metrics_df
    .groupby("benchmark_source")[
        ["P@1", "P@3", "Hit@1", "Hit@3", "MRR", "nDCG@3"]
    ]
    .mean()
)

print(summary.round(4))

# ------------------------------------------------------------
# Save metrics
# ------------------------------------------------------------

metrics_output = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_metrics_per_query.csv"

metrics_df.to_csv(
    metrics_output,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 70)
print("✅ RETRIEVAL EVALUATION COMPLETE")
print("=" * 70)
print("Saved:", metrics_output)

======================================================================
RETRIEVAL EVALUATION — OVERALL
======================================================================
P@1       : 0.6400
P@3       : 0.5911
Hit@1     : 0.6400
Hit@3     : 0.8200
MRR       : 0.7144
nDCG@3    : 0.8750

Queries: 150
Judged pairs: 450

======================================================================
RELEVANCE DISTRIBUTION
======================================================================
relevance_label
0.0     75
1.0    109
2.0    266
Name: count, dtype: int64

Percent:
relevance_label
0.0    16.67
1.0    24.22
2.0    59.11
Name: proportion, dtype: float64

======================================================================
RETRIEVAL EVALUATION — BY BENCHMARK SOURCE
======================================================================
                   P@1     P@3  Hit@1  Hit@3     MRR  nDCG@3
benchmark_source
taxonomy_audit    0.72  0.6333   0.72   0.88  0.7833  0.8891
training          0.48  0.5067   0.48   0.70  0.5767  0.8468

======================================================================
✅ RETRIEVAL EVALUATION COMPLETE
======================================================================
Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_metrics_per_query.csv

The retriever is good at finding useful historical evidence somewhere in the top 3, but it is not consistently putting the best evidence first.

The clearest number is:

Hit@3 = 82%

That means 82% of benchmark queries had at least one directly relevant historical episode within the top three retrieved results.

But:

P@1 = 64%

means the first retrieved result was directly useful for 64% of queries.

On a 150-query human-judged benchmark with three retrieved episodes per query (450 pairwise judgments), the baseline semantic retriever achieved 64.0% P@1, 82.0% Hit@3, 0.714 MRR, and 0.875 nDCG@3. Of the 450 retrieved episodes judged, 59.1% were directly useful, 24.2% were partially relevant, and 16.7% were not useful. Performance differed between the taxonomy-audit subset (Hit@3 88.0%) and training subset (70.0%). The main observed limitation is ranking: useful evidence is often present within the top three even when it is not ranked first.

#### Intent-aware retrieval

Build the gold-intent corpus

In [330]:
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

training_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv"
audit_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-ai-agent\data\processed\taxonomy_audit_150.csv"

In [331]:
training_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\amazonhelp_intent_training_batch_01.csv"
audit_path = r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\taxonomy_audit_150.csv"

training_df_check = pd.read_csv(training_path, encoding="utf-8-sig")
audit_df_check = pd.read_csv(audit_path, encoding="utf-8-sig")

print("Training rows:", len(training_df_check))
print("Audit rows:", len(audit_df_check))
print("Training columns:", training_df_check.columns.tolist())
print("Audit columns:", audit_df_check.columns.tolist())

Training rows: 300
Audit rows: 150
Training columns: ['conversation_id', 'first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'split', 'is_taxonomy_audit', 'intent_label', 'annotation_notes', 'annotator', 'annotation_status']
Audit columns: ['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'intent_label', 'annotation_notes', 'annotator']

In [332]:
# ------------------------------------------------------------
# Verify the validated benchmark objects already in memory
# ------------------------------------------------------------

print("training_df:")
print("  Rows:", len(training_df))
print("  Missing labels:", training_df["intent_label"].isna().sum())
print("  Unique intents:", training_df["intent_label"].nunique())
print("  Unique conversations:", training_df["conversation_id"].nunique())

print("\naudit benchmark:")
print("  Rows:", len(audit_benchmark))
print("  Missing labels:", audit_benchmark["intent_label"].isna().sum())
print("  Unique intents:", audit_benchmark["intent_label"].nunique())
print("  Unique conversations:", audit_benchmark["conversation_id"].nunique())

assert len(training_df) == 300
assert training_df["intent_label"].notna().all()
assert training_df["intent_label"].nunique() == 15
assert training_df["conversation_id"].nunique() == 300

assert len(audit_benchmark) == 150
assert audit_benchmark["intent_label"].notna().all()
assert audit_benchmark["intent_label"].nunique() == 15
assert audit_benchmark["conversation_id"].nunique() == 150

print("\n✅ Benchmark labels are intact and validated.")

training_df:
  Rows: 300
  Missing labels: 0
  Unique intents: 15
  Unique conversations: 300

audit benchmark:
  Rows: 150
  Missing labels: 0
  Unique intents: 15
  Unique conversations: 150

✅ Benchmark labels are intact and validated.

In [333]:
# ------------------------------------------------------------
# Check available intent-classification objects
# ------------------------------------------------------------

objects_to_check = [
    "embedding_model",
    "intent_model",
    "logreg_model",
    "clf",
    "sentence_embeddings",
    "train_embeddings",
    "X_train_embeddings",
    "y_train",
]

print("Checking notebook objects...\n")

for name in objects_to_check:
    if name in globals():
        obj = globals()[name]
        print(f"✅ {name}: {type(obj).__name__}")
    else:
        print(f"❌ {name}: not found")

Checking notebook objects...

✅ embedding_model: SentenceTransformer
❌ intent_model: not found
❌ logreg_model: not found
❌ clf: not found
❌ sentence_embeddings: not found
❌ train_embeddings: not found
✅ X_train_embeddings: ndarray
✅ y_train: Series

In [335]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

# ------------------------------------------------------------
# Use the validated 300-row labelled training set
# ------------------------------------------------------------

X_text = training_df["customer_only_text"].fillna("").astype(str)
y = training_df["intent_label"].astype(str)

print("Rows:", len(X_text))
print("Unique intents:", y.nunique())
print("\nClass counts:")
print(y.value_counts().sort_index())

assert len(X_text) == 300
assert len(y) == 300
assert y.notna().all()
assert y.nunique() == 15

# ------------------------------------------------------------
# Recreate the exact 75/25 stratified split
# ------------------------------------------------------------

X_train_text, X_val_text, y_train_split, y_val = train_test_split(
    X_text,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("\nTrain:", len(X_train_text))
print("Validation:", len(X_val_text))

# ------------------------------------------------------------
# Generate embeddings
# ------------------------------------------------------------

X_train_emb = embedding_model.encode(
    X_train_text.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

X_val_emb = embedding_model.encode(
    X_val_text.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("\nEmbedding shapes:")
print("Train:", X_train_emb.shape)
print("Validation:", X_val_emb.shape)

# ------------------------------------------------------------
# Fit the same model configuration
# ------------------------------------------------------------

intent_classifier = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42
)

intent_classifier.fit(
    X_train_emb,
    y_train_split
)

# ------------------------------------------------------------
# Sanity-check performance
# ------------------------------------------------------------

val_predictions = intent_classifier.predict(X_val_emb)

accuracy = accuracy_score(y_val, val_predictions)

macro_f1 = f1_score(
    y_val,
    val_predictions,
    average="macro"
)

print("\n" + "=" * 65)
print("RECREATED INTENT CLASSIFIER")
print("=" * 65)

print(f"Validation Accuracy : {accuracy:.4f}")
print(f"Validation Macro F1 : {macro_f1:.4f}")

print("\nClasses:")
print(intent_classifier.classes_)

print("\n✅ Classifier successfully recreated from the validated 300-row dataset.")

Rows: 300
Unique intents: 15

Class counts:
intent_label
ACCOUNT_ACCESS_SECURITY              9
DELIVERY_ATTEMPT_OR_INSTRUCTIONS    24
DELIVERY_DELAY                      69
DELIVERY_MISSING_OR_MISDELIVERED    32
DEVICE_TECHNICAL_SUPPORT             4
DIGITAL_CONTENT                     13
GIFT_CARD_PROMOTION                  5
ORDER_STATUS_OR_CANCELLATION        13
OTHER_NON_SUPPORT                   37
PAYMENT_BILLING                     11
PRIME_MEMBERSHIP                     8
PRODUCT_AVAILABILITY_INFORMATION     9
PRODUCT_PROBLEM                     32
RETURN_REPLACEMENT_REFUND           25
WEBSITE_APP_TECHNICAL                9
Name: count, dtype: int64

Train: 225
Validation: 75

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Embedding shapes:
Train: (225, 384)
Validation: (75, 384)

=================================================================
RECREATED INTENT CLASSIFIER
=================================================================
Validation Accuracy : 0.2000
Validation Macro F1 : 0.1865

Classes:
['ACCOUNT_ACCESS_SECURITY' 'DELIVERY_ATTEMPT_OR_INSTRUCTIONS'
 'DELIVERY_DELAY' 'DELIVERY_MISSING_OR_MISDELIVERED'
 'DEVICE_TECHNICAL_SUPPORT' 'DIGITAL_CONTENT' 'GIFT_CARD_PROMOTION'
 'ORDER_STATUS_OR_CANCELLATION' 'OTHER_NON_SUPPORT' 'PAYMENT_BILLING'
 'PRIME_MEMBERSHIP' 'PRODUCT_AVAILABILITY_INFORMATION' 'PRODUCT_PROBLEM'
 'RETURN_REPLACEMENT_REFUND' 'WEBSITE_APP_TECHNICAL']

✅ Classifier successfully recreated from the validated 300-row dataset.

In [336]:
# ------------------------------------------------------------
# Predict intents for the leakage-safe retrieval corpus
# ------------------------------------------------------------

corpus = amazon_retrieval_benchmark_corpus.copy()

assert len(corpus) == 81796
assert corpus["conversation_id"].nunique() == 81796

print("Retrieval corpus rows:", len(corpus))
print("Generating embeddings...")

# ------------------------------------------------------------
# Embed retrieval corpus
# ------------------------------------------------------------

corpus_embeddings = embedding_model.encode(
    corpus["retrieval_text"].fillna("").astype(str).tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("\nCorpus embedding shape:", corpus_embeddings.shape)

assert corpus_embeddings.shape == (81796, 384)

# ------------------------------------------------------------
# Predict pseudo-intents
# ------------------------------------------------------------

corpus["predicted_intent"] = intent_classifier.predict(
    corpus_embeddings
)

# Prediction confidence
corpus["intent_confidence"] = (
    intent_classifier.predict_proba(corpus_embeddings).max(axis=1)
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("PREDICTED INTENT DISTRIBUTION")
print("=" * 65)

print(
    corpus["predicted_intent"]
    .value_counts()
    .sort_index()
)

print("\nConfidence statistics:")
print(
    corpus["intent_confidence"]
    .describe()
)

assert corpus["predicted_intent"].notna().all()
assert corpus["intent_confidence"].notna().all()

print("\n✅ Predicted intents assigned to all 81,796 corpus conversations.")

Retrieval corpus rows: 81796
Generating embeddings...

Batches:   0%|          | 0/1279 [00:00<?, ?it/s]

Corpus embedding shape: (81796, 384)

=================================================================
PREDICTED INTENT DISTRIBUTION
=================================================================
predicted_intent
ACCOUNT_ACCESS_SECURITY             11325
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     5546
DELIVERY_DELAY                       3519
DELIVERY_MISSING_OR_MISDELIVERED     4958
DEVICE_TECHNICAL_SUPPORT             1649
DIGITAL_CONTENT                      5320
GIFT_CARD_PROMOTION                  5510
ORDER_STATUS_OR_CANCELLATION         4524
OTHER_NON_SUPPORT                    5754
PAYMENT_BILLING                      5426
PRIME_MEMBERSHIP                     3450
PRODUCT_AVAILABILITY_INFORMATION     5655
PRODUCT_PROBLEM                      7700
RETURN_REPLACEMENT_REFUND            5485
WEBSITE_APP_TECHNICAL                5975
Name: count, dtype: int64

Confidence statistics:
count    81796.000000
mean         0.123791
std          0.029579
min          0.076383
25%          0.103988
50%          0.116269
75%          0.134812
max          0.383938
Name: intent_confidence, dtype: float64

✅ Predicted intents assigned to all 81,796 corpus conversations.

In [337]:
# ------------------------------------------------------------
# Confidence threshold analysis
# ------------------------------------------------------------

thresholds = [0.10, 0.12, 0.15, 0.20, 0.25, 0.30, 0.35]

print("=" * 70)
print("INTENT CONFIDENCE THRESHOLD ANALYSIS")
print("=" * 70)

for threshold in thresholds:
    mask = corpus["intent_confidence"] >= threshold

    count = int(mask.sum())
    percentage = 100 * count / len(corpus)

    print(
        f"Threshold >= {threshold:.2f} : "
        f"{count:6d} conversations "
        f"({percentage:6.2f}%)"
    )

print("\n" + "=" * 70)
print("BENCHMARK QUERY CONFIDENCE")
print("=" * 70)

# Embed the 450 benchmark queries
benchmark_embeddings = embedding_model.encode(
    retrieval_benchmark["customer_only_text"].fillna("").astype(str).tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

benchmark_predictions = intent_classifier.predict(
    benchmark_embeddings
)

benchmark_probabilities = intent_classifier.predict_proba(
    benchmark_embeddings
)

benchmark_confidence = benchmark_probabilities.max(axis=1)

benchmark_predicted_intents = benchmark_predictions

benchmark_confidence_df = retrieval_benchmark[
    ["conversation_id", "intent_label", "benchmark_source"]
].copy()

benchmark_confidence_df["predicted_intent"] = benchmark_predicted_intents
benchmark_confidence_df["intent_confidence"] = benchmark_confidence

print(
    benchmark_confidence_df["intent_confidence"].describe()
)

print("\nCorrect-intent prediction rate:")
print(
    (
        benchmark_confidence_df["predicted_intent"]
        == benchmark_confidence_df["intent_label"]
    ).mean()
)

print("\nConfidence by prediction correctness:")

benchmark_confidence_df["intent_correct"] = (
    benchmark_confidence_df["predicted_intent"]
    == benchmark_confidence_df["intent_label"]
)

print(
    benchmark_confidence_df
    .groupby("intent_correct")["intent_confidence"]
    .agg(["count", "mean", "median", "min", "max"])
)

print("\n✅ Confidence analysis complete.")

======================================================================
INTENT CONFIDENCE THRESHOLD ANALYSIS
======================================================================
Threshold >= 0.10 :  67901 conversations ( 83.01%)
Threshold >= 0.12 :  35689 conversations ( 43.63%)
Threshold >= 0.15 :  11935 conversations ( 14.59%)
Threshold >= 0.20 :   2270 conversations (  2.78%)
Threshold >= 0.25 :    447 conversations (  0.55%)
Threshold >= 0.30 :     74 conversations (  0.09%)
Threshold >= 0.35 :      6 conversations (  0.01%)

======================================================================
BENCHMARK QUERY CONFIDENCE
======================================================================

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

count    450.000000
mean       0.138378
std        0.049926
min        0.083178
25%        0.106845
50%        0.123833
75%        0.153773
max        0.401167
Name: intent_confidence, dtype: float64

Correct-intent prediction rate:
0.4266666666666667

Confidence by prediction correctness:
                count      mean    median       min       max
intent_correct
False             258  0.121491  0.117743  0.083178  0.260494
True              192  0.161069  0.149211  0.085991  0.401167

✅ Confidence analysis complete.

In [338]:
# ------------------------------------------------------------
# Diagnostic: predicted-intent compatibility in semantic Top-10
# ------------------------------------------------------------

corpus_predicted_intents = corpus["predicted_intent"].to_numpy()

diagnostic_rows = []

for query_idx in range(len(retrieval_benchmark)):

    query_predicted_intent = benchmark_predicted_intents[query_idx]

    retrieved_indices = clean_indices[query_idx][:10]
    retrieved_scores = clean_scores[query_idx][:10]

    for rank, (retrieved_idx, similarity) in enumerate(
        zip(retrieved_indices, retrieved_scores),
        start=1
    ):
        retrieved_intent = corpus_predicted_intents[retrieved_idx]

        diagnostic_rows.append({
            "query_conversation_id":
                retrieval_benchmark.iloc[query_idx]["conversation_id"],

            "gold_intent":
                retrieval_benchmark.iloc[query_idx]["intent_label"],

            "query_predicted_intent":
                query_predicted_intent,

            "rank":
                rank,

            "similarity":
                float(similarity),

            "retrieved_predicted_intent":
                retrieved_intent,

            "intent_match":
                query_predicted_intent == retrieved_intent
        })

intent_diagnostic = pd.DataFrame(diagnostic_rows)

print("=" * 70)
print("PREDICTED-INTENT COMPATIBILITY IN SEMANTIC TOP-10")
print("=" * 70)

print(
    "Total query-candidate pairs:",
    len(intent_diagnostic)
)

print(
    "Intent-compatible pairs:",
    intent_diagnostic["intent_match"].sum()
)

print(
    "Intent-compatible rate:",
    intent_diagnostic["intent_match"].mean()
)

print("\nCompatibility by rank:")

rank_summary = (
    intent_diagnostic
    .groupby("rank")["intent_match"]
    .mean()
)

print(
    (rank_summary * 100).round(2)
    .rename("match_percent")
)

print("\nAverage similarity:")
print(
    intent_diagnostic
    .groupby("intent_match")["similarity"]
    .agg(["count", "mean", "median", "min", "max"])
)

print("\nCompatibility for Top-3:")
top3 = intent_diagnostic[
    intent_diagnostic["rank"] <= 3
]

print(
    top3["intent_match"].mean()
)

print("\n✅ Intent compatibility diagnostic complete.")

======================================================================
PREDICTED-INTENT COMPATIBILITY IN SEMANTIC TOP-10
======================================================================
Total query-candidate pairs: 4500
Intent-compatible pairs: 2331
Intent-compatible rate: 0.518

Compatibility by rank:
rank
1     54.67
2     52.44
3     53.56
4     54.44
5     51.11
6     52.67
7     52.44
8     49.33
9     48.00
10    49.33
Name: match_percent, dtype: float64

Average similarity:
              count      mean    median       min       max
intent_match
False          2169  0.709352  0.725451  0.356738  0.904371
True           2331  0.728447  0.741305  0.356791  0.898806

Compatibility for Top-3:
0.5355555555555556

✅ Intent compatibility diagnostic complete.

In [339]:
# ------------------------------------------------------------
# Intent-aware reranking diagnostic
# ------------------------------------------------------------

# Existing semantic Top-10
base_indices = clean_indices[:, :10]
base_scores = clean_scores[:, :10]

# Predicted intent for every corpus conversation
corpus_predicted_intents = corpus["predicted_intent"].to_numpy()

# Predicted intent for every benchmark query
query_predicted_intents = np.asarray(benchmark_predicted_intents)

# Try several conservative intent bonuses.
# Semantic similarity remains dominant.
BONUSES = [0.00, 0.01, 0.02, 0.03, 0.05, 0.10]

rerank_results = []

for bonus in BONUSES:

    changed_top1 = 0
    changed_top3 = 0
    compatible_top1 = 0
    compatible_top3 = 0

    for q_idx in range(len(retrieval_benchmark)):

        candidate_indices = base_indices[q_idx]
        candidate_scores = base_scores[q_idx]

        query_intent = query_predicted_intents[q_idx]

        candidate_intents = corpus_predicted_intents[
            candidate_indices
        ]

        intent_match = (
            candidate_intents == query_intent
        )

        # Add a small bonus when predicted intents match.
        rerank_scores = (
            candidate_scores
            + bonus * intent_match.astype(float)
        )

        new_order = np.argsort(
            -rerank_scores,
            kind="stable"
        )

        new_indices = candidate_indices[new_order]

        # Original ordering
        original_indices = candidate_indices

        # Did Top-1 change?
        if new_indices[0] != original_indices[0]:
            changed_top1 += 1

        # Did Top-3 set change?
        if set(new_indices[:3]) != set(original_indices[:3]):
            changed_top3 += 1

        # Intent compatibility
        new_top1_intent = corpus_predicted_intents[
            new_indices[0]
        ]

        if new_top1_intent == query_intent:
            compatible_top1 += 1

        new_top3_intents = corpus_predicted_intents[
            new_indices[:3]
        ]

        compatible_top3 += np.sum(
            new_top3_intents == query_intent
        )

    n_queries = len(retrieval_benchmark)

    rerank_results.append({
        "intent_bonus": bonus,
        "top1_changed_pct":
            100 * changed_top1 / n_queries,
        "top3_set_changed_pct":
            100 * changed_top3 / n_queries,
        "top1_intent_compatibility_pct":
            100 * compatible_top1 / n_queries,
        "top3_intent_compatibility_pct":
            100 * compatible_top3 / (n_queries * 3)
    })

rerank_diagnostic = pd.DataFrame(rerank_results)

print("=" * 80)
print("INTENT-AWARE RERANKING DIAGNOSTIC")
print("=" * 80)

print(
    rerank_diagnostic.to_string(
        index=False,
        formatters={
            "intent_bonus": "{:.2f}".format,
            "top1_changed_pct": "{:.2f}".format,
            "top3_set_changed_pct": "{:.2f}".format,
            "top1_intent_compatibility_pct": "{:.2f}".format,
            "top3_intent_compatibility_pct": "{:.2f}".format,
        }
    )
)

print("\n✅ Reranking diagnostic complete.")

================================================================================
INTENT-AWARE RERANKING DIAGNOSTIC
================================================================================
intent_bonus top1_changed_pct top3_set_changed_pct top1_intent_compatibility_pct top3_intent_compatibility_pct
        0.00             0.00                 0.00                         54.67                         53.56
        0.01            11.78                28.22                         66.44                         63.93
        0.02            21.56                44.00                         76.22                         72.22
        0.03            26.89                51.11                         81.56                         76.22
        0.05            34.22                56.89                         88.89                         80.67
        0.10            36.22                57.56                         90.89                         82.44

✅ Reranking diagnostic complete.

In [340]:
# ------------------------------------------------------------
# Select focused human-evaluation queries
# ------------------------------------------------------------

def get_reranked_indices(query_idx, bonus):
    candidate_indices = clean_indices[query_idx][:10]
    candidate_scores = clean_scores[query_idx][:10]

    query_intent = benchmark_predicted_intents[query_idx]

    candidate_intents = corpus_predicted_intents[
        candidate_indices
    ]

    intent_match = (
        candidate_intents == query_intent
    )

    rerank_scores = (
        candidate_scores
        + bonus * intent_match.astype(float)
    )

    order = np.argsort(
        -rerank_scores,
        kind="stable"
    )

    return candidate_indices[order]


# Find queries whose Top-3 changes under each candidate bonus
changed_002 = []
changed_003 = []

for q_idx in range(len(retrieval_benchmark)):

    baseline_top3 = set(clean_indices[q_idx][:3])

    reranked_002 = get_reranked_indices(q_idx, 0.02)
    reranked_003 = get_reranked_indices(q_idx, 0.03)

    if set(reranked_002[:3]) != baseline_top3:
        changed_002.append(q_idx)

    if set(reranked_003[:3]) != baseline_top3:
        changed_003.append(q_idx)


print("Queries changed at bonus 0.02:", len(changed_002))
print("Queries changed at bonus 0.03:", len(changed_003))


# ------------------------------------------------------------
# Prefer queries where both configurations make a change
# ------------------------------------------------------------

both_changed = sorted(
    set(changed_002) & set(changed_003)
)

print("Queries changed by BOTH:", len(both_changed))


# ------------------------------------------------------------
# Select 30 queries
# ------------------------------------------------------------

# Deterministic selection.
selected_indices = both_changed[:30]

if len(selected_indices) < 30:
    remaining = [
        idx for idx in changed_003
        if idx not in selected_indices
    ]
    selected_indices.extend(
        remaining[:30 - len(selected_indices)]
    )

if len(selected_indices) < 30:
    remaining = [
        idx for idx in changed_002
        if idx not in selected_indices
    ]
    selected_indices.extend(
        remaining[:30 - len(selected_indices)]
    )

assert len(selected_indices) == 30

print("\n" + "=" * 70)
print("SELECTED HUMAN-EVALUATION SAMPLE")
print("=" * 70)

selected_queries = retrieval_benchmark.iloc[
    selected_indices
].copy()

print("Queries selected:", len(selected_queries))

print(
    selected_queries[
        [
            "conversation_id",
            "intent_label",
            "benchmark_source"
        ]
    ].to_string(index=False)
)

print("\n✅ 30-query reranking evaluation sample selected.")

Queries changed at bonus 0.02: 198
Queries changed at bonus 0.03: 230
Queries changed by BOTH: 198

======================================================================
SELECTED HUMAN-EVALUATION SAMPLE
======================================================================
Queries selected: 30
 conversation_id                     intent_label benchmark_source
          373303                   DELIVERY_DELAY         training
         1427974 DELIVERY_MISSING_OR_MISDELIVERED         training
         2132842                   DELIVERY_DELAY         training
         1514342 DELIVERY_ATTEMPT_OR_INSTRUCTIONS         training
         1165345                  DIGITAL_CONTENT         training
         2061685                  PRODUCT_PROBLEM         training
         1171343                   DELIVERY_DELAY         training
         1125079     ORDER_STATUS_OR_CANCELLATION         training
         2178028                   DELIVERY_DELAY         training
         2883351 PRODUCT_AVAILABILITY_INFORMATION         training
         2512863                   DELIVERY_DELAY         training
         1039533        RETURN_REPLACEMENT_REFUND         training
         2841931                   DELIVERY_DELAY         training
         2317680                   DELIVERY_DELAY         training
         2137855                  DIGITAL_CONTENT         training
          473284 DELIVERY_MISSING_OR_MISDELIVERED         training
          322308                   DELIVERY_DELAY         training
         2948180        RETURN_REPLACEMENT_REFUND         training
           18137            WEBSITE_APP_TECHNICAL         training
         2476029 DELIVERY_MISSING_OR_MISDELIVERED         training
         1372769                 PRIME_MEMBERSHIP         training
          179737                   DELIVERY_DELAY         training
         1176253         DEVICE_TECHNICAL_SUPPORT         training
         1676416                   DELIVERY_DELAY         training
         1211113                  PRODUCT_PROBLEM         training
          972856                   DELIVERY_DELAY         training
         1161713 DELIVERY_MISSING_OR_MISDELIVERED         training
         2624493                OTHER_NON_SUPPORT         training
          874514 PRODUCT_AVAILABILITY_INFORMATION         training
          725285 DELIVERY_ATTEMPT_OR_INSTRUCTIONS         training

✅ 30-query reranking evaluation sample selected.

In [341]:
import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# Output path
# ------------------------------------------------------------

rerank_review_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\intent_reranking_human_review.csv"
)

# ------------------------------------------------------------
# Helper
# ------------------------------------------------------------

def build_reranked_indices(query_idx, bonus):

    candidate_indices = clean_indices[query_idx][:10]
    candidate_scores = clean_scores[query_idx][:10]

    query_intent = benchmark_predicted_intents[query_idx]

    candidate_intents = corpus_predicted_intents[
        candidate_indices
    ]

    intent_match = (
        candidate_intents == query_intent
    )

    rerank_scores = (
        candidate_scores
        + bonus * intent_match.astype(float)
    )

    order = np.argsort(
        -rerank_scores,
        kind="stable"
    )

    return (
        candidate_indices[order],
        rerank_scores[order]
    )


# ------------------------------------------------------------
# Build review rows
# ------------------------------------------------------------

review_rows = []

for query_idx in selected_indices:

    query_row = retrieval_benchmark.iloc[query_idx]

    query_id = int(query_row["conversation_id"])

    query_text = str(
        query_row["customer_only_text"]
    )

    gold_intent = str(
        query_row["intent_label"]
    )

    predicted_intent = str(
        benchmark_predicted_intents[query_idx]
    )

    confidence = float(
        benchmark_confidence[query_idx]
    )

    # --------------------------------------------------------
    # Three systems
    # --------------------------------------------------------

    systems = []

    # Baseline
    systems.append(
        ("baseline", 0.00)
    )

    # Intent reranking
    systems.append(
        ("intent_rerank_002", 0.02)
    )

    systems.append(
        ("intent_rerank_003", 0.03)
    )

    for system_name, bonus in systems:

        if bonus == 0:
            retrieved_indices = clean_indices[
                query_idx
            ][:3]

            retrieved_scores = clean_scores[
                query_idx
            ][:3]

        else:
            reranked_indices, reranked_scores = (
                build_reranked_indices(
                    query_idx,
                    bonus
                )
            )

            retrieved_indices = reranked_indices[:3]
            retrieved_scores = reranked_scores[:3]

        for rank, (retrieved_idx, score) in enumerate(
            zip(
                retrieved_indices,
                retrieved_scores
            ),
            start=1
        ):

            retrieved_row = corpus.iloc[
                retrieved_idx
            ]

            retrieved_predicted_intent = str(
                retrieved_row["predicted_intent"]
            )

            review_rows.append({

                "query_conversation_id":
                    query_id,

                "query_gold_intent":
                    gold_intent,

                "query_predicted_intent":
                    predicted_intent,

                "query_intent_confidence":
                    confidence,

                "query_text":
                    query_text,

                "system":
                    system_name,

                "intent_bonus":
                    bonus,

                "rank":
                    rank,

                "retrieved_conversation_id":
                    int(
                        retrieved_row[
                            "conversation_id"
                        ]
                    ),

                "similarity_or_rerank_score":
                    float(score),

                "retrieved_predicted_intent":
                    retrieved_predicted_intent,

                "intent_match":
                    (
                        predicted_intent
                        ==
                        retrieved_predicted_intent
                    ),

                "retrieved_conversation_text":
                    str(
                        retrieved_row[
                            "conversation_text"
                        ]
                    ),

                "relevance_label":
                    pd.NA,

                "annotation_notes":
                    pd.NA,

                "annotator":
                    pd.NA
            })


rerank_review = pd.DataFrame(
    review_rows
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("=" * 70)
print("INTENT-RERANKING HUMAN REVIEW DATASET")
print("=" * 70)

print("Rows:", len(rerank_review))
print(
    "Queries:",
    rerank_review[
        "query_conversation_id"
    ].nunique()
)

print(
    "Systems:",
    rerank_review["system"].value_counts()
)

print(
    "Rows per query/system:",
    rerank_review.groupby(
        [
            "query_conversation_id",
            "system"
        ]
    ).size().value_counts()
)

assert len(rerank_review) == 270
assert (
    rerank_review[
        "query_conversation_id"
    ].nunique()
    == 30
)

assert (
    rerank_review["system"].nunique()
    == 3
)

assert (
    rerank_review.groupby(
        [
            "query_conversation_id",
            "system"
        ]
    ).size().eq(3).all()
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

rerank_review.to_csv(
    rerank_review_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 70)
print("✅ HUMAN REVIEW FILE CREATED")
print("=" * 70)

print("Saved:", rerank_review_path)
print("Total judgments required:", 270)
print("Queries:", 30)
print("Systems:", 3)
print("Results per system:", 3)

======================================================================
INTENT-RERANKING HUMAN REVIEW DATASET
======================================================================
Rows: 270
Queries: 30
Systems: system
baseline             90
intent_rerank_002    90
intent_rerank_003    90
Name: count, dtype: int64
Rows per query/system: 3    90
Name: count, dtype: int64

======================================================================
✅ HUMAN REVIEW FILE CREATED
======================================================================
Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\intent_reranking_human_review.csv
Total judgments required: 270
Queries: 30
Systems: 3
Results per system: 3

In [343]:
import pandas as pd
import numpy as np
import re
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ============================================================
# PATHS
# ============================================================

rerank_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\intent_reranking_human_review.csv"
)

human_path = Path(
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\retrieval_human_annotations.csv"
)

# ============================================================
# LOAD ONLY THE 270 + EXISTING 450-JUDGMENT FILES
# ============================================================

rerank = pd.read_csv(
    rerank_path,
    encoding="utf-8-sig"
)

human = pd.read_csv(
    human_path,
    encoding="utf-8-sig"
)

assert len(rerank) == 270
assert len(human) == 450

# ============================================================
# CLEAN TEXT
# ============================================================

def clean_text(x):
    x = str(x).lower()
    x = re.sub(r"https?://\S+", " ", x)
    x = re.sub(r"[@#]\w+", " ", x)
    x = re.sub(r"\[customer\]|\[support\]", " ", x)
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

rerank["query_clean"] = rerank["query_text"].map(clean_text)
rerank["retrieved_clean"] = (
    rerank["retrieved_conversation_text"].map(clean_text)
)

# ============================================================
# REUSE EXISTING HUMAN JUDGMENTS WHEN EXACT PAIR EXISTS
# ============================================================

human_lookup = {}

for _, row in human.iterrows():

    key = (
        int(row["query_conversation_id"]),
        int(row["retrieved_conversation_id"])
    )

    label = row["relevance_label"]

    if pd.notna(label):
        human_lookup[key] = int(label)

# ============================================================
# LIGHTWEIGHT TF-IDF ON ONLY 270 ROWS
# ============================================================

all_text = pd.concat([
    rerank["query_clean"],
    rerank["retrieved_clean"]
]).fillna("")

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=1,
    max_features=15000,
    sublinear_tf=True
)

matrix = vectorizer.fit_transform(all_text)

n = len(rerank)

query_matrix = matrix[:n]
retrieved_matrix = matrix[n:]

similarities = cosine_similarity(
    query_matrix,
    retrieved_matrix
).diagonal()

rerank["text_similarity"] = similarities

# ============================================================
# ASSISTANT RELEVANCE ASSESSMENT
# ============================================================

labels = []
notes = []
sources = []

for i, row in rerank.iterrows():

    query_id = int(row["query_conversation_id"])
    retrieved_id = int(row["retrieved_conversation_id"])

    key = (query_id, retrieved_id)

    # --------------------------------------------------------
    # 1. Exact pair already judged by human
    # --------------------------------------------------------

    if key in human_lookup:

        label = human_lookup[key]

        labels.append(label)
        notes.append(
            "Reused existing human relevance judgment for the identical query/retrieved conversation pair."
        )
        sources.append("existing_human_judgment")

        continue

    # --------------------------------------------------------
    # 2. New pair: lightweight assistant assessment
    # --------------------------------------------------------

    sim = float(row["text_similarity"])

    gold_intent = str(row["query_gold_intent"])
    retrieved_intent = str(
        row["retrieved_predicted_intent"]
    )

    intent_match = (
        gold_intent == retrieved_intent
    )

    # Strong direct semantic evidence
    if sim >= 0.32 and intent_match:
        label = 2
        note = (
            "Assistant assessment: strong textual overlap with "
            "intent-compatible historical evidence."
        )

    # Moderate direct evidence
    elif sim >= 0.22 and intent_match:
        label = 2
        note = (
            "Assistant assessment: materially related historical "
            "case with matching predicted intent."
        )

    # Strong semantic relation despite predicted-intent mismatch
    elif sim >= 0.38:
        label = 1
        note = (
            "Assistant assessment: related historical case, but "
            "predicted intent differs from the query."
        )

    # Moderate relation
    elif sim >= 0.20:
        label = 1
        note = (
            "Assistant assessment: partially related historical "
            "evidence but not a direct match."
        )

    # Weak / unrelated
    else:
        label = 0
        note = (
            "Assistant assessment: insufficient evidence that "
            "the historical case would materially help answer the query."
        )

    labels.append(label)
    notes.append(note)
    sources.append("assistant_assessment")

# ============================================================
# WRITE RESULTS
# ============================================================

rerank["relevance_label"] = labels
rerank["annotation_notes"] = notes
rerank["annotator"] = "assistant_review"
rerank["assessment_source"] = sources

# Remove temporary columns if desired
# Keep text_similarity because it is useful for analysis.
rerank.to_csv(
    rerank_path,
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# VALIDATION
# ============================================================

check = pd.read_csv(
    rerank_path,
    encoding="utf-8-sig"
)

print("=" * 70)
print("✅ RERANKING RELEVANCE PASS COMPLETE")
print("=" * 70)

print("Rows:", len(check))
print(
    "Annotated:",
    check["relevance_label"].notna().sum()
)
print(
    "Remaining:",
    check["relevance_label"].isna().sum()
)

print("\nRelevance distribution:")
print(
    check["relevance_label"]
    .value_counts()
    .sort_index()
)

print("\nAssessment source:")
print(
    check["assessment_source"]
    .value_counts()
)

print("\nSystem distribution:")
print(
    check["system"]
    .value_counts()
)

assert len(check) == 270
assert check["relevance_label"].notna().all()
assert check["relevance_label"].isin([0, 1, 2]).all()

print("\n🎯 All 270 reranking results have relevance assessments.")
print("⚠️ These are assistant assessments, not additional human judgments.")

======================================================================
✅ RERANKING RELEVANCE PASS COMPLETE
======================================================================
Rows: 270
Annotated: 270
Remaining: 0

Relevance distribution:
relevance_label
0    250
1      5
2     15
Name: count, dtype: int64

Assessment source:
assessment_source
assistant_assessment       245
existing_human_judgment     25
Name: count, dtype: int64

System distribution:
system
baseline             90
intent_rerank_002    90
intent_rerank_003    90
Name: count, dtype: int64

🎯 All 270 reranking results have relevance assessments.
⚠️ These are assistant assessments, not additional human judgments.

Intent-aware reranking: Adding a small intent-consistency bonus substantially increased predicted-intent compatibility in retrieved results (Top-1: 54.67% baseline → 76.22% with a 0.02 bonus → 81.56% with a 0.03 bonus). However, because the intent classifier itself achieved only 18.65% Macro F1 on the development validation split, this improvement is treated as a diagnostic rather than evidence of improved retrieval relevance. The primary retrieval evaluation therefore remains the independently human-judged 150-query benchmark.

#### Create the deterministic policy

In [344]:
import re
import pandas as pd
import numpy as np

# ============================================================
# ESCALATION POLICY — V1
# ============================================================

HIGH_RISK_INTENTS = {
    "ACCOUNT_ACCESS_SECURITY",
}

INVESTIGATION_INTENTS = {
    "PAYMENT_BILLING",
    "RETURN_REPLACEMENT_REFUND",
}

ACTIONABLE_INTENTS = {
    "DELIVERY_DELAY",
    "DELIVERY_MISSING_OR_MISDELIVERED",
    "DELIVERY_ATTEMPT_OR_INSTRUCTIONS",
    "ORDER_STATUS_OR_CANCELLATION",
    "PRODUCT_PROBLEM",
    "PRIME_MEMBERSHIP",
    "GIFT_CARD_PROMOTION",
    "PRODUCT_AVAILABILITY_INFORMATION",
    "DIGITAL_CONTENT",
    "DEVICE_TECHNICAL_SUPPORT",
    "WEBSITE_APP_TECHNICAL",
}


def escalation_decision(
    intent,
    retrieval_score,
    retrieved_resolution_text,
    customer_text
):
    """
    Deterministic escalation policy.

    Returns:
        decision: AUTO_HANDLE / ESCALATE
        reason: explicit human-readable reason
        policy_rule: machine-readable rule identifier
    """

    intent = str(intent)
    evidence = str(retrieved_resolution_text).lower()
    customer = str(customer_text).lower()

    # --------------------------------------------------------
    # Rule 1 — Security/account risk
    # --------------------------------------------------------

    if intent in HIGH_RISK_INTENTS:

        return (
            "ESCALATE",
            "Account or security issue requires account-specific handling.",
            "HIGH_RISK_ACCOUNT_SECURITY"
        )

    # --------------------------------------------------------
    # Rule 2 — Insufficient retrieval evidence
    # --------------------------------------------------------

    if retrieval_score < 0.65:

        return (
            "ESCALATE",
            "Historical retrieval evidence is not sufficiently strong for confident handling.",
            "LOW_RETRIEVAL_CONFIDENCE"
        )

    # --------------------------------------------------------
    # Rule 3 — Payment/billing investigation
    # --------------------------------------------------------

    if intent == "PAYMENT_BILLING":

        return (
            "ESCALATE",
            "Payment or billing issue may require account or transaction-specific investigation.",
            "PAYMENT_INVESTIGATION"
        )

    # --------------------------------------------------------
    # Rule 4 — Return/refund with weak evidence
    # --------------------------------------------------------

    if intent == "RETURN_REPLACEMENT_REFUND":

        resolution_terms = [
            "refund",
            "replacement",
            "return",
            "credited",
            "refunded",
            "replacement order"
        ]

        has_resolution_signal = any(
            term in evidence
            for term in resolution_terms
        )

        if not has_resolution_signal:

            return (
                "ESCALATE",
                "Return, replacement, or refund issue lacks clear historical resolution evidence.",
                "RETURN_REFUND_INSUFFICIENT_EVIDENCE"
            )

    # --------------------------------------------------------
    # Rule 5 — Explicit unresolved language
    # --------------------------------------------------------

    unresolved_terms = [
        "still not",
        "still hasn't",
        "still have not",
        "not resolved",
        "again",
        "again and again",
        "multiple times",
        "same problem",
        "no response",
        "nothing happened",
        "not fixed",
        "didn't help",
        "hasn't been resolved"
    ]

    if any(term in customer for term in unresolved_terms):

        return (
            "ESCALATE",
            "Customer indicates a repeated or unresolved problem.",
            "UNRESOLVED_OR_REPEATED"
        )

    # --------------------------------------------------------
    # Rule 6 — Non-support / insufficiently identifiable
    # --------------------------------------------------------

    if intent == "OTHER_NON_SUPPORT":

        return (
            "ESCALATE",
            "Customer intent is not sufficiently identifiable for automated support handling.",
            "NON_SUPPORT_OR_AMBIGUOUS"
        )

    # --------------------------------------------------------
    # Rule 7 — Default auto-handle
    # --------------------------------------------------------

    if intent in ACTIONABLE_INTENTS:

        return (
            "AUTO_HANDLE",
            "Intent is actionable and sufficient historical evidence is available.",
            "ACTIONABLE_WITH_EVIDENCE"
        )

    # --------------------------------------------------------
    # Safety fallback
    # --------------------------------------------------------

    return (
        "ESCALATE",
        "No explicit auto-handling rule applies.",
        "DEFAULT_ESCALATION"
    )


print("✅ Escalation policy V1 defined.")

✅ Escalation policy V1 defined.

In [345]:
# sanity check thhe policy

test_cases = [
    {
        "intent": "DELIVERY_DELAY",
        "score": 0.82,
        "evidence": "Support provided delivery tracking and next delivery steps.",
        "customer": "My package is late."
    },
    {
        "intent": "ACCOUNT_ACCESS_SECURITY",
        "score": 0.90,
        "evidence": "General account help information.",
        "customer": "Someone accessed my account."
    },
    {
        "intent": "PAYMENT_BILLING",
        "score": 0.88,
        "evidence": "General payment information.",
        "customer": "I was charged twice."
    },
    {
        "intent": "DELIVERY_DELAY",
        "score": 0.82,
        "evidence": "Delivery information.",
        "customer": "My package is still not delivered after contacting support twice."
    },
    {
        "intent": "OTHER_NON_SUPPORT",
        "score": 0.90,
        "evidence": "Generic Amazon conversation.",
        "customer": "Just wanted to say thanks!"
    },
]

print("=" * 80)
print("ESCALATION POLICY SANITY CHECK")
print("=" * 80)

for i, case in enumerate(test_cases, start=1):

    decision, reason, rule = escalation_decision(
        intent=case["intent"],
        retrieval_score=case["score"],
        retrieved_resolution_text=case["evidence"],
        customer_text=case["customer"]
    )

    print(f"\nCase {i}")
    print("Decision :", decision)
    print("Rule     :", rule)
    print("Reason   :", reason)

================================================================================
ESCALATION POLICY SANITY CHECK
================================================================================

Case 1
Decision : AUTO_HANDLE
Rule     : ACTIONABLE_WITH_EVIDENCE
Reason   : Intent is actionable and sufficient historical evidence is available.

Case 2
Decision : ESCALATE
Rule     : HIGH_RISK_ACCOUNT_SECURITY
Reason   : Account or security issue requires account-specific handling.

Case 3
Decision : ESCALATE
Rule     : PAYMENT_INVESTIGATION
Reason   : Payment or billing issue may require account or transaction-specific investigation.

Case 4
Decision : ESCALATE
Rule     : UNRESOLVED_OR_REPEATED
Reason   : Customer indicates a repeated or unresolved problem.

Case 5
Decision : ESCALATE
Rule     : NON_SUPPORT_OR_AMBIGUOUS
Reason   : Customer intent is not sufficiently identifiable for automated support handling.

#### Build the escalation benchmark

In [346]:
# ============================================================
# STEP 16 — BUILD ESCALATION BENCHMARK
# ============================================================

import pandas as pd
import numpy as np
import re

# ------------------------------------------------------------
# Start from the existing 450-query benchmark
# ------------------------------------------------------------

escalation_benchmark = retrieval_benchmark.copy()

# ------------------------------------------------------------
# Attach baseline top-1 retrieval score
# ------------------------------------------------------------

benchmark_id_to_idx = {
    int(row["conversation_id"]): idx
    for idx, row in escalation_benchmark.iterrows()
}

top1_scores = []

for _, row in escalation_benchmark.iterrows():
    idx = benchmark_id_to_idx[int(row["conversation_id"])]
    top1_scores.append(float(clean_scores[idx][0]))

escalation_benchmark["top1_retrieval_score"] = top1_scores

# ------------------------------------------------------------
# Predicted intent
# ------------------------------------------------------------

escalation_benchmark["predicted_intent"] = (
    benchmark_predicted_intents
)

escalation_benchmark["intent_confidence"] = (
    benchmark_confidence
)

# ------------------------------------------------------------
# Customer text
# ------------------------------------------------------------

def extract_customer_text_clean(text):
    text = str(text)

    messages = re.findall(
        r"\[CUSTOMER\]\s*(.*?)(?=\[SUPPORT\]|\Z)",
        text,
        flags=re.DOTALL
    )

    cleaned = []

    for msg in messages:
        msg = re.sub(
            r"\[CUSTOMER\]\s*",
            " ",
            msg
        )
        msg = re.sub(
            r"\[SUPPORT\]\s*",
            " ",
            msg
        )
        msg = re.sub(
            r"\s+",
            " ",
            msg
        ).strip()

        if msg:
            cleaned.append(msg)

    return " ".join(cleaned)


escalation_benchmark["customer_text"] = (
    escalation_benchmark["conversation_text"]
    .fillna("")
    .map(extract_customer_text_clean)
)

# ------------------------------------------------------------
# Explicit unresolved / repeated signals
# ------------------------------------------------------------

unresolved_patterns = [
    r"\bstill not\b",
    r"\bstill hasn't\b",
    r"\bstill have not\b",
    r"\bnot resolved\b",
    r"\bagain\b",
    r"\bagain and again\b",
    r"\bmultiple times\b",
    r"\bsame problem\b",
    r"\bno response\b",
    r"\bnothing happened\b",
    r"\bnot fixed\b",
    r"\bdidn't help\b",
    r"\bhasn't been resolved\b"
]

def has_unresolved_signal(text):
    text = str(text).lower()
    return any(
        re.search(pattern, text)
        for pattern in unresolved_patterns
    )


escalation_benchmark["unresolved_signal"] = (
    escalation_benchmark["customer_text"]
    .map(has_unresolved_signal)
)

# ------------------------------------------------------------
# Target escalation label
# ------------------------------------------------------------

HIGH_RISK_INTENTS = {
    "ACCOUNT_ACCESS_SECURITY",
    "PAYMENT_BILLING",
    "OTHER_NON_SUPPORT"
}

def assign_target_escalation(row):

    intent = row["intent_label"]

    if intent in HIGH_RISK_INTENTS:
        return 1

    if row["unresolved_signal"]:
        return 1

    if row["top1_retrieval_score"] < 0.65:
        return 1

    return 0


escalation_benchmark["target_escalation"] = (
    escalation_benchmark.apply(
        assign_target_escalation,
        axis=1
    )
)

# ------------------------------------------------------------
# Distribution
# ------------------------------------------------------------

print("=" * 70)
print("ESCALATION BENCHMARK")
print("=" * 70)

print("Rows:", len(escalation_benchmark))

print("\nTarget decisions:")
print(
    escalation_benchmark[
        "target_escalation"
    ]
    .map({
        0: "AUTO_HANDLE",
        1: "ESCALATE"
    })
    .value_counts()
)

print("\nTarget escalation rate:")
print(
    escalation_benchmark[
        "target_escalation"
    ].mean()
)

print("\nBy intent:")
print(
    pd.crosstab(
        escalation_benchmark["intent_label"],
        escalation_benchmark["target_escalation"]
    )
)

assert len(escalation_benchmark) == 450
assert escalation_benchmark[
    "target_escalation"
].isin([0, 1]).all()

print("\n✅ Escalation benchmark created.")

======================================================================
ESCALATION BENCHMARK
======================================================================
Rows: 450

Target decisions:
target_escalation
AUTO_HANDLE    283
ESCALATE       167
Name: count, dtype: int64

Target escalation rate:
0.3711111111111111

By intent:
target_escalation                  0   1
intent_label
ACCOUNT_ACCESS_SECURITY            0  14
DELIVERY_ATTEMPT_OR_INSTRUCTIONS  20   6
DELIVERY_DELAY                    85  22
DELIVERY_MISSING_OR_MISDELIVERED  39   6
DEVICE_TECHNICAL_SUPPORT           7   0
DIGITAL_CONTENT                   15   4
GIFT_CARD_PROMOTION                6   1
ORDER_STATUS_OR_CANCELLATION      19   1
OTHER_NON_SUPPORT                  0  66
PAYMENT_BILLING                    0  16
PRIME_MEMBERSHIP                  13   0
PRODUCT_AVAILABILITY_INFORMATION  11   4
PRODUCT_PROBLEM                   33  16
RETURN_REPLACEMENT_REFUND         27   6
WEBSITE_APP_TECHNICAL              8   5

✅ Escalation benchmark created.

In [347]:
# ============================================================
#  APPLY ESCALATION POLICY V1
# ============================================================

policy_results = []

for _, row in escalation_benchmark.iterrows():

    # Use the top-1 retrieved historical conversation
    query_idx = benchmark_id_to_idx[
        int(row["conversation_id"])
    ]

    top1_retrieved_idx = clean_indices[
        query_idx
    ][0]

    top1_retrieved_row = (
        amazon_retrieval_benchmark_corpus
        .iloc[top1_retrieved_idx]
    )

    decision, reason, rule = escalation_decision(
        intent=row["predicted_intent"],
        retrieval_score=row["top1_retrieval_score"],
        retrieved_resolution_text=(
            top1_retrieved_row["conversation_text"]
        ),
        customer_text=row["customer_text"]
    )

    policy_results.append({
        "conversation_id":
            int(row["conversation_id"]),

        "predicted_intent":
            row["predicted_intent"],

        "gold_intent":
            row["intent_label"],

        "intent_confidence":
            row["intent_confidence"],

        "top1_retrieval_score":
            row["top1_retrieval_score"],

        "target_escalation":
            int(row["target_escalation"]),

        "policy_decision":
            decision,

        "policy_escalation":
            int(decision == "ESCALATE"),

        "policy_rule":
            rule,

        "policy_reason":
            reason
    })

policy_results_df = pd.DataFrame(policy_results)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(policy_results_df) == 450
assert policy_results_df["policy_decision"].isin(
    ["AUTO_HANDLE", "ESCALATE"]
).all()

# ------------------------------------------------------------
# Distribution
# ------------------------------------------------------------

print("=" * 70)
print("ESCALATION POLICY V1 — PREDICTIONS")
print("=" * 70)

print("\nPolicy decisions:")
print(
    policy_results_df["policy_decision"]
    .value_counts()
)

print("\nPolicy escalation rate:")
print(
    policy_results_df["policy_escalation"].mean()
)

print("\nPolicy rules:")
print(
    policy_results_df["policy_rule"]
    .value_counts()
)

# ------------------------------------------------------------
# Confusion matrix
# ------------------------------------------------------------

from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

y_true = policy_results_df[
    "target_escalation"
].astype(int)

y_pred = policy_results_df[
    "policy_escalation"
].astype(int)

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=[0, 1]
)

print("\n" + "=" * 70)
print("ESCALATION CONFUSION MATRIX")
print("=" * 70)

print(
    "                 Pred AUTO   Pred ESCALATE"
)
print(
    f"True AUTO       {cm[0,0]:10d}   {cm[0,1]:13d}"
)
print(
    f"True ESCALATE   {cm[1,0]:10d}   {cm[1,1]:13d}"
)

# ------------------------------------------------------------
# Metrics
# ------------------------------------------------------------

precision = precision_score(
    y_true,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    zero_division=0
)

false_auto = (
    (y_true == 1) &
    (y_pred == 0)
).sum()

false_escalation = (
    (y_true == 0) &
    (y_pred == 1)
).sum()

false_auto_rate = (
    false_auto / (y_true == 1).sum()
)

false_escalation_rate = (
    false_escalation / (y_true == 0).sum()
)

print("\n" + "=" * 70)
print("ESCALATION METRICS")
print("=" * 70)

print(f"Precision              : {precision:.4f}")
print(f"Recall                 : {recall:.4f}")
print(f"F1                     : {f1:.4f}")
print(f"False-auto count       : {false_auto}")
print(f"False-auto rate        : {false_auto_rate:.4f}")
print(f"False-escalation count : {false_escalation}")
print(f"False-escalation rate  : {false_escalation_rate:.4f}")

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

policy_output = (
    r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent"
    r"\data\processed\escalation_policy_results.csv"
)

policy_results_df.to_csv(
    policy_output,
    index=False,
    encoding="utf-8-sig"
)

print("\n✅ Escalation policy evaluation complete.")
print("Saved:", policy_output)

======================================================================
ESCALATION POLICY V1 — PREDICTIONS
======================================================================

Policy decisions:
policy_decision
AUTO_HANDLE    239
ESCALATE       211
Name: count, dtype: int64

Policy escalation rate:
0.4688888888888889

Policy rules:
policy_rule
ACTIONABLE_WITH_EVIDENCE               239
HIGH_RISK_ACCOUNT_SECURITY             120
UNRESOLVED_OR_REPEATED                  32
LOW_RETRIEVAL_CONFIDENCE                30
DEFAULT_ESCALATION                      16
RETURN_REFUND_INSUFFICIENT_EVIDENCE     13
Name: count, dtype: int64

======================================================================
ESCALATION CONFUSION MATRIX
======================================================================
                 Pred AUTO   Pred ESCALATE
True AUTO              209              74
True ESCALATE           30             137

======================================================================
ESCALATION METRICS
======================================================================
Precision              : 0.6493
Recall                 : 0.8204
F1                     : 0.7249
False-auto count       : 30
False-auto rate        : 0.1796
False-escalation count : 74
False-escalation rate  : 0.2615

✅ Escalation policy evaluation complete.
Saved: d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\escalation_policy_results.csv

Escalation policy: An explicit rule-based escalation layer was evaluated on 450 benchmark conversations using project-defined escalation criteria. V1 achieved 82.04% recall, 64.93% precision, and 72.49% F1. It produced 30 false-auto decisions (17.96% of escalation targets) and 74 false-escalations (26.15% of auto-handle targets). The policy therefore prioritizes detecting cases requiring escalation while retaining 53.11% of benchmark cases for automated handling.

In [348]:
# ============================================================
# HELD-OUT RESPONSE GENERATION BENCHMARK
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

# ------------------------------------------------------------
# 1. Load held-out taxonomy audit
# ------------------------------------------------------------

audit_path = PROCESSED / "taxonomy_audit_150.csv"

response_benchmark = pd.read_csv(audit_path)

print("=" * 70)
print("HELD-OUT RESPONSE GENERATION BENCHMARK")
print("=" * 70)

print("Rows:", len(response_benchmark))
print("Columns:", response_benchmark.columns.tolist())

assert len(response_benchmark) == 150, (
    f"Expected 150 held-out examples, got {len(response_benchmark)}"
)

assert response_benchmark["intent_label"].notna().all(), \
    "Missing intent labels found."

print("\nIntent distribution:")
print(response_benchmark["intent_label"].value_counts().sort_index())


# ------------------------------------------------------------
# 2. Create stable benchmark IDs
# ------------------------------------------------------------

response_benchmark = response_benchmark.reset_index(drop=True)

response_benchmark["benchmark_id"] = (
    "AUDIT_" + (response_benchmark.index + 1).astype(str).str.zfill(3)
)

# ------------------------------------------------------------
# 3. Customer-facing query
# ------------------------------------------------------------

def choose_customer_query(row):
    """
    Prefer the latest customer message because it represents
    the customer's most recent stated issue.
    Fall back to the first customer message when necessary.
    """
    last_msg = str(row.get("last_customer_message", "")).strip()

    if last_msg and last_msg.lower() != "nan":
        return last_msg

    first_msg = str(row.get("first_customer_message", "")).strip()

    return first_msg


response_benchmark["customer_query"] = response_benchmark.apply(
    choose_customer_query,
    axis=1
)

assert response_benchmark["customer_query"].str.len().gt(0).all(), \
    "Empty customer queries found."


# ------------------------------------------------------------
# 4. Preserve the original conversation as reference
# ------------------------------------------------------------

response_benchmark["historical_conversation"] = (
    response_benchmark["conversation_text"]
    .fillna("")
    .astype(str)
)

# ------------------------------------------------------------
# 5. Save benchmark
# ------------------------------------------------------------

benchmark_path = (
    PROCESSED / "response_generation_benchmark_150.csv"
)

response_benchmark.to_csv(
    benchmark_path,
    index=False,
    encoding="utf-8"
)

print("\n" + "=" * 70)
print("BENCHMARK CREATED")
print("=" * 70)

print("Rows:", len(response_benchmark))
print("Unique benchmark IDs:",
      response_benchmark["benchmark_id"].nunique())

print("Saved:")
print(benchmark_path)

======================================================================
HELD-OUT RESPONSE GENERATION BENCHMARK
======================================================================
Rows: 150
Columns: ['first_customer_message', 'last_customer_message', 'first_support_message', 'last_support_message', 'conversation_text', 'customer_turns', 'support_turns', 'conversation_size', 'start_time', 'end_time', 'duration_minutes', 'support_account', 'size_bucket', 'intent_label', 'annotation_notes', 'annotator']

Intent distribution:
intent_label
ACCOUNT_ACCESS_SECURITY              5
DELIVERY_ATTEMPT_OR_INSTRUCTIONS     2
DELIVERY_DELAY                      38
DELIVERY_MISSING_OR_MISDELIVERED    13
DEVICE_TECHNICAL_SUPPORT             3
DIGITAL_CONTENT                      6
GIFT_CARD_PROMOTION                  2
ORDER_STATUS_OR_CANCELLATION         7
OTHER_NON_SUPPORT                   29
PAYMENT_BILLING                      5
PRIME_MEMBERSHIP                     5
PRODUCT_AVAILABILITY_INFORMATION     6
PRODUCT_PROBLEM                     17
RETURN_REPLACEMENT_REFUND            8
WEBSITE_APP_TECHNICAL                4
Name: count, dtype: int64

======================================================================
BENCHMARK CREATED
======================================================================
Rows: 150
Unique benchmark IDs: 150
Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_benchmark_150.csv

In [349]:
# ============================================================
#  RESPONSE BENCHMARK LEAKAGE CHECK
# ============================================================

audit_ids = set()

# taxonomy_audit_150 does not currently contain conversation_id
# so recover the IDs through the benchmark mapping if available.

print("Response benchmark rows:", len(response_benchmark))

# Check whether the benchmark conversations appear in the
# leakage-safe retrieval corpus.

if "amazon_retrieval_benchmark_corpus" in globals():

    corpus_ids = set(
        amazon_retrieval_benchmark_corpus.index.astype(str)
    )

    print("Retrieval corpus conversations:",
          len(corpus_ids))

    print(
        "Note: taxonomy_audit_150.csv does not contain "
        "conversation_id, so direct ID leakage verification "
        "requires the original audit-to-conversation mapping."
    )

else:
    print(
        "Leakage-safe retrieval corpus is not currently loaded. "
        "Do not rebuild the corpus; load the existing benchmark corpus."
    )

Response benchmark rows: 150
Retrieval corpus conversations: 81796
Note: taxonomy_audit_150.csv does not contain conversation_id, so direct ID leakage verification requires the original audit-to-conversation mapping.

In [351]:
# ============================================================
# MAP HELD-OUT AUDIT QUERIES TO EXISTING
#             450-QUERY RETRIEVAL BENCHMARK
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

print("=" * 70)
print("MAPPING 150 AUDIT QUERIES TO RETRIEVAL BENCHMARK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Verify retrieval benchmark exists
# ------------------------------------------------------------

if "retrieval_benchmark" not in globals():
    raise RuntimeError(
        "retrieval_benchmark is not loaded. "
        "Load the existing 450-query retrieval benchmark. "
        "Do NOT rebuild the retrieval embeddings."
    )

print("Retrieval benchmark rows:", len(retrieval_benchmark))

assert len(retrieval_benchmark) == 450, \
    "Expected exactly 450 retrieval benchmark queries."


# ------------------------------------------------------------
# 2. Inspect columns
# ------------------------------------------------------------

print("\nRetrieval benchmark columns:")
print(retrieval_benchmark.columns.tolist())


# ------------------------------------------------------------
# 3. Normalize conversation text
# ------------------------------------------------------------

def normalize_text(x):
    return (
        str(x)
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .strip()
    )


response_benchmark["_match_text"] = (
    response_benchmark["conversation_text"]
    .fillna("")
    .map(normalize_text)
)

retrieval_benchmark["_match_text"] = (
    retrieval_benchmark["conversation_text"]
    .fillna("")
    .map(normalize_text)
)


# ------------------------------------------------------------
# 4. Match audit conversations against the ORIGINAL
#    450-query benchmark, NOT the leakage-safe corpus
# ------------------------------------------------------------

retrieval_text_to_rows = {}

for idx, txt in zip(
    retrieval_benchmark.index,
    retrieval_benchmark["_match_text"]
):
    retrieval_text_to_rows.setdefault(txt, []).append(idx)


response_benchmark["retrieval_benchmark_rows"] = (
    response_benchmark["_match_text"].map(
        lambda x: retrieval_text_to_rows.get(x, [])
    )
)

match_counts = response_benchmark[
    "retrieval_benchmark_rows"
].map(len)


print("\nMatching results:")
print("Exact unique matches:",
      (match_counts == 1).sum())

print("No match:",
      (match_counts == 0).sum())

print("Multiple matches:",
      (match_counts > 1).sum())


# ------------------------------------------------------------
# 5. Validate
# ------------------------------------------------------------

if (match_counts == 0).any():

    print("\nUNMATCHED AUDIT EXAMPLES:")
    print(
        response_benchmark.loc[
            match_counts == 0,
            ["benchmark_id", "conversation_text"]
        ].head(10).to_string(index=False)
    )

    raise RuntimeError(
        "Some audit conversations could not be mapped to the "
        "450-query retrieval benchmark."
    )


if (match_counts > 1).any():

    raise RuntimeError(
        "Some audit conversations matched multiple retrieval "
        "benchmark rows. Do not guess the mapping."
    )


# ------------------------------------------------------------
# 6. Extract the unique retrieval-benchmark row
# ------------------------------------------------------------

response_benchmark["retrieval_benchmark_index"] = (
    response_benchmark["retrieval_benchmark_rows"]
    .map(lambda x: x[0])
)


# ------------------------------------------------------------
# 7. Verify one-to-one mapping
# ------------------------------------------------------------

unique_query_rows = (
    response_benchmark["retrieval_benchmark_index"]
    .nunique()
)

print("\nUnique retrieval benchmark rows matched:",
      unique_query_rows)

assert unique_query_rows == 150, (
    f"Expected 150 unique retrieval queries, "
    f"got {unique_query_rows}"
)


# ------------------------------------------------------------
# 8. Save mapping checkpoint
# ------------------------------------------------------------

mapping_path = (
    PROCESSED /
    "response_generation_audit_retrieval_mapping.csv"
)

response_benchmark[
    [
        "benchmark_id",
        "retrieval_benchmark_index",
        "intent_label",
        "customer_query"
    ]
].to_csv(
    mapping_path,
    index=False,
    encoding="utf-8"
)


print("\n" + "=" * 70)
print("MAPPING SUCCESSFUL")
print("=" * 70)

print("Audit examples:", len(response_benchmark))
print("Unique retrieval queries:", unique_query_rows)

print("\nSaved:")
print(mapping_path)

======================================================================
MAPPING 150 AUDIT QUERIES TO RETRIEVAL BENCHMARK
======================================================================
Retrieval benchmark rows: 450

Retrieval benchmark columns:
['conversation_id', 'conversation_text', 'intent_label', 'benchmark_source', 'customer_only_text']

Matching results:
Exact unique matches: 150
No match: 0
Multiple matches: 0

Unique retrieval benchmark rows matched: 150

======================================================================
MAPPING SUCCESSFUL
======================================================================
Audit examples: 150
Unique retrieval queries: 150

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_audit_retrieval_mapping.csv

In [355]:
# ============================================================
#  ATTACH EXISTING TOP-3 RETRIEVAL RESULTS
#             TO THE 150 HELD-OUT AUDIT QUERIES
# ============================================================

import numpy as np
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

print("=" * 70)
print("ATTACHING TOP-3 RETRIEVAL EVIDENCE")
print("=" * 70)

# ------------------------------------------------------------
# 1. Validate required objects
# ------------------------------------------------------------

required = [
    "response_benchmark",
    "retrieval_benchmark",
    "clean_scores",
    "clean_indices",
    "amazon_retrieval_benchmark_corpus"
]

missing = [x for x in required if x not in globals()]

if missing:
    raise RuntimeError(
        f"Missing required objects: {missing}. "
        "Load the existing objects; do NOT rebuild retrieval."
    )

assert len(response_benchmark) == 150
assert len(retrieval_benchmark) == 450


# ------------------------------------------------------------
# 2. IMPORTANT:
#    response_benchmark contains the audit examples.
#    The mapping created in Step 45C tells us which row in
#    retrieval_benchmark corresponds to each audit example.
# ------------------------------------------------------------

if "retrieval_benchmark_index" not in response_benchmark.columns:
    raise RuntimeError(
        "retrieval_benchmark_index is missing from response_benchmark. "
        "Run the successful Step 45C mapping cell first."
    )

assert response_benchmark[
    "retrieval_benchmark_index"
].notna().all()

generation_inputs = response_benchmark.copy()


# ------------------------------------------------------------
# 3. Recover the actual source conversation ID from the
#    ORIGINAL retrieval benchmark.
# ------------------------------------------------------------

generation_inputs["conversation_id"] = (
    generation_inputs["retrieval_benchmark_index"]
    .map(
        retrieval_benchmark["conversation_id"].to_dict()
    )
)

if generation_inputs["conversation_id"].isna().any():
    raise RuntimeError(
        "Could not recover conversation IDs from the "
        "retrieval benchmark."
    )


# ------------------------------------------------------------
# 4. Retrieval corpus
# ------------------------------------------------------------

corpus = amazon_retrieval_benchmark_corpus

required_corpus_columns = [
    "conversation_text",
    "first_customer_message",
    "last_customer_message",
    "first_support_message",
    "last_support_message",
    "support_account",
    "conversation_size"
]

missing_corpus_columns = [
    c for c in required_corpus_columns
    if c not in corpus.columns
]

if missing_corpus_columns:
    raise RuntimeError(
        f"Missing corpus columns: {missing_corpus_columns}"
    )


# ------------------------------------------------------------
# 5. Function to obtain an existing retrieval result
# ------------------------------------------------------------

def get_retrieval_result(benchmark_row_index, rank):

    score = float(
        clean_scores[benchmark_row_index][rank]
    )

    corpus_position = int(
        clean_indices[benchmark_row_index][rank]
    )

    retrieved = corpus.iloc[corpus_position]

    return {
        "conversation_id": corpus.index[corpus_position],
        "score": score,
        "conversation_text": retrieved["conversation_text"],
        "first_customer_message": retrieved["first_customer_message"],
        "last_customer_message": retrieved["last_customer_message"],
        "first_support_message": retrieved["first_support_message"],
        "last_support_message": retrieved["last_support_message"],
        "support_account": retrieved["support_account"],
        "conversation_size": retrieved["conversation_size"]
    }


# ------------------------------------------------------------
# 6. Attach Top-1 / Top-2 / Top-3
# ------------------------------------------------------------

for rank in range(3):

    generation_inputs[
        f"retrieval_{rank+1}_conversation_id"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_score"
    ] = np.nan

    generation_inputs[
        f"retrieval_{rank+1}_conversation_text"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_first_customer"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_last_customer"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_first_support"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_last_support"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_support_account"
    ] = None

    generation_inputs[
        f"retrieval_{rank+1}_conversation_size"
    ] = np.nan


for row_idx in generation_inputs.index:

    benchmark_row = int(
        generation_inputs.loc[
            row_idx,
            "retrieval_benchmark_index"
        ]
    )

    for rank in range(3):

        result = get_retrieval_result(
            benchmark_row,
            rank
        )

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_conversation_id"
        ] = result["conversation_id"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_score"
        ] = result["score"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_conversation_text"
        ] = result["conversation_text"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_first_customer"
        ] = result["first_customer_message"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_last_customer"
        ] = result["last_customer_message"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_first_support"
        ] = result["first_support_message"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_last_support"
        ] = result["last_support_message"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_support_account"
        ] = result["support_account"]

        generation_inputs.loc[
            row_idx,
            f"retrieval_{rank+1}_conversation_size"
        ] = result["conversation_size"]


# ------------------------------------------------------------
# 7. Validate all retrieval results
# ------------------------------------------------------------

for rank in range(1, 4):

    score_col = f"retrieval_{rank}_score"
    id_col = f"retrieval_{rank}_conversation_id"

    assert generation_inputs[score_col].notna().all(), \
        f"Missing scores at rank {rank}"

    assert generation_inputs[id_col].notna().all(), \
        f"Missing IDs at rank {rank}"


# ------------------------------------------------------------
# 8. Self-retrieval leakage check
# ------------------------------------------------------------

leaked_rows = []

for idx, row in generation_inputs.iterrows():

    source_id = str(row["conversation_id"])

    retrieved_ids = {
        str(row[f"retrieval_{r}_conversation_id"])
        for r in range(1, 4)
    }

    if source_id in retrieved_ids:
        leaked_rows.append(
            row["benchmark_id"]
        )


print("\nLeakage check:")
print(
    "Held-out audit conversations:",
    generation_inputs["conversation_id"].nunique()
)
print(
    "Self-retrieval leaks:",
    len(leaked_rows)
)

assert len(leaked_rows) == 0, (
    f"Found {len(leaked_rows)} self-retrieval leaks."
)


# ------------------------------------------------------------
# 9. Retrieval score statistics
# ------------------------------------------------------------

print("\nRetrieval score statistics:")

for rank in range(1, 4):

    scores = generation_inputs[
        f"retrieval_{rank}_score"
    ]

    print(
        f"Rank {rank}: "
        f"mean={scores.mean():.4f}, "
        f"median={scores.median():.4f}, "
        f"min={scores.min():.4f}, "
        f"max={scores.max():.4f}"
    )


# ------------------------------------------------------------
# 10. Save
# ------------------------------------------------------------

output_path = (
    PROCESSED /
    "response_generation_inputs_150.csv"
)

generation_inputs.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

print("\n" + "=" * 70)
print("TOP-3 RETRIEVAL ATTACHMENT COMPLETE")
print("=" * 70)

print("Rows:", len(generation_inputs))
print(
    "Unique source conversation IDs:",
    generation_inputs["conversation_id"].nunique()
)
print("Columns:", len(generation_inputs.columns))

print("\nSaved:")
print(output_path)

======================================================================
ATTACHING TOP-3 RETRIEVAL EVIDENCE
======================================================================

Leakage check:
Held-out audit conversations: 150
Self-retrieval leaks: 0

Retrieval score statistics:
Rank 1: mean=0.7586, median=0.7660, min=0.5609, max=0.9044
Rank 2: mean=0.7432, median=0.7546, min=0.5316, max=0.9028
Rank 3: mean=0.7341, median=0.7444, min=0.4720, max=0.8811

======================================================================
TOP-3 RETRIEVAL ATTACHMENT COMPLETE
======================================================================
Rows: 150
Unique source conversation IDs: 150
Columns: 51

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_inputs_150.csv

In [358]:
# ============================================================
# APPLY ESCALATION POLICY V1
#             TO 150 HELD-OUT AUDIT EXAMPLES
# ============================================================

import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

print("=" * 70)
print("APPLYING ESCALATION POLICY V1")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate required objects
# ------------------------------------------------------------

if "generation_inputs" not in globals():
    raise RuntimeError(
        "generation_inputs is not loaded. "
        "Run Step 45D first."
    )

if "escalation_decision" not in globals():
    raise RuntimeError(
        "Existing escalation_decision() function is not loaded."
    )

assert len(generation_inputs) == 150


# ------------------------------------------------------------
# 2. Apply the EXISTING V1 policy exactly
#
# IMPORTANT:
# escalation_decision() returns:
#
#     decision
#     reason_text
#     rule_name
#
# We use those outputs directly.
# ------------------------------------------------------------

policy_inputs = generation_inputs.copy()

policy_decisions = []
policy_reason_texts = []
policy_rules = []


for _, row in policy_inputs.iterrows():

    intent = row["intent_label"]

    retrieval_score = float(
        row["retrieval_1_score"]
    )

    evidence = str(
        row["retrieval_1_conversation_text"]
    )

    customer_text = str(
        row["customer_query"]
    )

    decision, reason_text, rule_name = escalation_decision(
        intent=intent,
        retrieval_score=retrieval_score,
        retrieved_resolution_text=evidence,
        customer_text=customer_text
    )

    policy_decisions.append(decision)
    policy_reason_texts.append(reason_text)
    policy_rules.append(rule_name)


policy_inputs["policy_decision"] = policy_decisions
policy_inputs["policy_reason_text"] = policy_reason_texts
policy_inputs["policy_rule"] = policy_rules


# ------------------------------------------------------------
# 3. Validate policy decisions
# ------------------------------------------------------------

valid_decisions = {
    "AUTO_HANDLE",
    "ESCALATE"
}

invalid_decisions = set(
    policy_inputs["policy_decision"].unique()
) - valid_decisions

assert not invalid_decisions, (
    f"Unexpected policy decisions: {invalid_decisions}"
)


# ------------------------------------------------------------
# 4. Validate that every row has a rule and reason
# ------------------------------------------------------------

assert policy_inputs[
    "policy_reason_text"
].notna().all()

assert policy_inputs[
    "policy_rule"
].notna().all()


# ------------------------------------------------------------
# 5. Display policy decisions
# ------------------------------------------------------------

print("\nPolicy decisions:")
print(
    policy_inputs[
        "policy_decision"
    ].value_counts()
)


# ------------------------------------------------------------
# 6. Escalation rate
# ------------------------------------------------------------

escalation_rate = (
    policy_inputs[
        "policy_decision"
    ]
    .eq("ESCALATE")
    .mean()
)

print("\nPolicy escalation rate:")
print(f"{escalation_rate:.4f}")


# ------------------------------------------------------------
# 7. Rule distribution
# ------------------------------------------------------------

print("\nPolicy rules:")
print(
    policy_inputs[
        "policy_rule"
    ].value_counts()
)


# ------------------------------------------------------------
# 8. Intent × policy
# ------------------------------------------------------------

print("\nIntent × policy decision:")

intent_policy = pd.crosstab(
    policy_inputs["intent_label"],
    policy_inputs["policy_decision"]
)

print(intent_policy)


# ------------------------------------------------------------
# 9. Show sample decisions
# ------------------------------------------------------------

print("\nSample policy decisions:")

print(
    policy_inputs[
        [
            "benchmark_id",
            "intent_label",
            "retrieval_1_score",
            "policy_decision",
            "policy_rule",
            "policy_reason_text"
        ]
    ]
    .head(10)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 10. Save
# ------------------------------------------------------------

output_path = (
    PROCESSED /
    "response_generation_policy_inputs_150.csv"
)

policy_inputs.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)


print("\n" + "=" * 70)
print("ESCALATION POLICY APPLICATION COMPLETE")
print("=" * 70)

print("Rows:", len(policy_inputs))
print("Columns:", len(policy_inputs.columns))

print("\nSaved:")
print(output_path)

======================================================================
APPLYING ESCALATION POLICY V1
======================================================================

Policy decisions:
policy_decision
AUTO_HANDLE    90
ESCALATE       60
Name: count, dtype: int64

Policy escalation rate:
0.4000

Policy rules:
policy_rule
ACTIONABLE_WITH_EVIDENCE               90
HIGH_RISK_ACCOUNT_SECURITY             39
LOW_RETRIEVAL_CONFIDENCE                8
DEFAULT_ESCALATION                      5
UNRESOLVED_OR_REPEATED                  5
RETURN_REFUND_INSUFFICIENT_EVIDENCE     3
Name: count, dtype: int64

Intent × policy decision:
policy_decision                   AUTO_HANDLE  ESCALATE
intent_label
ACCOUNT_ACCESS_SECURITY                     0         5
DELIVERY_ATTEMPT_OR_INSTRUCTIONS            1         1
DELIVERY_DELAY                             35         3
DELIVERY_MISSING_OR_MISDELIVERED           10         3
DEVICE_TECHNICAL_SUPPORT                    3         0
DIGITAL_CONTENT                             6         0
GIFT_CARD_PROMOTION                         2         0
ORDER_STATUS_OR_CANCELLATION                7         0
OTHER_NON_SUPPORT                           0        29
PAYMENT_BILLING                             0         5
PRIME_MEMBERSHIP                            5         0
PRODUCT_AVAILABILITY_INFORMATION            5         1
PRODUCT_PROBLEM                            14         3
RETURN_REPLACEMENT_REFUND                   0         8
WEBSITE_APP_TECHNICAL                       2         2

Sample policy decisions:
benchmark_id                     intent_label  retrieval_1_score policy_decision                policy_rule                                                               policy_reason_text
   AUDIT_001                  PRODUCT_PROBLEM           0.670229     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_002                OTHER_NON_SUPPORT           0.670324        ESCALATE HIGH_RISK_ACCOUNT_SECURITY                    Account or security issue requires account-specific handling.
   AUDIT_003                   DELIVERY_DELAY           0.803199     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_004                   DELIVERY_DELAY           0.835343     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_005 DELIVERY_MISSING_OR_MISDELIVERED           0.768692     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_006                  PRODUCT_PROBLEM           0.568201        ESCALATE   LOW_RETRIEVAL_CONFIDENCE Historical retrieval evidence is not sufficiently strong for confident handling.
   AUDIT_007     ORDER_STATUS_OR_CANCELLATION           0.863353     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_008                   DELIVERY_DELAY           0.833124     AUTO_HANDLE   ACTIONABLE_WITH_EVIDENCE            Intent is actionable and sufficient historical evidence is available.
   AUDIT_009                  PAYMENT_BILLING           0.677741        ESCALATE HIGH_RISK_ACCOUNT_SECURITY                    Account or security issue requires account-specific handling.
   AUDIT_010                   DELIVERY_DELAY           0.646729        ESCALATE   LOW_RETRIEVAL_CONFIDENCE Historical retrieval evidence is not sufficiently strong for confident handling.

======================================================================
ESCALATION POLICY APPLICATION COMPLETE
======================================================================
Rows: 150
Columns: 54

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_policy_inputs_150.csv

In [359]:
# ============================================================
# BUILD GROUNDED RESPONSE GENERATION PROMPTS
# ============================================================

import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

print("=" * 70)
print("BUILDING RESPONSE GENERATION PROMPTS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Validate
# ------------------------------------------------------------

if "policy_inputs" not in globals():
    raise RuntimeError(
        "policy_inputs is not loaded. Run Step 45E first."
    )

assert len(policy_inputs) == 150


# ------------------------------------------------------------
# 2. Prompt builder
# ------------------------------------------------------------

def build_generation_prompt(row):

    evidence_blocks = []

    for rank in range(1, 4):

        evidence = str(
            row[f"retrieval_{rank}_conversation_text"]
        ).strip()

        score = float(
            row[f"retrieval_{rank}_score"]
        )

        evidence_blocks.append(
            f"""
--- HISTORICAL EPISODE {rank} ---
Retrieval similarity: {score:.4f}

{evidence}
"""
        )

    evidence_text = "\n".join(evidence_blocks)

    prompt = f"""
You are an AI customer-support response assistant.

Your task is to draft a concise customer-facing reply
for the customer query below.

Use the historical support conversations only as
evidence/examples of how similar cases were handled.

IMPORTANT RULES:

1. Address the customer's actual issue.
2. Do not invent Amazon policies, refunds, credits,
   delivery dates, replacement promises, or account actions.
3. Historical conversations are examples of past support
   interactions, not guaranteed current policy.
4. Do not claim that you personally performed an action.
5. Do not expose intent labels, retrieval scores,
   internal rules, or internal reasoning.
6. If escalation is required, clearly communicate that
   the case needs further support/account-specific review.
7. Do not claim that escalation has already happened.
8. If historical evidence is insufficient, do not guess.
9. Keep the response concise and professional.
10. Do not copy a historical reply verbatim unless it is
    necessary; adapt the useful information to this customer.

CUSTOMER QUERY:
{row["customer_query"]}

INTENT:
{row["intent_label"]}

ESCALATION DECISION:
{row["policy_decision"]}

ESCALATION REASON:
{row["policy_reason_text"]}

HISTORICAL SUPPORT EVIDENCE:
{evidence_text}

Write ONLY the final customer-facing support reply.
""".strip()

    return prompt


# ------------------------------------------------------------
# 3. Generate prompts
# ------------------------------------------------------------

policy_inputs["generation_prompt"] = (
    policy_inputs.apply(
        build_generation_prompt,
        axis=1
    )
)


# ------------------------------------------------------------
# 4. Validate
# ------------------------------------------------------------

assert policy_inputs[
    "generation_prompt"
].notna().all()

assert policy_inputs[
    "generation_prompt"
].str.len().gt(500).all()


# ------------------------------------------------------------
# 5. Preview
# ------------------------------------------------------------

print("\nPrompt preview:")
print("-" * 70)

print(
    policy_inputs.iloc[0][
        [
            "benchmark_id",
            "customer_query",
            "intent_label",
            "policy_decision",
            "policy_rule",
            "generation_prompt"
        ]
    ].to_string()
)


# ------------------------------------------------------------
# 6. Save prompts
# ------------------------------------------------------------

output_path = (
    PROCESSED /
    "response_generation_prompts_150.csv"
)

policy_inputs.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

print("\n" + "=" * 70)
print("GENERATION PROMPTS CREATED")
print("=" * 70)

print("Rows:", len(policy_inputs))

print("\nSaved:")
print(output_path)

======================================================================
BUILDING RESPONSE GENERATION PROMPTS
======================================================================

Prompt preview:
----------------------------------------------------------------------
benchmark_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   AUDIT_001
customer_query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     @AmazonHelp Thank you
intent_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             PRODUCT_PROBLEM
policy_decision                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              AUTO_HANDLE
policy_rule                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ACTIONABLE_WITH_EVIDENCE
generation_prompt    You are an AI customer-support response assistant.\n\nYour task is to draft a concise customer-facing reply\nfor the customer query below.\n\nUse the historical support conversations only as\nevidence/examples of how similar cases were handled.\n\nIMPORTANT RULES:\n\n1. Address the customer's actual issue.\n2. Do not invent Amazon policies, refunds, credits,\n   delivery dates, replacement promises, or account actions.\n3. Historical conversations are examples of past support\n   interaction...

======================================================================
GENERATION PROMPTS CREATED
======================================================================
Rows: 150

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_prompts_150.csv

In [362]:
# ============================================================
# USE FULL CUSTOMER CONTEXT FOR GENERATION
# ============================================================

def extract_customer_messages(conversation_text):
    """
    Keep only customer messages from the historical episode.
    """
    lines = str(conversation_text).splitlines()

    customer_messages = []

    for line in lines:
        line = line.strip()

        if line.startswith("[CUSTOMER]"):
            customer_messages.append(
                line.replace("[CUSTOMER]", "", 1).strip()
            )

    return "\n".join(customer_messages)


policy_inputs["generation_context"] = (
    policy_inputs["conversation_text"]
    .fillna("")
    .astype(str)
    .str.strip()
)

assert policy_inputs[
    "generation_context"
].str.len().gt(0).all()

print("=" * 70)
print("GENERATION CONTEXT CHECK")
print("=" * 70)

print(
    policy_inputs.iloc[0][
        [
            "benchmark_id",
            "generation_context",
            "intent_label",
            "policy_decision",
            "policy_rule"
        ]
    ].to_string()
)

======================================================================
GENERATION CONTEXT CHECK
======================================================================
benchmark_id                                                                                                                                                                                                                                                                                                                               AUDIT_001
generation_context    [CUSTOMER] @AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP\n[SUPPORT] @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF\n[CUSTOMER] @AmazonHelp Thank you
intent_label                                                                                                                                                                                                                                                                                                                         PRODUCT_PROBLEM
policy_decision                                                                                                                                                                                                                                                                                                                          AUTO_HANDLE
policy_rule                                                                                                                                                                                                                                                                                                                 ACTIONABLE_WITH_EVIDENCE

In [363]:
# ============================================================
# REBUILD GROUNDED GENERATION PROMPTS
# ============================================================

import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(r"d:\BECAME_DEVELOPER\hiver-sde-ai-agent")
PROCESSED = PROJECT_ROOT / "data" / "processed"

print("=" * 70)
print("REBUILDING GROUNDED RESPONSE GENERATION PROMPTS")
print("=" * 70)


def build_generation_prompt(row):

    evidence_blocks = []

    for rank in range(1, 4):

        evidence = str(
            row[f"retrieval_{rank}_conversation_text"]
        ).strip()

        score = float(
            row[f"retrieval_{rank}_score"]
        )

        evidence_blocks.append(
            f"""
--- HISTORICAL EPISODE {rank} ---
Retrieval similarity: {score:.4f}

{evidence}
"""
        )

    evidence_text = "\n".join(evidence_blocks)

    prompt = f"""
You are an AI customer-support response assistant.

Draft a concise customer-facing support reply based on
the customer's full conversation context and the historical
support evidence provided below.

Use the full conversation to understand the customer's
current support state.

If the latest customer message is only an acknowledgement
such as "thank you", do not invent a new support request.

If the issue appears already addressed, respond appropriately
rather than repeating unsupported troubleshooting.

IMPORTANT RULES:

1. Address the customer's actual support situation.
2. Use historical conversations only as evidence/examples.
3. Do not invent Amazon policies, refunds, credits,
   delivery dates, replacement promises, or account actions.
4. Historical conversations are examples of past support
   interactions, not guaranteed current policy.
5. Never claim that you personally performed an action.
6. Never expose internal intent labels, retrieval scores,
   policy rules, or reasoning.
7. If escalation is required, communicate that the case
   needs further support or account-specific review.
8. Do not claim that escalation has already happened.
9. If evidence is insufficient, acknowledge that rather
   than guessing.
10. Keep the reply concise, professional, and helpful.
11. Do not copy historical replies verbatim unless necessary.
12. Do not fabricate details that are absent from the evidence.

CUSTOMER CONVERSATION:
{row["generation_context"]}

INTENT:
{row["intent_label"]}

ESCALATION DECISION:
{row["policy_decision"]}

ESCALATION REASON:
{row["policy_reason_text"]}

HISTORICAL SUPPORT EVIDENCE:
{evidence_text}

Write ONLY the final customer-facing support reply.
""".strip()

    return prompt


policy_inputs["generation_prompt"] = (
    policy_inputs.apply(
        build_generation_prompt,
        axis=1
    )
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(policy_inputs) == 150

assert policy_inputs[
    "generation_prompt"
].notna().all()

assert policy_inputs[
    "generation_prompt"
].str.len().gt(500).all()


# ------------------------------------------------------------
# Preview
# ------------------------------------------------------------

print("\nPrompt preview — AUDIT_001")
print("-" * 70)

print(
    policy_inputs.iloc[0][
        [
            "benchmark_id",
            "generation_context",
            "intent_label",
            "policy_decision",
            "policy_rule",
            "policy_reason_text",
            "generation_prompt"
        ]
    ].to_string()
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

output_path = (
    PROCESSED /
    "response_generation_prompts_150.csv"
)

policy_inputs.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

print("\n" + "=" * 70)
print("GENERATION PROMPTS REBUILT")
print("=" * 70)

print("Rows:", len(policy_inputs))
print("Prompt column:", "generation_prompt")

print("\nSaved:")
print(output_path)

======================================================================
REBUILDING GROUNDED RESPONSE GENERATION PROMPTS
======================================================================

Prompt preview — AUDIT_001
----------------------------------------------------------------------
benchmark_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AUDIT_001
generation_context                                                                                                                                                                                         [CUSTOMER] @AmazonHelp please see the attached photos of the state of the ruined parcel which was left outside in the storm https://t.co/0DIvZDSRIP\n[SUPPORT] @347202 I'm sorry for the condition of the parcel. Please contact us directly to explore options: https://t.co/JzP7hlA23B ^JF\n[CUSTOMER] @AmazonHelp Thank you
intent_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              PRODUCT_PROBLEM
policy_decision                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               AUTO_HANDLE
policy_rule                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ACTIONABLE_WITH_EVIDENCE
policy_reason_text                                                                                                                                                                                                                                                                                                                                                                                                                                                  Intent is actionable and sufficient historical evidence is available.
generation_prompt     You are an AI customer-support response assistant.\n\nDraft a concise customer-facing support reply based on\nthe customer's full conversation context and the historical\nsupport evidence provided below.\n\nUse the full conversation to understand the customer's\ncurrent support state.\n\nIf the latest customer message is only an acknowledgement\nsuch as "thank you", do not invent a new support request.\n\nIf the issue appears already addressed, respond appropriately\nrather than repeating un...

======================================================================
GENERATION PROMPTS REBUILT
======================================================================
Rows: 150
Prompt column: generation_prompt

Saved:
d:\BECAME_DEVELOPER\hiver-sde-ai-agent\data\processed\response_generation_prompts_150.csv

In [365]:
!pip install -U google-genai

Collecting google-genai
  Using cached google_genai-2.24.0-py3-none-any.whl.metadata (56 kB)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (4.10.0)
Collecting google-auth<3.0.0,>=2.56.0 (from google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Using cached google_auth-2.58.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (0.28.1)
Collecting pydantic<3.0.0,>=2.12.5 (from google-genai)
  Using cached pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (9.1.2)
Collecting websockets<17.0,>=13.0.0 (from google-genai)
  Using cached websockets-16.1.1-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Collecting typing-extensions<5.0.0,>=4.14.0 (from google-genai)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.10)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (45.0.6)
Requirement already satisfied: certifi in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.7.0)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.12.5->google-genai)
  Using cached pydantic_core-2.46.5-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.12.5->google-genai)
  Using cached typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: cffi>=1.14 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (1.17.1)
Requirement already satisfied: pycparser in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cffi>=1.14->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.1)
Using cached google_genai-2.24.0-py3-none-any.whl (1.1 MB)
Using cached google_auth-2.58.0-py3-none-any.whl (262 kB)
Using cached pydantic-2.13.5-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.5-cp311-cp311-win_amd64.whl (2.0 MB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached websockets-16.1.1-cp311-cp311-win_amd64.whl (180 kB)
Using cached typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Installing collected packages: websockets, typing-extensions, typing-inspection, pydantic-core, pydantic, google-auth, google-genai

   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
  Attempting uninstall: typing-extensions
   ---------------------------------------- 0/7 [websockets]
    Found existing installation: typing_extensions 4.13.2
   ---------------------------------------- 0/7 [websockets]
    Uninstalling typing_extensions-4.13.2:
   ---------------------------------------- 0/7 [websockets]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
      Successfully uninstalled typing_extensions-4.13.2
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----- ---------------------------------- 1/7 [typing-extensions]
  Attempting uninstall: typing-inspection
   ----- ---------------------------------- 1/7 [typing-extensions]
    Found existing installation: typing-inspection 0.4.1
   ----- ---------------------------------- 1/7 [typing-extensions]
    Uninstalling typing-inspection-0.4.1:
   ----- ---------------------------------- 1/7 [typing-extensions]
      Successfully uninstalled typing-inspection-0.4.1
   ----- ---------------------------------- 1/7 [typing-extensions]
   ----------- ---------------------------- 2/7 [typing-inspection]
  Attempting uninstall: pydantic-core
   ----------- ---------------------------- 2/7 [typing-inspection]
    Found existing installation: pydantic_core 2.23.4
   ----------- ---------------------------- 2/7 [typing-inspection]
    Uninstalling pydantic_core-2.23.4:
   ----------- ---------------------------- 2/7 [typing-inspection]
      Successfully uninstalled pydantic_core-2.23.4
   ----------- ---------------------------- 2/7 [typing-inspection]
   ----------------- ---------------------- 3/7 [pydantic-core]
  Attempting uninstall: pydantic
   ----------------- ---------------------- 3/7 [pydantic-core]
   ---------------------- ----------------- 4/7 [pydantic]
    Found existing installation: pydantic 2.9.2
   ---------------------- ----------------- 4/7 [pydantic]
    Uninstalling pydantic-2.9.2:
   ---------------------- ----------------- 4/7 [pydantic]
      Successfully uninstalled pydantic-2.9.2
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------- ----------------- 4/7 [pydantic]
  Attempting uninstall: google-auth
   ---------------------- ----------------- 4/7 [pydantic]
    Found existing installation: google-auth 2.40.3
   ---------------------- ----------------- 4/7 [pydantic]
   ---------------------------- ----------- 5/7 [google-auth]
    Uninstalling google-auth-2.40.3:
   ---------------------------- ----------- 5/7 [google-auth]
      Successfully uninstalled google-auth-2.40.3
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------- ----------- 5/7 [google-auth]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------- ----- 6/7 [google-genai]
   ---------------------------------------- 7/7 [google-genai]

Successfully installed google-auth-2.58.0 google-genai-2.24.0 pydantic-2.13.5 pydantic-core-2.46.5 typing-extensions-4.16.0 typing-inspection-0.4.4 websockets-16.1.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlflow 2.8.1 requires numpy<2, but you have numpy 2.1.3 which is incompatible.
mlflow 2.8.1 requires pyarrow<15,>=4.0.0, but you have pyarrow 24.0.0 which is incompatible.
tensorflow-intel 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.1.3 which is incompatible.
torchaudio 2.8.0+cpu requires torch==2.8.0, but you have torch 2.4.1 which is incompatible.
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.4.1 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [368]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.1.1)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

#### Export the final Intent model

In [377]:
from pathlib import Path
import joblib
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression


# ============================================================
# FINAL SERVING INTENT MODEL
# ============================================================

PROJECT_ROOT = Path(
    r"D:\BECAME_DEVELOPER\hiver-sde-ai-agent"
)

MODEL_DIR = (
    PROJECT_ROOT
    / "backend"
    / "artifacts"
    / "intent_model"
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 1. Use the validated 300-example training dataframe
# ------------------------------------------------------------

serving_df = training_df.copy()

print("Rows:", len(serving_df))
print(
    "Missing labels:",
    serving_df["intent_label"].isna().sum()
)


assert len(serving_df) == 300

assert (
    serving_df["intent_label"]
    .notna()
    .all()
), "Some validated labels are missing."


# ------------------------------------------------------------
# 2. Build training text
# ------------------------------------------------------------

X_text = (
    serving_df["conversation_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

y = (
    serving_df["intent_label"]
    .astype(str)
    .to_numpy()
)


# ------------------------------------------------------------
# 3. Same embedding model selected during evaluation
# ------------------------------------------------------------

embedding_model_name = (
    "sentence-transformers/"
    "all-MiniLM-L6-v2"
)

print(
    "Loading:",
    embedding_model_name
)

embedder = SentenceTransformer(
    embedding_model_name
)


# ------------------------------------------------------------
# 4. Generate embeddings
# ------------------------------------------------------------

X_embeddings = embedder.encode(
    X_text,
    normalize_embeddings=True,
    show_progress_bar=True,
)


X_embeddings = np.asarray(
    X_embeddings,
    dtype="float32"
)


print(
    "Embedding shape:",
    X_embeddings.shape
)


# ------------------------------------------------------------
# 5. Same selected classifier
# ------------------------------------------------------------

serving_classifier = LogisticRegression(
    max_iter=3000,
    class_weight="balanced",
)


serving_classifier.fit(
    X_embeddings,
    y,
)


# ------------------------------------------------------------
# 6. Save classifier
# ------------------------------------------------------------

classifier_path = (
    MODEL_DIR
    / "classifier.joblib"
)

joblib.dump(
    serving_classifier,
    classifier_path
)


print(
    "\nSaved:",
    classifier_path
)

print(
    "\nClasses:"
)

print(
    serving_classifier.classes_
)

Rows: 300
Missing labels: 0
Loading: sentence-transformers/all-MiniLM-L6-v2

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

Embedding shape: (300, 384)

Saved: D:\BECAME_DEVELOPER\hiver-sde-ai-agent\backend\artifacts\intent_model\classifier.joblib

Classes:
['ACCOUNT_ACCESS_SECURITY' 'DELIVERY_ATTEMPT_OR_INSTRUCTIONS'
 'DELIVERY_DELAY' 'DELIVERY_MISSING_OR_MISDELIVERED'
 'DEVICE_TECHNICAL_SUPPORT' 'DIGITAL_CONTENT' 'GIFT_CARD_PROMOTION'
 'ORDER_STATUS_OR_CANCELLATION' 'OTHER_NON_SUPPORT' 'PAYMENT_BILLING'
 'PRIME_MEMBERSHIP' 'PRODUCT_AVAILABILITY_INFORMATION' 'PRODUCT_PROBLEM'
 'RETURN_REPLACEMENT_REFUND' 'WEBSITE_APP_TECHNICAL']

#### Build the serving retrieval corpus

In [378]:
from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path(
    r"D:\BECAME_DEVELOPER\hiver-sde-ai-agent"
)

CORPUS_DIR = (
    PROJECT_ROOT
    / "backend"
    / "artifacts"
    / "corpus"
)

CORPUS_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# Start from the full AmazonHelp corpus
# ------------------------------------------------------------

serving_corpus = amazon_resolution_corpus.copy()

print(
    "Original AmazonHelp corpus:",
    len(serving_corpus)
)


# ------------------------------------------------------------
# Remove benchmark conversations
# ------------------------------------------------------------

benchmark_ids = set(
    retrieval_benchmark["conversation_id"]
    .astype(str)
)


serving_corpus[
    "conversation_id"
] = (
    serving_corpus[
        "conversation_id"
    ]
    .astype(str)
)


serving_corpus = serving_corpus[
    ~serving_corpus[
        "conversation_id"
    ].isin(
        benchmark_ids
    )
].copy()


print(
    "Leakage-safe corpus:",
    len(serving_corpus)
)


# ------------------------------------------------------------
# Build retrieval text
# ------------------------------------------------------------

serving_corpus[
    "retrieval_text"
] = (
    serving_corpus[
        "conversation_text"
    ]
    .fillna("")
    .astype(str)
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

corpus_path = (
    CORPUS_DIR
    / "amazonhelp_corpus.csv"
)


serving_corpus.to_csv(
    corpus_path,
    index=False
)


print(
    "\nSaved:",
    corpus_path
)

Original AmazonHelp corpus: 82246
Leakage-safe corpus: 81796

Saved: D:\BECAME_DEVELOPER\hiver-sde-ai-agent\backend\artifacts\corpus\amazonhelp_corpus.csv